import { useEffect,useMemo,useState } from 'react';
import { RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { getBusinessAnalytics } from '../services/product';
import { currentBusinessId } from '../services/capabilityWorkflows';
type Row=Record<string,any>;
const labels:Record<string,string>={business_campaign_analytics:'Campaigns',business_engagement_analytics:'Engagement',business_location_analytics:'Locations',business_qr_detail:'QR',business_review_detail:'Reviews',business_benchmark_analytics:'Benchmarks',business_occupancy_analytics:'Occupancy',business_roi_analytics:'ROI',business_visitors_analytics:'Visitors',business_promotion_analytics:'Promotions'};
function list(value:any):Row[]{if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];for(const key of ['rows','items','data','results','locations','detail'])if(Array.isArray(value[key]))return value[key];return[]}
function facts(value:any):[string,string][]{if(!value||typeof value!=='object'||Array.isArray(value))return[];return Object.entries(value).filter(([,v])=>['string','number','boolean'].includes(typeof v)&&v!==null).slice(0,10).map(([k,v])=>[k,String(v)])}
function summarize(row:Row){const preferred=['name','title','location_name','campaign_name','promotion_name','metric','segment'];for(const key of preferred)if(row[key]!=null&&String(row[key]).trim())return String(row[key]);return'Analytics signal'}
export default function Analytics(){const[data,setData]=useState<Record<string,any>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading analytics…');async function load(){setBusy(true);try{const id=await currentBusinessId();setData(await getBusinessAnalytics(id));setMessage('')}catch(e:any){setMessage(e?.message||'Analytics unavailable.')}finally{setBusy(false)}}useEffect(()=>{void load()},[]);const sections=useMemo(()=>Object.entries(data||{}),[data]);return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}><View style={s.hero}><Text style={s.kicker}>ANALYTICS</Text><Text style={s.title}>See what changed and where.</Text><Text style={s.body}>Campaigns, engagement, locations, QR, reviews, occupancy, visitors, ROI, benchmarks and promotions share the same 30-day operating window.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}<View style={s.metrics}><Metric label="Analytics domains" value={sections.length}/><Metric label="Domains with data" value={sections.filter(([,v])=>list(v).length||facts(v).length).length}/></View>{sections.map(([key,value])=>{const rows=list(value),summary=facts(value);return <View key={key} style={s.section}><Text style={s.sectionTitle}>{labels[key]||key.replaceAll('business_','').replaceAll('_',' ')}</Text>{summary.length?<View style={s.card}>{summary.map(([label,val])=><Fact key={label} label={label} value={val}/>)}</View>:null}{rows.length?rows.slice(0,12).map((row,index)=><View key={String(row.id||row.location_id||row.campaign_id||index)} style={s.rowCard}><Text style={s.rowTitle}>{summarize(row)}</Text><View style={s.rowFacts}>{facts(row).slice(0,6).map(([label,val])=><Mini key={label} label={label} value={val}/>)}</View></View>):!summary.length?<View style={s.empty}><Text style={s.meta}>No current {String(labels[key]||key).toLowerCase()} signal in this window.</Text></View>:null}</View>})}</ScrollView>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}function Fact({label,value}:{label:string;value:string}){return <View style={s.fact}><Text style={s.factLabel}>{label.replaceAll('_',' ')}</Text><Text style={s.factValue}>{value}</Text></View>}function Mini({label,value}:{label:string;value:string}){return <View style={s.mini}><Text style={s.miniValue} numberOfLines={1}>{value}</Text><Text style={s.miniLabel} numberOfLines={1}>{label.replaceAll('_',' ')}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:14,backgroundColor:'#f3f6f4',paddingBottom:60},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:28,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},metrics:{flexDirection:'row',gap:8,flexWrap:'wrap'},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},section:{gap:8},sectionTitle:{fontSize:21,fontWeight:'900',color:'#102218',textTransform:'capitalize'},card:{backgroundColor:'#fff',borderRadius:17,padding:14,borderWidth:1,borderColor:'#dbe5de',gap:3},fact:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:5,borderBottomWidth:1,borderBottomColor:'#eef2ef'},factLabel:{fontSize:12,color:'#65756b',textTransform:'capitalize'},factValue:{fontSize:12,fontWeight:'900',color:'#21372a',textAlign:'right'},rowCard:{backgroundColor:'#fff',borderRadius:17,padding:14,borderWidth:1,borderColor:'#dbe5de',gap:8},rowTitle:{fontSize:16,fontWeight:'900',color:'#102218'},rowFacts:{flexDirection:'row',flexWrap:'wrap',gap:7},mini:{backgroundColor:'#edf3ef',borderRadius:11,padding:9,minWidth:90,maxWidth:'48%',flexGrow:1},miniValue:{fontSize:14,fontWeight:'900',color:'#173f2d'},miniLabel:{fontSize:9,fontWeight:'800',color:'#65756b',textTransform:'capitalize'},empty:{backgroundColor:'#eef3f0',borderRadius:14,padding:13}});
