import { Link } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { getBusinessDashboard,getBusinessQrPrograms } from '../services/product';
import { getEnterpriseLocationControls } from '../services/control';

type Row=Record<string,any>;
function list(value:any,keys:string[]=[]):Row[]{if(Array.isArray(value))return value;for(const key of keys)if(Array.isArray(value?.[key]))return value[key];return[]}
function n(value:any){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}
function pct(value:any){const parsed=Number(value);return Number.isFinite(parsed)?`${parsed.toFixed(parsed%1===0?0:1)}%`:'—'}
function idOf(row:Row){return String(row.location_id||row.id||'')}
export default function EnterpriseLocations(){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Enterprise Location portfolio…');
 async function load(){setBusy(true);try{const id=await currentBusinessId();const[dashboard,controls,qr]=await Promise.all([getBusinessDashboard(id),getEnterpriseLocationControls(id),getBusinessQrPrograms(id)]);setData({dashboard,controls,qr});setMessage(controls.partial?'Some live Enterprise Location services are temporarily degraded; available portfolio controls remain active.':'')}catch(e:any){setMessage(e?.message||'Enterprise Location controls are unavailable for this workspace.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const locations=list(data?.dashboard?.locations),configs=list(data?.controls?.configs,['configs','rows','items']),comparison=list(data?.controls?.comparison,['locations','rows','items','comparison']),qrRows=list(data?.qr,['qr_codes','qrs','rows','items']),activeQr=qrRows.filter(row=>row.active!==false).length;
 const comparisonByLocation=useMemo(()=>new Map(comparison.map(row=>[idOf(row),row])),[comparison]);
 const summary=(data?.dashboard?.summary&&typeof data.dashboard.summary==='object')?data.dashboard.summary:{};
 const configuredLimit=n(data?.controls?.portfolio?.location_limit||data?.controls?.portfolio?.max_locations),remainingSlots=configuredLimit>0?Math.max(0,configuredLimit-locations.filter(row=>row.active!==false&&row.is_active!==false).length):'∞';
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.kicker}>ENTERPRISE LOCATION · GROWTH+</Text><Text style={s.title}>One canonical location portfolio.</Text><Text style={s.body}>Operate location identity, QR, reviews, trust, prevention and cross-location intelligence without duplicating the places Consumer discovery and Fleet already use.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Managed locations" value={locations.length}/><Metric label="Location intelligence" value={comparison.length}/><Metric label="Active QR assets" value={activeQr}/><Metric label="Remaining Growth slots" value={remainingSlots}/></View>
  <Section title="Location portfolio" body="Every card resolves to the canonical Business location used by Consumer discovery, QR, trust and operational intelligence.">{locations.length?locations.map((location,index)=>{const id=idOf(location),intel=comparisonByLocation.get(id)||{},config=configs.find(row=>idOf(row)===id),active=location.active!==false&&location.is_active!==false;return <View key={id||String(index)} style={s.card}><View style={s.spread}><View style={{flex:1,gap:3}}><Text style={s.cardTitle}>{String(location.name||location.location_name||'Location')}</Text><Text style={s.meta}>{[location.address,location.city,location.state,location.postal_code].filter(Boolean).join(', ')||'Address unavailable'}</Text></View><Pill label={active?'ACTIVE':'INACTIVE'}/></View><Text style={s.meta}>{config?`Enterprise configuration · ${String(config.role_mode||config.mode||config.status||'configured')}`:'Workspace defaults active'}</Text><View style={s.facts}><Fact label="Intelligence score" value={intel.intelligence_score!=null?Number(intel.intelligence_score).toFixed(1):'—'}/><Fact label="Cleanliness" value={pct(intel.cleanliness_pct)}/><Fact label="Demand signal" value={n(intel.demand_signal).toLocaleString()}/><Fact label="Verifications" value={n(intel.verification_count).toLocaleString()}/><Fact label="Check-ins" value={n(intel.check_ins).toLocaleString()}/><Fact label="Reviews" value={n(intel.reviews).toLocaleString()}/></View><View style={s.links}><Link href="/locations" style={s.link}>Manage location</Link><Link href="/qr-studio" style={s.link}>QR Studio</Link><Link href="/reviews" style={s.link}>Reviews</Link></View></View>}):<View style={s.card}><Text style={s.cardTitle}>No managed locations yet</Text><Text style={s.meta}>Find and claim an existing place or create a genuinely new canonical location.</Text><Link href="/locations" style={s.link}>Manage location</Link></View>}</Section>
  <Section title="Location intelligence" body="Cross-location demand, cleanliness, verification and engagement signals are the Enterprise Location view included with Growth."><View style={s.card}><Fact label="30-day searches" value={n(summary.searches??summary.search_count).toLocaleString()}/><Fact label="30-day location views" value={n(summary.location_views??summary.views).toLocaleString()}/><Fact label="30-day check-ins" value={n(summary.check_ins).toLocaleString()}/><Fact label="30-day reviews" value={n(summary.reviews).toLocaleString()}/><Link href="/intelligence" style={s.primaryLink}>Open Advanced Intelligence</Link></View></Section>
  <Section title="QR & engagement" body="Run location-specific trust/check-in QR assets and Growth engagement against the same location IDs."><View style={s.card}><Text style={s.cardTitle}>{qrRows.length} QR asset{qrRows.length===1?'':'s'} · {activeQr} active</Text><Text style={s.meta}>QR lifecycle, attribution and engagement remain attached to canonical locations.</Text><View style={s.links}><Link href="/qr-studio" style={s.primaryLink}>Open QR Studio</Link><Link href="/engagement" style={s.link}>Campaign engagement</Link></View></View></Section>
  <Section title="Trust & operations" body="Move from location signal to corrective action, proof, reverification, prevention and customer/team communication."><View style={s.card}><Text style={s.cardTitle}>Location operations</Text><Text style={s.meta}>Use specialist workflows to resolve problems at individual locations and measure whether fixes hold.</Text><View style={s.links}><Link href="/trust-operations" style={s.primaryLink}>Trust operations</Link><Link href="/prevention" style={s.link}>Preventive operations</Link><Link href="/notifications" style={s.link}>Notify customers/team</Link></View></View></Section>
  <View style={s.enterprise}><Text style={s.enterpriseKicker}>FULL ENTERPRISE NETWORK AUTHORITY</Text><Text style={s.enterpriseTitle}>Cross-business portfolio controls stay one tap away.</Text><Text style={s.enterpriseBody}>Partner networks, portfolio Fleet operations and funded Enterprise Economy use these same canonical location IDs.</Text><View style={s.links}><Link href="/enterprise" style={s.lightLink}>Open Enterprise portfolio</Link><Link href="/enterprise-economy" style={s.lightLink}>Enterprise Economy</Link></View></View>
 </ScrollView>;
}
function Section({title,body,children}:{title:string;body:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text><Text style={s.meta}>{body}</Text>{children}</View>}
function Metric({label,value}:{label:string;value:string|number}){return <View style={s.metric}><Text style={s.metricValue}>{String(value)}</Text><Text style={s.meta}>{label}</Text></View>}
function Fact({label,value}:{label:string;value:string}){return <View style={s.fact}><Text style={s.meta}>{label}</Text><Text style={s.factValue}>{value}</Text></View>}
function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:14,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:28,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:19,color:'#65756b'},section:{gap:8},sectionTitle:{fontSize:22,fontWeight:'900',color:'#102218'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:10,borderWidth:1,borderColor:'#dbe5de'},spread:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:8},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6,alignSelf:'flex-start'},pillText:{fontSize:10,fontWeight:'900',color:'#31533f'},facts:{backgroundColor:'#f5f8f6',borderRadius:14,padding:11,gap:5},fact:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:3},factValue:{fontWeight:'900',color:'#263a30',textAlign:'right'},links:{flexDirection:'row',flexWrap:'wrap',gap:7},link:{backgroundColor:'#edf3ef',color:'#173f2d',fontWeight:'900',paddingHorizontal:10,paddingVertical:8,borderRadius:999},primaryLink:{backgroundColor:'#173f2d',color:'#fff',fontWeight:'900',paddingHorizontal:11,paddingVertical:9,borderRadius:999},enterprise:{backgroundColor:'#173f2d',borderRadius:18,padding:16,gap:9},enterpriseKicker:{color:'#c8ead7',fontWeight:'900',fontSize:10,letterSpacing:1.2},enterpriseTitle:{color:'#fff',fontSize:20,fontWeight:'900'},enterpriseBody:{color:'#deebe4',fontSize:12,lineHeight:18},lightLink:{backgroundColor:'#f1f7f3',color:'#173f2d',fontWeight:'900',paddingHorizontal:12,paddingVertical:9,borderRadius:999}});
