import { Link,useLocalSearchParams } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { BusinessCard,BusinessHero,SectionHeader,businessColors } from '../components/BusinessOS';
import { currentBusinessId,searchContributors } from '../services/capabilityWorkflows';
import { getEnterpriseLocationControls,listEnterpriseLocationStaff,manageEnterpriseLocationStaff,updateEnterpriseLocationConfig } from '../services/control';

type Row=Record<string,any>;
const FEATURES=[['qr','QR'],['fleet','Fleet'],['games','Games'],['photos','Photos'],['contests','Contests'],['journeys','Journeys'],['missions','Missions'],['campaigns','Campaigns'],['challenges','Challenges'],['intelligence','Intelligence'],['live_network','Live Network'],['local_events','Local events'],['notifications','Notifications'],['custom_metrics','Custom metrics'],['shared_learning','Shared learning'],['local_promotions','Local promotions']] as const;
const ROLES=['employee','manager','admin','owner'] as const;
function list(value:any):Row[]{if(Array.isArray(value))return value;if(Array.isArray(value?.rows))return value.rows;if(Array.isArray(value?.items))return value.items;return[]}
function idOf(row:Row){return String(row.location_id||row.id||'')}

export default function EnterpriseLocationAdmin(){
 const params=useLocalSearchParams<{locationId?:string}>();
 const[businessId,setBusinessId]=useState(''),[configs,setConfigs]=useState<Row[]>([]),[locationId,setLocationId]=useState(''),[featureState,setFeatureState]=useState<Record<string,boolean>>({});
 const[staff,setStaff]=useState<Row[]>([]),[query,setQuery]=useState(''),[candidates,setCandidates]=useState<Row[]>([]),[selectedUser,setSelectedUser]=useState<Row|null>(null),[role,setRole]=useState<(typeof ROLES)[number]>('employee');
 const[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Enterprise location administration…');

 async function load(preferred?:string){
  setBusy(true);
  try{
   const id=businessId||await currentBusinessId();setBusinessId(id);
   const controls=await getEnterpriseLocationControls(id);
   const rows=list(controls.configs);setConfigs(rows);
   const next=preferred||String(params.locationId||'')||locationId||idOf(rows[0]||{});setLocationId(next);
   if(next){
    const configRow=rows.find(row=>idOf(row)===next);const raw=(configRow?.config&&typeof configRow.config==='object')?configRow.config:{};
    setFeatureState(Object.fromEntries(FEATURES.map(([key])=>[key,raw[key]!==false])));
    setStaff(list(await listEnterpriseLocationStaff(id,next)));
   }else{setStaff([]);setFeatureState({})}
   setMessage(controls.partial?'Some Enterprise telemetry is degraded. Available controls remain active.':'');
  }catch(e:any){setMessage(e?.message||'Enterprise location administration is unavailable.')}finally{setBusy(false)}
 }
 useEffect(()=>{void load()},[]);
 const selectedConfig=useMemo(()=>configs.find(row=>idOf(row)===locationId)||null,[configs,locationId]);

 async function saveConfig(){if(!locationId)return;setBusy(true);try{await updateEnterpriseLocationConfig(businessId,locationId,featureState);setMessage('Enterprise location capabilities updated.');await load(locationId)}catch(e:any){setMessage(e?.message||'Location configuration could not be saved.')}finally{setBusy(false)}}
 async function search(){const value=query.trim();if(!value){setCandidates([]);return}setBusy(true);try{const rows=await searchContributors(value);setCandidates(Array.isArray(rows)?rows:[]);setMessage('')}catch(e:any){setMessage(e?.message||'People search failed.')}finally{setBusy(false)}}
 async function assign(){if(!locationId||!selectedUser)return;const userId=String(selectedUser.user_id||selectedUser.id||'');if(!userId)return;const existing=staff.some(row=>String(row.user_id)===userId);setBusy(true);try{await manageEnterpriseLocationStaff(businessId,locationId,userId,role,existing?'update':'add',{});setMessage(existing?'Location staff role updated.':'Location staff assignment added.');setSelectedUser(null);setQuery('');setCandidates([]);await load(locationId)}catch(e:any){setMessage(e?.message||'Location staff assignment failed.')}finally{setBusy(false)}}
 async function remove(row:Row){setBusy(true);try{await manageEnterpriseLocationStaff(businessId,locationId,String(row.user_id),String(row.role||'employee'),'remove',{});setMessage('Location staff assignment removed.');await load(locationId)}catch(e:any){setMessage(e?.message||'Location staff could not be removed.')}finally{setBusy(false)}}

 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>load(locationId)}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}>
  <BusinessHero eyebrow="ENTERPRISE LOCATION ADMIN" title="Put the right controls with the right location." body="Configure location-level Enterprise capabilities and assign staff authority without changing Business-wide roles."/>
  {message?<View style={s.message}><Text accessibilityLiveRegion="polite" style={s.messageText}>{message}</Text></View>:null}
  <BusinessCard><SectionHeader title="Choose a managed location" body="Only direct active Business locations are eligible for location administration."/><View style={s.chips}>{configs.map(row=><Chip key={idOf(row)} label={String(row.location_name||'Location')} active={idOf(row)===locationId} onPress={()=>void load(idOf(row))}/>)}</View>{!configs.length?<Link href="/locations" style={s.link}>Manage locations →</Link>:null}</BusinessCard>
  {locationId?<BusinessCard><SectionHeader title="Location capability profile" body={selectedConfig?String(selectedConfig.location_name||'Location')+' · '+String(Number(selectedConfig.staff_count||0))+' assigned staff':'Choose the Enterprise features this location can use.'}/><View style={s.featureGrid}>{FEATURES.map(([key,label])=><Pressable key={key} accessibilityRole="switch" accessibilityState={{checked:featureState[key]!==false}} onPress={()=>setFeatureState(current=>({...current,[key]:current[key]===false}))} style={[s.feature,featureState[key]!==false&&s.featureOn]}><View style={[s.dot,featureState[key]!==false&&s.dotOn]}/><Text style={[s.featureText,featureState[key]!==false&&s.featureTextOn]}>{label}</Text></Pressable>)}</View><Pressable disabled={busy} onPress={()=>void saveConfig()} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>{busy?'Saving…':'Save location capabilities'}</Text></Pressable></BusinessCard>:null}
  {locationId?<View style={s.section}><SectionHeader title="Location staff" body="Location roles are scoped below Business membership and are capped by the Enterprise location contract."/>{staff.length?staff.map(row=><BusinessCard key={String(row.id||row.user_id)}><View style={s.spread}><View style={{flex:1}}><Text style={s.staffName}>{String(row.display_name||row.username||row.user_id)}</Text><Text style={s.meta}>{String(row.role||'employee').toUpperCase()}</Text></View><Text style={s.roleBadge}>{String(row.role||'employee').toUpperCase()}</Text></View><Text style={s.capabilities}>{Object.entries(row.effective_capabilities||{}).filter(([,v])=>v===true).map(([k])=>k.replaceAll('_',' ')).join(' · ')||'Default role capabilities'}</Text><View style={s.actions}><Pressable onPress={()=>{setSelectedUser({id:row.user_id,username:row.username,display_name:row.display_name});setRole((ROLES.includes(row.role as any)?row.role:'employee') as any)}} style={s.secondary}><Text style={s.secondaryText}>Change role</Text></Pressable><Pressable disabled={busy} onPress={()=>void remove(row)} style={s.danger}><Text style={s.dangerText}>Remove</Text></Pressable></View></BusinessCard>):<BusinessCard><Text style={s.meta}>No location-specific staff assignments yet.</Text></BusinessCard>}</View>:null}
  {locationId?<BusinessCard><SectionHeader title={selectedUser?'Assign location role':'Find a Business member'} body="Search by name or username, choose the person, then select a valid Enterprise location role."/>{!selectedUser?<><View style={s.searchRow}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} placeholder="Search people…" placeholderTextColor="#829188" style={[s.input,{flex:1}]}/><Pressable disabled={busy||!query.trim()} onPress={()=>void search()} style={[s.secondary,(busy||!query.trim())&&s.disabled]}><Text style={s.secondaryText}>Search</Text></Pressable></View><View style={s.results}>{candidates.slice(0,12).map(row=><Pressable key={String(row.id||row.user_id)} onPress={()=>setSelectedUser(row)} style={s.person}><Text style={s.staffName}>{String(row.display_name||row.username||'Kleenest user')}</Text><Text style={s.meta}>@{String(row.username||row.id||row.user_id)}</Text></Pressable>)}</View></>:<><View style={s.selectedPerson}><Text style={s.staffName}>{String(selectedUser.display_name||selectedUser.username||selectedUser.id)}</Text><Pressable onPress={()=>setSelectedUser(null)}><Text style={s.link}>Change person</Text></Pressable></View><Text style={s.label}>LOCATION ROLE</Text><View style={s.chips}>{ROLES.map(value=><Chip key={value} label={value} active={role===value} onPress={()=>setRole(value)}/>)}</View><Text style={s.meta}>Owner requires Business owner membership; admin requires owner/admin; manager requires manager-or-higher.</Text><Pressable disabled={busy} onPress={()=>void assign()} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>Save location role</Text></Pressable></>}</BusinessCard>:null}
  <View style={s.bottomLinks}><Link href="/enterprise-locations" style={s.link}>← Enterprise Locations</Link><Link href="/members" style={s.link}>Business people & roles →</Link></View>
 </ScrollView>
}

function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
const s=StyleSheet.create({
 page:{padding:18,gap:14,backgroundColor:businessColors.paper,paddingBottom:70},message:{backgroundColor:'#eef5f0',borderRadius:14,padding:12,borderWidth:1,borderColor:businessColors.border},messageText:{fontSize:12,fontWeight:'800',color:businessColors.green},
 chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:11,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:businessColors.green},chipText:{fontWeight:'800',fontSize:11,color:'#315440',textTransform:'capitalize'},chipTextOn:{color:'#fff'},
 featureGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},feature:{flexBasis:145,flexGrow:1,minWidth:140,borderWidth:1,borderColor:businessColors.border,borderRadius:14,padding:11,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#fafcfb'},featureOn:{backgroundColor:'#edf7f1',borderColor:'#b9d8c5'},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#b6c0ba'},dotOn:{backgroundColor:businessColors.good},featureText:{fontSize:11,fontWeight:'800',color:businessColors.muted},featureTextOn:{color:businessColors.green},
 primary:{backgroundColor:businessColors.green,borderRadius:12,paddingHorizontal:13,paddingVertical:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#edf3ef',borderRadius:12,paddingHorizontal:12,paddingVertical:10},secondaryText:{color:businessColors.green,fontWeight:'900'},danger:{backgroundColor:'#fff0f0',borderRadius:12,paddingHorizontal:12,paddingVertical:10},dangerText:{color:businessColors.danger,fontWeight:'900'},disabled:{opacity:.45},
 section:{gap:8},spread:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:8},staffName:{fontSize:15,fontWeight:'900',color:businessColors.ink},meta:{fontSize:12,lineHeight:18,color:businessColors.muted},roleBadge:{fontSize:9,fontWeight:'900',color:businessColors.green,backgroundColor:'#e3efe7',paddingHorizontal:8,paddingVertical:5,borderRadius:999},capabilities:{fontSize:10,lineHeight:16,color:businessColors.muted,textTransform:'capitalize'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},
 searchRow:{flexDirection:'row',gap:8},input:{borderWidth:1,borderColor:businessColors.border,borderRadius:12,paddingHorizontal:12,paddingVertical:11,backgroundColor:'#fafcfb',color:businessColors.ink},results:{gap:7},person:{backgroundColor:'#f4f7f5',borderRadius:13,padding:11,borderWidth:1,borderColor:'#dfe7e1'},selectedPerson:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,backgroundColor:'#f4f7f5',borderRadius:13,padding:12},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:businessColors.green},link:{fontWeight:'900',color:businessColors.green},bottomLinks:{flexDirection:'row',justifyContent:'space-between',gap:10,flexWrap:'wrap'}
});