import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,Share,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { buildGovernanceReport,createWeeklyBusinessReportSchedule,deleteReportingSchedule,listReportingSchedules,runDueReportingSchedules,setReportingScheduleEnabled } from '../services/governance';
type Row=Record<string,any>;
function pairs(value:any){if(!value||typeof value!=='object'||Array.isArray(value))return[] as [string,string][];return Object.entries(value).filter(([,v])=>['string','number','boolean'].includes(typeof v)).slice(0,12).map(([k,v])=>[k,String(v)] as [string,string]);}
export default function Governance(){
 const[businessId,setBusinessId]=useState(''),[schedules,setSchedules]=useState<Row[]>([]),[report,setReport]=useState<any>(null),[name,setName]=useState('Weekly Business Report'),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading governance…');
 async function load(){setBusy(true);try{const id=businessId||await currentBusinessId();setBusinessId(id);setSchedules(await listReportingSchedules(id));setMessage('')}catch(e:any){setMessage(e?.message||'Governance unavailable.')}finally{setBusy(false)}}useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,ok:string,reload=true){setBusy(true);try{await fn();setMessage(ok);if(reload)await load()}catch(e:any){setMessage(e?.message||'Governance action failed.')}finally{setBusy(false)}}
 async function build(){setBusy(true);try{const result=await buildGovernanceReport(businessId,30);setReport(result);setMessage('Report refreshed for the last 30 days.')}catch(e:any){setMessage(e?.message||'Report could not be built.')}finally{setBusy(false)}}
 async function exportReport(){if(!report)return;const lines=['Kleenest Business Governance Report','Last 30 days','',...pairs(report).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`)];await Share.share({title:'Kleenest Business Report',message:lines.join('\n')});}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><View style={s.hero}><Text style={s.kicker}>GOVERNANCE</Text><Text style={s.title}>Reports, schedules and operating accountability.</Text><Text style={s.body}>Build a Business Report, Run due schedules, and Export a concise operating snapshot without exposing raw backend records.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}<View style={s.card}><Text style={s.cardTitle}>30-day Business Report</Text><Text style={s.meta}>Generate the current governance payload for this Business workspace.</Text><View style={s.actions}><Action label="Build Report" disabled={busy} onPress={build}/><Action label="Export" quiet disabled={busy||!report} onPress={exportReport}/><Action label="Run due" quiet disabled={busy} onPress={()=>run(runDueReportingSchedules,'Due reporting schedules executed.',false)}/></View>{report?<View style={s.report}>{pairs(report).length?pairs(report).map(([key,value])=><View key={key} style={s.row}><Text style={s.rowLabel}>{key.replaceAll('_',' ')}</Text><Text style={s.rowValue}>{value}</Text></View>):<Text style={s.meta}>Report generated. No scalar summary fields were returned.</Text>}</View>:null}</View><View style={s.card}><Text style={s.cardTitle}>Create weekly schedule</Text><TextInput style={s.input} color="#132b21" placeholderTextColor="#78877f" value={name} onChangeText={setName} placeholder="Schedule name"/><Action label="Create weekly Report schedule" disabled={busy||!name.trim()} onPress={()=>run(()=>createWeeklyBusinessReportSchedule(businessId,name.trim()),'Weekly report schedule created.')}/></View><Text style={s.section}>Reporting schedules</Text>{schedules.length?schedules.map(row=>{const id=String(row.id||'');const enabled=row.enabled!==false;return <View key={id} style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.cardTitle}>{String(row.name||'Business Report')}</Text><Text style={s.meta}>{String(row.cadence||'weekly')} · {String(row.timezone||'America/Chicago')} · {enabled?'ACTIVE':'PAUSED'}</Text></View><View style={[s.pill,!enabled&&s.pillOff]}><Text style={s.pillText}>{enabled?'ACTIVE':'PAUSED'}</Text></View></View><View style={s.actions}><Action label={enabled?'Pause':'Enable'} quiet disabled={busy} onPress={()=>run(()=>setReportingScheduleEnabled(id,!enabled),enabled?'Schedule paused.':'Schedule enabled.')}/><Action label="Delete" danger disabled={busy} onPress={()=>run(()=>deleteReportingSchedule(id),'Schedule deleted.')}/></View></View>}):<View style={s.card}><Text style={s.meta}>No reporting schedules yet.</Text></View>}</ScrollView>;
}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:10,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#26342c',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8dfd0'},title:{fontSize:27,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#e0e9e3'},message:{fontWeight:'700',color:'#596b61'},section:{fontSize:21,fontWeight:'900',color:'#102218',marginTop:4},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:10,borderWidth:1,borderColor:'#dbe5de'},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999},actionText:{color:'#fff',fontWeight:'900'},actionQuiet:{backgroundColor:'#edf3ef'},actionQuietText:{color:'#173f2d'},actionDanger:{backgroundColor:'#8b3434'},disabled:{opacity:.45},report:{borderTopWidth:1,borderTopColor:'#edf0ee',paddingTop:8,gap:6},row:{flexDirection:'row',justifyContent:'space-between',gap:10},rowLabel:{flex:1,color:'#65756b',textTransform:'capitalize'},rowValue:{fontWeight:'900',color:'#173f2d'},top:{flexDirection:'row',alignItems:'center',gap:8},pill:{backgroundColor:'#e4f3ea',borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillOff:{backgroundColor:'#f0efeb'},pillText:{fontSize:10,fontWeight:'900',color:'#31533f'}});
