import { Link } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { completeIntelligenceAction,currentBusinessId,executeIntelligenceAction,listBusinessIntelligenceActions } from '../services/capabilityWorkflows';
import { buildBusinessReportPayload,getGrowthIntelligenceBundle,type IntelligenceSection } from '../services/intelligence';

type Row=Record<string,any>;
function count(value:any){if(Array.isArray(value))return value.length;if(value&&typeof value==='object')return Object.keys(value).length;return value==null?0:1}
function title(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function scalar(value:any){if(value==null)return null;if(typeof value==='number')return Number.isInteger(value)?value.toLocaleString():value.toFixed(2);if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='string')return value.length>100?`${value.slice(0,97)}…`:value;return null}
function rows(value:any):Row[]{if(Array.isArray(value))return value.filter(item=>item&&typeof item==='object').slice(0,8);if(value&&typeof value==='object'){for(const key of['items','rows','recommendations','locations','history','results','queue'])if(Array.isArray(value[key]))return value[key].filter((item:any)=>item&&typeof item==='object').slice(0,8)}return[]}
function primary(row:Row,fallback:string){for(const key of['title','name','location_name','recommendation','action','status','metric_name']){const value=scalar(row[key]);if(value)return value}return fallback}
function details(row:Row){const parts:string[]=[];for(const[key,value]of Object.entries(row)){if(['id','business_id','location_id','title','name','location_name'].includes(key))continue;const text=scalar(value);if(text){parts.push(`${title(key)}: ${text}`);if(parts.length===3)break}}return parts.join(' · ')}
export default function Intelligence(){
 const[businessId,setBusinessId]=useState(''),[bundle,setBundle]=useState<any>(null),[actions,setActions]=useState<Row[]>([]),[report,setReport]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Advanced Intelligence…');
 async function load(){setBusy(true);try{const id=businessId||await currentBusinessId();setBusinessId(id);const[nextBundle,nextActions]=await Promise.all([getGrowthIntelligenceBundle(id),listBusinessIntelligenceActions(id)]);setBundle(nextBundle);setActions(nextActions);setMessage(nextBundle.errors.length?`${nextBundle.errors.length} intelligence section${nextBundle.errors.length===1?' is':'s are'} temporarily degraded; available sections remain active.`:'')}catch(e:any){setMessage(e?.message||'Business intelligence is unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const open=useMemo(()=>actions.filter(row=>!['completed','dismissed'].includes(String(row.status||''))),[actions]);
 async function run(row:Row,mode:'execute'|'complete'){setBusy(true);try{if(mode==='execute')await executeIntelligenceAction(String(row.id));else await completeIntelligenceAction(String(row.id),{source:'business-mobile'});setMessage(mode==='execute'?'Action executed through the canonical intelligence gateway.':'Action marked complete.');await load()}catch(e:any){setMessage(e?.message||'Intelligence action failed.')}finally{setBusy(false)}}
 async function buildReport(){if(!businessId)return;setBusy(true);try{setReport(await buildBusinessReportPayload(businessId,30));setMessage('Canonical 30-day Business report assembled.')}catch(e:any){setMessage(e?.message||'Business report could not be built.')}finally{setBusy(false)}}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.kicker}>ADVANCED INTELLIGENCE · GROWTH+</Text><Text style={s.title}>Decide what to improve next.</Text><Text style={s.body}>Canonical growth, ROI, benchmark, operations, trust and progression signals are composed here without creating a parallel metrics engine.</Text><Link href="/assistant" style={s.aiLink}>Ask Kleenest AI about this business</Link></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Open actions" value={open.length}/><Metric label="Growth signals" value={count(bundle?.growth?.data)}/><Metric label="Assets" value={count(bundle?.assets?.data)}/><Metric label="Benchmarks" value={count(bundle?.benchmarks?.data)}/><Metric label="Recommendations" value={count(bundle?.recommendations?.data)}/></View>
  <SummarySection title="Growth cockpit" section={bundle?.cockpit}/><SummarySection title="ROI & returns" section={bundle?.roi}/><SummarySection title="Location intelligence" section={bundle?.locations}/><SummarySection title="Recommended actions" section={bundle?.recommendations}/><SummarySection title="Reverification queue" section={bundle?.reverification}/><SummarySection title="Optimization history" section={bundle?.history}/><SummarySection title="Operations inventory" section={bundle?.operations}/>
  <View style={s.sectionHead}><View><Text style={s.kickerDark}>CALLABLE ACTIONS</Text><Text style={s.section}>Recommended actions</Text></View><Text style={s.meta}>{open.length} open</Text></View>{open.length?open.map(row=><View key={String(row.id)} style={s.card}><Text style={s.cardTitle}>{String(row.title||row.label||row.action_type||'Business intelligence action')}</Text><Text style={s.meta}>{String(row.description||row.reason||row.summary||'Kleenest has linked this signal to a callable Business action.')}</Text><View style={s.row}><Pill label={String(row.status||'open')}/><Pill label={String(row.priority||row.severity||'normal')}/></View><View style={s.row}><Action label="Execute" disabled={busy} onPress={()=>run(row,'execute')}/><Action quiet label="Mark complete" disabled={busy} onPress={()=>run(row,'complete')}/></View></View>):<View style={s.card}><Text style={s.cardTitle}>No open intelligence actions</Text><Text style={s.meta}>New canonical recommendations will appear here as the network produces them.</Text></View>}
  <View style={s.card}><Text style={s.section}>Reporting</Text><Text style={s.meta}>Build the canonical 30-day Business reporting payload for review and scheduled governance workflows.</Text><Action label="Build 30-day report" disabled={busy||!businessId} onPress={buildReport}/>{report?<View style={s.report}><Text style={s.reportTitle}>Report ready</Text><Text style={s.meta}>{Object.keys(report).length} reporting sections assembled from canonical Business data.</Text>{Object.entries(report).filter(([,value])=>['string','number','boolean'].includes(typeof value)).slice(0,8).map(([key,value])=><View key={key} style={s.factRow}><Text style={s.meta}>{title(key)}</Text><Text style={s.factValue}>{String(value)}</Text></View>)}</View>:null}</View>
 </ScrollView>}
function SummarySection({title:heading,section}:{title:string;section:IntelligenceSection|undefined}){if(!section)return null;if(section.error)return <View style={s.card}><Text style={s.section}>{heading}</Text><Text style={s.error}>{section.error}</Text></View>;const list=rows(section.data),object=section.data&&typeof section.data==='object'&&!Array.isArray(section.data)?section.data as Row:null;return <View style={s.card}><Text style={s.section}>{heading}</Text>{list.length?list.map((row,index)=><View key={String(row.id||row.location_id||index)} style={[s.summaryRow,index>0&&s.summaryBorder]}><Text style={s.cardTitle}>{primary(row,`${heading} item ${index+1}`)}</Text>{details(row)?<Text style={s.meta}>{details(row)}</Text>:null}</View>):object?<KeyFacts value={object}/>:<Text style={s.meta}>No current data in this window.</Text>}</View>}
function KeyFacts({value}:{value:Row}){const facts=Object.entries(value).flatMap(([key,item])=>{const text=scalar(item);return text?[[key,text] as const]:[]}).slice(0,10);return facts.length?<View style={{gap:6}}>{facts.map(([key,item])=><View key={key} style={s.factRow}><Text style={s.meta}>{title(key)}</Text><Text style={s.factValue}>{item}</Text></View>)}</View>:<Text style={s.meta}>Structured intelligence is available, with no scalar summary fields in this view.</Text>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label.replaceAll('_',' ')}</Text></View>}function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:11,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:8},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},kickerDark:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#547060'},title:{fontSize:28,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},aiLink:{alignSelf:'flex-start',backgroundColor:'#f1f7f3',color:'#173f2d',fontWeight:'900',paddingHorizontal:13,paddingVertical:10,borderRadius:999},message:{fontWeight:'700',color:'#596b61'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'30%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:8},section:{fontSize:20,fontWeight:'900',color:'#102218'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},cardTitle:{fontSize:15,fontWeight:'900',color:'#102218'},summaryRow:{gap:3,paddingTop:3},summaryBorder:{borderTopWidth:1,borderTopColor:'#edf1ee',paddingTop:9},row:{flexDirection:'row',flexWrap:'wrap',gap:7,alignItems:'center'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillText:{fontSize:10,fontWeight:'900',color:'#31533f',textTransform:'capitalize'},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},actionQuiet:{backgroundColor:'#edf3ef'},actionText:{fontWeight:'900',color:'#fff'},actionQuietText:{color:'#173f2d'},disabled:{opacity:.45},error:{color:'#9b2c2c'},report:{backgroundColor:'#edf4ef',borderRadius:14,padding:12,gap:6},reportTitle:{fontWeight:'900',color:'#173f2d'},factRow:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingVertical:3},factValue:{fontSize:12,fontWeight:'900',color:'#26372e',textAlign:'right',maxWidth:'55%'}});
