import { useCallback,useEffect,useState } from 'react';
import { AppState,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { configureLiveNetworkGeofence,disableLiveNetwork,ensureLiveNetworkGeofences,getLiveNetworkStatus,listLiveNetworkManifest,registerLiveNetworkPush,requestLiveNetworkBackgroundPermission,requestLiveNetworkForegroundPermission,startLiveNetworkGeofencing,type ManifestRow } from '../services/liveNetwork';
import { listLiveNetworkMotifs,subscribeLiveNetworkMotifs,type LiveNetworkMotif } from '../services/liveNetworkMotifs';

type Status=Awaited<ReturnType<typeof getLiveNetworkStatus>>;
export default function BusinessLiveNetwork(){
 const[businessId,setBusinessId]=useState(''),[status,setStatus]=useState<Status|null>(null),[manifest,setManifest]=useState<ManifestRow[]>([]),[motifs,setMotifs]=useState<LiveNetworkMotif[]>([]),[radius,setRadius]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState('Loading Live Network…'),[error,setError]=useState(''),[lastLiveAt,setLastLiveAt]=useState<string|null>(null);
 const load=useCallback(async()=>{const id=businessId||await currentBusinessId();if(!businessId)setBusinessId(id);const[nextStatus,nextManifest,nextMotifs]=await Promise.all([getLiveNetworkStatus(),listLiveNetworkManifest(id),listLiveNetworkMotifs(id,60).catch(()=>[])]);setStatus(nextStatus);setManifest(nextManifest);setMotifs(nextMotifs);setRadius(current=>Object.fromEntries(nextManifest.map(row=>[row.geofence_id,current[row.geofence_id]??String(row.radius_meters??150)])));setMessage('');},[businessId]);
 useEffect(()=>{setBusy(true);load().catch(c=>setError(text(c))).finally(()=>setBusy(false));},[load]);
 useEffect(()=>{if(!businessId)return;return subscribeLiveNetworkMotifs(businessId,()=>{setLastLiveAt(new Date().toISOString());void listLiveNetworkMotifs(businessId,60).then(setMotifs).catch(()=>{});});},[businessId]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active')void load().catch(()=>{});});return()=>sub.remove();},[load]);
 async function reload(){setRefreshing(true);setError('');try{await load();}catch(c){setError(text(c));}finally{setRefreshing(false)}}
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError('');try{await action();setMessage(success);await load();}catch(c){setError(text(c));}finally{setBusy(false)}}
 async function requestForeground(){await run(requestLiveNetworkForegroundPermission,'Foreground location is ready. Background permission is a separate step.');}
 async function requestBackground(){setMessage('Android may open App settings. Allow background location there, then return to Kleenest Business; this screen will refresh automatically.');await run(requestLiveNetworkBackgroundPermission,'Background location is ready. You can now Enable Live Network.');}
 async function start(){await run(async()=>{const result=await startLiveNetworkGeofencing(businessId);return result;},'Live Network is enabled on this device.');}
 async function stop(){await run(disableLiveNetwork,'Live Network geofencing is stopped on this device.');}
 async function push(){await run(registerLiveNetworkPush,'Live Network push delivery is registered for this device.');}
 async function provision(){await run(()=>ensureLiveNetworkGeofences(businessId),'Canonical Business locations are synchronized to Live Network geofences.');}
 async function saveGeofence(item:ManifestRow){const value=Number(radius[item.geofence_id]??item.radius_meters);if(!Number.isFinite(value)||value<50||value>1000){setError('Geofence radius must be between 50 and 1000 meters.');return;}await run(()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:Math.round(value),notificationEnabled:item.notification_enabled,active:true}),'Geofence configuration saved.');}
 const foreground=status?.foreground==='granted',background=status?.background==='granted',notifications=status?.notifications==='granted',active=Boolean(status?.registered),services=status?.services!==false;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.hero}><Text style={s.eyebrow}>LIVE NETWORK</Text><Text style={s.title}>Geofences + realtime operating motifs</Text><Text style={s.body}>Traffic momentum, quality drift, occupancy pressure and operational patterns stay connected to the same canonical locations used by Consumer and Fleet.</Text></View>
  {error?<View style={s.errorCard}><Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text></View>:null}{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Device" value={active?'Running':'Off'}/><Metric label="Geofences" value={String(manifest.length)}/><Metric label="Active motifs" value={String(motifs.filter(item=>item.severity!=='quiet').length)}/><Metric label="Realtime" value={lastLiveAt?'Updated':'Listening'}/></View>
  <View style={s.card}><Text style={s.kicker}>DEVICE CONTROLS</Text><Text style={s.cardTitle}>Permission & delivery state</Text><Status label="Location services" ready={services}/><Status label="Foreground location" ready={foreground}/><Status label="Background location" ready={background}/><Status label="Notifications" ready={notifications}/><Status label="Geofence task" ready={active}/><Text style={s.meta}>Android background location is intentionally requested separately so the app does not chain into system Settings while another permission action is still running.</Text><View style={s.actions}>{!foreground?<Action label="Allow foreground location" disabled={busy} onPress={requestForeground}/>:null}{foreground&&!background?<Action label="Allow background location" disabled={busy} onPress={requestBackground}/>:null}{foreground&&background&&!active?<Action label="Enable Live Network" disabled={busy||!services} onPress={start}/>:null}{active?<Action label="Disable Live Network" danger disabled={busy} onPress={stop}/>:null}<Action label={notifications?'Register push again':'Enable push alerts'} quiet disabled={busy} onPress={push}/></View></View>
  <View style={s.card}><Text style={s.kicker}>REALTIME ANALYSIS · LAST 60 MIN</Text><Text style={s.cardTitle}>Business motifs</Text><Text style={s.meta}>These signals summarize canonical Live Network events without exposing raw user movement.</Text></View>
  {motifs.length?motifs.map(item=><MotifCard key={item.motif_key} item={item}/>):<View style={s.card}><Text style={s.meta}>No active motifs in the last 60 minutes. Realtime listening remains connected.</Text></View>}
  <View style={s.card}><Text style={s.kicker}>LOCATION COVERAGE</Text><Text style={s.cardTitle}>Canonical geofences</Text><Text style={s.meta}>Synchronize Business locations with valid coordinates, then tune each geofence between 50 and 1000 meters.</Text><Action label="Synchronize business locations" quiet disabled={busy} onPress={provision}/></View>
  {manifest.map(item=><View key={item.geofence_id} style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.cardTitle}>{item.location_name||'Business location'}</Text><Text style={s.meta}>{[item.address,item.city,item.state].filter(Boolean).join(', ')||'Canonical location'}</Text></View><View style={s.pill}><Text style={s.pillText}>{item.active?'ACTIVE':'OFF'}</Text></View></View><Text style={s.label}>Radius meters</Text><TextInput color="#132b21" placeholderTextColor="#78877f" keyboardType="number-pad" style={s.input} value={radius[item.geofence_id]??String(item.radius_meters)} onChangeText={value=>setRadius(current=>({...current,[item.geofence_id]:value}))}/><View style={s.actions}><Action label="Save radius" quiet disabled={busy} onPress={()=>saveGeofence(item)}/><Action label={item.notification_enabled?'Mute geofence alerts':'Enable geofence alerts'} quiet disabled={busy} onPress={()=>run(()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:item.radius_meters,notificationEnabled:!item.notification_enabled,active:true}),'Geofence notification preference updated.')}/></View></View>)}
  <View style={s.card}><Text style={s.kicker}>PRIVACY + SAFETY</Text><Text style={s.cardTitle}>Scoped operational intelligence</Text><Text style={s.meta}>Live Network does not request microphone or overlay permission. Background location is used for enabled geofence operations, never as an automatic sponsored-targeting source.</Text></View>
 </ScrollView>;
}
function text(c:unknown){return c instanceof Error?c.message:String(c||'Live Network action failed.');}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
function Status({label,ready}:{label:string;ready:boolean}){return <View style={s.status}><Text style={s.meta}>{label}</Text><Text style={[s.statusValue,ready?s.good:s.warn]}>{ready?'READY':'NEEDS ACTION'}</Text></View>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
function MotifCard({item}:{item:LiveNetworkMotif}){const e=item.evidence||{};return <View style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.cardTitle}>{item.label}</Text><Text style={s.meta}>{motifDetail(item,e)}</Text></View><View style={s.pill}><Text style={s.pillText}>{item.severity.toUpperCase()}</Text></View></View><Text style={s.meta}>{item.observed_count} signals · {Math.round(item.confidence*100)}% confidence{item.last_seen_at?` · ${format(item.last_seen_at)}`:''}</Text></View>}
function motifDetail(item:LiveNetworkMotif,e:Record<string,unknown>){switch(item.motif_key){case'network_momentum':return `${num(e.routes)} route intents are contributing to the current demand pattern.`;case'geofence_flow':return `${num(e.enters)} enters · ${num(e.exits)} exits · ${num(e.dwells)} dwell observations.`;case'occupancy_pressure':return `${pct(e.occupancy_ratio)} occupancy · ${num(e.queue_avg,1)} avg queue · ${num(e.wait_minutes_avg,1)} min wait.`;case'quality_drift':return `Cleanliness ${num(e.cleanliness_avg,1)} · safety ${num(e.safety_avg,1)} · availability ${num(e.availability_avg,1)}.`;case'fleet_pressure':return `${num(e.operational_events)} Fleet events · ${num(e.open_alerts)} open alerts.`;default:return `${item.observed_count} canonical signals contributed to this motif.`;}}
function num(value:unknown,digits=0){const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):'—'}function pct(value:unknown){const n=Number(value);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}function format(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?'recently':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
const s=StyleSheet.create({page:{padding:18,gap:10,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},errorCard:{backgroundColor:'#fae7e7',borderRadius:14,padding:12},error:{fontWeight:'800',color:'#8f2f2f'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:21,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#547060'},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},status:{flexDirection:'row',justifyContent:'space-between',gap:10,borderBottomWidth:1,borderBottomColor:'#edf0ee',paddingBottom:7},statusValue:{fontSize:11,fontWeight:'900'},good:{color:'#226342'},warn:{color:'#8b5b24'},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999},actionText:{color:'#fff',fontWeight:'900'},actionQuiet:{backgroundColor:'#edf3ef'},actionQuietText:{color:'#173f2d'},actionDanger:{backgroundColor:'#8b3434'},disabled:{opacity:.45},top:{flexDirection:'row',alignItems:'flex-start',gap:8},pill:{backgroundColor:'#edf3ef',paddingHorizontal:9,paddingVertical:6,borderRadius:999},pillText:{fontSize:10,fontWeight:'900',color:'#31533f'},label:{fontSize:12,fontWeight:'900',color:'#365245'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'}});
