import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentBusinessId,sendBusinessNotification } from '../services/capabilityWorkflows';
import { configureLiveNetworkGeofence,disableLiveNetwork,enableLiveNetwork,ensureLiveNetworkGeofences,getLiveNetworkStatus,listLiveNetworkManifest,registerLiveNetworkPush,type ManifestRow } from '../services/liveNetwork';
import { listLiveNetworkMotifs,subscribeLiveNetworkMotifs,type LiveNetworkMotif } from '../services/liveNetworkMotifs';

type Status=Awaited<ReturnType<typeof getLiveNetworkStatus>>;
export default function BusinessLiveNetwork(){
 const[businessId,setBusinessId]=useState(''),[status,setStatus]=useState<Status|null>(null),[manifest,setManifest]=useState<ManifestRow[]>([]),[motifs,setMotifs]=useState<LiveNetworkMotif[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[radius,setRadius]=useState<Record<string,string>>({}),[lastLiveAt,setLastLiveAt]=useState<string|null>(null),[title,setTitle]=useState(''),[body,setBody]=useState(''),[audience,setAudience]=useState('business_members');
 const load=useCallback(async()=>{const id=businessId||await currentBusinessId();if(!businessId)setBusinessId(id);const[nextStatus,nextManifest,nextMotifs]=await Promise.all([getLiveNetworkStatus(),listLiveNetworkManifest(id),listLiveNetworkMotifs(id,60)]);setStatus(nextStatus);setManifest(nextManifest);setMotifs(nextMotifs);setRadius(current=>Object.fromEntries(nextManifest.map(row=>[row.geofence_id,current[row.geofence_id]??String(row.radius_meters??150)])))},[businessId]);
 useEffect(()=>{setLoading(true);load().catch(c=>setError(c instanceof Error?c.message:String(c))).finally(()=>setLoading(false))},[load]);
 useEffect(()=>businessId?subscribeLiveNetworkMotifs(businessId,()=>{setLastLiveAt(new Date().toISOString());listLiveNetworkMotifs(businessId,60).then(setMotifs).catch(c=>setError(c instanceof Error?c.message:String(c)))}):undefined,[businessId]);
 async function reload(){setRefreshing(true);setError(null);try{await load()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setRefreshing(false)}}
 async function run(key:string,action:()=>Promise<unknown>,message?:string){setBusy(key);setError(null);setNotice(null);try{await action();if(message)setNotice(message);await reload()}catch(c){setError(c instanceof Error?c.message:String(c))}finally{setBusy(null)}}
 async function provision(){if(!businessId)return;await run('provision',()=>ensureLiveNetworkGeofences(businessId),'Live Network geofences are synchronized to canonical Business locations.')}
 async function enable(){if(!businessId)return;await run('enable',()=>enableLiveNetwork(businessId),'Live Network is enabled on this device with background geofencing and push delivery.')}
 async function disable(){await run('disable',disableLiveNetwork,'Live Network background geofencing is disabled on this device.')}
 async function saveGeofence(item:ManifestRow){const value=Number(radius[item.geofence_id]??item.radius_meters);if(!Number.isFinite(value)||value<50||value>1000){setError('Geofence radius must be between 50 and 1000 meters.');return;}await run(`geo:${item.geofence_id}`,()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:Math.round(value),notificationEnabled:item.notification_enabled,active:true}),'Geofence radius updated.')}
 async function publish(){if(!businessId||!title.trim()||!body.trim()){setError('Title and message are required.');return;}await run('publish',()=>sendBusinessNotification(businessId,{title:title.trim(),body:body.trim(),audience}),'Business Live Network update published to the eligible audience.');setTitle('');setBody('')}
 if(loading)return <View style={s.loading}><ActivityIndicator size="large"/></View>;
 const foreground=status?.foreground==='granted',background=status?.background==='granted',active=Boolean(status?.registered);
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>LIVE NETWORK</Text><Text style={s.heroTitle}>Geofences + realtime operating motifs</Text><Text style={s.heroBody}>Canonical Business places power background geofences, native push, audience updates and realtime analysis from the same location network used by Consumer and Fleet.</Text></View>
  {error?<View style={s.errorCard}><Text style={s.errorText}>{error}</Text></View>:null}{notice?<View style={s.noticeCard}><Text style={s.noticeText}>{notice}</Text></View>:null}
  <View style={s.metrics}><Metric label="Device state" value={active?'Running':'Off'}/><Metric label="Foreground" value={foreground?'Granted':'Needs permission'}/><Metric label="Background" value={background?'Granted':'Needs permission'}/><Metric label="Geofences" value={String(manifest.length)}/><Metric label="Active motifs" value={String(motifs.filter(item=>item.severity!=='quiet').length)}/><Metric label="Realtime" value={lastLiveAt?'Updated':'Listening'}/></View>
  <View style={s.card}><Text style={s.kicker}>DEVICE CONTROLS</Text><Text style={s.heading}>Live Network permission & delivery</Text><Text style={s.muted}>Enable Live Network requests foreground location, background location and notification permission, registers canonical Business geofences, then starts native background monitoring. You can stop it here at any time.</Text><View style={s.row}><Action disabled={Boolean(busy)} label={busy==='enable'?'Enabling…':'Enable Live Network'} onPress={enable}/><Action secondary disabled={Boolean(busy)||!active} label={busy==='disable'?'Disabling…':'Disable Live Network'} onPress={disable}/><Action secondary disabled={Boolean(busy)} label="Register push again" onPress={()=>run('push',registerLiveNetworkPush,'Push delivery is registered for Kleenest Business.')}/></View></View>
  <View style={s.card}><Text style={s.kicker}>AUDIENCE UPDATE</Text><Text style={s.heading}>Compose a Business notification</Text><Text style={s.muted}>Publish through the canonical Business notification authority. Audience selection remains server-scoped and consent-aware.</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Notification title"/><TextInput multiline style={[s.input,s.multi]} value={body} onChangeText={setBody} placeholder="What should the eligible audience know?"/><Text style={s.field}>Audience</Text><View style={s.row}>{['business_members','followers','nearby'].map(value=><Choice key={value} label={value.replaceAll('_',' ')} active={audience===value} onPress={()=>setAudience(value)}/>)}</View><Action disabled={Boolean(busy)||!title.trim()||!body.trim()} label={busy==='publish'?'Sending notification…':'Send notification'} onPress={publish}/></View>
  <View style={s.card}><Text style={s.kicker}>REALTIME ANALYSIS · LAST 60 MIN</Text><Text style={s.heading}>Business motifs</Text><Text style={s.muted}>These are derived from canonical route, geofence, occupancy, quality, Fleet and source-health signals. The realtime revision stream refreshes this section automatically.</Text></View>
  <View style={{gap:10}}>{motifs.length?motifs.map(item=><MotifCard key={item.motif_key} item={item}/>):<View style={s.card}><Text style={s.heading}>No active motifs</Text><Text style={s.muted}>The Live Network is listening. Meaningful aggregate patterns will appear as canonical signals accumulate.</Text></View>}</View>
  <View style={s.card}><Text style={s.kicker}>LOCATION COVERAGE</Text><Text style={s.heading}>Canonical geofences</Text><Text style={s.muted}>Business locations with valid coordinates can be synchronized into the same geofence authority used by Fleet, notifications and progression triggers.</Text><Action disabled={Boolean(busy)} label={busy==='provision'?'Synchronizing…':'Synchronize Business locations'} onPress={provision}/></View>
  <View style={{gap:10}}>{manifest.length?manifest.map(item=><View key={item.geofence_id} style={s.card}><Text style={s.locationTitle}>{item.location_name??'Business location'}</Text><Text style={s.muted}>{[item.address,item.city,item.state].filter(Boolean).join(', ')||'Canonical location'}</Text><View style={s.row}><Badge text={item.active?'ACTIVE':'OFF'}/><Badge text={item.notification_enabled?'NOTIFY':'SILENT'}/></View><Text style={s.field}>Radius meters</Text><TextInput value={radius[item.geofence_id]??String(item.radius_meters)} onChangeText={value=>setRadius(current=>({...current,[item.geofence_id]:value}))} keyboardType="number-pad" style={s.input}/><View style={s.row}><Action secondary disabled={Boolean(busy)} label="Save radius" onPress={()=>saveGeofence(item)}/><Action secondary disabled={Boolean(busy)} label={item.notification_enabled?'Mute geofence alerts':'Enable geofence alerts'} onPress={()=>run(`notify:${item.geofence_id}`,()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:item.radius_meters,notificationEnabled:!item.notification_enabled,active:true}),'Geofence notification preference updated.')}/><Action secondary disabled={Boolean(busy)} label={item.active?'Deactivate geofence':'Activate geofence'} onPress={()=>run(`active:${item.geofence_id}`,()=>configureLiveNetworkGeofence(item.geofence_id,{radiusMeters:item.radius_meters,notificationEnabled:item.notification_enabled,active:!item.active}),'Geofence activation updated.')}/></View></View>):<View style={s.card}><Text style={s.heading}>No geofences yet</Text><Text style={s.muted}>Synchronize Business locations above. Locations need valid coordinates before they can participate in Live Network.</Text></View>}</View>
  <View style={s.card}><Text style={s.kicker}>PRIVACY + STORE SAFETY</Text><Text style={s.heading}>Scoped operational intelligence</Text><Text style={s.muted}>Business motifs are aggregate and workspace-scoped. Raw user identifiers and precise movement are not exposed by the motif RPC. Live Network uses only location and notification permissions required for the operating feature.</Text></View>
 </ScrollView>
}
function MotifCard({item}:{item:LiveNetworkMotif}){return <View style={s.card}><View style={s.spread}><View style={{flex:1,gap:3}}><Text style={s.locationTitle}>{item.label}</Text><Text style={s.muted}>{motifDetail(item)}</Text></View><Badge text={item.severity.toUpperCase()}/></View><View style={s.row}><Badge text={`${item.observed_count} signals`}/><Badge text={`${Math.round(item.confidence*100)}% confidence`}/>{item.last_seen_at?<Badge text={`Seen ${formatTime(item.last_seen_at)}`}/>:null}</View></View>}
function motifDetail(item:LiveNetworkMotif){const e=item.evidence??{};switch(item.motif_key){case'network_momentum':return `${num(e.routes)} route intents are contributing to this workspace's current demand pattern.`;case'geofence_flow':return `${num(e.enters)} enters · ${num(e.exits)} exits · ${num(e.dwells)} dwell observations · ${num(e.dwell_seconds_avg,0)}s avg dwell.`;case'occupancy_pressure':return `${pct(e.occupancy_ratio)} occupancy · ${num(e.queue_avg,1)} avg queue · ${num(e.wait_minutes_avg,1)} min avg wait.`;case'quality_drift':return `Cleanliness ${num(e.cleanliness_avg,1)} · safety ${num(e.safety_avg,1)} · availability ${num(e.availability_avg,1)}.`;case'fleet_pressure':return `${num(e.operational_events)} Fleet events · ${num(e.open_alerts)} open alerts in this workspace.`;case'source_health':return `${num(e.degraded)} degraded sources · ${num(e.recovered)} recovered sources.`;default:return `${item.observed_count} canonical signals contributed to this motif.`}}
function num(value:unknown,digits=0){const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):'—'}function pct(value:unknown){const n=Number(value);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}function formatTime(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?'recently':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.muted}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
function Badge({text}:{text:string}){return <View style={s.badge}><Text style={s.badgeText}>{text}</Text></View>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,active&&s.choiceOn]}><Text style={[s.choiceText,active&&s.choiceTextOn]}>{label}</Text></Pressable>}
function Action({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,secondary&&s.secondaryAction,disabled&&{opacity:.45}]}><Text style={[s.actionText,secondary&&s.secondaryText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({loading:{flex:1,justifyContent:'center'},page:{padding:16,paddingBottom:72,gap:16,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:19,gap:7},eyebrow:{color:'#bfe0cd',fontWeight:'900',letterSpacing:1},heroTitle:{color:'#fff',fontSize:26,fontWeight:'900'},heroBody:{color:'#dce9e2',lineHeight:20},errorCard:{backgroundColor:'#fae7e7',borderRadius:14,padding:12},errorText:{color:'#8f2f2f',fontWeight:'800'},noticeCard:{backgroundColor:'#e4f3ea',borderRadius:14,padding:12},noticeText:{color:'#22553a',fontWeight:'800'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{backgroundColor:'#fff',borderRadius:16,padding:13,minWidth:120,flexGrow:1,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:19,fontWeight:'900',color:'#173024'},card:{backgroundColor:'#fff',borderRadius:18,padding:16,gap:10,borderWidth:1,borderColor:'#dbe5de'},heading:{fontSize:20,fontWeight:'900',color:'#173024'},locationTitle:{fontSize:18,fontWeight:'900',color:'#173024'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#547060'},muted:{color:'#66766e',lineHeight:19},row:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center'},spread:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10},action:{backgroundColor:'#173f2d',borderRadius:999,paddingHorizontal:13,paddingVertical:10,alignSelf:'flex-start'},secondaryAction:{backgroundColor:'#edf3ef'},actionText:{fontWeight:'900',color:'#fff'},secondaryText:{color:'#244d39'},field:{fontSize:12,fontWeight:'900',color:'#365245'},input:{backgroundColor:'#f8faf9',borderWidth:1,borderColor:'#d8e1dc',borderRadius:12,paddingHorizontal:11,paddingVertical:10},multi:{minHeight:88,textAlignVertical:'top'},badge:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:5},badgeText:{fontSize:11,fontWeight:'900',color:'#244d39'},choice:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:10,paddingVertical:8},choiceOn:{backgroundColor:'#173f2d'},choiceText:{fontSize:11,fontWeight:'800',color:'#365645'},choiceTextOn:{color:'#fff'}});
