import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
import { currentBusinessId,sendBusinessNotification } from '../services/capabilityWorkflows';
import { runBusinessAi } from '../services/ai';
import { registerRolePush } from '../services/push';

type Row=Record<string,any>;
export default function Notifications(){
 const[businessId,setBusinessId]=useState(''),[rows,setRows]=useState<Row[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[audience,setAudience]=useState('followers'),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading notifications…');
 async function load(){setBusy(true);try{const id=businessId||await currentBusinessId();setBusinessId(id);const{data,error}=await getKleenestSupabaseClient().rpc('user_notifications',{p_limit:100});if(error)throw error;setRows(Array.isArray(data)?data:[]);setMessage('')}catch(e:any){setMessage(e?.message||'Notifications unavailable.')}finally{setBusy(false)}}useEffect(()=>{void load()},[]);
 async function enable(){setBusy(true);try{const result=await registerRolePush();setMessage(result.status==='registered'?'Native Business notifications are enabled.':result.message)}catch(e:any){setMessage(e?.message||'Push registration failed.')}finally{setBusy(false)}}
 async function send(){if(!title.trim()||!body.trim())return setMessage('Compose a title and message before sending.');setBusy(true);try{await sendBusinessNotification(businessId,{title:title.trim(),body:body.trim(),audience});setMessage('Notification sent to the eligible Audience.');setTitle('');setBody('');await load()}catch(e:any){setMessage(e?.message||'Notification could not be sent.')}finally{setBusy(false)}}
 async function ai(){setBusy(true);try{const result=await runBusinessAi('notification_copy',{business_id:businessId,audience,title,body},'Write concise Kleenest Business notification copy. Return a short title on the first line and the message on following lines. Do not invent offers or facts.');const lines=result.answer.split('\n').map(v=>v.trim()).filter(Boolean);if(lines.length){setTitle(lines[0].replace(/^title\s*:\s*/i,''));setBody(lines.slice(1).join(' ').replace(/^message\s*:\s*/i,'')||lines[0]);setMessage('Kleenest AI draft loaded. Review it before sending.')}}catch(e:any){setMessage(e?.message||'Kleenest AI could not draft notification copy.')}finally{setBusy(false)}}
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.hero}><Text style={s.kicker}>BUSINESS NOTIFICATIONS</Text><Text style={s.title}>Compose, target and send.</Text><Text style={s.copy}>Use the same consent-aware notification authority as Live Network. Draft with Kleenest AI, choose an Audience, review the copy, then Send notification.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}<View style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.cardTitle}>Device delivery</Text><Text style={s.meta}>Register this Business device for native notification delivery.</Text></View><Action label="Enable push" quiet disabled={busy} onPress={enable}/></View></View><View style={s.card}><Text style={s.kicker}>COMPOSE</Text><Text style={s.cardTitle}>New Business update</Text><Text style={s.label}>Audience</Text><View style={s.chips}>{['followers','nearby','business_members'].map(v=><Chip key={v} label={v.replaceAll('_',' ')} active={audience===v} onPress={()=>setAudience(v)}/>)}</View><Text style={s.label}>Title</Text><TextInput style={s.input} color="#132b21" placeholderTextColor="#78877f" value={title} onChangeText={setTitle} placeholder="What changed?"/><Text style={s.label}>Message</Text><TextInput style={[s.input,s.multi]} color="#132b21" placeholderTextColor="#78877f" multiline value={body} onChangeText={setBody} placeholder="Tell the eligible audience what matters."/><View style={s.actions}><Action label="Kleenest AI draft" quiet disabled={busy} onPress={ai}/><Action label="Send notification" disabled={busy||!title.trim()||!body.trim()} onPress={send}/></View></View><Text style={s.section}>Recent updates</Text>{rows.length?rows.map(r=><View style={s.card} key={String(r.id)}><Text style={s.cardTitle}>{String(r.title||r.type||'Update')}</Text><Text style={s.meta}>{String(r.body||r.message||'')}</Text><Text style={s.time}>{format(r.created_at||r.sent_at)}</Text></View>):<View style={s.card}><Text style={s.meta}>No recent Business notifications were returned.</Text></View>}</ScrollView>;
}
function format(value:any){if(!value)return'';const d=new Date(String(value));return Number.isNaN(d.getTime())?'':d.toLocaleString()}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:10,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},section:{fontSize:21,fontWeight:'900',color:'#102218',marginTop:4},card:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:1,borderColor:'#dbe5de',gap:9},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#607067'},time:{fontSize:10,color:'#7b8881'},label:{fontSize:12,fontWeight:'900',color:'#365245'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},multi:{minHeight:96,textAlignVertical:'top'},top:{flexDirection:'row',alignItems:'center',gap:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:10,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontWeight:'800',color:'#315440'},chipTextOn:{color:'#fff'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:10,borderRadius:12,alignItems:'center'},actionText:{color:'#fff',fontWeight:'900'},actionQuiet:{backgroundColor:'#edf3ef'},actionQuietText:{color:'#173f2d'},disabled:{opacity:.45}});
