import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
import { currentBusinessId,sendBusinessNotification } from '../services/capabilityWorkflows';
import { registerRolePush } from '../services/push';
import { runBusinessAi } from '../services/ai';

type Row=Record<string,any>;
const audiences=['business_members','followers','nearby'];
export default function Notifications(){
 const[rows,setRows]=useState<Row[]>([]),[businessId,setBusinessId]=useState(''),[busy,setBusy]=useState<string|null>('load'),[message,setMessage]=useState('Loading notifications…'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[audience,setAudience]=useState('followers');
 async function load(){setBusy('load');try{const id=businessId||await currentBusinessId();setBusinessId(id);const{data,error}=await getKleenestSupabaseClient().rpc('user_notifications',{p_limit:100});if(error)throw error;setRows(Array.isArray(data)?data:[]);setMessage('')}catch(e:any){setMessage(e?.message||'Notifications unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void load()},[]);
 async function enable(){setBusy('push');try{const result=await registerRolePush();setMessage(result.status==='registered'?'Native Business notifications are enabled.':result.message)}catch(e:any){setMessage(e?.message||'Push registration failed.')}finally{setBusy(null)}}
 async function send(){if(!title.trim()||!body.trim())return setMessage('Notification title and message are required.');setBusy('send');try{await sendBusinessNotification(businessId,{title:title.trim(),body:body.trim(),audience});setTitle('');setBody('');setMessage('Business notification sent to the eligible audience.');await load()}catch(e:any){setMessage(e?.message||'Notification could not be sent.')}finally{setBusy(null)}}
 async function assist(){setBusy('ai');try{const result=await runBusinessAi('notification_copy',{business_id:businessId,audience,title:title.trim(),draft:body.trim()},'Improve this Business notification. Keep it concise, useful, factual, and appropriate for the selected audience. Return only the recommended message body.');setBody(result.answer.trim());setMessage(result.review_required?'Kleenest AI drafted copy. Review it before sending.':'Kleenest AI drafted copy for review.')}catch(e:any){setMessage(e?.message||'Kleenest AI could not draft notification copy.')}finally{setBusy(null)}}
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy==='load'} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>BUSINESS NOTIFICATIONS</Text><Text style={s.title}>Compose useful updates, then deliver them deliberately</Text><Text style={s.copy}>Audience-scoped publishing, native push registration and Kleenest AI drafting live in one operating surface. AI never sends automatically.</Text></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.card}><Text style={s.head}>Compose</Text><Text style={s.label}>AUDIENCE</Text><View style={s.chips}>{audiences.map(value=><Chip key={value} label={value.replaceAll('_',' ')} active={audience===value} onPress={()=>setAudience(value)}/>)}</View><Text style={s.label}>TITLE</Text><TextInput value={title} onChangeText={setTitle} placeholder="Notification title" style={s.input}/><Text style={s.label}>MESSAGE</Text><TextInput value={body} onChangeText={setBody} placeholder="What should this audience know?" multiline style={[s.input,s.multi]}/><View style={s.actions}><Action quiet label={busy==='ai'?'Drafting…':'Kleenest AI'} disabled={Boolean(busy)} onPress={assist}/><Action label={busy==='send'?'Sending…':'Send notification'} disabled={Boolean(busy)||!title.trim()||!body.trim()} onPress={send}/></View><Text style={s.meta}>Audience: {audience.replaceAll('_',' ')}. Delivery remains subject to consent, eligibility and server-side notification rules.</Text></View>
  <View style={s.card}><Text style={s.head}>Device delivery</Text><Text style={s.meta}>Register this device for Business push so operational alerts and eligible notifications can arrive outside the app.</Text><Action label={busy==='push'?'Enabling…':'Enable device notifications'} disabled={Boolean(busy)} onPress={enable}/></View>
  <Text style={s.section}>Inbox</Text>{rows.map(row=><View style={s.card} key={String(row.id)}><Text style={s.head}>{row.title||row.type||'Update'}</Text><Text style={s.meta}>{row.body||row.message||''}</Text><Text style={s.date}>{row.created_at?new Date(row.created_at).toLocaleString():''}</Text></View>)}{!rows.length?<View style={s.card}><Text style={s.meta}>No Business notifications are currently in this inbox.</Text></View>:null}
 </ScrollView>;
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,quiet&&s.buttonQuiet,disabled&&{opacity:.45}]}><Text style={[s.buttonText,quiet&&s.buttonQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:19,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'800',color:'#5d6c63'},card:{backgroundColor:'#fff',padding:15,borderRadius:16,borderWidth:1,borderColor:'#dbe5de',gap:9},head:{fontSize:17,fontWeight:'900',color:'#102218'},meta:{fontSize:12,color:'#607067',lineHeight:19},date:{fontSize:10,color:'#829087'},label:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#718077'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},multi:{minHeight:90,textAlignVertical:'top'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:'#173f2d'},chipText:{fontWeight:'800',color:'#365645',textTransform:'capitalize'},chipTextOn:{color:'#fff'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{backgroundColor:'#173d2b',paddingHorizontal:12,paddingVertical:10,borderRadius:12,alignItems:'center',alignSelf:'flex-start'},buttonQuiet:{backgroundColor:'#edf3ef'},buttonText:{color:'#fff',fontWeight:'900'},buttonQuietText:{color:'#244d39'},section:{fontSize:21,fontWeight:'900',color:'#102218',marginTop:4}});
