import { Link } from 'expo-router';
import QRCode from 'react-native-qrcode-svg';
import { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { getBusinessDashboard } from '../services/product';
import { listQrStudioAssets } from '../services/qrStudio';
import { defaultQrDesign, normalizeQrDesign, saveQrVisualDesign, type QrDesign } from '../services/qrVisual';
import { pickAndUploadQrBranding } from '../services/media';

type Row=Record<string,any>;
const copy=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const idOf=(row:Row)=>String(row.id||row.qr_id||'');
const payloadOf=(row:Row)=>String(row.public_url||row.landing_url||row.code||row.qr_code||idOf(row)||'https://kleenest.app/qr');
function rgb(hex:string){const c=hex.replace('#','');if(!/^[0-9a-f]{6}$/i.test(c))return null;return[0,2,4].map(i=>parseInt(c.slice(i,i+2),16));}
function luminance(hex:string){const r=rgb(hex);if(!r)return null;const v=r.map(n=>{const s=n/255;return s<=.03928?s/12.92:((s+.055)/1.055)**2.4});return .2126*v[0]+.7152*v[1]+.0722*v[2];}
function contrast(a:string,b:string){const x=luminance(a),y=luminance(b);if(x==null||y==null)return 0;return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}

export default function QrDesigner(){
 const[businessId,setBusinessId]=useState(''),[assets,setAssets]=useState<Row[]>([]),[selectedId,setSelectedId]=useState(''),[businessLogo,setBusinessLogo]=useState(''),[design,setDesign]=useState<QrDesign>(copy(defaultQrDesign)),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading QR designer…');
 async function load(){setBusy(true);try{const id=businessId||await currentBusinessId();setBusinessId(id);const[a,d]=await Promise.all([listQrStudioAssets(id),getBusinessDashboard(id)]);setAssets(a as Row[]);setBusinessLogo(String(d?.profile?.logo_url||''));const next=(a as Row[]).find(row=>idOf(row)===selectedId)||(a as Row[])[0];if(next){setSelectedId(idOf(next));setDesign(normalizeQrDesign(next.customization||next.design));}setMessage('')}catch(e:any){setMessage(e?.message||'QR designer unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const selected=useMemo(()=>assets.find(row=>idOf(row)===selectedId)||null,[assets,selectedId]);
 const ratio=contrast(design.design.foreground,design.design.background),logoScale=Number(design.design.logo.scale||0),ready=ratio>=4.5&&design.design.quiet_zone>=4&&logoScale<=.22;
 const logoUrl=design.design.logo.source==='business'?businessLogo:(design.design.logo.url||'');
 const patch=(value:Partial<QrDesign['design']>)=>setDesign(current=>({...current,design:{...current.design,...value}}));
 const patchLogo=(value:Partial<QrDesign['design']['logo']>)=>setDesign(current=>({...current,design:{...current.design,logo:{...current.design.logo,...value}}}));
 async function save(){if(!selected)return;if(!ready)return setMessage('Scan readiness needs attention: use at least 4.5:1 contrast, a 4+ module quiet zone and a logo no larger than 22%.');setBusy(true);try{await saveQrVisualDesign({businessId,qrId:idOf(selected),locationId:selected.location_id?String(selected.location_id):null,design,summary:'Visual design saved from Business QR Designer'});setMessage('QR configuration saved as a versioned design.');await load()}catch(e:any){setMessage(e?.message||'QR design could not be saved.')}finally{setBusy(false)}}
 async function upload(){setBusy(true);try{const result=await pickAndUploadQrBranding(businessId);if(result){patchLogo({source:'media',url:result.publicUrl,scale:Math.max(.12,logoScale||0),padding:4});setMessage('Custom logo uploaded. Save configuration to attach it to this QR.')}}catch(e:any){setMessage(e?.message||'Logo upload failed.')}finally{setBusy(false)}}
 function choose(row:Row){setSelectedId(idOf(row));setDesign(normalizeQrDesign(row.customization||row.design));setMessage('');}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.hero}><Text style={s.eyebrow}>VISUAL QR DESIGNER</Text><Text style={s.title}>Brand without breaking scan reliability.</Text><Text style={s.body}>The QR identity and attribution stay stable while colors, finder geometry, framing, CTA and logo treatment are versioned.</Text></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.card}><View style={s.top}><View style={{flex:1}}><Text style={s.cardTitle}>Choose QR asset</Text><Text style={s.meta}>Select an existing code from the Business QR library.</Text></View><Link href="/qr-studio" style={s.link}>QR Library</Link></View><View style={s.chips}>{assets.map(row=><Chip key={idOf(row)} label={String(row.label||row.name||'QR asset')} active={idOf(row)===selectedId} onPress={()=>choose(row)}/>)}</View></View>
  {selected?<><View style={[s.preview,ready?s.previewReady:s.previewWarn]}><Text style={s.kicker}>LIVE PREVIEW</Text>{design.frame.cta?<Text style={s.cta}>{design.frame.cta}</Text>:null}<View style={{backgroundColor:design.design.background,padding:Math.max(12,design.design.quiet_zone*2),borderRadius:18}}><QRCode value={payloadOf(selected)} size={205} color={/^#[0-9a-f]{6}$/i.test(design.design.foreground)?design.design.foreground:'#173f2d'} backgroundColor={/^#[0-9a-f]{6}$/i.test(design.design.background)?design.design.background:'#ffffff'} quietZone={design.design.quiet_zone} ecl={logoUrl?'H':'M'} logo={logoUrl?{uri:logoUrl}:undefined} logoSize={logoUrl?Math.max(22,Math.round(205*Math.min(.22,logoScale||.12))):undefined} logoMargin={design.design.logo.padding}/></View><Text style={[s.readiness,ready?s.good:s.bad]}>Scan readiness: {ready?'Ready':'Needs attention'}</Text><Text style={s.meta}>Contrast {ratio.toFixed(2)}:1 · quiet zone {design.design.quiet_zone} · logo {Math.round(logoScale*100)}%</Text></View>
  <View style={s.card}><Text style={s.kicker}>DESIGN</Text><Text style={s.cardTitle}>Color & geometry</Text><Field label="Foreground color"><TextInput style={s.input} color="#132b21" placeholderTextColor="#78877f" value={design.design.foreground} onChangeText={v=>patch({foreground:v})} placeholder="#173F2D"/></Field><Field label="Background color"><TextInput style={s.input} color="#132b21" placeholderTextColor="#78877f" value={design.design.background} onChangeText={v=>patch({background:v})} placeholder="#FFFFFF"/></Field><Field label="Module style"><View style={s.chips}>{(['square','rounded','dots'] as const).map(v=><Chip key={v} label={v} active={design.design.module_style===v} onPress={()=>patch({module_style:v})}/>)}</View></Field><Field label="Finder eye style"><View style={s.chips}>{(['square','rounded','circle'] as const).map(v=><Chip key={v} label={v} active={design.design.eye_style===v} onPress={()=>patch({eye_style:v})}/>)}</View></Field><Field label="Quiet zone"><View style={s.chips}>{[4,6,8,10,12].map(v=><Chip key={v} label={`${v} modules`} active={design.design.quiet_zone===v} onPress={()=>patch({quiet_zone:v})}/>)}</View></Field></View>
  <View style={s.card}><Text style={s.kicker}>BRANDING</Text><Text style={s.cardTitle}>Logo</Text><View style={s.chips}><Chip label="No logo" active={design.design.logo.source==='none'} onPress={()=>patchLogo({source:'none',url:null,scale:0})}/><Chip label="Use business logo" active={design.design.logo.source==='business'} onPress={()=>patchLogo({source:'business',url:businessLogo||null,scale:.14,padding:4})}/></View><Pressable disabled={busy} onPress={upload} style={s.secondary}><Text style={s.secondaryText}>Upload custom logo</Text></Pressable>{logoUrl?<View style={s.logoRow}><Image source={{uri:logoUrl}} style={s.logo}/><Text style={s.meta}>Current QR logo</Text></View>:null}<Field label="Logo size"><View style={s.chips}>{[.10,.12,.14,.16,.18,.20,.22].map(v=><Chip key={v} label={`${Math.round(v*100)}%`} active={Math.abs(logoScale-v)<.001} onPress={()=>patchLogo({scale:v})}/>)}</View></Field></View>
  <View style={s.card}><Text style={s.kicker}>FRAME + MESSAGE</Text><Field label="CTA label"><TextInput style={s.input} color="#132b21" placeholderTextColor="#78877f" value={design.frame.cta||''} onChangeText={v=>setDesign(c=>({...c,frame:{...c.frame,cta:v||null}}))} placeholder="Scan to check in"/></Field><Field label="Supporting text"><TextInput style={[s.input,s.multi]} color="#132b21" placeholderTextColor="#78877f" multiline value={design.frame.supporting_text||''} onChangeText={v=>setDesign(c=>({...c,frame:{...c.frame,supporting_text:v||null}}))} placeholder="Earn XP and help keep restroom data fresh"/></Field></View>
  <View style={s.card}><Text style={s.kicker}>SCAN SAFETY</Text><Text style={s.cardTitle}>Scan readiness</Text><Text style={s.meta}>Minimum contrast is 4.5:1, quiet zone is at least four modules, and logo size is capped at 22%.</Text><Pressable disabled={busy||!ready} onPress={save} style={[s.primary,(busy||!ready)&&s.disabled]}><Text style={s.primaryText}>{busy?'Saving…':'Save configuration'}</Text></Pressable></View></>:<View style={s.card}><Text style={s.cardTitle}>Create a QR asset first</Text><Text style={s.meta}>The visual designer preserves an existing QR identity rather than inventing an untracked code.</Text><Link href="/qr-studio" style={s.link}>Open QR Studio</Link></View>}
 </ScrollView>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{gap:6}}><Text style={s.label}>{label}</Text>{children}</View>}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:11,borderWidth:1,borderColor:'#dbe5de'},top:{flexDirection:'row',alignItems:'center',gap:8},cardTitle:{fontSize:19,fontWeight:'900',color:'#102218'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#547060'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},link:{color:'#173f2d',fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:11,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontWeight:'800',color:'#315440'},chipTextOn:{color:'#fff'},preview:{backgroundColor:'#fff',borderRadius:22,padding:16,gap:10,alignItems:'center',borderWidth:2},previewReady:{borderColor:'#5f9f79'},previewWarn:{borderColor:'#b9894e'},cta:{fontSize:19,fontWeight:'900',color:'#173024',textAlign:'center'},readiness:{fontWeight:'900'},good:{color:'#226342'},bad:{color:'#8f2f2f'},label:{fontSize:12,fontWeight:'900',color:'#365245'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},multi:{minHeight:80,textAlignVertical:'top'},secondary:{alignSelf:'flex-start',backgroundColor:'#edf3ef',paddingHorizontal:12,paddingVertical:10,borderRadius:12},secondaryText:{fontWeight:'900',color:'#173f2d'},logoRow:{flexDirection:'row',gap:10,alignItems:'center'},logo:{width:54,height:54,borderRadius:12,resizeMode:'contain'},primary:{backgroundColor:'#173f2d',padding:13,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45}});
