import { Link } from 'expo-router';
import { Alert,Pressable,RefreshControl,ScrollView,Share,StyleSheet,Switch,Text,TextInput,View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { useEffect,useState } from 'react';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { getBusinessDashboard } from '../services/product';
import { createQrAsset,createQrProgram,deleteQrAsset,listQrPrograms,listQrStudioAssets,listQrStudioTemplates,listQrStudioVersions,restoreQrVersion,saveQrTemplate,setQrActive,updateQrAsset,type QrRecord } from '../services/qrStudio';

type Row=Record<string,any>;
const idOf=(r:Row)=>String(r.id||r.qr_id||'');
const locationIdOf=(r:Row)=>String(r.location_id||'');
const qrValueOf=(r:Row)=>String(r.public_url||r.landing_url||r.url||r.code||r.qr_code||idOf(r)||'https://kleenest.app/qr');
export default function QrStudio(){
 const[businessId,setBusinessId]=useState(''),[assets,setAssets]=useState<Row[]>([]),[templates,setTemplates]=useState<Row[]>([]),[locations,setLocations]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[versions,setVersions]=useState<Row[]>([]),[programs,setPrograms]=useState<Row[]>([]),[locationId,setLocationId]=useState(''),[label,setLabel]=useState('Kleenest check-in'),[singleUse,setSingleUse]=useState(false),[maxRedemptions,setMaxRedemptions]=useState('1'),[editLabel,setEditLabel]=useState(''),[programName,setProgramName]=useState(''),[programType,setProgramType]=useState('checkin_reward'),[templateName,setTemplateName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading QR Studio…');
 async function load(selectId?:string){setBusy(true);try{const id=businessId||await currentBusinessId();setBusinessId(id);const[a,t,d]=await Promise.all([listQrStudioAssets(id),listQrStudioTemplates(id),getBusinessDashboard(id)]);const nextAssets=a as Row[];setAssets(nextAssets);setTemplates(t as Row[]);const nextLocations=Array.isArray(d?.locations)?d.locations:[];setLocations(nextLocations);if(!locationId&&nextLocations[0])setLocationId(String(nextLocations[0].id||nextLocations[0].location_id||''));const wanted=selectId||idOf(selected||{});const next=nextAssets.find(row=>idOf(row)===wanted)||nextAssets[0]||null;if(next)await choose(next,false);else{setSelected(null);setVersions([]);setPrograms([]);}setMessage('')}catch(e:any){setMessage(e?.message||'QR Studio unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function choose(row:Row,setBusyState=true){if(setBusyState)setBusy(true);try{setSelected(row);setEditLabel(String(row.label||row.name||'Kleenest QR'));const id=idOf(row);const[v,p]=id?await Promise.all([listQrStudioVersions(businessId,id).catch(()=>[]),listQrPrograms(id).catch(()=>[])]):[[],[]];setVersions(v as Row[]);setPrograms(p as Row[]);}finally{if(setBusyState)setBusy(false)}}
 async function run(fn:()=>Promise<unknown>,success:string,selectId?:string){setBusy(true);try{await fn();setMessage(success);await load(selectId);}catch(e:any){setMessage(e?.message||'QR action failed.')}finally{setBusy(false)}}
 async function create(){if(!locationId||!label.trim())return setMessage('Choose a location and enter a QR label.');const result:any=await createQrAsset(businessId,{locationId,label:label.trim(),purpose:'check_in',actionType:'location',actionPayload:{location_id:locationId},singleUse,maxRedemptions:singleUse?Math.max(1,Number(maxRedemptions)||1):null});const row=Array.isArray(result)?result[0]:result;setMessage(singleUse?'Single-use QR asset created.':'QR asset created.');await load(row?String(row.id||row.qr_id||''):undefined);}
 async function saveConfiguration(){if(!selected)return;const id=idOf(selected);await run(()=>updateQrAsset(businessId,id,{label:editLabel.trim()||String(selected.label||'Kleenest QR'),purpose:String(selected.purpose||'check_in'),actionType:String(selected.action_type||'location'),actionPayload:selected.action_payload||{},customization:selected.customization||{},active:selected.active!==false,singleUse:Boolean(selected.single_use),maxRedemptions:selected.max_redemptions??null}),'QR configuration saved.',id);}
 function remove(){if(!selected)return;const id=idOf(selected);Alert.alert('Delete QR asset?',String(selected.label||'This QR asset'),[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void run(()=>deleteQrAsset(businessId,id),'QR asset deleted.')}]);}
 async function share(){if(!selected)return;await Share.share({title:String(selected.label||'Kleenest QR'),message:qrValueOf(selected)});}
 async function createProgram(){if(!selected||!programName.trim())return setMessage('Enter an engagement program name.');const id=idOf(selected);await run(()=>createQrProgram(id,{programType,name:programName.trim(),description:'Created from Kleenest Business QR Studio',triggerCount:1,rewardConfig:{}}),'Engagement program created.',id);setProgramName('');}
 const selectedId=idOf(selected||{}),qrValue=selected?qrValueOf(selected):'';
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>load()}/>} keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>QR STUDIO</Text><Text style={s.title}>Create, configure, version and activate QR assets.</Text><Text style={s.copy}>Stable QR identity, single-use controls, engagement programs, reusable design and attribution stay connected to canonical Business locations.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.card}><Text style={s.cardTitle}>Create QR asset</Text><Text style={s.label}>Location</Text><View style={s.chips}>{locations.slice(0,30).map(row=>{const id=String(row.id||row.location_id||'');return <Chip key={id} label={String(row.name||'Location')} active={id===locationId} onPress={()=>setLocationId(id)}/>)}</View><TextInput placeholderTextColor="#78877f" style={s.input} value={label} onChangeText={setLabel} placeholder="QR label"/><View style={s.switchRow}><View style={{flex:1}}><Text style={s.cardTitle}>Single-use QR</Text><Text style={s.meta}>Invalidate after the allowed redemption count is reached.</Text></View><Switch value={singleUse} onValueChange={setSingleUse}/></View>{singleUse?<TextInput placeholderTextColor="#78877f" style={s.input} keyboardType="number-pad" value={maxRedemptions} onChangeText={setMaxRedemptions} placeholder="Maximum redemptions"/>:null}<Action label="Create QR asset" disabled={busy||!locationId||!label.trim()} onPress={create}/></View>
  <View style={s.sectionHead}><Text style={s.section}>QR library</Text><Link href="/qr-designer" style={s.link}>Open visual designer →</Link></View><View style={s.chips}>{assets.map(row=><Pressable key={idOf(row)} onPress={()=>void choose(row)} style={[s.asset,idOf(row)===selectedId&&s.assetOn]}><Text style={s.assetTitle}>{String(row.label||row.name||'QR asset')}</Text><Text style={s.meta}>{String(row.location_name||row.purpose||'Location action')} · {row.active===false?'OFF':'ACTIVE'}</Text></Pressable>)}</View>
  {selected?<><View style={s.card}><View style={s.preview}><QRCode value={qrValue} size={190} color="#173f2d" backgroundColor="#ffffff"/><Text style={s.meta} selectable>{qrValue}</Text></View><Text style={s.label}>Label</Text><TextInput placeholderTextColor="#78877f" style={s.input} value={editLabel} onChangeText={setEditLabel}/><View style={s.actions}><Action label="Save configuration" disabled={busy} onPress={saveConfiguration}/><Action label={selected.active===false?'Activate':'Deactivate'} quiet disabled={busy} onPress={()=>run(()=>setQrActive(businessId,selectedId,selected.active===false),selected.active===false?'QR activated.':'QR deactivated.',selectedId)}/><Action label="Share" quiet disabled={busy} onPress={share}/><Action label="Delete" danger disabled={busy} onPress={remove}/></View></View>
  <View style={s.card}><Text style={s.cardTitle}>Create engagement program</Text><Text style={s.meta}>Attach rewards or repeat-scan behavior to this QR without replacing its code.</Text><TextInput placeholderTextColor="#78877f" style={s.input} value={programName} onChangeText={setProgramName} placeholder="Program name"/><View style={s.chips}>{['checkin_reward','streak','contest','promotion'].map(v=><Chip key={v} label={v.replaceAll('_',' ')} active={programType===v} onPress={()=>setProgramType(v)}/>)}</View><Action label="Create engagement program" disabled={busy||!programName.trim()} onPress={createProgram}/>{programs.length?<Text style={s.meta}>{programs.length} engagement program{programs.length===1?'':'s'} attached.</Text>:null}</View>
  <View style={s.card}><Text style={s.cardTitle}>Version history</Text>{versions.length?versions.map((row,index)=>{const version=Number(row.version||row.version_number||index+1);return <View key={String(row.id||version)} style={s.version}><View style={{flex:1}}><Text style={s.assetTitle}>Version {version}</Text><Text style={s.meta}>{String(row.change_summary||row.created_at||'Saved configuration')}</Text></View><Action label="Restore" quiet disabled={busy} onPress={()=>run(()=>restoreQrVersion(businessId,selectedId,version),`QR restored to version ${version}.`,selectedId)}/></View>}):<Text style={s.meta}>No prior versions returned.</Text>}</View>
  <View style={s.card}><Text style={s.cardTitle}>Reusable template</Text><TextInput placeholderTextColor="#78877f" style={s.input} value={templateName} onChangeText={setTemplateName} placeholder="Template name"/><Action label="Save current configuration as template" quiet disabled={busy||!templateName.trim()} onPress={()=>run(()=>saveQrTemplate(businessId,{name:templateName.trim(),description:'Saved from Business QR Studio',design:selected.customization||{}}),'QR template saved.',selectedId)}/></View></>:null}
  <Text style={s.section}>Templates</Text>{templates.length?templates.map(row=><View key={String(row.id||row.template_id)} style={s.card}><Text style={s.cardTitle}>{String(row.name||'QR template')}</Text><Text style={s.meta}>{String(row.description||'Reusable QR configuration')}</Text></View>):<View style={s.card}><Text style={s.meta}>No reusable templates yet.</Text></View>}
 </ScrollView>;
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&s.disabled]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},section:{fontSize:21,fontWeight:'900',color:'#102218'},link:{color:'#173f2d',fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:10,borderWidth:1,borderColor:'#dbe5de'},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},label:{fontSize:11,fontWeight:'900',color:'#365245'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:10,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontWeight:'800',color:'#315440'},chipTextOn:{color:'#fff'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb',color:'#132b21'},switchRow:{flexDirection:'row',alignItems:'center',gap:10},asset:{backgroundColor:'#fff',borderRadius:15,padding:12,borderWidth:1,borderColor:'#dbe5de',minWidth:'47%',flexGrow:1},assetOn:{borderWidth:2,borderColor:'#173f2d'},assetTitle:{fontWeight:'900',color:'#102218'},preview:{alignItems:'center',gap:8,backgroundColor:'#f7f9f8',borderRadius:16,padding:14},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},actionText:{color:'#fff',fontWeight:'900'},actionQuiet:{backgroundColor:'#edf3ef'},actionQuietText:{color:'#173f2d'},actionDanger:{backgroundColor:'#8b3434'},disabled:{opacity:.45},version:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:'#edf0ee',paddingTop:8}});
