import { useEffect,useMemo,useState } from 'react';
import { Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { getBusinessDashboard } from '../services/product';
import { archiveQrTemplate,createCustomQr,currentBusinessId,listQrAssets,listQrTemplates,listQrVersions,restoreQrVersion,saveQrTemplate,upsertQrAsset } from '../services/capabilityWorkflows';
import { deleteQrAsset,setQrActive } from '../services/qrStudio';
import { defaultQrDesign,normalizeQrDesign,type QrDesign } from '../services/qrVisual';
import { pickAndUploadQrBranding } from '../services/qrBranding';

type Row=Record<string,any>;
const arr=(value:any,key?:string):Row[]=>Array.isArray(key?value?.[key]:value)?(key?value[key]:value):Array.isArray(value?.assets)?value.assets:[];
const assetId=(row:Row|null)=>String(row?.id||row?.qr_id||'');
const cloneDesign=():QrDesign=>JSON.parse(JSON.stringify(defaultQrDesign)) as QrDesign;
const MODULE_STYLES:QrDesign['design']['module_style'][]=['square','rounded','dots'];
const EYE_STYLES:QrDesign['design']['eye_style'][]=['square','rounded','circle'];
const FRAME_STYLES=['none','minimal','rounded','high-visibility'];

function rgb(hex:string){const clean=hex.replace('#','');if(!/^[0-9a-f]{6}$/i.test(clean))return null;return[0,2,4].map(index=>parseInt(clean.slice(index,index+2),16)) as[number,number,number];}
function luminance(hex:string){const value=rgb(hex);if(!value)return null;const channels=value.map(channel=>{const s=channel/255;return s<=0.03928?s/12.92:((s+0.055)/1.055)**2.4;});return 0.2126*channels[0]+0.7152*channels[1]+0.0722*channels[2];}
function contrast(foreground:string,background:string){const a=luminance(foreground),b=luminance(background);if(a==null||b==null)return 0;return(Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);}
function patchDesign(current:QrDesign,patch:Partial<QrDesign['design']>):QrDesign{return{...current,design:{...current.design,...patch}};}
function patchLogo(current:QrDesign,patch:Partial<QrDesign['design']['logo']>):QrDesign{return patchDesign(current,{logo:{...current.design.logo,...patch}});}

export default function QrStudio(){
 const[businessId,setBusinessId]=useState(''),[assets,setAssets]=useState<Row[]>([]),[templates,setTemplates]=useState<Row[]>([]),[locations,setLocations]=useState<Row[]>([]),[profile,setProfile]=useState<Row>({}),[selected,setSelected]=useState<Row|null>(null),[locationId,setLocationId]=useState(''),[label,setLabel]=useState('Kleenest check-in'),[design,setDesign]=useState<QrDesign>(cloneDesign()),[versions,setVersions]=useState<Row[]>([]),[templateName,setTemplateName]=useState(''),[busy,setBusy]=useState<string|null>('load'),[message,setMessage]=useState('Loading QR Studio…');
 async function load(){setBusy('load');try{const id=businessId||await currentBusinessId();setBusinessId(id);const[a,t,d]=await Promise.all([listQrAssets(id),listQrTemplates(id),getBusinessDashboard(id)]);const nextAssets=arr(a);setAssets(nextAssets);setTemplates(arr(t));setProfile((d?.profile&&typeof d.profile==='object'?d.profile:{}) as Row);const nextLocations=Array.isArray(d?.locations)?d.locations:[];setLocations(nextLocations);if(!locationId&&nextLocations[0]?.id)setLocationId(String(nextLocations[0].id));setSelected(current=>current?nextAssets.find(row=>assetId(row)===assetId(current))??null:current);setMessage('')}catch(e:any){setMessage(e?.message||'QR Studio unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void load()},[]);
 async function select(row:Row){setSelected(row);setDesign(normalizeQrDesign(row.customization||row.design||{}));const id=assetId(row);if(id){try{const data=await listQrVersions(businessId,id);setVersions(arr(data,'versions').length?arr(data,'versions'):arr(data))}catch{setVersions([])}}}
 async function refreshVersions(id=assetId(selected)){if(!id)return;try{const data=await listQrVersions(businessId,id);setVersions(arr(data,'versions').length?arr(data,'versions'):arr(data))}catch{setVersions([])}}
 async function run(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setMessage('');try{await fn();setMessage(success);await load();await refreshVersions()}catch(e:any){setMessage(e?.message||'QR action failed.')}finally{setBusy(null)}}
 const selectedId=assetId(selected);
 const qrValue=String(selected?.public_url||selected?.landing_url||selected?.code||selected?.qr_code||selectedId||'https://kleenest.app/qr');
 const foreground=design.design.foreground,background=design.design.background,quietZone=Number(design.design.quiet_zone||4),logoScale=Number(design.design.logo.scale||0);
 const contrastRatio=contrast(foreground,background);
 const readiness=contrastRatio>=7&&quietZone>=4&&logoScale<=0.18?'Excellent':contrastRatio>=4.5&&quietZone>=4&&logoScale<=0.22?'Ready':'Needs attention';
 const readinessTone=readiness==='Excellent'?'#1e6a43':readiness==='Ready'?'#6a531e':'#8f2f2f';
 const businessLogo=typeof profile.logo_url==='string'?profile.logo_url:'';
 const logoUrl=design.design.logo.source==='business'?businessLogo:design.design.logo.url??'';
 const qrLogo=logoUrl?{uri:logoUrl}:undefined;
 const active=selected?.active!==false&&selected?.enabled!==false&&String(selected?.status||'active').toLowerCase()!=='inactive';
 async function saveDesign(){if(!selectedId)return;if(contrastRatio<4.5)throw new Error('Increase foreground/background contrast to at least 4.5:1 before saving.');if(quietZone<4)throw new Error('QR quiet zone must be at least four modules.');if(logoScale>0.22)throw new Error('QR logo cannot exceed 22% of QR width.');await upsertQrAsset(businessId,{qrId:selectedId,locationId:String(selected?.location_id||locationId||'')||null,patch:{customization:design},summary:'Scan-safe visual QR design updated from Business mobile'});}
 async function uploadLogo(){setBusy('logo');setMessage('');try{const uploaded=await pickAndUploadQrBranding(businessId);if(uploaded){setDesign(current=>patchLogo(current,{source:'media',url:uploaded.publicUrl,scale:Math.max(0.12,current.design.logo.scale||0),padding:4}));setMessage('Custom QR logo uploaded. Save the versioned design when the scan-readiness check is green.')}}catch(e:any){setMessage(e?.message||'QR logo upload failed.')}finally{setBusy(null)}}
 async function removeSelected(){if(!selectedId)return;setBusy('delete');setMessage('');try{await deleteQrAsset(businessId,selectedId);setSelected(null);setVersions([]);setMessage('QR asset deleted. Existing printed codes should be retired from use.');await load()}catch(e:any){setMessage(e?.message||'QR asset could not be deleted.')}finally{setBusy(null)}}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy==='load'} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>QR STUDIO</Text><Text style={s.title}>Design, version, activate and reuse your QR assets</Text><Text style={s.copy}>Every QR keeps a stable identity, canonical location/action, version history, scan-safe visual contract and analytics attribution underneath the design.</Text></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.section}><Text style={s.sectionTitle}>Create a location QR</Text><View style={s.card}><Text style={s.label}>LOCATION</Text><View style={s.choices}>{locations.slice(0,20).map(row=>{const id=String(row.id||row.location_id||'');return <Choice key={id} value={String(row.name||'Location')} active={id===locationId} onPress={()=>setLocationId(id)}/>})}</View><TextInput style={s.input} value={label} onChangeText={setLabel} placeholder="QR label"/><Action label="Create QR asset" disabled={!locationId||Boolean(busy)} onPress={()=>run('create',()=>createCustomQr(businessId,locationId,label,design),'QR asset created and attached to the selected location.')}/></View></View>
  <View style={s.section}><Text style={s.sectionTitle}>QR library</Text><View style={s.choices}>{assets.map(row=>{const id=assetId(row);return <Pressable key={id} onPress={()=>void select(row)} style={[s.asset,id===selectedId&&s.assetActive]}><Text style={s.assetTitle}>{String(row.label||row.name||'QR asset')}</Text><Text style={s.meta}>{String(row.location_name||row.purpose||'Location action')} · {row.active===false?'inactive':'active'}</Text></Pressable>})}</View></View>
  {selected?<View style={s.section}><Text style={s.sectionTitle}>Visual designer</Text>
   <View style={[s.previewCard,{borderColor:readinessTone}]}><Text style={s.label}>LIVE PREVIEW</Text>{design.frame.cta?<Text style={s.previewCta}>{design.frame.cta}</Text>:null}<View style={{alignItems:'center',backgroundColor, borderRadius:design.frame.style==='rounded'?24:10,padding:Math.max(12,quietZone*2),borderWidth:design.frame.style==='none'?0:2,borderColor:foreground}}><QRCode value={qrValue} size={200} color={validColor(foreground)?foreground:'#173f2d'} backgroundColor={validColor(background)?background:'#ffffff'} quietZone={quietZone} ecl={qrLogo?'H':'M'} logo={qrLogo} logoSize={qrLogo?Math.max(24,Math.round(200*logoScale)):undefined} logoBackgroundColor={background} logoMargin={design.design.logo.padding}/></View>{design.frame.supporting_text?<Text style={s.supporting}>{design.frame.supporting_text}</Text>:null}<Text style={{fontWeight:'900',color:readinessTone}}>Scan readiness: {readiness}</Text><Text style={s.meta}>Contrast {contrastRatio.toFixed(2)}:1 · quiet zone {quietZone} · logo {Math.round(logoScale*100)}%</Text></View>
   <View style={s.card}><Text style={s.cardTitle}>Color & geometry</Text><Text style={s.label}>FOREGROUND</Text><TextInput style={s.input} value={foreground} onChangeText={value=>setDesign(current=>patchDesign(current,{foreground:value}))} autoCapitalize="none"/><Text style={s.label}>BACKGROUND</Text><TextInput style={s.input} value={background} onChangeText={value=>setDesign(current=>patchDesign(current,{background:value}))} autoCapitalize="none"/><Text style={s.label}>MODULE STYLE</Text><View style={s.choices}>{MODULE_STYLES.map(value=><Choice key={value} value={value} active={design.design.module_style===value} onPress={()=>setDesign(current=>patchDesign(current,{module_style:value}))}/>)}</View><Text style={s.label}>FINDER EYES</Text><View style={s.choices}>{EYE_STYLES.map(value=><Choice key={value} value={value} active={design.design.eye_style===value} onPress={()=>setDesign(current=>patchDesign(current,{eye_style:value}))}/>)}</View><Text style={s.label}>QUIET ZONE</Text><View style={s.choices}>{[4,6,8,10,12].map(value=><Choice key={value} value={`${value} modules`} active={quietZone===value} onPress={()=>setDesign(current=>patchDesign(current,{quiet_zone:value}))}/>)}</View></View>
   <View style={s.card}><Text style={s.cardTitle}>Logo & branding</Text><Text style={s.meta}>Logo overlays use high QR error correction and are capped at 22% of QR width.</Text><View style={s.choices}><Choice value="No logo" active={design.design.logo.source==='none'} onPress={()=>setDesign(current=>patchLogo(current,{source:'none',url:null,scale:0}))}/><Choice value="Business logo" active={design.design.logo.source==='business'} onPress={()=>setDesign(current=>patchLogo(current,{source:'business',url:businessLogo||null,scale:0.14,padding:4}))}/><Choice value="Custom logo" active={design.design.logo.source==='media'} onPress={()=>void uploadLogo()}/></View>{businessLogo?<View style={s.brandRow}><Image source={{uri:businessLogo}} style={s.logoThumb}/><Text style={s.meta}>Current Business profile logo</Text></View>:null}<Action quiet label={busy==='logo'?'Uploading…':'Upload custom logo'} disabled={Boolean(busy)} onPress={uploadLogo}/><Text style={s.label}>LOGO SIZE</Text><View style={s.choices}>{[0.10,0.12,0.14,0.16,0.18,0.20,0.22].map(value=><Choice key={value} value={`${Math.round(value*100)}%`} active={Math.abs(logoScale-value)<0.001} onPress={()=>setDesign(current=>patchLogo(current,{scale:value}))}/>)}</View>{logoUrl?<View style={s.brandRow}><Image source={{uri:logoUrl}} style={s.logoThumb}/><Text style={s.meta}>Active logo preview</Text></View>:null}</View>
   <View style={s.card}><Text style={s.cardTitle}>Frame & message</Text><Text style={s.label}>FRAME STYLE</Text><View style={s.choices}>{FRAME_STYLES.map(value=><Choice key={value} value={value} active={design.frame.style===value} onPress={()=>setDesign(current=>({...current,frame:{...current.frame,style:value}}))}/>)}</View><Text style={s.label}>CALL TO ACTION</Text><TextInput style={s.input} value={design.frame.cta??''} onChangeText={value=>setDesign(current=>({...current,frame:{...current.frame,cta:value||null}}))} placeholder="Scan to check in"/><Text style={s.label}>SUPPORTING TEXT</Text><TextInput style={s.input} value={design.frame.supporting_text??''} onChangeText={value=>setDesign(current=>({...current,frame:{...current.frame,supporting_text:value||null}}))} placeholder="Earn XP and help keep restroom data fresh"/></View>
   <View style={s.card}><Text style={s.cardTitle}>Scan readiness</Text><Text style={{fontSize:20,fontWeight:'900',color:readinessTone}}>{readiness}</Text><Text style={s.meta}>Save threshold: contrast ≥ 4.5:1, quiet zone ≥ 4 modules, logo ≤ 22%. Excellent designs use stronger contrast and a logo ≤ 18%.</Text><Action label="Save versioned design" disabled={Boolean(busy)||readiness==='Needs attention'} onPress={()=>run('save-design',saveDesign,'QR design saved as a new version without rotating the printed code.')}/></View>
   <View style={s.card}><Text style={s.cardTitle}>Lifecycle</Text><Text style={s.meta}>Activation controls whether this QR is usable without deleting its version history or attribution.</Text><View style={s.choices}><Action label={active?'Deactivate QR':'Activate QR'} disabled={Boolean(busy)} onPress={()=>run('active',async()=>{await setQrActive(businessId,selectedId,!active);setSelected(current=>current?{...current,active:!active}:current)},active?'QR deactivated.':'QR activated.')}/><Action danger label="Delete QR" disabled={Boolean(busy)} onPress={removeSelected}/></View></View>
   <View style={s.card}><Text style={s.cardTitle}>Reusable template</Text><TextInput style={s.input} placeholder="Template name" value={templateName} onChangeText={setTemplateName}/><Action quiet label="Save current design as template" disabled={!templateName.trim()||Boolean(busy)} onPress={()=>run('template-save',async()=>{await saveQrTemplate(businessId,{name:templateName.trim(),description:'Saved from QR Studio',design});setTemplateName('')},'QR template saved.')}/></View>
   <View style={s.card}><Text style={s.cardTitle}>Version history</Text>{versions.length?versions.map((row,index)=>{const version=Number(row.version||row.version_number||index+1);return <View key={String(row.id||version)} style={s.version}><View style={{flex:1}}><Text style={s.assetTitle}>Version {version}</Text><Text style={s.meta}>{String(row.change_summary||row.created_at||'Saved design')}</Text></View><Action quiet label="Restore" disabled={Boolean(busy)} onPress={()=>run(`restore:${version}`,async()=>{await restoreQrVersion(businessId,selectedId,version);await refreshVersions(selectedId)},`QR restored to version ${version}.`)}/></View>}):<Text style={s.meta}>No prior versions were returned for this asset.</Text>}</View>
  </View>:null}
  <View style={s.section}><Text style={s.sectionTitle}>Templates</Text>{templates.length?templates.map(row=>{const id=String(row.id||row.template_id||'');return <View key={id} style={s.card}><View style={s.cardTop}><View style={{flex:1}}><Text style={s.cardTitle}>{String(row.name||'QR template')}</Text><Text style={s.meta}>{String(row.description||'Reusable QR design')}</Text></View><Action quiet label="Archive" disabled={Boolean(busy)} onPress={()=>run(`archive:${id}`,()=>archiveQrTemplate(businessId,id),'Template archived.')}/></View></View>}):<Text style={s.meta}>Save a visual design above to build a reusable QR template library.</Text>}</View>
 </ScrollView>;
}
function validColor(value:string){return /^#[0-9a-f]{6}$/i.test(value)}
function Choice({value,active,onPress}:{value:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,active&&s.choiceActive]}><Text style={[s.choiceText,active&&s.choiceTextActive]}>{value}</Text></Pressable>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&{color:'#234a36'}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:18,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:19,gap:7},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'800',color:'#5f6d65'},section:{gap:9},sectionTitle:{fontSize:21,fontWeight:'900',color:'#102218'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dbe5de',borderRadius:18,padding:15,gap:10},cardTop:{flexDirection:'row',gap:8,alignItems:'center'},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},label:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#718077'},meta:{fontSize:12,lineHeight:18,color:'#6a796f'},choices:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:11,paddingVertical:8},choiceActive:{backgroundColor:'#173f2d'},choiceText:{fontWeight:'800',color:'#315440'},choiceTextActive:{color:'#fff'},asset:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dbe5de',borderRadius:14,padding:12,minWidth:'47%',flexGrow:1},assetActive:{borderColor:'#173f2d',borderWidth:2},assetTitle:{fontSize:14,fontWeight:'900',color:'#102218'},previewCard:{backgroundColor:'#fff',borderRadius:22,padding:16,gap:12,borderWidth:2,alignItems:'center'},previewCta:{fontSize:20,fontWeight:'900',textAlign:'center',color:'#173024'},supporting:{textAlign:'center',fontSize:13,fontWeight:'700',color:'#42564a'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:10,borderRadius:12,alignItems:'center'},actionQuiet:{backgroundColor:'#edf3ef'},actionDanger:{backgroundColor:'#8d2d2d'},actionText:{fontWeight:'900',color:'#fff'},version:{flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:'#edf0ee',paddingTop:9},brandRow:{flexDirection:'row',alignItems:'center',gap:10},logoThumb:{width:48,height:48,borderRadius:10,backgroundColor:'#f4f7f5'}});
