import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentBusinessId,listBusinessReviews,replyBusinessReview } from '../services/capabilityWorkflows';
import { getLocationReviewEvidence,getReviewEvidence,getReviewPhotos } from '../services/reviews';

type Row=Record<string,any>;
type Review={id:string;location_id?:string;location?:string;location_name?:string;stars?:number;cleanliness_pct?:number;comment?:string;business_reply?:string|null;created_at?:string};
const text=(value:any,fallback='—')=>value===null||value===undefined||String(value).trim()===''?fallback:String(value);
const scalarEntries=(value:any):[string,string][]=>(value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value).filter(([key,item])=>!['id','review_id','location_id','user_id','author_id'].includes(key)&&item!==null&&item!==undefined&&['string','number','boolean'].includes(typeof item)).slice(0,12).map(([key,item])=>[key,String(item)]):[]);
export default function Reviews(){
 const[businessId,setBusinessId]=useState(''),[rows,setRows]=useState<Review[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[photos,setPhotos]=useState<Row[]>([]),[locationEvidence,setLocationEvidence]=useState<Record<string,Row[]>>({}),[evidence,setEvidence]=useState<Record<string,Row>>({}),[busy,setBusy]=useState<string|null>('load'),[message,setMessage]=useState('Loading reviews…');
 async function load(){setBusy('load');try{const id=businessId||await currentBusinessId();setBusinessId(id);const data=await listBusinessReviews(id),next=Array.isArray(data)?data as Review[]:[];setRows(next);const ids=next.map(row=>String(row.id||'')).filter(Boolean),locationIds=[...new Set(next.map(row=>String(row.location_id||'')).filter(Boolean))];const[photoResult,locationResult]=await Promise.all([getReviewPhotos(ids).catch(()=>[]),Promise.all(locationIds.map(async locationId=>[locationId,await getLocationReviewEvidence(locationId,20).catch(()=>[])] as const))]);setPhotos(photoResult as Row[]);setLocationEvidence(Object.fromEntries(locationResult));setMessage('')}catch(e:any){setMessage(e?.message||'Reviews unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void load()},[]);
 async function reply(row:Review){const value=(drafts[row.id]??'').trim();if(!value){setMessage('Write a useful response before publishing it.');return}setBusy(row.id);try{await replyBusinessReview(businessId,row.id,value);setDrafts(current=>({...current,[row.id]:''}));setMessage('Reply published.');await load()}catch(e:any){setMessage(e?.message||'Reply failed.');setBusy(null)}}
 async function inspect(row:Review){const id=String(row.id||'');if(!id)return;setBusy(`evidence:${id}`);try{const next=await getReviewEvidence(id);setEvidence(current=>({...current,[id]:next as Row}));setMessage('Review evidence loaded from the canonical trust pipeline.')}catch(e:any){setMessage(e?.message||'Review evidence unavailable.')}finally{setBusy(null)}}
 const photoCount=useMemo(()=>photos.length,[photos]);
 return <ScrollView refreshControl={<RefreshControl refreshing={busy==='load'} onRefresh={load}/>} keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>REVIEWS + EVIDENCE</Text><Text style={s.title}>Respond with the trust context visible.</Text><Text style={s.copy}>Replies remain Business-authorized while review evidence, location evidence and photos come from the shared Kleenest trust pipeline.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.summary}><Metric label="Reviews" value={rows.length}/><Metric label="Need reply" value={rows.filter(row=>!row.business_reply).length}/><Metric label="Low rating" value={rows.filter(row=>Number(row.stars||0)<3).length}/><Metric label="Review photos" value={photoCount}/></View>
  {rows.length?rows.map(row=>{const id=String(row.id),locationId=String(row.location_id||''),reviewPhotos=photos.filter(photo=>String(photo.review_id||'')===id),locEvidence=locationId?(locationEvidence[locationId]||[]):[],reviewEvidence=evidence[id],facts=scalarEntries(reviewEvidence);return <View key={id} style={[s.card,Number(row.stars||0)<3&&s.attention]}>
    <View style={s.cardTop}><View style={{flex:1}}><Text style={s.cardTitle}>{row.location||row.location_name||'Location review'}</Text><Text style={s.meta}>{formatDate(row.created_at)}</Text></View><Pill label={`${row.stars??'—'}/5`}/></View>
    <View style={s.scoreRow}><Fact label="Rating" value={`${row.stars??'—'}/5`}/><Fact label="Cleanliness" value={row.cleanliness_pct===null||row.cleanliness_pct===undefined?'—':`${row.cleanliness_pct}%`}/><Fact label="Review photos" value={String(reviewPhotos.length)}/><Fact label="Location evidence" value={String(locEvidence.length)}/></View>
    <View style={s.review}><Text style={s.reviewText}>{row.comment?.trim()?`“${row.comment.trim()}”`:'No written comment.'}</Text></View>
    <Pressable disabled={Boolean(busy)} onPress={()=>void inspect(row)} style={[s.secondary,busy===`evidence:${id}`&&s.disabled]}><Text style={s.secondaryText}>{busy===`evidence:${id}`?'Loading evidence…':'Inspect review evidence'}</Text></Pressable>
    {reviewEvidence?<View style={s.evidence}><Text style={s.evidenceTitle}>Canonical review evidence</Text><View style={s.scoreRow}><Fact label="Evidence source" value={text(reviewEvidence.source??reviewEvidence.source_type??reviewEvidence.provenance)}/><Fact label="Evidence confidence" value={text(reviewEvidence.confidence??reviewEvidence.confidence_score??reviewEvidence.trust_score)}/></View>{facts.length?<View style={s.evidenceFacts}>{facts.map(([key,value])=><View key={key} style={s.evidenceRow}><Text style={s.meta}>{key.replaceAll('_',' ')}</Text><Text style={s.evidenceValue}>{value}</Text></View>)}</View>:<Text style={s.meta}>Evidence is attached, but no additional scalar trust fields were returned.</Text>}</View>:null}
    {locEvidence.length?<View style={s.locationEvidence}><Text style={s.evidenceTitle}>Location evidence</Text><Text style={s.meta}>{locEvidence.length} recent evidence row{locEvidence.length===1?'':'s'} support context for this location.</Text>{locEvidence.slice(0,4).map((item,index)=><View key={String(item.id||index)} style={s.locationRow}><Text style={s.locationTitle}>{text(item.evidence_type??item.type??item.source,'Trust evidence')}</Text><Text style={s.meta}>{[item.confidence!=null?`confidence ${item.confidence}`:null,item.observed_at||item.created_at].filter(Boolean).join(' · ')||'Canonical location evidence'}</Text></View>)}</View>:null}
    {row.business_reply?<View style={s.reply}><Text style={s.label}>YOUR CURRENT REPLY</Text><Text style={s.replyText}>{row.business_reply}</Text></View>:null}
    <TextInput color="#132b21" placeholderTextColor="#78877f" style={s.input} multiline value={drafts[id]??''} onChangeText={value=>setDrafts(current=>({...current,[id]:value}))} placeholder={row.business_reply?'Write a replacement reply':'Write a helpful, specific reply'}/><Pressable disabled={Boolean(busy)} onPress={()=>void reply(row)} style={[s.action,busy&&s.disabled]}><Text style={s.actionText}>{busy===id?'Publishing…':row.business_reply?'Update reply':'Publish reply'}</Text></Pressable>
  </View>}):<View style={s.empty}><Text style={s.cardTitle}>No published reviews in the current window</Text><Text style={s.meta}>New review activity will appear here automatically.</Text></View>}
 </ScrollView>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}function Fact({label,value}:{label:string;value:string}){return <View style={s.factWrap}><Text style={s.label}>{label}</Text><Text style={s.fact}>{value}</Text></View>}function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}function formatDate(value?:string){if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
const s=StyleSheet.create({page:{padding:18,gap:14,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:19,gap:7},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'800',color:'#5f6d65'},summary:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'30%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dbe5de',borderRadius:18,padding:15,gap:10},attention:{borderColor:'#e8bb73',backgroundColor:'#fffaf1'},cardTop:{flexDirection:'row',gap:8,alignItems:'flex-start'},cardTitle:{fontSize:18,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#6a796f'},scoreRow:{flexDirection:'row',flexWrap:'wrap',gap:10},factWrap:{flex:1,minWidth:100},label:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#718077',textTransform:'uppercase'},fact:{fontSize:14,fontWeight:'900',color:'#233d2f'},review:{backgroundColor:'#f7f9f7',borderRadius:14,padding:13},reviewText:{fontSize:15,lineHeight:21,color:'#26372e'},secondary:{alignSelf:'flex-start',backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:12,paddingVertical:9},secondaryText:{fontWeight:'900',color:'#244d39'},evidence:{backgroundColor:'#eef5f0',borderRadius:15,padding:13,gap:9},evidenceTitle:{fontSize:14,fontWeight:'900',color:'#244838'},evidenceFacts:{gap:5},evidenceRow:{flexDirection:'row',justifyContent:'space-between',gap:12,paddingTop:5,borderTopWidth:1,borderTopColor:'#dbe7df'},evidenceValue:{fontSize:12,fontWeight:'900',color:'#26372e',textAlign:'right',maxWidth:'55%'},locationEvidence:{backgroundColor:'#f5f7f6',borderRadius:15,padding:13,gap:8},locationRow:{borderTopWidth:1,borderTopColor:'#e4ebe7',paddingTop:7},locationTitle:{fontWeight:'900',color:'#2f4d3d',textTransform:'capitalize'},reply:{backgroundColor:'#edf6f0',borderRadius:14,padding:13,gap:5},replyText:{fontSize:14,lineHeight:20,color:'#284a38'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:12,minHeight:60,backgroundColor:'#fafcfb',color:'#132b21'},action:{backgroundColor:'#173f2d',padding:12,borderRadius:12,alignItems:'center'},actionText:{color:'#fff',fontWeight:'900'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillText:{fontWeight:'900',color:'#28533c'},empty:{backgroundColor:'#eef3f0',borderRadius:16,padding:15,gap:4},disabled:{opacity:.45}});
