import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentBusinessId } from '../services/capabilityWorkflows';
import { getBusinessIntelligenceLayer,getLocationKleenestNow,recordRestroomServiceUpdate,type BusinessIntelligenceLocation,type RestroomServiceEvent } from '../services/intelligenceLayer';
import { useBusinessTheme } from '../services/theme';

const EVENTS:readonly[RestroomServiceEvent,string][]=[
 ['cleaned','Mark cleaned'],['restocked','Restocked'],['inspected','Inspected'],['repaired','Repaired'],['deep_cleaned','Deep clean'],['renovated','Renovated'],['closed','Temporarily closed'],['reopened','Reopened']
] as const;
const pretty=(v:unknown)=>String(v??'').replaceAll('_',' ');
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString():'Not recorded';

export default function ServiceFreshness(){
 const theme=useBusinessTheme();
 const[businessId,setBusinessId]=useState(''),[locations,setLocations]=useState<BusinessIntelligenceLocation[]>([]),[selectedId,setSelectedId]=useState(''),[now,setNow]=useState<any>(null),[recovery,setRecovery]=useState<any[]>([]),[fixFirst,setFixFirst]=useState<any[]>([]),[benchmarks,setBenchmarks]=useState<any[]>([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading service freshness…');
 const selected=useMemo(()=>locations.find(row=>String(row.id)===selectedId)||locations[0]||null,[locations,selectedId]);
 async function load(preferredId?:string){setBusy(true);try{const id=businessId||await currentBusinessId();if(!businessId)setBusinessId(id);const bundle=await getBusinessIntelligenceLayer(id);setLocations(bundle.locations);setRecovery(bundle.recovery);setFixFirst(bundle.fixFirst);setBenchmarks(bundle.benchmarks);const target=preferredId||selectedId||String(bundle.locations[0]?.id||'');if(target){setSelectedId(target);setNow(await getLocationKleenestNow(target));}else setNow(null);setMessage('');}catch(e:any){setMessage(e?.message||'Service freshness unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function choose(locationId:string){setSelectedId(locationId);setBusy(true);try{setNow(await getLocationKleenestNow(locationId));setMessage('')}catch(e:any){setMessage(e?.message||'Could not load this location.')}finally{setBusy(false)}}
 async function record(kind:RestroomServiceEvent){if(!businessId||!selected)return;setBusy(true);try{const result:any=await recordRestroomServiceUpdate(businessId,String(selected.id),kind,note);setNow(result?.now||await getLocationKleenestNow(String(selected.id)));setNote('');setMessage(`${pretty(kind)} recorded. Freshness updated with Business reported provenance; independent confidence is unchanged until outside evidence confirms it.`);await load(String(selected.id));}catch(e:any){setMessage(e?.message||'Service update failed.')}finally{setBusy(false)}}
 const currentBenchmark=benchmarks.find(row=>String(row.location_id)===String(selected?.id));
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>load(selectedId)}/>} contentContainerStyle={[s.page,{backgroundColor:theme.canvas}]}>
  <View style={[s.hero,{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:'#173f2d',borderColor:theme.line}]}><Text style={s.kicker}>CLAIMED RESTROOM SERVICE</Text><Text style={s.title}>Keep freshness current when the bathroom actually gets serviced.</Text><Text style={s.body}>Cleaning, restocking, repair and reopening events can improve freshness immediately. They stay labeled <Text style={{fontWeight:'900'}}>Business reported</Text>; they never become an independent customer confirmation.</Text></View>
  {message?<View style={[s.notice,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.noticeText,{color:theme.ink}]}>{message}</Text></View>:null}
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>LOCATION</Text><View style={s.chips}>{locations.map(location=><Pressable key={location.id} disabled={busy} onPress={()=>choose(String(location.id))} style={[s.chip,{backgroundColor:String(location.id)===String(selected?.id)?theme.accent:theme.surfaceRaised,borderColor:theme.line}]}><Text style={{fontWeight:'900',color:String(location.id)===String(selected?.id)?theme.accentText:theme.ink}}>{location.name||'Location'}</Text><Text style={{fontSize:10,color:String(location.id)===String(selected?.id)?theme.accentText:theme.muted}}>{[location.city,location.state].filter(Boolean).join(', ')}</Text></Pressable>)}</View></View>
  {selected?<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>SERVICE FRESHNESS</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{selected.name||'Selected location'}</Text><View style={s.metrics}><Metric label="Freshness" value={now?.freshness_score==null?'—':`${Math.round(Number(now.freshness_score))}%`} theme={theme}/><Metric label="Confidence" value={now?.confidence_score==null?'—':`${Math.round(Number(now.confidence_score))}%`} theme={theme}/><Metric label="Source" value={pretty(now?.freshness_provenance||'inferred')} theme={theme}/></View>{now?.latest_service?<Text style={[s.meta,{color:theme.muted}]}>Business reported · {pretty(now.latest_service.event_kind)} · {when(now.latest_service.reported_at)}</Text>:<Text style={[s.meta,{color:theme.muted}]}>No Business reported service event yet. Community evidence remains untouched.</Text>}<TextInput value={note} onChangeText={setNote} placeholder="Optional service note" placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]}/><View style={s.actions}>{EVENTS.map(([kind,label])=><Pressable key={kind} disabled={busy} onPress={()=>record(kind)} style={[s.action,{backgroundColor:kind==='closed'?theme.surfaceRaised:theme.accent,borderColor:theme.line}]}><Text style={{fontWeight:'900',fontSize:11,color:kind==='closed'?theme.ink:theme.accentText}}>{label}</Text></Pressable>)}</View></View>:null}
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>TRUST RECOVERY</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Trust Recovery</Text><Text style={[s.meta,{color:theme.muted}]}>A timeline from issue/remediation through real service and fresh evidence. Business activity is identified by provenance.</Text>{recovery.slice(0,8).map((row:any,index)=><View key={`${row.location_id}-${row.occurred_at}-${index}`} style={[s.row,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>{row.name||'Location'} · {pretty(row.event_type)}</Text><Text style={[s.meta,{color:theme.muted}]}>{pretty(row.status)} · {when(row.occurred_at)} · {pretty(row.provenance)}</Text></View><Text style={[s.score,{color:theme.accent}]}>{Math.round(Number(row.current_state?.freshness_score||0))}</Text></View>)}{!recovery.length?<Text style={[s.meta,{color:theme.muted}]}>No recovery/service events yet.</Text>:null}</View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>PRIORITY ACTIONS</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Fix First</Text><Text style={[s.meta,{color:theme.muted}]}>Prioritized from freshness, current cleanliness, unresolved remediation and recent negative evidence.</Text>{fixFirst.slice(0,8).map((row:any)=><Pressable key={row.location_id} onPress={()=>choose(String(row.location_id))} style={[s.row,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>{row.name}</Text><Text style={[s.meta,{color:theme.muted}]}>{Array.isArray(row.reasons)&&row.reasons.length?row.reasons.join(' · '):'No urgent signal'}</Text></View><Text style={[s.score,{color:theme.accent}]}>{Math.round(Number(row.priority_score||0))}</Text></Pressable>)}</View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>LOCAL BENCHMARK</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Freshness in context</Text>{currentBenchmark?<><Text style={[s.big,{color:theme.ink}]}>{Number(currentBenchmark.freshness_delta)>=0?'+':''}{Math.round(Number(currentBenchmark.freshness_delta||0))} pts</Text><Text style={[s.meta,{color:theme.muted}]}>vs nearby {currentBenchmark.city||'market'} average · your freshness {Math.round(Number(currentBenchmark.freshness_score||0))} · local average {Math.round(Number(currentBenchmark.local_freshness_average||0))}</Text></>:<Text style={[s.meta,{color:theme.muted}]}>Select a location to see its local freshness benchmark.</Text>}</View>
 </ScrollView>
}
function Metric({label,value,theme}:{label:string;value:string;theme:any}){return <View style={[s.metric,{backgroundColor:theme.surfaceRaised,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.ink}]}>{value}</Text><Text style={[s.meta,{color:theme.muted}]}>{label}</Text></View>}
const s=StyleSheet.create({page:{padding:16,gap:12,paddingBottom:80},hero:{borderRadius:20,padding:16,gap:7,borderWidth:1},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#bfe0ca'},title:{fontSize:23,lineHeight:28,fontWeight:'900',color:'#fff'},body:{fontSize:12,lineHeight:18,color:'#e3eee7'},notice:{borderWidth:1,borderRadius:14,padding:12},noticeText:{fontSize:12,fontWeight:'800'},card:{borderWidth:1,borderRadius:18,padding:14,gap:10},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},cardTitle:{fontSize:19,fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderRadius:14,paddingHorizontal:10,paddingVertical:8,gap:2},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:100,flexGrow:1,borderWidth:1,borderRadius:14,padding:10},metricValue:{fontSize:18,fontWeight:'900'},meta:{fontSize:11,lineHeight:16},input:{borderWidth:1,borderRadius:13,paddingHorizontal:12,paddingVertical:10,fontSize:13},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{borderWidth:1,borderRadius:999,paddingHorizontal:11,paddingVertical:9},row:{borderTopWidth:1,paddingTop:9,flexDirection:'row',gap:10,alignItems:'center'},rowTitle:{fontSize:13,fontWeight:'900'},score:{fontSize:21,fontWeight:'900'},big:{fontSize:31,fontWeight:'900'}});
