import 'react-native-url-polyfill/auto';
import * as SecureStore from 'expo-secure-store';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const storage = { getItem: (key: string) => SecureStore.getItemAsync(key), setItem: (key: string, value: string) => SecureStore.setItemAsync(key, value), removeItem: (key: string) => SecureStore.deleteItemAsync(key) };
let singleton: SupabaseClient | null = null;
export function getKleenestSupabaseClient(): SupabaseClient { if (singleton) return singleton; const url = process.env.EXPO_PUBLIC_SUPABASE_URL; const key = process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY; if (!url || !key) throw new Error('Missing EXPO_PUBLIC_SUPABASE_URL or EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY.'); singleton = createClient(url, key, { auth: { storage, autoRefreshToken: true, persistSession: true, detectSessionInUrl: false } }); return singleton; }
async function currentMobileUser(){const {data,error}=await getKleenestSupabaseClient().auth.getUser();if(error)throw error;if(!data?.user)throw new Error('Sign in to continue.');return data.user;}
const profileColumns='id,display_name,username,avatar_url,bio,points,level,streak,total_check_ins,total_reviews';
async function hydrateMobileProfiles(ids:string[]){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return [];const {data,error}=await getKleenestSupabaseClient().from('profiles').select(profileColumns).in('id',unique);if(error)throw error;const byId=new Map((data||[]).map((profile:any)=>[String(profile.id),profile]));return unique.map(id=>byId.get(String(id))).filter(Boolean);}
export async function listNearbyRestrooms(latitude:number,longitude:number,radiusMeters=8047,search='',amenityNames:string[]=[]){const names=[...new Set((amenityNames||[]).map(String).map(value=>value.trim()).filter(Boolean))];const{data,error}=await getKleenestSupabaseClient().rpc('map_network_nearby_v1',{p_lat:latitude,p_lng:longitude,p_radius_m:radiusMeters,p_limit:100,p_category:'restroom',p_search:search.trim()||null,p_amenity_names:names.length?names:null});if(error)throw error;return Array.isArray(data)?data:[];}
export async function getMobileAccountSummary(){const{data,error}=await getKleenestSupabaseClient().rpc('user_subscription_summary');if(error)throw error;return data||{};}
export async function listMobilePricingCatalog(){const{data,error}=await getKleenestSupabaseClient().from('pricing_catalog').select('code,name,category,price_cents,interval,price_note,active').eq('active',true).order('category').order('price_cents',{ascending:true,nullsFirst:false});if(error)throw error;return data||[];}
export async function getMobileLocations(ids:string[]){const unique=[...new Set(ids.filter(Boolean).map(String))];if(!unique.length)return[];const{data,error}=await getKleenestSupabaseClient().from('locations').select('id,name,address,city,state,postal_code,latitude,longitude,rating,review_count,cleanliness_pct,accessible,changing_table,verification_status').in('id',unique);if(error)throw error;return data||[];}
export async function getMobileLocation(id:string){const rows=await getMobileLocations([id]);return rows[0]||null;}
export async function listMobileLocationReviews(locationId:string,limit=30){const{data,error}=await getKleenestSupabaseClient().from('reviews').select('id,location_id,user_id,check_in_id,stars,cleanliness_pct,comment,status,business_reply,business_replied_at,helpful_count,created_at').eq('location_id',locationId).eq('status','published').order('created_at',{ascending:false}).limit(limit);if(error)throw error;const reviews=data||[];const profiles=await hydrateMobileProfiles(reviews.map((row:any)=>String(row.user_id||'')).filter(Boolean));const byId=new Map(profiles.map((profile:any)=>[String(profile.id),profile]));return reviews.map((review:any)=>({...review,contributor:review.user_id?byId.get(String(review.user_id))||null:null}));}
export async function listMobileFavoriteLocations(){const{data,error}=await getKleenestSupabaseClient().rpc('my_favorite_locations');if(error)throw error;return Array.isArray(data)?data:[];}
export async function toggleMobileFavorite(locationId:string){const{data,error}=await getKleenestSupabaseClient().rpc('kleenest_toggle_favorite',{p_location_id:locationId});if(error)throw error;return data;}
export async function mobileCheckIn(locationId:string,latitude:number,longitude:number){const{data,error}=await getKleenestSupabaseClient().rpc('kleenest_map_check_in',{p_location_id:locationId,p_lat:latitude,p_lng:longitude});if(error)throw error;return data;}
export async function createMobileReview(input:{locationId:string;checkInId?:string|null;stars:number;cleanlinessPct?:number|null;comment?:string}){const{data,error}=await getKleenestSupabaseClient().rpc('create_review',{p_location_id:input.locationId,p_check_in_id:input.checkInId||null,p_stars:Number(input.stars),p_cleanliness_pct:input.cleanlinessPct==null?null:Number(input.cleanlinessPct),p_comment:input.comment?.trim()||null});if(error)throw error;return data;}
export async function getMobileProgressionDashboard(){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('gamification_dashboard');if(error)throw error;return data||{};}
export async function getMobileProgressionSummary(){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('get_progression_summary');if(error)throw error;return data||{};}
export async function listMobileLeaderboard(limit=25){const{data,error}=await getKleenestSupabaseClient().rpc('get_user_leaderboard',{p_limit:Math.min(Math.max(limit,1),100)});if(error)throw error;return Array.isArray(data)?data:[];}
export async function getMobileLeaderboardPosition(){const user=await currentMobileUser();const rows=await listMobileLeaderboard(100);const index=rows.findIndex((row:any)=>String(row.user_id)===String(user.id));return index>=0?{rank:Number(rows[index].rank||index+1),entry:rows[index]}:{rank:null,entry:null};}
export async function listMobileBadges(){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('get_my_progression_badges');if(error)throw error;return(Array.isArray(data)?data:[]).map((row:any)=>({...row.badge,id:row.id||row.badge?.id,earned_at:row.earned_at}));}
export async function listMobileBadgeCatalog(){const{data,error}=await getKleenestSupabaseClient().from('badges').select('id,code,name,description,icon,criteria,created_at').order('created_at',{ascending:true});if(error)throw error;return(data||[]).filter((badge:any)=>badge?.criteria?.catalog_hidden!==true);}
export async function listMobileChallenges(limit=25){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('get_progression_challenges',{p_limit:Math.min(Math.max(limit,1),100)});if(error)throw error;return Array.isArray(data)?data:[];}
export async function listMobileChallengeProgress(){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('get_my_progression_metric_summary');if(error)throw error;return Array.isArray(data)?data:[];}
export async function listMobileMilestones(){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('get_my_progression_milestones');if(error)throw error;return Array.isArray(data)?data:[];}
export async function completeMobileChallenge(challengeId:string){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('complete_progression_challenge',{p_challenge_id:challengeId});if(error)throw error;return data;}
export async function listMobileContests(limit=10){const{data,error}=await getKleenestSupabaseClient().rpc('home_active_contests',{p_limit:Math.min(Math.max(limit,1),100)});if(error)throw error;return Array.isArray(data)?data:[];}
export async function joinMobileContest(contestId:string){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('join_contest',{p_contest_id:contestId});if(error)throw error;return data;}
export async function listMobileAvailableQuests(limit=12){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('quest_list_available',{p_limit:Math.min(Math.max(limit,1),50)});if(error)throw error;return Array.isArray(data)?data:[];}
export async function listMobileActiveQuests(limit=12){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('quest_my_active_progress',{p_limit:Math.min(Math.max(limit,1),50)});if(error)throw error;return Array.isArray(data)?data:[];}
export async function startMobileQuest(questId:string){await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().rpc('quest_start',{p_quest_id:questId});if(error)throw error;return data;}
export async function listMobileActivity(limit=40){const user=await currentMobileUser();const client=getKleenestSupabaseClient();const[checkins,reviews,social]=await Promise.all([client.from('check_ins').select('id,location_id,checked_in_at,verification_method,points_awarded').eq('user_id',user.id).order('checked_in_at',{ascending:false}).limit(limit),client.from('reviews').select('id,location_id,stars,cleanliness_pct,comment,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(limit),client.from('social_activity').select('id,user_id,actor_user_id,activity_type,location_id,metadata,created_at').order('created_at',{ascending:false}).limit(limit)]);for(const result of[checkins,reviews,social])if(result.error)throw result.error;const events=[...(checkins.data||[]).map((row:any)=>({id:`checkin:${row.id}`,kind:'checkin',locationId:row.location_id,createdAt:row.checked_in_at,title:'Checked in',detail:[row.verification_method,row.points_awarded?`+${row.points_awarded} pts`:null].filter(Boolean).join(' · ')})),...(reviews.data||[]).map((row:any)=>({id:`review:${row.id}`,kind:'review',locationId:row.location_id,createdAt:row.created_at,title:`Left a ${row.stars}★ review`,detail:row.comment||(row.cleanliness_pct!=null?`${row.cleanliness_pct}% cleanliness`:'' )})),...(social.data||[]).map((row:any)=>({id:`social:${row.id}`,kind:'social',locationId:row.location_id,createdAt:row.created_at,title:String(row.activity_type||'Community activity').replaceAll('_',' '),detail:row.metadata?.summary||''}))].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).slice(0,limit);const locations=await getMobileLocations(events.map(event=>event.locationId).filter(Boolean));const byId=new Map(locations.map((row:any)=>[String(row.id),row]));return events.map(event=>({...event,location:event.locationId?byId.get(String(event.locationId))||null:null}));}
export async function listMobileNotifications(limit=50){const user=await currentMobileUser();const{data,error}=await getKleenestSupabaseClient().from('notifications').select('id,user_id,type,title,body,data,read_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[];}
export async function markMobileNotificationRead(id:string){const user=await currentMobileUser();const{error}=await getKleenestSupabaseClient().from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id);if(error)throw error;}
export async function markAllMobileNotificationsRead(){const user=await currentMobileUser();const{error}=await getKleenestSupabaseClient().from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);if(error)throw error;}
export async function searchMobilePeople(term:string){const query=String(term||'').trim();if(query.length<2)return[];const pattern=`%${query.replace(/[%_]/g,'\\$&')}%`;const client=getKleenestSupabaseClient();const[byName,byUsername]=await Promise.all([client.from('profiles').select(profileColumns).ilike('display_name',pattern).limit(20),client.from('profiles').select(profileColumns).ilike('username',pattern).limit(20)]);if(byName.error)throw byName.error;if(byUsername.error)throw byUsername.error;const merged=new Map<string,any>();for(const profile of[...(byName.data||[]),...(byUsername.data||[])])merged.set(String(profile.id),profile);return[...merged.values()].slice(0,25);}
export async function listMobileFollowing(){const{data,error}=await getKleenestSupabaseClient().rpc('list_following_users',{p_limit:100});if(error)throw error;return hydrateMobileProfiles((data||[]).map((row:any)=>String(row.following_id)));}
export async function listMobileFollowers(){const{data,error}=await getKleenestSupabaseClient().rpc('list_follower_users',{p_limit:100});if(error)throw error;return hydrateMobileProfiles((data||[]).map((row:any)=>String(row.follower_id)));}
export async function toggleMobileFollow(userId:string){const{data,error}=await getKleenestSupabaseClient().rpc('toggle_follow_user',{p_target_user_id:userId});if(error)throw error;return data;}
export async function buildMobileRoute(originCoordinates:[number,number],stopLocationIds:string[]){const ids=[...new Set(stopLocationIds.filter(Boolean).map(String))];if(!ids.length)throw new Error('Add at least one stop before building the route.');const locations=await getMobileLocations(ids);const byId=new Map(locations.map((row:any)=>[String(row.id),row]));const ordered=ids.map(id=>byId.get(id));if(ordered.some(row=>!row))throw new Error('One or more route stops are unavailable.');const stopCoordinates=ordered.map((row:any)=>[Number(row.longitude),Number(row.latitude)]as[number,number]);if(stopCoordinates.some(([lng,lat])=>!Number.isFinite(lng)||!Number.isFinite(lat)))throw new Error('One or more stops do not have valid coordinates.');const points=[originCoordinates,...stopCoordinates];const response=await fetch(`https://router.project-osrm.org/route/v1/driving/${points.map(([lng,lat])=>`${lng},${lat}`).join(';')}?overview=full&geometries=geojson&steps=true`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Routing provider could not build this route.');const payload=await response.json();const route=payload?.routes?.[0];if(!route)throw new Error('No drivable route was found through those stops.');return{originCoordinates,stopLocationIds:ids,stopLocations:ordered,stopCoordinates,destinationCoordinates:stopCoordinates.at(-1),geometry:route.geometry,distanceMiles:+(route.distance/1609.344).toFixed(1),durationMinutes:Math.max(1,Math.round(route.duration/60)),provider:'osrm'};}
export async function persistMobileRoute(route:any,name='My route'){const{data,error}=await getKleenestSupabaseClient().rpc('create_route_plan',{p_name:name,p_start_lat:+route.originCoordinates[1],p_start_lng:+route.originCoordinates[0],p_end_lat:+route.destinationCoordinates[1],p_end_lng:+route.destinationCoordinates[0],p_distance_miles:+route.distanceMiles,p_estimated_minutes:+route.durationMinutes,p_stop_location_ids:route.stopLocationIds});if(error)throw error;return{...route,routeId:data?.route_id||data?.id||data};}
export function mobileNavigationUrl(route:any){if(!route?.stopCoordinates?.length)return'';const origin=`${route.originCoordinates[1]},${route.originCoordinates[0]}`;const points=route.stopCoordinates.map(([lng,lat]:[number,number])=>`${lat},${lng}`);const destination=points.at(-1);const waypoints=points.slice(0,-1).join('|');const params=new URLSearchParams({api:'1',origin,destination,travelmode:'driving'});if(waypoints)params.set('waypoints',waypoints);return`https://www.google.com/maps/dir/?${params.toString()}`;}
export const KLEENEST_APP_VERSION='0.1.0';
