import { getKleenestSupabaseClient } from './client';

export async function listNearbyRestrooms(latitude:number,longitude:number,radiusMeters=8047,search='',amenityNames:string[]=[]){const names=[...new Set((amenityNames||[]).map(String).map(value=>value.trim()).filter(Boolean))];const{data,error}=await getKleenestSupabaseClient().rpc('map_network_nearby_v2',{p_lat:latitude,p_lng:longitude,p_radius_m:radiusMeters,p_limit:100,p_category:'restroom',p_search:search.trim()||null,p_amenity_names:names.length?names:null});if(error)throw error;return Array.isArray(data)?data:[];}
export async function getMobileLocations(ids:string[]){const unique=[...new Set(ids.filter(Boolean).map(String))];if(!unique.length)return[];const client=getKleenestSupabaseClient();const rows=await Promise.all(unique.map(async id=>{const{data,error}=await client.rpc('mobile_location_detail_v1',{p_location_id:id});if(error)throw error;if(!data)return null;const row:any=data;return{...row,geofence_radius_m:row.geofence_radius_m};}));return rows.filter(Boolean);}
export async function getMobileLocation(id:string){const{data,error}=await getKleenestSupabaseClient().rpc('mobile_location_detail_v1',{p_location_id:id});if(error)throw error;return data||null;}
export async function listMobileFavoriteLocations(){const{data,error}=await getKleenestSupabaseClient().rpc('my_favorite_locations');if(error)throw error;return Array.isArray(data)?data:[];}
export async function toggleMobileFavorite(locationId:string){const{data,error}=await getKleenestSupabaseClient().rpc('kleenest_toggle_favorite',{p_location_id:locationId});if(error)throw error;return data;}
export async function mobileCheckIn(locationId:string,latitude:number,longitude:number,restroomFacilityId?:string|null){const client=getKleenestSupabaseClient();const{data,error}=await client.rpc('kleenest_map_check_in',{p_location_id:locationId,p_lat:latitude,p_lng:longitude});if(error)throw error;const checkInId=String((data as any)?.check_in_id||(data as any)?.id||'');if(restroomFacilityId&&checkInId){const{data:facilityData,error:facilityError}=await client.rpc('assign_check_in_restroom_facility',{p_check_in_id:checkInId,p_restroom_facility_id:restroomFacilityId});if(facilityError)throw facilityError;return{...((data as any)||{}),restroom_facility_id:restroomFacilityId,facility:facilityData||null};}return data;}
export async function createMobileReview(input:{locationId:string;checkInId?:string|null;stars:number;cleanlinessPct?:number|null;comment?:string}){const{data,error}=await getKleenestSupabaseClient().rpc('create_review',{p_location_id:input.locationId,p_check_in_id:input.checkInId||null,p_stars:Number(input.stars),p_cleanliness_pct:input.cleanlinessPct==null?null:Number(input.cleanlinessPct),p_comment:input.comment?.trim()||null});if(error)throw error;return data;}
