alter policy "admin_capability_audit_admin_read" on public.admin_capability_audit using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));
alter policy "business_growth_signals_read_member" on public.business_growth_signals using (exists (select 1 from public.business_members bm where bm.business_id = business_growth_signals.business_id and bm.user_id = (select auth.uid())));
alter policy "kleenest_business_progression_events_read" on public.business_progression_events using (business_can_manage(business_id) or user_id = (select auth.uid()));
alter policy "capability_audit_runs_owner_select" on public.capability_audit_runs using (is_platform_owner((select auth.uid())));
alter policy "contest_entries_owner_delete" on public.contest_entries using (user_id = (select auth.uid()));
alter policy "contest_entries_owner_select" on public.contest_entries using (user_id = (select auth.uid()));
alter policy "contests_read" on public.contests using ((status = any (array['scheduled'::text,'active'::text,'completed'::text])) or created_by = (select auth.uid()));
alter policy "demo identities admin read" on public.demo_identity_registry using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "business_engagement_attributions_admin_read" on public.business_engagement_attributions using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "enterprise_partner_allocations_admin_read" on public.enterprise_partner_allocations using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "enterprise_partner_campaign_outcomes_admin_read" on public.enterprise_partner_campaign_outcomes using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "enterprise_partner_campaigns_admin_read" on public.enterprise_partner_campaigns using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "enterprise_partner_network_members_admin_read" on public.enterprise_partner_network_members using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "enterprise_partner_networks_admin_read" on public.enterprise_partner_networks using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "admin_read_public_data_datasets" on public.external_data_datasets using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and (p.is_admin = true or (p.role)::text = any (array['admin'::text,'super_admin'::text,'platform_admin'::text,'owner'::text]))));
alter policy "admin_read_import_jobs" on public.external_import_jobs using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and (p.is_admin = true or (p.role)::text = any (array['admin'::text,'super_admin'::text,'platform_admin'::text,'owner'::text]))));
alter policy "kleenest_family_accounts_owner" on public.family_accounts using (owner_user_id = (select auth.uid()));
alter policy "kleenest_family_invites_sender" on public.family_invites using (invited_by = (select auth.uid()));
alter policy "family_members_access" on public.family_members using ((user_id = (select auth.uid())) or exists (select 1 from public.family_groups g where g.id = family_members.group_id and g.owner_id = (select auth.uid())));
alter policy "users can insert own intelligence notification deliveries" on public.intelligence_notification_deliveries with check ((select auth.uid()) = user_id);
alter policy "users can read own intelligence notification deliveries" on public.intelligence_notification_deliveries using ((select auth.uid()) = user_id);
alter policy "live_network_events_insert_authenticated" on public.live_network_events with check (actor_id = (select auth.uid()));
alter policy "location_ingestion_admin_read" on public.location_ingestion_jobs using (((select auth.uid()) is not null) and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and coalesce(p.is_admin,false)));
alter policy "kleenest_location_route_events_owner" on public.location_route_events using (user_id = (select auth.uid()));
alter policy "network_leaderboard_participation_actor_or_admin_read" on public.network_leaderboard_participation using ((actor_id = (select auth.uid())) or is_platform_owner((select auth.uid())));
alter policy "program owners read scoped locations" on public.partner_program_locations using (exists (select 1 from public.partner_programs pp join public.business_members bm on bm.business_id = pp.business_id where pp.id = partner_program_locations.partner_program_id and bm.user_id = (select auth.uid())));
alter policy "users read own partner program memberships" on public.partner_program_memberships using (user_id = (select auth.uid()));
