import { usePlatformTheme } from '../services/theme';
import { useEffect,useState } from 'react';
import { RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { getOwnerAuditBundle } from '../services/ownerAdmin';
const rows=(v:any)=>Array.isArray(v)?v:v&&typeof v==='object'?Object.values(v).flatMap(x=>Array.isArray(x)?x:[]):[];
export default function Audit(){
  const theme=usePlatformTheme();const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Running control-plane audit…');async function load(){setBusy(true);try{setData(await getOwnerAuditBundle());setMessage('Live capability and platform activity audit completed.')}catch(e:any){setMessage(e?.message||'Audit unavailable.')}finally{setBusy(false)}}useEffect(()=>{void load()},[]);const domains=rows(data?.domains),activity=rows(data?.activity),raw=rows(data?.raw);return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={[s.page,{backgroundColor:theme.canvas},{backgroundColor:theme.canvas}]}><View style={[s.hero,{backgroundColor:theme.accent,borderColor:theme.line},{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:theme.accent,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accentText},{color:theme.accentText}]}>AUDITED CONTROL PLANE</Text><Text style={[s.title,{color:theme.accentText},{color:theme.accentText}]}>Live platform audit</Text><Text style={[s.copy,{color:theme.accentText,opacity:.88},{color:theme.accentText,opacity:.88}]}>Verify capability uniqueness, raw-schema drift and recent administrator activity against the current production backend.</Text></View><Text style={[s.message,{color:theme.muted},{color:theme.muted}]}>{message}</Text><View style={s.metrics}><Metric label="Domain findings" value={domains.length}/><Metric label="Schema findings" value={raw.length}/><Metric label="24h admin activity" value={activity.length}/></View><Section title="Capability domain findings" rows={domains}/><Section title="Raw schema findings" rows={raw}/><Section title="Recent admin activity" rows={activity}/></ScrollView>}
function Section({title,rows}:{title:string;rows:any[]}){
  const theme=usePlatformTheme();return <View style={{gap:8}}><Text style={[s.sectionTitle,{color:theme.ink},{color:theme.ink}]}>{title}</Text>{rows.length?rows.slice(0,100).map((r:any,i:number)=><View key={String(r.id||r.domain||r.created_at||i)} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line},{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.cardTitle,{color:theme.ink},{color:theme.ink}]}>{String(r.action||r.domain||r.resource||r.table_name||r.capability||'Audit event').replaceAll('_',' ')}</Text><Text style={[s.meta,{color:theme.muted},{color:theme.muted}]}>{[r.status,r.reason,r.actor_email,r.admin_user_id,r.issue,r.message].filter(Boolean).map(String).join(' · ')||'Recorded by live audit'}</Text>{r.created_at?<Text style={[s.date,{color:theme.muted},{color:theme.muted}]}>{new Date(r.created_at).toLocaleString()}</Text>:null}</View>):<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line},{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.meta,{color:theme.muted},{color:theme.muted}]}>No findings in this section.</Text></View>}</View>}function Metric({label,value}:{label:string;value:number}){
  const theme=usePlatformTheme();return <View style={[s.metric,{backgroundColor:theme.surface,borderColor:theme.line},{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.accent},{color:theme.accent}]}>{value}</Text><Text style={[s.meta,{color:theme.muted},{color:theme.muted}]}>{label}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:16,paddingBottom:70,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#102218',padding:18,borderRadius:22,gap:6},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#b9d2c2'},title:{fontSize:28,fontWeight:'900',color:'#fff'},copy:{color:'#dce9e1',lineHeight:20},message:{fontWeight:'800',color:'#355345'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:23,fontWeight:'900',color:'#173f2d'},sectionTitle:{fontSize:20,fontWeight:'900',color:'#102218'},card:{backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dbe5de',gap:4},cardTitle:{fontSize:16,fontWeight:'900',color:'#102218',textTransform:'capitalize'},meta:{fontSize:12,lineHeight:18,color:'#66766e'},date:{fontSize:10,color:'#829087'}});