import { useEffect,useMemo,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { assignBusinessMember,getBusinessAdminDetail,getPlatformDashboard,removeBusinessMember,searchBusinesses,setBusinessAccess,setBusinessVerification } from '../services/product';
import { searchOwnerUsers } from '../services/ownerAdmin';

type Row=Record<string,any>;
const asRows=(value:unknown):Row[]=>Array.isArray(value)?value.filter((row):row is Row=>Boolean(row&&typeof row==='object')):[];
const text=(row:Row,...keys:string[])=>{for(const key of keys){const value=row[key];if(value!==null&&value!==undefined&&String(value).trim())return String(value)}return''};
const roles=['owner','admin','manager','staff','analyst'];
const tiers=['standard','growth','fleet','enterprise'];

export default function Businesses(){
 const[data,setData]=useState<any>(null),[results,setResults]=useState<Row[]>([]),[query,setQuery]=useState(''),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState<string|null>('load'),[message,setMessage]=useState('Loading business administration…'),[tier,setTier]=useState('standard'),[fleetEnabled,setFleetEnabled]=useState(false),[enterpriseEnabled,setEnterpriseEnabled]=useState(false),[reason,setReason]=useState('KleenestOS business access review'),[peopleQuery,setPeopleQuery]=useState(''),[people,setPeople]=useState<Row[]>([]),[memberRole,setMemberRole]=useState('manager');
 async function load(){setBusy('load');try{setData(await getPlatformDashboard());setMessage('')}catch(e:any){setMessage(e?.message||'Businesses unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void load()},[]);
 const pending=useMemo(()=>asRows(data?.pending),[data]);
 async function run(key:string,fn:()=>Promise<unknown>,success:string,refreshDetail=true){setBusy(key);setMessage('');try{await fn();setMessage(success);await load();if(refreshDetail&&detail?.business?.id)await selectBusiness({id:detail.business.id})}catch(e:any){setMessage(e?.message||'Administrative action failed.');setBusy(null)}}
 async function findBusinesses(){const value=query.trim();if(!value){setResults([]);return;}setBusy('search-business');try{setResults(asRows(await searchBusinesses(value)));setMessage('')}catch(e:any){setMessage(e?.message||'Business search failed.')}finally{setBusy(null)}}
 async function selectBusiness(row:Row){const id=text(row,'id','business_id');if(!id)return;setBusy(`business:${id}`);try{const next:any=await getBusinessAdminDetail(id);setDetail(next);const access=next?.access??{};setTier(String(access.business_tier||next?.business?.business_tier||'standard'));setFleetEnabled(Boolean(access.fleet_enabled));setEnterpriseEnabled(Boolean(access.enterprise_enabled));setPeople([]);setPeopleQuery('');setMessage('')}catch(e:any){setMessage(e?.message||'Business detail unavailable.')}finally{setBusy(null)}}
 async function saveAccess(){const id=String(detail?.business?.id||'');if(!id)return;await run('save-access',()=>setBusinessAccess(id,tier,fleetEnabled,enterpriseEnabled,reason),`Access updated for ${detail.business.name||'business'}.`)}
 async function findPeople(){const value=peopleQuery.trim();if(!value)return setPeople([]);setBusy('search-people');try{setPeople(asRows(await searchOwnerUsers(value)));setMessage('')}catch(e:any){setMessage(e?.message||'People search failed.')}finally{setBusy(null)}}
 function removeMember(row:Row){const businessId=String(detail?.business?.id||''),userId=text(row,'user_id','id');if(!businessId||!userId)return;Alert.alert('Remove business member?',`${text(row,'display_name','username')||'This account'} will lose this Business workspace membership.`,[{text:'Cancel',style:'cancel'},{text:'Remove member',style:'destructive',onPress:()=>void run(`remove:${userId}`,()=>removeBusinessMember(businessId,userId),'Business member removed.')}]);}
 const business=detail?.business??null,access=detail?.access??null,members=asRows(detail?.members),locations=asRows(detail?.locations);
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy==='load'} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>BUSINESS GOVERNANCE</Text><Text style={s.heroTitle}>Business access control</Text><Text style={s.heroCopy}>Find any Business workspace, review verification and locations, operate Fleet/Enterprise entitlement state, and manage workspace membership from one platform-owner surface.</Text></View>
  {message?<View style={s.banner}><Text style={s.bannerText}>{message}</Text></View>:null}
  <View style={s.metrics}><Metric label="Pending review" value={pending.length}/><Metric label="Selected locations" value={locations.length}/><Metric label="Selected members" value={members.length}/></View>
  <View style={s.card}><Text style={s.cardTitle}>Find a business</Text><View style={s.row}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={findBusinesses} placeholder="Business name or UUID" style={[s.input,{flex:1}]}/><Action label="Search" disabled={Boolean(busy)||!query.trim()} onPress={findBusinesses}/></View>{results.map(row=><BusinessResult key={text(row,'id')} row={row} selected={text(row,'id')===String(business?.id||'')} onPress={()=>void selectBusiness(row)}/>)}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Pending verification</Text>{pending.length?pending.slice(0,20).map(row=><BusinessResult key={text(row,'id','business_id')} row={row} selected={text(row,'id','business_id')===String(business?.id||'')} onPress={()=>void selectBusiness(row)}/>):<Empty title="Review queue clear" body="New business verification requests will appear here."/>}</View>
  {business?<>
   <View style={s.section}><Text style={s.sectionTitle}>{String(business.name||'Business')}</Text><Text style={s.sectionCopy}>Verification and commercial capability state are intentionally separate. Fleet and Enterprise can be operated explicitly without pretending a tier change is identity verification.</Text>
    <View style={s.card}><View style={s.spread}><View style={{flex:1}}><Text style={s.cardTitle}>{String(business.name||'Business')}</Text><Text style={s.meta}>{String(business.email||business.website||business.phone||'No contact supplied')}</Text></View><Pill label={String(business.verification_status||'pending').toUpperCase()}/></View><View style={s.actions}><Action label="Verify" disabled={Boolean(busy)||business.verification_status==='verified'} onPress={()=>run('verify',()=>setBusinessVerification(business.id,'verified'),'Business verified.')}/><Action quiet label="Reject" disabled={Boolean(busy)} onPress={()=>run('reject',()=>setBusinessVerification(business.id,'rejected'),'Business rejected.')}/></View></View>
   </View>
   <View style={s.section}><Text style={s.sectionTitle}>Product access</Text><View style={s.card}><Text style={s.label}>BUSINESS TIER</Text><View style={s.chips}>{tiers.map(value=><Chip key={value} label={value} active={tier===value} onPress={()=>setTier(value)}/>)}</View><Text style={s.label}>CAPABILITIES</Text><View style={s.toggles}><Toggle label="Fleet enabled" value={fleetEnabled} onPress={()=>setFleetEnabled(value=>!value)}/><Toggle label="Enterprise enabled" value={enterpriseEnabled} onPress={()=>setEnterpriseEnabled(value=>!value)}/></View><Text style={s.meta}>Current authority: Fleet {access?.fleet_enabled?'enabled':'disabled'} · Enterprise {access?.enterprise_enabled?'enabled':'disabled'} · owner {access?.owner_user_id?'linked':'not linked'}.</Text><TextInput value={reason} onChangeText={setReason} placeholder="Audit reason" style={s.input}/><Action label="Save business access" disabled={Boolean(busy)||!reason.trim()} onPress={saveAccess}/></View></View>
   <View style={s.section}><Text style={s.sectionTitle}>Workspace members</Text><View style={s.card}><Text style={s.cardTitle}>Add member</Text><View style={s.row}><TextInput value={peopleQuery} onChangeText={setPeopleQuery} onSubmitEditing={findPeople} placeholder="Search account name, username or email" style={[s.input,{flex:1}]}/><Action label="Find" disabled={Boolean(busy)||!peopleQuery.trim()} onPress={findPeople}/></View><View style={s.chips}>{roles.map(value=><Chip key={value} label={value} active={memberRole===value} onPress={()=>setMemberRole(value)}/>)}</View>{people.slice(0,10).map(row=>{const userId=text(row,'id','user_id');return <View key={userId} style={s.person}><View style={{flex:1}}><Text style={s.cardTitle}>{text(row,'display_name','username','email')||'Account'}</Text><Text style={s.meta}>{text(row,'username','email','role')||userId}</Text></View><Action label="Add member" disabled={Boolean(busy)||!userId} onPress={()=>run(`add:${userId}`,()=>assignBusinessMember(business.id,userId,memberRole),`${text(row,'display_name','username')||'Account'} added as ${memberRole}.`)}/></View>})}</View>{members.map(row=><View key={text(row,'user_id')} style={s.card}><View style={s.spread}><View style={{flex:1}}><Text style={s.cardTitle}>{text(row,'display_name','username')||'Business member'}</Text><Text style={s.meta}>{text(row,'username')||text(row,'user_id')}</Text></View><Pill label={text(row,'role').toUpperCase()||'MEMBER'}/></View><Action danger label="Remove member" disabled={Boolean(busy)||text(row,'role')==='owner'} onPress={()=>removeMember(row)}/>{text(row,'role')==='owner'?<Text style={s.meta}>Owner membership is protected here. Transfer ownership through its dedicated ownership workflow rather than removing the last owner.</Text>:null}</View>)}</View>
   <View style={s.section}><Text style={s.sectionTitle}>Locations</Text>{locations.length?locations.map(row=><View key={text(row,'id')} style={s.card}><Text style={s.cardTitle}>{text(row,'name')||'Location'}</Text><Text style={s.meta}>{[text(row,'address'),text(row,'city'),text(row,'state')].filter(Boolean).join(', ')||'No address supplied'}</Text><Pill label={(text(row,'verification_status')||'unknown').toUpperCase()}/></View>):<Empty title="No linked locations" body="This Business currently has no canonical or claimed locations."/>}</View>
  </>:null}
 </ScrollView>;
}
function BusinessResult({row,selected,onPress}:{row:Row;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.result,selected&&s.resultSelected]}><View style={{flex:1}}><Text style={s.cardTitle}>{text(row,'name')||'Business'}</Text><Text style={s.meta}>{text(row,'verification_status')||'pending'} · {text(row,'business_tier')||'standard'} · {Number(row.location_count||0)} locations · {Number(row.member_count||0)} members</Text></View><Text style={s.open}>OPEN ›</Text></Pressable>}
function Metric({label,value}:{label:string;value:string|number}){return <View style={s.metric}><Text style={s.metricValue}>{String(value)}</Text><Text style={s.meta}>{label}</Text></View>}
function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Toggle({label,value,onPress}:{label:string;value:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.toggle,value&&s.toggleOn]}><Text style={[s.toggleText,value&&s.toggleTextOn]}>{value?'✓ ':''}{label}</Text></Pressable>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&{opacity:.42}]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
function Empty({title,body}:{title:string;body:string}){return <View style={s.empty}><Text style={s.cardTitle}>{title}</Text><Text style={s.meta}>{body}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:18,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#132a20',padding:19,borderRadius:24,gap:7},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:'#badbc8'},heroTitle:{fontSize:27,fontWeight:'900',color:'#fff'},heroCopy:{fontSize:14,lineHeight:21,color:'#dce8e1'},banner:{backgroundColor:'#eef3f0',borderRadius:14,padding:12},bannerText:{fontWeight:'800',color:'#365245'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'30%',flexGrow:1,backgroundColor:'#fff',borderRadius:17,padding:14,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:23,fontWeight:'900',color:'#173f2d'},section:{gap:9},sectionTitle:{fontSize:21,fontWeight:'900',color:'#102218'},sectionCopy:{color:'#617068',lineHeight:19},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:11,borderWidth:1,borderColor:'#dbe5de'},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#6a796f'},row:{flexDirection:'row',gap:8,alignItems:'center'},spread:{flexDirection:'row',gap:8,alignItems:'flex-start',justifyContent:'space-between'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},actionQuiet:{backgroundColor:'#edf3ef'},actionDanger:{backgroundColor:'#8d2d2d'},actionText:{fontWeight:'900',color:'#fff'},actionQuietText:{color:'#244d39'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6,alignSelf:'flex-start'},pillText:{fontSize:10,fontWeight:'900',color:'#28533c'},label:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#718077'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:'#173f2d'},chipText:{fontWeight:'800',color:'#365645',textTransform:'capitalize'},chipTextOn:{color:'#fff'},toggles:{flexDirection:'row',flexWrap:'wrap',gap:8},toggle:{borderWidth:1,borderColor:'#cad8d0',borderRadius:14,paddingHorizontal:12,paddingVertical:10},toggleOn:{backgroundColor:'#dff0e6',borderColor:'#75a98a'},toggleText:{fontWeight:'900',color:'#66766e'},toggleTextOn:{color:'#214d36'},result:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dbe5de',borderRadius:14,padding:12,flexDirection:'row',alignItems:'center',gap:8},resultSelected:{borderColor:'#173f2d',borderWidth:2},open:{fontSize:11,fontWeight:'900',color:'#24573d'},person:{borderTopWidth:1,borderTopColor:'#edf0ee',paddingTop:10,flexDirection:'row',alignItems:'center',gap:8},empty:{backgroundColor:'#eef3f0',borderRadius:16,padding:15,gap:4}});
