import { router } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Switch,Text,TextInput,View } from 'react-native';
import { getCapabilityCatalogBundle,runCapabilityAudit,updateCapabilityDomainContract,type CapabilityDomainContract } from '../services/ownerAdmin';

type Filter='issues'|'surface'|'gated'|'all';
const rows=(v:any)=>Array.isArray(v)?v:v&&typeof v==='object'?[...Object.values(v)].flatMap(x=>Array.isArray(x)?x:[]):[];
const pretty=(v:unknown)=>String(v??'').replaceAll('_',' ').replaceAll('-',' ');
const executionNeedsReview=(c:CapabilityDomainContract)=>!c.rpc_exists||(c.release_state==='enabled'&&c.exposure_state==='surface'&&!c.authenticated_execute)||(c.release_state==='internal-only'&&c.anon_execute);
const authPolicyHealthy=(c:CapabilityDomainContract)=>c.authenticated_execute||c.exposure_state!=='surface'||c.release_state!=='enabled';
const anonPolicyHealthy=(c:CapabilityDomainContract)=>!(c.release_state==='internal-only'&&c.anon_execute);
export default function Capabilities(){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading capability governance…'),[query,setQuery]=useState(''),[filter,setFilter]=useState<Filter>('issues');
 async function load(){setBusy(true);try{setData(await getCapabilityCatalogBundle());setMessage('')}catch(e:any){setMessage(e?.message||'Capability governance unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function audit(){setBusy(true);try{const r:any=await runCapabilityAudit();setMessage(`Audit complete · ${Number(r?.issue_count||0)} issues across ${Number(r?.domain_count||0)} domains.`);await load()}catch(e:any){setMessage(e?.message||'Capability audit failed.')}finally{setBusy(false)}}
 async function patch(c:CapabilityDomainContract,value:Record<string,unknown>,reason:string){setBusy(true);try{await updateCapabilityDomainContract(c.domain,value,reason);setMessage(`${pretty(c.domain)} updated.`);await load()}catch(e:any){setMessage(e?.message||'Governance update failed.')}finally{setBusy(false)}}
 function toggleActive(c:CapabilityDomainContract,next:boolean){if(next){void patch(c,{active:true},'Re-enabled in KleenestOS');return}Alert.alert('Disable capability domain?',`${pretty(c.domain)} stays documented but will no longer be an active canonical domain.`,[{text:'Cancel',style:'cancel'},{text:'Disable',style:'destructive',onPress:()=>void patch(c,{active:false},'Disabled in KleenestOS')}])}
 function release(c:CapabilityDomainContract,state:string){if(state==='retired'){Alert.alert('Retire this domain?',`${pretty(c.domain)} will be marked retired and disabled. This does not drop database functions.`,[{text:'Cancel',style:'cancel'},{text:'Retire',style:'destructive',onPress:()=>void patch(c,{release_state:'retired',active:false},'Retired in KleenestOS')}]);return}void patch(c,{release_state:state},`Release state set to ${state} in KleenestOS`)}
 function openOwner(c:CapabilityDomainContract){const ws=String(c.owner_workspace||c.owner_surface||'').toLowerCase();if(ws.includes('business'))router.push('/businesses');else if(ws.includes('owner')||ws.includes('platform'))router.push((c.owner_route||'/operations') as any);else router.push('/operations')}
 const contracts:CapabilityDomainContract[]=Array.isArray(data?.contracts)?data.contracts:[];
 const domainIssues=rows(data?.domainIssues).filter((r:any)=>r.issue&&r.issue!=='ok');const issueDomains=new Set(domainIssues.map((r:any)=>String(r.domain)));
 const filtered=useMemo(()=>contracts.filter(c=>{const q=query.trim().toLowerCase(),text=[c.domain,c.canonical_capability,c.canonical_rpc,c.owner_workspace,c.owner_route,c.release_state,c.exposure_state].filter(Boolean).join(' ').toLowerCase();if(q&&!text.includes(q))return false;const issue=issueDomains.has(c.domain)||executionNeedsReview(c);if(filter==='issues')return issue;if(filter==='surface')return c.requires_surface;if(filter==='gated')return c.release_state!=='enabled';return true}),[contracts,query,filter,data]);
 const executionReview=contracts.filter(executionNeedsReview).length,active=contracts.filter(c=>c.active).length,surface=contracts.filter(c=>c.requires_surface).length,gated=contracts.filter(c=>c.release_state!=='enabled').length;
 const errors=data?.errors&&typeof data.errors==='object'?Object.entries(data.errors):[];
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>KLEENESTOS · CAPABILITY GOVERNANCE</Text><Text style={s.title}>Own every product capability</Text><Text style={s.copy}>Audit backend authority, find unowned or overexposed domains, control release state and jump to the workflow responsible for the capability.</Text></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  {errors.length?<View style={s.warning}><Text style={s.warningTitle}>Some audit sources were unavailable</Text>{errors.map(([k,v])=><Text key={k} style={s.meta}>{pretty(k)} · {String(v)}</Text>)}</View>:null}
  <View style={s.metrics}><Metric label="Active domains" value={active}/><Metric label="Surface owned" value={surface}/><Metric label="Execution review" value={executionReview}/><Metric label="Release gated" value={gated}/></View>
  <View style={s.notice}><Text style={s.noticeTitle}>Execution policy is intent-aware</Text><Text style={s.meta}>Server-support and shared-service RPCs are not treated as authorization gaps merely because authenticated clients cannot execute them. Internal-only domains are flagged if anonymous execution is exposed; enabled app surfaces are flagged when their authenticated execution path is missing.</Text></View>
  <View style={s.actions}><Button label={busy?'Auditing…':'Run live audit'} disabled={busy} onPress={audit}/><Button secondary label="Refresh" disabled={busy} onPress={load}/></View>
  <View style={s.toolbox}><Text style={s.sectionTitle}>Capability registry</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search domain, RPC, app or route" style={s.input}/><View style={s.chips}>{(['issues','surface','gated','all'] as Filter[]).map(v=><Pressable key={v} onPress={()=>setFilter(v)} style={[s.chip,filter===v&&s.chipOn]}><Text style={[s.chipText,filter===v&&s.chipTextOn]}>{pretty(v)}</Text></Pressable>)}</View><Text style={s.meta}>{filtered.length} of {contracts.length} domains</Text></View>
  {filtered.length?filtered.map(c=>{const issue=issueDomains.has(c.domain)||executionNeedsReview(c);return <View key={c.domain} style={[s.card,issue&&s.issueCard]}><View style={s.cardTop}><View style={{flex:1}}><Text style={s.cardTitle}>{pretty(c.domain)}</Text><Text style={s.meta}>{pretty(c.canonical_capability)}</Text></View><Badge text={c.active?'ACTIVE':'OFF'} bad={!c.active}/>{issue?<Badge text="REVIEW" bad/>:null}</View><Fact label="Canonical RPC" value={c.canonical_rpc}/><View style={s.facts}><Mini label="Owner" value={c.owner_workspace||c.owner_surface}/><Mini label="Route" value={c.owner_route||'supporting service'}/><Mini label="Exposure" value={pretty(c.exposure_state)}/><Mini label="Release" value={pretty(c.release_state)}/></View><View style={s.health}><Health label="RPC exists" ok={c.rpc_exists}/><Health label="Auth policy" ok={authPolicyHealthy(c)}/><Health label="Anon policy" ok={anonPolicyHealthy(c)}/></View><View style={s.toggle}><View style={{flex:1}}><Text style={s.rowTitle}>Active canonical domain</Text><Text style={s.meta}>Disable only when this capability is intentionally withdrawn or retired.</Text></View><Switch value={c.active} onValueChange={v=>toggleActive(c,v)}/></View><View style={s.toggle}><View style={{flex:1}}><Text style={s.rowTitle}>Requires app surface</Text><Text style={s.meta}>When on, parity must provide a discoverable workflow for this domain.</Text></View><Switch value={c.requires_surface} onValueChange={v=>void patch(c,{requires_surface:v},'Surface requirement changed in KleenestOS')}/></View><View style={s.chips}>{['enabled','internal-only','play-gated','retired'].map(v=><Pressable key={v} onPress={()=>release(c,v)} style={[s.chip,c.release_state===v&&s.chipOn]}><Text style={[s.chipText,c.release_state===v&&s.chipTextOn]}>{pretty(v)}</Text></Pressable>)}</View><Button secondary label="Open owning workflow" onPress={()=>openOwner(c)}/></View>}):<View style={s.card}><Text style={s.cardTitle}>No matching capability domains</Text><Text style={s.meta}>Change the filter or search term. Zero results here do not mean the registry is empty.</Text></View>}
 </ScrollView>;
}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
function Fact({label,value}:{label:string;value:string}){return <View style={s.fact}><Text style={s.factLabel}>{label}</Text><Text selectable style={s.factValue}>{value}</Text></View>}
function Mini({label,value}:{label:string;value:any}){return <View style={s.mini}><Text style={s.factLabel}>{label}</Text><Text style={s.miniValue}>{String(value??'—')}</Text></View>}
function Health({label,ok}:{label:string;ok:boolean}){return <View style={[s.healthPill,ok?s.good:s.bad]}><Text style={s.healthText}>{ok?'✓':'!'} {label}</Text></View>}
function Badge({text,bad=false}:{text:string;bad?:boolean}){return <View style={[s.badge,bad?s.bad:s.good]}><Text style={s.badgeText}>{text}</Text></View>}
function Button({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.buttonSecondary,disabled&&s.disabled]}><Text style={[s.buttonText,secondary&&s.buttonSecondaryText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:14,paddingBottom:80,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#102218',padding:19,borderRadius:23,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#b9d2c2'},title:{fontSize:28,fontWeight:'900',color:'#fff'},copy:{color:'#dce9e1',lineHeight:20},message:{fontWeight:'800',color:'#554e39'},warning:{backgroundColor:'#fff5dd',borderWidth:1,borderColor:'#ead49b',padding:13,borderRadius:15,gap:4},warningTitle:{fontWeight:'900',color:'#6d5314'},notice:{backgroundColor:'#f8fbf9',borderWidth:1,borderColor:'#dbe5de',padding:12,borderRadius:14,gap:4},noticeTitle:{fontWeight:'900',color:'#173f2d'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:24,fontWeight:'900',color:'#173f2d'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},toolbox:{backgroundColor:'#fff',padding:14,borderRadius:17,borderWidth:1,borderColor:'#dbe5de',gap:9},sectionTitle:{fontSize:20,fontWeight:'900',color:'#102218'},input:{backgroundColor:'#f9fbfa',borderWidth:1,borderColor:'#ccd9d1',borderRadius:12,padding:11},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#cbd8d0',borderRadius:999,paddingHorizontal:10,paddingVertical:7,backgroundColor:'#fff'},chipOn:{backgroundColor:'#173f2d',borderColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'800',color:'#42574b'},chipTextOn:{color:'#fff'},card:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:1,borderColor:'#dbe5de',gap:10},issueCard:{borderColor:'#d09b79'},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:7},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#66766e'},fact:{gap:3},factLabel:{fontSize:9,fontWeight:'900',letterSpacing:.7,color:'#718077',textTransform:'uppercase'},factValue:{fontSize:12,fontWeight:'800',color:'#274536'},facts:{flexDirection:'row',flexWrap:'wrap',gap:8},mini:{backgroundColor:'#f4f7f5',padding:9,borderRadius:10,minWidth:'46%',flexGrow:1},miniValue:{fontSize:12,fontWeight:'800',color:'#254536',textTransform:'capitalize'},health:{flexDirection:'row',flexWrap:'wrap',gap:6},healthPill:{paddingHorizontal:9,paddingVertical:6,borderRadius:999},healthText:{fontSize:10,fontWeight:'900',color:'#244333'},good:{backgroundColor:'#dff2e6'},bad:{backgroundColor:'#f6deda'},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:999},badgeText:{fontSize:9,fontWeight:'900',color:'#244333'},toggle:{flexDirection:'row',alignItems:'center',gap:12,paddingTop:4},rowTitle:{fontSize:13,fontWeight:'900',color:'#102218'},button:{backgroundColor:'#173f2d',borderRadius:12,paddingHorizontal:13,paddingVertical:11,alignItems:'center'},buttonSecondary:{backgroundColor:'#edf3ef'},buttonText:{fontWeight:'900',color:'#fff'},buttonSecondaryText:{color:'#234a36'},disabled:{opacity:.45}});
