import { useEffect,useMemo,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { getOwnerCrudCatalog,ownerCrudCreateRecord,ownerCrudDeleteRecord,ownerCrudListRecords,ownerCrudUpdateRecord,type CrudCapability } from '../services/ownerData';

type Row=Record<string,unknown>;
type EditorMode='create'|'edit'|null;
type DraftField={key:string;value:string;original?:unknown};
const immutable=new Set(['id','created_at','updated_at','deleted_at']);
const title=(row:Row)=>String(row.name||row.display_name||row.title||row.email||row.code||row.slug||row.id||'Record');
const primitive=(value:unknown)=>value===null||['string','number','boolean'].includes(typeof value);
function stringify(value:unknown){if(value===null||value===undefined)return'';return String(value)}
function typed(value:string,original?:unknown):unknown{const text=value.trim();if(text==='')return null;if(typeof original==='boolean'||text==='true'||text==='false')return text==='true';if(typeof original==='number'||/^-?\d+(\.\d+)?$/.test(text))return Number(text);return value;}
function rowFields(row:Row):DraftField[]{return Object.entries(row).filter(([key,value])=>!immutable.has(key)&&primitive(value)).map(([key,value])=>({key,value:stringify(value),original:value}));}
function summary(row:Row){const entries=Object.entries(row).filter(([key,value])=>!immutable.has(key)&&value!==null&&value!==undefined&&primitive(value)).slice(0,5);return entries.map(([key,value])=>`${key.replaceAll('_',' ')}: ${String(value)}`).join(' · ')||'Canonical record';}

export default function DataWorkbench(){
 const[catalog,setCatalog]=useState<CrudCapability[]>([]),[resource,setResource]=useState('locations'),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState<string|null>('catalog'),[message,setMessage]=useState('Loading audited resource catalog…'),[mode,setMode]=useState<EditorMode>(null),[selected,setSelected]=useState<Row|null>(null),[fields,setFields]=useState<DraftField[]>([]);
 const capability=catalog.find(item=>item.resource===resource);
 const visibleCatalog=useMemo(()=>catalog.filter(item=>!query.trim()||item.resource.includes(query.trim().toLowerCase())).slice(0,60),[catalog,query]);
 async function loadCatalog(){setBusy('catalog');try{const next=await getOwnerCrudCatalog();setCatalog(next);const preferred=next.find(item=>item.resource===resource)??next.find(item=>!item.read_only)??next[0];if(preferred){setResource(preferred.resource);await load(preferred.resource)}else setMessage('No approved Owner CRUD resources are currently exposed.')}catch(e:any){setMessage(e?.message||'CRUD catalog unavailable.')}finally{setBusy(null)}}
 async function load(next=resource){setBusy('load');setResource(next);setMode(null);setSelected(null);try{const nextRows=await ownerCrudListRecords(next);setRows(nextRows as Row[]);setMessage(`${nextRows.length} ${next.replaceAll('_',' ')} loaded through the platform-owner audited gateway.`)}catch(e:any){setRows([]);setMessage(e?.message||'Resource unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void loadCatalog()},[]);
 function beginCreate(){if(!capability?.create)return;const sample=rows[0]??{};const seed=Object.entries(sample).filter(([key,value])=>!immutable.has(key)&&primitive(value)).slice(0,8).map(([key,value])=>({key,value:'',original:value}));setFields(seed.length?seed:[{key:'name',value:''}]);setSelected(null);setMode('create');}
 function beginEdit(row:Row){if(!capability?.update)return;setSelected(row);setFields(rowFields(row));setMode('edit');}
 function updateField(index:number,patch:Partial<DraftField>){setFields(current=>current.map((item,i)=>i===index?{...item,...patch}:item));}
 function payload(){const result:Record<string,unknown>={};for(const field of fields){const key=field.key.trim();if(!key||immutable.has(key))continue;if(mode==='edit'&&stringify(field.original)===field.value)continue;if(mode==='create'&&!field.value.trim())continue;result[key]=typed(field.value,field.original);}return result;}
 async function save(){const values=payload();if(!Object.keys(values).length){setMessage('Add or change at least one editable field.');return;}setBusy('save');try{if(mode==='create')await ownerCrudCreateRecord(resource,values);else{const id=String(selected?.id||'');if(!id)throw new Error('This record does not expose the canonical id required for an audited update.');await ownerCrudUpdateRecord(resource,id,values);}setMessage(mode==='create'?'Record created through the audited gateway.':'Record updated through the audited gateway.');await load(resource)}catch(e:any){setMessage(e?.message||'Record could not be saved.')}finally{setBusy(null)}}
 function remove(row:Row){const id=String(row.id||'');if(!id||!capability?.delete)return;Alert.alert('Delete canonical record?',`Delete ${title(row)} from ${resource.replaceAll('_',' ')}? This uses the platform-owner audited gateway and cannot bypass protected resources.`,[{text:'Cancel',style:'cancel'},{text:'Delete record',style:'destructive',onPress:()=>void(async()=>{setBusy(`delete:${id}`);try{await ownerCrudDeleteRecord(resource,id);setMessage('Record deleted through the audited gateway.');await load(resource)}catch(e:any){setMessage(e?.message||'Record could not be deleted.')}finally{setBusy(null)}})()}]);}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy==='load'||busy==='catalog'} onRefresh={loadCatalog}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>AUDITED DATA GATEWAY</Text><Text style={s.title}>Data workbench</Text><Text style={s.copy}>Inspect and operate approved canonical resources without raw schema access. Read-only domains stay protected and mutations are platform-owner authorized on the server.</Text></View>
  <Text style={s.message}>{message}</Text>
  <View style={s.card}><Text style={s.cardTitle}>Canonical resource</Text><TextInput value={query} onChangeText={setQuery} autoCapitalize="none" placeholder="Filter resources" style={s.input}/><View style={s.chips}>{visibleCatalog.map(item=><Pressable key={item.resource} onPress={()=>void load(item.resource)} style={[s.chip,resource===item.resource&&s.chipActive]}><Text style={[s.chipText,resource===item.resource&&s.chipTextActive]}>{item.resource.replaceAll('_',' ')}</Text></Pressable>)}</View><View style={s.capabilities}><Pill label="READ" on/><Pill label="CREATE" on={Boolean(capability?.create)}/><Pill label="EDIT" on={Boolean(capability?.update)}/><Pill label="DELETE" on={Boolean(capability?.delete)}/>{capability?.read_only?<Pill label="PROTECTED" on/>:null}</View>{capability?.create?<Action label="Create record" disabled={Boolean(busy)} onPress={beginCreate}/>:<Text style={s.meta}>This resource is intentionally read-only here. Use its dedicated protected Owner workflow for mutations.</Text>}</View>
  {mode?<View style={s.editor}><View style={s.sectionHead}><Text style={s.sectionTitle}>{mode==='create'?'Create record':`Edit ${selected?title(selected):'record'}`}</Text><Action quiet label="Cancel" onPress={()=>setMode(null)}/></View><Text style={s.meta}>Only changed non-empty fields are sent. Server-side resource allowlists, read-only protections and table constraints remain authoritative.</Text>{fields.map((field,index)=><View key={`${field.key}:${index}`} style={s.fieldRow}><TextInput value={field.key} editable={mode==='create'} onChangeText={value=>updateField(index,{key:value})} autoCapitalize="none" placeholder="field name" style={[s.input,s.fieldName]}/><TextInput value={field.value} onChangeText={value=>updateField(index,{value})} autoCapitalize="none" placeholder="value" style={[s.input,{flex:1}]}/>{mode==='create'?<Pressable onPress={()=>setFields(current=>current.filter((_,i)=>i!==index))} style={s.removeField}><Text style={s.removeFieldText}>×</Text></Pressable>:null}</View>)}{mode==='create'?<Action quiet label="Add field" onPress={()=>setFields(current=>[...current,{key:'',value:''}])}/>:null}<Action label={busy==='save'?'Saving…':mode==='create'?'Create record':'Save changes'} disabled={Boolean(busy)} onPress={save}/></View>:null}
  <View style={s.sectionHead}><Text style={s.sectionTitle}>{resource.replaceAll('_',' ')}</Text><Text style={s.meta}>{rows.length} records</Text></View>
  {rows.map((row,index)=>{const id=String(row.id||index);return <View key={id} style={s.card}><Text style={s.cardTitle}>{title(row)}</Text><Text style={s.meta}>{summary(row)}</Text><View style={s.actions}>{capability?.update?<Action quiet label="Edit record" disabled={Boolean(busy)} onPress={()=>beginEdit(row)}/>:null}{capability?.delete&&row.id?<Action danger label="Delete record" disabled={Boolean(busy)} onPress={()=>remove(row)}/>:null}</View></View>})}
  {!busy&&!rows.length?<View style={s.card}><Text style={s.meta}>No records returned for this resource.</Text></View>:null}
 </ScrollView>;
}
function Pill({label,on}:{label:string;on:boolean}){return <View style={[s.pill,!on&&s.pillOff]}><Text style={[s.pillText,!on&&s.pillTextOff]}>{label}</Text></View>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,danger&&s.actionDanger,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&s.actionQuietText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:14,paddingBottom:70,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#102218',padding:18,borderRadius:22,gap:6},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#b9d2c2'},title:{fontSize:28,fontWeight:'900',color:'#fff'},copy:{color:'#dce9e1',lineHeight:20},message:{fontWeight:'800',color:'#355345'},card:{backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dbe5de',gap:9},cardTitle:{fontSize:16,fontWeight:'900',color:'#102218'},meta:{fontSize:12,lineHeight:18,color:'#66766e'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:10,backgroundColor:'#fafcfb'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:10,paddingVertical:8,borderRadius:999},chipActive:{backgroundColor:'#173f2d'},chipText:{fontWeight:'900',color:'#244d39',textTransform:'capitalize'},chipTextActive:{color:'#fff'},capabilities:{flexDirection:'row',flexWrap:'wrap',gap:6},pill:{backgroundColor:'#dff0e6',borderRadius:999,paddingHorizontal:9,paddingVertical:5},pillOff:{backgroundColor:'#f1f2f1'},pillText:{fontSize:10,fontWeight:'900',color:'#235038'},pillTextOff:{color:'#879087'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},sectionTitle:{fontSize:20,fontWeight:'900',color:'#102218',textTransform:'capitalize'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},actionQuiet:{backgroundColor:'#edf3ef'},actionDanger:{backgroundColor:'#8d2d2d'},actionText:{fontWeight:'900',color:'#fff'},actionQuietText:{color:'#244d39'},editor:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:2,borderColor:'#173f2d',gap:10},fieldRow:{flexDirection:'row',gap:7,alignItems:'center'},fieldName:{width:135},removeField:{width:34,height:34,borderRadius:17,backgroundColor:'#fae9e9',alignItems:'center',justifyContent:'center'},removeFieldText:{fontSize:20,fontWeight:'900',color:'#8d2d2d'}});
