import { Link } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { getPlatformDashboard } from '../services/product';
import { getIngestionControlSnapshot,getNotificationControlSnapshot } from '../services/controlPlane';
import { getOwnerAuthorization,getOwnerProgressionPlatformSnapshot,type OwnerAuthorization } from '../services/ownerAdmin';
import { HealthCard,OSHero,SectionHeader,StatusPill,osCard,osColors } from '../components/KleenestOS';

type Row=Record<string,any>;
type Attention={key:string;href:string;title:string;body:string;tone:'danger'|'warning'};
const primaryRoutes=[['/access','People & Access','Search accounts and make audited role, subscription and authority changes.'],['/businesses','Businesses & Network','Verify businesses, manage memberships, tiers, locations, Fleet and Enterprise access.'],['/progression','Economy','Operate XP issuance, objectives, evidence tiers and progression supply.'],['/moderation','Trust & Moderation','Resolve review reports, user safety reports, AI reports and business trust queues.'],['/operations','Operations','Control ingestion, storage safety, scheduler execution, integrity and delivery health.'],['/notifications','Live Network Messaging','Operate notification rules, audiences, caps, consent and delivery outcomes.']] as const;
const governanceRoutes=[['/capabilities','System Capabilities','Inspect canonical capability ownership, release state and retirement drift.'],['/audit','System Audit','Run live capability/schema audits and review administrator activity.'],['/data','System Data Workbench','Use the audited CRUD gateway for advanced canonical data work.'],['/intelligence','Intelligence Lab','Inspect network intelligence, recommendations and operating signals.'],['/history','Control History','Review audited platform mutation history.']] as const;
const object=(value:any):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const count=(value:any)=>Array.isArray(value)?value.length:value&&typeof value==='object'?Object.keys(value).length:Number(value||0);
const number=(value:any)=>{const parsed=Number(value??0);return Number.isFinite(parsed)?parsed:0;};
const maybeNumber=(value:any)=>value===null||value===undefined||value===''?null:Number.isFinite(Number(value))?Number(value):null;
function compactBytes(value:any){const bytes=number(value);if(bytes<=0)return'0 MB';const mb=bytes/1024/1024;return mb<1024?`${mb.toFixed(mb>=100?0:1)} MB`:`${(mb/1024).toFixed(2)} GB`;}
function DomainList({routes,subdued=false}:{routes:readonly (readonly [string,string,string])[];subdued?:boolean}){return <View style={{gap:8}}>{routes.map(([href,title,body])=><Link key={href} href={href as any} asChild><Pressable style={{...osCard,backgroundColor:subdued?'#f7f9f8':'#fff'}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{flex:1,gap:4}}><Text style={{fontSize:17,fontWeight:'900',color:osColors.ink}}>{title}</Text><Text style={{color:osColors.muted,lineHeight:19}}>{body}</Text></View><Text style={{fontSize:24,color:osColors.green}}>›</Text></View></Pressable></Link>)}</View>}
function AttentionCard({item}:{item:Attention}){const danger=item.tone==='danger';return <Link href={item.href as any} asChild><Pressable style={{...osCard,borderColor:danger?'#e8bbbb':'#efd9a5',backgroundColor:danger?'#fff6f6':'#fffaf0'}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><View style={{flex:1,gap:4}}><Text style={{fontWeight:'900',color:danger?osColors.danger:osColors.warning}}>{item.title}</Text><Text style={{color:osColors.muted,lineHeight:19}}>{item.body}</Text></View><Text style={{fontSize:24,color:osColors.green}}>›</Text></View></Pressable></Link>}

export default function PlatformHome(){
 const[data,setData]=useState<any>(null),[ingestion,setIngestion]=useState<any>(null),[messaging,setMessaging]=useState<any>(null),[economy,setEconomy]=useState<any>(null),[authorization,setAuthorization]=useState<OwnerAuthorization|null>(null),[busy,setBusy]=useState(false),[errors,setErrors]=useState<string[]>([]);
 async function load(){setBusy(true);const nextErrors:string[]=[];try{const auth=await getOwnerAuthorization();setAuthorization(auth);if(!auth.authorized)throw new Error('KleenestOS authorization required.');const settled=await Promise.allSettled([getPlatformDashboard(),getIngestionControlSnapshot(25),getNotificationControlSnapshot(25),getOwnerProgressionPlatformSnapshot()]);const value=(index:number)=>{const result=settled[index];if(result.status==='fulfilled')return result.value;nextErrors.push(result.reason instanceof Error?result.reason.message:String(result.reason));return null;};setData(value(0));setIngestion(value(1));setMessaging(value(2));setEconomy(value(3));}catch(error:any){nextErrors.push(error?.message||'Sign in with an authorized platform-owner account.')}finally{setErrors(nextErrors);setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const markets=object(ingestion?.status?.markets),guard=object(ingestion?.storage_guard),scheduler=object(ingestion?.status?.scheduler||ingestion?.scheduler),runs=Array.isArray(messaging?.recent_runs)?messaging.recent_runs:[],outcomes=object(messaging?.outcomes);const failedRuns=useMemo(()=>runs.filter((row:any)=>String(row.status)==='failed').length,[runs]);
 const reports=count(data?.reports),pending=count(data?.pending),observedPercent=maybeNumber(guard.observed_percent),diskPercent=maybeNumber(guard.disk_observed_percent),running=maybeNumber(markets.running),markedRunning=maybeNumber(markets.marked_running),staleRunning=maybeNumber(markets.stale_running),pendingMarkets=maybeNumber(markets.pending),xp=number(economy?.xp_awarded??economy?.xpLast24h),discoveries=number(economy?.discoveries),objectives=number(economy?.active_objectives??economy?.activeObjectives);
 const ingestionLoaded=Boolean(ingestion),messagingLoaded=Boolean(messaging);
 const ingestionDetail=ingestionLoaded?`${pendingMarkets??0} pending · ${markedRunning??running??0} marked running${staleRunning?` · ${staleRunning} stale`:''}`:'Telemetry unavailable';
 const attention=useMemo<Attention[]>(()=>{const items:Attention[]=[];if(guard.hard_stop||guard.paused)items.push({key:'storage',href:'/operations',title:guard.hard_stop?'Ingestion hard stop':'Ingestion paused',body:String(guard.pause_reason||'Storage or ingestion safety requires owner review.'),tone:'danger'});if(ingestionLoaded&&scheduler.active===false)items.push({key:'scheduler',href:'/operations',title:'Ingestion scheduler inactive',body:'The canonical ingestion scheduler is not currently active.',tone:'warning'});if((staleRunning??0)>0)items.push({key:'stale-ingestion',href:'/operations',title:`${staleRunning} stale ingestion market${staleRunning===1?'':'s'}`,body:'These markets are marked running without a recent active execution and should be repaired or reconciled.',tone:'warning'});if(failedRuns)items.push({key:'delivery',href:'/notifications',title:`${failedRuns} failed messaging run${failedRuns===1?'':'s'}`,body:'Open Live Network Messaging to inspect delivery execution and retry state.',tone:'warning'});if(reports)items.push({key:'reports',href:'/moderation',title:`${reports} review report${reports===1?'':'s'} waiting`,body:'Trust reports require an owner/admin decision.',tone:'warning'});if(pending)items.push({key:'businesses',href:'/businesses',title:`${pending} business item${pending===1?'':'s'} waiting`,body:'Resolve pending verification or network administration.',tone:'warning'});return items;},[failedRuns,guard.hard_stop,guard.pause_reason,guard.paused,ingestionLoaded,pending,reports,scheduler.active,staleRunning]);
 const activity=Array.isArray(data?.activity)?data.activity.slice(0,6):[];
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:70,backgroundColor:osColors.paper}}>
  <OSHero eyebrow="KLEENESTOS · PRIVATE PLATFORM OPERATING SYSTEM" title="COMMAND CENTER" body="Live platform health, what needs attention, and the audited control surfaces that can resolve it.">{authorization?<StatusPill label={authorization.is_platform_owner?'PLATFORM OWNER · FULL CONTROL':'ADMIN · RESTRICTED CONTROL'} tone={authorization.is_platform_owner?'good':'warning'}/>:null}</OSHero>
  {errors.map((error,index)=><View key={`${error}:${index}`} style={{...osCard,borderColor:'#e8bbbb',backgroundColor:'#fff6f6'}}><Text style={{fontWeight:'900',color:osColors.danger}}>Subsystem degraded</Text><Text style={{color:osColors.danger}}>{error}</Text></View>)}
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:9}}><HealthCard label="Ingestion" value={!ingestionLoaded?'UNKNOWN':guard.paused?'PAUSED':`${running??0} LIVE RUNS`} tone={!ingestionLoaded?'warning':guard.hard_stop?'danger':guard.paused?'warning':(staleRunning??0)>0?'warning':'good'} detail={ingestionDetail}/><HealthCard label="Database observed" value={observedPercent===null?'UNKNOWN':`${observedPercent.toFixed(1)}%`} tone={observedPercent===null?'warning':observedPercent>=70?'warning':'good'} detail={observedPercent===null?'Telemetry unavailable':`${compactBytes(guard.observed_bytes)} observed · WAL ${compactBytes(guard.wal_bytes)}`}/><HealthCard label="Disk observed" value={diskPercent===null?'UNKNOWN':`${diskPercent.toFixed(1)}%`} tone={diskPercent===null?'warning':diskPercent>=85?'danger':diskPercent>=70?'warning':'good'} detail={diskPercent===null?'Telemetry unavailable':'Database + WAL/overhead observation'}/><HealthCard label="Messaging" value={!messagingLoaded?'UNKNOWN':failedRuns?`${failedRuns} FAILED`:'HEALTHY'} tone={!messagingLoaded?'warning':failedRuns?'warning':'good'} detail={!messagingLoaded?'Control-plane snapshot unavailable':`${number(outcomes.delivered)} delivered · ${number(outcomes.opened)} opened`}/><HealthCard label="Moderation" value={reports} tone={reports?'warning':'good'} detail="Open review reports"/><HealthCard label="Business queue" value={pending} tone={pending?'warning':'good'} detail="Pending verification/access"/></View>
  <View style={{gap:9}}><SectionHeader title="Needs attention" body="KleenestOS promotes actionable conditions instead of making you hunt through diagnostics."/>{attention.length?attention.map(item=><AttentionCard key={item.key} item={item}/>):<View style={osCard}><Text style={{fontWeight:'900',color:osColors.good}}>No active owner actions</Text><Text style={{color:osColors.muted}}>Current ingestion, messaging, moderation and business queues are clear.</Text></View>}</View>
  <View style={{...osCard,backgroundColor:osColors.ink,gap:8}}><Text style={{color:'#bde4cf',fontWeight:'900',letterSpacing:1,fontSize:10}}>ECONOMY PULSE</Text><Text style={{color:'#fff',fontSize:22,fontWeight:'900'}}>{xp.toLocaleString()} XP in the current platform snapshot</Text><Text style={{color:'#dce8e1'}}>{discoveries.toLocaleString()} canonical discoveries · {objectives.toLocaleString()} active objectives</Text><Link href="/progression" asChild><Pressable style={{alignSelf:'flex-start',backgroundColor:'#d9efe1',borderRadius:999,paddingHorizontal:12,paddingVertical:9}}><Text style={{fontWeight:'900',color:osColors.ink}}>Open Economy →</Text></Pressable></Link></View>
  <View style={{gap:9}}><SectionHeader title="Operate the platform" body="Daily control surfaces stay first: people, businesses, economy, trust, ingestion and delivery."/><DomainList routes={primaryRoutes}/></View>
  <View style={{gap:9}}><SectionHeader title="Understand & govern" body="Advanced capability, audit, data and intelligence tools remain directly reachable without crowding daily operations."/><DomainList routes={governanceRoutes} subdued/></View>
  <View style={{gap:9}}><SectionHeader title="Recent control-plane activity" body="Latest audited platform events remain visible without exposing raw backend payloads."/>{activity.length?activity.map((row:any,index:number)=><View key={String(row.id||index)} style={osCard}><Text style={{fontWeight:'900',color:osColors.ink}}>{String(row.event_type||row.action||row.type||'Platform activity').replaceAll('_',' ')}</Text><Text style={{fontSize:12,color:osColors.muted}}>{row.created_at?new Date(String(row.created_at)).toLocaleString():'Recent'}{row.actor_email?` · ${String(row.actor_email)}`:''}</Text></View>):<View style={osCard}><Text style={{color:osColors.muted}}>No recent control-plane activity returned.</Text></View>}</View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Link href="/account" style={{backgroundColor:'#edf3ef',color:osColors.green,fontWeight:'900',paddingHorizontal:12,paddingVertical:10,borderRadius:999}}>Account</Link><Link href="/support" style={{backgroundColor:'#edf3ef',color:osColors.green,fontWeight:'900',paddingHorizontal:12,paddingVertical:10,borderRadius:999}}>Support</Link><Link href="/terms" style={{backgroundColor:'#edf3ef',color:osColors.green,fontWeight:'900',paddingHorizontal:12,paddingVertical:10,borderRadius:999}}>Terms</Link><Link href="/privacy" style={{backgroundColor:'#edf3ef',color:osColors.green,fontWeight:'900',paddingHorizontal:12,paddingVertical:10,borderRadius:999}}>Privacy</Link></View>
 </ScrollView>;
}
