import { usePlatformTheme } from '../services/theme';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { listBusinessMotifs,listPlatformMotifs,subscribePlatformMotifs,type LiveNetworkMotif } from '../services/liveNetworkMotifs';
import { explainLocationIntelligence,getOwnerIntelligenceWorkspace,updateIntelligencePolicy } from '../services/intelligenceLayer';

const pretty=(value:unknown)=>String(value??'').replaceAll('_',' ').replaceAll('-',' ');
const numeric=(value:unknown,fallback=0)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback};
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():'Not recorded';

export default function Intelligence(){
  const theme=usePlatformTheme();
  const[motifs,setMotifs]=useState<LiveNetworkMotif[]>([]),[scopeId,setScopeId]=useState(''),[scopeMotifs,setScopeMotifs]=useState<LiveNetworkMotif[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[lastLiveAt,setLastLiveAt]=useState<string|null>(null);
  const[overview,setOverview]=useState<any>(null),[policy,setPolicy]=useState<any>({}),[locationId,setLocationId]=useState(''),[explanation,setExplanation]=useState<any>(null);
  const[launchFresh,setLaunchFresh]=useState('50'),[launchConfidence,setLaunchConfidence]=useState('40'),[freshTarget,setFreshTarget]=useState('65'),[claimedTarget,setClaimedTarget]=useState('20'),[cooldown,setCooldown]=useState('15');

  const hydratePolicy=useCallback((next:any)=>{const p=next||{};setPolicy(p);setLaunchFresh(String(numeric(p?.launch?.freshness_min,50)));setLaunchConfidence(String(numeric(p?.launch?.confidence_min,40)));setFreshTarget(String(numeric(p?.launch?.fresh_location_pct_target,65)));setClaimedTarget(String(numeric(p?.launch?.claimed_location_pct_target,20)));setCooldown(String(numeric(p?.service_min_interval_minutes,15)));},[]);
  const load=useCallback(async()=>{setBusy(true);try{const[nextMotifs,workspace]=await Promise.all([listPlatformMotifs(60),getOwnerIntelligenceWorkspace()]);setMotifs(nextMotifs);setOverview(workspace.overview);hydratePolicy(workspace.policy);setMessage('')}catch(e:any){setMessage(e?.message||'Platform intelligence unavailable.')}finally{setBusy(false)}},[hydratePolicy]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>subscribePlatformMotifs(()=>{setLastLiveAt(new Date().toISOString());void load()}),[load]);
  const urgent=useMemo(()=>motifs.filter(item=>['high','elevated'].includes(item.severity)),[motifs]);

  async function inspectBusiness(){const value=scopeId.trim();if(!value){setScopeMotifs([]);return}setBusy(true);try{setScopeMotifs(await listBusinessMotifs(value,60));setMessage('')}catch(e:any){setMessage(e?.message||'Business intelligence unavailable.')}finally{setBusy(false)}}
  async function inspectLocation(){const value=locationId.trim();if(!value)return;setBusy(true);try{setExplanation(await explainLocationIntelligence(value));setMessage('Explainability trace loaded from canonical evidence.')}catch(e:any){setMessage(e?.message||'Could not explain that location.')}finally{setBusy(false)}}
  async function savePolicy(){setBusy(true);try{const launch={...(policy?.launch||{}),freshness_min:numeric(launchFresh,50),confidence_min:numeric(launchConfidence,40),fresh_location_pct_target:numeric(freshTarget,65),claimed_location_pct_target:numeric(claimedTarget,20)};const next=await updateIntelligencePolicy({launch,service_min_interval_minutes:numeric(cooldown,15)});hydratePolicy(next);setMessage('Intelligence policy updated. Derived projections will use the new thresholds.');await load()}catch(e:any){setMessage(e?.message||'Intelligence policy update failed.')}finally{setBusy(false)}}

  const graph=overview?.platform_graph||{};
  const markets=Array.isArray(overview?.launch_readiness)?overview.launch_readiness:[];
  const evidence=Array.isArray(explanation?.evidence)?explanation.evidence:[];
  return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={[s.page,{backgroundColor:theme.canvas}]}>
    <View style={[s.hero,{backgroundColor:theme.accent,borderColor:theme.accent}]}><Text style={[s.eyebrow,{color:theme.accentText}]}>KLEENESTOS INTELLIGENCE</Text><Text style={[s.heroTitle,{color:theme.accentText}]}>Signals that need a decision</Text><Text style={[s.heroCopy,{color:theme.accentText}]}>Live motifs, the platform graph, explainability and launch readiness share one control surface. Raw user movement stays out of this view.</Text></View>
    {message?<View style={[s.banner,{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.warning}]}><Text style={[s.bannerText,{color:theme.warning}]}>{message}</Text></View>:null}

    <View style={s.metrics}><Metric label="Urgent motifs" value={urgent.length}/><Metric label="Active motifs" value={motifs.filter(item=>item.severity!=='quiet').length}/><Metric label="Signals observed" value={motifs.reduce((sum,item)=>sum+item.observed_count,0)}/><Metric label="Realtime" value={lastLiveAt?'Updated':'Listening'}/></View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionEyebrow,{color:theme.accent}]}>PLATFORM GRAPH</Text><Text style={[s.sectionTitle,{color:theme.ink}]}>Connected platform state</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>Derived intelligence stays explainable and points back to canonical users, locations, businesses, Fleet routes, service events, evidence, access and visits.</Text><View style={s.metrics}>{Object.entries(graph).map(([key,value])=><Metric key={key} label={pretty(key)} value={Number(value||0).toLocaleString()}/>)}</View></View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionEyebrow,{color:theme.accent}]}>LAUNCH READINESS</Text><Text style={[s.sectionTitle,{color:theme.ink}]}>Market readiness</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>Density, freshness, claimed coverage, confidence and recent service activity are visible together before a market is treated as mature.</Text>{markets.slice(0,30).map((row:any,index:number)=><View key={`${row.city}-${row.state}-${index}`} style={[s.line,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{row.city||'Unknown'}{row.state?`, ${row.state}`:''}</Text><Text style={[s.detail,{color:theme.muted}]}>{Number(row.locations||0).toLocaleString()} locations · fresh {numeric(row.fresh_pct).toFixed(1)}% · claimed {numeric(row.claimed_pct).toFixed(1)}% · confident {Number(row.confident_locations||0).toLocaleString()} · service updates 30d {Number(row.service_updates_30d||0).toLocaleString()}</Text></View></View>)}</View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionEyebrow,{color:theme.accent}]}>WHY DID THIS HAPPEN?</Text><Text style={[s.sectionTitle,{color:theme.ink}]}>Explain a location</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>Paste a canonical location UUID to inspect Kleenest Now, Facility Passport, evidence provenance and the policy that produced the projection.</Text><View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><TextInput value={locationId} onChangeText={setLocationId} onSubmitEditing={()=>void inspectLocation()} placeholder="Location UUID" placeholderTextColor={theme.muted} autoCapitalize="none" autoCorrect={false} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]}/><Pressable disabled={busy||!locationId.trim()} onPress={()=>void inspectLocation()} style={[s.button,{backgroundColor:theme.accent,opacity:busy||!locationId.trim()?.55:1}]}><Text style={[s.buttonText,{color:theme.accentText}]}>Explain intelligence</Text></Pressable></View>{explanation?<><View style={s.metrics}><Metric label="Freshness" value={`${Math.round(numeric(explanation?.now?.freshness_score))}%`}/><Metric label="Confidence" value={`${Math.round(numeric(explanation?.now?.confidence_score))}%`}/><Metric label="Evidence events" value={evidence.length}/></View><Text style={[s.detail,{color:theme.muted}]}>Freshness provenance: {pretty(explanation?.now?.freshness_provenance)} · generated {when(explanation?.generated_at)}</Text>{evidence.slice(0,20).map((row:any,index:number)=><View key={`${row.kind}-${row.observed_at}-${index}`} style={[s.line,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{pretty(row.kind)}</Text><Text style={[s.detail,{color:theme.muted}]}>{pretty(row.provenance)} · confidence {Math.round(numeric(row.confidence)*100)}% · {when(row.observed_at)} · {pretty(row.source_type)}</Text></View></View>)}</>:null}</View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionEyebrow,{color:theme.accent}]}>INTELLIGENCE POLICY</Text><Text style={[s.sectionTitle,{color:theme.ink}]}>Global derived-intelligence thresholds</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>These controls tune projections only. They do not rewrite reviews, check-ins, observations, access entitlements or independent verification records.</Text><Field label="Launch freshness minimum" value={launchFresh} onChange={setLaunchFresh}/><Field label="Launch confidence minimum" value={launchConfidence} onChange={setLaunchConfidence}/><Field label="Fresh-location target %" value={freshTarget} onChange={setFreshTarget}/><Field label="Claimed-location target %" value={claimedTarget} onChange={setClaimedTarget}/><Field label="Service-event cooldown minutes" value={cooldown} onChange={setCooldown}/><Pressable disabled={busy} onPress={()=>void savePolicy()} style={[s.button,{backgroundColor:theme.accent,opacity:busy?.55:1}]}><Text style={[s.buttonText,{color:theme.accentText}]}>Save intelligence policy</Text></Pressable></View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionTitle,{color:theme.ink}]}>Platform triage</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>Elevated patterns rise first. Each card explains the operational meaning and evidence so the next action is investigation, not interpreting JSON.</Text>{motifs.map(item=><Motif key={item.motif_key} item={item}/>)}</View>

    <View style={[s.section,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.sectionTitle,{color:theme.ink}]}>Business drilldown</Text><Text style={[s.sectionCopy,{color:theme.muted}]}>Use a business ID only as an administrative drilldown. The primary platform view remains ranked platform intelligence.</Text><View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><TextInput value={scopeId} onChangeText={setScopeId} onSubmitEditing={()=>void inspectBusiness()} placeholder="Business UUID" placeholderTextColor={theme.muted} autoCapitalize="none" style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]}/><Text style={[s.link,{color:theme.accent}]} onPress={()=>void inspectBusiness()}>{busy?'Loading…':'Inspect authorized business motifs'}</Text></View>{scopeMotifs.map(item=><Motif key={`scope:${item.motif_key}`} item={item}/>)}</View>
  </ScrollView>
}
function Motif({item}:{item:LiveNetworkMotif}){const theme=usePlatformTheme();return <View style={[s.card,{backgroundColor:theme.surface,borderColor:['high','elevated'].includes(item.severity)?theme.warning:theme.line}]}><View style={s.cardTop}><View style={{flex:1,gap:3}}><Text style={[s.cardTitle,{color:theme.ink}]}>{item.label}</Text><Text style={[s.detail,{color:theme.muted}]}>{detail(item)}</Text></View><Pill label={item.severity.toUpperCase()}/></View><View style={s.factRow}><Fact label="Signals" value={String(item.observed_count)}/><Fact label="Confidence" value={`${Math.round(item.confidence*100)}%`}/><Fact label="Last seen" value={formatTime(item.last_seen_at)}/></View><Text style={[s.next,{color:theme.ink}]}>{nextAction(item)}</Text></View>}
function detail(item:LiveNetworkMotif){const e=item.evidence||{};switch(item.motif_key){case'network_momentum':return `${n(e.discoveries)} discovery events and ${n(e.routes)} route intents in the current analysis window.`;case'quality_drift':return `Cleanliness ${n(e.cleanliness_avg,1)} · safety ${n(e.safety_avg,1)} · availability ${n(e.availability_avg,1)}.`;case'occupancy_pressure':return `${pct(e.occupancy_ratio)} occupancy · ${n(e.queue_avg,1)} average queue · ${n(e.wait_minutes_avg,1)} minute average wait.`;case'geofence_flow':return `${n(e.enters)} enters · ${n(e.exits)} exits · ${n(e.dwells)} dwell observations.`;case'fleet_pressure':return `${n(e.operational_events)} operational events · ${n(e.open_alerts)} open Fleet alerts.`;case'source_health':return `${n(e.degraded)} degraded source signals · ${n(e.recovered)} recoveries.`;default:return `${item.observed_count} canonical observations contributed.`}}
function nextAction(item:LiveNetworkMotif){if(item.severity==='quiet')return'No intervention indicated; continue observing.';switch(item.motif_key){case'quality_drift':return'NEXT: inspect trust/remediation queues and the affected location evidence.';case'occupancy_pressure':return'NEXT: inspect demand concentration and Fleet/Business capacity response.';case'fleet_pressure':return'NEXT: open Fleet exceptions and unresolved alerts before they breach service targets.';case'source_health':return'NEXT: inspect ingestion/source health before treating downstream absence as real-world absence.';case'geofence_flow':return'NEXT: compare traffic flow with occupancy, service and notification outcomes.';default:return'NEXT: compare this signal with adjacent operational domains before taking control-plane action.'}}
function n(value:unknown,digits=0){const valueNumber=Number(value);return Number.isFinite(valueNumber)?valueNumber.toFixed(digits):'—'}
function pct(value:unknown){const valueNumber=Number(value);return Number.isFinite(valueNumber)?`${Math.round(valueNumber*100)}%`:'—'}
function formatTime(value:string|null){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function Metric({label,value}:{label:string;value:string|number}){const theme=usePlatformTheme();return <View style={[s.metric,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.accent}]}>{String(value)}</Text><Text style={[s.meta,{color:theme.muted}]}>{label}</Text></View>}
function Fact({label,value}:{label:string;value:string}){const theme=usePlatformTheme();return <View style={{minWidth:90,flexGrow:1,flexBasis:90}}><Text style={[s.factLabel,{color:theme.muted}]}>{label}</Text><Text style={[s.factValue,{color:theme.ink}]}>{value}</Text></View>}
function Pill({label}:{label:string}){const theme=usePlatformTheme();return <View style={[s.pill,{backgroundColor:theme.surfaceRaised,borderWidth:1,borderColor:theme.line}]}><Text style={[s.pillText,{color:theme.ink}]}>{label}</Text></View>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){const theme=usePlatformTheme();return <View style={{gap:4}}><Text style={[s.fieldLabel,{color:theme.ink}]}>{label}</Text><TextInput keyboardType="numeric" value={value} onChangeText={onChange} placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]}/></View>}
const s=StyleSheet.create({page:{padding:18,gap:18},hero:{padding:19,borderRadius:24,gap:7,borderWidth:1},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.3},heroTitle:{fontSize:27,fontWeight:'900'},heroCopy:{fontSize:14,lineHeight:21},banner:{borderRadius:14,padding:12},bannerText:{fontWeight:'800'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,borderRadius:17,padding:14,borderWidth:1},metricValue:{fontSize:23,fontWeight:'900'},meta:{fontSize:12,lineHeight:18},section:{gap:9,borderWidth:1,borderRadius:20,padding:14},sectionEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},sectionTitle:{fontSize:21,fontWeight:'900'},sectionCopy:{lineHeight:19},card:{borderRadius:18,padding:15,gap:10,borderWidth:1},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:8},cardTitle:{fontSize:16,fontWeight:'900'},detail:{fontSize:12,lineHeight:18},factRow:{flexDirection:'row',flexWrap:'wrap',gap:10},factLabel:{fontSize:10,fontWeight:'900',letterSpacing:.6,textTransform:'uppercase'},factValue:{fontSize:13,fontWeight:'800'},next:{fontSize:12,fontWeight:'900'},pill:{borderRadius:999,paddingHorizontal:9,paddingVertical:6,alignSelf:'flex-start'},pillText:{fontSize:10,fontWeight:'900'},input:{borderWidth:1,borderRadius:12,padding:12},link:{fontWeight:'900',paddingVertical:6},line:{borderTopWidth:1,paddingTop:9,flexDirection:'row',gap:10},button:{alignSelf:'flex-start',borderRadius:999,paddingHorizontal:13,paddingVertical:10},buttonText:{fontSize:12,fontWeight:'900'},fieldLabel:{fontSize:12,fontWeight:'900'}});
