import { useEffect,useMemo,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Switch,Text,TextInput,View } from 'react-native';
import { authorizeIngestionResume,getIngestionControlSnapshot,repairIngestionCells,runIngestionCycle,updateIngestionMarket,updateIngestionSourcePolicy,updateIngestionStorageGuard } from '../services/controlPlane';

function num(v:any,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function Button({label,onPress,danger=false,disabled=false}:{label:string;onPress:()=>void;danger?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,danger&&s.dangerButton,disabled&&s.disabled]}><Text style={[s.buttonText,danger&&s.dangerText]}>{label}</Text></Pressable>}
function Input({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="numeric" value={String(value??'')} onChangeText={onChange} style={s.input}/></View>}

export default function Operations(){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading ingestion control plane…'),[sourceEdits,setSourceEdits]=useState<Record<string,any>>({}),[marketEdits,setMarketEdits]=useState<Record<string,any>>({}),[guard,setGuard]=useState<any>({});
 async function load(){setBusy(true);try{const next=await getIngestionControlSnapshot(100);setData(next);setGuard(next.storage_guard||{});setSourceEdits(Object.fromEntries((next.sources||[]).map((x:any)=>[x.source_key,{...x}])));setMarketEdits(Object.fromEntries((next.markets||[]).map((x:any)=>[x.id,{priority:x.priority,enabled:x.status!=='blocked'}])));setMessage('')}catch(e:any){setMessage(e?.message||'Ingestion control plane could not be loaded.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const status=data?.status||{};const markets=status?.markets||{};const paused=Boolean(data?.storage_guard?.paused);const sources:any[]=data?.sources||[];const marketRows:any[]=data?.markets||[];
 const activeSources=useMemo(()=>sources.filter((x:any)=>x.enabled).length,[sources]);
 async function saveSource(source:any){setBusy(true);try{const edit=sourceEdits[source.source_key]||source;await updateIngestionSourcePolicy(source.source_key,{enabled:Boolean(edit.enabled),priority:num(edit.priority,100),quota_mode:edit.quota_mode||'fixed',daily_request_limit:edit.daily_request_limit===''?null:num(edit.daily_request_limit),hourly_request_limit:edit.hourly_request_limit===''?null:num(edit.hourly_request_limit),daily_byte_limit:edit.daily_byte_limit===''?null:num(edit.daily_byte_limit),min_interval_seconds:num(edit.min_interval_seconds),max_requests_per_cycle:num(edit.max_requests_per_cycle,1),notes:edit.notes||null});await load();setMessage(`${source.source_key} ingestion policy saved.`)}catch(e:any){setMessage(e?.message||'Source policy could not be saved.')}finally{setBusy(false)}}
 async function saveGuard(){setBusy(true);try{await updateIngestionStorageGuard({allocation_bytes:num(guard.allocation_bytes),pause_fraction:num(guard.pause_fraction),hard_stop_fraction:num(guard.hard_stop_fraction)});await load();setMessage('Storage guard saved.')}catch(e:any){setMessage(e?.message||'Storage guard could not be saved.')}finally{setBusy(false)}}
 async function saveMarket(row:any){setBusy(true);try{const edit=marketEdits[row.id]||{};await updateIngestionMarket(row.id,num(edit.priority,row.priority),Boolean(edit.enabled));await load();setMessage(`${row.name} scheduling policy saved.`)}catch(e:any){setMessage(e?.message||'Market could not be updated.')}finally{setBusy(false)}}
 function confirmRun(){Alert.alert('Run one ingestion cycle?','KleenestOS will invoke the canonical scheduler once using the configured source, market, quota and storage policies.',[{text:'Cancel',style:'cancel'},{text:'Run cycle',onPress:()=>void (async()=>{setBusy(true);try{await runIngestionCycle();await load();setMessage('Ingestion cycle executed.')}catch(e:any){setMessage(e?.message||'Ingestion cycle failed.')}finally{setBusy(false)}})()}])}
 function confirmRepair(){Alert.alert('Repair stalled ingestion cells?','This uses the canonical repair authority and preserves the configured storage guard.',[{text:'Cancel',style:'cancel'},{text:'Repair',onPress:()=>void (async()=>{setBusy(true);try{await repairIngestionCells();await load();setMessage('Stalled-cell repair executed.')}catch(e:any){setMessage(e?.message||'Repair failed.')}finally{setBusy(false)}})()}])}
 function confirmResume(){Alert.alert('Authorize ingestion resume?','This clears the paused storage guard using platform-owner authority. Storage thresholds remain enforced.',[{text:'Cancel',style:'cancel'},{text:'Authorize',style:'destructive',onPress:()=>void (async()=>{setBusy(true);try{await authorizeIngestionResume(true);await load();setMessage('Ingestion resume authorized.')}catch(e:any){setMessage(e?.message||'Resume authorization failed.')}finally{setBusy(false)}})()}])}
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>KLEENESTOS · INGESTION</Text><Text style={s.title}>National ingestion control</Text><Text style={s.heroBody}>Tune sources, quotas, radius-market priority and storage safety without redeploying ingestion code. Every owner mutation is audited server-side.</Text><View style={s.heroActions}><Button label="Run one cycle" onPress={confirmRun} disabled={busy}/><Button label="Repair stalled cells" onPress={confirmRepair} disabled={busy}/>{paused?<Button label="Authorize resume" onPress={confirmResume} danger disabled={busy}/>:null}</View></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><View style={s.metric}><Text style={s.metricValue}>{paused?'PAUSED':'RUNNING'}</Text><Text style={s.meta}>Storage guard</Text></View><View style={s.metric}><Text style={s.metricValue}>{activeSources}/{sources.length}</Text><Text style={s.meta}>Sources enabled</Text></View><View style={s.metric}><Text style={s.metricValue}>{Number(markets.completed||0)}</Text><Text style={s.meta}>Markets complete</Text></View><View style={s.metric}><Text style={s.metricValue}>{Number(markets.pending||0)}</Text><Text style={s.meta}>Markets pending</Text></View></View>
  <View style={s.card}><Text style={s.kicker}>STORAGE SAFETY</Text><Text style={s.sectionTitle}>Capacity guard</Text><Text style={s.meta}>Pause must remain below hard stop. The backend rejects unsafe thresholds.</Text><Input label="Allocation bytes" value={guard.allocation_bytes} onChange={v=>setGuard((g:any)=>({...g,allocation_bytes:v}))}/><View style={s.two}><View style={{flex:1}}><Input label="Pause fraction" value={guard.pause_fraction} onChange={v=>setGuard((g:any)=>({...g,pause_fraction:v}))}/></View><View style={{flex:1}}><Input label="Hard stop fraction" value={guard.hard_stop_fraction} onChange={v=>setGuard((g:any)=>({...g,hard_stop_fraction:v}))}/></View></View>{guard.pause_reason?<Text style={s.warning}>Pause reason: {String(guard.pause_reason)}</Text>:null}<Button label="Save storage guard" onPress={saveGuard} disabled={busy}/></View>
  <View style={s.sectionHead}><View><Text style={s.kicker}>SOURCES</Text><Text style={s.sectionTitle}>Source policies & quotas</Text></View><Text style={s.meta}>{sources.length} configured</Text></View>
  {sources.map((source:any)=>{const edit=sourceEdits[source.source_key]||source;return <View key={source.source_key} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{source.source_key}</Text><Text style={s.meta}>{edit.quota_mode||'fixed'} quota · priority {edit.priority}</Text></View><Switch accessibilityLabel={`Enable ${source.source_key}`} value={Boolean(edit.enabled)} onValueChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,enabled:v}}))}/></View><View style={s.two}><View style={{flex:1}}><Input label="Priority" value={edit.priority} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,priority:v}}))}/></View><View style={{flex:1}}><Input label="Max / cycle" value={edit.max_requests_per_cycle} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,max_requests_per_cycle:v}}))}/></View></View><View style={s.two}><View style={{flex:1}}><Input label="Hourly requests" value={edit.hourly_request_limit??''} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,hourly_request_limit:v}}))}/></View><View style={{flex:1}}><Input label="Daily requests" value={edit.daily_request_limit??''} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,daily_request_limit:v}}))}/></View></View><View style={s.two}><View style={{flex:1}}><Input label="Min interval sec" value={edit.min_interval_seconds} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,min_interval_seconds:v}}))}/></View><View style={{flex:1}}><Input label="Daily byte limit" value={edit.daily_byte_limit??''} onChange={v=>setSourceEdits(x=>({...x,[source.source_key]:{...edit,daily_byte_limit:v}}))}/></View></View><Button label="Save source policy" onPress={()=>saveSource(source)} disabled={busy}/></View>})}
  <View style={s.sectionHead}><View><Text style={s.kicker}>MARKETS</Text><Text style={s.sectionTitle}>Priority & coverage queue</Text></View><Text style={s.meta}>Top {marketRows.length}</Text></View>
  {marketRows.map((row:any)=>{const edit=marketEdits[row.id]||{priority:row.priority,enabled:row.status!=='blocked'};return <View key={row.id} style={s.market}><View style={{flex:1}}><Text style={s.rowTitle}>{row.name}{row.state_code?`, ${row.state_code}`:''}</Text><Text style={s.meta}>{row.market_kind} · {row.status} · tile {row.tile_cursor||0}/{row.tile_count||'?'}</Text></View><TextInput accessibilityLabel={`${row.name} priority`} keyboardType="numeric" value={String(edit.priority??'')} onChangeText={v=>setMarketEdits(x=>({...x,[row.id]:{...edit,priority:v}}))} style={s.priorityInput}/><Switch accessibilityLabel={`Enable ${row.name}`} value={Boolean(edit.enabled)} disabled={row.status==='running'} onValueChange={v=>setMarketEdits(x=>({...x,[row.id]:{...edit,enabled:v}}))}/><Button label="Save" onPress={()=>saveMarket(row)} disabled={busy}/></View>})}
  <View style={s.card}><Text style={s.kicker}>AUDIT</Text><Text style={s.sectionTitle}>Recent Owner changes</Text>{(data?.history||[]).slice(0,20).map((h:any)=><View key={h.id} style={s.audit}><Text style={s.rowTitle}>{String(h.action||'change').replaceAll('_',' ')}</Text><Text style={s.meta}>{h.target_key||'platform'} · {new Date(h.created_at).toLocaleString()}</Text>{h.reason?<Text style={s.meta}>{h.reason}</Text>:null}</View>)}{!(data?.history||[]).length?<Text style={s.meta}>No Owner ingestion mutations recorded yet.</Text>:null}</View>
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:18,gap:14,paddingBottom:70,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#173d2b',padding:20,borderRadius:24,gap:8},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#b9d2c2'},title:{fontSize:29,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},heroActions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:4},message:{fontWeight:'700',color:'#40584a'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:9},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:21,fontWeight:'900',color:'#173d2b'},meta:{fontSize:12,lineHeight:18,color:'#607067'},card:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:1,borderColor:'#dbe5de',gap:10},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:'#66766d'},sectionTitle:{fontSize:20,fontWeight:'900',color:'#102218'},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:12},row:{flexDirection:'row',alignItems:'center',gap:12},rowTitle:{fontWeight:'900',color:'#102218'},two:{flexDirection:'row',gap:10},field:{gap:4},label:{fontSize:11,fontWeight:'900',color:'#41564a'},input:{backgroundColor:'#f9fbf9',borderWidth:1,borderColor:'#cfdad3',borderRadius:10,padding:10,color:'#102218'},button:{borderWidth:1,borderColor:'#c8d7ce',backgroundColor:'#fff',paddingHorizontal:12,paddingVertical:10,borderRadius:11,alignSelf:'flex-start'},buttonText:{fontWeight:'900',color:'#173d2b'},dangerButton:{backgroundColor:'#fff3ef',borderColor:'#efc9bd'},dangerText:{color:'#8f3d29'},disabled:{opacity:.5},warning:{color:'#8a5b00',fontWeight:'800'},market:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dbe5de',borderRadius:16,padding:13,flexDirection:'row',alignItems:'center',gap:8},priorityInput:{width:64,borderWidth:1,borderColor:'#cfdad3',borderRadius:9,padding:8,textAlign:'center',color:'#102218'},audit:{borderTopWidth:1,borderTopColor:'#edf2ee',paddingTop:9,gap:2}});
