import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { getBusinessAnalyticsOverview, getBusinessWorkspaceOverview, getWorkspaceContext } from '../services/workspaces.js';
import BusinessOperationsPanel from './BusinessOperationsPanel.jsx';
import BusinessAdvancedOperationsPanel from './BusinessAdvancedOperationsPanel.jsx';

function Metric({label,value}){return <div><span>{label}</span><strong>{value??'—'}</strong></div>}
function JsonPanel({title,value}){if(value==null)return null;return <section className="panel compact"><div className="eyebrow">{title}</div><pre className="data-preview">{JSON.stringify(value,null,2)}</pre></section>}

export default function BusinessWorkspacePage(){
  const navigate=useNavigate();const[params]=useSearchParams();
  const[workspace,setWorkspace]=useState(null);const[overview,setOverview]=useState(null);const[analytics,setAnalytics]=useState(null);const[status,setStatus]=useState('loading');const[analyticsStatus,setAnalyticsStatus]=useState('idle');const[error,setError]=useState('');const[days,setDays]=useState(30);const[revision,setRevision]=useState(0);
  const refresh=useCallback(async()=>{setRevision(value=>value+1)},[]);
  useEffect(()=>{let active=true;(async()=>{try{const context=await getWorkspaceContext();if(!context.access.business)throw new Error('Business workspace access is not enabled for this account.');const requested=params.get('business');const row=context.businesses.find(item=>String(item.business_id)===String(requested))||context.businesses[0];if(!row)throw new Error('No authorized business workspace is available.');const next=await getBusinessWorkspaceOverview(row.business_id);if(active){setWorkspace(row);setOverview(next);setStatus('ready');}}catch(err){if(active){setError(err?.message||'Business workspace could not be loaded.');setStatus('error');}}})();return()=>{active=false;};},[params.toString(),revision]);
  useEffect(()=>{if(!workspace?.business_id)return;let active=true;setAnalyticsStatus('loading');getBusinessAnalyticsOverview(workspace.business_id,{days}).then(data=>{if(active){setAnalytics(data);setAnalyticsStatus('ready');}}).catch(err=>{if(active){setAnalytics({unavailable:{analytics:err?.message||'Analytics unavailable'}});setAnalyticsStatus('error');}});return()=>{active=false;};},[workspace?.business_id,days,revision]);
  const unavailableCount=Object.keys(analytics?.unavailable||{}).length;
  const visitorMetrics=analytics?.visitors||{};const occupancy=analytics?.occupancy||{};const benchmark=analytics?.benchmark||{};const partner=analytics?.partner||{};
  const summaryCards=useMemo(()=>[
    ['Unique visitors',visitorMetrics.unique_visitors],['Repeat visitors',visitorMetrics.repeat_visitors],['Check-ins',occupancy.check_ins],['Visits',occupancy.visits],['Peak hour',occupancy.peak_hour==null?'—':`${occupancy.peak_hour}:00`],['Peer percentile',benchmark.percentile==null?'—':`${benchmark.percentile}%`],['Partner programs',partner.partner_programs],['Active agreements',partner.active_agreements],
  ],[visitorMetrics,occupancy,benchmark,partner]);
  if(status==='loading')return <section className="panel"><div className="eyebrow">BUSINESS</div><h1>Business workspace</h1><p>Loading authorized business data…</p></section>;
  if(status==='error')return <section className="panel"><div className="eyebrow">BUSINESS</div><h1>Business workspace</h1><div className="notice error">{error}</div><button className="secondary" onClick={()=>navigate('/workspace')}>Back to workspaces</button></section>;
  const access=overview?.access||{};const summary=overview?.summary||{};const locations=overview?.locations||[];const management=overview?.management||{};
  return <>
    <section className="panel"><div className="eyebrow">BUSINESS</div><h1>{workspace.business_name||workspace.name||'Business workspace'}</h1><p>{[workspace.role,access.plan||workspace.business_tier].filter(Boolean).join(' · ')}</p><div className="detail-grid"><Metric label="Locations" value={access.location_count??locations.length}/><Metric label="Location limit" value={access.location_limit}/><Metric label="Fleet" value={access.fleet_enabled?'Enabled':'Not enabled'}/><Metric label="Enterprise" value={access.enterprise_enabled?'Enabled':'Not enabled'}/></div><div className="card-actions"><button className="secondary" onClick={()=>navigate('/workspace')}>Switch workspace</button>{access.fleet_enabled&&<button className="primary" onClick={()=>navigate('/workspace/fleet')}>Open Fleet</button>}{access.enterprise_enabled&&<button className="primary" onClick={()=>navigate('/workspace/enterprise')}>Open Enterprise</button>}</div></section>
    <BusinessOperationsPanel businessId={workspace.business_id} locations={locations} analytics={analytics||{}} management={management} onChanged={refresh}/>
    <BusinessAdvancedOperationsPanel businessId={workspace.business_id} locations={locations} analytics={analytics||{}} management={management} onChanged={refresh}/>
    <section className="panel compact"><div className="eyebrow">BUSINESS INTELLIGENCE</div><h2>Authorized performance analytics</h2><p>Canonical business analytics across engagement, QR, reviews, campaigns, visitors, occupancy, partners, media, events and benchmarks.</p><div className="card-actions">{[7,30,90].map(value=><button key={value} className={days===value?'primary':'secondary'} onClick={()=>setDays(value)}>{value} days</button>)}</div>{analyticsStatus==='loading'?<div className="notice">Refreshing analytics…</div>:<><div className="detail-grid">{summaryCards.map(([label,value])=><Metric key={label} label={label} value={value}/>)}</div>{unavailableCount>0&&<div className="notice">{unavailableCount} analytics surface{unavailableCount===1?' is':'s are'} unavailable for this account or schema state; available surfaces are still shown.</div>}</>}</section>
    <section className="panel compact"><div className="eyebrow">30-DAY SUMMARY</div><h2>Business performance</h2><pre className="data-preview">{JSON.stringify(summary,null,2)}</pre></section>
    <section className="results"><div className="eyebrow">LOCATIONS</div>{locations.length===0?<div className="notice">No authorized locations are attached to this business.</div>:locations.map(location=><article className="place-card" key={location.id}><div className="place-main"><h2>{location.name||'Business location'}</h2><p>{[location.address,location.city,location.state].filter(Boolean).join(', ')||'Address unavailable'}</p><div className="meta">{[location.rating?`${location.rating} ★`:null,location.is_active===false?'Inactive':'Active'].filter(Boolean).join(' · ')}</div></div><button className="secondary" onClick={()=>navigate(`/location/${location.id}`)}>View place</button></article>)}</section>
    <JsonPanel title="ENGAGEMENT" value={analytics?.engagement}/><JsonPanel title="LOCATION ANALYTICS" value={analytics?.locations}/><JsonPanel title="LOCATION INTELLIGENCE" value={analytics?.locationIntelligence}/><JsonPanel title="QR ATTRIBUTION" value={analytics?.qr}/><JsonPanel title="REVIEW DETAIL" value={analytics?.reviews}/><JsonPanel title="CAMPAIGNS" value={analytics?.campaigns}/><JsonPanel title="CAMPAIGN DETAIL" value={analytics?.campaignDetail}/><JsonPanel title="EVENTS" value={analytics?.events}/><JsonPanel title="MEDIA" value={analytics?.media}/><JsonPanel title="PARTNER DETAIL" value={analytics?.partnerDetail}/><JsonPanel title="ROI" value={analytics?.roi}/>
  </>;
}
