import { useEffect,useState } from 'react';
import { getBusinessRestroomReliability } from '../services/remediation.js';

function Metric({label,value}){return <div><span>{label}</span><strong>{value??'—'}</strong></div>}
function when(value){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString()}

export default function BusinessReliabilityPanel({businessId}){
  const[data,setData]=useState(null);const[days,setDays]=useState(90);const[status,setStatus]=useState('loading');const[message,setMessage]=useState('');
  useEffect(()=>{if(!businessId)return;let active=true;setStatus('loading');getBusinessRestroomReliability(businessId,days).then(next=>{if(active){setData(next||{});setStatus('ready')}}).catch(error=>{if(active){setMessage(error?.message||'Restroom reliability could not be loaded.');setStatus('error')}});return()=>{active=false}},[businessId,days]);
  const summary=data?.summary||{};const issues=Array.isArray(data?.issues)?data.issues:[];
  return <section className="panel compact"><div className="eyebrow">RESTROOM RELIABILITY</div><h2>Separate recurring failures from one-time issues</h2><p>Reliability is derived from canonical remediation history, community confirmation, failed fixes and escalations. It does not replace location truth; it exposes operational recurrence patterns.</p><div className="card-actions">{[30,90,180].map(value=><button key={value} className={days===value?'primary':'secondary'} onClick={()=>setDays(value)}>{value} days</button>)}</div>{status==='loading'?<div className="notice">Calculating canonical recurrence patterns…</div>:status==='error'?<div className="notice error">{message}</div>:<><div className="detail-grid"><Metric label="Reliability score" value={summary.average_reliability_score==null?'—':`${summary.average_reliability_score}/100`}/><Metric label="Amenity pairs tracked" value={summary.tracked_amenity_pairs??0}/><Metric label="Recurring failures" value={summary.recurring_pairs??0}/><Metric label="Failed fixes" value={summary.failed_fix_pairs??0}/><Metric label="Critical patterns" value={summary.critical_pairs??0}/></div>{issues.length?<div className="results">{issues.slice(0,20).map(row=><article className="place-card" key={`${row.location_id}:${row.amenity_id}`}><div className="place-main"><div className="eyebrow">{String(row.reliability_state||'stable').toUpperCase()} · RELIABILITY {row.reliability_score??'—'}/100</div><h3>{row.location_name||'Location'} · {row.amenity_name||'Amenity'}</h3><div className="meta">{row.issue_count||0} issue{Number(row.issue_count||0)===1?'':'s'} · {row.recurrence_count||0} recurrence{Number(row.recurrence_count||0)===1?'':'s'} · {row.escalated_count||0} escalated</div><p>{row.failed_fixes?`${row.failed_fixes} business fix${Number(row.failed_fixes)===1?' was':'es were'} reported still broken by a verified visitor.`:row.community_confirmed_fixes?`${row.community_confirmed_fixes} fix${Number(row.community_confirmed_fixes)===1?' was':'es were'} independently confirmed by verified visitors.`:row.recurrence_count?'This amenity has repeated operational failures in the selected window.':'No recurrence detected for this amenity in the selected window.'}</p><div className="meta">Latest issue {when(row.latest_issue_at)}</div></div></article>)}</div>:<div className="notice">No remediation history is available for reliability scoring in this window.</div>}</>}</section>;
}
