import { useEffect,useMemo,useState } from 'react';
import { createBusinessReverificationQr,getBusinessReverificationQueue } from '../services/reverification.js';

function Metric({label,value}){return <div><span>{label}</span><strong>{value??'—'}</strong></div>}

export default function BusinessReverificationPanel({businessId,onChanged}){
  const[data,setData]=useState(null);const[status,setStatus]=useState('loading');const[message,setMessage]=useState('');const[busy,setBusy]=useState('');
  async function refresh(){setStatus('loading');try{const next=await getBusinessReverificationQueue(businessId);setData(next||{});setStatus('ready')}catch(error){setMessage(error?.message||'Reverification queue could not be loaded.');setStatus('error')}}
  useEffect(()=>{if(businessId)refresh()},[businessId]);
  const rows=Array.isArray(data?.queue)?data.queue:[];
  const conflictCount=useMemo(()=>rows.filter(row=>Number(row?.q?.contradiction_count||0)>0).length,[rows]);
  const staleCount=useMemo(()=>rows.filter(row=>row?.q?.stale===true).length,[rows]);
  async function createQr(row){const id=String(row.location_id);setBusy(id);setMessage('');try{const qr=await createBusinessReverificationQr(businessId,id);setMessage(`Reverification QR created for ${row.name||'this restroom'}${qr?.code?` · ${qr.code}`:''}.`);await refresh();await onChanged?.()}catch(error){setMessage(error?.message||'Reverification QR could not be created.')}finally{setBusy('')}}
  return <section className="panel compact"><div className="eyebrow">REVERIFICATION OPERATIONS</div><h2>Resolve stale and conflicting restroom evidence</h2><p>Locations are ranked from canonical trust quality. QR campaigns start a verified trust mission for the exact restroom and trust flags clear automatically when fresh evidence establishes the required consensus.</p><div className="detail-grid"><Metric label="Queue" value={rows.length}/><Metric label="Conflict locations" value={conflictCount}/><Metric label="Stale locations" value={staleCount}/><Metric label="Consensus" value="3:1"/></div>{message?<div className="notice">{message}</div>:null}{status==='loading'?<div className="notice">Loading reverification queue…</div>:rows.length===0?<div className="notice">No locations currently require reverification.</div>:<div className="results">{rows.map(row=>{const q=row.q||{};return <article className="place-card" key={row.location_id}><div className="place-main"><h3>{row.name||'Restroom location'}</h3><div className="meta">Priority {row.priority_score} · {String(row.suggested_action||'reverify').replaceAll('_',' ')} · Trust {q.quality_score??'—'}/100 · {q.freshness||'unknown'}{q.contradiction_count?` · ${q.contradiction_count} conflict${q.contradiction_count===1?'':'s'}`:''}</div><p>{q.contradiction_count?'Fresh verified amenity observations are needed to resolve disputed evidence.':q.stale?'This location needs a current verified visit.':'More independent canonical evidence is needed.'}</p></div><div className="card-actions"><button className="primary" disabled={busy===String(row.location_id)} onClick={()=>createQr(row)}>{busy===String(row.location_id)?'Creating…':'Create reverification QR'}</button></div></article>})}</div>}</section>;
}
