import { useEffect,useState } from 'react';
import { getBusinessRestroomPreventiveExecutionPerformance } from '../services/remediation.js';

function Metric({label,value}){return <div><span>{label}</span><strong>{value??'—'}</strong></div>}
function hours(value){const n=Number(value);if(!Number.isFinite(n))return'—';if(n<24)return`${n}h`;return`${(n/24).toFixed(1)}d`}

export default function BusinessPreventiveExecutionPerformancePanel({businessId}){
 const[data,setData]=useState(null);const[days,setDays]=useState(90);const[message,setMessage]=useState('');
 useEffect(()=>{let active=true;if(!businessId)return;getBusinessRestroomPreventiveExecutionPerformance(businessId,days).then(next=>{if(active){setData(next||{});setMessage('')}}).catch(error=>{if(active)setMessage(error?.message||'Preventive execution performance could not be loaded.')});return()=>{active=false}},[businessId,days]);
 const summary=data?.summary||{};const locations=Array.isArray(data?.locations)?data.locations:[];
 return <section className="panel compact"><div className="eyebrow">PREVENTIVE EXECUTION PERFORMANCE</div><h2>Measure whether preventive work is executed on time</h2><p>Execution performance is derived from the same canonical preventive work orders used by operations. It measures operator responsiveness and proof discipline; it does not alter restroom trust or independent effectiveness.</p><div className="card-actions">{[30,90,180].map(value=><button key={value} className={days===value?'primary':'secondary'} onClick={()=>setDays(value)}>{value} days</button>)}</div><div className="detail-grid"><Metric label="Completion rate" value={`${summary.completion_rate_pct??0}%`}/><Metric label="On-time completion" value={`${summary.on_time_completion_pct??0}%`}/><Metric label="Escalation rate" value={`${summary.escalation_rate_pct??0}%`}/><Metric label="Proof-backed" value={`${summary.proof_rate_pct??0}%`}/><Metric label="Median completion" value={hours(summary.median_completion_hours)}/><Metric label="Average start" value={hours(summary.average_start_hours)}/><Metric label="Critical escalations" value={summary.critical_escalated??0}/><Metric label="Completed late" value={summary.completed_late??0}/></div>{message?<div className="notice">{message}</div>:null}{locations.length?<div className="results">{locations.filter(row=>Number(row.created||0)>0).map(row=><article className="place-card" key={row.location_id}><div className="place-main"><h3>{row.location_name||'Business location'}</h3><div className="meta">{row.created||0} created · {row.completed||0} completed · {row.escalated||0} escalated · {row.proof_backed||0} proof-backed</div><p>{row.completed?`${row.on_time_completion_pct??0}% completed by deadline · average completion ${hours(row.average_completion_hours)}`:'No completed preventive work in this window yet.'}</p></div></article>)}</div>:<div className="notice">No preventive execution history is available in this window yet.</div>}</section>;
}
