import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { getBusinessWorkspaceOverview, getWorkspaceContext } from '../services/workspaces.js';

export default function BusinessWorkspacePage(){
  const navigate=useNavigate();const[params]=useSearchParams();
  const[workspace,setWorkspace]=useState(null);const[overview,setOverview]=useState(null);const[status,setStatus]=useState('loading');const[error,setError]=useState('');
  useEffect(()=>{let active=true;(async()=>{try{const context=await getWorkspaceContext();if(!context.access.business)throw new Error('Business workspace access is not enabled for this account.');const requested=params.get('business');const row=context.businesses.find(item=>String(item.business_id)===String(requested))||context.businesses[0];if(!row)throw new Error('No authorized business workspace is available.');const next=await getBusinessWorkspaceOverview(row.business_id);if(active){setWorkspace(row);setOverview(next);setStatus('ready');}}catch(err){if(active){setError(err?.message||'Business workspace could not be loaded.');setStatus('error');}}})();return()=>{active=false;};},[params.toString()]);
  if(status==='loading')return <section className="panel"><div className="eyebrow">BUSINESS</div><h1>Business workspace</h1><p>Loading authorized business data…</p></section>;
  if(status==='error')return <section className="panel"><div className="eyebrow">BUSINESS</div><h1>Business workspace</h1><div className="notice error">{error}</div><button className="secondary" onClick={()=>navigate('/workspace')}>Back to workspaces</button></section>;
  const access=overview?.access||{};const summary=overview?.summary||{};const locations=overview?.locations||[];
  return <><section className="panel"><div className="eyebrow">BUSINESS</div><h1>{workspace.business_name||workspace.name||'Business workspace'}</h1><p>{[workspace.role,access.plan||workspace.business_tier].filter(Boolean).join(' · ')}</p><div className="detail-grid"><div><span>Locations</span><strong>{access.location_count??locations.length}</strong></div><div><span>Location limit</span><strong>{access.location_limit??'—'}</strong></div><div><span>Fleet</span><strong>{access.fleet_enabled?'Enabled':'Not enabled'}</strong></div><div><span>Enterprise</span><strong>{access.enterprise_enabled?'Enabled':'Not enabled'}</strong></div></div><div className="card-actions"><button className="secondary" onClick={()=>navigate('/workspace')}>Switch workspace</button>{access.fleet_enabled&&<button className="primary" onClick={()=>navigate('/workspace/fleet')}>Open Fleet</button>}{access.enterprise_enabled&&<button className="primary" onClick={()=>navigate('/workspace/enterprise')}>Open Enterprise</button>}</div></section><section className="panel compact"><div className="eyebrow">30-DAY SUMMARY</div><h2>Business performance</h2><pre className="data-preview">{JSON.stringify(summary,null,2)}</pre></section><section className="results"><div className="eyebrow">LOCATIONS</div>{locations.length===0?<div className="notice">No authorized locations are attached to this business.</div>:locations.map(location=><article className="place-card" key={location.id}><div className="place-main"><h2>{location.name||'Business location'}</h2><p>{[location.address,location.city,location.state].filter(Boolean).join(', ')||'Address unavailable'}</p><div className="meta">{[location.rating?`${location.rating} ★`:null,location.is_active===false?'Inactive':'Active'].filter(Boolean).join(' · ')}</div></div><button className="secondary" onClick={()=>navigate(`/location/${location.id}`)}>View place</button></article>)}</section></>;
}
