import { useMemo, useState } from 'react';
import { createBusinessCampaign, createBusinessEvent, createBusinessLocation, createBusinessPromotion, createBusinessQr, deactivateBusinessLocation, deactivateBusinessQr, replyToBusinessReview, setBusinessCampaignStatus } from '../services/businessOperations.js';

const emptyLocation={name:'',address:'',city:'',state:'',postal_code:'',country:'US',description:'',phone:'',website:''};
const emptyPromotion={title:'',description:'',discount:'',location_id:'',starts_at:'',ends_at:'',active:true};
const emptyCampaign={name:'',campaignType:'',goal:'',status:'draft'};
const emptyEvent={title:'',description:'',location_id:'',event_date:'',event_time:''};

function Field({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function ActionForm({title,children,onSubmit,busy,submitLabel='Create'}){return <form className="panel compact" onSubmit={onSubmit}><div className="eyebrow">OPERATIONS</div><h2>{title}</h2>{children}<button className="primary" disabled={busy} type="submit">{busy?'Saving…':submitLabel}</button></form>}

export default function BusinessOperationsPanel({businessId,locations=[],analytics={},management={},onChanged}){
  const[location,setLocation]=useState(emptyLocation);const[promotion,setPromotion]=useState(emptyPromotion);const[campaign,setCampaign]=useState(emptyCampaign);const[event,setEvent]=useState(emptyEvent);const[qrLabel,setQrLabel]=useState('');const[qrLocation,setQrLocation]=useState('');const[replyReviewId,setReplyReviewId]=useState('');const[reply,setReply]=useState('');const[busy,setBusy]=useState('');const[notice,setNotice]=useState('');
  const campaigns=useMemo(()=>Array.isArray(analytics?.campaignDetail)?analytics.campaignDetail:Array.isArray(analytics?.campaigns)?analytics.campaigns:[],[analytics]);
  const reviews=useMemo(()=>Array.isArray(analytics?.reviews)?analytics.reviews:[],[analytics]);
  const qrRows=useMemo(()=>Array.isArray(analytics?.qr)?analytics.qr:[],[analytics]);
  async function run(key,fn,message){setBusy(key);setNotice('');try{await fn();setNotice(message);await onChanged?.();}catch(err){setNotice(err?.message||'Operation failed.')}finally{setBusy('')}}
  if(management?.can_manage===false)return <section className="panel compact"><div className="eyebrow">OPERATIONS</div><h2>Business controls</h2><div className="notice">Your business role has analytics access but not mutation authority.</div></section>;
  return <section className="results"><div className="eyebrow">BUSINESS OPERATIONS</div>{notice&&<div className="notice">{notice}</div>}
    <ActionForm title="Add location" busy={busy==='location'} onSubmit={e=>{e.preventDefault();run('location',()=>createBusinessLocation(businessId,location),'Location created.').then(()=>setLocation(emptyLocation))}}><div className="detail-grid"><Field label="Name" value={location.name} required onChange={e=>setLocation({...location,name:e.target.value})}/><Field label="Address" value={location.address} onChange={e=>setLocation({...location,address:e.target.value})}/><Field label="City" value={location.city} onChange={e=>setLocation({...location,city:e.target.value})}/><Field label="State" value={location.state} onChange={e=>setLocation({...location,state:e.target.value})}/><Field label="Postal code" value={location.postal_code} onChange={e=>setLocation({...location,postal_code:e.target.value})}/><Field label="Phone" value={location.phone} onChange={e=>setLocation({...location,phone:e.target.value})}/><Field label="Website" value={location.website} onChange={e=>setLocation({...location,website:e.target.value})}/></div></ActionForm>
    <ActionForm title="Create promotion" busy={busy==='promotion'} onSubmit={e=>{e.preventDefault();run('promotion',()=>createBusinessPromotion(businessId,{...promotion,location_id:promotion.location_id||null,starts_at:promotion.starts_at||null,ends_at:promotion.ends_at||null}),'Promotion created.').then(()=>setPromotion(emptyPromotion))}}><Field label="Title" value={promotion.title} required onChange={e=>setPromotion({...promotion,title:e.target.value})}/><Field label="Description" value={promotion.description} onChange={e=>setPromotion({...promotion,description:e.target.value})}/><Field label="Discount" value={promotion.discount} onChange={e=>setPromotion({...promotion,discount:e.target.value})}/><label className="field"><span>Location</span><select value={promotion.location_id} onChange={e=>setPromotion({...promotion,location_id:e.target.value})}><option value="">All / none</option>{locations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></ActionForm>
    <ActionForm title="Create campaign" busy={busy==='campaign'} onSubmit={e=>{e.preventDefault();run('campaign',()=>createBusinessCampaign(businessId,campaign),'Campaign created.').then(()=>setCampaign(emptyCampaign))}}><Field label="Name" value={campaign.name} required onChange={e=>setCampaign({...campaign,name:e.target.value})}/><Field label="Campaign type" value={campaign.campaignType} onChange={e=>setCampaign({...campaign,campaignType:e.target.value})}/><Field label="Goal" value={campaign.goal} onChange={e=>setCampaign({...campaign,goal:e.target.value})}/></ActionForm>
    <ActionForm title="Create event" busy={busy==='event'} onSubmit={e=>{e.preventDefault();run('event',()=>createBusinessEvent(businessId,{...event,location_id:event.location_id||null,event_date:event.event_date||null,event_time:event.event_time||null}),'Event created.').then(()=>setEvent(emptyEvent))}}><Field label="Title" value={event.title} required onChange={e=>setEvent({...event,title:e.target.value})}/><Field label="Description" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><label className="field"><span>Location</span><select value={event.location_id} onChange={e=>setEvent({...event,location_id:e.target.value})}><option value="">None</option>{locations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><Field label="Date" type="date" value={event.event_date} onChange={e=>setEvent({...event,event_date:e.target.value})}/><Field label="Time" type="time" value={event.event_time} onChange={e=>setEvent({...event,event_time:e.target.value})}/></ActionForm>
    <ActionForm title="Create location QR" busy={busy==='qr'} onSubmit={e=>{e.preventDefault();run('qr',()=>createBusinessQr(businessId,qrLocation,{label:qrLabel||'Location QR'}),'QR code created.').then(()=>{setQrLabel('');setQrLocation('')})}}><label className="field"><span>Location</span><select required value={qrLocation} onChange={e=>setQrLocation(e.target.value)}><option value="">Choose location</option>{locations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><Field label="Label" value={qrLabel} onChange={e=>setQrLabel(e.target.value)}/></ActionForm>
    <ActionForm title="Reply to review" busy={busy==='reply'} submitLabel="Save reply" onSubmit={e=>{e.preventDefault();run('reply',()=>replyToBusinessReview(businessId,replyReviewId,reply),'Review reply saved.')}}><label className="field"><span>Review</span><select required value={replyReviewId} onChange={e=>setReplyReviewId(e.target.value)}><option value="">Choose review</option>{reviews.map(row=><option key={row.id} value={row.id}>{row.title||row.reviewer_name||row.id}</option>)}</select></label><label className="field"><span>Reply</span><textarea value={reply} onChange={e=>setReply(e.target.value)} /></label></ActionForm>
    {campaigns.length>0&&<section className="panel compact"><div className="eyebrow">CAMPAIGN CONTROL</div>{campaigns.map(row=><article className="place-card" key={row.id}><div className="place-main"><h2>{row.name||'Campaign'}</h2><div className="meta">{row.status||'draft'}</div></div><button className="secondary" disabled={busy===`campaign-${row.id}`} onClick={()=>run(`campaign-${row.id}`,()=>setBusinessCampaignStatus(businessId,row.id,row.status!=='active'),row.status==='active'?'Campaign paused.':'Campaign activated.')}>{row.status==='active'?'Pause':'Activate'}</button></article>)}</section>}
    {qrRows.length>0&&<section className="panel compact"><div className="eyebrow">QR LIFECYCLE</div>{qrRows.map(row=><article className="place-card" key={row.id}><div className="place-main"><h2>{row.label||'QR code'}</h2><div className="meta">{row.active===false?'Inactive':'Active'}{row.scans!=null?` · ${row.scans} scans`:''}</div></div>{row.active!==false&&<button className="secondary" disabled={busy===`qr-${row.id}`} onClick={()=>run(`qr-${row.id}`,()=>deactivateBusinessQr(businessId,row.id,row.location_id||null),'QR code deactivated.')}>Deactivate</button>}</article>)}</section>}
    {locations.length>0&&<section className="panel compact"><div className="eyebrow">LOCATION CONTROL</div>{locations.map(row=><article className="place-card" key={row.id}><div className="place-main"><h2>{row.name}</h2><div className="meta">{row.is_active===false?'Inactive':'Active'}</div></div>{row.is_active!==false&&<button className="secondary" disabled={busy===`location-${row.id}`} onClick={()=>run(`location-${row.id}`,()=>deactivateBusinessLocation(businessId,row.id),'Location deactivated.')}>Deactivate</button>}</article>)}</section>}
  </section>;
}
