import { useEffect,useState } from 'react';
import { useNavigate,useSearchParams } from 'react-router-dom';
import { getFleetWorkspaceOverview,getWorkspaceContext } from '../services/workspaces.js';
import FleetPreventiveDispatchPanel from './FleetPreventiveDispatchPanel.jsx';

function Metric({label,value}){return <div><span>{label}</span><strong>{value??'—'}</strong></div>}
function actionLabel(value){return String(value||'monitor').replaceAll('_',' ')}
function when(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
function verificationLabel(row){if(row.verification_status==='failed')return'FOLLOW-UP REQUIRED';if(row.verification_status==='pending')return'AWAITING COMMUNITY VERIFICATION';if(row.verification_status==='effective')return'COMMUNITY VERIFIED EFFECTIVE';return null}
function effectivenessLabel(value){return String(value||'').replaceAll('_',' ').toUpperCase()}
function slaLabel(row){if(!['planned','assigned','in_progress'].includes(row.status))return null;if(Number(row.escalation_level||0)>=2)return'CRITICAL OVERDUE';if(Number(row.escalation_level||0)>=1)return'OVERDUE';if(row.due_at){const due=new Date(row.due_at).getTime(),now=Date.now();if(Number.isFinite(due)&&due>now&&due-now<=4*60*60*1000)return'DUE SOON';}return null}

export default function FleetWorkspacePage(){
 const navigate=useNavigate();const[params]=useSearchParams();const[data,setData]=useState(null);const[business,setBusiness]=useState(null);const[status,setStatus]=useState('loading');const[error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const context=await getWorkspaceContext();if(!context.access.fleet)throw new Error('Fleet workspace access is not enabled for this account.');const requested=params.get('business');const row=context.businesses.find(item=>String(item.business_id)===String(requested))||context.businesses[0];if(!row)throw new Error('A Fleet-enabled business membership is required.');const overview=await getFleetWorkspaceOverview(row.business_id);if(active){setBusiness(row);setData(overview);setStatus('ready');}}catch(err){if(active){setError(err?.message||'Fleet workspace could not be loaded.');setStatus('error');}}})();return()=>{active=false;};},[params.toString()]);
 if(status==='loading')return <section className="panel"><div className="eyebrow">FLEET</div><h1>Fleet workspace</h1><p>Loading dispatch and operations…</p></section>;
 if(status==='error')return <section className="panel"><div className="eyebrow">FLEET</div><h1>Fleet workspace</h1><div className="notice error">{error}</div><button className="secondary" onClick={()=>navigate('/workspace')}>Back to workspaces</button></section>;
 const remediation=data?.remediationRisk||{},riskSummary=remediation.summary||{},riskLocations=Array.isArray(remediation.locations)?remediation.locations:[];
 const prevention=data?.preventionPortfolio||{},preventionSummary=prevention.summary||{},preventionLocations=Array.isArray(prevention.locations)?prevention.locations:[];
 const schedule=data?.preventiveSchedule||{},scheduleSummary=schedule.summary||{},workOrders=Array.isArray(schedule.work_orders)?schedule.work_orders:[];
 const effectiveness=data?.preventionEffectiveness||{},effectSummary=effectiveness.summary||{},interventions=Array.isArray(effectiveness.interventions)?effectiveness.interventions:[];
 const attentionInterventions=interventions.filter(row=>['failed_verification','recurrence_detected','pending_verification'].includes(row.effectiveness_state));
 const operationalWork=workOrders.filter(row=>['planned','assigned','in_progress'].includes(row.status)||row.verification_status==='pending'||row.verification_status==='failed');
 const proofBacked=workOrders.filter(row=>row.status==='completed'&&row.proof_media_id).length;
 const completedCount=workOrders.filter(row=>row.status==='completed').length;
 const operationsUrl=`/workspace/business?business=${encodeURIComponent(business.business_id)}&focus=remediation`;
 const preventionUrl=id=>`/workspace/business?business=${encodeURIComponent(business.business_id)}&focus=prevention${id?`&work_order=${encodeURIComponent(id)}`:''}`;
 return <><section className="panel"><div className="eyebrow">FLEET</div><h1>{business?.business_name||'Fleet operations'}</h1><p>Current-user dispatch, operational intelligence, restroom reliability risk, and preventive-maintenance execution from production Fleet authority.</p><button className="secondary" onClick={()=>navigate('/workspace')}>Switch workspace</button></section>
 <section className="panel compact"><div className="eyebrow">RESTROOM OPERATIONS RISK</div><h2>Prioritize recurring and failed remediation across the fleet</h2><p>This Fleet view ranks locations from the same canonical remediation cases, escalations, and verified post-fix community evidence used by business operations.</p><div className="detail-grid"><Metric label="Operational reliability" value={riskSummary.average_operational_reliability==null?'—':`${riskSummary.average_operational_reliability}/100`}/><Metric label="Locations with active work" value={riskSummary.locations_with_active_work??0}/><Metric label="Critical locations" value={riskSummary.critical_locations??0}/><Metric label="High-risk locations" value={riskSummary.high_risk_locations??0}/><Metric label="Failed-fix locations" value={riskSummary.failed_fix_locations??0}/></div>{riskLocations.length?<div className="results">{riskLocations.map(row=><article className="place-card" key={row.location_id}><div className="place-main"><div className="eyebrow">{String(row.risk_state||'stable').toUpperCase()} · RELIABILITY {row.operational_reliability_score??'—'}/100</div><h3>{row.location_name||'Fleet location'}</h3><div className="meta">{row.active_count||0} active · {row.issue_count||0} issues · {row.affected_amenities||0} amenities affected · {row.escalated_count||0} escalated</div></div><button className="secondary" onClick={()=>navigate(operationsUrl)}>Open operations</button></article>)}</div>:<div className="notice">No Fleet remediation risk is currently recorded.</div>}</section>
 <section className="panel compact"><div className="eyebrow">PREVENTION READINESS</div><h2>Turn recurrence into preventive routing</h2><p>Fleet prevention readiness converts repeated failures and failed fixes into recommended root-cause inspections, preventive routes, SLA reviews, and inspection watches.</p><div className="detail-grid"><Metric label="Prevention readiness" value={preventionSummary.average_prevention_readiness==null?'—':`${preventionSummary.average_prevention_readiness}/100`}/><Metric label="Root-cause locations" value={preventionSummary.root_cause_locations??0}/><Metric label="Preventive-route locations" value={preventionSummary.preventive_route_locations??0}/></div>{preventionLocations.filter(row=>row.recommended_action!=='monitor').length?<div className="results">{preventionLocations.filter(row=>row.recommended_action!=='monitor').map(row=><article className="place-card" key={`prevent:${row.location_id}`}><div className="place-main"><div className="eyebrow">READINESS {row.prevention_readiness_score??'—'}/100 · {actionLabel(row.recommended_action).toUpperCase()}</div><h3>{row.location_name||'Fleet location'}</h3><div className="meta">{row.repeat_issue_count||0} repeat issues · {row.failed_fix_count||0} failed fixes · {row.active_count||0} active · {row.escalated_count||0} escalated</div><p>Recommended Fleet action: {actionLabel(row.recommended_action)}.</p></div><button className="secondary" onClick={()=>navigate(preventionUrl())}>Open prevention work</button></article>)}</div>:<div className="notice">Fleet recurrence patterns currently support normal monitoring.</div>}</section>
 <section className="panel compact"><div className="eyebrow">PREVENTION EFFECTIVENESS</div><h2>Measure whether preventive work actually holds</h2><p>Effectiveness is earned only through independent verification and later canonical evidence. Recurrence after a verified intervention moves that location back to the top of Fleet inspection planning.</p><div className="detail-grid"><Metric label="Intervention score" value={effectSummary.average_intervention_score==null?'—':`${effectSummary.average_intervention_score}/100`}/><Metric label="Verification rate" value={`${effectSummary.verification_rate_pct??0}%`}/><Metric label="Effective rate" value={`${effectSummary.effective_rate_pct??0}%`}/><Metric label="30d recurrence" value={`${effectSummary.recurrence_rate_30d_pct??0}%`}/><Metric label="Durable 30d" value={effectSummary.durable_30d??0}/><Metric label="7d recurrence" value={effectSummary.recurrence_7d??0}/></div>{attentionInterventions.length?<div className="results">{attentionInterventions.map(row=><article className="place-card" key={`effect:${row.work_order_id}`}><div className="place-main"><div className="eyebrow">{effectivenessLabel(row.effectiveness_state)} · INTERVENTION {row.intervention_score??'—'}/100</div><h3>{row.location_name||'Fleet location'} · {row.amenity_name||'Amenity'}</h3><div className="meta">Verified {when(row.verified_at)} · Next check {when(row.recommended_next_check_at)}</div><p>{row.effectiveness_state==='recurrence_detected'?`Canonical evidence shows recurrence${row.recurrence_at?` at ${when(row.recurrence_at)}`:''}. Route an earlier inspection or follow-up.`:row.effectiveness_state==='failed_verification'?'Independent verification failed. Prioritize the follow-up work order before routine prevention.':'Preventive work is complete but still needs independent community verification.'}</p></div><button className="secondary" onClick={()=>navigate(preventionUrl(row.work_order_id))}>Open prevention work</button></article>)}</div>:<div className="notice">No failed, recurrent, or verification-pending interventions are currently driving Fleet attention.</div>}</section>
 <FleetPreventiveDispatchPanel businessId={business.business_id} initialData={data?.preventiveDispatch}/>
 <section className="panel compact"><div className="eyebrow">PREVENTIVE WORK SCHEDULE</div><h2>Coordinate restroom prevention with Fleet operations</h2><p>This schedule carries execution, SLA escalation, business proof, and independent-verification state. Critical-overdue work is ordered ahead of routine prevention, while maintenance photos never substitute for visitor evidence.</p><div className="detail-grid"><Metric label="Active work orders" value={scheduleSummary.active??0}/><Metric label="Due soon" value={scheduleSummary.due_soon??0}/><Metric label="Overdue" value={scheduleSummary.overdue??0}/><Metric label="Escalated" value={scheduleSummary.escalated??0}/><Metric label="Critical overdue" value={scheduleSummary.critical_overdue??0}/><Metric label="Awaiting verification" value={scheduleSummary.awaiting_verification??0}/><Metric label="Verified effective" value={scheduleSummary.verified_effective??0}/><Metric label="Failed verification" value={scheduleSummary.failed_verification??0}/><Metric label="Proof-backed completed" value={completedCount?`${proofBacked}/${completedCount}`:'0/0'}/></div>{operationalWork.length?<div className="results">{operationalWork.map(row=>{const verification=verificationLabel(row),sla=slaLabel(row);return <article className="place-card" key={`work:${row.id}`}><div className="place-main"><div className="eyebrow">{String(row.priority||'watch').toUpperCase()} · {String(row.status||'planned').replaceAll('_',' ').toUpperCase()}{sla?` · ${sla}`:''}{verification?` · ${verification}`:''}{row.proof_media_id?' · PHOTO PROOF':''}</div><h3>{row.location_name||'Fleet location'} · {row.amenity_name||'Amenity'}</h3><div className="meta">{actionLabel(row.recommendation_action)} · Due {when(row.due_at)}{row.escalated_at?` · Escalated ${when(row.escalated_at)}`:''}{row.verified_at?` · Verified ${when(row.verified_at)}`:''}</div><p>{sla==='CRITICAL OVERDUE'?'This preventive task is critically overdue. Route or reassign it before lower-risk maintenance.':sla==='OVERDUE'?'This preventive task has passed its deadline and is escalated for Fleet attention.':sla==='DUE SOON'?'This preventive task is due within four hours and should be sequenced ahead of routine work.':row.verification_status==='failed'?'Post-maintenance fresh community evidence has shown the issue persists. Prioritize the generated follow-up work order in routing and staffing.':row.verification_status==='pending'?`Preventive work is complete${row.proof_media_id?' with business photo proof':''}, but independent visitor verification is still pending.`:'Include this preventive task when sequencing site visits, staffing, or inspection routes.'}</p></div><button className="secondary" onClick={()=>navigate(preventionUrl(row.id))}>Open work order</button></article>})}</div>:<div className="notice">No active or verification-pending restroom preventive work.</div>}</section>
 <section className="workspace-data-grid"><article className="panel compact"><h2>My dispatch</h2><pre className="data-preview">{JSON.stringify(data.dispatch,null,2)}</pre></article><article className="panel compact"><h2>Fleet summary</h2><pre className="data-preview">{JSON.stringify(data.summary,null,2)}</pre></article><article className="panel compact"><h2>24-hour signals</h2><pre className="data-preview">{JSON.stringify(data.signals,null,2)}</pre></article><article className="panel compact"><h2>Exceptions</h2><pre className="data-preview">{JSON.stringify(data.exceptions,null,2)}</pre></article></section></>;
}
