import { useEffect,useState } from 'react';
import { useNavigate,useSearchParams } from 'react-router-dom';
import { getFleetWorkspaceOverview,getWorkspaceContext } from '../services/workspaces.js';

export default function FleetWorkspacePage(){
 const navigate=useNavigate();const[params]=useSearchParams();const[data,setData]=useState(null);const[business,setBusiness]=useState(null);const[status,setStatus]=useState('loading');const[error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{try{const context=await getWorkspaceContext();if(!context.access.fleet)throw new Error('Fleet workspace access is not enabled for this account.');const requested=params.get('business');const row=context.businesses.find(item=>String(item.business_id)===String(requested))||context.businesses[0];if(!row)throw new Error('A Fleet-enabled business membership is required.');const overview=await getFleetWorkspaceOverview(row.business_id);if(active){setBusiness(row);setData(overview);setStatus('ready');}}catch(err){if(active){setError(err?.message||'Fleet workspace could not be loaded.');setStatus('error');}}})();return()=>{active=false;};},[params.toString()]);
 if(status==='loading')return <section className="panel"><div className="eyebrow">FLEET</div><h1>Fleet workspace</h1><p>Loading dispatch and operations…</p></section>;
 if(status==='error')return <section className="panel"><div className="eyebrow">FLEET</div><h1>Fleet workspace</h1><div className="notice error">{error}</div><button className="secondary" onClick={()=>navigate('/workspace')}>Back to workspaces</button></section>;
 return <><section className="panel"><div className="eyebrow">FLEET</div><h1>{business?.business_name||'Fleet operations'}</h1><p>Current-user dispatch and operational intelligence from the production Fleet authority.</p><button className="secondary" onClick={()=>navigate('/workspace')}>Switch workspace</button></section><section className="workspace-data-grid"><article className="panel compact"><h2>My dispatch</h2><pre className="data-preview">{JSON.stringify(data.dispatch,null,2)}</pre></article><article className="panel compact"><h2>Fleet summary</h2><pre className="data-preview">{JSON.stringify(data.summary,null,2)}</pre></article><article className="panel compact"><h2>24-hour signals</h2><pre className="data-preview">{JSON.stringify(data.signals,null,2)}</pre></article><article className="panel compact"><h2>Exceptions</h2><pre className="data-preview">{JSON.stringify(data.exceptions,null,2)}</pre></article></section></>;
}
