import { useEffect,useState } from 'react';
import { attachPreventiveWorkToFleetRoute,getFleetPreventiveDispatchOpportunities } from '../services/workspaces.js';

function when(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
function actionLabel(value){return String(value||'preventive work').replaceAll('_',' ')}
function urgency(row){if(Number(row.escalation_level||0)>=2)return'CRITICAL OVERDUE';if(Number(row.escalation_level||0)>=1)return'OVERDUE';if(row.due_at){const due=new Date(row.due_at).getTime(),now=Date.now();if(Number.isFinite(due)&&due>now&&due-now<=4*60*60*1000)return'DUE SOON';}return String(row.priority||'watch').toUpperCase()}

export default function FleetPreventiveDispatchPanel({businessId,initialData=null}){
 const[data,setData]=useState(initialData||{});const[selected,setSelected]=useState({});const[busy,setBusy]=useState('');const[message,setMessage]=useState('');
 async function refresh(){try{const next=await getFleetPreventiveDispatchOpportunities(businessId);setData(next||{});setMessage('')}catch(error){setMessage(error?.message||'Preventive dispatch opportunities could not be loaded.')}}
 useEffect(()=>{if(businessId)refresh()},[businessId]);
 const work=Array.isArray(data?.work_orders)?data.work_orders:[];const routes=Array.isArray(data?.routes)?data.routes:[];
 async function attach(row){const id=String(row.work_order_id),routeId=selected[id];if(!routeId)return setMessage('Choose an unlocked planned route first.');setBusy(id);setMessage('');try{const result=await attachPreventiveWorkToFleetRoute(businessId,id,routeId);setMessage(result.already_attached?'This preventive work was already on that Fleet route.':'Preventive work appended as a canonical Fleet route stop.');await refresh()}catch(error){setMessage(error?.message||'Preventive work could not be attached to the Fleet route.')}finally{setBusy('')}}
 return <section className="panel compact"><div className="eyebrow">PREVENTIVE DISPATCH</div><h2>Route urgent prevention through the existing Fleet stop model</h2><p>Preventive work remains the operational authority. Routing only appends a normal Fleet route stop with metadata pointing back to the work order—there is no parallel task or dispatch lifecycle.</p>{message?<div className="notice">{message}</div>:null}<div className="detail-grid"><div><span>Active preventive work</span><strong>{work.length}</strong></div><div><span>Unlocked planned routes</span><strong>{routes.length}</strong></div><div><span>Already routed</span><strong>{work.filter(row=>row.assigned_route_stop_id).length}</strong></div></div>{work.length?<div className="results">{work.map(row=>{const id=String(row.work_order_id);return <article className="place-card" key={id}><div className="place-main"><div className="eyebrow">{urgency(row)} · {String(row.status||'planned').replaceAll('_',' ').toUpperCase()}</div><h3>{row.location_name||'Fleet location'} · {row.amenity_name||'Amenity'}</h3><div className="meta">{actionLabel(row.recommendation_action)} · Due {when(row.due_at)}</div><p>{row.assigned_route_stop_id?`Already attached to Fleet route ${row.assigned_route_id}. The route stop points back to this preventive work order.`:'Choose an unlocked planned Fleet route to append this location as a canonical stop.'}</p>{!row.assigned_route_stop_id?<div className="card-actions"><select value={selected[id]||''} onChange={event=>setSelected(current=>({...current,[id]:event.target.value}))}><option value="">Choose planned route</option>{routes.map(route=><option key={route.route_id} value={route.route_id}>{route.name||'Fleet route'} · {when(route.scheduled_for)} · {route.stops_count||0} stops</option>)}</select><button className="primary" disabled={!selected[id]||busy===id||routes.length===0} onClick={()=>attach(row)}>Add to route</button></div>:null}</div></article>})}</div>:<div className="notice">No active preventive work currently needs Fleet routing.</div>}</section>;
}
