import { useMemo,useState } from 'react';
import { recordFleetRouteStopTiming } from '../services/workspaces.js';

function when(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
function label(value){return String(value||'preventive work').replaceAll('_',' ')}

export default function FleetPreventiveDriverStopsPanel({businessId,dispatch,onChanged}){
 const[busy,setBusy]=useState('');const[message,setMessage]=useState('');
 const stops=useMemo(()=>Array.isArray(dispatch?.preventive_stops)?dispatch.preventive_stops:[],[dispatch]);
 async function mark(stop,eventType,success){const key=`${stop.route_stop_id}:${eventType}`;setBusy(key);setMessage('');try{await recordFleetRouteStopTiming(businessId,stop.route_id,stop.route_stop_id,eventType);setMessage(success);await onChanged?.()}catch(error){setMessage(error?.message||'Fleet stop update failed.')}finally{setBusy('')}}
 return <section className="panel compact"><div className="eyebrow">MY PREVENTIVE STOPS</div><h2>Execute routed restroom prevention from the driver dispatch</h2><p>These stops come from your canonical Fleet routes. Starting service moves the preventive work order into progress. Completing the Fleet stop does not complete maintenance—it prompts the business for notes/proof and keeps independent verification intact.</p>{message?<div className="notice">{message}</div>:null}{stops.length?<div className="results">{stops.map(stop=>{const key=String(stop.route_stop_id),status=String(stop.stop_status||'planned');return <article className="place-card" key={key}><div className="place-main"><div className="eyebrow">{String(stop.priority||'watch').toUpperCase()} · STOP {stop.stop_order??'—'} · {status.replaceAll('_',' ').toUpperCase()}</div><h3>{stop.route_name||'Fleet route'} · Preventive restroom work</h3><div className="meta">{label(stop.recommendation_action)} · Due {when(stop.due_at)} · Work order {stop.work_order_id}</div><p>Record the real route-stop state here. Maintenance completion remains a separate business signoff with notes/proof.</p></div><div className="card-actions">{status==='planned'?<button disabled={busy.startsWith(key)} onClick={()=>mark(stop,'arrived','Arrival recorded.')}>Arrived</button>:null}{['planned','arrived'].includes(status)?<button className="primary" disabled={busy.startsWith(key)} onClick={()=>mark(stop,'service_started','Service started. Preventive work is now in progress.')}>Start service</button>:null}{status==='servicing'?<button className="primary" disabled={busy.startsWith(key)} onClick={()=>mark(stop,'completed','Fleet stop completed. Business maintenance signoff is still required.')}>Complete stop</button>:null}{!['completed','skipped'].includes(status)?<button disabled={busy.startsWith(key)} onClick={()=>mark(stop,'skipped','Stop skipped. Preventive work remains active.')}>Skip stop</button>:null}</div></article>})}</div>:<div className="notice">No preventive maintenance stops are assigned to your current Fleet routes.</div>}</section>;
}
