import { getKleenestSupabaseClient } from '@kleenest/mobile-core';

export type DiscoveryMethod='remote'|'address'|'place_search'|'map_pin'|'gps'|'onsite_live';
export type DiscoveryInput={method:DiscoveryMethod;name?:string;address?:string;latitude?:number|null;longitude?:number|null;place_type?:string;external_source?:string|null;external_id?:string|null};
export type DiscoveryPhotoDraft={uri:string;width:number|null;height:number|null;fileName:string|null;mimeType:string|null;fileSize:number|null};

async function requireUser(){const client=getKleenestSupabaseClient();const{data,error}=await client.auth.getUser();if(error)throw error;if(!data.user)throw new Error('Sign in to contribute and earn XP.');return data.user;}

export async function matchOrCreateDiscovery(input:DiscoveryInput){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_match_or_create_discovery',{p_input:input});if(error)throw error;return data||{};}
export async function recordDiscoveryEvidence(locationId:string,input:Record<string,unknown>){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_record_discovery_evidence',{p_location_id:locationId,p_input:input});if(error)throw error;return data||{};}
export async function getProgressionOverviewV2(){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_progression_overview');if(error)throw error;return data||{};}
export async function listActiveObjectivesV2(){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_active_objectives');if(error)throw error;return Array.isArray(data)?data:[];}
export async function listProgressionRankingsV2(scope='global',metric='xp',context:Record<string,unknown>={}){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_progression_rankings',{p_scope:scope,p_metric:metric,p_context:context});if(error)throw error;return Array.isArray(data)?data:[];}
export async function listNearbyProgressionOpportunities(latitude:number,longitude:number,radiusMeters=5000){await requireUser();const{data,error}=await getKleenestSupabaseClient().rpc('consumer_nearby_progression_opportunities',{p_lat:latitude,p_lon:longitude,p_radius_m:radiusMeters});if(error)throw error;return Array.isArray(data)?data:[];}

function extensionFor(photo:DiscoveryPhotoDraft){const ext=photo.fileName?.split('.').pop()?.toLowerCase();if(ext&&/^[a-z0-9]{2,5}$/.test(ext))return ext;if(photo.mimeType==='image/png')return'png';if(photo.mimeType==='image/webp')return'webp';return'jpg';}
export async function uploadDiscoveryPhoto(discoveryId:string,photo:DiscoveryPhotoDraft){const user=await requireUser();if(photo.fileSize!=null&&photo.fileSize>8*1024*1024)throw new Error('Discovery photos must be 8 MB or smaller.');const response=await fetch(photo.uri);if(!response.ok)throw new Error('The selected photo could not be read.');const bytes=await response.arrayBuffer();if(bytes.byteLength>8*1024*1024)throw new Error('Discovery photos must be 8 MB or smaller.');const extension=extensionFor(photo);const contentType=photo.mimeType||(extension==='png'?'image/png':extension==='webp'?'image/webp':'image/jpeg');const storagePath=`${user.id}/${discoveryId}/${Date.now()}.${extension}`;const client=getKleenestSupabaseClient();const{error:uploadError}=await client.storage.from('discovery-photos').upload(storagePath,bytes,{contentType,upsert:false});if(uploadError)throw uploadError;const{data,error}=await client.rpc('attach_discovery_photo',{p_discovery_id:discoveryId,p_storage_path:storagePath,p_mime_type:contentType,p_size_bytes:bytes.byteLength,p_width:photo.width,p_height:photo.height});if(error)throw error;return data||{};}
export async function listDiscoveryPhotos(locationId:string){const client=getKleenestSupabaseClient();const{data,error}=await client.rpc('discovery_photos_for_location',{p_location_id:locationId});if(error)throw error;return(Array.isArray(data)?data:[]).map((row:any)=>({...row,public_url:client.storage.from('discovery-photos').getPublicUrl(String(row.storage_path)).data.publicUrl}));}
