import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
import { GAME_DEFINITIONS } from './gameModes';

export type QuizQuestion={prompt:string;options:string[];correctIndex:number};
export const QUIZ_GAMES=GAME_DEFINITIONS;
export const QUESTIONS:QuizQuestion[]=[
  {prompt:'Which signal is strongest for a trustworthy restroom review?',options:['Verified check-in plus useful observation','A random rating with no visit','A copied description'],correctIndex:0},
  {prompt:'Which detail helps the next visitor most?',options:['Specific cleanliness and amenity facts','Only a star number','Only a joke'],correctIndex:0},
];
export function shuffledQuestion(question:QuizQuestion){const options=question.options.map((text,index)=>({text,index}));for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]];}return{prompt:question.prompt,options,correctIndex:question.correctIndex};}
export async function getGameFreshnessProfile(gameCode?:string|null,cooldownDays=30){const{data,error}=await getKleenestSupabaseClient().rpc('game_freshness_profile',{p_game_code:gameCode||null,p_cooldown_days:cooldownDays});if(error)throw error;return data||{};}
export async function recordGameContentExposure(input:{gameCode:string;contentKey:string;topic?:string;mechanic?:string;locationId?:string|null;answerKey?:string|null;correct?:boolean|null;responseMs?:number;informationValue?:number;metadata?:any}){const{data,error}=await getKleenestSupabaseClient().rpc('record_game_content_exposure',{p_game_code:input.gameCode,p_content_key:input.contentKey,p_topic:input.topic||null,p_mechanic:input.mechanic||null,p_location_id:input.locationId||null,p_answer_key:input.answerKey||null,p_correct:input.correct??null,p_response_ms:Math.max(0,Math.round(input.responseMs||0)),p_information_value:Math.max(0,Number(input.informationValue||0)),p_metadata:input.metadata||{}});if(error)throw error;return data;}
export function freshRoundOrder<T extends {prompt:string;choices?:string[]}>(rows:T[],profile:any){const seen=new Set((profile?.recent_content_keys||[]).map(String));const answerSeen=new Set((profile?.recent_answer_keys||[]).map(String));const keyed=rows.map((row,index)=>{const contentKey=`${row.prompt}|${(row.choices||[]).join('|')}`.toLowerCase().replace(/\s+/g,' ').trim();const answerKey=(row.choices||[]).join('|').toLowerCase();return{row,index,contentKey,novelty:(seen.has(contentKey)?0:2)+(answerSeen.has(answerKey)?0:1)+Math.random()*.25}});keyed.sort((a,b)=>b.novelty-a.novelty);return keyed.map(x=>x.row);}
export async function recordGameResult(gameCode:string,score:number,durationMs:number,metadata:any={}){const{data,error}=await getKleenestSupabaseClient().rpc('record_game_result',{p_game_code:gameCode,p_score:Math.max(0,Math.round(score)),p_duration_ms:Math.max(0,Math.round(durationMs)),p_metadata:{...metadata,freshness_engine:'v1',intelligence_provenance:'game_center'}});if(error)throw error;return data;}
export async function listGameChallengeTargets(limit=30){const{data,error}=await getKleenestSupabaseClient().rpc('list_game_challenge_targets',{p_limit:Math.min(Math.max(limit,1),100)});if(error)throw error;return data||[];}
export async function listGameChallenges(status:string|null=null,limit=30){const{data,error}=await getKleenestSupabaseClient().rpc('list_game_challenges',{p_status:status,p_limit:Math.min(Math.max(limit,1),100)});if(error)throw error;return data||[];}
export async function createGameChallenge(gameCode:string,inviteeId:string){const{data,error}=await getKleenestSupabaseClient().rpc('create_game_challenge',{p_game_code:gameCode,p_invitee_id:inviteeId,p_metadata:{focus:'bathroom_trust',freshness_engine:'v1'}});if(error)throw error;return data;}
export async function respondGameChallenge(challengeId:string,accept:boolean){const{data,error}=await getKleenestSupabaseClient().rpc('respond_game_challenge',{p_challenge_id:challengeId,p_accept:accept});if(error)throw error;return data;}
export async function recordGameChallengeScore(challengeId:string,score:number,rounds:number){const{data,error}=await getKleenestSupabaseClient().rpc('record_game_challenge_score',{p_challenge_id:challengeId,p_score:Math.max(0,Math.round(score)),p_metadata:{rounds,focus:'bathroom_trust',freshness_engine:'v1'}});if(error)throw error;return data;}
