import * as SecureStore from 'expo-secure-store';
import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
const client=()=>getKleenestSupabaseClient();async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data;}
const WORKSPACE_KEY='kleenest.fleet.selected_workspace.v1';
export async function listFleetWorkspaceOptions(){const rows:any[]=(await rpc('business_list_workspaces',{p_include_demo:false}))||[];const checked=await Promise.all(rows.map(async row=>{const id=String(row.business_id||'');try{const allowed=Boolean(await rpc('business_fleet_authorized',{p_business_id:id}));return allowed?row:null}catch{return null}}));return checked.filter(Boolean) as any[];}
export async function selectFleetWorkspace(businessId:string){const rows=await listFleetWorkspaceOptions();if(!rows.some(row=>String(row.business_id)===businessId))throw new Error('That Fleet workspace is not enabled for this account.');await SecureStore.setItemAsync(WORKSPACE_KEY,businessId);return businessId;}
export async function currentFleetBusinessId(){const rows=await listFleetWorkspaceOptions();if(!rows.length)throw new Error('No Fleet-enabled Business workspace is available.');const preferred=await SecureStore.getItemAsync(WORKSPACE_KEY).catch(()=>null);const preferredRow=rows.find(row=>String(row.business_id)===preferred);if(preferredRow)return String(preferredRow.business_id);const scored=await Promise.all(rows.map(async row=>{const id=String(row.business_id||'');try{const access:any=await rpc('get_business_product_access',{p_business_id:id});const a=Array.isArray(access)?access[0]:access;return{row,score:Number(a?.location_count||0)*100+(a?.enterprise_enabled?30:0)+(row?.is_demo_test?0:5)}}catch{return{row,score:row?.is_demo_test?0:5}}}));scored.sort((a,b)=>b.score-a.score);const id=String(scored[0]?.row?.business_id||'');if(!id)throw new Error('No Fleet-enabled Business workspace is available.');await SecureStore.setItemAsync(WORKSPACE_KEY,id).catch(()=>{});return id;}
export async function getFleetInventory(businessId:string){const settled=await Promise.allSettled([client().from('fleet_vehicles').select('*').eq('business_id',businessId).order('created_at',{ascending:false}),client().from('fleet_drivers').select('*').eq('business_id',businessId).order('created_at',{ascending:false}),client().from('fleet_routes').select('*').eq('business_id',businessId).order('created_at',{ascending:false}),client().from('fleet_maintenance_records').select('*').eq('business_id',businessId).order('created_at',{ascending:false}),client().rpc('fleet_exception_alerts',{p_business_id:businessId,p_status:null,p_limit:100}),client().from('fleet_route_stops').select('*').eq('business_id',businessId).order('stop_order',{ascending:true})]);const value=(index:number)=>settled[index].status==='fulfilled'?(settled[index] as PromiseFulfilledResult<any>).value:null;const [vehicles,drivers,routes,maintenance,alerts,stops]=settled.map((_,index)=>value(index));for(const result of[vehicles,drivers,routes,maintenance,stops])if(!result||result.error)throw(result?.error||new Error('Fleet inventory request failed.'));const alertsWarning=!alerts||alerts.error?String(alerts?.error?.message||'Fleet exception alerts are temporarily unavailable.'):null;return{vehicles:vehicles.data||[],drivers:drivers.data||[],routes:routes.data||[],maintenance:maintenance.data||[],alerts:alerts?.data||[],stops:stops.data||[],alertsWarning};}
export async function getFleetAdvancedIntelligence(businessId:string){const calls=[rpc('fleet_operations_exception_intelligence',{p_business_id:businessId,p_window_hours:24}),rpc('fleet_restroom_preventive_schedule',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_remediation_risk',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_prevention_portfolio',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_prevention_effectiveness',{p_business_id:businessId,p_days:180}),rpc('fleet_asset_exception_scorecards',{p_business_id:businessId,p_window_days:30}),rpc('fleet_exception_trends',{p_business_id:businessId,p_window_days:30}),rpc('fleet_list_monitored_locations',{p_business_id:businessId}),rpc('fleet_service_opportunities_for_business',{p_business_id:businessId}),rpc('fleet_operational_signal_summary',{p_business_id:businessId,p_window_hours:24})];const settled=await Promise.allSettled(calls);const v=(i:number)=>settled[i].status==='fulfilled'?(settled[i] as PromiseFulfilledResult<any>).value:null;return{operations:v(0),prevention:v(1),remediationRisk:v(2),preventionPortfolio:v(3),preventionEffectiveness:v(4),assetScorecards:v(5),exceptionTrends:v(6),monitoredLocations:v(7),serviceOpportunities:v(8),operationalSignals:v(9),partial:settled.some(x=>x.status==='rejected')};}
export function listFleetPremiumMembers(businessId:string){return rpc('fleet_list_premium_members',{p_business_id:businessId});}
export function grantFleetPremiumByEmail(businessId:string,email:string){return rpc('fleet_grant_premium_member_by_email',{p_business_id:businessId,p_email:email.trim(),p_metadata:{source:'fleet-mobile'}});}
export function revokeFleetPremiumMember(businessId:string,userId:string){return rpc('fleet_revoke_premium_member',{p_business_id:businessId,p_user_id:userId});}
export function listMonitoredLocations(businessId:string){return rpc('fleet_list_monitored_locations',{p_business_id:businessId});}
export function setMonitoredLocation(businessId:string,locationId:string,enabled=true){return rpc('fleet_set_monitored_location',{p_business_id:businessId,p_location_id:locationId,p_enabled:enabled});}
export function removeMonitoredLocation(businessId:string,locationId:string){return rpc('fleet_remove_monitored_location',{p_business_id:businessId,p_location_id:locationId});}
export function getFleetProgression(businessId:string){return rpc('fleet_progression_snapshot',{p_business_id:businessId});}
export function getFleetLeaderboard(businessId:string,metric='score',targetType='driver',limit=25){return rpc('get_fleet_leaderboard',{p_business_id:businessId,p_metric:metric,p_target_type:targetType,p_limit:limit});}
export function getFleetNetworkLeaderboard(metric='score',limit=25){return rpc('get_fleet_network_leaderboard',{p_metric:metric,p_limit:limit});}
export function getFleetRoutePerformance(businessId:string,routeId:string){return rpc('fleet_route_performance',{p_business_id:businessId,p_route_id:routeId});}
export function getFleetRouteExceptions(businessId:string,routeId:string){return rpc('fleet_route_exception_drilldown',{p_business_id:businessId,p_route_id:routeId});}
export function getFleetRouteGeofences(businessId:string,routeId:string){return rpc('fleet_route_geofence_manifest',{p_business_id:businessId,p_route_id:routeId});}
export function getDispatchIntelligence(businessId:string,routeId:string,limit=20){return rpc('fleet_dispatch_intelligence',{p_business_id:businessId,p_route_id:routeId,p_limit:limit});}
export function attachPreventiveWorkToRoute(businessId:string,workOrderId:string,routeId:string){return rpc('fleet_attach_preventive_work_to_route',{p_business_id:businessId,p_work_order_id:workOrderId,p_route_id:routeId});}
export function setRouteStops(businessId:string,routeId:string,stops:unknown[]){return rpc('fleet_set_route_stops',{p_business_id:businessId,p_route_id:routeId,p_stops:stops});}
export function updateRoute(businessId:string,route:Record<string,any>){return rpc('fleet_update_route',{p_business_id:businessId,p_route_id:String(route.id||route.route_id),p_name:String(route.name||'Fleet route'),p_status:String(route.status||'planned'),p_vehicle_id:route.vehicle_id||null,p_driver_id:route.driver_id||null,p_scheduled_for:route.scheduled_for||null,p_distance_miles:route.distance_miles??null,p_estimated_minutes:route.estimated_minutes??null,p_stops_count:Number(route.stops_count??0),p_metadata:route.metadata||{source:'fleet-mobile'}});}
export async function getFleetCapabilityState(businessId:string){const[access,entitlement,observe,dispatchPolicy,exceptionPolicy]=await Promise.allSettled([rpc('get_business_product_access',{p_business_id:businessId}),rpc('get_business_service_entitlement',{p_business_id:businessId}),rpc('fleet_observe_access',{p_business_id:businessId}),rpc('fleet_dispatch_signal_policy',{p_business_id:businessId}),rpc('fleet_exception_policy',{p_business_id:businessId})]);const v=(x:PromiseSettledResult<any>)=>x.status==='fulfilled'?x.value:null;return{access:v(access),entitlement:v(entitlement),observe:v(observe),dispatchPolicy:v(dispatchPolicy),exceptionPolicy:v(exceptionPolicy),partial:[access,entitlement,observe,dispatchPolicy,exceptionPolicy].some(x=>x.status==='rejected')};}
