import { getKleenestSupabaseClient } from '@kleenest/mobile-core';

const client=()=>getKleenestSupabaseClient();
async function rpc<T=any>(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw new Error(`${name}: ${error.message}`);return data as T;}

export async function updateVehicle(businessId:string,vehicle:Record<string,any>){return rpc('fleet_update_vehicle',{p_business_id:businessId,p_vehicle_id:String(vehicle.id),p_name:vehicle.name??'Fleet vehicle',p_unit_code:vehicle.unit_code??null,p_vehicle_type:vehicle.vehicle_type??null,p_status:vehicle.status??'active',p_driver_name:vehicle.driver_name??null,p_current_lat:vehicle.current_lat??null,p_current_lng:vehicle.current_lng??null,p_odometer_miles:vehicle.odometer_miles??null,p_metadata:vehicle.metadata??{}});}
export async function deleteVehicle(businessId:string,vehicleId:string){return rpc('fleet_delete_vehicle',{p_business_id:businessId,p_vehicle_id:vehicleId});}
export async function updateDriver(businessId:string,driver:Record<string,any>){return rpc('fleet_update_driver',{p_business_id:businessId,p_driver_id:String(driver.id),p_name:driver.name??'Fleet driver',p_email:driver.email??null,p_phone:driver.phone??null,p_status:driver.status??'active',p_vehicle_id:driver.vehicle_id??null,p_metadata:driver.metadata??{}});}
export async function deleteDriver(businessId:string,driverId:string){return rpc('fleet_delete_driver',{p_business_id:businessId,p_driver_id:driverId});}
export async function assignDriverUser(businessId:string,driverId:string,userId:string){return rpc('fleet_assign_driver_user',{p_business_id:businessId,p_driver_id:driverId,p_user_id:userId});}
export async function listFleetAssignableMembers(businessId:string){const{data,error}=await client().from('business_members').select('id,user_id,role,created_at').eq('business_id',businessId).order('created_at',{ascending:true});if(error)throw error;return data||[];}
export async function updateRoute(businessId:string,route:Record<string,any>){return rpc('fleet_update_route',{p_business_id:businessId,p_route_id:String(route.id||route.route_id),p_name:route.name??'Fleet route',p_status:route.status??'planned',p_vehicle_id:route.vehicle_id??null,p_driver_id:route.driver_id??null,p_scheduled_for:route.scheduled_for??null,p_distance_miles:route.distance_miles??null,p_estimated_minutes:route.estimated_minutes??null,p_stops_count:route.stops_count??0,p_metadata:route.metadata??{}});}
export async function deleteRoute(businessId:string,routeId:string){return rpc('fleet_delete_route',{p_business_id:businessId,p_route_id:routeId});}
export async function getRoutePerformance(businessId:string,routeId:string){return rpc('fleet_route_performance',{p_business_id:businessId,p_route_id:routeId});}
export async function getRouteExceptionDetail(businessId:string,routeId:string){return rpc('fleet_route_exception_drilldown',{p_business_id:businessId,p_route_id:routeId});}
export async function updateMaintenance(businessId:string,row:Record<string,any>){return rpc('fleet_update_maintenance',{p_business_id:businessId,p_maintenance_id:String(row.id),p_vehicle_id:row.vehicle_id??null,p_maintenance_type:row.maintenance_type??'inspection',p_status:row.status??'scheduled',p_scheduled_at:row.scheduled_at??null,p_completed_at:row.completed_at??null,p_odometer_miles:row.odometer_miles??null,p_cost:row.cost??null,p_vendor:row.vendor??null,p_notes:row.notes??null,p_metadata:row.metadata??{}});}
export async function deleteMaintenance(businessId:string,maintenanceId:string){return rpc('fleet_delete_maintenance',{p_business_id:businessId,p_maintenance_id:maintenanceId});}
export async function recordOperationalEvent(businessId:string,eventType:string,payload:Record<string,unknown>={}){return rpc('record_fleet_operational_event',{p_business_id:businessId,p_event_type:eventType,p_payload:payload});}

export async function getFleetMetricCapabilities(businessId:string){return rpc('get_fleet_metric_capabilities',{p_business_id:businessId});}
export async function getFleetMetricConfiguration(businessId:string){return rpc('get_fleet_metric_configuration',{p_business_id:businessId});}
export async function getFleetMetricValues(businessId:string,asOf=new Date().toISOString().slice(0,10)){return rpc('get_fleet_metric_values',{p_business_id:businessId,p_as_of:asOf});}
export async function createFleetMetricDefinition(businessId:string,i:{metricKey:string;featureCode:string;name:string;description?:string;unit?:string;sourceDataset:string;sourceMetric:string;aggregation?:string;direction?:string;scoringMethod?:string;goal?:number|null;threshold?:number|null;maxScore?:number|null;scoringConfig?:Record<string,unknown>;period?:string}){return rpc('create_fleet_metric_definition',{p_business_id:businessId,p_metric_key:i.metricKey,p_feature_code:i.featureCode,p_name:i.name,p_description:i.description??null,p_unit:i.unit??'count',p_source_dataset:i.sourceDataset,p_source_metric:i.sourceMetric,p_aggregation:i.aggregation??'sum',p_direction:i.direction??'higher_is_better',p_scoring_method:i.scoringMethod??'linear',p_goal:i.goal??null,p_threshold:i.threshold??null,p_max_score:i.maxScore??100,p_scoring_config:i.scoringConfig??{},p_period:i.period??'daily'});}
export async function updateFleetMetricDefinition(id:string,i:{name?:string|null;description?:string|null;goal?:number|null;threshold?:number|null;maxScore?:number|null;scoringMethod?:string|null;scoringConfig?:Record<string,unknown>;period?:string|null;active?:boolean}){return rpc('update_fleet_metric_definition',{p_metric_definition_id:id,p_name:i.name??null,p_description:i.description??null,p_goal:i.goal??null,p_threshold:i.threshold??null,p_max_score:i.maxScore??null,p_scoring_method:i.scoringMethod??null,p_scoring_config:i.scoringConfig??{},p_period:i.period??null,p_active:i.active??true});}
export async function assignFleetMetric(id:string,targetType:string,targetId:string){return rpc('assign_fleet_metric',{p_metric_definition_id:id,p_target_type:targetType,p_target_id:targetId});}
