import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
const client=()=>getKleenestSupabaseClient();
async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data;}
export async function listFleetWorkspaces(){return (await rpc('business_list_workspaces',{p_include_demo:false}))||[];}
export async function getFleetDashboard(businessId:string){const [authorized,dispatch,summary,signals,exceptions,risk,portfolio,schedule,effectiveness,opportunities]=await Promise.all([rpc('business_fleet_authorized',{p_business_id:businessId}),rpc('fleet_current_user_dispatch',{p_business_id:businessId}),rpc('fleet_dashboard_summary_v2',{p_business_id:businessId}),rpc('fleet_operational_signal_summary',{p_business_id:businessId,p_window_hours:24}),rpc('fleet_operations_exception_intelligence',{p_business_id:businessId,p_window_hours:24}),rpc('fleet_restroom_remediation_risk',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_prevention_portfolio',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_preventive_schedule',{p_business_id:businessId,p_days:90}),rpc('fleet_restroom_prevention_effectiveness',{p_business_id:businessId,p_days:180}),rpc('fleet_preventive_dispatch_opportunities',{p_business_id:businessId})]);if(!authorized)throw new Error('Fleet access is not enabled for this business.');return{dispatch,summary,signals,exceptions,risk,portfolio,schedule,effectiveness,opportunities};}
export async function recordRouteStopTiming(businessId:string,routeId:string,routeStopId:string,eventType:'arrived'|'service_started'|'completed'|'departed'|'skipped'){return rpc('fleet_record_route_stop_timing',{p_business_id:businessId,p_route_id:routeId,p_route_stop_id:routeStopId,p_event_type:eventType,p_occurred_at:new Date().toISOString()});}
export async function dispatchRoute(businessId:string,routeId:string){return rpc('fleet_dispatch_route',{p_business_id:businessId,p_route_id:routeId});}
export async function resolveAlert(businessId:string,alertId:string,note=''){return rpc('fleet_resolve_alert',{p_business_id:businessId,p_alert_id:alertId,p_resolution_note:note});}
export const FLEET_PARITY=['workspace-selection','dispatch','routes','route-stop-timing','drivers','vehicles','maintenance','alerts','operational-signals','exceptions','remediation-risk','prevention-portfolio','preventive-schedule','prevention-effectiveness','preventive-dispatch','notifications','offline-recovery','support','privacy','account-control'];
