import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PMTiles } from "https://esm.sh/pmtiles@4.3.0";
import { VectorTile } from "https://esm.sh/@mapbox/vector-tile@2.0.4";
import Pbf from "https://esm.sh/pbf@4.0.1";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,KEY,{auth:{persistSession:false}});
const H={"content-type":"application/json"};
const endpoints=["https://overpass.private.coffee/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass-api.de/api/interpreter"];
const now=()=>new Date().toISOString();
async function guard(req:Request){const supplied=req.headers.get("x-kleenest-scheduler")||"";const r=await db.rpc("get_internal_scheduler_secret",{p_name:"kleenest_maps_scheduler"});if(!supplied||r.error||!r.data||supplied!==r.data)throw Error("Invalid scheduler authentication")}
function type(t:any){if(t.amenity==="toilets")return"restroom";if(t.amenity==="fuel")return"gas_station";if(["restaurant","fast_food"].includes(t.amenity))return"restaurant";if(t.amenity==="cafe")return"cafe";if(t.shop)return"retail";if(t.tourism)return"lodging";if(t.leisure)return"park";if(["hospital","clinic","doctors","pharmacy"].includes(t.amenity))return"health";return"service";}
function rows(es:any[]){const m=new Map();for(const e of es){const t=e.tags||{},lat=Number(e.lat??e.center?.lat),lng=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;const pt=type(t),id=`osm:${e.type}:${e.id}`;m.set(id,{source_id:id,latitude:lat,longitude:lng,name:t.name||t.brand||t.operator||(pt==="restroom"?"Public Restroom":`Unnamed ${pt}`),place_type:pt,address:[t["addr:housenumber"],t["addr:street"]].filter(Boolean).join(" ")||t["addr:full"]||null,city:t["addr:city"]||null,state:t["addr:state"]||null,postal_code:t["addr:postcode"]||null,brand:t.brand||null,source_metadata:{provider:"overpass",tags:t,captured_at:now(),discovery_lane:"consumer_on_demand"}})}return[...m.values()];}
const OVERTURE_PM="https://overturemaps-extras-us-west-2.s3.us-west-2.amazonaws.com/tiles/2026-09-23.1/places.pmtiles";
const pm=new PMTiles(OVERTURE_PM);
function tileXY(lat:number,lng:number,z:number){const n=2**z,x=Math.floor((lng+180)/360*n),r=lat*Math.PI/180,y=Math.floor((1-Math.asinh(Math.tan(r))/Math.PI)/2*n);return{x,y}}
async function fetchRows(q:any){const z=14,{x,y}=tileXY(Number(q.latitude),Number(q.longitude),z);const got=await pm.getZxy(z,x,y);if(!got?.data)return[];const vt=new VectorTile(new Pbf(got.data));const layer=vt.layers.place;if(!layer)return[];const out:any[]=[];for(let i=0;i<layer.length&&out.length<250;i++){const f=layer.feature(i),gj=f.toGeoJSON(x,y,z),p:any=f.properties||{},coords:any=gj.geometry?.coordinates;if(!Array.isArray(coords)||coords.length<2)continue;const name=String(p["@name"]??p["names.primary"]??p.name??"").trim();if(!name)continue;const cat=String(p["@category"]??p["taxonomy.primary"]??p.basic_category??"service");out.push({source_id:String(p.id??`tile:${z}:${x}:${y}:${i}`),latitude:Number(coords[1]),longitude:Number(coords[0]),name,place_type:/restaurant|food/.test(cat)?"restaurant":/cafe|coffee/.test(cat)?"cafe":/fuel|gas/.test(cat)?"gas_station":/hotel|lodging|motel/.test(cat)?"lodging":/shop|retail|market|store/.test(cat)?"retail":/toilet|restroom/.test(cat)?"restroom":"service",address:p["addresses.0.freeform"]??p.address??null,city:p["addresses.0.locality"]??null,state:p["addresses.0.region"]??null,postal_code:p["addresses.0.postcode"]??null,brand:p["brand.names.primary"]??null,source_metadata:{provider:"overture_pmtiles",release:"2026-09-23.1",taxonomy:cat,confidence:p.confidence??null,tile:{z,x,y},captured_at:now(),discovery_lane:"consumer_on_demand"}})}return out}
async function persist(all:any[]){let imported=0,updated=0,skipped=0;for(let i=0;i<all.length;i+=5){const r=await db.rpc("ingest_external_locations",{p_source_key:"overture",p_rows:all.slice(i,i+5)});if(r.error)throw r.error;imported+=Number(r.data?.imported_locations||0);updated+=Number(r.data?.updated_locations||0);skipped+=Number(r.data?.skipped_rows||0)}return{imported,updated,skipped}}
Deno.serve(async(req)=>{let q:any=null;try{await guard(req);await db.from("place_discovery_hydration_queue").update({status:"pending",started_at:null,last_error:"recovered stale consumer hydration",updated_at:now()}).like("request_key","consumer:%").eq("status","running").lt("started_at",new Date(Date.now()-90000).toISOString());const claim=await db.from("place_discovery_hydration_queue").select("*").eq("status","pending").like("request_key","consumer:%").order("priority").order("requested_at",{ascending:false}).limit(1).maybeSingle();if(claim.error)throw claim.error;if(!claim.data)return new Response(JSON.stringify({ok:true,status:"idle"}),{headers:H});q=claim.data;const started=await db.from("place_discovery_hydration_queue").update({status:"running",started_at:now(),attempt_count:Number(q.attempt_count||0)+1,last_error:null,updated_at:now()}).eq("id",q.id).eq("status","pending").select("id").maybeSingle();if(started.error)throw started.error;if(!started.data)return new Response(JSON.stringify({ok:true,status:"claim_lost"}),{headers:H});const all=await fetchRows(q);const saved=await persist(all);await db.from("place_discovery_hydration_queue").update({status:"completed",records_seen:all.length,records_imported:saved.imported,records_updated:saved.updated,skipped_rows:saved.skipped,completed_at:now(),last_error:null,updated_at:now()}).eq("id",q.id);return new Response(JSON.stringify({ok:true,request_id:q.id,seen:all.length,...saved}),{headers:H})}catch(e){const message=e instanceof Error?e.message:String(e);if(q?.id)await db.from("place_discovery_hydration_queue").update({status:Number(q.attempt_count||0)+1>=3?"failed":"pending",last_error:message,started_at:null,updated_at:now()}).eq("id",q.id);return new Response(JSON.stringify({ok:false,error:message}),{status:500,headers:H})}});