// Consumer UI release trigger: canonical Explore interactions are source-controlled.
import type { ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useConsumerTheme } from '../services/theme';

export const palette={ink:'#102218',green:'#173d2b',green2:'#24553d',mint:'#e7f1ea',mint2:'#d7e8dc',paper:'#ffffff',canvas:'#f3f6f4',muted:'#5f7166',line:'#d7e2da',gold:'#986c20'};
const actionHitSlop={top:8,right:8,bottom:8,left:8};

export function Eyebrow({children}:{children:ReactNode}){const theme=useConsumerTheme();return <Text accessibilityRole="text" style={[s.eyebrow,{color:theme.muted}]}>{children}</Text>}
export function ScreenIntro({eyebrow,title,body,aside}:{eyebrow:string;title:string;body?:string;aside?:ReactNode}){const theme=useConsumerTheme();return <View style={s.intro}><View style={{flex:1}}><Eyebrow>{eyebrow}</Eyebrow><Text accessibilityRole="header" style={[s.title,{color:theme.ink}]}>{title}</Text>{body?<Text style={[s.body,{color:theme.muted}]}>{body}</Text>:null}</View>{aside}</View>}
export function SectionHeader({eyebrow,title,body,action}:{eyebrow?:string;title:string;body?:string;action?:ReactNode}){const theme=useConsumerTheme();return <View style={s.sectionHead}><View style={{flex:1}}>{eyebrow?<Eyebrow>{eyebrow}</Eyebrow>:null}<Text accessibilityRole="header" style={[s.sectionTitle,{color:theme.ink}]}>{title}</Text>{body?<Text style={[s.sectionBody,{color:theme.muted}]}>{body}</Text>:null}</View>{action}</View>}
export function HeroCard({eyebrow,title,body,children}:{eyebrow?:string;title:string;body?:string;children?:ReactNode}){const theme=useConsumerTheme();return <View accessible accessibilityLabel={[title,body].filter(Boolean).join('. ')} style={[s.hero,{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:palette.green,borderWidth:1,borderColor:theme.resolved==='dark'?theme.line:palette.green}]}>{eyebrow?<Text style={s.heroEyebrow}>{eyebrow}</Text>:null}<Text accessibilityRole="header" style={s.heroTitle}>{title}</Text>{body?<Text style={s.heroBody}>{body}</Text>:null}{children}</View>}
export function FeatureCard({title,body,kicker,children,onPress}:{title:string;body?:string;kicker?:string;children?:ReactNode;onPress?:()=>void}){const theme=useConsumerTheme();const content=<><View style={s.featureTop}>{kicker?<Text style={[s.kicker,{color:theme.accent}]}>{kicker}</Text>:null}<Text accessibilityElementsHidden importantForAccessibility="no" style={[s.chevron,{color:theme.accent}]}>{onPress?'›':''}</Text></View><Text style={[s.featureTitle,{color:theme.ink}]}>{title}</Text>{body?<Text style={[s.featureBody,{color:theme.muted}]}>{body}</Text>:null}{children}</>;return onPress?<Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityHint={body} hitSlop={actionHitSlop} onPress={onPress} style={({pressed})=>[s.feature,{backgroundColor:theme.surface,borderColor:theme.line},s.touchTarget,pressed&&s.pressed]}>{content}</Pressable>:<View accessible accessibilityLabel={[title,body].filter(Boolean).join('. ')} style={[s.feature,{backgroundColor:theme.surface,borderColor:theme.line}]}>{content}</View>}
export function MetricTile({value,label,detail}:{value:ReactNode;label:string;detail?:string}){const theme=useConsumerTheme();return <View accessible accessibilityLabel={`${label}: ${String(value)}${detail?`. ${detail}`:''}`} style={[s.metric,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.accent}]}>{value}</Text><Text style={[s.metricLabel,{color:theme.muted}]}>{label}</Text>{detail?<Text style={[s.metricDetail,{color:theme.muted}]}>{detail}</Text>:null}</View>}
export function PrimaryAction({label,onPress}:{label:string;onPress:()=>void}){const theme=useConsumerTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label} hitSlop={actionHitSlop} onPress={onPress} style={({pressed})=>[s.primary,{backgroundColor:theme.accent},s.touchTarget,pressed&&s.pressed]}><Text style={[s.primaryText,{color:theme.accentText}]}>{label}</Text></Pressable>}
export function SecondaryAction({label,onPress}:{label:string;onPress:()=>void}){const theme=useConsumerTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label} hitSlop={actionHitSlop} onPress={onPress} style={({pressed})=>[s.secondary,{backgroundColor:theme.accentSoft},s.touchTarget,pressed&&s.pressed]}><Text style={[s.secondaryText,{color:theme.accent}]}>{label}</Text></Pressable>}
export function TrustStrip({items}:{items:string[]}){return <View accessibilityRole="summary" accessibilityLabel={items.join(', ')} style={s.strip}>{items.map(item=><View style={s.stripItem} key={item}><Text style={s.stripDot}>•</Text><Text style={s.stripText}>{item}</Text></View>)}</View>}

const s=StyleSheet.create({
  eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#557060'},intro:{flexDirection:'row',gap:12,alignItems:'flex-start'},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:palette.ink,marginTop:5},body:{fontSize:15,lineHeight:22,color:palette.muted,marginTop:7},
  sectionHead:{flexDirection:'row',alignItems:'flex-end',gap:10,marginTop:8},sectionTitle:{fontSize:23,lineHeight:27,fontWeight:'900',color:palette.ink,marginTop:4},sectionBody:{fontSize:13,lineHeight:19,color:palette.muted,marginTop:4},
  hero:{backgroundColor:palette.green,padding:20,borderRadius:24,gap:7,shadowColor:'#000',shadowOpacity:.08,shadowRadius:14,shadowOffset:{width:0,height:6},elevation:3},heroEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#bcd4c5'},heroTitle:{fontSize:27,lineHeight:31,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},
  feature:{backgroundColor:'#fff',padding:16,borderRadius:19,borderWidth:1,borderColor:palette.line,gap:5,shadowColor:'#000',shadowOpacity:.025,shadowRadius:8,shadowOffset:{width:0,height:3},elevation:1},featureTop:{minHeight:17,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1,color:palette.green2},chevron:{fontSize:25,lineHeight:20,fontWeight:'700',color:palette.green},featureTitle:{fontSize:17,fontWeight:'900',color:palette.ink},featureBody:{fontSize:13,lineHeight:19,color:palette.muted},
  metric:{flex:1,minWidth:96,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:palette.line},metricValue:{fontSize:20,fontWeight:'900',color:palette.green},metricLabel:{fontSize:10,fontWeight:'900',color:palette.muted,marginTop:2},metricDetail:{fontSize:9,color:'#829087',marginTop:3},
  touchTarget:{minHeight:48},primary:{backgroundColor:palette.green,paddingHorizontal:15,paddingVertical:12,borderRadius:13,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:12,fontWeight:'900'},secondary:{backgroundColor:palette.mint,paddingHorizontal:15,paddingVertical:12,borderRadius:13,alignItems:'center',justifyContent:'center'},secondaryText:{color:palette.green,fontSize:12,fontWeight:'900'},pressed:{opacity:.72,transform:[{scale:.99}]},
  strip:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:6},stripItem:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:'#2a513d',paddingHorizontal:9,paddingVertical:6,borderRadius:999},stripDot:{color:'#c7e0d0',fontSize:12},stripText:{color:'#eef6f1',fontWeight:'800',fontSize:9},
});