import { getLocationRecoveryHistory,type LocationRecoveryHistoryItem } from '../services/recoveryHistory';
import { useEffect,useState } from 'react';
import { Image,StyleSheet,Text,View } from 'react-native';

function when(value:string|null){if(!value)return'—';const time=new Date(value).getTime();if(!Number.isFinite(time))return'—';const hours=Math.max(0,Math.floor((Date.now()-time)/3600000));if(hours<1)return'within the hour';if(hours<24)return`${hours}h ago`;const days=Math.floor(hours/24);return days===1?'yesterday':`${days}d ago`;}
function responseTitle(item:LocationRecoveryHistoryItem){if(item.response_status==='business_alerted')return'Business alerted';if(item.response_status==='business_addressing')return'Business addressing';if(item.resolution_method==='community_confirmation')return'Recovered by fresh community evidence';if(item.response_status==='addressed')return'Business reported fix';return String(item.response_status||'Recovery update').replaceAll('_',' ')}
function responseBody(item:LocationRecoveryHistoryItem){if(item.response_status==='business_alerted')return'Community evidence opened an operational response for this amenity.';if(item.response_status==='business_addressing')return'The business has assigned or started remediation work.';if(item.resolution_method==='community_confirmation')return'Newer strong canonical evidence independently confirmed this amenity recovered.';return`A canonical remediation observation closed this issue${item.proof_available?' with linked photo proof':''}${item.sla_met===true?' within the business SLA':item.sla_met===false?' after the business SLA':''}.`;}

export default function LocationRecoveryHistory({locationId,refreshToken=0}:{locationId:string;refreshToken?:number}){
  const[rows,setRows]=useState<LocationRecoveryHistoryItem[]>([]);const[message,setMessage]=useState('');
  useEffect(()=>{if(!locationId)return;let active=true;getLocationRecoveryHistory(locationId).then(data=>{if(active){setRows(data);setMessage('')}}).catch(error=>{if(active)setMessage(error?.message||'Recovery history could not be loaded.')});return()=>{active=false}},[locationId,refreshToken]);
  if(!rows.length&&!message)return null;
  return <View style={s.section}><Text style={s.eyebrow}>RECOVERY HISTORY</Text><Text style={s.title}>How reported issues were handled</Text><Text style={s.body}>This timeline preserves the original community signal, business response, proof, and independent recovery evidence instead of replacing older reports.</Text>{rows.slice(0,8).map(item=><View style={s.event} key={item.case_id}><View style={s.dot}/><View style={s.eventBody}><Text style={s.eventTitle}>{item.amenity_name} · {responseTitle(item)}</Text><Text style={s.eventText}>{responseBody(item)}</Text><Text style={s.meta}>Reported {when(item.source_observed_at||item.opened_at)}{item.resolved_at?` · Resolved ${when(item.resolved_at)}`:''} · {item.priority_band} priority</Text>{item.proof_url?<View style={s.proof}><Image source={{uri:item.proof_url}} style={s.proofImage}/><View style={{flex:1}}><Text style={s.proofTitle}>VERIFIED RECOVERY PROOF</Text><Text style={s.proofText}>Business remediation photo linked to the same canonical recovery event.</Text></View></View>:null}</View></View>)}{message?<Text style={s.message}>{message}</Text>:null}</View>;
}

const s=StyleSheet.create({section:{gap:9,marginTop:8},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:18,fontWeight:'900',color:'#14231b'},body:{fontSize:13,lineHeight:19,color:'#65756b'},event:{flexDirection:'row',gap:10,backgroundColor:'#f7faf8',borderWidth:1,borderColor:'#dde7e0',borderRadius:14,padding:12},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#173d2b',marginTop:5},eventBody:{flex:1,gap:3},eventTitle:{fontSize:13,fontWeight:'900',color:'#173d2b',textTransform:'capitalize'},eventText:{fontSize:12,lineHeight:18,color:'#53645a'},meta:{fontSize:10,lineHeight:15,color:'#7a8b81',fontWeight:'700'},proof:{flexDirection:'row',gap:9,alignItems:'center',backgroundColor:'#eaf3ed',borderRadius:11,padding:8,marginTop:4},proofImage:{width:64,height:48,borderRadius:8,backgroundColor:'#dce8df'},proofTitle:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#173d2b'},proofText:{fontSize:10,lineHeight:14,color:'#4d6658',fontWeight:'700',marginTop:2},message:{fontSize:12,color:'#53645a',fontWeight:'700'}});
