import { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View, type ViewStyle } from 'react-native';
import { palette } from './ConsumerUI';
import { useConsumerTheme } from '../services/theme';

type Row=Record<string,any>;
type Signal={icon:string;label:string};
type BrandIdentity=Signal&{domain?:string};

const placeSignals:Record<string,Signal>={shopping:{icon:'🛍',label:'Shopping'},restaurant:{icon:'🍴',label:'Restaurant'},service:{icon:'🏢',label:'Service'},park:{icon:'🌳',label:'Park'},cafe:{icon:'☕',label:'Cafe'},restroom:{icon:'🚻',label:'Public restroom'},health:{icon:'🏥',label:'Health'},gas_station:{icon:'⛽',label:'Fuel / travel stop'},public_safety:{icon:'🛡',label:'Public safety'},library:{icon:'📚',label:'Library'},library_dropoff:{icon:'📚',label:'Library'},dog_park:{icon:'🐾',label:'Dog park'},government:{icon:'🏛',label:'Government'},brand:{icon:'🏢',label:'Business'}};
const brandSignals:[RegExp,BrandIdentity][]=[
[/\bstarbucks\b/i,{icon:'☕',label:'Starbucks',domain:'starbucks.com'}],[/\bmcdonald'?s\b/i,{icon:'Ⓜ',label:"McDonald's",domain:'mcdonalds.com'}],[/\bwalmart\b/i,{icon:'✳',label:'Walmart',domain:'walmart.com'}],[/\btaco bell\b/i,{icon:'🔔',label:'Taco Bell',domain:'tacobell.com'}],[/\bjack in the box\b/i,{icon:'J',label:'Jack in the Box',domain:'jackinthebox.com'}],[/\bmercy\b/i,{icon:'M',label:'Mercy',domain:'mercy.net'}],[/\btarget\b/i,{icon:'◎',label:'Target',domain:'target.com'}],[/\bcostco\b/i,{icon:'Ⓒ',label:'Costco',domain:'costco.com'}],[/\bsam'?s club\b/i,{icon:'S',label:"Sam's Club",domain:'samsclub.com'}],[/\bwalgreens\b/i,{icon:'ⓦ',label:'Walgreens',domain:'walgreens.com'}],[/\bcvs\b/i,{icon:'✚',label:'CVS',domain:'cvs.com'}],[/\blove'?s\b/i,{icon:'♥',label:"Love's",domain:'loves.com'}],[/\bpilot\b/i,{icon:'Ⓟ',label:'Pilot',domain:'pilotflyingj.com'}],[/\bflying j\b/i,{icon:'Ⓙ',label:'Flying J',domain:'pilotflyingj.com'}],[/\bquiktrip\b|\bqt\b/i,{icon:'Ⓠ',label:'QuikTrip',domain:'quiktrip.com'}],[/\b7-?eleven\b/i,{icon:'7',label:'7-Eleven',domain:'7-eleven.com'}],[/\bspeedway\b/i,{icon:'S',label:'Speedway',domain:'speedway.com'}],[/\bcasey'?s\b/i,{icon:'C',label:"Casey's",domain:'caseys.com'}],[/\bu-?haul\b/i,{icon:'Ⓤ',label:'U-Haul',domain:'uhaul.com'}],[/\bhome depot\b/i,{icon:'Ⓗ',label:'Home Depot',domain:'homedepot.com'}],[/\blowe'?s\b/i,{icon:'Ⓛ',label:"Lowe's",domain:'lowes.com'}],[/\bkroger\b/i,{icon:'Ⓚ',label:'Kroger',domain:'kroger.com'}],[/\baldi\b/i,{icon:'Ⓐ',label:'ALDI',domain:'aldi.us'}],[/\bwhole foods\b/i,{icon:'W',label:'Whole Foods',domain:'wholefoodsmarket.com'}],[/\btrader joe'?s\b/i,{icon:'T',label:"Trader Joe's",domain:'traderjoes.com'}],[/\bshell\b/i,{icon:'⛽',label:'Shell',domain:'shell.com'}],[/\bwendy'?s\b/i,{icon:'W',label:"Wendy's",domain:'wendys.com'}],[/\bburger king\b/i,{icon:'BK',label:'Burger King',domain:'bk.com'}],[/\bsubway\b/i,{icon:'S',label:'Subway',domain:'subway.com'}],[/\bchick-fil-a\b/i,{icon:'C',label:'Chick-fil-A',domain:'chick-fil-a.com'}],[/\bdunkin'?\b/i,{icon:'D',label:'Dunkin',domain:'dunkindonuts.com'}],[/\bsonic\b/i,{icon:'S',label:'Sonic',domain:'sonicdrivein.com'}],[/\bpopeyes\b/i,{icon:'P',label:'Popeyes',domain:'popeyes.com'}],[/\bchipotle\b/i,{icon:'C',label:'Chipotle',domain:'chipotle.com'}],[/\bpanera\b/i,{icon:'P',label:'Panera',domain:'panerabread.com'}],[/\bkfc\b|\bkentucky fried chicken\b/i,{icon:'K',label:'KFC',domain:'kfc.com'}],[/\barby'?s\b/i,{icon:'A',label:"Arby's",domain:'arbys.com'}],[/\b(bp|exxon|mobil|chevron|circle k)\b/i,{icon:'⛽',label:'Fuel stop'}]
];
const businessLikeTypes=new Set(['shopping','restaurant','service','cafe','health','gas_station','brand']);
function restroomCandidateStatus(item:Row){return String(item?.restroom_candidate_status||'').trim().toLowerCase()}
function networkState(item:Row){return String(item?.network?.network_state||item?.network_state||'unknown').trim().toLowerCase()}
const HEAT_STOPS=[
  {day:0,color:'#ef4444'},
  {day:1,color:'#f97316'},
  {day:7,color:'#facc15'},
  {day:30,color:'#84cc16'},
  {day:90,color:'#06b6d4'},
  {day:180,color:'#3b82f6'},
] as const;
function hexRgb(hex:string){const value=hex.replace('#','');return [0,2,4].map(index=>parseInt(value.slice(index,index+2),16))}
function rgbHex(rgb:number[]){return '#'+rgb.map(value=>Math.max(0,Math.min(255,Math.round(value))).toString(16).padStart(2,'0')).join('')}
function heatColor(ageDays:number){const age=Math.max(0,ageDays);for(let index=0;index<HEAT_STOPS.length-1;index++){const from=HEAT_STOPS[index],to=HEAT_STOPS[index+1];if(age<=to.day){const span=Math.max(1,to.day-from.day),t=Math.max(0,Math.min(1,(age-from.day)/span));const a=hexRgb(from.color),b=hexRgb(to.color);return rgbHex(a.map((value,i)=>value+(b[i]-value)*t))}}return HEAT_STOPS[HEAT_STOPS.length-1].color}
export function freshestEvidenceAt(item:Row){const values=[item?.network?.latest_evidence_at,item?.latest_evidence_at,item?.trust?.latest_verified_at,item?.latest_verified_at,item?.trust?.latest_amenity_observed_at,item?.latest_amenity_observed_at,item?.consumer_photo_created_at].map(value=>value?new Date(value).getTime():NaN).filter((value:number)=>Number.isFinite(value));return values.length?Math.max(...values):null}
export function freshnessHeatSignal(item:Row){const timestamp=freshestEvidenceAt(item);if(timestamp==null)return{color:'#94a3b8',label:'Freshness unknown',ageDays:null as number|null};const ageDays=Math.max(0,(Date.now()-timestamp)/86400000);const label=ageDays<1?'Hot freshness · <24h':ageDays<=3?'Very fresh · 1–3d':ageDays<=7?'Fresh · <7d':ageDays<=30?'Recent · <30d':ageDays<=90?'Cooling · 1–3mo':'Stale · 3mo+';return{color:heatColor(ageDays),label,ageDays}}
export function isKleenestNetworkVerified(item:Row){return Boolean(item?.network?.network_verified??item?.network_verified)||networkState(item)==='network_verified'}
export function isBusinessClaimed(item:Row){return Boolean(item?.network?.business_claimed??item?.business_claimed)||networkState(item)==='claimed'}
export function needsRestroomVerification(item:Row){return restroomCandidateStatus(item)==='needs_verification'||item?.needs_restroom_verification===true}
export function hasRestroomEvidence(item:Row){return restroomCandidateStatus(item)==='restroom_evidence'}
export function isVerifiedRestroom(item:Row){if(needsRestroomVerification(item))return false;return Boolean(item?.is_verified||String(item?.verification_status||'').toLowerCase()==='verified'||String(item?.bathroom_verification_status||'').toLowerCase()==='verified')}
function identityText(item:Row){return [item?.business_name,item?.business?.name,item?.brand,item?.operator_name,item?.name].filter(Boolean).join(' ')}
function brandIdentity(item:Row):BrandIdentity|null{const identity=identityText(item);for(const [pattern,signal] of brandSignals)if(pattern.test(identity))return signal;return null}
export function placeSignal(item:Row):Signal{return brandIdentity(item)||placeSignals[String(item?.place_type||item?.category||'').toLowerCase()]||{icon:'🚻',label:'Restroom location'}}
export function restroomMarkerGlyph(item:Row){return placeSignal(item).icon}
export function restroomMarkerLabel(item:Row){const place=placeSignal(item),state=networkState(item),freshness=freshnessHeatSignal(item);const extras=[freshness.label,isKleenestNetworkVerified(item)?'verified by the Kleenest Network':state==='building'?'community evidence building':needsRestroomVerification(item)?'possible restroom, needs evidence':hasRestroomEvidence(item)?'restroom evidence':null,isBusinessClaimed(item)?'claimed business':null,!isKleenestNetworkVerified(item)&&isVerifiedRestroom(item)?'verified restroom':null,Boolean(item?.accessible)?'accessible':null,Boolean(item?.changing_table)?'family feature':null].filter(Boolean).join(', ');return extras?`${place.label}, ${extras}`:place.label}
function explicitBusinessName(item:Row){const value=String(item?.business_name||item?.business?.name||item?.brand||item?.operator_name||'').trim();return /^(unknown|unassigned|uncategorized|n\/?a|none|null|business)$/i.test(value)?'':value}
function displayBusinessName(item:Row){const explicit=explicitBusinessName(item);if(explicit)return explicit;const brand=brandIdentity(item);if(brand)return brand.label;const kind=String(item?.place_type||item?.category||'').toLowerCase();return businessLikeTypes.has(kind)?String(item?.name||'').trim():''}
function initials(name:string){return name.replace(/[^a-z0-9'& -]/gi,' ').trim().split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase()}
function websiteDomain(item:Row){const raw=String(item?.business?.website||item?.website||'').trim();if(!raw)return '';try{return new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`).hostname.replace(/^www\./i,'')}catch{return ''}}
function favicon(domain:string){return domain?`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128`:''}
function brandLogoUrl(item:Row){const brand=brandIdentity(item);return favicon(brand?.domain||websiteDomain(item))}
function needsCommunityEvidence(item:Row){return !isBusinessClaimed(item)&&!isKleenestNetworkVerified(item)&&(Boolean(item?.network)||Boolean(item?.network_state))&&networkState(item)!=='claimed'}
export function PlaceIcon({item,size=24,evidenceFrame=true}:{item:Row;size?:number;evidenceFrame?:boolean}){const theme=useConsumerTheme();const[imageFailed,setImageFailed]=useState(false);const brand=brandIdentity(item);const businessName=displayBusinessName(item);const signal=placeSignal(item);const networkVerified=isKleenestNetworkVerified(item),claimed=isBusinessClaimed(item),needsEvidence=needsCommunityEvidence(item);if(networkVerified&&!claimed)return <View accessibilityLabel="Verified by the Kleenest Network" style={{width:size,height:size,borderRadius:size/2,backgroundColor:theme.accent,borderWidth:2,borderColor:theme.surface,alignItems:'center',justifyContent:'center'}}><Text adjustsFontSizeToFit numberOfLines={1} style={{color:theme.accentText,fontWeight:'900',letterSpacing:-.8,fontSize:Math.max(8,size*.34)}}>K✓</Text></View>;const logo=String(item?.business_logo_url||item?.business?.logo_url||brandLogoUrl(item)).trim();const showEvidence=needsEvidence&&evidenceFrame;const frame:ViewStyle={width:size,height:size,borderRadius:Math.max(6,size*.24),backgroundColor:theme.surface,borderWidth:showEvidence?2:1,borderColor:showEvidence?theme.warning:theme.line,borderStyle:showEvidence?'dashed':'solid',alignItems:'center' as const,justifyContent:'center' as const,overflow:'hidden' as const};const trustLabel=needsEvidence?' — needs community evidence':'';if(logo&&!imageFailed)return <View accessibilityLabel={`${businessName||signal.label} logo${trustLabel}`} style={frame}><Image source={{uri:logo}} onError={()=>setImageFailed(true)} resizeMode="contain" style={{width:size*.78,height:size*.78}}/></View>;if(businessName){const fallbackGlyph=brand?.icon||initials(businessName)||signal.icon;return <View accessibilityLabel={`${businessName} business icon${trustLabel}`} style={[frame,!showEvidence&&{backgroundColor:theme.accent,borderColor:theme.surface}]}><Text adjustsFontSizeToFit numberOfLines={1} style={{color:showEvidence?theme.accent:theme.accentText,fontWeight:'900',letterSpacing:-.4,fontSize:Math.max(8,size*(brand?.icon?0.44:0.38))}}>{fallbackGlyph}</Text></View>}if(needsEvidence)return <View accessibilityLabel="Unknown place identity — needs community evidence" style={{width:size,height:size,borderRadius:size/2,backgroundColor:theme.surface,borderWidth:evidenceFrame?2:1,borderColor:evidenceFrame?theme.warning:theme.line,borderStyle:evidenceFrame?'dashed':'solid',alignItems:'center',justifyContent:'center'}}><Text style={{color:evidenceFrame?theme.warning:theme.accent,fontWeight:'900',fontSize:Math.max(12,size*.58)}}>?</Text></View>;return <Text accessibilityLabel={signal.label} style={{fontSize:size*.82}}>{signal.icon}</Text>}
export function FreshnessHeatRing({item,size=24,active=false}:{item:Row;size?:number;active?:boolean}){const theme=useConsumerTheme();const heat=freshnessHeatSignal(item);const ringSize=size+(active?14:10);return <View accessibilityLabel={heat.label} style={{width:ringSize,height:ringSize,borderRadius:ringSize/2,backgroundColor:heat.color,alignItems:'center',justifyContent:'center',borderWidth:active?2:1,borderColor:active?theme.ink:theme.surface}}><View style={{width:ringSize-6,height:ringSize-6,borderRadius:(ringSize-6)/2,backgroundColor:theme.surface,alignItems:'center',justifyContent:'center'}}><PlaceIcon item={item} size={size} evidenceFrame={false}/></View></View>}
export function RestroomSignals({item,compact=false}:{item:Row;compact?:boolean}){const theme=useConsumerTheme();const signals:Signal[]=[];const place=placeSignal(item),networkVerified=isKleenestNetworkVerified(item),claimed=isBusinessClaimed(item);signals.push(place);if(networkVerified)signals.push({icon:'K✓',label:'Kleenest Network verified'});else if(networkState(item)==='building')signals.push({icon:'?',label:'Evidence building'});else if(needsRestroomVerification(item))signals.push({icon:'?',label:'Needs evidence'});else if(hasRestroomEvidence(item))signals.push({icon:'🚻',label:'Restroom evidence'});if(claimed)signals.push({icon:'▣',label:'Claimed business'});else if(!networkVerified&&isVerifiedRestroom(item))signals.push({icon:'✓',label:'Verified restroom'});if(Boolean(item?.accessible))signals.push({icon:'♿',label:'Accessible'});if(Boolean(item?.changing_table))signals.push({icon:'👶',label:'Changing table'});if(Boolean(item?.smart_bathroom))signals.push({icon:'◉',label:'Smart bathroom'});const clean=Number(item?.cleanliness_pct);if(Number.isFinite(clean))signals.push({icon:'✨',label:`${Math.round(clean)}% clean`});const rating=Number(item?.rating);if(Number.isFinite(rating)&&rating>0)signals.push({icon:'★',label:rating.toFixed(1)});return <View style={styles.row}>{signals.slice(0,compact?5:7).map((signal,index)=><View key={`${signal.label}-${index}`} accessibilityLabel={signal.label} style={[styles.badge,{backgroundColor:theme.surfaceRaised,borderColor:theme.line},compact&&styles.badgeCompact]}><Text style={styles.icon}>{signal.icon}</Text><Text style={[styles.label,{color:theme.ink},compact&&styles.labelCompact]}>{signal.label}</Text></View>)}</View>}
export function CompactRestroomSignals({item}:{item:Row}){const theme=useConsumerTheme();const signals:{icon:string;value?:string;label:string}[]=[],networkVerified=isKleenestNetworkVerified(item),claimed=isBusinessClaimed(item);if(networkVerified)signals.push({icon:'K✓',label:'Kleenest Network verified'});else if(networkState(item)==='building')signals.push({icon:'?',value:'Building',label:'Community evidence building'});else if(needsRestroomVerification(item))signals.push({icon:'?',value:'Evidence',label:'Needs community evidence'});else if(hasRestroomEvidence(item))signals.push({icon:'🚻',label:'Restroom evidence'});if(claimed)signals.push({icon:'▣',label:'Claimed business'});else if(!networkVerified&&isVerifiedRestroom(item))signals.push({icon:'✓',label:'Verified restroom'});const rating=Number(item?.rating);if(Number.isFinite(rating)&&rating>0)signals.push({icon:'★',value:rating.toFixed(1),label:`Rating ${rating.toFixed(1)}`});const clean=Number(item?.cleanliness_pct);if(Number.isFinite(clean))signals.push({icon:'✨',value:`${Math.round(clean)}%`,label:`${Math.round(clean)} percent clean`});if(Boolean(item?.accessible))signals.push({icon:'♿',label:'Accessible'});if(Boolean(item?.changing_table))signals.push({icon:'👶',label:'Changing table'});const visits=Number(item?.network?.verified_visits||item?.trust?.verified_visit_count||0);if(visits>0)signals.push({icon:'✓',value:String(visits),label:`${visits} verified visits`});if(Boolean(item?.smart_bathroom))signals.push({icon:'◉',label:'Smart bathroom'});return <View style={styles.row}>{signals.slice(0,7).map((signal,index)=><View key={`${signal.label}-${index}`} accessibilityLabel={signal.label} style={[styles.badge,{backgroundColor:theme.surfaceRaised,borderColor:theme.line},styles.badgeCompact]}><Text style={styles.icon}>{signal.icon}</Text>{signal.value?<Text style={[styles.labelCompact,{color:theme.ink}]}>{signal.value}</Text>:null}</View>)}</View>}
export function MapLegend(){const theme=useConsumerTheme();const[expanded,setExpanded]=useState(false);return <View style={[styles.legend,{backgroundColor:theme.surface,borderColor:theme.line},expanded&&styles.legendExpanded]} accessibilityLabel="Map legend"><Pressable accessibilityRole="button" accessibilityLabel={expanded?'Close map legend':'Open map legend'} onPress={()=>setExpanded(value=>!value)} style={styles.legendHeader}><Text style={[styles.legendTitle,{color:theme.accent}]}>MAP LEGEND</Text><Text style={[styles.legendToggle,{color:theme.muted}]}>{expanded?'Close ×':'Legend +'}</Text></Pressable>{expanded?<View style={styles.legendBody}><Text style={[styles.heatTitle,{color:theme.ink}]}>FRESHNESS RING</Text><View style={styles.heatScale}><HeatDot color="#ef4444" label="<24h"/><HeatDot color="#f97316" label="1–3d"/><HeatDot color="#facc15" label="<7d"/><HeatDot color="#84cc16" label="<30d"/><HeatDot color="#06b6d4" label="1–3mo"/><HeatDot color="#3b82f6" label="3mo+"/><HeatDot color="#94a3b8" label="Unknown"/></View><View style={styles.legendRow}><Legend icon="●" label="You"/><Legend icon="?" label="Unknown identity / evidence needed"/><Legend icon="K✓" label="Network verified"/><Legend icon="▣" label="Claimed business"/><Legend icon="🍴" label="Food"/><Legend icon="☕" label="Cafe"/><Legend icon="⛽" label="Travel"/><Legend icon="🛍" label="Shopping"/><Legend icon="🌳" label="Park"/><Legend icon="🚻" label="Restroom evidence"/><Legend icon="♿" label="Accessible"/><Legend icon="👶" label="Family"/></View></View>:null}</View>}
function HeatDot({color,label}:{color:string;label:string}){const theme=useConsumerTheme();return <View style={styles.heatItem}><View style={[styles.heatDot,{backgroundColor:color,borderColor:theme.surface}]}/><Text style={[styles.heatLabel,{color:theme.muted}]}>{label}</Text></View>}function Legend({icon,label}:{icon:string;label:string}){const theme=useConsumerTheme();return <View style={styles.legendItem}><Text style={[styles.legendIcon,{color:theme.accent}]}>{icon}</Text><Text style={[styles.legendLabel,{color:theme.muted}]}>{label}</Text></View>}
const styles=StyleSheet.create({row:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},badge:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#eef4f0',borderWidth:1,borderColor:'#d5e2da',borderRadius:999,paddingHorizontal:8,paddingVertical:6},badgeCompact:{paddingHorizontal:7,paddingVertical:5},icon:{fontSize:13},label:{fontSize:9,fontWeight:'900',color:'#3f594b'},labelCompact:{fontSize:8},legend:{backgroundColor:'rgba(255,255,255,.96)',borderWidth:1,borderColor:'#d2dfd7',borderRadius:12,paddingHorizontal:8,paddingVertical:7,maxWidth:118},legendExpanded:{maxWidth:250},legendHeader:{flexDirection:'row',alignItems:'center',gap:8},legendBody:{gap:6},heatTitle:{fontSize:7,fontWeight:'900',letterSpacing:.8,marginTop:6},heatScale:{flexDirection:'row',flexWrap:'wrap',gap:6},heatItem:{flexDirection:'row',alignItems:'center',gap:3},heatDot:{width:10,height:10,borderRadius:5,borderWidth:1},heatLabel:{fontSize:7,fontWeight:'800'},legendTitle:{fontSize:7,fontWeight:'900',letterSpacing:1,color:palette.green},legendToggle:{fontSize:7,fontWeight:'900',color:'#53675a'},legendRow:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:6},legendItem:{flexDirection:'row',alignItems:'center',gap:3},legendIcon:{fontSize:10,color:palette.green,fontWeight:'900'},legendLabel:{fontSize:7,fontWeight:'800',color:'#53675a'}});