import { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { palette } from './ConsumerUI';

type Row=Record<string,any>;
type Signal={icon:string;label:string};
type BrandIdentity=Signal&{domain?:string};

const placeSignals:Record<string,Signal>={shopping:{icon:'🛍',label:'Shopping'},restaurant:{icon:'🍴',label:'Restaurant'},service:{icon:'🏢',label:'Service'},park:{icon:'🌳',label:'Park'},cafe:{icon:'☕',label:'Cafe'},restroom:{icon:'🚻',label:'Public restroom'},health:{icon:'🏥',label:'Health'},gas_station:{icon:'⛽',label:'Fuel / travel stop'},public_safety:{icon:'🛡',label:'Public safety'},library:{icon:'📚',label:'Library'},library_dropoff:{icon:'📚',label:'Library'},dog_park:{icon:'🐾',label:'Dog park'},government:{icon:'🏛',label:'Government'},brand:{icon:'🏢',label:'Business'}};
const brandSignals:[RegExp,BrandIdentity][]=[
[/\bstarbucks\b/i,{icon:'☕',label:'Starbucks',domain:'starbucks.com'}],[/\bmcdonald'?s\b/i,{icon:'Ⓜ',label:"McDonald's",domain:'mcdonalds.com'}],[/\bwalmart\b/i,{icon:'✳',label:'Walmart',domain:'walmart.com'}],[/\btaco bell\b/i,{icon:'🔔',label:'Taco Bell',domain:'tacobell.com'}],[/\bjack in the box\b/i,{icon:'J',label:'Jack in the Box',domain:'jackinthebox.com'}],[/\bmercy\b/i,{icon:'M',label:'Mercy',domain:'mercy.net'}],[/\btarget\b/i,{icon:'◎',label:'Target',domain:'target.com'}],[/\bcostco\b/i,{icon:'Ⓒ',label:'Costco',domain:'costco.com'}],[/\bsam'?s club\b/i,{icon:'S',label:"Sam's Club",domain:'samsclub.com'}],[/\bwalgreens\b/i,{icon:'ⓦ',label:'Walgreens',domain:'walgreens.com'}],[/\bcvs\b/i,{icon:'✚',label:'CVS',domain:'cvs.com'}],[/\blove'?s\b/i,{icon:'♥',label:"Love's",domain:'loves.com'}],[/\bpilot\b/i,{icon:'Ⓟ',label:'Pilot',domain:'pilotflyingj.com'}],[/\bflying j\b/i,{icon:'Ⓙ',label:'Flying J',domain:'pilotflyingj.com'}],[/\bquiktrip\b|\bqt\b/i,{icon:'Ⓠ',label:'QuikTrip',domain:'quiktrip.com'}],[/\b7-?eleven\b/i,{icon:'7',label:'7-Eleven',domain:'7-eleven.com'}],[/\bspeedway\b/i,{icon:'S',label:'Speedway',domain:'speedway.com'}],[/\bcasey'?s\b/i,{icon:'C',label:"Casey's",domain:'caseys.com'}],[/\bu-?haul\b/i,{icon:'Ⓤ',label:'U-Haul',domain:'uhaul.com'}],[/\bhome depot\b/i,{icon:'Ⓗ',label:'Home Depot',domain:'homedepot.com'}],[/\blowe'?s\b/i,{icon:'Ⓛ',label:"Lowe's",domain:'lowes.com'}],[/\bkroger\b/i,{icon:'Ⓚ',label:'Kroger',domain:'kroger.com'}],[/\baldi\b/i,{icon:'Ⓐ',label:'ALDI',domain:'aldi.us'}],[/\bwhole foods\b/i,{icon:'W',label:'Whole Foods',domain:'wholefoodsmarket.com'}],[/\btrader joe'?s\b/i,{icon:'T',label:"Trader Joe's",domain:'traderjoes.com'}],[/\bshell\b/i,{icon:'⛽',label:'Shell',domain:'shell.com'}],[/\bwendy'?s\b/i,{icon:'W',label:"Wendy's",domain:'wendys.com'}],[/\bburger king\b/i,{icon:'BK',label:'Burger King',domain:'bk.com'}],[/\bsubway\b/i,{icon:'S',label:'Subway',domain:'subway.com'}],[/\bchick-fil-a\b/i,{icon:'C',label:'Chick-fil-A',domain:'chick-fil-a.com'}],[/\bdunkin'?\b/i,{icon:'D',label:'Dunkin',domain:'dunkindonuts.com'}],[/\bsonic\b/i,{icon:'S',label:'Sonic',domain:'sonicdrivein.com'}],[/\bpopeyes\b/i,{icon:'P',label:'Popeyes',domain:'popeyes.com'}],[/\bchipotle\b/i,{icon:'C',label:'Chipotle',domain:'chipotle.com'}],[/\bpanera\b/i,{icon:'P',label:'Panera',domain:'panerabread.com'}],[/\bkfc\b|\bkentucky fried chicken\b/i,{icon:'K',label:'KFC',domain:'kfc.com'}],[/\barby'?s\b/i,{icon:'A',label:"Arby's",domain:'arbys.com'}],[/\b(bp|exxon|mobil|chevron|circle k)\b/i,{icon:'⛽',label:'Fuel stop'}]
];
const businessLikeTypes=new Set(['shopping','restaurant','service','cafe','health','gas_station','brand']);
export function isVerifiedRestroom(item:Row){return Boolean(item?.is_verified||String(item?.verification_status||'').toLowerCase()==='verified'||String(item?.bathroom_verification_status||'').toLowerCase()==='verified')}
function identityText(item:Row){return [item?.business_name,item?.business?.name,item?.brand,item?.operator_name,item?.name].filter(Boolean).join(' ')}
function brandIdentity(item:Row):BrandIdentity|null{const identity=identityText(item);for(const [pattern,signal] of brandSignals)if(pattern.test(identity))return signal;return null}
export function placeSignal(item:Row):Signal{return brandIdentity(item)||placeSignals[String(item?.place_type||item?.category||'').toLowerCase()]||{icon:'🚻',label:'Restroom location'}}
export function restroomMarkerGlyph(item:Row){return placeSignal(item).icon}
export function restroomMarkerLabel(item:Row){const place=placeSignal(item);const extras=[isVerifiedRestroom(item)?'verified':null,Boolean(item?.accessible)?'accessible':null,Boolean(item?.changing_table)?'family feature':null].filter(Boolean).join(', ');return extras?`${place.label}, ${extras}`:place.label}
function explicitBusinessName(item:Row){return String(item?.business_name||item?.business?.name||item?.brand||item?.operator_name||'').trim()}
function displayBusinessName(item:Row){const explicit=explicitBusinessName(item);if(explicit)return explicit;const brand=brandIdentity(item);if(brand)return brand.label;const kind=String(item?.place_type||item?.category||'').toLowerCase();return businessLikeTypes.has(kind)?String(item?.name||'').trim():''}
function initials(name:string){return name.replace(/[^a-z0-9'& -]/gi,' ').trim().split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase()}
function websiteDomain(item:Row){const raw=String(item?.business?.website||item?.website||'').trim();if(!raw)return '';try{return new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`).hostname.replace(/^www\./i,'')}catch{return ''}}
function favicon(domain:string){return domain?`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128`:''}
function brandLogoUrl(item:Row){const brand=brandIdentity(item);return favicon(brand?.domain||websiteDomain(item))}
export function PlaceIcon({item,size=24}:{item:Row;size?:number}){const[imageFailed,setImageFailed]=useState(false);const logo=String(item?.business_logo_url||item?.business?.logo_url||brandLogoUrl(item)).trim();const businessName=displayBusinessName(item);const signal=placeSignal(item);if(logo&&!imageFailed)return <View style={{width:size,height:size,borderRadius:Math.max(6,size*.24),backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6df',alignItems:'center',justifyContent:'center',overflow:'hidden'}}><Image accessibilityLabel={`${businessName||signal.label} logo`} source={{uri:logo}} onError={()=>setImageFailed(true)} resizeMode="contain" style={{width:size*.82,height:size*.82}}/></View>;if(businessName)return <View accessibilityLabel={`${businessName} business icon`} style={{width:size,height:size,borderRadius:Math.max(6,size*.24),backgroundColor:palette.green,borderWidth:1,borderColor:'#fff',alignItems:'center',justifyContent:'center'}}><Text adjustsFontSizeToFit numberOfLines={1} style={{color:'#fff',fontWeight:'900',letterSpacing:-.4,fontSize:Math.max(8,size*.38)}}>{initials(businessName)||signal.icon}</Text></View>;return <Text accessibilityLabel={signal.label} style={{fontSize:size*.82}}>{signal.icon}</Text>}
export function RestroomSignals({item,compact=false}:{item:Row;compact?:boolean}){const signals:Signal[]=[];const place=placeSignal(item);signals.push(place);if(isVerifiedRestroom(item))signals.push({icon:'✓',label:'Verified'});if(Boolean(item?.accessible))signals.push({icon:'♿',label:'Accessible'});if(Boolean(item?.changing_table))signals.push({icon:'👶',label:'Changing table'});if(Boolean(item?.smart_bathroom))signals.push({icon:'◉',label:'Smart bathroom'});const clean=Number(item?.cleanliness_pct);if(Number.isFinite(clean))signals.push({icon:'✨',label:`${Math.round(clean)}% clean`});const rating=Number(item?.rating);if(Number.isFinite(rating)&&rating>0)signals.push({icon:'★',label:rating.toFixed(1)});return <View style={styles.row}>{signals.slice(0,compact?5:7).map((signal,index)=><View key={`${signal.label}-${index}`} accessibilityLabel={signal.label} style={[styles.badge,compact&&styles.badgeCompact]}><Text style={styles.icon}>{signal.icon}</Text><Text style={[styles.label,compact&&styles.labelCompact]}>{signal.label}</Text></View>)}</View>}
export function MapLegend(){const[expanded,setExpanded]=useState(false);return <View style={[styles.legend,expanded&&styles.legendExpanded]} accessibilityLabel="Map legend"><Pressable accessibilityRole="button" accessibilityLabel={expanded?'Close map legend':'Open map legend'} onPress={()=>setExpanded(value=>!value)} style={styles.legendHeader}><Text style={styles.legendTitle}>MAP LEGEND</Text><Text style={styles.legendToggle}>{expanded?'Close ×':'Legend +'}</Text></Pressable>{expanded?<View style={styles.legendRow}><Legend icon="●" label="You"/><Legend icon="▣" label="Business / brand"/><Legend icon="🍴" label="Food"/><Legend icon="☕" label="Cafe"/><Legend icon="⛽" label="Travel"/><Legend icon="🛍" label="Shopping"/><Legend icon="🌳" label="Park"/><Legend icon="🚻" label="Restroom"/><Legend icon="✓" label="Verified"/><Legend icon="♿" label="Accessible"/><Legend icon="👶" label="Family"/></View>:null}</View>}
function Legend({icon,label}:{icon:string;label:string}){return <View style={styles.legendItem}><Text style={styles.legendIcon}>{icon}</Text><Text style={styles.legendLabel}>{label}</Text></View>}
const styles=StyleSheet.create({row:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},badge:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#eef4f0',borderWidth:1,borderColor:'#d5e2da',borderRadius:999,paddingHorizontal:8,paddingVertical:6},badgeCompact:{paddingHorizontal:7,paddingVertical:5},icon:{fontSize:13},label:{fontSize:9,fontWeight:'900',color:'#3f594b'},labelCompact:{fontSize:8},legend:{backgroundColor:'rgba(255,255,255,.96)',borderWidth:1,borderColor:'#d2dfd7',borderRadius:12,paddingHorizontal:8,paddingVertical:7,maxWidth:118},legendExpanded:{maxWidth:250},legendHeader:{flexDirection:'row',alignItems:'center',gap:8},legendTitle:{fontSize:7,fontWeight:'900',letterSpacing:1,color:palette.green},legendToggle:{fontSize:7,fontWeight:'900',color:'#53675a'},legendRow:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:6},legendItem:{flexDirection:'row',alignItems:'center',gap:3},legendIcon:{fontSize:10,color:palette.green,fontWeight:'900'},legendLabel:{fontSize:7,fontWeight:'800',color:'#53675a'}});