import { useEffect,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { createDriver,createVehicle,setDriverStatus,setVehicleStatus } from '../services/product';
import { currentFleetBusinessId,getFleetAdvancedIntelligence,getFleetInventory } from '../services/control';
import { assignDriverUser,deleteDriver,deleteVehicle,listFleetAssignableMembers,updateDriver,updateVehicle } from '../services/parity';
import { useFleetTheme } from '../services/theme';
type Row=Record<string,any>;type Editor={kind:'vehicle'|'driver';row:Row}|null;
export default function Assets(){
 const theme=useFleetTheme();
 const[businessId,setBusinessId]=useState(''),[inventory,setInventory]=useState<any>(null),[intel,setIntel]=useState<any>(null),[members,setMembers]=useState<Row[]>([]),[vehicle,setVehicle]=useState(''),[driver,setDriver]=useState(''),[editor,setEditor]=useState<Editor>(null),[name,setName]=useState(''),[unitCode,setUnitCode]=useState(''),[vehicleType,setVehicleType]=useState('service'),[odometer,setOdometer]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[assignedVehicle,setAssignedVehicle]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading assets…');
 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const[inv,signals,team]=await Promise.all([getFleetInventory(id),getFleetAdvancedIntelligence(id),listFleetAssignableMembers(id)]);setInventory(inv);setIntel(signals);setMembers(team);setMessage(signals.partial?'Some asset intelligence is temporarily unavailable.':'')}catch(e:any){setMessage(e?.message||'Assets unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,success:string,close=false){setBusy(true);try{await fn();setMessage(success);if(close)setEditor(null);await load()}catch(e:any){setMessage(e?.message||'Asset action failed.')}finally{setBusy(false)}}
 const vehicles=(inventory?.vehicles||[]) as Row[],drivers=(inventory?.drivers||[]) as Row[],scorecards=Array.isArray(intel?.assetScorecards)?intel.assetScorecards:[];
 function edit(kind:'vehicle'|'driver',row:Row){setEditor({kind,row});setName(String(row.name||''));setUnitCode(String(row.unit_code||''));setVehicleType(String(row.vehicle_type||'service'));setOdometer(row.odometer_miles==null?'':String(row.odometer_miles));setEmail(String(row.email||''));setPhone(String(row.phone||''));setAssignedVehicle(String(row.vehicle_id||''));}
 function confirmDelete(kind:'vehicle'|'driver',row:Row){Alert.alert(`Delete ${kind}?`,String(row.name||'This resource'),[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void run(()=>kind==='vehicle'?deleteVehicle(businessId,String(row.id)):deleteDriver(businessId,String(row.id)),`${kind==='vehicle'?'Vehicle':'Driver'} deleted.`,true)}])}
 async function save(){if(!editor)return;const row=editor.row;if(editor.kind==='vehicle')await run(()=>updateVehicle(businessId,{...row,name:name.trim()||'Fleet vehicle',unit_code:unitCode.trim()||null,vehicle_type:vehicleType.trim()||'service',odometer_miles:odometer.trim()?Number(odometer):null}), 'Vehicle updated.',true);else await run(()=>updateDriver(businessId,{...row,name:name.trim()||'Fleet driver',email:email.trim()||null,phone:phone.trim()||null,vehicle_id:assignedVehicle||null}),'Driver updated.',true)}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[s.page,{backgroundColor:theme.canvas}]}>
  <View style={[s.hero,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,borderWidth:1}]}><Text style={[s.kicker,{color:theme.accent}]}>VEHICLES & DRIVERS</Text><Text style={[s.title,{color:theme.ink}]}>Operate Fleet assets, not display cards.</Text><Text style={[s.body,{color:theme.muted}]}>Create, edit, assign and retire vehicles and drivers from the same Fleet workspace used by routing and dispatch.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={[s.message,{color:theme.muted}]}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Vehicles" value={vehicles.length}/><Metric label="Drivers" value={drivers.length}/><Metric label="Asset scorecards" value={scorecards.length}/></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.cardTitle,{color:theme.ink}]}>Add assets</Text><TextInput placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} placeholder="Vehicle name / unit" value={vehicle} onChangeText={setVehicle}/><Action label="Add vehicle" disabled={busy||!vehicle.trim()} onPress={()=>run(async()=>{await createVehicle(businessId,{name:vehicle.trim()});setVehicle('')},'Vehicle created.')}/><TextInput placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} placeholder="Driver name" value={driver} onChangeText={setDriver}/><Action label="Add driver" disabled={busy||!driver.trim()} onPress={()=>run(async()=>{await createDriver(businessId,{name:driver.trim()});setDriver('')},'Driver created.')}/></View>
  <Text style={[s.section,{color:theme.ink}]}>Vehicles</Text>{vehicles.map(row=><View key={String(row.id)} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><View style={s.row}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{String(row.name||row.unit_code||'Vehicle')}</Text><Text style={[s.meta,{color:theme.muted}]}>{[row.unit_code,row.vehicle_type,row.driver_name,row.odometer_miles!=null?`${Number(row.odometer_miles).toLocaleString()} mi`:null].filter(Boolean).join(' · ')}</Text></View><Pill label={String(row.status||'active').toUpperCase()}/></View><View style={s.row}><Action quiet label="Edit vehicle" disabled={busy} onPress={()=>edit('vehicle',row)}/><Action danger label="Delete vehicle" disabled={busy} onPress={()=>confirmDelete('vehicle',row)}/>{['active','inactive','maintenance'].map(value=><Pressable key={value} disabled={busy||String(row.status)===value} onPress={()=>void run(()=>setVehicleStatus(businessId,String(row.id),value),`Vehicle marked ${value}.`)} style={[s.chip,{backgroundColor:String(row.status)===value?theme.accent:theme.surfaceRaised,borderColor:String(row.status)===value?theme.accent:theme.line,borderWidth:1}]}><Text style={[s.chipText,{color:String(row.status)===value?theme.accentText:theme.ink}]}>{value}</Text></Pressable>)}</View></View>)}
  <Text style={[s.section,{color:theme.ink}]}>Drivers</Text>{drivers.map(row=><View key={String(row.id)} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><View style={s.row}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{String(row.name||'Fleet driver')}</Text><Text style={[s.meta,{color:theme.muted}]}>{[row.email,row.phone,row.vehicle_id?'Vehicle assigned':null,row.user_id?'App account linked':null].filter(Boolean).join(' · ')||'Driver profile'}</Text></View><Pill label={String(row.status||'active').toUpperCase()}/></View><View style={s.row}><Action quiet label="Edit driver" disabled={busy} onPress={()=>edit('driver',row)}/><Action danger label="Delete driver" disabled={busy} onPress={()=>confirmDelete('driver',row)}/>{['active','inactive'].map(value=><Pressable key={value} disabled={busy||String(row.status)===value} onPress={()=>void run(()=>setDriverStatus(businessId,String(row.id),value),`Driver marked ${value}.`)} style={[s.chip,{backgroundColor:String(row.status)===value?theme.accent:theme.surfaceRaised,borderColor:String(row.status)===value?theme.accent:theme.line,borderWidth:1}]}><Text style={[s.chipText,{color:String(row.status)===value?theme.accentText:theme.ink}]}>{value}</Text></Pressable>)}</View><Text style={[s.label,{color:theme.muted}]}>ASSIGN ACCOUNT</Text><View style={s.row}>{members.map(member=>{const uid=String(member.user_id||'');const linked=String(row.user_id||'')===uid;return <Action key={uid} quiet={!linked} label={linked?'✓ Assigned':`Assign account · ${String(member.role||'member')}`} disabled={busy||linked||!uid} onPress={()=>run(()=>assignDriverUser(businessId,String(row.id),uid),'Driver account assigned.')}/>})}{!members.length?<Text style={[s.meta,{color:theme.muted}]}>Add this person to the Business team first, then assign their account here.</Text>:null}</View></View>)}
  {editor?<View style={[s.editor,{backgroundColor:theme.surfaceRaised,borderColor:theme.accent}]}><Text style={[s.section,{color:theme.ink}]}>{editor.kind==='vehicle'?'Edit vehicle':'Edit driver'}</Text><Text style={[s.label,{color:theme.muted}]}>NAME</Text><TextInput placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={name} onChangeText={setName}/>{editor.kind==='vehicle'?<><Text style={[s.label,{color:theme.muted}]}>UNIT CODE</Text><TextInput placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={unitCode} onChangeText={setUnitCode}/><Text style={[s.label,{color:theme.muted}]}>VEHICLE TYPE</Text><TextInput placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={vehicleType} onChangeText={setVehicleType}/><Text style={[s.label,{color:theme.muted}]}>ODOMETER MILES</Text><TextInput keyboardType="decimal-pad" placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={odometer} onChangeText={setOdometer}/></>:<><Text style={[s.label,{color:theme.muted}]}>EMAIL</Text><TextInput keyboardType="email-address" autoCapitalize="none" placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={email} onChangeText={setEmail}/><Text style={[s.label,{color:theme.muted}]}>PHONE</Text><TextInput keyboardType="phone-pad" placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]} value={phone} onChangeText={setPhone}/><Text style={[s.label,{color:theme.muted}]}>ASSIGN VEHICLE</Text><View style={s.row}><Action quiet label="Unassigned" disabled={busy||!assignedVehicle} onPress={()=>setAssignedVehicle('')}/>{vehicles.map(v=><Action key={String(v.id)} quiet={assignedVehicle!==String(v.id)} label={String(v.name||v.unit_code||'Vehicle')} disabled={busy} onPress={()=>setAssignedVehicle(String(v.id))}/>)}</View></>}<View style={s.row}><Action label="Save changes" disabled={busy||!name.trim()} onPress={save}/><Action quiet label="Cancel" disabled={busy} onPress={()=>setEditor(null)}/></View></View>:null}
  <Text style={[s.section,{color:theme.ink}]}>Exception scorecards</Text>{scorecards.length?scorecards.slice(0,30).map((row:Row,index:number)=><View key={String(row.asset_id||row.id||index)} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.cardTitle,{color:theme.ink}]}>{String(row.asset_name||row.driver_name||row.vehicle_name||row.name||'Fleet asset')}</Text><Text style={[s.meta,{color:theme.muted}]}>{[row.asset_type,row.exception_count!=null?`${row.exception_count} exceptions`:null,row.score!=null?`score ${row.score}`:null,row.risk_band].filter(Boolean).join(' · ')||'Fleet asset scorecard'}</Text></View>):<Empty text="No elevated asset exception scorecards."/>}
 </ScrollView>}
function Metric({label,value}:{label:string;value:number}){const theme=useFleetTheme();return <View style={[s.metric,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.ink}]}>{value}</Text><Text style={[s.meta,{color:theme.muted}]}>{label}</Text></View>}
function Pill({label}:{label:string}){const theme=useFleetTheme();return <View style={[s.pill,{backgroundColor:theme.accentSoft}]}><Text style={[s.pillText,{color:theme.accent}]}>{label}</Text></View>}
function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){const theme=useFleetTheme();return <Pressable disabled={disabled} onPress={onPress} style={[s.action,{backgroundColor:danger?theme.danger:quiet?theme.accentSoft:theme.accent,borderColor:danger?theme.danger:quiet?theme.line:theme.accent,borderWidth:1},disabled&&{opacity:.45}]}><Text style={[s.actionText,{color:danger?'#fff':quiet?theme.accent:theme.accentText}]}>{label}</Text></Pressable>}
function Empty({text}:{text:string}){const theme=useFleetTheme();return <View style={[s.empty,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,borderWidth:1}]}><Text style={[s.meta,{color:theme.muted}]}>{text}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:10,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},metrics:{flexDirection:'row',gap:8,flexWrap:'wrap'},metric:{minWidth:'30%',flexGrow:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},editor:{backgroundColor:'#eaf2ed',borderRadius:20,padding:15,gap:9,borderWidth:2,borderColor:'#173f2d'},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},action:{backgroundColor:'#173f2d',borderRadius:12,paddingHorizontal:11,paddingVertical:9,alignItems:'center'},quiet:{backgroundColor:'#edf3ef'},danger:{backgroundColor:'#7b2f2f'},actionText:{color:'#fff',fontWeight:'900',fontSize:12},section:{fontSize:21,fontWeight:'900',color:'#102218',marginTop:4},label:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#587066'},row:{flexDirection:'row',flexWrap:'wrap',gap:7,alignItems:'center'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillText:{fontSize:10,fontWeight:'900',color:'#31533f'},chip:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'800',color:'#365645'},chipTextOn:{color:'#fff'},empty:{backgroundColor:'#eef3f0',borderRadius:14,padding:13}});
