import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { getFleetRouteCoverageWorkspace,getRouteReliefCoverage } from '../services/routeReliefIntelligence';
import { useFleetTheme } from '../services/theme';

const pretty=(v:unknown)=>String(v??'').replaceAll('_',' ');
export default function Coverage(){
 const theme=useFleetTheme();
 const[businessId,setBusinessId]=useState(''),[routes,setRoutes]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[coverage,setCoverage]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading route coverage…');
 async function load(){setBusy(true);try{const ws=await getFleetRouteCoverageWorkspace();setBusinessId(ws.businessId);setRoutes(ws.routes);setSelected(ws.selected);setCoverage(ws.coverage);setMessage('')}catch(e:any){setMessage(e?.message||'Route coverage unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function choose(route:any){if(!businessId)return;setSelected(route);setBusy(true);try{setCoverage(await getRouteReliefCoverage(businessId,String(route.id)));setMessage('')}catch(e:any){setMessage(e?.message||'Could not calculate route coverage.')}finally{setBusy(false)}}
 const stops=Array.isArray(coverage?.stops)?coverage.stops:[];
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={[s.page,{backgroundColor:theme.canvas}]}>
  <View style={[s.hero,{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:'#173f2d',borderColor:theme.line}]}><Text style={s.kicker}>ROUTE COVERAGE · ROUTE RELIEF</Text><Text style={s.title}>Know where a route has trusted restroom support—and where it does not.</Text><Text style={s.body}>Coverage uses existing route stops plus Kleenest freshness, confidence and access evidence. It is operational context, not a replacement routing engine.</Text></View>
  {message?<View style={[s.notice,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.meta,{color:theme.ink,fontWeight:'800'}]}>{message}</Text></View>:null}
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>ROUTES</Text><View style={s.chips}>{routes.map(route=><Pressable key={route.id} onPress={()=>choose(route)} style={[s.chip,{backgroundColor:String(route.id)===String(selected?.id)?theme.accent:theme.surfaceRaised,borderColor:theme.line}]}><Text style={{fontWeight:'900',color:String(route.id)===String(selected?.id)?theme.accentText:theme.ink}}>{route.name||'Route'}</Text><Text style={{fontSize:10,color:String(route.id)===String(selected?.id)?theme.accentText:theme.muted}}>{pretty(route.status||'planned')}</Text></Pressable>)}</View>{!routes.length?<Text style={[s.meta,{color:theme.muted}]}>Create a Fleet route to calculate coverage.</Text>:null}</View>
  {coverage?<><View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>ROUTE COVERAGE</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{coverage.route_name||selected?.name||'Selected route'}</Text><View style={s.metrics}><Metric label="Coverage" value={`${Math.round(Number(coverage.coverage_pct||0))}%`} theme={theme}/><Metric label="Trusted stops" value={String(coverage.trusted_stop_count||0)} theme={theme}/><Metric label="Preferred access" value={String(coverage.preferred_access_count||0)} theme={theme}/></View><View style={[s.desert,{backgroundColor:coverage.restroom_desert?theme.surfaceRaised:theme.accentSoft,borderColor:theme.line}]}><Text style={[s.desertTitle,{color:coverage.restroom_desert?theme.warning:theme.accent}]}>{coverage.restroom_desert?'RESTROOM DESERT':'COVERAGE CONTINUITY'}</Text><Text style={[s.meta,{color:theme.muted}]}>{coverage.restroom_desert?`Estimated uncovered span ${Math.round(Number(coverage.longest_uncovered_minutes_estimate||0))} min, above the ${coverage.restroom_desert_threshold_minutes} min threshold.`:`Longest uncovered span is about ${Math.round(Number(coverage.longest_uncovered_minutes_estimate||0))} min.`} Basis: {pretty(coverage.basis||'stop sequence')}.</Text></View></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>WHY THIS COVERAGE?</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Explain the route signal</Text><Text style={[s.meta,{color:theme.muted}]}>A stop counts as covered only when its current Kleenest freshness and independent confidence clear the canonical thresholds. Preferred/Verified Access is shown separately; it does not manufacture confidence.</Text><Text style={[s.meta,{color:theme.ink}]}>Basis: {pretty(coverage.basis||'stop sequence')} · trusted {Number(coverage.trusted_stop_count||0)}/{Number(coverage.total_stops||0)} · longest uncovered {Math.round(Number(coverage.longest_uncovered_minutes_estimate||0))} min · desert threshold {Math.round(Number(coverage.restroom_desert_threshold_minutes||0))} min.</Text></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>CORRIDOR INTELLIGENCE</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Stops along this route</Text>{stops.map((row:any,index:number)=><View key={row.stop_id||index} style={[s.row,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>{row.stop_order}. {row.name||'Route stop'}</Text><Text style={[s.meta,{color:theme.muted}]}>{row.covered?'Trusted restroom coverage':'Coverage gap'} · freshness {Math.round(Number(row.kleenest_now?.freshness_score||0))} · confidence {Math.round(Number(row.kleenest_now?.confidence_score||0))}</Text>{row.verified_access?.allowed?<Text style={[s.access,{color:theme.accent}]}>Preferred access / Verified Access: {pretty(row.verified_access?.source)}</Text>:null}</View><Text style={[s.status,{color:row.covered?theme.accent:theme.warning}]}>{row.covered?'✓':'!'}</Text></View>)}</View></>:null}
 </ScrollView>
}
function Metric({label,value,theme}:{label:string;value:string;theme:any}){return <View style={[s.metric,{backgroundColor:theme.surfaceRaised,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.ink}]}>{value}</Text><Text style={[s.meta,{color:theme.muted}]}>{label}</Text></View>}
const s=StyleSheet.create({page:{padding:16,gap:12,paddingBottom:90},hero:{borderRadius:20,padding:16,gap:6,borderWidth:1},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#c9e8d4'},title:{fontSize:23,lineHeight:28,fontWeight:'900',color:'#fff'},body:{fontSize:12,lineHeight:18,color:'#e4eee8'},notice:{borderWidth:1,borderRadius:14,padding:11},card:{borderWidth:1,borderRadius:18,padding:14,gap:9},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},cardTitle:{fontSize:19,fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderRadius:14,paddingHorizontal:10,paddingVertical:8,gap:2},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:96,flexGrow:1,borderWidth:1,borderRadius:14,padding:10},metricValue:{fontSize:20,fontWeight:'900'},meta:{fontSize:11,lineHeight:16},desert:{borderWidth:1,borderRadius:14,padding:12,gap:3},desertTitle:{fontSize:11,fontWeight:'900',letterSpacing:.8},row:{borderTopWidth:1,paddingTop:9,flexDirection:'row',alignItems:'center',gap:10},rowTitle:{fontSize:13,fontWeight:'900'},access:{fontSize:10,fontWeight:'900'},status:{fontSize:22,fontWeight:'900'}});
