import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { createRoute,dispatchRoute,getFleetDashboard,listFleetWorkspaces,setRouteStatus } from '../services/product';
import { listOfflineRouteEvents,recordOrQueueRouteStopTiming,replayOfflineRouteEvents } from '../services/offline';

type Row=Record<string,unknown>;
const object=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const array=(value:unknown,key?:string):Row[]=>{const candidate=key?object(value)[key]:value;return Array.isArray(candidate)?candidate.filter((item):item is Row=>Boolean(item&&typeof item==='object')):[]};
const str=(row:Row,...keys:string[])=>{for(const key of keys){const value=row[key];if(value!==null&&value!==undefined&&String(value).trim())return String(value)}return''};

export default function Dispatch(){
 const[businessId,setBusinessId]=useState(''),[data,setData]=useState<any>(null),[name,setName]=useState(''),[queued,setQueued]=useState(0),[busy,setBusy]=useState<string|null>('load'),[message,setMessage]=useState('Loading dispatch…');
 async function load(){setBusy('load');try{const spaces:any[]=await listFleetWorkspaces();const nextId=businessId||String(spaces[0]?.business_id||'');if(!nextId)throw new Error('No Fleet workspace.');setBusinessId(nextId);setData(await getFleetDashboard(nextId));setQueued((await listOfflineRouteEvents()).length);setMessage('')}catch(e:any){setMessage(e?.message||'Dispatch unavailable.')}finally{setBusy(null)}}
 useEffect(()=>{void load()},[]);
 const dispatch=object(data?.dispatch),routes=useMemo(()=>array(dispatch,'routes'),[data]),preventiveStops=useMemo(()=>array(dispatch,'preventive_stops'),[data]),opportunityOrders=useMemo(()=>array(data?.opportunities,'work_orders'),[data]);
 const activeRoutes=routes.filter(route=>['active','paused'].includes(str(route,'status'))),plannedRoutes=routes.filter(route=>str(route,'status')==='planned');
 async function run(key:string,fn:()=>Promise<unknown>,success:string){setBusy(key);setMessage('');try{await fn();setMessage(success);await load()}catch(e:any){setMessage(e?.message||'Action failed.');setBusy(null)}}
 async function addRoute(){const routeName=name.trim();if(!routeName){setMessage('Give the route a useful name first.');return}await run('create',()=>createRoute(businessId,{name:routeName}),'Route created and ready for stops/assignment.');setName('')}
 async function sync(){setBusy('sync');try{const result=await replayOfflineRouteEvents();setQueued(result.remaining);setMessage(`Synced ${result.synced} queued stop events; ${result.remaining} remain.`);await load()}catch(e:any){setMessage(e?.message||'Offline events could not be replayed.');setBusy(null)}}
 return <ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={busy==='load'} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>FLEET DISPATCH</Text><Text style={s.heroTitle}>Run the route, not the database</Text><Text style={s.heroCopy}>Drivers and dispatchers see current routes, the next stop, exceptions, preventive work and sync state in one execution flow. IDs stay behind the interface.</Text></View>
  {queued>0?<Pressable onPress={sync} disabled={Boolean(busy)} style={s.offline}><View style={{flex:1}}><Text style={s.offlineTitle}>{queued} stop event{queued===1?'':'s'} waiting to sync</Text><Text style={s.meta}>Tap to replay them when connectivity is available. Field execution remains durable offline.</Text></View><Text style={s.syncText}>{busy==='sync'?'SYNCING':'SYNC'}</Text></Pressable>:null}
  {message?<View style={s.banner}><Text style={s.bannerText}>{message}</Text></View>:null}
  <View style={s.metrics}><Metric label="Running routes" value={activeRoutes.length}/><Metric label="Ready to dispatch" value={plannedRoutes.length}/><Metric label="Preventive stops" value={preventiveStops.length}/><Metric label="Work opportunities" value={opportunityOrders.length}/></View>
  <View style={s.section}><Text style={s.sectionTitle}>Running now</Text><Text style={s.sectionCopy}>Route cards are ordered around execution. Stop controls advance the canonical timing state and queue safely when the network disappears.</Text>{activeRoutes.length?activeRoutes.map(route=><RouteCard key={str(route,'id')} route={route} businessId={businessId} busy={busy} run={run}/>):<Empty title="No route is running" body="Dispatch one of the planned routes below when a driver is ready."/>}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Ready to dispatch</Text>{plannedRoutes.length?plannedRoutes.map(route=><RouteCard key={str(route,'id')} route={route} businessId={businessId} busy={busy} run={run}/>):<Empty title="No planned routes" body="Create a route below, then add/assign stops through the route planning workflow."/>}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Preventive work to absorb into routes</Text><Text style={s.sectionCopy}>High-risk bathroom work is visible beside normal dispatch so a route can solve operational risk instead of creating a separate maintenance silo.</Text>{opportunityOrders.length?opportunityOrders.slice(0,12).map((row,index)=><View key={str(row,'work_order_id')||String(index)} style={s.card}><View style={s.cardTop}><View style={{flex:1}}><Text style={s.cardTitle}>{str(row,'location_name')||'Location'}</Text><Text style={s.issue}>{str(row,'amenity_name')||'Preventive service'} · {str(row,'recommendation_action')||'Service recommended'}</Text></View><Pill label={(str(row,'priority')||'normal').toUpperCase()}/></View><View style={s.factRow}><Fact label="Due" value={formatDate(str(row,'due_at'))}/><Fact label="Route" value={str(row,'assigned_route_id')?'Already assigned':'Unassigned'}/><Fact label="Escalation" value={str(row,'escalation_level')||'0'}/></View></View>):<Empty title="No preventive route opportunities" body="When preventive work is due, it will be ranked here for dispatch planning."/>}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Create a route</Text><View style={s.card}><Text style={s.meta}>Use a human-readable route name. Driver, vehicle and stops can then be assigned in route planning; no UUID entry is required here.</Text><TextInput style={s.input} placeholder="e.g. Northside morning service" value={name} onChangeText={setName}/><Action label={busy==='create'?'Creating…':'Create planned route'} disabled={Boolean(busy)} onPress={addRoute}/></View></View>
 </ScrollView>
}

function RouteCard({route,businessId,busy,run}:{route:Row;businessId:string;busy:string|null;run:(key:string,fn:()=>Promise<unknown>,success:string)=>Promise<void>}){const routeId=str(route,'id','route_id'),status=str(route,'status')||'planned',stops=array(route,'stops'),nextIndex=Math.max(0,stops.findIndex(stop=>!['completed','skipped','departed'].includes(str(stop,'status')))),next=stops[nextIndex]||null;return <View style={s.routeCard}><View style={s.cardTop}><View style={{flex:1,gap:3}}><Text style={s.routeTitle}>{str(route,'name')||'Route'}</Text><Text style={s.meta}>{formatDate(str(route,'scheduled_for'))} · {stops.length} stop{stops.length===1?'':'s'}</Text></View><Pill label={status.toUpperCase()}/></View>{next?<View style={s.nextStop}><Text style={s.nextLabel}>NEXT STOP · {nextIndex+1} OF {stops.length}</Text><Text style={s.cardTitle}>{str(next,'location_name','name')||`Stop ${nextIndex+1}`}</Text><Text style={s.meta}>{str(next,'address','status')||'Ready for field execution'}</Text><StopActions routeId={routeId} stop={next} businessId={businessId} busy={busy} run={run}/></View>:<View style={s.complete}><Text style={s.cardTitle}>{stops.length?'All route stops complete':'No stops assigned yet'}</Text><Text style={s.meta}>{stops.length?'Close the route when final reconciliation is complete.':'Add canonical locations to this route before dispatch.'}</Text></View>}<View style={s.actions}>{status==='planned'?<Action label="Dispatch" disabled={!routeId||Boolean(busy)||!stops.length} onPress={()=>run(`dispatch:${routeId}`,()=>dispatchRoute(businessId,routeId),'Route dispatched.')}/>:null}{status==='active'?<Action quiet label="Pause" disabled={Boolean(busy)} onPress={()=>run(`pause:${routeId}`,()=>setRouteStatus(businessId,routeId,'paused'),'Route paused.')}/>:null}{status==='paused'?<Action label="Resume" disabled={Boolean(busy)} onPress={()=>run(`resume:${routeId}`,()=>setRouteStatus(businessId,routeId,'active'),'Route resumed.')}/>:null}{['active','paused'].includes(status)&&stops.length>0&&!next?<Action label="Complete route" disabled={Boolean(busy)} onPress={()=>run(`complete:${routeId}`,()=>setRouteStatus(businessId,routeId,'completed'),'Route completed.')}/>:null}</View></View>}
function StopActions({routeId,stop,businessId,busy,run}:{routeId:string;stop:Row;businessId:string;busy:string|null;run:(key:string,fn:()=>Promise<unknown>,success:string)=>Promise<void>}){const stopId=str(stop,'id','route_stop_id'),status=str(stop,'status')||'pending';const action=status==='pending'||status==='planned'?'arrived':status==='arrived'?'service_started':status==='service_started'||status==='in_progress'?'completed':status==='completed'?'departed':null;const label=action==='arrived'?'Mark arrived':action==='service_started'?'Start service':action==='completed'?'Complete stop':action==='departed'?'Depart stop':null;return <View style={s.actions}>{action&&label?<Action label={label} disabled={Boolean(busy)} onPress={()=>run(`stop:${stopId}:${action}`,async()=>{const result=await recordOrQueueRouteStopTiming(businessId,routeId,stopId,action);if(result.queued)return result;return result},`${label} recorded.`)}/>:null}{!['completed','departed','skipped'].includes(status)?<Action quiet label="Skip" disabled={Boolean(busy)} onPress={()=>run(`stop:${stopId}:skip`,()=>recordOrQueueRouteStopTiming(businessId,routeId,stopId,'skipped'),'Stop skipped with timing evidence.')}/>:null}</View>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
function Fact({label,value}:{label:string;value:string}){return <View style={{minWidth:90,flexGrow:1,flexBasis:90}}><Text style={s.factLabel}>{label}</Text><Text style={s.factValue}>{value}</Text></View>}
function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}
function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.actionQuiet,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&{color:'#244d39'}]}>{label}</Text></Pressable>}
function Empty({title,body}:{title:string;body:string}){return <View style={s.empty}><Text style={s.cardTitle}>{title}</Text><Text style={s.meta}>{body}</Text></View>}
function formatDate(value:string){if(!value)return'Unscheduled';const date=new Date(value);return Number.isNaN(date.getTime())?'Unscheduled':date.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
const s=StyleSheet.create({page:{padding:18,gap:18,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#173f2d',padding:19,borderRadius:24,gap:7},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.3,color:'#c7e8d5'},heroTitle:{fontSize:27,fontWeight:'900',color:'#fff'},heroCopy:{fontSize:14,lineHeight:21,color:'#deebe4'},offline:{backgroundColor:'#fff0d5',borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:12},offlineTitle:{fontWeight:'900',color:'#65430d'},syncText:{fontWeight:'900',color:'#65430d'},banner:{backgroundColor:'#eef3f0',borderRadius:14,padding:12},bannerText:{fontWeight:'800',color:'#365245'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',borderRadius:17,padding:14,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:23,fontWeight:'900',color:'#173f2d'},section:{gap:9},sectionTitle:{fontSize:21,fontWeight:'900',color:'#102218'},sectionCopy:{color:'#617068',lineHeight:19},routeCard:{backgroundColor:'#fff',borderRadius:20,padding:16,gap:12,borderWidth:1,borderColor:'#dbe5de'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:10,borderWidth:1,borderColor:'#dbe5de'},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:8},routeTitle:{fontSize:20,fontWeight:'900',color:'#102218'},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},issue:{fontSize:14,fontWeight:'700',color:'#4d6256'},meta:{fontSize:12,lineHeight:18,color:'#6a796f'},nextStop:{backgroundColor:'#f5f8f6',borderRadius:15,padding:13,gap:6},nextLabel:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#557060'},complete:{backgroundColor:'#edf6f0',borderRadius:15,padding:13,gap:4},factRow:{flexDirection:'row',flexWrap:'wrap',gap:10},factLabel:{fontSize:10,fontWeight:'900',letterSpacing:.6,color:'#718077',textTransform:'uppercase'},factValue:{fontSize:13,fontWeight:'800',color:'#243b2f'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6,alignSelf:'flex-start'},pillText:{fontSize:10,fontWeight:'900',color:'#28533c'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:12,backgroundColor:'#fafcfb'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},action:{backgroundColor:'#173f2d',paddingHorizontal:12,paddingVertical:9,borderRadius:999},actionQuiet:{backgroundColor:'#edf3ef'},actionText:{fontWeight:'900',color:'#fff'},empty:{backgroundColor:'#eef3f0',borderRadius:16,padding:15,gap:4}});
