import { useEffect,useState } from 'react';
import { Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { completeMaintenance,createMaintenance,resolveAlert } from '../services/product';
import { currentFleetBusinessId,getFleetInventory } from '../services/control';
import { deleteMaintenance,updateMaintenance } from '../services/parity';
type Row=Record<string,any>;
export default function Maintenance(){
 const[businessId,setBusinessId]=useState(''),[inventory,setInventory]=useState<any>(null),[vehicleId,setVehicleId]=useState(''),[type,setType]=useState('inspection'),[editing,setEditing]=useState<Row|null>(null),[editVehicle,setEditVehicle]=useState(''),[editType,setEditType]=useState('inspection'),[status,setStatus]=useState('scheduled'),[scheduledAt,setScheduledAt]=useState(''),[odometer,setOdometer]=useState(''),[cost,setCost]=useState(''),[vendor,setVendor]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading maintenance…');
 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const inv=await getFleetInventory(id);setInventory(inv);if(!vehicleId&&inv.vehicles?.[0]?.id)setVehicleId(String(inv.vehicles[0].id));setMessage('')}catch(e:any){setMessage(e?.message||'Maintenance unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,success:string,close=false){setBusy(true);try{await fn();setMessage(success);if(close)setEditing(null);await load()}catch(e:any){setMessage(e?.message||'Maintenance action failed.')}finally{setBusy(false)}}
 const vehicles=(inventory?.vehicles||[]) as Row[],maintenance=(inventory?.maintenance||[]) as Row[],alerts=(inventory?.alerts||[]) as Row[];
 function edit(row:Row){setEditing(row);setEditVehicle(String(row.vehicle_id||''));setEditType(String(row.maintenance_type||row.type||'inspection'));setStatus(String(row.status||'scheduled'));setScheduledAt(String(row.scheduled_at||''));setOdometer(row.odometer_miles==null?'':String(row.odometer_miles));setCost(row.cost==null?'':String(row.cost));setVendor(String(row.vendor||''));setNotes(String(row.notes||''))}
 async function save(){if(!editing)return;await run(()=>updateMaintenance(businessId,{...editing,vehicle_id:editVehicle||null,maintenance_type:editType.trim()||'inspection',status,scheduled_at:scheduledAt.trim()||null,odometer_miles:odometer.trim()?Number(odometer):null,cost:cost.trim()?Number(cost):null,vendor:vendor.trim()||null,notes:notes.trim()||null}),'Maintenance updated.',true)}
 function remove(row:Row){Alert.alert('Delete maintenance record?',String(row.maintenance_type||'Maintenance'),[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void run(()=>deleteMaintenance(businessId,String(row.id)),'Maintenance record deleted.',true)}])}
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.kicker}>MAINTENANCE + ALERTS</Text><Text style={s.title}>Full service lifecycle controls.</Text><Text style={s.body}>Schedule, edit, complete or remove maintenance records and resolve Fleet exceptions against the same operational inventory.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Scheduled/open" value={maintenance.filter(row=>!['completed','cancelled'].includes(String(row.status))).length}/><Metric label="Alerts" value={alerts.filter(row=>!['resolved','closed'].includes(String(row.status))).length}/></View>
  <View style={s.card}><Text style={s.cardTitle}>Schedule maintenance</Text><Text style={s.label}>Vehicle</Text><View style={s.row}>{vehicles.map(row=>{const id=String(row.id);return <Pressable key={id} onPress={()=>setVehicleId(id)} style={[s.chip,vehicleId===id&&s.chipOn]}><Text style={[s.chipText,vehicleId===id&&s.chipTextOn]}>{String(row.name||row.unit_code||'Vehicle')}</Text></Pressable>})}</View><TextInput style={s.input} placeholder="Maintenance type" value={type} onChangeText={setType}/><Action label="Schedule maintenance" disabled={busy||!vehicleId||!type.trim()} onPress={()=>run(()=>createMaintenance(businessId,{vehicleId,type:type.trim()}),'Maintenance scheduled.')}/></View>
  <Text style={s.section}>Maintenance records</Text>{maintenance.length?maintenance.map((row,index)=><View key={String(row.id||index)} style={s.card}><View style={s.rowTop}><View style={{flex:1}}><Text style={s.cardTitle}>{String(row.maintenance_type||row.type||'Maintenance')}</Text><Text style={s.meta}>{vehicleName(vehicles,row.vehicle_id)} · {String(row.status||'scheduled')}{row.scheduled_at?` · ${format(row.scheduled_at)}`:''}</Text><Text style={s.meta}>{[row.vendor,row.cost!=null?`$${Number(row.cost).toLocaleString()}`:null,row.odometer_miles!=null?`${Number(row.odometer_miles).toLocaleString()} mi`:null].filter(Boolean).join(' · ')}</Text></View><Pill label={String(row.status||'scheduled').toUpperCase()}/></View><View style={s.row}><Action quiet label="Edit maintenance" disabled={busy} onPress={()=>edit(row)}/><Action danger label="Delete maintenance" disabled={busy} onPress={()=>remove(row)}/>{!['completed','cancelled'].includes(String(row.status))?<Action label="Complete maintenance" disabled={busy} onPress={()=>run(()=>completeMaintenance(businessId,String(row.id),'Completed from Kleenest Fleet'),'Maintenance completed.')}/>:null}</View></View>):<Empty text="No maintenance records yet."/>}
  {editing?<View style={s.editor}><Text style={s.section}>Edit maintenance</Text><Text style={s.label}>VEHICLE</Text><View style={s.row}>{vehicles.map(row=><Action key={String(row.id)} quiet={editVehicle!==String(row.id)} label={String(row.name||row.unit_code||'Vehicle')} disabled={busy} onPress={()=>setEditVehicle(String(row.id))}/>)}</View><Text style={s.label}>TYPE</Text><TextInput style={s.input} value={editType} onChangeText={setEditType}/><Text style={s.label}>STATUS</Text><View style={s.row}>{['scheduled','in_progress','completed','cancelled'].map(v=><Action key={v} quiet={status!==v} label={v.replaceAll('_',' ')} disabled={busy} onPress={()=>setStatus(v)}/>)}</View><Text style={s.label}>SCHEDULED AT</Text><TextInput style={s.input} value={scheduledAt} onChangeText={setScheduledAt} placeholder="ISO date/time" autoCapitalize="none"/><Text style={s.label}>ODOMETER</Text><TextInput style={s.input} value={odometer} onChangeText={setOdometer} keyboardType="decimal-pad"/><Text style={s.label}>COST</Text><TextInput style={s.input} value={cost} onChangeText={setCost} keyboardType="decimal-pad"/><Text style={s.label}>VENDOR</Text><TextInput style={s.input} value={vendor} onChangeText={setVendor}/><Text style={s.label}>NOTES</Text><TextInput style={[s.input,{minHeight:70,textAlignVertical:'top'}]} value={notes} onChangeText={setNotes} multiline/><View style={s.row}><Action label="Save changes" disabled={busy||!editType.trim()} onPress={save}/><Action quiet label="Cancel" disabled={busy} onPress={()=>setEditing(null)}/></View></View>:null}
  <Text style={s.section}>Operational alerts</Text>{alerts.length?alerts.map((row,index)=><View key={String(row.id||row.alert_id||index)} style={s.card}><View style={s.rowTop}><View style={{flex:1}}><Text style={s.cardTitle}>{String(row.title||row.alert_type||'Fleet alert')}</Text><Text style={s.meta}>{String(row.message||row.description||row.reason||'Operational alert')}</Text></View><Pill label={String(row.severity||row.status||'OPEN').toUpperCase()}/></View>{!['resolved','closed'].includes(String(row.status))?<Action quiet label="Resolve alert" disabled={busy} onPress={()=>run(()=>resolveAlert(businessId,String(row.id||row.alert_id)),'Alert resolved.')}/>:null}</View>):<Empty text="No Fleet alerts."/>}
 </ScrollView>}
function vehicleName(rows:Row[],id:any){return String(rows.find(row=>String(row.id)===String(id))?.name||rows.find(row=>String(row.id)===String(id))?.unit_code||'Vehicle')}function format(value:any){const d=new Date(String(value));return Number.isNaN(d.getTime())?'Unscheduled':d.toLocaleString()}function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}function Action({label,onPress,disabled,quiet=false,danger=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.quiet,danger&&s.danger,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&{color:'#173f2d'}]}>{label}</Text></Pressable>}function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.meta}>{text}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:10,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'700',color:'#596b61'},metrics:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:22,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},editor:{backgroundColor:'#eaf2ed',borderRadius:20,padding:15,gap:9,borderWidth:2,borderColor:'#173f2d'},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},label:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#4f6559'},row:{flexDirection:'row',flexWrap:'wrap',gap:7},rowTop:{flexDirection:'row',gap:8,alignItems:'flex-start'},chip:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:10,paddingVertical:8},chipOn:{backgroundColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'800',color:'#365645'},chipTextOn:{color:'#fff'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:12,padding:11,backgroundColor:'#fafcfb'},action:{alignSelf:'flex-start',backgroundColor:'#173f2d',borderRadius:999,paddingHorizontal:12,paddingVertical:9},quiet:{backgroundColor:'#edf3ef'},danger:{backgroundColor:'#7b2f2f'},actionText:{fontWeight:'900',color:'#fff'},section:{fontSize:21,fontWeight:'900',color:'#102218',marginTop:4},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:6},pillText:{fontSize:10,fontWeight:'900',color:'#31533f'},empty:{backgroundColor:'#eef3f0',borderRadius:14,padding:13}});
