import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Switch,Text,TextInput,View } from 'react-native';
import { currentFleetBusinessId,getFleetInventory } from '../services/control';
import { assignFleetMetric,createFleetMetricDefinition,getFleetMetricCapabilities,getFleetMetricConfiguration,getFleetMetricValues,updateFleetMetricDefinition } from '../services/parity';
type Row=Record<string,any>;const rows=(v:any):Row[]=>Array.isArray(v)?v:Array.isArray(v?.rows)?v.rows:Array.isArray(v?.metrics)?v.metrics:Array.isArray(v?.definitions)?v.definitions:[];
export default function Metrics(){
 const[businessId,setBusinessId]=useState(''),[capabilities,setCapabilities]=useState<any>(null),[definitions,setDefinitions]=useState<Row[]>([]),[values,setValues]=useState<Row[]>([]),[inventory,setInventory]=useState<any>(null),[editing,setEditing]=useState<Row|null>(null),[name,setName]=useState('Fleet reliability'),[key,setKey]=useState('fleet_reliability'),[featureCode,setFeatureCode]=useState('fleet'),[sourceDataset,setSourceDataset]=useState('fleet_operational_events'),[sourceMetric,setSourceMetric]=useState('event_count'),[unit,setUnit]=useState('count'),[goal,setGoal]=useState('100'),[threshold,setThreshold]=useState('80'),[active,setActive]=useState(true),[assignType,setAssignType]=useState('driver'),[assignTarget,setAssignTarget]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Fleet metrics…');
 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const[cfg,caps,vals,inv]=await Promise.all([getFleetMetricConfiguration(id),getFleetMetricCapabilities(id),getFleetMetricValues(id),getFleetInventory(id)]);setDefinitions(rows(cfg));setCapabilities(caps);setValues(rows(vals));setInventory(inv);setMessage('')}catch(e:any){setMessage(e?.message||'Fleet metrics unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,success:string,close=false){setBusy(true);try{await fn();setMessage(success);if(close)setEditing(null);await load()}catch(e:any){setMessage(e?.message||'Metric action failed.')}finally{setBusy(false)}}
 function edit(row:Row){setEditing(row);setName(String(row.name||''));setKey(String(row.metric_key||row.key||''));setFeatureCode(String(row.feature_code||'fleet'));setSourceDataset(String(row.source_dataset||'fleet_operational_events'));setSourceMetric(String(row.source_metric||'event_count'));setUnit(String(row.unit||'count'));setGoal(row.goal==null?'':String(row.goal));setThreshold(row.threshold==null?'':String(row.threshold));setActive(row.active!==false)}
 async function create(){if(!name.trim()||!key.trim()||!sourceDataset.trim()||!sourceMetric.trim())return;await run(()=>createFleetMetricDefinition(businessId,{metricKey:key.trim(),featureCode:featureCode.trim()||'fleet',name:name.trim(),unit:unit.trim()||'count',sourceDataset:sourceDataset.trim(),sourceMetric:sourceMetric.trim(),goal:goal.trim()?Number(goal):null,threshold:threshold.trim()?Number(threshold):null}),'Metric definition created.')}
 async function save(){if(!editing)return;await run(()=>updateFleetMetricDefinition(String(editing.id||editing.metric_definition_id),{name:name.trim()||String(editing.name||'Fleet metric'),goal:goal.trim()?Number(goal):null,threshold:threshold.trim()?Number(threshold):null,active}),'Metric definition updated.',true)}
 const targets=assignType==='vehicle'?(inventory?.vehicles||[]):assignType==='route'?(inventory?.routes||[]):(inventory?.drivers||[]);
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>FLEET METRICS</Text><Text style={s.title}>Define what good Fleet performance means.</Text><Text style={s.copy}>Create canonical metrics, tune goals and thresholds, assign them to real Fleet entities and inspect current values without schema-level tooling.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Definitions" value={definitions.length}/><Metric label="Current values" value={values.length}/><Metric label="Capabilities" value={rows(capabilities).length||Object.keys(capabilities||{}).length}/></View>
  <View style={s.card}><Text style={s.cardTitle}>Create metric</Text><Field label="Metric name" value={name} set={setName}/><Field label="Stable metric key" value={key} set={setKey}/><Field label="Feature code" value={featureCode} set={setFeatureCode}/><Field label="Source dataset" value={sourceDataset} set={setSourceDataset}/><Field label="Source metric" value={sourceMetric} set={setSourceMetric}/><Field label="Unit" value={unit} set={setUnit}/><View style={s.two}><Field label="Goal" value={goal} set={setGoal} numeric/><Field label="Threshold" value={threshold} set={setThreshold} numeric/></View><Action label="Create metric" disabled={busy||!name.trim()||!key.trim()} onPress={create}/></View>
  <Text style={s.section}>Configured metrics</Text>{definitions.length?definitions.map((row,i)=>{const id=String(row.id||row.metric_definition_id||i);return <View key={id} style={s.card}><View style={s.spread}><View style={{flex:1}}><Text style={s.cardTitle}>{String(row.name||row.metric_key||'Metric')}</Text><Text style={s.meta}>{String(row.metric_key||'')} · {String(row.unit||'count')} · goal {row.goal??'—'} · threshold {row.threshold??'—'}</Text></View><Pill label={row.active===false?'OFF':'ACTIVE'}/></View><View style={s.actions}><Action quiet label="Edit metric" disabled={busy} onPress={()=>edit(row)}/><Action quiet label="Assign metric" disabled={busy} onPress={()=>{setEditing(row);setAssignTarget(String(targets[0]?.id||''))}}/></View></View>}):<View style={s.empty}><Text style={s.meta}>No custom Fleet metrics are configured yet.</Text></View>}
  {editing?<View style={s.editor}><Text style={s.section}>Edit metric · {String(editing.name||editing.metric_key||'Metric')}</Text><Field label="Name" value={name} set={setName}/><View style={s.two}><Field label="Goal" value={goal} set={setGoal} numeric/><Field label="Threshold" value={threshold} set={setThreshold} numeric/></View><View style={s.toggle}><Text style={s.label}>ACTIVE</Text><Switch value={active} onValueChange={setActive}/></View><View style={s.actions}><Action label="Save metric" disabled={busy} onPress={save}/><Action quiet label="Cancel" disabled={busy} onPress={()=>setEditing(null)}/></View><Text style={s.label}>ASSIGN METRIC</Text><View style={s.chips}>{['driver','vehicle','route'].map(v=><Choice key={v} label={v} active={assignType===v} onPress={()=>{setAssignType(v);setAssignTarget('')}}/>)}</View><View style={s.chips}>{targets.map((t:Row)=><Choice key={String(t.id)} label={String(t.name||t.unit_code||`${assignType} ${String(t.id).slice(0,6)}`)} active={assignTarget===String(t.id)} onPress={()=>setAssignTarget(String(t.id))}/>)}</View><Action label="Assign metric" disabled={busy||!assignTarget} onPress={()=>run(()=>assignFleetMetric(String(editing.id||editing.metric_definition_id),assignType,assignTarget),'Metric assignment saved.')}/></View>:null}
  <Text style={s.section}>Current metric values</Text>{values.slice(0,50).map((row,i)=><View key={String(row.id||row.metric_key||i)} style={s.card}><View style={s.spread}><Text style={s.cardTitle}>{String(row.name||row.metric_name||row.metric_key||'Metric')}</Text><Text style={s.value}>{String(row.value??row.metric_value??'—')} {String(row.unit||'')}</Text></View><Text style={s.meta}>{[row.target_type,row.target_name,row.period,row.as_of].filter(Boolean).join(' · ')}</Text></View>)}
 </ScrollView>}
function Metric({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}function Field({label,value,set,numeric=false}:{label:string;value:string;set:(v:string)=>void;numeric?:boolean}){return <View style={{flex:1,gap:4}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" style={s.input}/></View>}function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.quiet,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&{color:'#244d39'}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:12,paddingBottom:70,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#173f2d',borderRadius:23,padding:18,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{color:'#dce9e2',lineHeight:20},message:{fontWeight:'800',color:'#5d5140'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'30%',flexGrow:1,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:21,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#66766e'},card:{backgroundColor:'#fff',padding:14,borderRadius:17,borderWidth:1,borderColor:'#dbe5de',gap:9},editor:{backgroundColor:'#eaf2ed',padding:14,borderRadius:18,borderWidth:2,borderColor:'#173f2d',gap:9},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},section:{fontSize:20,fontWeight:'900',color:'#102218'},label:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#597065',textTransform:'uppercase'},input:{borderWidth:1,borderColor:'#cbd9d0',borderRadius:11,padding:10,backgroundColor:'#fafcfb'},two:{flexDirection:'row',gap:8},spread:{flexDirection:'row',gap:8,justifyContent:'space-between'},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{backgroundColor:'#173f2d',paddingHorizontal:11,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},quiet:{backgroundColor:'#edf3ef'},actionText:{fontWeight:'900',fontSize:11,color:'#fff'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:10,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'800',color:'#345443'},chipTextOn:{color:'#fff'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:8,paddingVertical:5,alignSelf:'flex-start'},pillText:{fontSize:9,fontWeight:'900',color:'#31533f'},toggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},value:{fontWeight:'900',color:'#173f2d'},empty:{backgroundColor:'#eef3f0',padding:14,borderRadius:15}});
