import { Link,router } from 'expo-router';
import { useEffect,useMemo,useState,type Dispatch,type SetStateAction } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentFleetBusinessId } from '../services/control';
import { applyFleetOnboarding,getFleetOnboardingCatalog,getFleetOnboardingGate,getFleetOnboardingState,previewFleetOnboarding } from '../services/onboarding';

const BUSINESS_TYPES=[['logistics_delivery','Logistics / delivery'],['field_service','Field service'],['healthcare_public','Mobile care / public service'],['multi_location_chain','Multi-location operator'],['fuel_travel','Travel / roadside'],['other','Other']] as const;
const GOALS=[['route_efficiency','Improve route efficiency'],['workforce_wellbeing','Support mobile workers'],['service_verification','Verify field service'],['reduce_downtime','Reduce restroom downtime'],['multi_location_consistency','Improve multi-location consistency'],['partner_network','Build partner networks'],['multi_market_roi','Measure multi-market ROI']] as const;
const CUSTOMER_PROFILES=[['mobile_workforce','Mobile workforce'],['employees','Employees'],['customers_only','Customers / clients'],['general_public','General public'],['partners_mixed','Partners / mixed']] as const;
const ACCESS_MODELS=[['public','Public access'],['customer_only','Customer-only'],['employee_only','Employee-only'],['restricted','Restricted'],['mixed','Mixed']] as const;
const TRAFFIC_PATTERNS=[['route_based','Route-based work'],['scheduled','Scheduled jobs'],['steady','Steady operations'],['commuter','Commuter peaks'],['event_peak','Event / surge'],['seasonal','Seasonal']] as const;
const PAIN_POINTS=[['route_delays','Route delays / detours'],['workforce_stop_access','Workers struggle to find good stops'],['restroom_downtime','Restroom downtime'],['cleanliness_inconsistency','Inconsistent conditions'],['multi_market_visibility','Poor cross-market visibility'],['weak_reviews','Weak customer feedback']] as const;
const QR_INTENTS=[['service_proof','Service verification'],['check_in','Verified check-ins'],['review','Verified reviews'],['rewards','Rewards / contests'],['offer','Promotions / offers']] as const;
const SUCCESS_METRICS=[['route_efficiency','Route efficiency'],['worker_wellbeing','Worker wellbeing'],['response_time','Exception response time'],['restroom_uptime','Restroom uptime'],['verified_visits','Verified stops'],['partner_roi','Partner / portfolio ROI']] as const;
const REPORTING=[['live','Live dashboard'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly']] as const;
const TEAM_FOCUS=[['dispatch','Dispatch / field ops'],['operations','Operations'],['facilities','Facilities'],['owner','Owner / GM'],['analytics','Analytics'],['executive','Executive'],['customer_experience','Customer experience']] as const;

export default function FleetOnboarding(){
 const[businessId,setBusinessId]=useState(''),[businessType,setBusinessType]=useState('logistics_delivery'),[goals,setGoals]=useState<string[]>(['route_efficiency','workforce_wellbeing','service_verification']),[locations,setLocations]=useState('1'),[workers,setWorkers]=useState('25'),[markets,setMarkets]=useState('1'),[catalog,setCatalog]=useState<any>(null),[gate,setGate]=useState<any>(null),[preview,setPreview]=useState<any>(null),[applied,setApplied]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Fleet setup…');
 const[customerProfile,setCustomerProfile]=useState('mobile_workforce'),[accessModel,setAccessModel]=useState('mixed'),[trafficPattern,setTrafficPattern]=useState('route_based'),[painPoints,setPainPoints]=useState<string[]>(['route_delays','workforce_stop_access']),[qrIntent,setQrIntent]=useState<string[]>(['service_proof','check_in']),[successMetrics,setSuccessMetrics]=useState<string[]>(['route_efficiency','worker_wellbeing']),[reportingCadence,setReportingCadence]=useState('live'),[teamFocus,setTeamFocus]=useState<string[]>(['dispatch','operations']);
 const scale=useMemo(()=>({locations:Math.max(0,Number(locations)||0),mobile_workers:Math.max(0,Number(workers)||0),markets:Math.max(0,Number(markets)||0)}),[locations,workers,markets]);
 const answers=useMemo(()=>({customer_profile:customerProfile,access_model:accessModel,traffic_pattern:trafficPattern,pain_points:painPoints,qr_intent:qrIntent,success_metrics:successMetrics,reporting_cadence:reportingCadence,team_focus:teamFocus}),[customerProfile,accessModel,trafficPattern,painPoints,qrIntent,successMetrics,reportingCadence,teamFocus]);

 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const[c,stateRaw,g]=await Promise.all([getFleetOnboardingCatalog(),getFleetOnboardingState(id).catch(()=>({})),getFleetOnboardingGate(id).catch(()=>null)]);const state:any=stateRaw||{},saved:any=state.answers||{};setCatalog(c);setGate(g);if(state.business_type)setBusinessType(String(state.business_type));if(Array.isArray(state.goals)&&state.goals.length)setGoals(state.goals.map(String));if(state.scale){setLocations(String(state.scale.locations??1));setWorkers(String(state.scale.mobile_workers??25));setMarkets(String(state.scale.markets??1));}if(saved.customer_profile)setCustomerProfile(String(saved.customer_profile));if(saved.access_model)setAccessModel(String(saved.access_model));if(saved.traffic_pattern)setTrafficPattern(String(saved.traffic_pattern));if(Array.isArray(saved.pain_points))setPainPoints(saved.pain_points.map(String));if(Array.isArray(saved.qr_intent))setQrIntent(saved.qr_intent.map(String));if(Array.isArray(saved.success_metrics))setSuccessMetrics(saved.success_metrics.map(String));if(saved.reporting_cadence)setReportingCadence(String(saved.reporting_cadence));if(Array.isArray(saved.team_focus))setTeamFocus(saved.team_focus.map(String));if(state.preview&&Object.keys(state.preview).length)setPreview(state.preview);setMessage(g?.required?'This new Fleet business must complete onboarding before dispatch and operations unlock.':'')}catch(e:any){setMessage(e?.message||'Fleet onboarding unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const toggle=(setter:Dispatch<SetStateAction<string[]>>,id:string)=>{setter(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);setPreview(null);setApplied(null)};
 async function recommend(){if(!goals.length)return setMessage('Choose at least one result.');setBusy(true);try{setPreview(await previewFleetOnboarding(businessId,businessType,goals,scale,answers));setMessage('Fleet recommendation ready.')}catch(e:any){setMessage(e?.message||'Recommendation failed.')}finally{setBusy(false)}}
 async function apply(){if(gate&&!gate.can_complete)return setMessage('An owner or admin must complete mandatory onboarding.');setBusy(true);try{const result=await applyFleetOnboarding(businessId,businessType,goals,scale,answers);setApplied(result);setPreview(result.preview||preview);setGate(await getFleetOnboardingGate(businessId));setMessage('Fleet business setup completed. Real vehicles, drivers and routes remain yours to add.');router.replace('/')}catch(e:any){setMessage(e?.message||'Fleet setup could not be completed.')}finally{setBusy(false)}}
 const goalDetails=new Map((catalog?.goals||[]).map((g:any)=>[String(g.id),g]));

 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.kicker}>{gate?.required?'REQUIRED FLEET ONBOARDING':'FLEET ONBOARDING'}</Text><Text style={s.title}>Build Fleet around the operation you actually run.</Text><Text style={s.body}>Kleenest uses workforce, access, traffic, pain points, metrics and team ownership to target dispatch, stop intelligence, exceptions and reporting.</Text></View>
  {gate?.required?<View style={s.required}><Text style={s.section}>Complete setup to unlock Fleet</Text><Text style={s.meta}>The same versioned Business onboarding profile is shared across Business and Fleet.</Text></View>:null}
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <Card title="1 · Operation type"><Choice rows={BUSINESS_TYPES} value={businessType} setValue={setBusinessType}/></Card>
  <Card title="2 · Who is moving through the network?"><Choice rows={CUSTOMER_PROFILES} value={customerProfile} setValue={setCustomerProfile}/><Text style={s.sub}>Access model</Text><Choice rows={ACCESS_MODELS} value={accessModel} setValue={setAccessModel}/><Text style={s.sub}>Traffic pattern</Text><Choice rows={TRAFFIC_PATTERNS} value={trafficPattern} setValue={setTrafficPattern}/></Card>
  <Card title="3 · Operating scale"><NumberField label="Locations" value={locations} onChange={setLocations}/><NumberField label="Mobile workers" value={workers} onChange={setWorkers}/><NumberField label="Cities / markets" value={markets} onChange={setMarkets}/></Card>
  <Card title="4 · Operational pain points"><Multi rows={PAIN_POINTS} selected={painPoints} toggle={id=>toggle(setPainPoints,id)}/></Card>
  <Card title="5 · Results you need">{GOALS.map(([id,label])=>{const detail:any=goalDetails.get(id);return <Pressable key={id} onPress={()=>toggle(setGoals,id)} style={[s.goal,goals.includes(id)&&s.goalOn]}><Text style={[s.goalTitle,goals.includes(id)&&s.goalTitleOn]}>{label}</Text><Text style={[s.meta,goals.includes(id)&&{color:'#dce9e2'}]}>{detail?.detail||''}</Text></Pressable>})}</Card>
  <Card title="6 · QR and stop actions"><Multi rows={QR_INTENTS} selected={qrIntent} toggle={id=>toggle(setQrIntent,id)}/></Card>
  <Card title="7 · Success metrics"><Multi rows={SUCCESS_METRICS} selected={successMetrics} toggle={id=>toggle(setSuccessMetrics,id)}/><Text style={s.sub}>Reporting cadence</Text><Choice rows={REPORTING} value={reportingCadence} setValue={setReportingCadence}/></Card>
  <Card title="8 · Team ownership"><Multi rows={TEAM_FOCUS} selected={teamFocus} toggle={id=>toggle(setTeamFocus,id)}/></Card>
  <Pressable disabled={busy||!goals.length} onPress={recommend} style={[s.primary,(busy||!goals.length)&&s.disabled]}><Text style={s.primaryText}>Build targeted Fleet experience</Text></Pressable>
  {preview?<View style={s.card}><Text style={s.kickerDark}>TARGETED EXPERIENCE</Text><Text style={s.recommend}>{String(preview?.experience?.headline||'Fleet operating plan')}</Text><View style={s.tierBox}><Text style={s.kickerDark}>FLEET COMMERCIAL PATH</Text><Text style={s.tierName}>{tierDisplay(String(preview.recommended_tier||preview.current_plan||'fleet'))}</Text><Text style={s.meta}>{String(preview.tier_reason||'Fleet is a first-class tier and can also be added to Growth or Enterprise.')}</Text><Text style={s.fleetLine}>$75/month · 50 Premium users · Business Growth tools + Fleet-specific tools.</Text>{(preview.recommended_addons||[]).length?<Text style={s.fleetLine}>Add-ons: {(preview.recommended_addons||[]).map(titleCase).join(' + ')}</Text>:null}</View>{preview.enterprise_quote?<View style={s.enterpriseBox}><Text style={s.kickerDark}>ENTERPRISE PRICING</Text><Text style={s.tierName}>{money(preview.enterprise_quote.monthly_price_cents)}/month</Text><Text style={s.meta}>Band: {preview.enterprise_quote.band_locations||'250+'} locations · $1,500 onboarding. Fleet can stay enabled when moving to Enterprise.</Text></View>:null}{(preview.capabilities||[]).map((cap:any)=><View key={cap.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{cap.label}</Text><Text style={s.meta}>{cap.product==='fleet'?'FLEET TIER / ADD-ON':String(cap.product).toUpperCase()}</Text></View><Text style={s.badge}>{cap.available?'READY':'OFFER'}</Text></View>)}<Pressable onPress={apply} disabled={busy||Boolean(gate&&!gate.can_complete)} style={[s.primary,(busy||Boolean(gate&&!gate.can_complete))&&s.disabled]}><Text style={s.primaryText}>Complete Fleet setup</Text></Pressable></View>:null}
  {applied?<View style={s.done}><Text style={s.section}>Created</Text><Text style={s.meta}>{(applied.created||[]).join(', ')||'No new starter objects needed.'}</Text><Text style={s.meta}>Operational assets are never fabricated in real workspaces.</Text></View>:null}
  {!gate?.required?<View style={s.links}><Link href="/demo" style={s.link}>Run Fleet demo</Link><Link href="/assets" style={s.link}>Add real assets</Link><Link href="/planner" style={s.link}>Build first route</Link></View>:null}
 </ScrollView>
}
function titleCase(value:string){return value?value.charAt(0).toUpperCase()+value.slice(1).toLowerCase():'Fleet'}
function tierDisplay(value:string){const v=value.toLowerCase();return v==='enterprise'?'Business Enterprise':v==='growth'?'Business Growth':v==='standard'?'Business Standard':'Fleet'}
function money(cents:any){return Number.isFinite(Number(cents))?'$'+Math.round(Number(cents)/100).toLocaleString():'Custom'}
function Card({title,children}:{title:string;children:any}){return <View style={s.card}><Text style={s.section}>{title}</Text>{children}</View>}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function Choice({rows,value,setValue}:{rows:ReadonlyArray<readonly [string,string]>;value:string;setValue:(v:string)=>void}){return <View style={s.chips}>{rows.map(([id,label])=><Chip key={id} label={label} active={value===id} onPress={()=>setValue(id)}/>)}</View>}
function Multi({rows,selected,toggle}:{rows:readonly(readonly[string,string])[];selected:string[];toggle:(v:string)=>void}){return <View style={s.chips}>{rows.map(([id,label])=><Chip key={id} label={label} active={selected.includes(id)} onPress={()=>toggle(id)}/>)}</View>}
function NumberField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={s.numberRow}><Text style={[s.rowTitle,{flex:1}]}>{label}</Text><TextInput keyboardType="number-pad" value={value} onChangeText={onChange} style={s.number}/></View>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},kickerDark:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#587066'},title:{fontSize:28,lineHeight:32,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'800',color:'#596b61'},required:{backgroundColor:'#fff3ce',borderRadius:18,padding:15,gap:6,borderWidth:1,borderColor:'#e7d291'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},section:{fontSize:19,fontWeight:'900',color:'#102218'},sub:{fontSize:11,fontWeight:'900',textTransform:'uppercase',letterSpacing:.5,color:'#587066',marginTop:3},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:11,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:'#dbe5de'},chipOn:{backgroundColor:'#173f2d',borderColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'900',color:'#31533f'},chipTextOn:{color:'#fff'},goal:{padding:11,borderRadius:13,backgroundColor:'#f5f8f6',borderWidth:1,borderColor:'#dbe5de'},goalOn:{backgroundColor:'#173f2d'},goalTitle:{fontWeight:'900',color:'#20382a'},goalTitleOn:{color:'#fff'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},numberRow:{flexDirection:'row',alignItems:'center',gap:10},number:{width:76,borderWidth:1,borderColor:'#cbd9d0',borderRadius:10,padding:9,textAlign:'center'},rowTitle:{fontSize:13,fontWeight:'900',color:'#20382a'},primary:{backgroundColor:'#173f2d',padding:13,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},recommend:{fontSize:20,fontWeight:'900',color:'#102218'},tierBox:{backgroundColor:'#eef5f0',borderRadius:15,padding:12,gap:4,borderWidth:1,borderColor:'#cfe1d5'},enterpriseBox:{backgroundColor:'#f8f3e8',borderRadius:15,padding:12,gap:4,borderWidth:1,borderColor:'#ead9b3'},tierName:{fontSize:20,fontWeight:'900',color:'#173f2d'},fleetLine:{fontSize:11,fontWeight:'900',color:'#173f2d'},row:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:'#edf1ee',paddingVertical:7},badge:{fontSize:9,fontWeight:'900',backgroundColor:'#e9f2ec',paddingHorizontal:8,paddingVertical:5,borderRadius:999,color:'#31533f'},done:{backgroundColor:'#eaf4ed',borderRadius:18,padding:15,gap:7},links:{flexDirection:'row',flexWrap:'wrap',gap:8},link:{backgroundColor:'#edf3ef',color:'#173f2d',fontWeight:'900',paddingHorizontal:11,paddingVertical:9,borderRadius:999}});
