import { Link } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { currentFleetBusinessId } from '../services/control';
import { applyFleetOnboarding,getFleetOnboardingCatalog,getFleetOnboardingState,previewFleetOnboarding } from '../services/onboarding';

const BUSINESS_TYPES=[['logistics_delivery','Logistics / delivery'],['field_service','Field service'],['healthcare_public','Mobile care / public service'],['multi_location_chain','Multi-location operator'],['fuel_travel','Travel / roadside'],['other','Other']] as const;
const GOALS=[['route_efficiency','Improve route efficiency'],['workforce_wellbeing','Support mobile workers'],['service_verification','Verify field service'],['reduce_downtime','Reduce restroom downtime'],['multi_location_consistency','Improve multi-location consistency'],['partner_network','Build partner networks'],['multi_market_roi','Measure multi-market ROI']] as const;

export default function FleetOnboarding(){
 const[businessId,setBusinessId]=useState(''),[businessType,setBusinessType]=useState('logistics_delivery'),[goals,setGoals]=useState<string[]>(['route_efficiency','workforce_wellbeing','service_verification']),[locations,setLocations]=useState('1'),[workers,setWorkers]=useState('25'),[markets,setMarkets]=useState('1'),[catalog,setCatalog]=useState<any>(null),[preview,setPreview]=useState<any>(null),[applied,setApplied]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Fleet setup…');
 const scale=useMemo(()=>({locations:Math.max(0,Number(locations)||0),mobile_workers:Math.max(0,Number(workers)||0),markets:Math.max(0,Number(markets)||0)}),[locations,workers,markets]);
 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const[c,stateRaw]=await Promise.all([getFleetOnboardingCatalog(),getFleetOnboardingState(id).catch(()=>({}))]);const state:any=stateRaw||{};setCatalog(c);if(state?.business_type)setBusinessType(String(state.business_type));if(Array.isArray(state?.goals)&&state.goals.length)setGoals(state.goals.map(String));if(state?.scale){setLocations(String(state.scale.locations??1));setWorkers(String(state.scale.mobile_workers??25));setMarkets(String(state.scale.markets??1));}setMessage('')}catch(e:any){setMessage(e?.message||'Fleet onboarding unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 function toggle(id:string){setPreview(null);setApplied(null);setGoals(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function recommend(){if(!goals.length)return setMessage('Choose at least one result.');setBusy(true);try{setPreview(await previewFleetOnboarding(businessId,businessType,goals,scale));setMessage('Fleet recommendation ready.')}catch(e:any){setMessage(e?.message||'Recommendation failed.')}finally{setBusy(false)}}
 async function apply(){setBusy(true);try{const result=await applyFleetOnboarding(businessId,businessType,goals,scale);setApplied(result);setPreview(result.preview||preview);setMessage('Available Fleet setup created. Operational assets remain yours to add with real names and assignments.')}catch(e:any){setMessage(e?.message||'Fleet setup could not be created.')}finally{setBusy(false)}}
 const goalDetails=new Map((catalog?.goals||[]).map((g:any)=>[String(g.id),g]));
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.kicker}>FLEET ONBOARDING</Text><Text style={s.title}>Start with the operation, not a feature checklist.</Text><Text style={s.body}>Tell Kleenest what mobile work you run and what results matter. Fleet setup never invents drivers, vehicles or routes in a real workspace.</Text></View>
  {message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.card}><Text style={s.section}>What kind of operation?</Text><View style={s.chips}>{BUSINESS_TYPES.map(([id,label])=><Chip key={id} label={label} active={businessType===id} onPress={()=>{setBusinessType(id);setPreview(null)}}/>)}</View></View>
  <View style={s.card}><Text style={s.section}>What results do you need?</Text>{GOALS.map(([id,label])=>{const detail:any=goalDetails.get(id);return <Pressable key={id} onPress={()=>toggle(id)} style={[s.goal,goals.includes(id)&&s.goalOn]}><Text style={[s.goalTitle,goals.includes(id)&&s.goalTitleOn]}>{label}</Text><Text style={[s.meta,goals.includes(id)&&{color:'#dce9e2'}]}>{detail?.detail||''}</Text></Pressable>})}</View>
  <View style={s.card}><Text style={s.section}>Operating scale</Text><NumberField label="Locations" value={locations} onChange={setLocations}/><NumberField label="Mobile workers" value={workers} onChange={setWorkers}/><NumberField label="Cities / markets" value={markets} onChange={setMarkets}/></View>
  <Pressable disabled={busy||!goals.length} onPress={recommend} style={[s.primary,(busy||!goals.length)&&s.disabled]}><Text style={s.primaryText}>Build Fleet recommendation</Text></Pressable>
  {preview?<View style={s.card}><Text style={s.kickerDark}>RECOMMENDED</Text><Text style={s.recommend}>{(preview.recommended_products||[]).join(' + ').toUpperCase()}</Text><Text style={s.meta}>{preview.upgrade_required?'Some requested outcomes require an additional Kleenest product.':'Requested outcomes are available on this workspace.'}</Text>{(preview.capabilities||[]).map((cap:any)=><View key={cap.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{cap.label}</Text><Text style={s.meta}>{String(cap.product).toUpperCase()}</Text></View><Text style={s.badge}>{cap.available?'READY':'OFFER'}</Text></View>)}<Pressable onPress={apply} disabled={busy} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>Create available Fleet setup</Text></Pressable></View>:null}
  {applied?<View style={s.done}><Text style={s.section}>Created</Text><Text style={s.meta}>{(applied.created||[]).join(', ')||'No new starter objects needed.'}</Text><Text style={s.section}>Still offered</Text><Text style={s.meta}>{(applied.offered||[]).join(', ')||'Nothing additional required.'}</Text>{(applied.next_steps||[]).map((x:string,i:number)=><Text key={i} style={s.meta}>• {x}</Text>)}</View>:null}
  <View style={s.links}><Link href="/demo" style={s.link}>Run Fleet demo</Link><Link href="/assets" style={s.link}>Add real assets</Link><Link href="/planner" style={s.link}>Build first route</Link></View>
 </ScrollView>
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
function NumberField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={s.numberRow}><Text style={[s.rowTitle,{flex:1}]}>{label}</Text><TextInput keyboardType="number-pad" value={value} onChangeText={onChange} style={s.number}/></View>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f3f6f4',paddingBottom:70},hero:{backgroundColor:'#173f2d',borderRadius:24,padding:20,gap:7},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#c8ead7'},kickerDark:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#587066'},title:{fontSize:28,lineHeight:32,fontWeight:'900',color:'#fff'},body:{fontSize:14,lineHeight:21,color:'#deebe4'},message:{fontWeight:'800',color:'#596b61'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,gap:9,borderWidth:1,borderColor:'#dbe5de'},section:{fontSize:19,fontWeight:'900',color:'#102218'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:11,paddingVertical:9,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'900',color:'#31533f'},chipTextOn:{color:'#fff'},goal:{padding:11,borderRadius:13,backgroundColor:'#f5f8f6',borderWidth:1,borderColor:'#dbe5de'},goalOn:{backgroundColor:'#173f2d'},goalTitle:{fontWeight:'900',color:'#20382a'},goalTitleOn:{color:'#fff'},meta:{fontSize:12,lineHeight:18,color:'#65756b'},numberRow:{flexDirection:'row',alignItems:'center',gap:10},number:{width:76,borderWidth:1,borderColor:'#cbd9d0',borderRadius:10,padding:9,textAlign:'center'},rowTitle:{fontSize:13,fontWeight:'900',color:'#20382a'},primary:{backgroundColor:'#173f2d',padding:13,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},recommend:{fontSize:22,fontWeight:'900',color:'#102218'},row:{flexDirection:'row',alignItems:'center',gap:8,borderTopWidth:1,borderTopColor:'#edf1ee',paddingVertical:7},badge:{fontSize:9,fontWeight:'900',backgroundColor:'#e9f2ec',paddingHorizontal:8,paddingVertical:5,borderRadius:999,color:'#31533f'},done:{backgroundColor:'#eaf4ed',borderRadius:18,padding:15,gap:7},links:{flexDirection:'row',flexWrap:'wrap',gap:8},link:{backgroundColor:'#edf3ef',color:'#173f2d',fontWeight:'900',paddingHorizontal:11,paddingVertical:9,borderRadius:999}});
