import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { currentFleetBusinessId,getFleetInventory } from '../services/control';
import { disableFleetLiveNetwork,enableFleetLiveNetwork,getFleetLiveNetworkStatus,registerFleetPush } from '../services/geofence';
import { listBusinessLocations,listMonitoredLocations,removeMonitoredLocation,setMonitoredLocation } from '../services/signals';
type Row=Record<string,any>;
export default function Signals(){
 const[businessId,setBusinessId]=useState(''),[locations,setLocations]=useState<Row[]>([]),[monitored,setMonitored]=useState<Row[]>([]),[routes,setRoutes]=useState<Row[]>([]),[routeId,setRouteId]=useState(''),[locationId,setLocationId]=useState(''),[status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Live Network…');
 async function load(){setBusy(true);try{const id=businessId||await currentFleetBusinessId();setBusinessId(id);const[l,m,inv,live]=await Promise.all([listBusinessLocations(id),listMonitoredLocations(id),getFleetInventory(id),getFleetLiveNetworkStatus()]);setLocations(l);setMonitored(m);setRoutes(inv.routes||[]);setStatus(live);if(!routeId&&inv.routes?.[0]?.id)setRouteId(String(inv.routes[0].id));if(!locationId&&l[0]?.id)setLocationId(String(l[0].id));setMessage('')}catch(e:any){setMessage(e?.message||'Fleet signals unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function run(fn:()=>Promise<unknown>,success:string){setBusy(true);try{await fn();setMessage(success);await load()}catch(e:any){setMessage(e?.message||'Live Network action failed.')}finally{setBusy(false)}}
 const monitoredIds=new Set(monitored.map(r=>String(r.location_id||r.id||'')));
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={s.page}>
  <View style={s.hero}><Text style={s.eyebrow}>LIVE NETWORK + SIGNALS</Text><Text style={s.title}>Control where Fleet listens.</Text><Text style={s.copy}>Choose monitored locations, run route geofences in the background and keep push alerts connected to the same operational event stream.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
  <View style={s.metrics}><Metric label="Monitored locations" value={monitored.length}/><Metric label="Routes" value={routes.length}/><Metric label="Geofence runtime" value={status?.registered?'ON':'OFF'}/><Metric label="Location services" value={status?.services?'ON':'OFF'}/></View>
  <View style={s.card}><Text style={s.cardTitle}>Live Network route</Text><Text style={s.meta}>Select a route with canonical stops. Fleet will register platform geofences and native push for background enter/exit alerts.</Text><View style={s.chips}>{routes.map(r=><Pressable key={String(r.id)} onPress={()=>setRouteId(String(r.id))} style={[s.chip,routeId===String(r.id)&&s.chipOn]}><Text style={[s.chipText,routeId===String(r.id)&&s.chipTextOn]}>{String(r.name||'Route')} · {String(r.status||'planned')}</Text></Pressable>)}</View><View style={s.actions}><Action label="Enable Live Network" disabled={busy||!routeId} onPress={()=>run(()=>enableFleetLiveNetwork(businessId,routeId),'Live Network enabled for selected route.')}/><Action quiet label="Stop Live Network" disabled={busy||!status?.registered} onPress={()=>run(()=>disableFleetLiveNetwork(),'Live Network stopped.')}/><Action quiet label="Register Fleet push" disabled={busy} onPress={()=>run(()=>registerFleetPush(),'Fleet push registration refreshed.')}/></View><Text style={s.meta}>Foreground permission: {String(status?.foreground||'unknown')} · Background: {String(status?.background||'unknown')}</Text></View>
  <View style={s.card}><Text style={s.cardTitle}>Location monitoring</Text><Text style={s.meta}>Monitoring promotes a location into Fleet opportunity, exception and intelligence workflows. Pick from canonical Business locations—no UUID entry required.</Text><View style={s.chips}>{locations.filter(r=>!monitoredIds.has(String(r.id||r.location_id))).map(r=><Pressable key={String(r.id||r.location_id)} onPress={()=>setLocationId(String(r.id||r.location_id))} style={[s.chip,locationId===String(r.id||r.location_id)&&s.chipOn]}><Text style={[s.chipText,locationId===String(r.id||r.location_id)&&s.chipTextOn]}>{String(r.name||r.location_name||'Location')}</Text></Pressable>)}</View><Action label="Monitor location" disabled={busy||!locationId||monitoredIds.has(locationId)} onPress={()=>run(()=>setMonitoredLocation(businessId,locationId,true),'Location added to Fleet monitoring.')}/></View>
  <Text style={s.section}>Currently monitored</Text>{monitored.length?monitored.map((r,i)=>{const id=String(r.location_id||r.id||'');return <View key={id||String(i)} style={s.card}><View style={s.spread}><View style={{flex:1}}><Text style={s.cardTitle}>{String(r.location_name||r.name||locations.find(l=>String(l.id)===id)?.name||'Monitored location')}</Text><Text style={s.meta}>{String(r.status||'active')} · {String(r.reason||'Fleet signal monitoring')}</Text></View><Pill label="MONITORED"/></View><Action quiet label="Stop monitoring" disabled={busy||!id} onPress={()=>run(()=>removeMonitoredLocation(businessId,id),'Location removed from Fleet monitoring.')}/></View>}):<View style={s.empty}><Text style={s.meta}>No locations are currently monitored.</Text></View>}
 </ScrollView>}
function Metric({label,value}:{label:string;value:string|number}){return <View style={s.metric}><Text style={s.metricValue}>{String(value)}</Text><Text style={s.meta}>{label}</Text></View>}function Pill({label}:{label:string}){return <View style={s.pill}><Text style={s.pillText}>{label}</Text></View>}function Action({label,onPress,disabled,quiet=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;quiet?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,quiet&&s.quiet,disabled&&{opacity:.45}]}><Text style={[s.actionText,quiet&&{color:'#244d39'}]}>{label}</Text></Pressable>}
const s=StyleSheet.create({page:{padding:18,gap:12,paddingBottom:70,backgroundColor:'#f3f6f4'},hero:{backgroundColor:'#173f2d',borderRadius:23,padding:18,gap:7},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#c8ead7'},title:{fontSize:27,fontWeight:'900',color:'#fff'},copy:{color:'#dce9e2',lineHeight:20},message:{fontWeight:'800',color:'#5d5140'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:'46%',flexGrow:1,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:'#dbe5de'},metricValue:{fontSize:21,fontWeight:'900',color:'#173f2d'},meta:{fontSize:12,lineHeight:18,color:'#66766e'},card:{backgroundColor:'#fff',padding:14,borderRadius:17,borderWidth:1,borderColor:'#dbe5de',gap:9},cardTitle:{fontSize:17,fontWeight:'900',color:'#102218'},section:{fontSize:20,fontWeight:'900',color:'#102218'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:'#edf3ef',paddingHorizontal:10,paddingVertical:8,borderRadius:999},chipOn:{backgroundColor:'#173f2d'},chipText:{fontSize:11,fontWeight:'800',color:'#345443'},chipTextOn:{color:'#fff'},actions:{flexDirection:'row',flexWrap:'wrap',gap:7},action:{backgroundColor:'#173f2d',paddingHorizontal:11,paddingVertical:9,borderRadius:999,alignSelf:'flex-start'},quiet:{backgroundColor:'#edf3ef'},actionText:{fontWeight:'900',fontSize:11,color:'#fff'},spread:{flexDirection:'row',gap:8,justifyContent:'space-between'},pill:{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:8,paddingVertical:5,alignSelf:'flex-start'},pillText:{fontSize:9,fontWeight:'900',color:'#31533f'},empty:{backgroundColor:'#eef3f0',padding:14,borderRadius:15}});
