import { useState,type ReactNode } from 'react';
import { Pressable,Text,View } from 'react-native';
import { usePlatformTheme } from '../services/theme';

export const osColors={ink:'#10261d',green:'#173f2d',mint:'#dcebe2',paper:'#f4f7f5',white:'#ffffff',muted:'#5e7066',border:'#d5e0d9',danger:'#8f2f2f',warning:'#8a5a18',good:'#1d6b43'};
export const osCard={backgroundColor:osColors.white,borderRadius:18,padding:15,borderWidth:1,borderColor:osColors.border,gap:7} as const;
export function useOSCardStyle(){const theme=usePlatformTheme();return {...osCard,backgroundColor:theme.surface,borderColor:theme.line} as const;}

export function OSHero({eyebrow,title,body,children}:{eyebrow:string;title:string;body:string;children?:ReactNode}){const theme=usePlatformTheme();return <View style={{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:osColors.ink,borderWidth:1,borderColor:theme.resolved==='dark'?theme.line:osColors.ink,borderRadius:16,padding:12,gap:4}}><Text style={{color:'#bde4cf',fontWeight:'900',letterSpacing:1.2,fontSize:9}}>{eyebrow}</Text><Text style={{color:'white',fontSize:21,lineHeight:25,fontWeight:'900'}}>{title}</Text><Text style={{color:'#dce8e1',fontSize:12,lineHeight:18}}>{body}</Text>{children}</View>}

export function StatusPill({label,tone='neutral'}:{label:string;tone?:'good'|'warning'|'danger'|'neutral'}){const background=tone==='good'?'#e1f3e9':tone==='warning'?'#f7ecd8':tone==='danger'?'#f7e2e2':'#eef2ef';const color=tone==='good'?osColors.good:tone==='warning'?osColors.warning:tone==='danger'?osColors.danger:osColors.muted;return <View style={{alignSelf:'flex-start',borderRadius:999,paddingHorizontal:9,paddingVertical:5,backgroundColor:background}}><Text style={{color,fontWeight:'900',fontSize:11}}>{label}</Text></View>}

export function HealthCard({label,value,detail,tone='neutral',onPress}:{label:string;value:string|number;detail?:string;tone?:'good'|'warning'|'danger'|'neutral';onPress?:()=>void}){const theme=usePlatformTheme();const card=useOSCardStyle();const body=<View style={{...card,minWidth:145,flexGrow:1}}><StatusPill label={label} tone={tone}/><Text style={{fontSize:25,fontWeight:'900',color:theme.ink}}>{String(value)}</Text>{detail?<Text style={{color:theme.muted,lineHeight:18}}>{detail}</Text>:null}</View>;return onPress?<Pressable onPress={onPress} style={{flexGrow:1,flexBasis:145}}>{body}</Pressable>:body}

export function SectionHeader({title,body,actionLabel,onAction}:{title:string;body?:string;actionLabel?:string;onAction?:()=>void}){const theme=usePlatformTheme();return <View style={{gap:4}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8}}><Text style={{fontSize:19,fontWeight:'900',color:theme.ink,flex:1}}>{title}</Text>{actionLabel&&onAction?<Pressable onPress={onAction}><Text style={{fontWeight:'900',color:theme.accent}}>{actionLabel}</Text></Pressable>:null}</View>{body?<Text style={{color:theme.muted,lineHeight:19}}>{body}</Text>:null}</View>}

export function DiagnosticDisclosure({title,value}:{title:string;value:unknown}){const[open,setOpen]=useState(false);const theme=usePlatformTheme();const card=useOSCardStyle();return <View style={card}><Pressable onPress={()=>setOpen(value=>!value)}><Text style={{fontWeight:'900',color:theme.accent}}>{open?'Hide':'Show'} {title}</Text></Pressable>{open?<Text selectable style={{fontFamily:'monospace',fontSize:11,color:theme.muted}}>{JSON.stringify(value,null,2)}</Text>:null}</View>}
