import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
const client=()=>getKleenestSupabaseClient();
async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data;}
export type OwnerAuthorization={authorized:boolean;role:string|null;is_admin:boolean;is_platform_owner:boolean;tier:'platform_owner'|'admin'|'none'};
export async function getOwnerAuthorization():Promise<OwnerAuthorization>{const value:any=(await rpc('admin_authorization_v1'))||{};const isPlatformOwner=Boolean(value.is_platform_owner),isAdmin=Boolean(value.is_admin);return{authorized:Boolean(value.authorized)||isPlatformOwner||isAdmin,role:typeof value.role==='string'?value.role:null,is_admin:isAdmin,is_platform_owner:isPlatformOwner,tier:isPlatformOwner?'platform_owner':isAdmin?'admin':'none'};}
export async function requirePlatformOwner(){const authorization=await getOwnerAuthorization();if(!authorization.authorized)throw new Error('Owner control-plane authority is required for this command.');return authorization;}
function asRows(data:unknown):any[]{if(Array.isArray(data))return data;if(data&&typeof data==='object'){const value=data as Record<string,unknown>;for(const key of['items','rows','users','results','reports'])if(Array.isArray(value[key]))return value[key] as any[];}return[];}
export async function searchOwnerUsers(query:string){const q=query.trim();if(!q)return[];return asRows(await rpc('admin_user_search',{p_query:q}));}
export async function setOwnerUserAccess(input:{userId:string;isAdmin:boolean;role:string;subscriptionTier:string;isBusinessUser:boolean;reason:string}){await requirePlatformOwner();return rpc('admin_set_user_access',{p_target_user_id:input.userId,p_is_admin:input.isAdmin,p_role:input.role,p_subscription_tier:input.subscriptionTier,p_is_business_user:input.isBusinessUser,p_reason:input.reason.trim()||'KleenestOS access update'});}
export async function getOwnerUserCapabilityHistory(userId:string){const{data,error}=await client().from('admin_capability_audit').select('id,admin_user_id,target_user_id,previous_state,new_state,reason,created_at').eq('target_user_id',userId).order('created_at',{ascending:false}).limit(50);if(error)throw error;return data||[];}
export async function getOwnerModerationQueues(){await requirePlatformOwner();const[reviewReports,userReports,aiReports,pendingBusinesses]=await Promise.all([client().rpc('admin_list_review_reports',{p_status:'pending'}),client().rpc('admin_list_user_safety_reports',{p_status:'open'}),client().rpc('admin_list_ai_response_reports',{p_status:'open'}),client().rpc('admin_list_pending_businesses')]);for(const result of[reviewReports,userReports,aiReports,pendingBusinesses])if(result.error)throw result.error;return{reviewReports:asRows(reviewReports.data),userReports:asRows(userReports.data),aiReports:asRows(aiReports.data),pendingBusinesses:asRows(pendingBusinesses.data)};}
export async function resolveOwnerReviewReport(input:{reportId:string;resolution:'dismiss'|'hide'|'restore';reason:string;reviewStatus?:string|null}){await requirePlatformOwner();return rpc('admin_resolve_review_report',{p_report_id:input.reportId,p_resolution:input.resolution,p_reason:input.reason.trim(),p_review_status:input.reviewStatus??null});}
export async function resolveOwnerUserSafetyReport(reportId:string,status:'reviewing'|'resolved'|'dismissed'){await requirePlatformOwner();return rpc('admin_resolve_user_safety_report',{p_report_id:reportId,p_status:status});}
export async function resolveOwnerAiResponseReport(reportId:string,status:'reviewing'|'resolved'|'dismissed',resolution=''){await requirePlatformOwner();return rpc('admin_resolve_ai_response_report',{p_report_id:reportId,p_status:status,p_resolution:resolution.trim()||null});}
export async function getOwnerProgressionPlatformSnapshot(){return(await rpc('owner_progression_platform_snapshot'))||{users_with_xp:0,xp_awarded:0,discoveries:0,on_site_discoveries:0,discovery_photos:0,active_objectives:0,objective_kinds:{},awards_by_action:[],recent_discoveries:[]};}
export async function getCapabilityCatalogBundle(){const[operational,crud,classifications,retirement,domainIssues,raw]=await Promise.all([rpc('admin_operational_capability_catalog'),rpc('admin_crud_capability_catalog'),rpc('capability_classification_summary'),rpc('capability_retirement_audit',{p_limit:100}),rpc('check_single_capability_per_domain'),rpc('admin_raw_schema_capability_audit')]);return{operational,crud,classifications,retirement,domainIssues,raw};}
export function runCapabilityAudit(){return rpc('run_capability_audit',{p_source:'kleenestos_mobile'});}
export async function getOwnerAuditBundle(){const end=new Date(),start=new Date(end.getTime()-86400000);const[run,raw,domains,activity]=await Promise.all([client().rpc('run_capability_audit',{p_source:'kleenestos_mobile'}),client().rpc('admin_raw_schema_capability_audit'),client().rpc('check_single_capability_per_domain'),client().rpc('admin_list_activity_events',{p_limit:100,p_from:start.toISOString(),p_to:end.toISOString()})]);for(const result of[run,raw,domains,activity])if(result.error)throw result.error;return{run:run.data,raw:raw.data,domains:domains.data,activity:activity.data};}
export async function ownerCrudList(resource:string,limit=50){if(!/^[-_a-z0-9]+$/.test(resource))throw new Error('Choose a valid canonical resource.');return rpc('admin_crud_gateway',{p_resource:resource,p_action:'list',p_id:null,p_payload:{limit:Math.min(Math.max(limit,1),100),order:'desc'}});}
export async function getOwnerOperationsBundle(){const end=new Date(),start=new Date(end.getTime()-86400000);const[overview,integrity,activity,reports,reviewReports,ingestion,push,nativePush,resources]=await Promise.all([client().rpc('admin_get_overview'),client().rpc('admin_data_integrity_summary'),client().rpc('admin_list_activity_events',{p_limit:100}),client().rpc('admin_list_reports'),client().rpc('admin_list_review_reports',{p_status:null}),client().rpc('admin_national_ingestion_status'),client().rpc('admin_notification_push_delivery_summary',{p_from:start.toISOString(),p_to:end.toISOString()}),client().rpc('admin_notification_native_push_delivery_health',{p_from:start.toISOString(),p_to:end.toISOString()}),client().rpc('admin_backend_resource_catalog')]);for(const result of[overview,integrity,activity,reports,reviewReports,ingestion,push,nativePush,resources])if(result.error)throw result.error;return{overview:overview.data,integrity:integrity.data,activity:activity.data,reports:reports.data,reviewReports:reviewReports.data,ingestion:ingestion.data,push:push.data,nativePush:nativePush.data,resources:resources.data};}
