import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
const client=()=>getKleenestSupabaseClient();async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data;}
export async function getBusinessCapabilityState(businessId:string){const[matrix,qualification,management,entitlement]=await Promise.allSettled([rpc('business_tier_capability_matrix',{p_business_id:businessId}),rpc('business_tier_qualification_snapshot',{p_business_id:businessId}),rpc('business_management_context',{p_business_id:businessId}),rpc('get_business_service_entitlement',{p_business_id:businessId})]);const v=(x:PromiseSettledResult<any>)=>x.status==='fulfilled'?x.value:null;return{matrix:v(matrix),qualification:v(qualification),management:v(management),entitlement:v(entitlement),partial:[matrix,qualification,management,entitlement].some(x=>x.status==='rejected')};}
export async function getBusinessProgression(businessId:string){return rpc('business_progression_engagement_snapshot',{p_business_id:businessId});}
export async function getEnterpriseLocationControls(businessId:string){const[configs,portfolio,comparison,opportunities]=await Promise.allSettled([rpc('enterprise_list_location_configs',{p_business_id:businessId}),rpc('enterprise_operational_portfolio_snapshot',{p_business_id:businessId}),rpc('enterprise_location_comparison_snapshot',{p_business_id:businessId,p_window_days:30}),rpc('enterprise_network_opportunity_snapshot',{p_business_id:businessId,p_window_days:30})]);const v=(x:PromiseSettledResult<any>)=>x.status==='fulfilled'?x.value:null;return{configs:v(configs),portfolio:v(portfolio),comparison:v(comparison),opportunities:v(opportunities),partial:[configs,portfolio,comparison,opportunities].some(x=>x.status==='rejected')};}
export function updateEnterpriseLocationConfig(businessId:string,locationId:string,config:Record<string,unknown>){return rpc('enterprise_update_location_config',{p_business_id:businessId,p_location_id:locationId,p_config:config});}
export function listEnterpriseLocationStaff(businessId:string,locationId:string){return rpc('enterprise_list_location_staff',{p_business_id:businessId,p_location_id:locationId});}
export function manageEnterpriseLocationStaff(businessId:string,locationId:string,userId:string,role:string,action:'add'|'update'|'remove',overrides:Record<string,unknown>={}){return rpc('enterprise_manage_location_staff',{p_business_id:businessId,p_location_id:locationId,p_user_id:userId,p_role:role,p_action:action,p_capability_overrides:overrides});}
export async function getEnterpriseEconomy(businessId:string){const[progression,opportunities,portfolio]=await Promise.allSettled([rpc('business_progression_engagement_snapshot',{p_business_id:businessId}),rpc('enterprise_intracompany_opportunities',{p_business_id:businessId,p_window_days:30}),rpc('enterprise_operational_portfolio_snapshot',{p_business_id:businessId})]);const v=(x:PromiseSettledResult<any>)=>x.status==='fulfilled'?x.value:null;return{progression:v(progression),opportunities:v(opportunities),portfolio:v(portfolio),partial:[progression,opportunities,portfolio].some(x=>x.status==='rejected')};}
