import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
const client=()=>getKleenestSupabaseClient();async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data;}
export async function listOwnedEnterpriseNetworks(businessId:string){const data=await rpc('enterprise_list_owned_networks',{p_business_id:businessId});return Array.isArray(data)?data:[];}
export async function listEnterprisePartnerBusinesses(businessId:string){const data=await rpc('enterprise_list_partner_businesses',{p_business_id:businessId});return Array.isArray(data)?data:[];}
export async function listEnterpriseNetworkCampaigns(networkId:string){const data=await rpc('enterprise_list_network_campaigns',{p_network_id:networkId});return Array.isArray(data)?data:[];}
export function createPartnerAllocation(networkId:string,partnerBusinessId:string,campaignId:string|null,input:{type:string;quantity:number;budgetCents:number;rationale?:string}){return rpc('create_partner_allocation',{p_network_id:networkId,p_partner_business_id:partnerBusinessId,p_campaign_id:campaignId,p_type:input.type,p_quantity:input.quantity,p_budget_cents:input.budgetCents,p_rationale:input.rationale??null});}
export const activatePartnerAllocation=(allocationId:string)=>rpc('activate_partner_allocation',{p_allocation_id:allocationId});
export async function getPartnerAllocationRoi(networkId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86400000);return rpc('get_partner_allocation_roi',{p_network_id:networkId,p_start:start.toISOString().slice(0,10),p_end:end.toISOString().slice(0,10)});}
export async function getPartnerNetworkBenchmark(networkId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86400000);return rpc('get_partner_network_benchmark',{p_network_id:networkId,p_start:start.toISOString().slice(0,10),p_end:end.toISOString().slice(0,10)});}
export function recordEnterpriseCampaignOutcome(campaignId:string,partnerBusinessId:string,input:{visits?:number;checkIns?:number;reviews?:number;preferredUses?:number;accessRedemptions?:number;promotionRedemptions?:number;attributedUsers?:number;pointsAwarded?:number}){return rpc('record_enterprise_partner_campaign_outcome',{p_campaign_id:campaignId,p_partner_business_id:partnerBusinessId,p_visits:input.visits??0,p_check_ins:input.checkIns??0,p_reviews:input.reviews??0,p_preferred_uses:input.preferredUses??0,p_access_redemptions:input.accessRedemptions??0,p_promotion_redemptions:input.promotionRedemptions??0,p_attributed_users:input.attributedUsers??0,p_points_awarded:input.pointsAwarded??0});}
