import { getKleenestSupabaseClient } from '@kleenest/mobile-core';

const client=()=>getKleenestSupabaseClient();
function windowArgs(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86_400_000);return{p_business_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()};}
export type IntelligenceSection={data:unknown;error:string|null};
export type GrowthIntelligenceBundle={authority:IntelligenceSection;cockpit:IntelligenceSection;growth:IntelligenceSection;assets:IntelligenceSection;benchmarks:IntelligenceSection;roi:IntelligenceSection;locations:IntelligenceSection;operations:IntelligenceSection;recommendations:IntelligenceSection;reverification:IntelligenceSection;history:IntelligenceSection;errors:string[]};
function section(result:PromiseSettledResult<{data:unknown;error:{message?:string}|null}>):IntelligenceSection{if(result.status==='rejected')return{data:null,error:result.reason instanceof Error?result.reason.message:String(result.reason)};if(result.value.error)return{data:null,error:result.value.error.message||'Intelligence request failed.'};return{data:result.value.data,error:null};}
export async function getGrowthIntelligenceBundle(businessId:string,days=30):Promise<GrowthIntelligenceBundle>{const args=windowArgs(businessId,days),calls=[client().rpc('get_business_intelligence_authority_bundle',args),client().rpc('business_growth_cockpit',{p_business_id:businessId,p_window_days:days}),client().rpc('business_growth_analytics',args),client().rpc('business_growth_asset_performance',args),client().rpc('business_benchmark_analytics',args),client().rpc('business_roi_analytics',args),client().rpc('business_location_intelligence',args),client().rpc('business_operations_inventory',{p_business_id:businessId}),client().rpc('business_restroom_prevention_recommendations',{p_business_id:businessId,p_days:Math.max(days,90)}),client().rpc('business_reverification_queue',{p_business_id:businessId}),client().rpc('business_growth_optimization_history',{p_business_id:businessId,p_limit:50})];const settled=await Promise.allSettled(calls),keys=['authority','cockpit','growth','assets','benchmarks','roi','locations','operations','recommendations','reverification','history'] as const,built=Object.fromEntries(keys.map((key,index)=>[key,section(settled[index] as PromiseSettledResult<{data:unknown;error:{message?:string}|null}>)])) as unknown as Omit<GrowthIntelligenceBundle,'errors'>,errors=keys.flatMap(key=>built[key].error?[`${key}: ${built[key].error}`]:[]);return{...built,errors};}
export async function buildBusinessReportPayload(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86_400_000),{data,error}=await client().rpc('reporting_build_payload',{p_scope_type:'business',p_scope_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()});if(error)throw new Error(error.message);if(!data||typeof data!=='object')throw new Error('Business reporting payload returned no data.');return data as Record<string,unknown>;}
