import { getKleenestSupabaseClient } from '@kleenest/mobile-core';

const client=()=>getKleenestSupabaseClient();
function windowArgs(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86_400_000);return{p_business_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()};}
async function rpc(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw new Error(`${name}: ${error.message}`);return data;}
export type BusinessParityBundle={analytics:Record<string,unknown>;funnels:Record<string,unknown>;partner:Record<string,unknown>;progression:Record<string,unknown>;leaderboards:Record<string,unknown>;operations:Record<string,unknown>;errors:string[]};
export async function getBusinessParityBundle(businessId:string,days=30):Promise<BusinessParityBundle>{const w=windowArgs(businessId,days),calls:[string,Promise<unknown>][]= [['visitors',rpc('business_visitors_analytics',w)],['reviews',rpc('business_review_analytics',w)],['promotions',rpc('business_promotion_analytics',w)],['campaigns',rpc('business_campaign_analytics',w)],['events',rpc('business_event_analytics',w)],['qr',rpc('business_qr_analytics',w)],['media',rpc('business_media_analytics',w)],['amenities',rpc('business_amenity_feedback_analytics',{...w,p_location_id:null})],['occupancy',rpc('business_occupancy_analytics',w)],['partners',rpc('business_partner_analytics',w)],['rewards',rpc('business_rewards_analytics',w)],['summary',rpc('business_summary_analytics',w)],['attribution',rpc('get_business_attribution_funnel',w)],['engagement',rpc('get_business_engagement_funnel',w)],['growthActions',rpc('get_business_growth_action_summary',{p_business_id:businessId})],['progression',rpc('business_progression_engagement_snapshot',{p_business_id:businessId})],['preferred',rpc('business_preferred_location_summary')],['businessLeaderboard',rpc('get_business_leaderboard',{p_metric:'check_ins',p_limit:25})],['crossTierLeaderboard',rpc('get_cross_tier_leaderboard',{p_leaderboard_key:'business_engagement',p_limit:25})],['reverification',rpc('business_reverification_operations',{p_business_id:businessId})],['remediation',rpc('business_restroom_remediation_operations',{p_business_id:businessId})],['reliability',rpc('business_restroom_reliability',{p_business_id:businessId,p_days:Math.max(days,90)})],['remediationPerformance',rpc('business_restroom_remediation_performance',{p_business_id:businessId,p_days:Math.max(days,90)})]];const settled=await Promise.allSettled(calls.map(([,promise])=>promise)),values:Record<string,unknown>={},errors:string[]=[];settled.forEach((result,index)=>{const key=calls[index][0];if(result.status==='fulfilled')values[key]=result.value;else errors.push(`${key}: ${result.reason instanceof Error?result.reason.message:String(result.reason)}`)});return{analytics:{visitors:values.visitors,reviews:values.reviews,promotions:values.promotions,campaigns:values.campaigns,events:values.events,qr:values.qr,media:values.media,amenities:values.amenities,occupancy:values.occupancy,rewards:values.rewards,summary:values.summary},funnels:{attribution:values.attribution,engagement:values.engagement,growthActions:values.growthActions},partner:{analytics:values.partners,preferredLocations:values.preferred},progression:{snapshot:values.progression},leaderboards:{business:values.businessLeaderboard,crossTier:values.crossTierLeaderboard},operations:{reverification:values.reverification,remediation:values.remediation,reliability:values.reliability,remediationPerformance:values.remediationPerformance},errors};}
export async function listPartnerPrograms(){return (await rpc('business_list_partner_programs'))??[];}
export function createPartnerProgram(businessId:string,name:string){return rpc('business_create_partner_program',{p_business_id:businessId,p_name:name});}
export function updatePartnerProgram(businessId:string,id:string,name:string,enabled:boolean){return rpc('business_update_partner_program',{p_business_id:businessId,p_partner_program_id:id,p_name:name,p_enabled:enabled});}
export function deletePartnerProgram(businessId:string,id:string){return rpc('business_delete_partner_program',{p_business_id:businessId,p_partner_program_id:id});}
export function createPartnership(businessId:string,name:string){return rpc('business_create_partnership',{p_business_id:businessId,p_name:name,p_enabled:true,p_preferred_access:false,p_match_discount_bonus:0,p_custom_perk:null});}
export async function listPartnerships(businessId:string){return (await rpc('business_list_partnerships',{p_business_id:businessId}))??[];}
export function updatePartnership(businessId:string,id:string,input:{name:string;enabled:boolean;preferredAccess?:boolean;matchDiscountBonus?:number;customPerk?:string|null}){return rpc('business_update_partnership',{p_business_id:businessId,p_partnership_id:id,p_name:input.name,p_enabled:input.enabled,p_preferred_access:input.preferredAccess??false,p_match_discount_bonus:input.matchDiscountBonus??0,p_custom_perk:input.customPerk??null});}
export function deletePartnership(businessId:string,id:string){return rpc('business_delete_partnership',{p_business_id:businessId,p_partnership_id:id});}
