import { getKleenestSupabaseClient } from '@kleenest/mobile-core';

export type QrRecord=Record<string,any>;
const client=()=>getKleenestSupabaseClient();
async function rpc<T=any>(name:string,args:Record<string,unknown>={}){const{data,error}=await client().rpc(name,args);if(error)throw error;return data as T;}
const rows=(value:any)=>Array.isArray(value)?value:Array.isArray(value?.assets)?value.assets:Array.isArray(value?.rows)?value.rows:[];
export async function getQrStudioTier(businessId:string){const data:any=await rpc('get_business_product_access',{p_business_id:businessId});const row=Array.isArray(data)?data[0]:data;const plan=String(row?.plan||row?.tier||'standard').toLowerCase();return{plan,standard:plan==='standard',growth:plan==='growth',enterprise:Boolean(row?.enterprise_enabled)||plan==='enterprise',fleet:Boolean(row?.fleet_enabled),locationCount:Number(row?.location_count||0)};}
export async function listQrStudioAssets(businessId:string,days=90){const end=new Date(),start=new Date(end.getTime()-days*86400000);return rows(await rpc('qr_studio_list_assets',{p_business_id:businessId,p_from:start.toISOString(),p_to:end.toISOString()}));}
export async function listQrStudioTemplates(businessId:string){return rows(await rpc('qr_studio_list_templates',{p_business_id:businessId}));}
export async function listQrStudioVersions(businessId:string,qrId:string){return rows(await rpc('qr_studio_versions',{p_business_id:businessId,p_qr_id:qrId}));}
export async function listQrPrograms(qrId:string){return rows(await rpc('list_qr_engagement_programs',{p_qr_code_id:qrId}));}
export function createQrProgram(qrId:string,input:{programType:string;name:string;description?:string;triggerCount?:number;rewardConfig?:Record<string,unknown>}){return rpc('create_qr_engagement_program',{p_qr_code_id:qrId,p_program_type:input.programType,p_name:input.name,p_description:input.description??null,p_reward_config:input.rewardConfig??{},p_trigger_count:input.triggerCount??1});}
export function createQrAsset(businessId:string,input:{locationId:string;label:string;purpose:string;actionType:string;actionPayload?:Record<string,unknown>;customization?:Record<string,unknown>;singleUse?:boolean;maxRedemptions?:number|null}){return rpc('business_create_custom_qr',{p_business_id:businessId,p_location_id:input.locationId,p_label:input.label,p_purpose:input.purpose,p_action_type:input.actionType,p_action_payload:input.actionPayload??{},p_customization:input.customization??{},p_single_use:Boolean(input.singleUse),p_max_redemptions:input.maxRedemptions??null});}
export function updateQrAsset(businessId:string,qrId:string,input:{label?:string|null;purpose?:string|null;actionType?:string|null;actionPayload?:Record<string,unknown>;customization?:Record<string,unknown>;active?:boolean;singleUse?:boolean;maxRedemptions?:number|null}){return rpc('business_update_custom_qr',{p_business_id:businessId,p_qr_id:qrId,p_label:input.label??null,p_purpose:input.purpose??null,p_action_type:input.actionType??null,p_action_payload:input.actionPayload??{},p_customization:input.customization??{},p_active:input.active??true,p_single_use:Boolean(input.singleUse),p_max_redemptions:input.maxRedemptions??null});}
export function setQrActive(businessId:string,qrId:string,active:boolean){return rpc('business_set_qr_active',{p_business_id:businessId,p_qr_id:qrId,p_active:active});}
export function deleteQrAsset(businessId:string,qrId:string){return rpc('business_delete_qr',{p_business_id:businessId,p_qr_id:qrId});}
export function saveQrTemplate(businessId:string,input:{templateId?:string|null;name:string;description?:string;design:Record<string,unknown>;defaultAction?:Record<string,unknown>}){return rpc('qr_studio_save_template',{p_business_id:businessId,p_template_id:input.templateId??null,p_name:input.name,p_description:input.description??null,p_design:input.design,p_default_action:input.defaultAction??{}});}
export function archiveQrTemplate(businessId:string,templateId:string){return rpc('qr_studio_archive_template',{p_business_id:businessId,p_template_id:templateId});}
export function restoreQrVersion(businessId:string,qrId:string,version:number){return rpc('qr_studio_restore_version',{p_business_id:businessId,p_qr_id:qrId,p_version:version,p_change_summary:`Restored QR version ${version} from Business mobile`});}
export function saveQrVersion(businessId:string,qrId:string,locationId:string|null,patch:Record<string,unknown>,summary:string){return rpc('qr_studio_upsert_asset',{p_business_id:businessId,p_qr_id:qrId,p_location_id:locationId,p_patch:patch,p_change_summary:summary});}
export async function listQrLocationOptions(businessId:string){const value:any=await rpc('business_list_locations',{p_business_id:businessId});return rows(value);}
export async function getQrAnalytics(businessId:string,days=30){const end=new Date(),start=new Date(end.getTime()-days*86400000);const args={p_business_id:businessId,p_start:start.toISOString(),p_end:end.toISOString()};const [detail,analytics,attribution]=await Promise.allSettled([rpc('business_qr_detail',args),rpc('business_qr_analytics',args),rpc('get_business_attribution_funnel',args)]);return{detail:detail.status==='fulfilled'?detail.value:null,analytics:analytics.status==='fulfilled'?analytics.value:null,attribution:attribution.status==='fulfilled'?attribution.value:null,partial:[detail,analytics,attribution].some(x=>x.status==='rejected')};}
