do $$
declare b1 uuid; b2 uuid; p uuid; l1 uuid; l2 uuid;
begin
 select id into b1 from public.businesses where name='Downtown Coffee & Market' and is_demo_test=true limit 1;
 if b1 is null then insert into public.businesses(name,website,phone,email,business_tier,verification_status,is_demo_test) values('Downtown Coffee & Market','https://downtowncoffee.demo','(618) 555-0101','owner@downtowncoffee.demo','growth','verified',true) returning id into b1; end if;
 select id into b2 from public.businesses where name='Kleenest Travel Plaza' and is_demo_test=true limit 1;
 if b2 is null then insert into public.businesses(name,website,phone,email,business_tier,verification_status,is_demo_test) values('Kleenest Travel Plaza','https://travelplaza.demo','(618) 555-0103','travel@kleenest.demo','growth','verified',true) returning id into b2; end if;
 select id into l1 from public.locations where name='Downtown Coffee & Market' and is_active=true limit 1;
 if l1 is null then insert into public.locations(business_id,name,address,city,state,postal_code,country,latitude,longitude,place_type,phone,website,description,owner_name,owner_email,verification_status,source,is_premium,is_active,accessible,changing_table,cleanliness,cleanliness_pct,rating,review_count,cleaning_schedule,smart_bathroom,geofence_radius_m,promo_offer) values(b1,'Downtown Coffee & Market','101 Main Street','Downtown','IL','62220','US',38.505,-89.699,'restaurant','(618) 555-0101','https://downtowncoffee.demo','Neighborhood cafe with a well-maintained restroom.','Downtown Coffee Owner','owner@downtowncoffee.demo','verified','demo',true,true,true,true,'excellent',96,4.8,128,'Every 2 hours',false,50,'Free drip coffee with Kleenest check-in') returning id into l1; end if;
 select id into l2 from public.locations where name='Kleenest Travel Plaza' and is_active=true limit 1;
 if l2 is null then insert into public.locations(business_id,name,address,city,state,postal_code,country,latitude,longitude,place_type,phone,website,description,owner_name,owner_email,verification_status,source,is_premium,is_active,accessible,changing_table,cleanliness,cleanliness_pct,rating,review_count,cleaning_schedule,smart_bathroom,geofence_radius_m,promo_offer) values(b2,'Kleenest Travel Plaza','800 Route 4','Sparta','IL','62286','US',38.502,-89.695,'travel','(618) 555-0103','https://travelplaza.demo','High-traffic travel plaza designed for families and drivers.','Travel Plaza Manager','travel@kleenest.demo','verified','demo',true,true,true,true,'excellent',98,4.9,201,'Every 45 minutes',true,50,'10% off snacks with a Kleenest check-in') returning id into l2; end if;
 select id into p from public.partner_programs where business_id=b2 and name='Road + Coffee Preferred' and is_demo_test=true limit 1;
 if p is null then insert into public.partner_programs(business_id,name,enabled,preferred_access,match_discount_bonus,custom_perk,is_demo_test) values(b2,'Road + Coffee Preferred',true,true,2,'Priority shower lane + partner coffee benefit',true) returning id into p; end if;
 if not exists(select 1 from public.partner_agreements where partner_program_id=p and partner_business_id=b1 and status='active') then insert into public.partner_agreements(partner_program_id,partner_business_id,status,is_demo_test) values(p,b1,'active',true); end if;
 if not exists(select 1 from public.partner_program_locations where partner_program_id=p and location_id=l2) then insert into public.partner_program_locations(partner_program_id,location_id,status,benefit_type) values(p,l2,'active','preferred_location'); end if;
 if not exists(select 1 from public.partner_program_locations where partner_program_id=p and location_id=l1) then insert into public.partner_program_locations(partner_program_id,location_id,status,benefit_type) values(p,l1,'active','preferred_location'); end if;
end $$;
