revoke execute on function public.audit_contributor_reputation_consistency(boolean) from anon, authenticated;
revoke execute on function public.capability_retirement_audit() from anon, authenticated;
revoke execute on function public.compute_bathroom_intelligence(uuid) from anon, authenticated;
revoke execute on function public.refresh_bathroom_intelligence(integer) from anon, authenticated;
revoke execute on function public.refresh_location_bathroom_intelligence_trigger() from anon, authenticated;
revoke execute on function public.refresh_reputation_for_evidence_user() from anon, authenticated;
revoke execute on function public.recompute_contributor_reputation(uuid) from anon, authenticated;
revoke execute on function public.create_gps_geofence_notification(uuid,integer,text,text,text,jsonb) from anon, authenticated;
revoke execute on function public.claim_map_discovery_cell(numeric,numeric,integer,integer) from anon, authenticated;
revoke execute on function public.run_capability_audit(text) from anon, authenticated;
revoke execute on function public.admin_crud_gateway(text,text,uuid,jsonb) from anon, authenticated;
revoke execute on function public.admin_crud_schema(text) from anon, authenticated;
revoke execute on function public.admin_set_account_capabilities(uuid,text,text,boolean,boolean,boolean,text) from anon, authenticated;
revoke execute on function public.admin_set_user_access(uuid,boolean,text,text,boolean,text) from anon, authenticated;
revoke execute on function public.admin_set_business_access(uuid,public.business_tier,boolean,boolean,text) from anon, authenticated;
revoke execute on function public.admin_set_business_tier(uuid,public.business_tier) from anon, authenticated;
revoke execute on function public.admin_set_business_verification(uuid,public.verification_status) from anon, authenticated;
revoke execute on function public.admin_assign_business_member(uuid,uuid,public.business_member_role) from anon, authenticated;
revoke execute on function public.admin_remove_business_member(uuid,uuid) from anon, authenticated;
revoke execute on function public.admin_list_business_members(uuid) from anon, authenticated;
revoke execute on function public.admin_list_pending_businesses() from anon, authenticated;
revoke execute on function public.admin_list_reports() from anon, authenticated;
revoke execute on function public.admin_get_overview() from anon, authenticated;
revoke execute on function public.admin_operational_capability_catalog() from anon, authenticated;
revoke execute on function public.admin_raw_schema_capability_audit() from anon, authenticated;
revoke execute on function public.admin_crud_capability_catalog() from anon, authenticated;
revoke execute on function public.is_platform_owner_session() from anon, authenticated;
revoke execute on function public.ensure_current_user_profile() from anon;
revoke execute on function public.accept_family_invite() from anon;
revoke execute on function public.create_family_group(text) from anon;
revoke execute on function public.invite_family_member(text) from anon;
revoke execute on function public.family_has_premium_access(uuid) from anon;
