-- Contests: preserve member write authority while merging member visibility into the single read policy.
drop policy if exists "contests_member_advanced_all" on public.contests;
create policy "contests_member_advanced_insert" on public.contests for insert to authenticated with check (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = contests.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
create policy "contests_member_advanced_update" on public.contests for update to authenticated using (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = contests.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier)) with check (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = contests.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
create policy "contests_member_advanced_delete" on public.contests for delete to authenticated using (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = contests.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
alter policy "contests_read" on public.contests using ((status = any (array['scheduled'::text,'active'::text,'completed'::text])) or created_by = (select auth.uid()) or exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = contests.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));

-- Family members: owner access is already included in family_members_access; split only writes.
drop policy if exists "family_members_group_owner_all" on public.family_members;
create policy "family_members_group_owner_insert" on public.family_members for insert to authenticated with check (exists (select 1 from public.family_groups g where g.id = family_members.group_id and g.owner_id = (select auth.uid())));
create policy "family_members_group_owner_update" on public.family_members for update to authenticated using (exists (select 1 from public.family_groups g where g.id = family_members.group_id and g.owner_id = (select auth.uid()))) with check (exists (select 1 from public.family_groups g where g.id = family_members.group_id and g.owner_id = (select auth.uid())));
create policy "family_members_group_owner_delete" on public.family_members for delete to authenticated using (exists (select 1 from public.family_groups g where g.id = family_members.group_id and g.owner_id = (select auth.uid())));

-- Fleet routes: preserve manager visibility in the single SELECT policy and split writes.
drop policy if exists "fleet_routes_write" on public.fleet_routes;
alter policy "fleet_routes_select" on public.fleet_routes using (fleet_observe_access(business_id) or fleet_actor_is_manager(business_id));
create policy "fleet_routes_insert" on public.fleet_routes for insert to authenticated with check (fleet_actor_is_manager(business_id));
create policy "fleet_routes_update" on public.fleet_routes for update to authenticated using (fleet_actor_is_manager(business_id)) with check (fleet_actor_is_manager(business_id));
create policy "fleet_routes_delete" on public.fleet_routes for delete to authenticated using (fleet_actor_is_manager(business_id));

-- Public fixture/hour reads already cover authenticated SELECT; split member writes only.
drop policy if exists "location_fixtures_member_all" on public.location_fixtures;
create policy "location_fixtures_member_insert" on public.location_fixtures for insert to authenticated with check (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_fixtures.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "location_fixtures_member_update" on public.location_fixtures for update to authenticated using (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_fixtures.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role]))) with check (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_fixtures.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "location_fixtures_member_delete" on public.location_fixtures for delete to authenticated using (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_fixtures.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));

drop policy if exists "location_hours_member_all" on public.location_hours;
create policy "location_hours_member_insert" on public.location_hours for insert to authenticated with check (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_hours.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "location_hours_member_update" on public.location_hours for update to authenticated using (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_hours.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role]))) with check (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_hours.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "location_hours_member_delete" on public.location_hours for delete to authenticated using (exists (select 1 from public.locations l join public.business_members bm on bm.business_id = l.business_id where l.id = location_hours.location_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));

-- Locations: anonymous reads stay active-only; authenticated reads are active OR authorized business membership.
drop policy if exists "locations_member_all" on public.locations;
alter policy "locations_public_select" on public.locations to anon using (is_active = true);
create policy "locations_authenticated_select" on public.locations for select to authenticated using ((is_active = true) or exists (select 1 from public.business_members bm where bm.business_id = locations.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "locations_member_insert" on public.locations for insert to authenticated with check (exists (select 1 from public.business_members bm where bm.business_id = locations.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "locations_member_update" on public.locations for update to authenticated using (exists (select 1 from public.business_members bm where bm.business_id = locations.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role]))) with check (exists (select 1 from public.business_members bm where bm.business_id = locations.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));
create policy "locations_member_delete" on public.locations for delete to authenticated using (exists (select 1 from public.business_members bm where bm.business_id = locations.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role,'staff'::business_member_role])));

-- Promotions: anonymous reads stay public-active; authenticated reads preserve public-active OR advanced-member access.
drop policy if exists "promotions_member_advanced_all" on public.promotions;
alter policy "promotions_public_active_select" on public.promotions to anon using ((active = true) and ((starts_at is null) or (starts_at <= now())) and ((ends_at is null) or (ends_at > now())) and exists (select 1 from public.businesses b where b.id = promotions.business_id and b.verification_status = 'verified'::verification_status) and ((location_id is null) or exists (select 1 from public.locations l where l.id = promotions.location_id and l.business_id = promotions.business_id and l.is_active = true and l.verification_status = 'verified'::verification_status)));
create policy "promotions_authenticated_select" on public.promotions for select to authenticated using (((active = true) and ((starts_at is null) or (starts_at <= now())) and ((ends_at is null) or (ends_at > now())) and exists (select 1 from public.businesses b where b.id = promotions.business_id and b.verification_status = 'verified'::verification_status) and ((location_id is null) or exists (select 1 from public.locations l where l.id = promotions.location_id and l.business_id = promotions.business_id and l.is_active = true and l.verification_status = 'verified'::verification_status))) or exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = promotions.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
create policy "promotions_member_advanced_insert" on public.promotions for insert to authenticated with check (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = promotions.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
create policy "promotions_member_advanced_update" on public.promotions for update to authenticated using (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = promotions.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier)) with check (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = promotions.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
create policy "promotions_member_advanced_delete" on public.promotions for delete to authenticated using (exists (select 1 from public.business_members bm join public.businesses b on b.id = bm.business_id where bm.business_id = promotions.business_id and bm.user_id = (select auth.uid()) and bm.role = any (array['owner'::business_member_role,'admin'::business_member_role,'manager'::business_member_role]) and b.business_tier <> 'standard'::business_tier));
