alter view public.restroom_intelligence rename column community_agreement to weighted_community_agreement;
create or replace view public.restroom_intelligence as
with obs as (
 select ro.location_id,count(*)::integer observation_count,max(ro.created_at) last_observed_at,
 count(*) filter(where ro.created_at>=now()-interval '30 days' and ro.observation_type in('clean','supplies_stocked','open'))::integer recent_positive_count,
 count(*) filter(where ro.created_at>=now()-interval '30 days' and ro.observation_type in('needs_cleaning','supplies_low','closed_unavailable'))::integer recent_negative_count,
 coalesce(sum(case when ro.created_at>=now()-interval '30 days' then case cr.verification_level when 'verified' then 3.0 when 'trusted' then 2.0 when 'contributor' then 1.25 else 1.0 end*greatest(.25,1-extract(epoch from(now()-ro.created_at))/2592000) else 0 end),0)::numeric weighted_observation_count,
 coalesce(sum(case when ro.created_at>=now()-interval '30 days' and ro.observation_type in('clean','supplies_stocked','open') then case cr.verification_level when 'verified' then 3.0 when 'trusted' then 2.0 when 'contributor' then 1.25 else 1.0 end*greatest(.25,1-extract(epoch from(now()-ro.created_at))/2592000) else 0 end),0)::numeric weighted_positive_count,
 coalesce(sum(case when ro.created_at>=now()-interval '30 days' and ro.observation_type in('needs_cleaning','supplies_low','closed_unavailable') then case cr.verification_level when 'verified' then 3.0 when 'trusted' then 2.0 when 'contributor' then 1.25 else 1.0 end*greatest(.25,1-extract(epoch from(now()-ro.created_at))/2592000) else 0 end),0)::numeric weighted_negative_count
 from public.restroom_observations ro left join public.contributor_reputation cr on cr.user_id=ro.user_id group by ro.location_id)
select p.id place_id,p.location_id,p.name,p.latitude,p.longitude,coalesce(l.cleanliness_pct,0)::numeric base_cleanliness_pct,coalesce(l.bathroom_verification_count,0)::integer verification_count,coalesce(l.bathroom_positive_count,0)::integer positive_count,coalesce(l.bathroom_negative_count,0)::integer negative_count,coalesce(obs.observation_count,0)::integer observation_count,obs.last_observed_at,greatest(0,extract(epoch from(now()-coalesce(obs.last_observed_at,l.updated_at,p.updated_at)))/86400)::numeric age_days,case when obs.last_observed_at is null then 0 else greatest(0,1-extract(epoch from(now()-obs.last_observed_at))/2592000) end::numeric freshness_factor,case when coalesce(obs.weighted_positive_count,0)+coalesce(obs.weighted_negative_count,0)>0 then obs.weighted_positive_count/nullif(obs.weighted_positive_count+obs.weighted_negative_count,0) else null end weighted_community_agreement,case when coalesce(obs.weighted_positive_count,0)>0 and coalesce(obs.weighted_negative_count,0)>0 then true else false end has_recent_conflict,
round(least(100,greatest(0,coalesce(l.cleanliness_pct,50)*.50+least(18,coalesce(l.bathroom_verification_count,0)*1.8)+least(17,coalesce(obs.weighted_observation_count,0)*2)+case when obs.last_observed_at is null then 0 else greatest(0,10*(1-extract(epoch from(now()-obs.last_observed_at))/2592000)) end+case when coalesce(obs.weighted_positive_count,0)>coalesce(obs.weighted_negative_count,0) and coalesce(obs.weighted_negative_count,0)=0 then 5 else 0 end-case when coalesce(obs.weighted_negative_count,0)>coalesce(obs.weighted_positive_count,0) then 8 else 0 end)))::integer intelligence_score,
case when obs.last_observed_at is null then 'No recent community observation' when extract(epoch from(now()-obs.last_observed_at))/86400<=1 then 'Observed today' when extract(epoch from(now()-obs.last_observed_at))/86400<=7 then 'Observed this week' when extract(epoch from(now()-obs.last_observed_at))/86400<=30 then 'Observed this month' else 'Observation is stale' end freshness_label
from public.places p left join public.locations l on l.id=p.location_id left join obs on obs.location_id=p.location_id where p.is_active=true and p.category='restroom';
grant select on public.restroom_intelligence to anon,authenticated;
