insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('admin_get_overview()','owner_admin','canonical','Owner/Admin operational overview.'),
('business_create_location(uuid,text,text,text,text,numeric,numeric)','business_management','canonical','Canonical business location creation.'),
('business_update_location(uuid,text,text,text,text,boolean)','business_management','canonical','Canonical business location update.'),
('business_set_location_active(uuid,boolean)','business_management','supporting','Business location lifecycle toggle.'),
('business_list_locations(uuid)','business_management','supporting','Business location listing.'),
('business_location_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Business location analytics detail.'),
('business_list_campaigns(uuid)','business_campaigns','supporting','Business campaign listing.'),
('business_list_events(uuid)','business_events','supporting','Business event listing.'),
('business_list_contests(uuid)','business_contests','supporting','Business contest listing.'),
('business_list_media(uuid)','business_media','supporting','Business media listing.'),
('business_list_amenities(uuid,uuid)','business_amenities','supporting','Business amenity listing.'),
('business_campaign_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Campaign analytics detail.'),
('business_event_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Event analytics detail.'),
('business_media_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Media analytics detail.'),
('business_promotion_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Promotion analytics detail.'),
('business_review_detail(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Review analytics detail.'),
('business_location_intelligence(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Location intelligence analytics.'),
('business_set_promotion_active(uuid,boolean)','business_promotions','compatibility','Legacy promotion lifecycle signature.'),
('business_set_promotion_active(uuid,uuid,boolean)','business_promotions','compatibility','Older business-scoped promotion lifecycle signature.'),
('business_set_location_status(uuid,uuid,boolean)','business_management','compatibility','Older business-scoped location lifecycle signature.'),
('get_amenities_catalog()','amenities','canonical','Canonical amenities catalog.'),
('get_location_occupancy(uuid,integer)','location_intelligence','supporting','Location occupancy calculation.'),
('search_locations(text,integer)','location_discovery','supporting','Location text search.'),
('kleenest_location_confidence(uuid)','location_intelligence','supporting','Location confidence computation.'),
('map_location_category(text)','location_identity','supporting','External category mapping.'),
('submit_location_info(uuid,jsonb)','consumer_evidence','canonical','Consumer location information submission.'),
('submit_location_verification(uuid,boolean,boolean,text)','consumer_evidence','canonical','Consumer verification submission.'),
('submit_location_photo_record(uuid,text,text,text,text,bigint,integer,integer)','consumer_evidence','canonical','Consumer location photo evidence submission.'),
('refresh_location_verification_summary(uuid)','consumer_evidence','trigger_helper','Verification projection refresh helper.'),
('trg_refresh_location_verification_summary()','consumer_evidence','trigger_helper','Verification trigger helper.'),
('refresh_location_rating()','consumer_evidence','trigger_helper','Rating projection refresh helper.'),
('refresh_location_feature_summary(uuid)','location_intelligence','trigger_helper','Location feature projection refresh helper.'),
('set_location_geom()','location_identity','trigger_helper','Canonical location geometry trigger helper.'),
('set_updated_at()','infrastructure','trigger_helper','Timestamp trigger helper.'),
('touch_updated_at()','infrastructure','trigger_helper','Timestamp trigger helper.'),
('create_business_for_current_user(text,text,text,text,text)','business_management','canonical','Canonical owner business creation.'),
('claim_location_for_business(uuid,uuid)','business_management','canonical','Canonical business location claim.'),
('set_location_amenities(uuid,uuid[])','business_amenities','canonical','Canonical location amenity assignment.'),
('set_featured_location_photo(uuid,uuid)','business_media','supporting','Featured location photo projection.'),
('submit_feedback(text,text,text,text,jsonb)','consumer_feedback','canonical','Canonical feedback submission.'),
('record_business_engagement_attribution(uuid,uuid,uuid,uuid,text,text,jsonb)','business_analytics','supporting','Business engagement attribution.'),
('record_feature_access(text,text,text,text,jsonb)','platform_analytics','supporting','Feature access telemetry.'),
('record_data_feature_event(text,text,text,uuid,uuid,uuid,uuid,text,uuid,numeric,text,jsonb)','platform_analytics','supporting','Data feature telemetry.'),
('consumer_ads_enabled(uuid)','consumer_membership','supporting','Consumer advertising entitlement check.'),
('get_business_product_access(uuid)','business_membership','supporting','Business product entitlement check.'),
('require_business_admin(uuid)','owner_admin','supporting','Business admin authorization guard.'),
('handle_new_user()','account_profile','trigger_helper','New-user profile trigger helper.'),
('create_default_location_data(uuid)','location_identity','trigger_helper','Canonical default location projection helper.'),
('enforce_growth_location_cap()','location_identity','trigger_helper','Location growth policy trigger helper.'),
('apply_external_amenity_to_location(uuid,text,text)','bathroom_intelligence','supporting','External amenity observation application.'),
('apply_user_amenity_confirmation()','consumer_evidence','trigger_helper','User amenity confirmation projection helper.')
on conflict(function_signature) do update set domain=excluded.domain,classification=excluded.classification,rationale=excluded.rationale,updated_at=now();
