create or replace function public.sync_external_location_address() returns trigger language plpgsql security definer set search_path='public','auth','extensions','pg_temp' as $function$
declare tags jsonb:=coalesce(new.raw_data->'source_metadata'->'tags','{}'::jsonb); src record; display text; begin
 if new.location_id is null then return new; end if;
 select name,source_url into src from public.external_data_sources where id=new.source_id;
 display:=nullif(new.raw_data->>'address','');
 if display is null then display:=nullif(concat_ws(', ',nullif(concat_ws(' ',coalesce(new.raw_data->>'addr:housenumber',tags->>'addr:housenumber'),coalesce(new.raw_data->>'addr:street',tags->>'addr:street')),''),nullif(coalesce(new.raw_data->>'city',tags->>'addr:city'),''),nullif(coalesce(new.raw_data->>'state',tags->>'addr:state'),''),nullif(coalesce(new.raw_data->>'postal_code',tags->>'addr:postcode'),''),nullif(coalesce(new.raw_data->>'country',tags->>'addr:country'),'')),''); end if;
 insert into public.location_address_backfills(location_id,provider,display_address,house_number,road,city,state,postal_code,country,latitude,longitude,fetched_at,source_url,metadata,external_record_id,osm_tags,raw_data) values(new.location_id,coalesce(src.name,'external'),display,coalesce(new.raw_data->>'addr:housenumber',tags->>'addr:housenumber'),coalesce(new.raw_data->>'addr:street',tags->>'addr:street'),coalesce(new.raw_data->>'city',tags->>'addr:city'),coalesce(new.raw_data->>'state',tags->>'addr:state'),coalesce(new.raw_data->>'postal_code',tags->>'addr:postcode'),coalesce(new.raw_data->>'country',tags->>'addr:country'),new.latitude,new.longitude,now(),src.source_url,jsonb_build_object('external_id',new.external_id,'record_type',new.record_type,'source_name',src.name,'source_updated_at',new.source_updated_at),new.id,tags,new.raw_data)
 on conflict(location_id) do update set provider=excluded.provider,display_address=coalesce(excluded.display_address,public.location_address_backfills.display_address),house_number=coalesce(excluded.house_number,public.location_address_backfills.house_number),road=coalesce(excluded.road,public.location_address_backfills.road),city=coalesce(excluded.city,public.location_address_backfills.city),state=coalesce(excluded.state,public.location_address_backfills.state),postal_code=coalesce(excluded.postal_code,public.location_address_backfills.postal_code),country=coalesce(excluded.country,public.location_address_backfills.country),latitude=coalesce(excluded.latitude,public.location_address_backfills.latitude),longitude=coalesce(excluded.longitude,public.location_address_backfills.longitude),fetched_at=excluded.fetched_at,source_url=coalesce(excluded.source_url,public.location_address_backfills.source_url),metadata=public.location_address_backfills.metadata||excluded.metadata,external_record_id=excluded.external_record_id,osm_tags=excluded.osm_tags,raw_data=excluded.raw_data;
 update public.locations l set address=coalesce(nullif(l.address,''),display),city=coalesce(nullif(l.city,''),coalesce(new.raw_data->>'city',tags->>'addr:city')),state=coalesce(nullif(l.state,''),coalesce(new.raw_data->>'state',tags->>'addr:state')),postal_code=coalesce(nullif(l.postal_code,''),coalesce(new.raw_data->>'postal_code',tags->>'addr:postcode')),country=coalesce(nullif(l.country,''),coalesce(new.raw_data->>'country',tags->>'addr:country')),updated_at=now() where l.id=new.location_id;
 return new;
end $function$;

update public.locations l set address=coalesce(nullif(l.address,''),b.display_address,case when b.house_number is not null or b.road is not null then concat_ws(' ',b.house_number,b.road) end),city=coalesce(nullif(l.city,''),b.city),state=coalesce(nullif(l.state,''),b.state),postal_code=coalesce(nullif(l.postal_code,''),b.postal_code),country=coalesce(nullif(l.country,''),b.country),updated_at=now() from public.location_address_backfills b where b.location_id=l.id and (nullif(l.address,'') is null or nullif(l.city,'') is null or nullif(l.state,'') is null or nullif(l.postal_code,'') is null or nullif(l.country,'') is null);
