CREATE OR REPLACE FUNCTION public.map_network_nearby_v1(p_lat double precision, p_lng double precision, p_radius_m integer DEFAULT 30000, p_limit integer DEFAULT 250, p_category text DEFAULT NULL::text, p_search text DEFAULT NULL::text, p_amenity_names text[] DEFAULT '{}'::text[])
 RETURNS TABLE(location_id uuid, place_id uuid, name text, category text, address text, city text, state text, postal_code text, latitude double precision, longitude double precision, distance_meters double precision, source text, source_dataset text, source_external_id text, is_verified boolean, rating numeric, review_count integer, cleanliness_pct numeric, verification_confidence numeric, amenities jsonb, fixtures jsonb, brand text, operator_name text, osm_tags jsonb)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
WITH base AS (
  SELECT l.id,p.id AS place_id,l.place_type,l.name,l.address,l.city,l.state,l.postal_code,l.latitude,l.longitude,l.source,l.source_dataset,l.source_external_id,l.source_metadata,l.rating AS l_rating,l.review_count AS l_review_count,l.cleanliness_pct,l.verification_confidence,p.category AS place_category,p.rating AS p_rating,p.review_count AS p_review_count,p.is_verified AS p_is_verified,p.name AS place_name,
    COALESCE(l.source_metadata->>'brand',l.source_metadata->>'brand_name',l.source_metadata->'evidence'->>'brand') AS brand_name,
    COALESCE(l.source_metadata->>'operator',l.source_metadata->>'operator_name',l.source_metadata->'evidence'->>'operator') AS operator_name,
    6371000.0*2*asin(sqrt(power(sin(radians(l.latitude-p_lat)/2),2)+cos(radians(p_lat))*cos(radians(l.latitude))*power(sin(radians(l.longitude-p_lng)/2),2))) AS dist,
    (lower(coalesce(l.source_metadata->'evidence'->>'toilets:access',l.source_metadata->'evidence'->>'access',l.source_metadata->>'toilets:access',l.source_metadata->>'access','')) NOT IN ('private','no') AND lower(coalesce(l.source_metadata->'evidence'->>'toilets',l.source_metadata->>'toilets','')) NOT IN ('no','none') AND (lower(coalesce(l.bathroom_verification_status,'')) IN ('has_bathroom','verified') OR lower(coalesce(l.place_type,'')) IN ('restroom','bathroom','toilet') OR lower(coalesce(p.category,'')) IN ('restroom','bathroom','toilet') OR lower(coalesce(l.source_metadata->'evidence'->>'amenity','')) IN ('toilets','restroom','bathroom') OR lower(coalesce(l.source_metadata->'evidence'->>'building',''))='toilets' OR lower(coalesce(l.source_metadata->'evidence'->>'toilets','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'amenity','')) IN ('toilets','restroom','bathroom') OR lower(coalesce(l.source_metadata->>'toilets','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'restroom','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'bathroom','')) IN ('yes','public','customers','permissive') OR coalesce(l.source_metadata->'osm_tags'->>'amenity','') ILIKE 'toilet%')) AS bathroom_signal
  FROM public.locations l LEFT JOIN public.places p ON p.location_id=l.id AND p.is_active=true
  WHERE l.is_active=true AND l.latitude IS NOT NULL AND l.longitude IS NOT NULL
    AND l.latitude BETWEEN p_lat-(p_radius_m/111320.0) AND p_lat+(p_radius_m/111320.0)
    AND l.longitude BETWEEN p_lng-(p_radius_m/(111320.0*greatest(cos(radians(p_lat)),0.2))) AND p_lng+(p_radius_m/(111320.0*greatest(cos(radians(p_lat)),0.2)))
    AND (
      p_category IS NULL OR lower(p_category)='all' OR lower(p_category)=lower(coalesce(p.category,l.place_type,''))
      OR (lower(p_category)='brand' AND coalesce(l.source_metadata->>'brand',l.source_metadata->>'brand_name') IS NOT NULL)
      OR (lower(p_category)='restroom' AND (lower(coalesce(l.source_metadata->'evidence'->>'toilets:access',l.source_metadata->'evidence'->>'access',l.source_metadata->>'toilets:access',l.source_metadata->>'access','')) NOT IN ('private','no') AND lower(coalesce(l.source_metadata->'evidence'->>'toilets',l.source_metadata->>'toilets','')) NOT IN ('no','none') AND (lower(coalesce(l.bathroom_verification_status,'')) IN ('has_bathroom','verified') OR lower(coalesce(l.place_type,'')) IN ('restroom','bathroom','toilet') OR lower(coalesce(p.category,'')) IN ('restroom','bathroom','toilet') OR lower(coalesce(l.source_metadata->'evidence'->>'amenity','')) IN ('toilets','restroom','bathroom') OR lower(coalesce(l.source_metadata->'evidence'->>'building',''))='toilets' OR lower(coalesce(l.source_metadata->'evidence'->>'toilets','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'amenity','')) IN ('toilets','restroom','bathroom') OR lower(coalesce(l.source_metadata->>'toilets','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'restroom','')) IN ('yes','public','customers','permissive') OR lower(coalesce(l.source_metadata->>'bathroom','')) IN ('yes','public','customers','permissive') OR coalesce(l.source_metadata->'osm_tags'->>'amenity','') ILIKE 'toilet%')))
      OR (lower(p_category)='restaurant' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(restaurant|food|fast_food)%')
      OR (lower(p_category)='cafe' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(cafe|coffee)%')
      OR (lower(p_category)='gas_station' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(gas|fuel)%')
      OR (lower(p_category)='shopping' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(shop|retail|supermarket|mall)%')
      OR (lower(p_category)='government' AND (lower(coalesce(p.category,l.place_type,'')) LIKE '%government%' OR lower(coalesce(l.place_type,'')) IN ('library','library_dropoff') OR lower(coalesce(l.name,'')) LIKE ANY(array['%city hall%','%town hall%','%county office%','%courthouse%','%court house%','%municipal%','%public library%','%library district%','%post office%','%dmv%','%department of motor vehicles']) OR lower(coalesce(l.source_metadata->>'government','')) IN ('true','yes') OR lower(coalesce(l.source_metadata->>'is_government','')) IN ('true','yes')))
      OR (lower(p_category)='park' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(park|recreation)%')
      OR (lower(p_category)='health' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(hospital|clinic|health|medical|pharmacy)%')
      OR (lower(p_category)='public_safety' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(police|fire|emergency|public_safety|public safety)%')
      OR (lower(p_category)='cooling_center' AND lower(coalesce(p.category,l.place_type,'')) SIMILAR TO '%(cooling|heat relief|warming)%')
    )
    AND (nullif(trim(p_search),'') IS NULL OR coalesce(l.name,'') ILIKE '%'||p_search||'%' OR coalesce(p.name,'') ILIKE '%'||p_search||'%' OR coalesce(l.address,'') ILIKE '%'||p_search||'%' OR coalesce(l.city,'') ILIKE '%'||p_search||'%' OR coalesce(l.state,'') ILIKE '%'||p_search||'%' OR coalesce(l.postal_code,'') ILIKE '%'||p_search||'%' OR coalesce(l.source_metadata->>'brand','') ILIKE '%'||p_search||'%' OR coalesce(l.source_metadata->>'brand_name','') ILIKE '%'||p_search||'%' OR coalesce(l.source_metadata->>'operator','') ILIKE '%'||p_search||'%' OR coalesce(l.source_metadata->>'operator_name','') ILIKE '%'||p_search||'%')
    AND (coalesce(cardinality(p_amenity_names),0)=0 OR EXISTS (SELECT 1 FROM public.location_amenities la JOIN public.amenities aa ON aa.id=la.amenity_id WHERE la.location_id=l.id AND aa.name=ANY(p_amenity_names)))
), ranked AS (
  SELECT * FROM base WHERE dist<=p_radius_m ORDER BY CASE WHEN lower(coalesce(p_category,''))='restroom' THEN NOT bathroom_signal ELSE false END,dist LIMIT greatest(1,least(p_limit,500))
), amen AS (SELECT la.location_id,jsonb_agg(DISTINCT jsonb_build_object('name',a.name,'category',a.category)) items FROM public.location_amenities la JOIN public.amenities a ON a.id=la.amenity_id GROUP BY la.location_id),
fx AS (SELECT lf.location_id,jsonb_build_object('stalls',lf.stalls,'urinals',lf.urinals,'sinks',lf.sinks,'hand_dryers',lf.hand_dryers,'changing_tables',lf.changing_tables,'showers',lf.showers) items FROM public.location_fixtures lf)
SELECT r.id,r.place_id,coalesce(r.place_name,r.name),
  CASE WHEN lower(coalesce(r.place_category,r.place_type,'')) IN ('library','library_dropoff') THEN 'government' WHEN lower(coalesce(p_category,''))='restroom' THEN 'restroom' WHEN lower(coalesce(p_category,''))='park' THEN 'park' WHEN lower(coalesce(p_category,''))='health' THEN 'health' WHEN lower(coalesce(p_category,''))='public_safety' THEN 'public_safety' WHEN lower(coalesce(p_category,''))='cooling_center' THEN 'cooling_center' WHEN lower(coalesce(p_category,''))='government' THEN 'government' WHEN r.brand_name IS NOT NULL AND lower(coalesce(r.place_category,r.place_type,''))='service' THEN 'brand' ELSE coalesce(r.place_category,r.place_type,'service') END,
  r.address,r.city,r.state,r.postal_code,r.latitude,r.longitude,r.dist,r.source,r.source_dataset,r.source_external_id,coalesce(r.p_is_verified,false),coalesce(r.p_rating,r.l_rating,0),coalesce(r.p_review_count,r.l_review_count,0),r.cleanliness_pct,r.verification_confidence,coalesce(a.items,'[]'::jsonb),coalesce(f.items,'{}'::jsonb),r.brand_name,r.operator_name,coalesce(r.source_metadata->'osm_tags','{}'::jsonb)
FROM ranked r LEFT JOIN amen a ON a.location_id=r.id LEFT JOIN fx f ON f.location_id=r.id ORDER BY r.dist;
$function$
