revoke execute on function public.business_change_member_role(uuid,uuid,public.business_member_role) from public, anon;
revoke execute on function public.business_create_location(uuid,text,text,text,text,text,numeric,numeric,text,text) from public, anon;
revoke execute on function public.business_create_promotion(uuid,uuid,text,text,text,timestamptz,timestamptz) from public, anon;
revoke execute on function public.business_dashboard_secure_summary(uuid,timestamptz,timestamptz) from public, anon;
revoke execute on function public.business_dashboard_summary(uuid,timestamptz,timestamptz) from public, anon;
revoke execute on function public.business_invite_member(uuid,uuid,public.business_member_role) from public, anon;
revoke execute on function public.business_remove_member(uuid,uuid) from public, anon;
revoke execute on function public.business_set_promotion_active(uuid,boolean) from public, anon;
revoke execute on function public.business_update_location(uuid,text,text,text,text,boolean) from public, anon;
revoke execute on function public.business_update_member_role(uuid,uuid,public.business_member_role) from public, anon;
revoke execute on function public.business_transfer_ownership(uuid,uuid) from public, anon;
grant execute on function public.business_change_member_role(uuid,uuid,public.business_member_role) to authenticated;
grant execute on function public.business_create_location(uuid,text,text,text,text,text,numeric,numeric,text,text) to authenticated;
grant execute on function public.business_create_promotion(uuid,uuid,text,text,text,timestamptz,timestamptz) to authenticated;
grant execute on function public.business_dashboard_secure_summary(uuid,timestamptz,timestamptz) to authenticated;
grant execute on function public.business_dashboard_summary(uuid,timestamptz,timestamptz) to authenticated;
grant execute on function public.business_invite_member(uuid,uuid,public.business_member_role) to authenticated;
grant execute on function public.business_remove_member(uuid,uuid) to authenticated;
grant execute on function public.business_set_promotion_active(uuid,boolean) to authenticated;
grant execute on function public.business_update_location(uuid,text,text,text,text,boolean) to authenticated;
grant execute on function public.business_update_member_role(uuid,uuid,public.business_member_role) to authenticated;
grant execute on function public.business_transfer_ownership(uuid,uuid) to authenticated;
