insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('_collect_raw_schema_capability_audit()','architecture_governance','trigger_helper','Raw schema audit implementation helper.'),
('_kleenest_capture_feature_event()','telemetry','trigger_helper','Internal feature-event capture helper.'),
('admin_crud_capability_catalog()','owner_admin_crud','supporting','Owner/Admin capability discovery.'),
('admin_crud_gateway(text,text,uuid,jsonb)','owner_admin_crud','canonical','Canonical Owner/Admin CRUD gateway.'),
('admin_crud_schema(text)','owner_admin_crud','supporting','CRUD schema introspection.'),
('admin_raw_schema_capability_audit()','architecture_governance','canonical','Canonical raw-schema audit surface.'),
('admin_operational_capability_catalog()','architecture_governance','supporting','Operational capability inventory.'),
('admin_data_integrity_summary()','owner_admin_crud','supporting','Owner/Admin diagnostic summary.'),
('admin_overview()','owner_admin_crud','supporting','Owner/Admin dashboard overview.'),
('admin_authorization_v1(uuid)','owner_admin_crud','supporting','Owner/Admin authorization helper.'),
('admin_get_business_access(uuid)','owner_admin_crud','supporting','Business access inspection.'),
('admin_list_business_members(uuid)','owner_admin_crud','supporting','Business member administration.'),
('admin_list_pending_businesses()','owner_admin_crud','supporting','Pending business administration.'),
('admin_list_reports()','owner_admin_crud','supporting','Report administration.'),
('admin_remove_business_member(uuid,uuid)','owner_admin_crud','supporting','Owner/Admin business member removal.'),
('admin_set_account_capabilities(uuid,text,text,boolean,boolean,boolean,text)','owner_admin_crud','supporting','Owner/Admin account capability mutation.'),
('admin_set_business_access(uuid,business_tier,boolean,boolean,text)','owner_admin_crud','supporting','Owner/Admin business access mutation.'),
('admin_set_business_tier(uuid,business_tier)','owner_admin_crud','supporting','Owner/Admin business tier mutation.'),
('admin_set_business_verification(uuid,verification_status)','owner_admin_crud','supporting','Owner/Admin business verification.'),
('admin_set_user_access(uuid,boolean,text,text,boolean,text)','owner_admin_crud','supporting','Owner/Admin user access mutation.'),
('admin_user_search(text)','owner_admin_crud','supporting','Owner/Admin user lookup.'),
('admin_assign_business_member(uuid,uuid,business_member_role)','owner_admin_crud','compatibility','Admin-specific member role path; should converge on canonical business membership contract.'),
('business_create_event(uuid,text,text,uuid,date,time without time zone)','business_crud','compatibility','Legacy event-create signature.'),
('business_create_event(uuid,text,text,date,time without time zone,uuid)','business_crud','compatibility','Legacy event-create signature.'),
('business_create_event(uuid,text)','business_crud','compatibility','Legacy event-create convenience signature.'),
('create_business_event(uuid,text,text,date,time without time zone,uuid)','business_crud','compatibility','Older generic event-create boundary.'),
('business_set_event(uuid,uuid,text,text,date,time without time zone,uuid)','business_crud','compatibility','Legacy event set/upsert boundary.'),
('business_create_location(uuid,text,text,text,numeric,numeric)','business_crud','compatibility','Legacy location-create signature.'),
('business_create_location(uuid,text)','business_crud','compatibility','Legacy location-create convenience signature.'),
('create_business_location(uuid,text,text,text,text)','business_crud','compatibility','Older generic location-create boundary.'),
('business_create_promotion(uuid,text,text,numeric,uuid,timestamp with time zone,timestamp with time zone)','business_crud','compatibility','Legacy promotion-create signature.'),
('business_create_promotion(uuid,text)','business_crud','compatibility','Legacy promotion-create convenience signature.'),
('create_business_promotion(uuid,text,text,numeric,timestamp with time zone,timestamp with time zone,uuid)','business_crud','compatibility','Older generic promotion-create boundary.'),
('business_dashboard_summary(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','compatibility','Legacy dashboard summary; v2 is canonical.'),
('get_business_dashboard()','business_analytics','compatibility','Older dashboard read boundary pending convergence.'),
('get_location_details(uuid)','location_discovery','supporting','Location detail read surface.'),
('kleenest_map_view(uuid)','location_discovery','supporting','Map-view supporting read surface.'),
('get_public_restroom_intelligence(uuid)','bathroom_intelligence','supporting','Bathroom intelligence detail read surface.'),
('get_location_bathroom_verification(uuid)','bathroom_intelligence','supporting','Bathroom verification read surface.'),
('record_location_verification(uuid,boolean,double precision,double precision,text)','consumer_observations','supporting','Location verification evidence primitive.'),
('record_bathroom_verification(uuid,boolean,double precision,double precision,double precision)','consumer_observations','supporting','Bathroom verification evidence primitive.'),
('refresh_bathroom_intelligence(integer)','bathroom_intelligence','supporting','Bulk intelligence refresh.'),
('refresh_location_bathroom_intelligence_trigger()','bathroom_intelligence','trigger_helper','Bathroom intelligence trigger helper.'),
('process_bathroom_verification()','bathroom_intelligence','trigger_helper','Bathroom verification trigger processor.'),
('create_route_plan(text,double precision,double precision,double precision,double precision,numeric,integer)','route_planning','canonical','Canonical route-plan creation.'),
('complete_route(uuid)','route_planning','canonical','Canonical route completion.'),
('prepare_route_discovery(uuid,integer,integer)','route_planning','supporting','Route discovery preparation.'),
('populate_route_discovery_cache(uuid,jsonb)','route_planning','supporting','Route discovery cache population.'),
('record_location_route_event(uuid,boolean)','route_planning','supporting','Route engagement telemetry.'),
('record_favorite_route_event(uuid,uuid,numeric,numeric)','route_planning','supporting','Favorite-route telemetry.'),
('kleenest_toggle_favorite(uuid)','consumer_saved_locations','canonical','Canonical saved-location toggle.'),
('my_favorite_locations()','consumer_saved_locations','canonical','Canonical saved-location listing.'),
('get_favorite_locations(uuid)','consumer_saved_locations','supporting','Saved-location lookup.'),
('follow_user(uuid)','community','canonical','Canonical user follow action.'),
('mark_message_read(uuid)','community','supporting','Community message read state.'),
('notify_new_message()','community','trigger_helper','Community message notification trigger.'),
('gamification_dashboard()','rewards_quests','supporting','Progression dashboard aggregate.'),
('get_progression_summary()','rewards_quests','supporting','Progression summary aggregate.'),
('complete_progression_challenge(uuid)','rewards_quests','canonical','Progression challenge completion.'),
('record_progression_action(text,uuid)','rewards_quests','supporting','Progression action event.'),
('record_progression_metric_event(text,text,uuid,numeric,integer,jsonb)','rewards_quests','supporting','Progression metric event.'),
('refresh_contributor_milestones(uuid)','rewards_quests','supporting','Contributor milestone refresh.'),
('record_game_result(text,integer,integer,jsonb)','rewards_quests','canonical','Game result recording.'),
('create_game_challenge(text,uuid,jsonb)','rewards_quests','canonical','Game challenge creation.'),
('list_game_challenges(text,integer)','rewards_quests','supporting','Game challenge discovery.'),
('list_game_challenge_targets(integer)','rewards_quests','supporting','Game challenge targets.'),
('record_game_challenge_score(uuid,integer,jsonb)','rewards_quests','canonical','Game challenge scoring.'),
('home_active_contests(integer)','community','supporting','Home contest discovery.'),
('home_active_events(integer)','community','supporting','Home event discovery.'),
('join_contest(uuid)','community','canonical','Contest participation.'),
('contest_score(uuid,uuid)','community','supporting','Contest score calculation.'),
('create_contest(text,text,timestamp with time zone,timestamp with time zone,jsonb,jsonb)','community','canonical','Contest creation.'),
('business_create_contest(uuid,text,text,timestamp with time zone,timestamp with time zone,jsonb,jsonb)','business_crud','canonical','Business contest creation.'),
('business_update_contest(uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,jsonb,jsonb,text)','business_crud','canonical','Business contest update.'),
('business_delete_contest(uuid,uuid)','business_crud','canonical','Business contest deletion.'),
('list_public_live_network_events(integer)','network_intelligence','supporting','Public network event feed.'),
('publish_live_network_event(text,uuid,text,uuid,jsonb)','network_intelligence','canonical','Network intelligence event publication.'),
('publish_intelligence_location_event(uuid,text,text,text,jsonb,integer,text)','network_intelligence','supporting','Intelligence event publication.'),
('record_geofence_event(uuid,uuid,uuid,uuid,text,integer,jsonb,uuid,uuid,uuid)','network_intelligence','supporting','Geofence intelligence event.'),
('record_location_filter_event(jsonb,integer,jsonb,double precision,double precision,integer,text)','location_discovery','supporting','Discovery filter telemetry.'),
('record_location_visit(uuid,jsonb)','location_discovery','supporting','Location visit telemetry.'),
('claim_map_discovery_cell(numeric,numeric,integer,integer)','location_discovery','supporting','Map discovery cell claim.'),
('enrich_location_from_osm(uuid)','location_identity','supporting','External identity/location enrichment.'),
('ingest_external_locations(text,jsonb)','location_identity','canonical','External location ingestion boundary.'),
('ingest_osm_locations(jsonb)','location_identity','supporting','OSM ingestion implementation.'),
('merge_external_location_metadata(uuid,text,text,text,text,text,text,text,text,jsonb)','location_identity','supporting','External metadata merge.'),
('account_effective_business_tier(uuid)','business_management','supporting','Business tier resolution.'),
('current_user_business_role(uuid)','business_membership','supporting','Current business role resolution.'),
('can_manage_business(uuid)','business_management','supporting','Business management eligibility.'),
('business_advanced_allowed(uuid)','business_management','supporting','Business feature entitlement.'),
('consumer_feature_access(text,uuid)','account_lifecycle','supporting','Consumer entitlement check.'),
('get_current_user_product_entitlements()','account_lifecycle','supporting','Product entitlement resolution.'),
('get_effective_consumer_tier(uuid)','account_lifecycle','supporting','Consumer tier resolution.'),
('is_platform_owner()','owner_admin_crud','supporting','Platform owner authorization.'),
('is_platform_owner(uuid)','owner_admin_crud','supporting','Platform owner authorization.'),
('current_user_id()','account_lifecycle','supporting','Current identity helper.'),
('accept_family_invite()','community','canonical','Family/community membership acceptance.'),
('create_family_group(text)','community','canonical','Family group creation.'),
('invite_family_member(text)','community','canonical','Family membership invitation.'),
('family_has_premium_access(uuid)','account_lifecycle','supporting','Family entitlement resolution.'),
('has_kleenest_premium()','account_lifecycle','supporting','Premium entitlement resolution.'),
('demo_create_business(text,text)','business_crud','legacy','Demo-only business creation path.'),
('demo_provision_business(text,uuid)','business_crud','legacy','Demo-only business provisioning.'),
('demo_create_partnership(uuid,uuid)','business_partnerships','legacy','Demo-only partnership path.'),
('demo_create_program(uuid,text,boolean)','business_partnerships','legacy','Demo-only program path.'),
('demo_add_test_membership(uuid,uuid)','business_membership','legacy','Demo-only membership path.'),
('demo_assign_program_location(uuid,uuid)','business_partnerships','legacy','Demo-only program location path.'),
('demo_list_test_businesses()','business_crud','legacy','Demo-only business listing.'),
('demo_network_health()','network_intelligence','legacy','Demo-only network diagnostic.'),
('ensure_current_user_demo_membership()','business_membership','legacy','Demo-only membership provisioning.'),
('ensure_demo_partner_network()','business_partnerships','legacy','Demo-only partner network provisioning.'),
('provision_demo_membership_after_profile()','business_membership','legacy','Demo-only membership trigger helper.')
on conflict(function_signature) do update set domain=excluded.domain, classification=excluded.classification, rationale=excluded.rationale, updated_at=now();
