create or replace function public.submit_location_verification(p_location_id uuid,p_is_open boolean,p_has_bathroom boolean default true,p_note text default null) returns jsonb language sql security invoker set search_path=public as $$ select public.submit_location_verification(p_location_id,p_is_open,p_has_bathroom,p_note,null::uuid); $$;
create or replace function public.submit_location_photo_record(p_location_id uuid,p_storage_path text,p_caption text default null,p_media_type text default 'image',p_mime_type text default null,p_size_bytes bigint default null,p_width integer default null,p_height integer default null) returns public.location_photos language sql security definer set search_path=public,auth,extensions,pg_temp as $$ select public.submit_location_photo_record(p_location_id,p_storage_path,p_caption,p_media_type,p_mime_type,p_size_bytes,p_width,p_height,null::uuid); $$;
insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('submit_location_verification(uuid,boolean,boolean,text,uuid)','consumer_evidence','canonical','Canonical verification submission with optional check-in evidence-session anchor.'),
('submit_location_photo_record(uuid,text,text,text,text,bigint,integer,integer,uuid)','consumer_evidence','canonical','Canonical photo evidence submission with optional check-in evidence-session anchor.')
on conflict(function_signature) do update set domain=excluded.domain,classification=excluded.classification,rationale=excluded.rationale,updated_at=now();
insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('submit_location_verification(uuid,boolean,boolean,text)','consumer_evidence','compatibility','Backward-compatible wrapper delegating to the check-in-aware canonical verification capability.'),
('submit_location_photo_record(uuid,text,text,text,text,bigint,integer,integer)','consumer_evidence','compatibility','Backward-compatible wrapper delegating to the check-in-aware canonical photo capability.')
on conflict(function_signature) do update set domain=excluded.domain,classification=excluded.classification,rationale=excluded.rationale,updated_at=now();
