alter function public.fleet_asset_exception_scorecards(uuid,integer) set search_path = '';
alter function public.fleet_current_user_dispatch(uuid) set search_path = '';
alter function public.fleet_dashboard_summary_v2(uuid) set search_path = '';
alter function public.fleet_dispatch_intelligence(uuid,uuid,integer) set search_path = '';
alter function public.fleet_dispatch_signal_policy(uuid) set search_path = '';
alter function public.fleet_driver_assignment_candidates(uuid) set search_path = '';
alter function public.fleet_exception_alerts(uuid,text,integer) set search_path = '';
alter function public.fleet_exception_policy(uuid) set search_path = '';
alter function public.fleet_exception_trends(uuid,integer) set search_path = '';
alter function public.fleet_operational_signal_summary(uuid,integer) set search_path = '';
alter function public.fleet_operations_exception_intelligence(uuid,integer) set search_path = '';
alter function public.fleet_route_exception_drilldown(uuid,uuid) set search_path = '';
alter function public.fleet_service_opportunities_for_business(uuid) set search_path = '';
alter function public.get_fleet_leaderboard(uuid,text,text,integer) set search_path = '';
alter function public.get_fleet_metric_capabilities(uuid) set search_path = '';
alter function public.get_fleet_metric_configuration(uuid) set search_path = '';
alter function public.get_fleet_metric_values(uuid,date) set search_path = '';
alter function public.get_fleet_network_leaderboard(text,integer) set search_path = '';

revoke execute on function public.fleet_asset_exception_scorecards(uuid,integer) from public, anon;
revoke execute on function public.fleet_current_user_dispatch(uuid) from public, anon;
revoke execute on function public.fleet_dashboard_summary_v2(uuid) from public, anon;
revoke execute on function public.fleet_dispatch_intelligence(uuid,uuid,integer) from public, anon;
revoke execute on function public.fleet_dispatch_signal_policy(uuid) from public, anon;
revoke execute on function public.fleet_driver_assignment_candidates(uuid) from public, anon;
revoke execute on function public.fleet_exception_alerts(uuid,text,integer) from public, anon;
revoke execute on function public.fleet_exception_policy(uuid) from public, anon;
revoke execute on function public.fleet_exception_trends(uuid,integer) from public, anon;
revoke execute on function public.fleet_operational_signal_summary(uuid,integer) from public, anon;
revoke execute on function public.fleet_operations_exception_intelligence(uuid,integer) from public, anon;
revoke execute on function public.fleet_route_exception_drilldown(uuid,uuid) from public, anon;
revoke execute on function public.fleet_service_opportunities_for_business(uuid) from public, anon;
revoke execute on function public.get_fleet_leaderboard(uuid,text,text,integer) from public, anon;
revoke execute on function public.get_fleet_metric_capabilities(uuid) from public, anon;
revoke execute on function public.get_fleet_metric_configuration(uuid) from public, anon;
revoke execute on function public.get_fleet_metric_values(uuid,date) from public, anon;
revoke execute on function public.get_fleet_network_leaderboard(text,integer) from public, anon;

grant execute on function public.fleet_asset_exception_scorecards(uuid,integer) to authenticated, service_role;
grant execute on function public.fleet_current_user_dispatch(uuid) to authenticated, service_role;
grant execute on function public.fleet_dashboard_summary_v2(uuid) to authenticated, service_role;
grant execute on function public.fleet_dispatch_intelligence(uuid,uuid,integer) to authenticated, service_role;
grant execute on function public.fleet_dispatch_signal_policy(uuid) to authenticated, service_role;
grant execute on function public.fleet_driver_assignment_candidates(uuid) to authenticated, service_role;
grant execute on function public.fleet_exception_alerts(uuid,text,integer) to authenticated, service_role;
grant execute on function public.fleet_exception_policy(uuid) to authenticated, service_role;
grant execute on function public.fleet_exception_trends(uuid,integer) to authenticated, service_role;
grant execute on function public.fleet_operational_signal_summary(uuid,integer) to authenticated, service_role;
grant execute on function public.fleet_operations_exception_intelligence(uuid,integer) to authenticated, service_role;
grant execute on function public.fleet_route_exception_drilldown(uuid,uuid) to authenticated, service_role;
grant execute on function public.fleet_service_opportunities_for_business(uuid) to authenticated, service_role;
grant execute on function public.get_fleet_leaderboard(uuid,text,text,integer) to authenticated, service_role;
grant execute on function public.get_fleet_metric_capabilities(uuid) to authenticated, service_role;
grant execute on function public.get_fleet_metric_configuration(uuid) to authenticated, service_role;
grant execute on function public.get_fleet_metric_values(uuid,date) to authenticated, service_role;
grant execute on function public.get_fleet_network_leaderboard(text,integer) to authenticated, service_role;
