create schema if not exists internal;

create table if not exists internal.storage_pressure_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tier text not null,
  disk_before numeric,
  disk_after numeric,
  database_before numeric,
  wal_before bigint,
  action jsonb not null default '{}'::jsonb
);

revoke all on internal.storage_pressure_events from public, anon, authenticated;

create or replace function internal.run_storage_pressure_controller()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, internal
as $$
declare
  before_status jsonb;
  after_status jsonb;
  disk_before numeric;
  db_before numeric;
  wal_before bigint;
  cleanup jsonb := '{}'::jsonb;
  trimmed_runs bigint := 0;
  trimmed_audits bigint := 0;
  trimmed_cron bigint := 0;
  tier text := 'normal';
  prepaused boolean := false;
  resumed boolean := false;
  got_lock boolean;
begin
  got_lock := pg_try_advisory_xact_lock(hashtext('kleenest_storage_pressure_controller'));
  if not got_lock then
    return jsonb_build_object('ok', true, 'status', 'overlap_suppressed');
  end if;

  before_status := public.national_ingestion_storage_status();
  disk_before := coalesce((before_status->>'disk_observed_fraction')::numeric, 1);
  db_before := coalesce((before_status->>'database_fraction')::numeric, 1);
  wal_before := coalesce((before_status->>'wal_bytes')::bigint, 0);

  if disk_before >= 0.82 then
    tier := 'compact_82';
    cleanup := public.compact_kleenest_storage();
  end if;

  if disk_before >= 0.86 then
    tier := 'aggressive_86';

    update public.national_ingestion_runs
       set detail = '{}'::jsonb
     where finished_at < now() - interval '48 hours'
       and detail is not null
       and detail <> '{}'::jsonb;
    get diagnostics trimmed_runs = row_count;

    update public.capability_audit_runs
       set report = '{}'::jsonb
     where executed_at < now() - interval '72 hours'
       and report is not null
       and report <> '{}'::jsonb;
    get diagnostics trimmed_audits = row_count;

    delete from cron.job_run_details
     where end_time < now() - interval '12 hours';
    get diagnostics trimmed_cron = row_count;
  end if;

  if disk_before >= 0.89 then
    tier := 'prepause_89';
    update public.national_ingestion_storage_guard
       set paused = true,
           pause_reason = case
             when pause_reason is null or pause_reason = 'adaptive_storage_pressure_pre_pause_89'
               then 'adaptive_storage_pressure_pre_pause_89'
             else pause_reason
           end,
           paused_at = coalesce(paused_at, now()),
           updated_at = now()
     where singleton = true
       and not paused;
    prepaused := found;
  end if;

  after_status := public.national_ingestion_storage_status();

  if coalesce((after_status->>'disk_observed_fraction')::numeric, 1) <= 0.84
     and coalesce((after_status->>'database_fraction')::numeric, 1) < 0.70
     and coalesce(after_status->>'pause_reason','') = 'adaptive_storage_pressure_pre_pause_89'
     and coalesce((after_status->>'hard_stop')::boolean, false) = false then
    update public.national_ingestion_storage_guard
       set paused = false,
           pause_reason = null,
           paused_at = null,
           resume_authorized = false,
           resume_authorized_at = null,
           updated_at = now()
     where singleton = true;
    resumed := true;
    after_status := public.national_ingestion_storage_status();
  end if;

  if tier <> 'normal' or resumed then
    insert into internal.storage_pressure_events(
      tier, disk_before, disk_after, database_before, wal_before, action
    ) values (
      tier,
      disk_before,
      coalesce((after_status->>'disk_observed_fraction')::numeric, null),
      db_before,
      wal_before,
      jsonb_build_object(
        'base_compaction', cleanup,
        'run_details_trimmed', trimmed_runs,
        'audit_reports_trimmed', trimmed_audits,
        'cron_history_deleted', trimmed_cron,
        'prepaused', prepaused,
        'resumed', resumed
      )
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'tier', tier,
    'before', before_status,
    'after', after_status,
    'base_compaction', cleanup,
    'run_details_trimmed', trimmed_runs,
    'audit_reports_trimmed', trimmed_audits,
    'cron_history_deleted', trimmed_cron,
    'prepaused', prepaused,
    'resumed', resumed
  );
end;
$$;

revoke all on function internal.run_storage_pressure_controller() from public, anon, authenticated;
grant execute on function internal.run_storage_pressure_controller() to postgres, service_role;

do $$
declare
  j record;
begin
  for j in select jobid from cron.job where jobname in ('kleenest-storage-compaction-daily','kleenest-storage-pressure-controller') loop
    perform cron.unschedule(j.jobid);
  end loop;
end;
$$;

select cron.schedule(
  'kleenest-storage-pressure-controller',
  '*/5 * * * *',
  'select internal.run_storage_pressure_controller();'
);
