revoke execute on function public.enable_enterprise_fleet_service(uuid) from anon, public;
revoke execute on function public.create_qr_engagement_program(uuid,text,text,text,jsonb,integer) from anon, public;
revoke execute on function public.merge_external_location_metadata(uuid,text,text,text,text,text,text,text,text,jsonb) from anon, public;
revoke execute on function public.publish_fleet_route_notification(uuid,text,text,text,jsonb) from anon, public;
revoke execute on function public.publish_intelligence_location_event(uuid,text,text,text,jsonb,integer,text) from anon, public;
revoke execute on function public.quest_create(text,uuid,text,text,jsonb,jsonb,jsonb,timestamptz,timestamptz) from anon, public;
revoke execute on function public.quest_add_step(uuid,integer,text,text,text,uuid,uuid,uuid,boolean,integer,jsonb,jsonb) from anon, public;
revoke execute on function public.quest_set_status(uuid,text) from anon, public;
revoke execute on function public.record_geofence_event(uuid,uuid,uuid,uuid,text,integer,jsonb,uuid,uuid,uuid) from anon, public;
revoke execute on function public.record_network_leaderboard_participation(text,uuid,text,numeric,text,uuid,date,date,jsonb) from anon, public;
revoke execute on function public.sync_business_service_entitlement(uuid) from anon, public;
grant execute on function public.enable_enterprise_fleet_service(uuid) to authenticated;
grant execute on function public.create_qr_engagement_program(uuid,text,text,text,jsonb,integer) to authenticated;
grant execute on function public.merge_external_location_metadata(uuid,text,text,text,text,text,text,text,text,jsonb) to authenticated;
grant execute on function public.publish_fleet_route_notification(uuid,text,text,text,jsonb) to authenticated;
grant execute on function public.publish_intelligence_location_event(uuid,text,text,text,jsonb,integer,text) to authenticated;
grant execute on function public.quest_create(text,uuid,text,text,jsonb,jsonb,jsonb,timestamptz,timestamptz) to authenticated;
grant execute on function public.quest_add_step(uuid,integer,text,text,text,uuid,uuid,uuid,boolean,integer,jsonb,jsonb) to authenticated;
grant execute on function public.quest_set_status(uuid,text) to authenticated;
grant execute on function public.record_geofence_event(uuid,uuid,uuid,uuid,text,integer,jsonb,uuid,uuid,uuid) to authenticated;
grant execute on function public.record_network_leaderboard_participation(text,uuid,text,numeric,text,uuid,date,date,jsonb) to authenticated;
grant execute on function public.sync_business_service_entitlement(uuid) to authenticated;
