create table if not exists public.kleenest_storage_pressure_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  disk_observed_fraction numeric not null,
  database_fraction numeric not null,
  wal_bytes bigint not null,
  tier text not null,
  action jsonb not null default '{}'::jsonb
);

alter table public.kleenest_storage_pressure_events enable row level security;
revoke all on table public.kleenest_storage_pressure_events from anon, authenticated;

create or replace function public.control_kleenest_storage_pressure()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  s jsonb;
  diskf numeric;
  dbf numeric;
  wal bigint;
  tier text := 'normal';
  compact_result jsonb := '{}'::jsonb;
  trimmed_runs bigint := 0;
  trimmed_audits bigint := 0;
  cron_pruned bigint := 0;
  offload_request bigint := null;
  auto_paused boolean := false;
  auto_resumed boolean := false;
begin
  s := public.national_ingestion_storage_status();
  diskf := coalesce((s->>'disk_observed_fraction')::numeric, 1);
  dbf := coalesce((s->>'database_fraction')::numeric, 1);
  wal := coalesce((s->>'wal_bytes')::bigint, 0);

  if diskf >= 0.89 then
    tier := 'critical_pre_pause';

    update public.national_ingestion_storage_guard
       set paused = true,
           pause_reason = 'adaptive_storage_pressure_89_percent',
           paused_at = coalesce(paused_at, now()),
           resume_authorized = false,
           resume_authorized_at = null,
           updated_at = now()
     where singleton = true
       and not paused;
    auto_paused := found;

    compact_result := public.compact_kleenest_storage();

    update public.national_ingestion_runs
       set detail = '{}'::jsonb
     where finished_at < now() - interval '12 hours'
       and detail is not null
       and detail <> '{}'::jsonb;
    get diagnostics trimmed_runs = row_count;

    update public.capability_audit_runs
       set report = '{}'::jsonb
     where executed_at < now() - interval '24 hours'
       and report <> '{}'::jsonb;
    get diagnostics trimmed_audits = row_count;

    delete from cron.job_run_details
     where end_time < now() - interval '3 hours';
    get diagnostics cron_pruned = row_count;

    begin
      offload_request := public.run_cold_provenance_offloader();
    exception when others then
      offload_request := null;
    end;

  elsif diskf >= 0.86 then
    tier := 'aggressive_cleanup';
    compact_result := public.compact_kleenest_storage();

    update public.national_ingestion_runs
       set detail = '{}'::jsonb
     where finished_at < now() - interval '48 hours'
       and detail is not null
       and detail <> '{}'::jsonb;
    get diagnostics trimmed_runs = row_count;

    update public.capability_audit_runs
       set report = '{}'::jsonb
     where executed_at < now() - interval '2 days'
       and report <> '{}'::jsonb;
    get diagnostics trimmed_audits = row_count;

    delete from cron.job_run_details
     where end_time < now() - interval '6 hours';
    get diagnostics cron_pruned = row_count;

    begin
      offload_request := public.run_cold_provenance_offloader();
    exception when others then
      offload_request := null;
    end;

  elsif diskf >= 0.82 then
    tier := 'light_cleanup';
    compact_result := public.compact_kleenest_storage();

    update public.national_ingestion_runs
       set detail = '{}'::jsonb
     where finished_at < now() - interval '7 days'
       and detail is not null
       and detail <> '{}'::jsonb;
    get diagnostics trimmed_runs = row_count;

    delete from cron.job_run_details
     where end_time < now() - interval '12 hours';
    get diagnostics cron_pruned = row_count;

  else
    tier := 'normal';
  end if;

  if diskf <= 0.85 then
    update public.national_ingestion_storage_guard
       set paused = false,
           pause_reason = null,
           paused_at = null,
           updated_at = now()
     where singleton = true
       and paused = true
       and pause_reason = 'adaptive_storage_pressure_89_percent';
    auto_resumed := found;
  end if;

  insert into public.kleenest_storage_pressure_events(
    disk_observed_fraction, database_fraction, wal_bytes, tier, action
  ) values (
    diskf, dbf, wal, tier,
    jsonb_build_object(
      'compact', compact_result,
      'trimmed_ingestion_run_details', trimmed_runs,
      'trimmed_audit_reports', trimmed_audits,
      'cron_history_pruned', cron_pruned,
      'cold_offload_request_id', offload_request,
      'auto_paused', auto_paused,
      'auto_resumed', auto_resumed
    )
  );

  delete from public.kleenest_storage_pressure_events
   where observed_at < now() - interval '14 days';

  return jsonb_build_object(
    'tier', tier,
    'disk_observed_fraction', diskf,
    'database_fraction', dbf,
    'wal_bytes', wal,
    'compact', compact_result,
    'trimmed_ingestion_run_details', trimmed_runs,
    'trimmed_audit_reports', trimmed_audits,
    'cron_history_pruned', cron_pruned,
    'cold_offload_request_id', offload_request,
    'auto_paused', auto_paused,
    'auto_resumed', auto_resumed
  );
end;
$function$;

revoke all on function public.control_kleenest_storage_pressure() from public, anon, authenticated;
grant execute on function public.control_kleenest_storage_pressure() to postgres, service_role;

select cron.schedule(
  'kleenest-storage-pressure-controller',
  '*/5 * * * *',
  $cron$select public.control_kleenest_storage_pressure();$cron$
);

select cron.alter_job(
  (select jobid from cron.job where jobname = 'kleenest-storage-compaction-daily' limit 1),
  active := false
);
