create or replace function public.partner_preferred_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user uuid:=auth.uid(); v_allowed boolean; v_result jsonb; begin if v_user is null then raise exception 'not_authenticated'; end if; select exists(select 1 from business_members where business_id=p_business_id and user_id=v_user and role in ('owner','admin','manager','analyst')) into v_allowed; if not v_allowed and not exists(select 1 from profiles where id=v_user and is_admin) then raise exception 'business_access_required'; end if; select jsonb_build_object('business_id',p_business_id,'period_start',p_start,'period_end',p_end,'total_activations',(select count(*) from preferred_location_activations a join locations l on l.id=a.location_id where l.business_id=p_business_id and a.activated_at between p_start and p_end),'active_activations',(select count(*) from preferred_location_activations a join locations l on l.id=a.location_id where l.business_id=p_business_id and a.deactivated_at is null),'total_uses',(select count(*) from preferred_usage_events e where e.business_id=p_business_id and e.occurred_at between p_start and p_end),'unique_users',(select count(distinct e.user_id) from preferred_usage_events e where e.business_id=p_business_id and e.occurred_at between p_start and p_end),'locations_count',(select count(*) from locations where business_id=p_business_id and is_active),'check_ins',(select count(*) from check_ins ci join locations l on l.id=ci.location_id where l.business_id=p_business_id and ci.checked_in_at between p_start and p_end),'reviews',(select count(*) from reviews r join locations l on l.id=r.location_id where l.business_id=p_business_id and r.created_at between p_start and p_end)) into v_result; return v_result; end $$;

grant execute on function public.partner_preferred_analytics(uuid,timestamptz,timestamptz) to authenticated;

grant execute on function public.business_qr_analytics(uuid) to authenticated;

create or replace function public.business_review_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'reviews',count(*),'average_rating',coalesce(round(avg(r.stars)::numeric,2),0),'average_cleanliness_pct',coalesce(round(avg(r.cleanliness_pct)::numeric,2),0),'published_reviews',count(*) filter(where r.status='published'),'business_replies',count(*) filter(where r.business_reply is not null),'locations_with_reviews',count(distinct r.location_id),'period_reviews',count(*) filter(where r.created_at between p_start and p_end)) from reviews r join locations l on l.id=r.location_id where l.business_id=p_business_id and r.created_at between p_start and p_end and r.status<>'hidden' and (exists(select 1 from business_members bm where bm.business_id=p_business_id and bm.user_id=auth.uid() and bm.role in ('owner','admin','manager','analyst')) or exists(select 1 from profiles p where p.id=auth.uid() and p.is_admin)); $$;
grant execute on function public.business_review_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_media_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'photos',count(*),'vr_media',count(*) filter(where lower(coalesce(lp.media_type,'')) in ('vr','360','360_vr')),'total_bytes',coalesce(sum(coalesce(lp.size_bytes,0)),0),'avg_bytes',coalesce(round(avg(lp.size_bytes))::bigint,0),'locations_with_media',count(distinct lp.location_id),'period_uploads',count(*) filter(where lp.created_at between p_start and p_end)) from location_photos lp join locations l on l.id=lp.location_id where l.business_id=p_business_id and lp.created_at between p_start and p_end and (exists(select 1 from business_members bm where bm.business_id=p_business_id and bm.user_id=auth.uid() and bm.role in ('owner','admin','manager','analyst')) or exists(select 1 from profiles p where p.id=auth.uid() and p.is_admin)); $$;
grant execute on function public.business_media_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_promotion_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'promotions',count(distinct p.id),'active_promotions',count(distinct p.id) filter(where p.active),'promotion_views',count(*) filter(where ae.event_type='promotion_view'),'redemptions',count(*) filter(where ae.event_type='promotion_redeemed'),'unique_redeemers',count(distinct ae.user_id) filter(where ae.event_type='promotion_redeemed'),'conversion_rate_pct',case when count(*) filter(where ae.event_type='promotion_view')=0 then 0 else round((count(*) filter(where ae.event_type='promotion_redeemed')::numeric/count(*) filter(where ae.event_type='promotion_view'))*100,2) end) from promotions p left join analytics_events ae on ae.promotion_id=p.id and ae.created_at between p_start and p_end where p.business_id=p_business_id; $$;
grant execute on function public.business_promotion_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_campaign_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'campaigns',count(distinct c.id),'active_campaigns',count(distinct c.id) filter(where c.status='active'),'outcome_visits',coalesce(sum(o.visits),0),'outcome_check_ins',coalesce(sum(o.check_ins),0),'outcome_reviews',coalesce(sum(o.reviews),0),'attributed_users',coalesce(sum(o.attributed_users),0),'points_awarded',coalesce(sum(o.points_awarded),0)) from enterprise_partner_campaigns c join enterprise_partner_networks n on n.id=c.network_id and n.owner_business_id=p_business_id left join enterprise_partner_campaign_outcomes o on o.campaign_id=c.id and o.metric_date between p_start::date and p_end::date; $$;
grant execute on function public.business_campaign_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_partner_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'partner_programs',count(distinct pp.id),'enabled_programs',count(distinct pp.id) filter(where pp.enabled),'partner_agreements',count(distinct pa.id),'active_agreements',count(distinct pa.id) filter(where pa.status='active'),'preferred_uses',coalesce((select count(*) from preferred_usage_events e where e.business_id=p_business_id and e.occurred_at between p_start and p_end),0),'partner_users',coalesce((select count(distinct ppm.user_id) from partner_program_memberships ppm join partner_programs ppx on ppx.id=ppm.partner_program_id where ppx.business_id=p_business_id and ppm.granted_at between p_start and p_end),0)) from partner_programs pp left join partner_agreements pa on pa.partner_program_id=pp.id where pp.business_id=p_business_id; $$;
grant execute on function public.business_partner_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_rewards_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'check_ins',count(ci.id),'points_awarded',coalesce(sum(ci.points_awarded),0),'reward_events',count(pt.id),'reward_points',coalesce(sum(pt.points),0)) from locations l left join check_ins ci on ci.location_id=l.id and ci.checked_in_at between p_start and p_end left join lateral (select pt.id,pt.points from point_transactions pt where pt.user_id=ci.user_id and pt.created_at between p_start and p_end limit 1) pt on true where l.business_id=p_business_id; $$;
grant execute on function public.business_rewards_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_event_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('events',count(distinct e.id),'rsvps',count(distinct er.user_id),'event_views',count(*) filter(where ae.event_type='location_view'),'event_rsvps_tracked',count(*) filter(where ae.event_type='event_rsvp')) from business_events e left join event_rsvps er on er.event_id=e.id left join analytics_events ae on ae.event_id=e.id and ae.created_at between p_start and p_end where e.business_id=p_business_id and (e.event_date is null or e.event_date between p_start::date and p_end::date); $$;
grant execute on function public.business_event_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_occupancy_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('visits',count(lv.id),'check_ins',count(ci.id),'unique_visitors',count(distinct coalesce(lv.user_id,ci.user_id)),'peak_hour',coalesce((select extract(hour from coalesce(lv2.occurred_at,ci2.checked_in_at))::int from location_visits lv2 full join check_ins ci2 on false join locations lx on lx.id=coalesce(lv2.location_id,ci2.location_id) where lx.business_id=p_business_id and coalesce(lv2.occurred_at,ci2.checked_in_at) between p_start and p_end group by 1 order by count(*) desc limit 1),null)) from locations l left join location_visits lv on lv.location_id=l.id and lv.occurred_at between p_start and p_end left join check_ins ci on ci.location_id=l.id and ci.checked_in_at between p_start and p_end where l.business_id=p_business_id; $$;
grant execute on function public.business_occupancy_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_roi_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('business_id',p_business_id,'revenue',null,'cost_cents',coalesce((select sum(budget_cents) from enterprise_partner_allocations epa join enterprise_partner_networks epn on epn.id=epa.network_id where epn.owner_business_id=p_business_id and epa.created_at between p_start and p_end),0),'attributed_users',coalesce((select count(distinct user_id) from business_engagement_attributions where business_id=p_business_id and created_at between p_start and p_end),0),'roi',null,'roi_status','unavailable_without_revenue_source'); $$;
grant execute on function public.business_roi_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_growth_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ select jsonb_build_object('check_ins',count(ci.id),'unique_users',count(distinct ci.user_id),'reviews',count(distinct r.id),'new_users',count(distinct case when p.created_at between p_start and p_end then p.id end),'locations',count(distinct l.id)) from locations l left join check_ins ci on ci.location_id=l.id and ci.checked_in_at between p_start and p_end left join reviews r on r.location_id=l.id and r.created_at between p_start and p_end left join profiles p on p.id=ci.user_id where l.business_id=p_business_id; $$;
grant execute on function public.business_growth_analytics(uuid,timestamptz,timestamptz) to authenticated;

create or replace function public.business_benchmark_analytics(p_business_id uuid,p_start timestamptz default now()-interval '30 days',p_end timestamptz default now()) returns jsonb language sql security definer set search_path=public,pg_temp as $$ with mine as (select count(ci.id)::numeric check_ins from check_ins ci join locations l on l.id=ci.location_id where l.business_id=p_business_id and ci.checked_in_at between p_start and p_end), allb as (select b.id, count(ci.id)::numeric check_ins from businesses b left join locations l on l.business_id=b.id left join check_ins ci on ci.location_id=l.id and ci.checked_in_at between p_start and p_end group by b.id) select jsonb_build_object('business_check_ins',coalesce((select check_ins from mine),0),'peer_businesses',count(*),'peer_average_check_ins',coalesce(round(avg(check_ins),2),0),'percentile',coalesce(round(100.0*(select check_ins from mine)/(nullif((select max(check_ins) from allb),0)),2),0)) from allb; $$;
grant execute on function public.business_benchmark_analytics(uuid,timestamptz,timestamptz) to authenticated;
