insert into public.capability_feature_contracts(feature_code,canonical_capability,mapping_type,evidence_status,notes) values
('checkin_basic','Consumer check-in','primary','unverified','GPS check-in product feature maps to canonical consumer check-in capability'),
('checkin_qr','Consumer check-in','secondary','unverified','QR check-in is a presentation/input variant of the canonical check-in capability'),
('amenity_verify','Consumer restroom observation','primary','unverified','Amenity verification is represented by the canonical restroom observation capability'),
('bathroom_deep_verification','Bathroom intelligence','primary','unverified','Deep verification consumes bathroom intelligence'),
('location_rate','Consumer review creation','secondary','unverified','Location rating is a review-domain interaction'),
('review_vote','Consumer review creation','secondary','unverified','Review voting is supporting review-domain behavior'),
('location_photo','Consumer restroom observation','secondary','unverified','Location evidence/photo is supporting observation behavior'),
('advanced_routes','Universal location discovery','primary','unverified','Route planning depends on location discovery'),
('admin_data_control','Owner/Admin CRUD gateway','primary','unverified','Administrative data controls use owner/admin gateway'),
('business_workspace','Owner/Admin CRUD gateway','primary','unverified','Business workspace access is administered through owner/admin controls'),
('business_analytics','Owner/Admin CRUD gateway','supporting','unverified','Business analytics is an owner/business operational surface'),
('business_engagement','Owner/Admin CRUD gateway','supporting','unverified','Business engagement is an owner/business operational surface'),
('business_intelligence','Bathroom intelligence','secondary','unverified','Business intelligence consumes platform intelligence'),
('business_qr','Owner/Admin CRUD gateway','supporting','unverified','Business QR is managed through business administration'),
('business_qr_studio','Owner/Admin CRUD gateway','supporting','unverified','QR Studio is managed through business administration'),
('business_custom_notifications','Owner/Admin CRUD gateway','supporting','unverified','Business notification configuration is administrative'),
('enterprise_workspace','Owner/Admin CRUD gateway','primary','unverified','Enterprise workspace access is administrative'),
('enterprise_network_analytics','Owner/Admin CRUD gateway','supporting','unverified','Enterprise analytics is an administrative/operational surface'),
('fleet_workspace','Owner/Admin CRUD gateway','primary','unverified','Fleet workspace access is administrative'),
('fleet_operations','Owner/Admin CRUD gateway','primary','unverified','Fleet operations are administrative/operational actions'),
('fleet_analytics','Owner/Admin CRUD gateway','supporting','unverified','Fleet analytics is an operational surface'),
('fleet_driver_safety','Owner/Admin CRUD gateway','supporting','unverified','Fleet safety scorecards are an operational surface'),
('fleet_intelligence','Bathroom intelligence','secondary','unverified','Fleet intelligence consumes platform intelligence'),
('fleet_maintenance','Owner/Admin CRUD gateway','supporting','unverified','Fleet maintenance is an operational surface'),
('fleet_metric_configuration','Owner/Admin CRUD gateway','supporting','unverified','Fleet metric configuration is administrative'),
('fleet_route_optimization','Universal location discovery','secondary','unverified','Fleet routing depends on universal location discovery'),
('fleet_service_opportunities','Universal location discovery','secondary','unverified','Service opportunities depend on location discovery'),
('fleet_telemetry_ingestion','Owner/Admin CRUD gateway','supporting','unverified','Telemetry ingestion is an operational/admin surface'),
('fleet_vehicle_utilization','Owner/Admin CRUD gateway','supporting','unverified','Vehicle utilization is an operational surface'),
('gamification_badges','Consumer check-in','secondary','unverified','Badges can be earned from engagement/check-in activity'),
('gamification_challenges','Consumer check-in','secondary','unverified','Challenges can use engagement/check-in activity'),
('quest_creator','Owner/Admin CRUD gateway','supporting','unverified','Quest creation is an administrative/business surface')
on conflict (feature_code,canonical_capability) do update set mapping_type=excluded.mapping_type,notes=excluded.notes,updated_at=now();
