create or replace function public.apply_external_amenity_to_location(p_location_id uuid,p_attribute_key text,p_value_text text) returns void language plpgsql security definer set search_path=public as $$ declare aid uuid; v text:=lower(coalesce(p_value_text,'')); k text:=lower(coalesce(p_attribute_key,'')); target_name text; begin if v not in ('yes','true','present','available','limited','24/7') then return; end if; target_name:=case k when 'changing_table' then 'Changing Table' when 'changing_table_present' then 'Changing Table' when 'toilets:wheelchair' then 'Accessible Stall' when 'wheelchair' then 'Accessible' when 'handwashing:soap' then 'Soap' when 'toilets:hands_drying' then 'Hand Dryer' when 'hot_water' then 'Hot Water' when 'toilets:paper_supplied' then 'Paper Towels' when 'drinking_water' then 'Drinking Water' when 'shower' then 'Showers' when 'toilets:menstrual_products' then 'Baby Changing' when 'unisex' then 'Family Restroom' when 'gender_neutral' then 'Family Restroom' when 'opening_hours' then '24 Hours' when 'handwashing:hand_disinfection' then 'Touchless Fixtures' when 'mirror' then 'Mirrors' when 'parking' then 'Parking' when 'internet_access' then 'Free Wi-Fi' when 'vending' then 'Vending' when 'outdoor_seating' then 'Outdoor Seating' when 'pet' then 'Pet Friendly' when 'ev_charging' then 'EV Charging' when 'amenity=toilets' then null else null end; if target_name is not null then select id into aid from public.amenities where lower(name)=lower(target_name) limit 1; if aid is not null then insert into public.location_amenities(location_id,amenity_id) values(p_location_id,aid) on conflict do nothing; end if; end if; if k in ('osm.amenity','amenity','toilets') and v in ('toilets','yes','true') then update public.locations set bathroom_verification_status=case when coalesce(bathroom_verification_status,'') in ('','unverified','pending') then 'externally_sourced' else bathroom_verification_status end, bathroom_verification_source=coalesce(bathroom_verification_source,'osm'), bathroom_verified_at=coalesce(bathroom_verified_at,now()), updated_at=now() where id=p_location_id; end if; end; $$;
insert into public.feature_catalog(feature_code,name,category,minimum_tier,points_value,enabled,configuration) values
('fleet_route_optimization','Fleet Route Optimization','fleet','fleet',0,true,'{"dataset":"fleet_routes","uses":"restroom_coverage,amenities,distance,stops"}'),
('fleet_vehicle_utilization','Vehicle Utilization','fleet','fleet',0,true,'{"dataset":"fleet_vehicle_daily_metrics","metrics":["miles","engine_hours","trips","fuel","energy","idle","utilization"]}'),
('fleet_driver_safety','Driver Safety Scorecards','fleet','fleet',0,true,'{"dataset":"fleet_driver_scorecards","metrics":["safety","efficiency","harsh_braking","harsh_acceleration","speeding","collision","seatbelt"]}'),
('fleet_maintenance','Fleet Maintenance','fleet','fleet',0,true,'{"dataset":"fleet_maintenance_records","metrics":["due","overdue","cost","odometer","service"]}'),
('fleet_service_opportunities','Restroom Service Opportunities','fleet','fleet',0,true,'{"dataset":"fleet_service_opportunities","uses":"amenity_density,verification_freshness,accessibility"}'),
('fleet_telemetry_ingestion','Telematics Ingestion','fleet','fleet',0,true,'{"dataset":"fleet_operational_events","event_types":["gps","mileage","fuel","energy","idle","speeding","hard_braking","collision","diagnostic"]}')
on conflict(feature_code) do update set name=excluded.name,category=excluded.category,minimum_tier=excluded.minimum_tier,enabled=true,configuration=excluded.configuration,updated_at=now();
