revoke execute on function public.create_offline_pack(text,text,uuid,uuid,double precision,double precision,double precision,double precision,integer) from anon;
revoke execute on function public.populate_route_discovery_cache(uuid,jsonb) from anon;
revoke execute on function public.prepare_route_discovery(uuid,integer,integer) from anon;
revoke execute on function public.submit_feedback(text,text,text,text,jsonb) from anon;
revoke execute on function public.touch_updated_at() from anon,authenticated;

create or replace function public.record_location_observation(p_location_id uuid,p_observation_type text,p_latitude double precision default null,p_longitude double precision default null,p_accuracy_m double precision default null,p_evidence jsonb default '{}'::jsonb,p_confidence numeric default null,p_expires_at timestamptz default null)
returns uuid language plpgsql security definer set search_path=public,auth,extensions,pg_temp as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not exists(select 1 from public.locations where id=p_location_id and is_active=true) then raise exception 'location not found'; end if; if p_latitude is not null and (p_latitude < -90 or p_latitude > 90) then raise exception 'invalid latitude'; end if; if p_longitude is not null and (p_longitude < -180 or p_longitude > 180) then raise exception 'invalid longitude'; end if; insert into public.location_observations(location_id,observer_user_id,observation_type,latitude,longitude,accuracy_m,evidence,confidence,expires_at) values(p_location_id,auth.uid(),p_observation_type,p_latitude,p_longitude,p_accuracy_m,coalesce(p_evidence,'{}'::jsonb),p_confidence,p_expires_at) returning id into v_id; return v_id; end $$;

create or replace function public.record_location_filter_event(p_amenity_keys jsonb default '[]'::jsonb,p_result_count integer default 0,p_result_location_ids jsonb default '[]'::jsonb,p_latitude double precision default null,p_longitude double precision default null,p_radius_meters integer default 15000,p_session_id text default null)
returns uuid language plpgsql security definer set search_path=public,auth,extensions,pg_temp as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if p_latitude is not null and (p_latitude < -90 or p_latitude > 90) then raise exception 'invalid latitude'; end if; if p_longitude is not null and (p_longitude < -180 or p_longitude > 180) then raise exception 'invalid longitude'; end if; insert into public.location_filter_events(user_id,session_id,amenity_keys,result_count,result_location_ids,latitude,longitude,radius_meters) values(auth.uid(),p_session_id,coalesce(p_amenity_keys,'[]'::jsonb),greatest(0,coalesce(p_result_count,0)),coalesce(p_result_location_ids,'[]'::jsonb),p_latitude,p_longitude,greatest(1,least(coalesce(p_radius_meters,15000),50000))) returning id into v_id; return v_id; end $$;

create or replace function public.record_feature_access(p_feature_code text,p_outcome text,p_tier_code text default null,p_destination text default null,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path=public,auth,extensions,pg_temp as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; if not exists(select 1 from public.feature_catalog where feature_code=p_feature_code and enabled) then raise exception 'unknown or disabled feature'; end if; if p_outcome not in ('allowed','locked','denied') then raise exception 'invalid feature access outcome'; end if; insert into public.feature_access_events(user_id,feature_code,outcome,tier_code,destination,metadata) values(auth.uid(),p_feature_code,p_outcome,p_tier_code,p_destination,coalesce(p_metadata,'{}'::jsonb)) returning id into v_id; return v_id; end $$;

revoke execute on function public.record_location_observation(uuid,text,double precision,double precision,double precision,jsonb,numeric,timestamptz) from anon;
revoke execute on function public.record_location_filter_event(jsonb,integer,jsonb,double precision,double precision,integer,text) from anon;
revoke execute on function public.submit_feedback(text,text,text,text,jsonb) from anon;
