insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('quest_create(text,uuid,text,text,jsonb,jsonb,jsonb,timestamp with time zone,timestamp with time zone)','rewards_quests','canonical','Canonical quest creation.'),
('quest_add_step(uuid,integer,text,text,text,uuid,uuid,uuid,boolean,integer,jsonb,jsonb)','rewards_quests','canonical','Canonical quest step creation.'),
('quest_set_status(uuid,text)','rewards_quests','canonical','Quest lifecycle status.'),
('quest_start(uuid)','rewards_quests','canonical','Canonical quest participation start.'),
('quest_record_step(uuid,uuid,text,text,jsonb,uuid,uuid,uuid,uuid)','rewards_quests','canonical','Canonical quest progress recording.'),
('quest_advance_activity(uuid,text,uuid,uuid,uuid,uuid,jsonb)','rewards_quests','supporting','Quest activity progression engine.'),
('quest_list_available(integer)','rewards_quests','supporting','Available quest discovery.'),
('quest_list_creator(text,uuid)','rewards_quests','supporting','Creator quest management listing.'),
('quest_creator_authorized(text,uuid)','rewards_quests','supporting','Quest creator authorization.'),
('quest_trigger_geofence(uuid,uuid,text,integer,jsonb)','rewards_quests','supporting','Geofence quest trigger.'),
('quest_trigger_qr(uuid,uuid,uuid,jsonb)','rewards_quests','supporting','QR quest trigger.'),
('quest_leaderboard(uuid,integer)','rewards_quests','canonical','Quest-specific progression leaderboard.'),
('evaluate_user_badges(uuid)','rewards_quests','canonical','Badge evaluation after progression activity.'),
('record_gamification_activity(text,uuid)','rewards_quests','canonical','Canonical gamification activity record.'),
('user_rewards_history(integer)','rewards_quests','supporting','Consumer rewards history.'),
('checkin_rewards_summary(uuid)','rewards_quests','supporting','Check-in-derived reward summary.'),
('review_rewards_summary(uuid)','rewards_quests','supporting','Review-derived reward summary.'),
('promotion_redemption_rewards_summary(uuid)','rewards_quests','supporting','Promotion-derived reward summary.'),
('gamification_activity_trigger()','rewards_quests','trigger_helper','Gamification activity trigger.'),
('trg_quest_checkin_activity()','rewards_quests','trigger_helper','Quest check-in trigger.'),
('trg_quest_review_activity()','rewards_quests','trigger_helper','Quest review trigger.'),
('trg_quest_progression_game_activity()','rewards_quests','trigger_helper','Quest progression trigger.'),
('can_participate_community_activity(text)','community','canonical','Community participation eligibility.'),
('user_notifications(integer)','notifications','canonical','Canonical user notification retrieval.'),
('mark_notification_read(uuid)','notifications','canonical','Canonical notification read state mutation.'),
('mark_all_notifications_read()','notifications','canonical','Canonical bulk notification read mutation.'),
('create_intelligence_notification(uuid,uuid,text,text,text,text,text,jsonb,integer)','notifications','canonical','Canonical intelligence notification creation.'),
('publish_location_notification(text,uuid,jsonb,text,timestamp with time zone)','notifications','supporting','Location notification publication.'),
('create_gps_geofence_notification(uuid,integer,text)','notifications','supporting','Geofence notification creation.'),
('register_notification_push_subscription(text,jsonb)','notifications','canonical','Push subscription registration.'),
('remove_notification_push_subscription(text)','notifications','canonical','Push subscription removal.'),
('queue_notification_delivery(uuid,uuid,text)','notifications','supporting','Notification delivery queueing.'),
('queue_push_deliveries_for_notification(uuid)','notifications','supporting','Push delivery queueing.'),
('resolve_nearby_notification_recipients(uuid,integer)','notifications','supporting','Notification recipient resolution.'),
('send_prioritized_notification_batch(uuid,uuid[],text,text,text,jsonb)','notifications','supporting','Prioritized notification delivery.'),
('materialize_notification_event(uuid)','notifications','supporting','Notification event materialization.'),
('process_intelligence_notification_jobs(integer)','notifications','supporting','Notification job processor.'),
('queue_intelligence_notification_jobs()','notifications','trigger_helper','Notification job queue trigger.'),
('enqueue_notification_push_delivery()','notifications','trigger_helper','Push delivery trigger.'),
('business_rewards_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Business rewards analytics.'),
('business_request_partner_agreement(uuid,uuid)','business_partnerships','supporting','Partner agreement request.'),
('request_account_deletion(text)','account_lifecycle','canonical','Canonical account deletion request.')
on conflict(function_signature) do update set domain=excluded.domain, classification=excluded.classification, rationale=excluded.rationale, updated_at=now();
