create table if not exists public.external_data_sources (id uuid primary key default gen_random_uuid(),source_key text not null unique,name text not null,source_url text,license_name text,license_url text,attribution_text text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.external_location_records (id uuid primary key default gen_random_uuid(),source_id uuid not null references public.external_data_sources(id) on delete cascade,external_id text not null,record_type text not null default 'place',location_id uuid references public.locations(id) on delete set null,latitude double precision,longitude double precision,name text,raw_data jsonb not null default '{}'::jsonb,first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),source_updated_at timestamptz,active boolean not null default true,unique(source_id,external_id));
create index if not exists external_location_records_location_idx on public.external_location_records(location_id);
create index if not exists external_location_records_coords_idx on public.external_location_records(latitude,longitude);
create table if not exists public.external_observations (id uuid primary key default gen_random_uuid(),source_id uuid not null references public.external_data_sources(id) on delete cascade,external_record_id uuid not null references public.external_location_records(id) on delete cascade,location_id uuid references public.locations(id) on delete set null,attribute_key text not null,value_text text,value_numeric numeric,value_boolean boolean,value_json jsonb,observed_at timestamptz not null default now(),imported_at timestamptz not null default now(),confidence numeric not null default 0.75 check(confidence between 0 and 1),verification_state text not null default 'externally_sourced' check(verification_state in ('externally_sourced','kleenest_confirmed','business_confirmed','conflicted','stale')),provenance jsonb not null default '{}'::jsonb,unique(source_id,external_record_id,attribute_key));
create index if not exists external_observations_location_idx on public.external_observations(location_id);
create index if not exists external_observations_attribute_idx on public.external_observations(attribute_key);
insert into public.external_data_sources(source_key,name,source_url,license_name,license_url,attribution_text) values('osm','OpenStreetMap','https://www.openstreetmap.org/','Open Database License (ODbL)','https://www.openstreetmap.org/copyright','© OpenStreetMap contributors') on conflict(source_key) do update set source_url=excluded.source_url,license_name=excluded.license_name,license_url=excluded.license_url,attribution_text=excluded.attribution_text,updated_at=now();
create or replace function public.ingest_osm_locations(p_rows jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare source_id uuid; item jsonb; ext_id text; rec_id uuid; loc_id uuid; lat double precision; lng double precision; nm text; place_type text; address text; city text; state text; postal text; phone text; website text; osm_amenity text; v text; imported integer:=0; updated integer:=0; observations integer:=0; source_meta jsonb;
begin
 if jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)>500 then raise exception 'p_rows must be an array containing at most 500 records'; end if;
 select id into source_id from public.external_data_sources where source_key='osm' and active=true; if source_id is null then raise exception 'OSM source is not configured'; end if;
 for item in select value from jsonb_array_elements(p_rows) loop
  ext_id:=nullif(item->>'source_id',''); lat:=nullif(item->>'latitude','')::double precision; lng:=nullif(item->>'longitude','')::double precision;
  if ext_id is null or lat is null or lng is null or lat not between -90 and 90 or lng not between -180 and 180 then continue; end if;
  nm:=coalesce(nullif(item->>'name',''),'Public Place'); place_type:=coalesce(nullif(item->>'place_type',''),'place'); address:=nullif(item->>'address',''); city:=nullif(item->>'city',''); state:=nullif(item->>'state',''); postal:=nullif(item->>'postal_code',''); phone:=nullif(item->>'phone',''); website:=nullif(item->>'website',''); source_meta:=coalesce(item->'source_metadata','{}'::jsonb);
  select location_id into loc_id from public.external_location_records where source_id=source_id and external_id=ext_id limit 1;
  if loc_id is null then select l.id into loc_id from public.locations l where l.latitude is not null and l.longitude is not null and abs(l.latitude-lat)<0.0005 and abs(l.longitude-lng)<0.0005 and lower(coalesce(l.name,''))=lower(nm) limit 1; end if;
  if loc_id is null then insert into public.locations(name,address,city,state,postal_code,country,latitude,longitude,place_type,phone,website,source,source_dataset,source_external_id,source_metadata,bathroom_verification_source,bathroom_verification_status,is_active,created_at,updated_at) values(nm,address,city,state,postal,'US',lat,lng,place_type,phone,website,'osm','OpenStreetMap',ext_id,source_meta,'osm','pending',true,now(),now()) returning id into loc_id; imported:=imported+1;
  else update public.locations set name=coalesce(nullif(name,''),nm),address=coalesce(nullif(address,''),address),city=coalesce(nullif(city,''),city),state=coalesce(nullif(state,''),state),postal_code=coalesce(nullif(postal_code,''),postal),phone=coalesce(nullif(phone,''),phone),website=coalesce(nullif(website,''),website),latitude=coalesce(latitude,lat),longitude=coalesce(longitude,lng),source_dataset=coalesce(source_dataset,'OpenStreetMap'),source_external_id=coalesce(source_external_id,ext_id),source_metadata=coalesce(source_metadata,'{}'::jsonb)||source_meta,updated_at=now() where id=loc_id; updated:=updated+1; end if;
  insert into public.external_location_records(source_id,external_id,record_type,location_id,latitude,longitude,name,raw_data,last_seen_at) values(source_id,ext_id,place_type,loc_id,lat,lng,nm,item,now()) on conflict(source_id,external_id) do update set location_id=excluded.location_id,latitude=excluded.latitude,longitude=excluded.longitude,name=excluded.name,raw_data=excluded.raw_data,last_seen_at=now(),active=true returning id into rec_id;
  osm_amenity:=nullif(item->>'osm_amenity','');
  if osm_amenity='toilets' then update public.locations set bathroom_verification_source='osm',bathroom_verification_status='pending',bathroom_verified_at=now(),source_metadata=coalesce(source_metadata,'{}'::jsonb)||jsonb_build_object('osm_bathroom_observation',true) where id=loc_id; end if;
  for v in select key from jsonb_each_text(coalesce(item->'observations','{}'::jsonb)) loop
    insert into public.external_observations(source_id,external_record_id,location_id,attribute_key,value_text,confidence,provenance) values(source_id,rec_id,loc_id,v,(item->'observations')->>v,0.80,jsonb_build_object('source','OpenStreetMap','source_id',ext_id)) on conflict(source_id,external_record_id,attribute_key) do update set value_text=excluded.value_text,observed_at=now(),imported_at=now(),confidence=excluded.confidence,verification_state='externally_sourced',provenance=excluded.provenance; observations:=observations+1;
  end loop;
  insert into public.data_feature_events(subject_type,subject_id,event_type,feature_code,source_table,source_id,value_numeric,value_text,metadata,occurred_at) values('location',loc_id,'external_data_import','maps.external.osm','external_location_records',rec_id,1,'OpenStreetMap',jsonb_build_object('external_id',ext_id,'place_type',place_type),now());
 end loop;
 return jsonb_build_object('imported_locations',imported,'updated_locations',updated,'observations_upserted',observations);
end; $$;
revoke all on function public.ingest_osm_locations(jsonb) from public; grant execute on function public.ingest_osm_locations(jsonb) to anon,authenticated;
alter table public.external_data_sources enable row level security; alter table public.external_location_records enable row level security; alter table public.external_observations enable row level security;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='external_data_sources' and policyname='external_sources_read') then create policy external_sources_read on public.external_data_sources for select using(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='external_location_records' and policyname='external_records_read') then create policy external_records_read on public.external_location_records for select using(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='external_observations' and policyname='external_observations_read') then create policy external_observations_read on public.external_observations for select using(true); end if;
end $$;
