revoke execute on function public.admin_set_user_access(uuid, boolean, text, text, boolean, text) from anon;
revoke execute on function public.admin_user_search(text) from anon;
revoke execute on function public.admin_set_account_capabilities(uuid, text, text, boolean, boolean, boolean, text) from anon;
revoke execute on function public.admin_set_business_tier(uuid, public.business_tier) from anon;
revoke execute on function public.admin_set_business_verification(uuid, public.verification_status) from anon;
revoke execute on function public.admin_crud_gateway(text, text, uuid, jsonb) from anon;
revoke execute on function public.admin_data_integrity_summary() from anon;
revoke execute on function public.admin_get_overview() from anon;
revoke execute on function public.admin_list_pending_businesses() from anon;
revoke execute on function public.admin_list_reports() from anon;
revoke execute on function public.business_create_location(uuid, text) from anon;
revoke execute on function public.business_create_location(uuid, text, text, text, text, numeric, numeric) from anon;
revoke execute on function public.business_create_location(uuid, text, text, text, text, text, numeric, numeric, text, text) from anon;
revoke execute on function public.business_create_promotion(uuid, text) from anon;
revoke execute on function public.business_create_promotion(uuid, uuid, text, text, text, timestamptz, timestamptz) from anon;
revoke execute on function public.business_create_promotion(uuid, text, text, numeric, uuid, timestamptz, timestamptz) from anon;
revoke execute on function public.business_create_qr(uuid, uuid, text) from anon;
revoke execute on function public.business_create_custom_qr(uuid, uuid, text, text, text, jsonb, jsonb, boolean, integer) from anon;
revoke execute on function public.business_delete_campaign(uuid, uuid) from anon;
revoke execute on function public.business_delete_contest(uuid, uuid) from anon;
revoke execute on function public.business_delete_event(uuid, uuid) from anon;
revoke execute on function public.business_delete_media(uuid, uuid) from anon;
revoke execute on function public.business_delete_promotion(uuid, uuid) from anon;
revoke execute on function public.business_delete_qr(uuid, uuid) from anon;
revoke execute on function public.business_manage_campaign(uuid, uuid, text, text, text, text, text) from anon;
revoke execute on function public.business_manage_event(uuid, uuid, text, jsonb) from anon;
revoke execute on function public.business_manage_location(uuid, uuid, text, jsonb) from anon;
revoke execute on function public.business_manage_promotion(uuid, uuid, text, jsonb) from anon;
revoke execute on function public.business_manage_qr(uuid, uuid, uuid, text, jsonb) from anon;
revoke execute on function public.business_update_campaign(uuid, uuid, text, text, text, text) from anon;
revoke execute on function public.business_update_contest(uuid, uuid, text, text, timestamptz, timestamptz, jsonb, jsonb, text) from anon;
revoke execute on function public.business_update_custom_qr(uuid, uuid, text, text, text, jsonb, jsonb, boolean, boolean, integer) from anon;
revoke execute on function public.business_update_event(uuid, uuid, uuid, text, text, date, time) from anon;
revoke execute on function public.business_update_location(uuid, uuid, text, text, text, text, boolean) from anon;
revoke execute on function public.business_update_media(uuid, uuid, text, text, text, integer) from anon;
revoke execute on function public.business_update_partner_program(uuid, uuid, text, boolean) from anon;
revoke execute on function public.business_update_partnership(uuid, uuid, text, boolean, boolean, numeric, text) from anon;
revoke execute on function public.business_update_promotion(uuid, uuid, text, text, text, boolean) from anon;
revoke execute on function public.business_set_location_active(uuid, uuid, boolean) from anon;
revoke execute on function public.business_set_qr_active(uuid, uuid, boolean) from anon;
revoke execute on function public.business_set_promotion_active(uuid, uuid, boolean) from anon;
revoke execute on function public.set_business_location_status(uuid, uuid, boolean) from anon;
revoke execute on function public.set_business_qr_customization(uuid, uuid, jsonb) from anon;
revoke execute on function public.set_business_qr_status(uuid, uuid, boolean) from anon;
revoke execute on function public.set_location_qr_customization(uuid, text, jsonb) from anon;
revoke execute on function public.set_qr_active(uuid, boolean) from anon;
revoke execute on function public.create_check_in(uuid, text) from anon;
revoke execute on function public.verify_checkin(text, double precision, double precision) from anon;
revoke execute on function public.record_gps_checkin(double precision, double precision, integer) from anon;
revoke execute on function public.record_location_verification(uuid, boolean, double precision, double precision, text) from anon;
revoke execute on function public.record_bathroom_verification(uuid, boolean, double precision, double precision, double precision) from anon;
revoke execute on function public.submit_restroom_observation(uuid, uuid, text, numeric, text) from anon;
revoke execute on function public.submit_location_quality_observation(uuid, smallint, numeric, numeric, numeric, numeric, numeric, text, uuid, uuid, jsonb) from anon;
revoke execute on function public.submit_amenity_observation(uuid, uuid, text, numeric, text, uuid, uuid, text, jsonb) from anon;
