REVOKE EXECUTE ON FUNCTION public.business_location_metrics(uuid, uuid, text, timestamptz, timestamptz) FROM anon;
REVOKE EXECUTE ON FUNCTION public.business_partner_program_usage(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.business_preferred_location_summary() FROM anon;
REVOKE EXECUTE ON FUNCTION public.business_preferred_location_usage(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.business_reply_review(uuid, uuid, text) FROM anon;

CREATE OR REPLACE FUNCTION public.business_location_metrics(p_business_id uuid,p_location_id uuid,p_dataset text,p_start timestamptz DEFAULT (now()-interval '30 days'),p_end timestamptz DEFAULT now()) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$
declare r jsonb; begin
if auth.uid() is null then raise exception 'Authentication required'; end if;
if not exists(select 1 from public.business_members bm where bm.business_id=p_business_id and bm.user_id=auth.uid() and bm.role::text in ('owner','admin','manager','analyst')) and not exists(select 1 from public.profiles pr where pr.id=auth.uid() and coalesce(pr.is_admin,false)) then raise exception 'Not authorized for this business'; end if;
if not exists(select 1 from public.locations l where l.id=p_location_id and l.business_id=p_business_id) then raise exception 'Location does not belong to business'; end if;
if p_dataset='overview' then select jsonb_build_object('views',coalesce((select count(*) from public.location_visits v where v.location_id=p_location_id and v.occurred_at between p_start and p_end),0),'check_ins',coalesce((select count(*) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),0),'reviews',coalesce((select count(*) from public.reviews rv where rv.location_id=p_location_id and rv.created_at between p_start and p_end),0),'qr_scans',coalesce((select count(*) from public.qr_codes q where q.location_id=p_location_id and q.created_at<=p_end),0)) into r;
elsif p_dataset='engagement' then select jsonb_build_object('visits',count(*),'check_ins',(select count(*) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),'reviews',(select count(*) from public.reviews rv where rv.location_id=p_location_id and rv.created_at between p_start and p_end),'unique_users',(select count(distinct c.user_id) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end)) into r from public.location_visits v where v.location_id=p_location_id and v.occurred_at between p_start and p_end;
elsif p_dataset in ('qr','visitors') then select jsonb_build_object('qr_scans',(select count(*) from public.qr_codes q where q.location_id=p_location_id and q.created_at<=p_end),'check_ins',(select count(*) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),'unique_users',(select count(distinct c.user_id) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),'visits',(select count(*) from public.location_visits v where v.location_id=p_location_id and v.occurred_at between p_start and p_end)) into r;
elsif p_dataset='reviews' then select jsonb_build_object('reviews',count(*),'average_rating',coalesce(avg(stars),0),'average_cleanliness_pct',coalesce(avg(cleanliness_pct),0),'published_reviews',count(*) filter(where status::text='published'),'business_replies',count(*) filter(where business_reply is not null and length(trim(business_reply))>0)) into r from public.reviews where location_id=p_location_id and created_at between p_start and p_end;
elsif p_dataset='photos' then select jsonb_build_object('photos',count(*),'vr_media',count(*) filter(where lower(coalesce(media_type,'')) in('vr','360','360_vr')),'locations_with_media',case when count(*)>0 then 1 else 0 end,'period_uploads',count(*)) into r from public.location_photos where location_id=p_location_id and created_at between p_start and p_end;
elsif p_dataset='promotions' then select jsonb_build_object('promotions',count(*),'active_promotions',count(*) filter(where active=true and (ends_at is null or ends_at>=p_start)),'promotion_views',0,'redemptions',0,'unique_redeemers',0,'conversion_rate_pct',0) into r from public.promotions where business_id=p_business_id and location_id=p_location_id and created_at between p_start and p_end;
elsif p_dataset='events' then select jsonb_build_object('events',count(*),'rsvps',0,'event_views',0,'event_rsvps_tracked',0) into r from public.business_events where business_id=p_business_id and location_id=p_location_id and created_at between p_start and p_end;
elsif p_dataset='contests' then select jsonb_build_object('contests',count(*),'active_contests',count(*) filter(where status='active')) into r from public.contests where business_id=p_business_id and created_at between p_start and p_end;
elsif p_dataset='occupancy' then select jsonb_build_object('visits',count(*),'check_ins',(select count(*) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),'unique_visitors',(select count(distinct c.user_id) from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end),'peak_hour',(select extract(hour from v2.occurred_at)::int from public.location_visits v2 where v2.location_id=p_location_id and v2.occurred_at between p_start and p_end group by extract(hour from v2.occurred_at) order by count(*) desc limit 1)) into r from public.location_visits v where v.location_id=p_location_id and v.occurred_at between p_start and p_end;
elsif p_dataset='growth' then select jsonb_build_object('check_ins',count(*),'unique_users',count(distinct c.user_id),'reviews',(select count(*) from public.reviews rv where rv.location_id=p_location_id and rv.created_at between p_start and p_end),'new_users',0,'locations',1,'active_locations',case when (select is_active from public.locations where id=p_location_id) then 1 else 0 end) into r from public.check_ins c where c.location_id=p_location_id and c.checked_in_at between p_start and p_end;
elsif p_dataset='verification' then select jsonb_build_object('bathroom_verification_status',l.bathroom_verification_status,'bathroom_verification_count',coalesce(l.bathroom_verification_count,0),'bathroom_positive_count',coalesce(l.bathroom_positive_count,0),'bathroom_negative_count',coalesce(l.bathroom_negative_count,0),'verification_source',l.bathroom_verification_source) into r from public.locations l where l.id=p_location_id and l.business_id=p_business_id;
elsif p_dataset='tier' then select jsonb_build_object('business_tier',b.business_tier::text,'location_count',(select count(*) from public.locations l where l.business_id=p_business_id and l.is_active is distinct from false),'verification_status',b.verification_status::text) into r from public.businesses b where b.id=p_business_id;
else r=jsonb_build_object('message','This dataset uses business-level intelligence and is not reducible to a duplicate location KPI.','location_id',p_location_id); end if; return coalesce(r,'{}'::jsonb); end;$function$;

CREATE OR REPLACE FUNCTION public.business_reply_review(p_business_id uuid,p_review_id uuid,p_reply text) RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'public','pg_temp' AS $function$ declare r public.reviews; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; update public.reviews rv set business_reply=trim(p_reply),business_replied_at=case when nullif(trim(p_reply),'') is null then null else now() end,updated_at=now() where rv.id=p_review_id and rv.location_id in(select l.id from public.locations l where l.business_id=p_business_id); if not found then raise exception 'Review not found or not owned by this business'; end if; select * into r from public.reviews where id=p_review_id; return to_jsonb(r); end;$function$;

CREATE OR REPLACE FUNCTION public.business_set_promotion_active(p_promotion_id uuid,p_active boolean) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_business uuid; begin select business_id into v_business from public.promotions where id=p_promotion_id; if v_business is null then raise exception 'Promotion not found'; end if; if not public.business_can_manage(v_business) then raise exception 'Business management access required'; end if; if not public.business_advanced_allowed(v_business) then raise exception 'Business Growth or Enterprise plan required'; end if; update public.promotions set active=p_active where id=p_promotion_id and business_id=v_business; return found; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_location(p_business_id uuid,p_name text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; insert into public.locations(business_id,name,is_active,created_by) values(p_business_id,trim(p_name),true,auth.uid()) returning id into v_id; return v_id; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_promotion(p_business_id uuid,p_title text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required'; end if; insert into public.promotions(business_id,title,active,created_at) values(p_business_id,trim(p_title),true,now()) returning id into v_id; return v_id; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_qr(p_business_id uuid,p_location_id uuid,p_label text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required'; end if; if not exists(select 1 from public.locations where id=p_location_id and business_id=p_business_id) then raise exception 'Location does not belong to business'; end if; insert into public.qr_codes(location_id,code,active,label,customization) values(p_location_id,encode(gen_random_bytes(12),'hex'),true,trim(p_label),'{}'::jsonb) returning id into v_id; return v_id; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_event(p_business_id uuid,p_title text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required'; end if; insert into public.business_events(business_id,title,created_at) values(p_business_id,trim(p_title),now()) returning id into v_id; return v_id; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_partner_program(p_business_id uuid,p_name text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not exists(select 1 from public.businesses b where b.id=p_business_id and b.business_tier::text='enterprise') then raise exception 'Business Enterprise plan required'; end if; insert into public.partner_programs(business_id,name,enabled) values(p_business_id,trim(p_name),true) returning id into v_id; return v_id; end;$function$;

CREATE OR REPLACE FUNCTION public.business_create_partnership(p_business_id uuid,p_name text,p_enabled boolean DEFAULT false,p_preferred_access boolean DEFAULT false,p_match_discount_bonus numeric DEFAULT 0,p_custom_perk text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $function$ declare v_id uuid; begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not exists(select 1 from public.businesses b where b.id=p_business_id and b.business_tier::text='enterprise') then raise exception 'Business Enterprise plan required'; end if; insert into public.partner_programs(business_id,name,enabled,preferred_access,match_discount_bonus,custom_perk) values(p_business_id,trim(p_name),p_enabled,p_preferred_access,coalesce(p_match_discount_bonus,0),p_custom_perk) returning id into v_id; return v_id; end;$function$;
