create or replace function public.business_create_campaign(p_business_id uuid,p_name text,p_campaign_type text default 'engagement',p_goal text default null,p_status text default 'draft') returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_network uuid;v_id uuid;begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required'; end if; if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required'; end if; select id into v_network from public.enterprise_partner_networks where owner_business_id=p_business_id order by created_at limit 1;if v_network is null then insert into public.enterprise_partner_networks(owner_business_id,name,enabled) values(p_business_id,'Kleenest Partner Network',true) returning id into v_network;end if;insert into public.enterprise_partner_campaigns(network_id,name,campaign_type,goal,status) values(v_network,trim(p_name),coalesce(nullif(trim(p_campaign_type),''),'engagement'),p_goal,coalesce(nullif(trim(p_status),''),'draft')) returning id into v_id;return v_id;end;$$;

create or replace function public.business_update_campaign(p_business_id uuid,p_campaign_id uuid,p_name text,p_campaign_type text,p_goal text,p_status text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;update public.enterprise_partner_campaigns c set name=trim(p_name),campaign_type=coalesce(nullif(trim(p_campaign_type),''),campaign_type),goal=p_goal,status=coalesce(nullif(trim(p_status),''),status) where c.id=p_campaign_id and c.network_id in(select id from public.enterprise_partner_networks where owner_business_id=p_business_id);if not found then raise exception 'Campaign not found';end if;return p_campaign_id;end;$$;

create or replace function public.business_delete_campaign(p_business_id uuid,p_campaign_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;delete from public.enterprise_partner_campaigns c where c.id=p_campaign_id and c.network_id in(select id from public.enterprise_partner_networks where owner_business_id=p_business_id);if not found then raise exception 'Campaign not found';end if;return true;end;$$;

create or replace function public.business_create_event(p_business_id uuid,p_location_id uuid,p_title text,p_description text,p_event_date date,p_event_time time) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare v_id uuid;begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;if p_location_id is not null and not exists(select 1 from public.locations where id=p_location_id and business_id=p_business_id) then raise exception 'Location does not belong to business';end if;insert into public.business_events(business_id,location_id,title,description,event_date,event_time) values(p_business_id,p_location_id,trim(p_title),p_description,p_event_date,p_event_time) returning id into v_id;return v_id;end;$$;

create or replace function public.business_update_event(p_business_id uuid,p_event_id uuid,p_location_id uuid,p_title text,p_description text,p_event_date date,p_event_time time) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;if p_location_id is not null and not exists(select 1 from public.locations where id=p_location_id and business_id=p_business_id) then raise exception 'Location does not belong to business';end if;update public.business_events set location_id=p_location_id,title=trim(p_title),description=p_description,event_date=p_event_date,event_time=p_event_time where id=p_event_id and business_id=p_business_id;if not found then raise exception 'Event not found';end if;return p_event_id;end;$$;

create or replace function public.business_delete_event(p_business_id uuid,p_event_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;delete from public.business_events where id=p_event_id and business_id=p_business_id;if not found then raise exception 'Event not found';end if;return true;end;$$;

create or replace function public.business_create_promotion(p_business_id uuid,p_location_id uuid,p_title text,p_description text,p_discount text,p_starts_at timestamptz,p_ends_at timestamptz) returns public.promotions language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.promotions;begin if auth.uid() is null then raise exception 'Authentication required';end if;if not public.business_can_manage(p_business_id) then raise exception 'Not authorized for this business';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;if p_location_id is not null and not exists(select 1 from public.locations l where l.id=p_location_id and l.business_id=p_business_id) then raise exception 'Location does not belong to business';end if;if p_title is null or trim(p_title)='' then raise exception 'Promotion title is required';end if;if p_ends_at is not null and p_starts_at is not null and p_ends_at<=p_starts_at then raise exception 'Promotion end must be after start';end if;insert into public.promotions(business_id,location_id,title,description,discount,starts_at,ends_at,active) values(p_business_id,p_location_id,trim(p_title),nullif(trim(p_description),''),nullif(trim(p_discount),''),p_starts_at,p_ends_at,true) returning * into v;return v;end;$$;

create or replace function public.business_update_promotion(p_business_id uuid,p_id uuid,p_title text,p_description text,p_discount text,p_active boolean) returns public.promotions language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.promotions;begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;update public.promotions p set title=nullif(trim(p_title),''),description=p_description,discount=p_discount,active=p_active where p.id=p_id and p.business_id=p_business_id returning p.* into v;if v.id is null then raise exception 'Promotion not found';end if;return v;end;$$;

create or replace function public.business_delete_promotion(p_business_id uuid,p_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;delete from public.promotions p where p.id=p_id and p.business_id=p_business_id;return found;end;$$;

create or replace function public.business_create_custom_qr(p_business_id uuid,p_location_id uuid,p_label text,p_purpose text default 'checkin',p_action_type text default 'checkin',p_action_payload jsonb default '{}'::jsonb,p_customization jsonb default '{}'::jsonb) returns public.qr_codes language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.qr_codes;begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;if not exists(select 1 from public.locations l where l.id=p_location_id and l.business_id=p_business_id) then raise exception 'Location does not belong to business';end if;insert into public.qr_codes(location_id,code,label,active,customization,purpose,action_type,action_payload) values(p_location_id,encode(gen_random_bytes(12),'hex'),nullif(trim(p_label),''),true,coalesce(p_customization,'{}'::jsonb),coalesce(nullif(trim(p_purpose),''),'custom'),coalesce(nullif(trim(p_action_type),''),'custom'),coalesce(p_action_payload,'{}'::jsonb)) returning * into v;return v;end;$$;

create or replace function public.business_update_custom_qr(p_business_id uuid,p_qr_id uuid,p_label text,p_purpose text,p_action_type text,p_action_payload jsonb,p_customization jsonb,p_active boolean default true) returns public.qr_codes language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.qr_codes;begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;update public.qr_codes q set label=nullif(trim(p_label),''),purpose=coalesce(nullif(trim(p_purpose),''),'custom'),action_type=coalesce(nullif(trim(p_action_type),''),'custom'),action_payload=coalesce(p_action_payload,'{}'::jsonb),customization=coalesce(p_customization,'{}'::jsonb),active=p_active where q.id=p_qr_id and exists(select 1 from public.locations l where l.id=q.location_id and l.business_id=p_business_id) returning q.* into v;if v.id is null then raise exception 'QR code not found';end if;return v;end;$$;

create or replace function public.business_delete_qr(p_business_id uuid,p_qr_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin if not public.business_can_manage(p_business_id) then raise exception 'Business management access required';end if;if not public.business_advanced_allowed(p_business_id) then raise exception 'Business Growth or Enterprise plan required';end if;delete from public.qr_codes q where q.id=p_qr_id and exists(select 1 from public.locations l where l.id=q.location_id and l.business_id=p_business_id);return found;end;$$;
