insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('award_business_progression_perk(uuid,text,uuid)','business_progression','supporting','Business progression perk award.'),
('business_add_program_location(uuid,uuid)','enterprise_partnerships','canonical','Canonical partner-program location membership.'),
('business_add_program_member(uuid,uuid)','enterprise_partnerships','canonical','Canonical partner-program member management.'),
('business_create_single_use_access_offer(uuid,text,text,integer,integer,timestamp with time zone)','qr_access','canonical','Canonical single-use access offer creation.'),
('business_enroll_program_user(uuid,uuid)','enterprise_partnerships','canonical','Canonical program-user enrollment.'),
('business_preferred_location_summary()','preferred_locations','supporting','Business preferred-location summary.'),
('business_remove_program_location(uuid,uuid)','enterprise_partnerships','canonical','Canonical partner-program location removal.'),
('business_revoke_program_member(uuid,uuid)','enterprise_partnerships','canonical','Canonical partner-program member revocation.'),
('capability_classification_summary()','architecture_governance','canonical','Canonical capability inventory summary.'),
('capability_retirement_audit(integer)','architecture_governance','canonical','Canonical automated retirement gate.'),
('check_single_capability_per_domain()','architecture_governance','canonical','Automated single-capability-per-domain governance check.'),
('enroll_program_location(uuid,uuid)','enterprise_partnerships','compatibility','Older program-location enrollment signature.'),
('enterprise_delete_campaign(uuid)','enterprise_partnerships','canonical','Enterprise campaign deletion.'),
('enterprise_delete_network(uuid)','enterprise_partnerships','canonical','Enterprise network deletion.'),
('enterprise_list_network_campaigns(uuid)','enterprise_partnerships','supporting','Enterprise network campaign listing.'),
('enterprise_list_network_members(uuid)','enterprise_partnerships','supporting','Enterprise network member listing.'),
('enterprise_list_owned_networks(uuid)','enterprise_partnerships','supporting','Enterprise owned-network listing.'),
('enterprise_update_campaign(uuid,text,text,text,text)','enterprise_partnerships','canonical','Enterprise campaign update.'),
('enterprise_update_network(uuid,text,boolean)','enterprise_partnerships','canonical','Enterprise network update.'),
('get_business_engagement_funnel(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Business engagement funnel analytics.'),
('get_single_use_access_offers()','qr_access','supporting','Single-use access offer listing.'),
('list_my_demo_programs()','legacy_demo','legacy','Legacy demo program listing.'),
('list_program_locations(uuid)','enterprise_partnerships','supporting','Partner-program location listing.'),
('location_favorite_counts(uuid[])','location_analytics','supporting','Favorite-location aggregate counts.'),
('promotion_redemption_summary(uuid)','business_analytics','supporting','Promotion redemption analytics.'),
('purchase_single_use_access(uuid)','qr_access','canonical','Single-use access purchase.'),
('redeem_promotion(uuid,uuid)','business_promotions','canonical','Canonical promotion redemption.'),
('redeem_single_use_access(uuid)','qr_access','canonical','Single-use access redemption.'),
('remove_program_location(uuid,uuid)','enterprise_partnerships','compatibility','Older program-location removal signature.'),
('respond_game_challenge(uuid,boolean)','rewards_play','canonical','Canonical game challenge response.'),
('search_public_data_catalog(text,integer)','platform_data','supporting','Public data catalog search.'),
('seed_location_verification_campaign(text,integer)','consumer_evidence','supporting','Verification campaign seeding.'),
('select_location_verification_targets(integer)','consumer_evidence','supporting','Verification target selection.'),
('set_business_location_status(uuid,uuid,boolean)','business_management','compatibility','Older business-scoped location status signature.'),
('set_business_promotion_status(uuid,uuid,boolean)','business_promotions','canonical','Canonical business promotion status mutation.'),
('submit_contest_entry(uuid,jsonb)','business_contests','canonical','Canonical contest entry submission.')
on conflict(function_signature) do update set domain=excluded.domain,classification=excluded.classification,rationale=excluded.rationale,updated_at=now();
