create table if not exists public.location_departures (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,location_id uuid not null references public.locations(id) on delete cascade,left_at timestamptz not null default now(),latitude double precision not null,longitude double precision not null,distance_meters double precision not null,created_at timestamptz not null default now());
create index if not exists location_departures_user_location_time_idx on public.location_departures(user_id,location_id,left_at desc);
alter table public.location_departures enable row level security;
drop policy if exists location_departures_select_own on public.location_departures;
create policy location_departures_select_own on public.location_departures for select to authenticated using(user_id=auth.uid());
revoke insert,update,delete on public.location_departures from anon,authenticated;

drop function if exists public.record_location_departure(uuid,double precision,double precision);
create function public.record_location_departure(p_location_id uuid,p_lat double precision,p_lng double precision) returns jsonb language plpgsql security definer set search_path='public','auth','extensions','pg_temp' as $function$ declare uid uuid:=auth.uid(); loc record; d double precision; radius double precision; begin if uid is null then raise exception 'AUTH_REQUIRED'; end if; if p_lat is null or p_lng is null or p_lat not between -90 and 90 or p_lng not between -180 and 180 then raise exception 'LOCATION_REQUIRED'; end if; select id,latitude,longitude,greatest(25,least(coalesce(geofence_radius_m,150),5000))::double precision radius_m into loc from public.locations where id=p_location_id and is_active=true; if not found or loc.latitude is null or loc.longitude is null then raise exception 'LOCATION_COORDINATES_UNAVAILABLE'; end if; radius:=loc.radius_m; d:=6371000.0*2*asin(sqrt(power(sin(radians(p_lat-loc.latitude)/2),2)+cos(radians(loc.latitude))*cos(radians(p_lat))*power(sin(radians(p_lng-loc.longitude)/2),2))); if d <= radius then raise exception 'STILL_WITHIN_GEOFENCE: distance=% radius=%',round(d),round(radius); end if; insert into public.location_departures(user_id,location_id,left_at,latitude,longitude,distance_meters) values(uid,p_location_id,now(),p_lat,p_lng,d); return jsonb_build_object('ok',true,'location_id',p_location_id,'left_at',now(),'distance_meters',d); end; $function$;
grant execute on function public.record_location_departure(uuid,double precision,double precision) to authenticated;

create or replace function public.is_qualifying_return_visit(p_user_id uuid,p_location_id uuid,p_check_in_at timestamptz default now(),p_check_in_id uuid default null) returns boolean language plpgsql security definer set search_path='public','auth','extensions','pg_temp' as $function$ declare v_last_check timestamptz; v_last_departure timestamptz; v_today integer; v_cap integer:=5; v_same_visit_reward boolean; begin if p_user_id is null or p_location_id is null then return false; end if; if p_check_in_id is not null then select exists(select 1 from public.point_transactions pt where pt.user_id=p_user_id and pt.reason='check_in' and pt.reference_id=p_check_in_id) into v_same_visit_reward; if v_same_visit_reward then return false; end if; end if; select max(checked_in_at) into v_last_check from public.check_ins where user_id=p_user_id and location_id=p_location_id and checked_in_at < p_check_in_at and (p_check_in_id is null or id<>p_check_in_id); if v_last_check is not null then select max(left_at) into v_last_departure from public.location_departures where user_id=p_user_id and location_id=p_location_id and left_at>v_last_check and left_at<=p_check_in_at; if v_last_departure is null then return false; end if; end if; select count(*)::integer into v_today from public.point_transactions where user_id=p_user_id and reason in ('check_in','review') and created_at >= date_trunc('day',p_check_in_at) and created_at < date_trunc('day',p_check_in_at)+interval '1 day'; return v_today < v_cap; end; $function$;

comment on table public.location_departures is 'GPS-backed departure evidence used to distinguish genuine return visits from repeated activity while remaining at a location.';
comment on function public.is_qualifying_return_visit(uuid,uuid,timestamptz,uuid) is 'Progression/reward eligibility requires a genuine return: after a prior check-in, an authenticated GPS departure outside the location geofence must precede the next check-in. Rewards remain capped at five qualifying check-in/review events per local day; check-ins/reviews themselves are not blocked by the reward cap.';
