revoke execute on function public.business_can_manage(uuid) from anon, public;
revoke execute on function public.business_list_campaigns(uuid) from anon, public;
revoke execute on function public.business_create_campaign(uuid,text,text,text,text) from anon, public;
revoke execute on function public.business_update_campaign(uuid,uuid,text,text,text,text) from anon, public;
revoke execute on function public.business_delete_campaign(uuid,uuid) from anon, public;
revoke execute on function public.business_list_events(uuid) from anon, public;
revoke execute on function public.business_create_event(uuid,uuid,text,text,date,time) from anon, public;
revoke execute on function public.business_update_event(uuid,uuid,uuid,text,text,date,time) from anon, public;
revoke execute on function public.business_delete_event(uuid,uuid) from anon, public;
revoke execute on function public.business_list_media(uuid) from anon, public;
revoke execute on function public.business_create_media(uuid,uuid,text,text,text,text,bigint,integer,integer,integer) from anon, public;
revoke execute on function public.business_update_media(uuid,uuid,text,text,text,integer) from anon, public;
revoke execute on function public.business_delete_media(uuid,uuid) from anon, public;
revoke execute on function public.business_list_partnerships(uuid) from anon, public;
revoke execute on function public.business_create_partnership(uuid,text,boolean,boolean,numeric,text) from anon, public;
revoke execute on function public.business_update_partnership(uuid,uuid,text,boolean,boolean,numeric,text) from anon, public;
revoke execute on function public.business_delete_partnership(uuid,uuid) from anon, public;
revoke execute on function public.get_location_occupancy(uuid,integer) from anon, public;
grant execute on function public.business_can_manage(uuid) to authenticated;
grant execute on function public.business_list_campaigns(uuid) to authenticated;
grant execute on function public.business_create_campaign(uuid,text,text,text,text) to authenticated;
grant execute on function public.business_update_campaign(uuid,uuid,text,text,text,text) to authenticated;
grant execute on function public.business_delete_campaign(uuid,uuid) to authenticated;
grant execute on function public.business_list_events(uuid) to authenticated;
grant execute on function public.business_create_event(uuid,uuid,text,text,date,time) to authenticated;
grant execute on function public.business_update_event(uuid,uuid,uuid,text,text,date,time) to authenticated;
grant execute on function public.business_delete_event(uuid,uuid) to authenticated;
grant execute on function public.business_list_media(uuid) to authenticated;
grant execute on function public.business_create_media(uuid,uuid,text,text,text,text,bigint,integer,integer,integer) to authenticated;
grant execute on function public.business_update_media(uuid,uuid,text,text,text,integer) to authenticated;
grant execute on function public.business_delete_media(uuid,uuid) to authenticated;
grant execute on function public.business_list_partnerships(uuid) to authenticated;
grant execute on function public.business_create_partnership(uuid,text,boolean,boolean,numeric,text) to authenticated;
grant execute on function public.business_update_partnership(uuid,uuid,text,boolean,boolean,numeric,text) to authenticated;
grant execute on function public.business_delete_partnership(uuid,uuid) to authenticated;
grant execute on function public.get_location_occupancy(uuid,integer) to authenticated;
