revoke execute on function public.get_business_metric_detail(uuid,uuid,text) from public,anon,authenticated;
revoke execute on function public.get_business_leaderboard(text,integer) from public,anon,authenticated;
revoke execute on function public.get_business_dashboard() from public,anon,authenticated;
revoke execute on function public.business_event_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_location_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_media_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_partner_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_promotion_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_visitors_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_occupancy_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.get_partner_network_benchmark(uuid,date,date) from public,anon,authenticated;
revoke execute on function public.get_partner_campaign_roi(uuid,date,date) from public,anon,authenticated;
revoke execute on function public.get_partner_allocation_roi(uuid,date,date) from public,anon,authenticated;
revoke execute on function public.business_campaign_detail(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_engagement_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_promotion_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_location_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_event_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_growth_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_summary_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_rewards_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_roi_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_partner_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_amenity_feedback_analytics(uuid,uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
revoke execute on function public.business_benchmark_analytics(uuid,timestamp with time zone,timestamp with time zone) from public,anon,authenticated;
