revoke execute on function public._collect_raw_schema_capability_audit() from anon, authenticated;
revoke execute on function public.admin_get_business_access(uuid) from anon;
revoke execute on function public.admin_list_business_members(uuid) from anon;
revoke execute on function public.admin_remove_business_member(uuid,uuid) from anon;
revoke execute on function public.audit_contributor_reputation_consistency(boolean) from anon;
revoke execute on function public.business_intelligence_authorized(uuid) from anon;
revoke execute on function public.compute_bathroom_intelligence(uuid) from anon;
revoke execute on function public.create_gps_geofence_notification(uuid,integer,text,text,text,jsonb) from anon;
revoke execute on function public.enterprise_delete_campaign(uuid) from anon;
revoke execute on function public.enterprise_delete_network(uuid) from anon;
revoke execute on function public.enterprise_list_network_campaigns(uuid) from anon;
revoke execute on function public.enterprise_list_network_members(uuid) from anon;
revoke execute on function public.enterprise_list_owned_networks(uuid) from anon;
revoke execute on function public.enterprise_list_partner_businesses(uuid) from anon;
revoke execute on function public.enterprise_update_campaign(uuid,text,text,text,text) from anon;
revoke execute on function public.enterprise_update_network(uuid,text,boolean) from anon;
revoke execute on function public.fleet_create_driver(uuid,text,text,text,text,uuid,jsonb) from anon;
revoke execute on function public.fleet_create_maintenance(uuid,uuid,text,text,timestamptz,numeric,numeric,text,text,jsonb) from anon;
revoke execute on function public.fleet_create_route(uuid,text,text,uuid,uuid,timestamptz,numeric,integer,integer,jsonb) from anon;
revoke execute on function public.fleet_create_vehicle(uuid,text,text,text,text,text,double precision,double precision,numeric,jsonb) from anon;
revoke execute on function public.fleet_delete_driver(uuid,uuid) from anon;
revoke execute on function public.fleet_delete_maintenance(uuid,uuid) from anon;
revoke execute on function public.fleet_delete_route(uuid,uuid) from anon;
revoke execute on function public.fleet_delete_vehicle(uuid,uuid) from anon;
revoke execute on function public.fleet_update_driver(uuid,uuid,text,text,text,text,uuid,jsonb) from anon;
revoke execute on function public.fleet_update_maintenance(uuid,uuid,uuid,text,text,timestamptz,timestamptz,numeric,numeric,text,text,jsonb) from anon;
revoke execute on function public.fleet_update_route(uuid,uuid,text,text,uuid,uuid,timestamptz,numeric,integer,integer,jsonb) from anon;
revoke execute on function public.fleet_update_vehicle(uuid,uuid,text,text,text,text,text,double precision,double precision,numeric,jsonb) from anon;
revoke execute on function public.refresh_bathroom_intelligence(integer) from anon;
revoke execute on function public.refresh_location_bathroom_intelligence_trigger() from anon;
revoke execute on function public.refresh_reputation_for_evidence_user() from anon;
revoke execute on function public.recompute_contributor_reputation(uuid) from anon;
revoke execute on function public.run_capability_audit(text) from anon;
revoke execute on function public.capability_classification_summary() from anon;
revoke execute on function public.capability_retirement_audit() from anon;
revoke execute on function public.search_public_data_catalog(text,integer) from anon;
