create table if not exists public.mobile_store_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null check (platform in ('apple','google')),
  product_id text not null,
  transaction_id text not null,
  purchase_token_sha256 text,
  store_environment text,
  verified_at timestamptz not null default now(),
  verification_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(platform,transaction_id)
);

alter table public.mobile_store_purchases enable row level security;
revoke all on table public.mobile_store_purchases from public,anon,authenticated;
grant select on table public.mobile_store_purchases to authenticated;

drop policy if exists mobile_store_purchases_select_own on public.mobile_store_purchases;
create policy mobile_store_purchases_select_own
on public.mobile_store_purchases
for select
to authenticated
using ((select auth.uid())=user_id);

create index if not exists mobile_store_purchases_user_verified_idx
  on public.mobile_store_purchases(user_id,verified_at desc);

create or replace function public.grant_mobile_store_premium(
  p_user_id uuid,
  p_platform text,
  p_product_id text,
  p_transaction_id text,
  p_purchase_token_sha256 text default null,
  p_store_environment text default null,
  p_verification_summary jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  v_platform text:=lower(trim(coalesce(p_platform,'')));
  v_product text:=trim(coalesce(p_product_id,''));
  v_transaction text:=trim(coalesce(p_transaction_id,''));
  v_existing_user uuid;
begin
  if session_user<>'postgres' and coalesce(auth.jwt()->>'role','')<>'service_role' then
    raise exception 'service_role required' using errcode='42501';
  end if;
  if p_user_id is null or not exists(select 1 from public.profiles p where p.id=p_user_id) then
    raise exception 'Kleenest user not found';
  end if;
  if v_platform not in ('apple','google') then raise exception 'Unsupported store platform'; end if;
  if v_product<>'kleenest_remove_ads_lifetime' then raise exception 'Unsupported store product'; end if;
  if v_transaction='' then raise exception 'Store transaction id is required'; end if;

  select m.user_id into v_existing_user
  from public.mobile_store_purchases m
  where m.platform=v_platform and m.transaction_id=v_transaction;

  if v_existing_user is not null and v_existing_user<>p_user_id then
    raise exception 'Store transaction is already linked to another Kleenest account' using errcode='23505';
  end if;

  insert into public.mobile_store_purchases(
    user_id,platform,product_id,transaction_id,purchase_token_sha256,store_environment,verified_at,verification_summary
  ) values (
    p_user_id,v_platform,v_product,v_transaction,nullif(trim(coalesce(p_purchase_token_sha256,'')),''),
    nullif(trim(coalesce(p_store_environment,'')),''),now(),coalesce(p_verification_summary,'{}'::jsonb)
  )
  on conflict(platform,transaction_id) do update set
    purchase_token_sha256=excluded.purchase_token_sha256,
    store_environment=excluded.store_environment,
    verified_at=now(),
    verification_summary=excluded.verification_summary;

  update public.profiles
     set subscription_tier=case when subscription_tier::text='family' then subscription_tier else 'premium'::public.subscription_tier end,
         updated_at=now()
   where id=p_user_id;

  insert into public.user_feature_entitlements(user_id,feature_code,tier_code,enabled,source,updated_at)
  select p_user_id,f.value,'premium',true,'mobile_store_purchase',now()
  from public.pricing_catalog pc
  cross join lateral jsonb_array_elements_text(coalesce(pc.features,'[]'::jsonb)) f(value)
  where pc.code='premium_user' and pc.category='consumer' and pc.active
  on conflict(user_id,feature_code) do update set
    tier_code=excluded.tier_code,
    enabled=true,
    source=excluded.source,
    updated_at=now();
end;
$$;

revoke all on function public.grant_mobile_store_premium(uuid,text,text,text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.grant_mobile_store_premium(uuid,text,text,text,text,text,jsonb) to service_role;

comment on table public.mobile_store_purchases is 'Server-verified Apple App Store and Google Play lifetime Consumer purchases. Raw purchase tokens are never persisted.';
comment on function public.grant_mobile_store_premium(uuid,text,text,text,text,text,jsonb) is 'Service-role-only idempotent grant for the lifetime Remove Ads mobile store product.';
