insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('has_fleet_access(uuid)','fleet_management','canonical','Canonical fleet access boundary.'),
('fleet_actor_is_manager(uuid)','fleet_management','supporting','Fleet manager authorization check.'),
('enable_enterprise_fleet_service(uuid)','fleet_management','canonical','Enterprise fleet activation.'),
('fleet_create_vehicle(uuid,text,text,text,text,text,double precision,double precision,numeric,jsonb)','fleet_crud','canonical','Canonical fleet vehicle creation.'),
('fleet_update_vehicle(uuid,uuid,text,text,text,text,text,double precision,double precision,numeric,jsonb)','fleet_crud','canonical','Canonical fleet vehicle update.'),
('fleet_delete_vehicle(uuid,uuid)','fleet_crud','canonical','Canonical fleet vehicle deletion.'),
('fleet_set_vehicle_status(uuid,uuid,text)','fleet_crud','supporting','Vehicle lifecycle status.'),
('fleet_create_driver(uuid,text,text,text,text,uuid,jsonb)','fleet_crud','canonical','Canonical driver creation.'),
('fleet_update_driver(uuid,uuid,text,text,text,text,uuid,jsonb)','fleet_crud','canonical','Canonical driver update.'),
('fleet_delete_driver(uuid,uuid)','fleet_crud','canonical','Canonical driver deletion.'),
('fleet_set_driver_status(uuid,uuid,text)','fleet_crud','supporting','Driver lifecycle status.'),
('fleet_create_route(uuid,text,text,uuid,uuid,timestamp with time zone,numeric,integer,integer,jsonb)','fleet_routes','canonical','Canonical fleet route creation.'),
('fleet_update_route(uuid,uuid,text,text,uuid,uuid,timestamp with time zone,numeric,integer,integer,jsonb)','fleet_routes','canonical','Canonical fleet route update.'),
('fleet_delete_route(uuid,uuid)','fleet_routes','canonical','Canonical fleet route deletion.'),
('fleet_set_route_status(uuid,uuid,text)','fleet_routes','supporting','Route lifecycle status.'),
('fleet_create_maintenance(uuid,uuid,text,text,timestamp with time zone,numeric,numeric,text,text,jsonb)','fleet_maintenance','canonical','Canonical maintenance creation.'),
('fleet_update_maintenance(uuid,uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,numeric,numeric,text,text,jsonb)','fleet_maintenance','canonical','Canonical maintenance update.'),
('fleet_delete_maintenance(uuid,uuid)','fleet_maintenance','canonical','Canonical maintenance deletion.'),
('fleet_complete_maintenance(uuid,uuid,text)','fleet_maintenance','supporting','Maintenance completion lifecycle.'),
('fleet_dashboard_summary_v2(uuid)','fleet_analytics','canonical','Current secure fleet dashboard summary.'),
('fleet_dashboard_summary(uuid)','fleet_analytics','compatibility','Older dashboard summary retained for compatibility.'),
('fleet_service_opportunities_for_business(uuid)','fleet_analytics','canonical','Fleet service opportunity discovery.'),
('get_fleet_metric_capabilities(uuid)','fleet_metrics','canonical','Fleet metric capability inventory.'),
('get_fleet_metric_configuration(uuid)','fleet_metrics','canonical','Fleet metric configuration.'),
('get_fleet_metric_values(uuid,date)','fleet_metrics','canonical','Fleet metric values.'),
('create_fleet_metric_definition(uuid,text,text,text,text,text,text,text,text,text,text,numeric,numeric,numeric,jsonb,text)','fleet_metrics','canonical','Fleet metric definition creation.'),
('update_fleet_metric_definition(uuid,text,text,numeric,numeric,numeric,text,jsonb,text,boolean)','fleet_metrics','canonical','Fleet metric definition update.'),
('assign_fleet_metric(uuid,text,uuid)','fleet_metrics','canonical','Fleet metric assignment.'),
('fleet_metric_controller_authorized(uuid)','fleet_metrics','supporting','Fleet metric controller authorization.'),
('fleet_metric_source_allowed(text,text)','fleet_metrics','supporting','Fleet metric source authorization.'),
('get_fleet_leaderboard(uuid,text,text,integer)','fleet_leaderboards','canonical','Fleet-scoped leaderboard.'),
('get_fleet_network_leaderboard(text,integer)','fleet_leaderboards','canonical','Network fleet leaderboard.'),
('record_fleet_operational_event(uuid,text,jsonb)','fleet_operations','canonical','Fleet operational event recording.'),
('publish_fleet_route_notification(uuid,text,text,text,jsonb)','fleet_operations','supporting','Fleet route notification.'),
('fleet_resolve_alert(uuid,uuid,text)','fleet_operations','canonical','Fleet alert resolution.'),
('record_network_leaderboard_participation(text,uuid,text,numeric,text,uuid,date,date,jsonb)','fleet_leaderboards','supporting','Leaderboard participation event.'),
('refresh_business_metric_leaderboards()','fleet_leaderboards','supporting','Leaderboard materialization refresh.'),
('get_business_leaderboard(text,integer)','business_analytics','supporting','Business leaderboard aggregate.'),
('get_cross_tier_leaderboard(text,integer)','network_intelligence','canonical','Cross-tier network leaderboard.'),
('get_platform_leaderboard(text,integer)','network_intelligence','canonical','Platform leaderboard.'),
('get_user_leaderboard(integer)','network_intelligence','canonical','Consumer user leaderboard.'),
('refresh_user_leaderboard()','network_intelligence','supporting','User leaderboard materialization refresh.'),
('quest_leaderboard(uuid,integer)','rewards_quests','canonical','Quest-specific progression leaderboard.')
on conflict(function_signature) do update set domain=excluded.domain, classification=excluded.classification, rationale=excluded.rationale, updated_at=now();
