insert into public.capability_function_classifications(function_signature,domain,classification,rationale) values
('business_management_context(uuid)','business_management','canonical','Canonical business authorization/context boundary.'),
('business_can_manage(uuid)','business_management','supporting','Business management eligibility check.'),
('business_admin_allowed(uuid)','business_management','supporting','Business admin authorization check.'),
('business_admin_guard(uuid)','business_management','trigger_helper','Authorization guard/helper.'),
('business_create_location(uuid,text,text,text,text,text,numeric,numeric,text,text)','business_crud','canonical','Canonical business location creation.'),
('business_update_location(uuid,uuid,text,text,text,text,boolean)','business_crud','canonical','Canonical business location update.'),
('business_manage_location(uuid,uuid,text,jsonb)','business_crud','supporting','Generic location management gateway; retain as supporting until all clients converge.'),
('business_delete_event(uuid,uuid)','business_crud','canonical','Canonical event deletion.'),
('business_update_event(uuid,uuid,uuid,text,text,date,time without time zone)','business_crud','canonical','Canonical event update.'),
('business_create_event(uuid,uuid,text,text,date,time without time zone)','business_crud','canonical','Canonical event creation variant.'),
('business_manage_event(uuid,uuid,text,jsonb)','business_crud','supporting','Generic event management gateway.'),
('business_create_media(uuid,uuid,text,text,text,text,bigint,integer,integer,integer)','business_crud','canonical','Canonical business media creation.'),
('business_update_media(uuid,uuid,text,text,text,integer)','business_crud','canonical','Canonical business media update.'),
('business_delete_media(uuid,uuid)','business_crud','canonical','Canonical business media deletion.'),
('business_create_promotion(uuid,uuid,text,text,text,timestamp with time zone,timestamp with time zone)','business_crud','canonical','Canonical promotion creation.'),
('business_update_promotion(uuid,uuid,text,text,text,boolean)','business_crud','canonical','Canonical promotion update.'),
('business_delete_promotion(uuid,uuid)','business_crud','canonical','Canonical promotion deletion.'),
('business_manage_promotion(uuid,uuid,text,jsonb)','business_crud','supporting','Generic promotion management gateway.'),
('business_create_campaign(uuid,text,text,text,text)','business_campaigns','canonical','Business campaign creation.'),
('business_update_campaign(uuid,uuid,text,text,text,text)','business_campaigns','canonical','Business campaign update.'),
('business_delete_campaign(uuid,uuid)','business_campaigns','canonical','Business campaign deletion.'),
('business_manage_campaign(uuid,uuid,text,text,text,text,text)','business_campaigns','supporting','Generic campaign management gateway.'),
('business_create_partner_program(uuid,text)','business_partnerships','canonical','Business partner program creation.'),
('business_update_partner_program(uuid,uuid,text,boolean)','business_partnerships','canonical','Business partner program update.'),
('business_delete_partner_program(uuid,uuid)','business_partnerships','canonical','Business partner program deletion.'),
('business_create_partnership(uuid,text,boolean,boolean,numeric,text)','business_partnerships','canonical','Business partnership creation.'),
('business_update_partnership(uuid,uuid,text,boolean,boolean,numeric,text)','business_partnerships','canonical','Business partnership update.'),
('business_delete_partnership(uuid,uuid)','business_partnerships','canonical','Business partnership deletion.'),
('business_invite_member(uuid,uuid,business_member_role)','business_membership','canonical','Business member invitation.'),
('business_change_member_role(uuid,uuid,business_member_role)','business_membership','canonical','Business member role change.'),
('business_remove_member(uuid,uuid)','business_membership','canonical','Business member removal.'),
('business_update_member_role(uuid,uuid,business_member_role)','business_membership','compatibility','Duplicate role-management entry point pending consolidation.'),
('business_transfer_ownership(uuid,uuid)','business_membership','canonical','Business ownership transfer.'),
('business_set_location_active(uuid,uuid,boolean)','business_crud','supporting','Location lifecycle toggle.'),
('business_set_location_amenity(uuid,uuid,uuid,text)','business_crud','supporting','Location amenity management.'),
('business_create_qr(uuid,uuid,text)','business_marketing','canonical','Business QR creation.'),
('business_update_custom_qr(uuid,uuid,text,text,text,jsonb,jsonb,boolean,boolean,integer)','business_marketing','canonical','Business QR update.'),
('business_delete_qr(uuid,uuid)','business_marketing','canonical','Business QR deletion.'),
('business_set_qr_active(uuid,uuid,boolean)','business_marketing','supporting','QR lifecycle toggle.'),
('business_reply_review(uuid,uuid,text)','business_reviews','canonical','Business review response.'),
('business_dashboard_secure_summary(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','canonical','Secure business analytics summary.'),
('business_summary_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Business analytics aggregate.'),
('business_location_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Location analytics aggregate.'),
('business_campaign_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Campaign analytics.'),
('business_promotion_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Promotion analytics.'),
('business_engagement_analytics(uuid,timestamp with time zone,timestamp with time zone)','business_analytics','supporting','Engagement analytics.')
on conflict(function_signature) do update set domain=excluded.domain, classification=excluded.classification, rationale=excluded.rationale, updated_at=now();
