import { listMobileFavoriteLocations } from '@kleenest/mobile-core';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { TrustStrip,palette } from '../components/ConsumerUI';
import { activatePreferredLocation,claimSingleUseAccess,deactivatePreferredLocation,listMyPreferredActivations,listSingleUseAccessOffers,listSingleUseAccessPurchases,preferredEligibility,recordPreferredLocationUse,redeemSingleUseAccess } from '../services/access';

type Row=Record<string,any>;
export default function AccessScreen(){const[saved,setSaved]=useState<Row[]>([]),[eligibility,setEligibility]=useState<Record<string,Row>>({}),[activations,setActivations]=useState<Row[]>([]),[offers,setOffers]=useState<Row[]>([]),[purchases,setPurchases]=useState<Row[]>([]),[busy,setBusy]=useState(''),[message,setMessage]=useState('Loading access…');
async function load(){try{const[s,o,p,a]=await Promise.all([listMobileFavoriteLocations(),listSingleUseAccessOffers(),listSingleUseAccessPurchases(),listMyPreferredActivations()]);setSaved(s);setOffers(o);setPurchases(p);setActivations(a);const checks=await Promise.all(s.slice(0,20).map(async row=>{const id=String(row.id||row.location_id||'');return[id,await preferredEligibility(id).catch(()=>({eligible:false,reason:'unavailable'}))] as const}));setEligibility(Object.fromEntries(checks));setMessage('')}catch(e:any){setMessage(e?.message||'Access could not be loaded.')}}
useEffect(()=>{void load()},[]);const activeByLocation=useMemo(()=>new Map(activations.map(a=>[String(a.location_id),a])),[activations]);async function run(key:string,fn:()=>Promise<any>){setBusy(key);setMessage('');try{await fn();await load()}catch(e:any){setMessage(e?.message||'Action could not be completed.')}finally{setBusy('')}}
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.eyebrow}>ACCESS + PREFERRED</Text><Text style={s.heroTitle}>Use the restroom access your Kleenest network has earned.</Text><Text style={s.heroBody}>Preferred locations and single-use access are resolved by the canonical partner and purchase authorities. The app does not invent eligibility.</Text><TrustStrip items={['Scoped partner eligibility','Single-use redemption','Usage attribution']}/></View>{message?<Text style={s.message}>{message}</Text>:null}
<View style={s.section}><Text style={s.sectionTitle}>Preferred saved locations</Text><Text style={s.body}>Only locations where the backend says you are eligible can be activated.</Text>{saved.length?saved.slice(0,20).map(row=>{const id=String(row.id||row.location_id||''),check=eligibility[id]||{},active=activeByLocation.get(id);return <View key={id} style={s.card}><Text style={s.cardTitle}>{row.name||'Saved restroom'}</Text><Text style={s.meta}>{[row.address,row.city,row.state].filter(Boolean).join(', ')}</Text><Text style={check.eligible?s.good:s.meta}>{check.eligible?`Eligible${check.program_name?` · ${check.program_name}`:''}`:`Not eligible · ${String(check.reason||'no scoped preferred program').replaceAll('_',' ')}`}</Text>{check.eligible?<View style={s.actions}>{active?<><Button label="Record use" disabled={!!busy} onPress={()=>run(`use:${id}`,()=>recordPreferredLocationUse(id))}/><Button label="Deactivate" secondary disabled={!!busy} onPress={()=>run(`off:${id}`,()=>deactivatePreferredLocation(id))}/></>:<Button label="Activate preferred" disabled={!!busy} onPress={()=>run(`on:${id}`,()=>activatePreferredLocation(id))}/>}</View>:null}</View>}):<Text style={s.body}>Save locations from Explore to check preferred-access eligibility.</Text>}</View>
<View style={s.section}><Text style={s.sectionTitle}>Single-use access offers</Text><Text style={s.body}>Free offers can be claimed here. Paid offers require the verified native/store checkout boundary before fulfillment.</Text>{offers.length?offers.map(o=>{const purchased=purchases.find(p=>String(p.offer_id)===String(o.id)&&p.status==='purchased');return <View key={String(o.id)} style={s.card}><Text style={s.cardTitle}>{o.name||'Access offer'}</Text><Text style={s.body}>{o.description||'Single-use access'}</Text><Text style={s.meta}>{Number(o.price_cents||0)===0?'Free':`$${(Number(o.price_cents)/100).toFixed(2)}`}</Text>{purchased?<Button label="Redeem now" disabled={!!busy} onPress={()=>run(`redeem:${purchased.id}`,()=>redeemSingleUseAccess(String(purchased.id)))}/>:Number(o.price_cents||0)===0?<Button label="Claim access" disabled={!!busy} onPress={()=>run(`claim:${o.id}`,()=>claimSingleUseAccess(String(o.id)))}/>:<Text style={s.meta}>Native checkout required before this paid access can be issued.</Text>}</View>}):<Text style={s.body}>No active single-use offers right now.</Text>}</View>
</ScrollView></SafeAreaView>}
function Button({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.buttonSecondary,disabled&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&s.buttonSecondaryText]}>{label}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:44,gap:14},hero:{backgroundColor:palette.green,padding:20,borderRadius:26,gap:8},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#bad0c2'},heroTitle:{fontSize:29,lineHeight:33,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},section:{gap:9},sectionTitle:{fontSize:23,fontWeight:'900',color:palette.ink},body:{fontSize:13,lineHeight:20,color:palette.muted},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6df',borderRadius:18,padding:15,gap:6},cardTitle:{fontSize:17,fontWeight:'900',color:palette.ink},meta:{fontSize:11,lineHeight:17,color:palette.muted},good:{fontSize:11,fontWeight:'900',color:palette.green},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:4},button:{alignSelf:'flex-start',backgroundColor:palette.green,paddingHorizontal:13,paddingVertical:10,borderRadius:12},buttonText:{color:'#fff',fontWeight:'900'},buttonSecondary:{backgroundColor:'#edf3ef'},buttonSecondaryText:{color:palette.green},message:{fontSize:12,fontWeight:'700',color:'#6b756f'}});
