import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { requestAccountDeletion } from '../services/account';

export default function AccountDeletionScreen(){
  const [reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function submit(){if(busy||!confirmed)return;setBusy(true);setMessage('');try{const result=await requestAccountDeletion(reason);setMessage(`Deletion request submitted ${result.requested_at?`on ${new Date(result.requested_at).toLocaleString()}`:''}. Your request is now ${result.status||'requested'}.`);setReason('');setConfirmed(false)}catch(error:any){setMessage(error?.message||'Account deletion request could not be submitted.')}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>ACCOUNT CONTROL</Text><Text style={s.title}>Request account deletion</Text><Text style={s.body}>This sends a protected deletion request for your signed-in Kleenest account. It does not silently delete data from the client. The backend records the request for processing and audit.</Text><View style={s.card}><Text style={s.cardTitle}>Before you submit</Text><Text style={s.body}>Your profile, contribution history, saved places, progression, and related account data may be affected when the request is processed. You can include an optional reason below.</Text><TextInput style={[s.input,s.textarea]} value={reason} onChangeText={setReason} maxLength={1000} multiline placeholder="Optional reason"/><Text style={s.counter}>{reason.length}/1000</Text><Pressable style={s.confirmRow} onPress={()=>setConfirmed(value=>!value)}><View style={[s.checkbox,confirmed&&s.checkboxOn]}><Text style={s.check}>{confirmed?'✓':''}</Text></View><Text style={s.confirmText}>I understand that I am requesting deletion of my Kleenest account.</Text></Pressable><Pressable style={[s.danger,(!confirmed||busy)&&s.disabled]} disabled={!confirmed||busy} onPress={submit}><Text style={s.dangerText}>{busy?'Submitting request…':'Request account deletion'}</Text></Pressable></View>{message?<View style={s.message}><Text style={s.messageText}>{message}</Text></View>:null}<Pressable style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back to profile</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},content:{padding:22,paddingBottom:42,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:32,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#e2dfdc',gap:11},cardTitle:{fontSize:19,fontWeight:'900',color:'#14231b'},input:{backgroundColor:'#fbfdfc',borderWidth:1,borderColor:'#d6d7d3',borderRadius:14,padding:13},textarea:{minHeight:110,textAlignVertical:'top'},counter:{alignSelf:'flex-end',fontSize:12,color:'#718078',fontWeight:'700'},confirmRow:{flexDirection:'row',alignItems:'flex-start',gap:10},checkbox:{width:25,height:25,borderRadius:7,borderWidth:2,borderColor:'#aa9c96',alignItems:'center',justifyContent:'center'},checkboxOn:{backgroundColor:'#6e2a22',borderColor:'#6e2a22'},check:{color:'#fff',fontWeight:'900'},confirmText:{flex:1,color:'#4f4c49',lineHeight:20,fontWeight:'700'},danger:{backgroundColor:'#6e2a22',padding:14,borderRadius:14,alignItems:'center'},dangerText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},message:{backgroundColor:'#eef3ef',padding:13,borderRadius:14},messageText:{color:'#274535',fontWeight:'700',lineHeight:20},secondary:{backgroundColor:'#edf3ef',padding:14,borderRadius:14,alignItems:'center'},secondaryText:{color:'#173d2b',fontWeight:'800'}});
