import { LegalDocument, LegalSection } from '../components/LegalDocument';

export default function CommunityGuidelinesScreen(){return <LegalDocument eyebrow="SAFETY" title="Kleenest Community Guidelines">
  <LegalSection title="Be useful and truthful">Contribute restroom information, reviews, photos, access observations and community posts that reflect your genuine experience. Do not fabricate visits, manipulate trust signals, coordinate false ratings, or intentionally publish misleading availability, cleanliness, accessibility or safety information.</LegalSection>
  <LegalSection title="Respect people">Do not harass, threaten, stalk, bully, shame, or target people with degrading or hateful content. Do not encourage violence or discrimination against protected groups. Do not use Kleenest to pressure, intimidate, or repeatedly contact someone who does not want contact.</LegalSection>
  <LegalSection title="Protect privacy">Do not publish private personal information, precise private-home locations, credentials, private communications, or identifying information about another person without a legitimate right to share it. Never use reviews, photos or messages to dox or surveil someone.</LegalSection>
  <LegalSection title="No sexual exploitation or illegal content">Do not upload sexual exploitation material, non-consensual intimate content, content that sexualizes minors, or material facilitating illegal activity. Content presenting an immediate safety risk may be escalated as appropriate.</LegalSection>
  <LegalSection title="No spam, scams or impersonation">Do not impersonate another person or business, phish for credentials, distribute malware, run scams, send repetitive unsolicited promotions, or manipulate social, game, reward, support, review or messaging systems.</LegalSection>
  <LegalSection title="Photos and reviews">Only upload images you have the right to share. Avoid identifiable bystanders where reasonably possible, especially in sensitive restroom contexts. Reviews should focus on the place and relevant experience rather than attacking individuals.</LegalSection>
  <LegalSection title="Reporting and blocking">Use the in-app Report action for objectionable content or accounts. For one-to-one interactions, you can block a contributor; blocking prevents direct messages between the two accounts. Safety reports are private and are evaluated separately from public reputation signals.</LegalSection>
  <LegalSection title="Moderation">Kleenest may reduce visibility, remove content, preserve evidence needed for abuse prevention, issue warnings, restrict features, suspend accounts, or terminate access based on severity, repetition, context and applicable law. Attempts to evade enforcement may result in additional restrictions.</LegalSection>
  <LegalSection title="Emergencies">Kleenest reporting is not an emergency service. If you or someone else faces immediate danger, contact the appropriate local emergency service.</LegalSection>
</LegalDocument>}
