import * as Linking from 'expo-linking';
import { getKleenestSupabaseClient } from '@kleenest/mobile-core';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { requestAccountDeletion } from '../services/account';
import { palette } from '../components/ConsumerUI';

export default function DeleteAccountWebScreen(){
  const client=getKleenestSupabaseClient();
  const[email,setEmail]=useState(''),[reason,setReason]=useState(''),[session,setSession]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function refresh(){const{data,error}=await client.auth.getSession();if(error){setMessage(error.message);return}setSession(data.session)}
  async function handleUrl(url:string|null){if(!url)return;try{const parsed=Linking.parse(url);const code=typeof parsed.queryParams?.code==='string'?parsed.queryParams.code:'';if(code){const{error}=await client.auth.exchangeCodeForSession(code);if(error)throw error;setMessage('Identity verified. You can now submit the deletion request.');await refresh()}}catch(error:any){setMessage(error?.message||'Verification link could not be completed.')}}
  useEffect(()=>{void refresh();void Linking.getInitialURL().then(handleUrl);const auth=client.auth.onAuthStateChange((_event,next)=>setSession(next));const link=Linking.addEventListener('url',event=>{void handleUrl(event.url)});return()=>{auth.data.subscription.unsubscribe();link.remove()}},[]);
  async function sendLink(){if(busy||!email.trim())return;setBusy(true);setMessage('');try{const redirect=Linking.createURL('/delete-account');const{error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:redirect,shouldCreateUser:false}});if(error)throw error;setMessage('Verification link sent. Open the email on this device/browser, then return here to submit your deletion request.')}catch(error:any){setMessage(error?.message||'Verification link could not be sent.')}finally{setBusy(false)}}
  async function submit(){if(busy||!session||!confirmed)return;setBusy(true);setMessage('');try{const result=await requestAccountDeletion(reason);setMessage(`Deletion request submitted${result.requested_at?` on ${new Date(result.requested_at).toLocaleString()}`:''}. Status: ${result.status||'requested'}. You may now sign out and close this page.`);setConfirmed(false);setReason('')}catch(error:any){setMessage(error?.message||'Deletion request could not be submitted.')}finally{setBusy(false)}}
  async function signOut(){await client.auth.signOut();setSession(null);setMessage('Signed out.')}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.eyebrow}>KLEENEST ACCOUNT CONTROL</Text><Text accessibilityRole="header" style={s.title}>Delete your Kleenest account</Text>
    <Text style={s.body}>This public page lets you request deletion even if Kleenest is no longer installed. For security, we verify that you control the account before accepting the request.</Text>
    {!session?<View style={s.card}><Text style={s.cardTitle}>1. Verify your account</Text><Text style={s.body}>Enter the email address used for Kleenest. We will send a sign-in link only for an existing account; this deletion flow will not create a new account.</Text><TextInput accessibilityLabel="Kleenest account email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" placeholder="you@example.com" style={s.input}/><Pressable disabled={busy||!email.trim()} onPress={sendLink} style={[s.primary,(busy||!email.trim())&&s.disabled]}><Text style={s.primaryText}>{busy?'Sending…':'Send verification link'}</Text></Pressable></View>:<View style={s.card}><Text style={s.cardTitle}>2. Request deletion</Text><Text style={s.body}>Verified as {session.user?.email||'your Kleenest account'}. Processing the request removes or de-identifies associated account data except limited records that must be retained for legitimate legal, security, fraud-prevention, dispute, or audit purposes.</Text><TextInput accessibilityLabel="Optional deletion reason" value={reason} onChangeText={setReason} maxLength={1000} multiline placeholder="Optional reason" style={[s.input,s.textarea]}/><Text style={s.counter}>{reason.length}/1000</Text><Pressable onPress={()=>setConfirmed(v=>!v)} accessibilityRole="checkbox" accessibilityState={{checked:confirmed}} style={s.confirm}><View style={[s.box,confirmed&&s.boxOn]}><Text style={s.check}>{confirmed?'✓':''}</Text></View><Text style={s.confirmText}>I understand that I am requesting deletion of my Kleenest account and associated data.</Text></Pressable><Pressable disabled={busy||!confirmed} onPress={submit} style={[s.danger,(busy||!confirmed)&&s.disabled]}><Text style={s.dangerText}>{busy?'Submitting…':'Submit deletion request'}</Text></Pressable><Pressable onPress={signOut} style={s.secondary}><Text style={s.secondaryText}>Sign out without deleting</Text></Pressable></View>}
    {message?<View accessibilityRole="alert" style={s.notice}><Text style={s.noticeText}>{message}</Text></View>:null}
    <View style={s.card}><Text style={s.cardTitle}>What happens next</Text><Text style={s.body}>The request is recorded in Kleenest's protected deletion workflow for processing and audit. You do not need to reinstall the app. If you still have access to Kleenest, the same request can also be initiated from Profile → Account deletion.</Text></View>
  </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:50,gap:12,maxWidth:720,width:'100%',alignSelf:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:palette.muted},title:{fontSize:34,lineHeight:39,fontWeight:'900',color:palette.ink},body:{fontSize:14,lineHeight:21,color:palette.muted},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dce6df',gap:11},cardTitle:{fontSize:19,fontWeight:'900',color:palette.ink},input:{minHeight:48,borderWidth:1,borderColor:'#ccd9d1',borderRadius:13,padding:12,backgroundColor:'#fbfdfc'},textarea:{minHeight:110,textAlignVertical:'top'},counter:{alignSelf:'flex-end',fontSize:11,fontWeight:'700',color:palette.muted},confirm:{flexDirection:'row',alignItems:'flex-start',gap:10},box:{width:25,height:25,borderRadius:7,borderWidth:2,borderColor:'#9ba9a0',alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:palette.green,borderColor:palette.green},check:{color:'#fff',fontWeight:'900'},confirmText:{flex:1,fontSize:13,lineHeight:19,fontWeight:'700',color:palette.muted},primary:{minHeight:48,backgroundColor:palette.green,borderRadius:14,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'},danger:{minHeight:48,backgroundColor:'#742d25',borderRadius:14,alignItems:'center',justifyContent:'center'},dangerText:{color:'#fff',fontWeight:'900'},secondary:{minHeight:48,backgroundColor:'#edf3ef',borderRadius:14,alignItems:'center',justifyContent:'center'},secondaryText:{color:palette.green,fontWeight:'900'},disabled:{opacity:.5},notice:{backgroundColor:'#eef4f0',padding:13,borderRadius:14},noticeText:{color:'#365344',fontWeight:'700',lineHeight:20}});
