import * as Linking from 'expo-linking';
import * as Location from 'expo-location';
import { router } from 'expo-router';
import { listNearbyRestrooms } from '@kleenest/mobile-core';
import { useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';

const idOf=(item:any)=>item.location_id||item.place_id;
const navigateUrl=(item:any)=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${item.latitude},${item.longitude}`)}&travelmode=driving`;
export default function ExploreScreen(){
  const [rows,setRows]=useState<any[]>([]),[search,setSearch]=useState(''),[message,setMessage]=useState('');
  async function load(){setMessage('Finding nearby restrooms…');try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Location permission is required.');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const data=await listNearbyRestrooms(current.coords.latitude,current.coords.longitude,8047,search);setRows(data);setMessage(data.length?`${data.length} nearby options.`:'No nearby restrooms returned.');}catch(error:any){setMessage(error?.message||'Nearby restrooms could not be loaded.');}}
  return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.eyebrow}>EXPLORE</Text><Text style={s.title}>Nearby restrooms</Text><TextInput style={s.input} value={search} onChangeText={setSearch} placeholder="Search places or brands"/><Pressable style={s.primary} onPress={load}><Text style={s.primaryText}>Use my location</Text></Pressable>{message?<Text style={s.message}>{message}</Text>:null}</View><FlatList data={rows} keyExtractor={(item,index)=>String(idOf(item)||index)} contentContainerStyle={s.list} renderItem={({item})=><View style={s.card}><Text style={s.cardTitle}>{item.name||'Restroom location'}</Text><Text style={s.meta}>{[item.address,item.city,item.state].filter(Boolean).join(', ')||'Address unavailable'}</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push(`/location/${String(idOf(item))}`)}><Text style={s.secondaryText}>Details</Text></Pressable><Pressable style={s.secondary} onPress={()=>Linking.openURL(navigateUrl(item))}><Text style={s.secondaryText}>Navigate</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/route',params:{add:String(idOf(item))}})}><Text style={s.secondaryText}>Add to route</Text></Pressable></View></View>}/></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},header:{padding:20,gap:10},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:32,fontWeight:'800',color:'#14231b'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ccd9d1',borderRadius:14,padding:14},primary:{backgroundColor:'#173d2b',padding:14,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},message:{color:'#53645a'},list:{padding:20,paddingTop:0,gap:12},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0'},cardTitle:{fontSize:18,fontWeight:'800',color:'#14231b'},meta:{color:'#65756b',marginTop:6},actions:{flexDirection:'row',gap:8,marginTop:14,flexWrap:'wrap'},secondary:{backgroundColor:'#edf3ef',padding:12,borderRadius:12},secondaryText:{fontWeight:'800',color:'#173d2b'}});
