import { router } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { palette } from '../components/ConsumerUI';
import { createFamilyGroup,getFamilyState,inviteFamilyMember,type FamilyState } from '../services/family';

export default function FamilyScreen(){
  const [state,setState]=useState<FamilyState|null>(null),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=useCallback(async()=>{try{setState(await getFamilyState());setMessage('')}catch(e:any){setMessage(e?.message||'Family could not be loaded.')}},[]);
  useEffect(()=>{load()},[load]);
  async function act(fn:()=>Promise<any>,success:string){setBusy(true);setMessage('');try{await fn();await load();setMessage(success)}catch(e:any){setMessage(e?.message||'That Family action could not be completed.')}finally{setBusy(false)}}
  if(!state&&!message)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:60}}/></SafeAreaView>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
    <View style={s.hero}><Text style={s.kicker}>KLEENEST FAMILY</Text><Text style={s.title}>Premium value for five people.</Text><Text style={s.heroBody}>Family is a Consumer upgrade: one owner plus up to four additional members. Everyone keeps their own Kleenest account, history, messages, favorites and progress.</Text><View style={s.seats}><Text style={s.seatNumber}>{state?.seatsUsed??0}/5</Text><Text style={s.seatLabel}>SEATS IN USE</Text></View></View>
    {!state?.group?<View style={s.card}><Text style={s.cardTitle}>Start your Family</Text><Text style={s.body}>Purchase or restore the Family upgrade from Membership, then create the household group here. Family entitlement is verified by Kleenest before Premium access is granted.</Text><Pressable disabled={busy} style={s.primary} onPress={()=>act(()=>createFamilyGroup('My Family'),'Family created.')}><Text style={s.primaryText}>Create Family group</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/membership')}><Text style={s.secondaryText}>View Family upgrade</Text></Pressable></View>:<>
      <View style={s.card}><Text style={s.cardTitle}>Invite a member</Text><Text style={s.body}>{state.seatsAvailable} of 5 seats available. Invitations do not share credentials or personal Consumer data.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="member@example.com" style={s.input}/><Pressable disabled={busy||state.seatsAvailable<1} style={[s.primary,(busy||state.seatsAvailable<1)&&s.disabled]} onPress={()=>act(async()=>{await inviteFamilyMember(email);setEmail('')},'Invitation sent.')}><Text style={s.primaryText}>Send invitation</Text></Pressable></View>
      <View style={s.card}><Text style={s.cardTitle}>Family members</Text>{state.members.length?state.members.map((member:any,index:number)=><View key={String(member.id||index)} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{member.display_name||member.email||`Member ${index+1}`}</Text><Text style={s.rowMeta}>{String(member.role||member.status||'member').replaceAll('_',' ')}</Text></View></View>):<Text style={s.body}>Your owner seat is active. Invite up to four more people.</Text>}</View>
      <View style={s.card}><Text style={s.cardTitle}>Invitations</Text>{state.invites.length?state.invites.slice(0,8).map((invite:any,index:number)=><View key={String(invite.id||index)} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{invite.email||'Family invitation'}</Text><Text style={s.rowMeta}>{String(invite.status||'pending').replaceAll('_',' ')}</Text></View></View>):<Text style={s.body}>No invitations yet.</Text>}</View>
    </>}
    <View style={s.entitlement}><Text style={s.entitlementTitle}>{state?.premium?'Premium entitlement active':'Family entitlement pending'}</Text><Text style={s.body}>{state?.premium?'This account currently receives Premium through canonical entitlement authority.':'Premium is not inferred from an invite or screen state. Purchase/restore and backend entitlement must confirm it.'}</Text></View>
    {message?<Text style={s.message}>{message}</Text>:null}
    <Pressable style={s.secondary} onPress={()=>router.push('/membership')}><Text style={s.secondaryText}>Back to Membership</Text></Pressable>
  </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},page:{padding:20,paddingBottom:48,gap:12},hero:{backgroundColor:palette.green,padding:21,borderRadius:26,gap:8},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#bed2c5'},title:{fontSize:31,lineHeight:35,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#e0ebe4'},seats:{marginTop:7,alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.13)',paddingHorizontal:14,paddingVertical:10,borderRadius:15},seatNumber:{fontSize:25,fontWeight:'900',color:'#fff'},seatLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:'#c9dbcf'},card:{backgroundColor:'#fff',padding:17,borderRadius:20,borderWidth:1,borderColor:'#dce6df',gap:9},cardTitle:{fontSize:20,fontWeight:'900',color:palette.ink},body:{fontSize:13,lineHeight:19,color:palette.muted},input:{borderWidth:1,borderColor:'#cfdcd3',borderRadius:13,paddingHorizontal:13,paddingVertical:12,fontSize:15,color:palette.ink,backgroundColor:'#fafcfb'},primary:{backgroundColor:palette.green,padding:13,borderRadius:13,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#edf3ef',padding:13,borderRadius:13,alignItems:'center'},secondaryText:{color:palette.green,fontWeight:'900'},disabled:{opacity:.45},row:{flexDirection:'row',paddingVertical:9,borderTopWidth:1,borderTopColor:'#edf1ee'},rowTitle:{fontWeight:'900',color:palette.ink},rowMeta:{fontSize:12,color:palette.muted,marginTop:2,textTransform:'capitalize'},entitlement:{backgroundColor:'#edf4ef',padding:16,borderRadius:19,gap:4},entitlementTitle:{fontWeight:'900',fontSize:16,color:palette.green},message:{fontWeight:'700',color:palette.muted}});