import { getKleenestSupabaseClient, getMobileProgressionDashboard, listMobileBadges } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { createGameChallenge,listGameChallenges,listGameChallengeTargets,QUIZ_GAMES,recordGameChallengeScore,recordGameResult,respondGameChallenge } from '../services/games';
import { BUILDER_SCENARIOS,GAME_DEFINITIONS,MEMORY_PAIRS,roundsFor } from '../services/gameModes';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';

async function progressionSnapshot(){const[dashboard,badges]=await Promise.all([getMobileProgressionDashboard().catch(()=>({})),listMobileBadges().catch(()=>[])]);return{dashboard,badgeCount:badges.length};}
function progressionMessage(before:any,after:any,base:string){const points=Math.max(0,Number(after.dashboard?.points||0)-Number(before.dashboard?.points||0)),beforeLevel=Number(before.dashboard?.level||1),afterLevel=Number(after.dashboard?.level||1),badges=Math.max(0,Number(after.badgeCount||0)-Number(before.badgeCount||0));const rewards=[points?`+${points} progression points`:null,afterLevel>beforeLevel?`Level ${afterLevel} unlocked`:null,badges?`${badges} new badge${badges===1?'':'s'}`:null].filter(Boolean);return rewards.length?`${base} ${rewards.join(' · ')}`:base;}
const shuffle=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);

export default function GamesScreen(){
 const[game,setGame]=useState(GAME_DEFINITIONS[0]),[round,setRound]=useState(0),[score,setScore]=useState(0),[startedAt,setStartedAt]=useState(Date.now()),[saved,setSaved]=useState(false),[message,setMessage]=useState(''),[targets,setTargets]=useState<any[]>([]),[challenges,setChallenges]=useState<any[]>([]),[userId,setUserId]=useState(''),[activeChallenge,setActiveChallenge]=useState<any>(null),[memoryCards,setMemoryCards]=useState<any[]>([]),[memoryOpen,setMemoryOpen]=useState<number[]>([]),[memoryMatched,setMemoryMatched]=useState<number[]>([]),[builderSelected,setBuilderSelected]=useState<number[]>([]);
 const choiceRounds=useMemo(()=>roundsFor(game),[game]);
 const current=choiceRounds.length?choiceRounds[round%choiceRounds.length]:null;
 const builder=BUILDER_SCENARIOS[round%BUILDER_SCENARIOS.length];
 async function refreshSocial(){try{const[{data:{user}},nextTargets,nextChallenges]=await Promise.all([getKleenestSupabaseClient().auth.getUser(),listGameChallengeTargets(30),listGameChallenges(null,30)]);setUserId(user?.id||'');setTargets(nextTargets);setChallenges(nextChallenges)}catch(error:any){setMessage(error?.message||'Challenge data could not be loaded.')}}
 useEffect(()=>{refreshSocial()},[]);
 function newMemory(){const cards=shuffle(MEMORY_PAIRS.flatMap((pair,pairId)=>pair.map((text,side)=>({pairId,text,side}))));setMemoryCards(cards);setMemoryOpen([]);setMemoryMatched([]);}
 function reset(nextGame=game,challenge:any=null){setGame(nextGame);setRound(0);setScore(0);setSaved(false);setStartedAt(Date.now());setActiveChallenge(challenge);setBuilderSelected([]);setMessage(nextGame.instructions);if(nextGame.mode==='memory')setTimeout(newMemory,0);}
 useEffect(()=>{reset(game)},[]);
 function advance(correct:boolean,detail:string){const next=round+1;if(correct)setScore(v=>v+15);setMessage(`${correct?'✓':'✕'} ${detail}`);setRound(next);setBuilderSelected([]);}
 function answer(index:number){if(saved||!current||round>=game.rounds)return;advance(index===current.correct,current.detail);}
 function toggleBuilder(index:number){setBuilderSelected(v=>v.includes(index)?v.filter(x=>x!==index):[...v,index]);}
 function submitBuilder(){const a=[...builderSelected].sort().join(','),b=[...builder.correct].sort().join(',');advance(a===b,'Build only what the visit actually proves.');}
 function flipMemory(index:number){if(saved||memoryOpen.includes(index)||memoryMatched.includes(index)||memoryOpen.length>=2)return;const open=[...memoryOpen,index];setMemoryOpen(open);if(open.length===2){const[a,b]=open;if(memoryCards[a].pairId===memoryCards[b].pairId){setMemoryMatched(v=>[...v,a,b]);setScore(v=>v+20);setMessage('✓ Amenity matched to its evidence.');setRound(r=>r+1);setMemoryOpen([]);}else setTimeout(()=>setMemoryOpen([]),550);}}
 async function save(){if(saved||round===0)return;try{const before=await progressionSnapshot();if(activeChallenge)await recordGameChallengeScore(String(activeChallenge.id),score,round);else await recordGameResult(game.code,score,Date.now()-startedAt,{rounds:round,mode:game.mode,focus:'bathroom_trust'});const after=await progressionSnapshot();setSaved(true);setMessage(progressionMessage(before,after,activeChallenge?'Challenge score submitted.':'Score saved to progression.'));await refreshSocial()}catch(error:any){setMessage(error?.message||'Score could not be saved.')}}
 async function challenge(targetId:string){try{await createGameChallenge(game.code,targetId);setMessage('Challenge sent.');await refreshSocial()}catch(error:any){setMessage(error?.message||'Challenge could not be sent.')}}
 async function respond(id:string,accept:boolean){try{await respondGameChallenge(id,accept);setMessage(accept?'Challenge accepted.':'Challenge declined.');await refreshSocial()}catch(error:any){setMessage(error?.message||'Challenge could not be updated.')}}
 function playChallenge(row:any){reset(QUIZ_GAMES.find(g=>g.code===row.game_code)||QUIZ_GAMES[0],row);}
 const complete=game.mode==='memory'?memoryMatched.length===memoryCards.length&&memoryCards.length>0:round>=game.rounds;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>GAME CENTER</Text><Text style={s.title}>Different skills. Different games.</Text><Text style={s.body}>Memory, strategy, speed, routing, investigation, building and trust battles now play differently—not just under different names.</Text>
 <View style={s.scoreRow}><Stat value={score} label="score"/><Stat value={`${Math.min(round,game.rounds)}/${game.rounds}`} label={game.mode==='memory'?'pairs':'rounds'}/><Stat value={activeChallenge?'VS':'SOLO'} label="mode"/></View>
 <View style={s.section}><Text style={s.sectionTitle}>Choose a game</Text><View style={s.gameGrid}>{GAME_DEFINITIONS.map(g=><Pressable key={g.code} style={[s.gameCard,g.code===game.code&&s.gameActive]} onPress={()=>reset(g)}><Text style={s.gameIcon}>{g.accent}</Text><Text style={[s.gameName,g.code===game.code&&s.activeText]}>{g.name}</Text><Text style={[s.gameMode,g.code===game.code&&s.activeSub]}>{g.mode.replaceAll('_',' ')}</Text></Pressable>)}</View></View>
 <View style={s.quiz}><Text style={s.quizLabel}>{game.accent} {game.name.toUpperCase()} · {game.mode.replaceAll('_',' ')}</Text><Text style={s.body}>{game.description}</Text><Text style={s.instructions}>{game.instructions}</Text>
 {game.mode==='memory'?<View style={s.memoryGrid}>{memoryCards.map((card,index)=>{const shown=memoryOpen.includes(index)||memoryMatched.includes(index);return <Pressable key={index} onPress={()=>flipMemory(index)} style={[s.memoryCard,memoryMatched.includes(index)&&s.matched]}><Text style={s.memoryText}>{shown?card.text:'?'}</Text></Pressable>})}</View>:game.mode==='builder'?<><Text style={s.question}>{builder.prompt}</Text><View style={s.builderGrid}>{builder.options.map((option,index)=><Pressable key={option} onPress={()=>toggleBuilder(index)} style={[s.buildOption,builderSelected.includes(index)&&s.selected]}><Text style={[s.answerText,builderSelected.includes(index)&&s.activeText]}>{builderSelected.includes(index)?'✓ ':''}{option}</Text></Pressable>)}</View><Pressable style={s.primary} onPress={submitBuilder}><Text style={s.primaryText}>Lock profile</Text></Pressable></>:current?<><Text style={s.question}>{current.prompt}</Text>{current.choices.map((choice,index)=><Pressable key={`${round}:${choice}`} disabled={complete} style={s.answer} onPress={()=>answer(index)}><Text style={s.answerText}>{game.mode==='ranking'?`${index+1}. `:''}{choice}</Text></Pressable>)}</>:null}
 <Text style={s.message}>{message}</Text><Pressable disabled={saved||round===0||!complete} style={[s.primary,(saved||round===0||!complete)&&s.disabled]} onPress={save}><Text style={s.primaryText}>{saved?'Score saved':complete?(activeChallenge?'Submit challenge score':'Save score'):`Finish ${game.rounds-Math.min(round,game.rounds)} more`}</Text></Pressable>{saved&&/(progression points|Level|badge)/.test(message)?<Pressable onPress={()=>router.push('/play')}><Text style={s.progressLink}>See your progress →</Text></Pressable>:null}</View>
 <View style={s.section}><Text style={s.sectionTitle}>Challenge your community</Text>{targets.length?targets.slice(0,6).map(t=><View style={s.row} key={t.user_id}><Text style={[s.cardTitle,{flex:1}]}>{t.display_name||t.username||'Contributor'}</Text><Pressable style={s.secondary} onPress={()=>challenge(String(t.user_id))}><Text style={s.secondaryText}>Challenge</Text></Pressable></View>):<Text style={s.body}>Follow contributors in Community to unlock challenge targets.</Text>}</View>
 <View style={s.section}><Text style={s.sectionTitle}>Your matches</Text>{challenges.slice(0,8).map(c=><View style={s.row} key={c.id}><View style={{flex:1}}><Text style={s.cardTitle}>{QUIZ_GAMES.find(g=>g.code===c.game_code)?.name||c.game_code}</Text><Text style={s.meta}>{c.status} · {c.creator_score??'—'}–{c.invitee_score??'—'}</Text></View>{c.status==='pending'&&c.invitee_id===userId?<Pressable style={s.secondary} onPress={()=>respond(String(c.id),true)}><Text style={s.secondaryText}>Accept</Text></Pressable>:null}{c.status==='accepted'&&((c.creator_id===userId&&c.creator_score==null)||(c.invitee_id===userId&&c.invitee_score==null))?<Pressable style={s.primarySmall} onPress={()=>playChallenge(c)}><Text style={s.primaryText}>Play</Text></Pressable>:null}</View>)}</View>
 </ScrollView></SafeAreaView>;
}
function Stat({value,label}:{value:any;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},content:{padding:22,paddingBottom:42,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},scoreRow:{flexDirection:'row',gap:9},stat:{flex:1,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:'#dde7e0'},statValue:{fontSize:22,fontWeight:'900',color:'#173d2b'},meta:{fontSize:12,color:'#6c7c72',fontWeight:'700'},section:{gap:9,marginTop:10},sectionTitle:{fontSize:21,fontWeight:'900',color:'#14231b'},gameGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},gameCard:{width:'31%',minHeight:94,padding:10,borderRadius:15,backgroundColor:'#e8f0eb'},gameActive:{backgroundColor:'#173d2b'},gameIcon:{fontSize:22},gameName:{fontSize:12,fontWeight:'900',color:'#173d2b'},gameMode:{fontSize:9,fontWeight:'800',color:'#6c7c72',marginTop:3,textTransform:'uppercase'},activeText:{color:'#fff'},activeSub:{color:'#d8e5dd'},quiz:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0',gap:10},quizLabel:{fontSize:12,fontWeight:'900',color:'#4d6658',letterSpacing:1},instructions:{fontSize:14,fontWeight:'900',color:'#173d2b'},question:{fontSize:20,lineHeight:26,fontWeight:'900',color:'#14231b'},answer:{backgroundColor:'#edf3ef',padding:14,borderRadius:13},answerText:{color:'#173d2b',fontWeight:'800'},message:{fontWeight:'800',color:'#53645a'},progressLink:{fontWeight:'900',color:'#173d2b'},primary:{backgroundColor:'#173d2b',padding:14,borderRadius:14,alignItems:'center'},primarySmall:{backgroundColor:'#173d2b',paddingHorizontal:12,paddingVertical:9,borderRadius:11},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},secondary:{backgroundColor:'#edf3ef',paddingHorizontal:12,paddingVertical:9,borderRadius:11},secondaryText:{color:'#173d2b',fontWeight:'800'},row:{backgroundColor:'#fff',padding:14,borderRadius:16,flexDirection:'row',alignItems:'center',gap:10},cardTitle:{fontSize:16,fontWeight:'800',color:'#14231b'},memoryGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},memoryCard:{width:'31%',height:72,backgroundColor:'#edf3ef',borderRadius:12,alignItems:'center',justifyContent:'center',padding:6},matched:{backgroundColor:'#d9eadf'},memoryText:{fontSize:12,textAlign:'center',fontWeight:'900',color:'#173d2b'},builderGrid:{gap:8},buildOption:{padding:13,borderRadius:12,backgroundColor:'#edf3ef',borderWidth:2,borderColor:'transparent'},selected:{backgroundColor:'#173d2b',borderColor:'#173d2b'}});
