import { getKleenestSupabaseClient, getMobileProgressionDashboard, listMobileBadges } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { createGameChallenge, listGameChallenges, listGameChallengeTargets, QUESTIONS, QUIZ_GAMES, recordGameChallengeScore, recordGameResult, respondGameChallenge, shuffledQuestion } from '../services/games';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

async function progressionSnapshot(){const[dashboard,badges]=await Promise.all([getMobileProgressionDashboard().catch(()=>({})),listMobileBadges().catch(()=>[])]);return{dashboard,badgeCount:badges.length};}
function progressionMessage(before:any,after:any,base:string){const points=Math.max(0,Number(after.dashboard?.points||0)-Number(before.dashboard?.points||0)),beforeLevel=Number(before.dashboard?.level||1),afterLevel=Number(after.dashboard?.level||1),badges=Math.max(0,Number(after.badgeCount||0)-Number(before.badgeCount||0));const rewards=[points?`+${points} progression points`:null,afterLevel>beforeLevel?`Level ${afterLevel} unlocked`:null,badges?`${badges} new badge${badges===1?'':'s'}`:null].filter(Boolean);return rewards.length?`${base} ${rewards.join(' · ')}`:base;}

export default function GamesScreen(){
  const [game,setGame]=useState(QUIZ_GAMES[0]),[questionIndex,setQuestionIndex]=useState(0),[presented,setPresented]=useState(()=>shuffledQuestion(QUESTIONS[0])),[rounds,setRounds]=useState(0),[score,setScore]=useState(0),[startedAt,setStartedAt]=useState(Date.now()),[saved,setSaved]=useState(false),[message,setMessage]=useState('Choose the strongest answer.'),[targets,setTargets]=useState<any[]>([]),[challenges,setChallenges]=useState<any[]>([]),[userId,setUserId]=useState(''),[activeChallenge,setActiveChallenge]=useState<any>(null);
  async function refreshSocial(){try{const[{data:{user}},nextTargets,nextChallenges]=await Promise.all([getKleenestSupabaseClient().auth.getUser(),listGameChallengeTargets(30),listGameChallenges(null,30)]);setUserId(user?.id||'');setTargets(nextTargets);setChallenges(nextChallenges)}catch(error:any){setMessage(error?.message||'Challenge data could not be loaded.')}}
  useEffect(()=>{refreshSocial()},[]);
  function reset(nextGame=game,challenge:any=null){setGame(nextGame);setQuestionIndex(0);setPresented(shuffledQuestion(QUESTIONS[0]));setRounds(0);setScore(0);setSaved(false);setStartedAt(Date.now());setActiveChallenge(challenge);setMessage(challenge?'Head-to-head challenge started.':'Choose the strongest answer.');}
  function answer(originalIndex:number){if(saved||rounds>=8)return;const correct=originalIndex===presented.correctIndex;const nextRounds=rounds+1,nextIndex=(questionIndex+1)%QUESTIONS.length;setRounds(nextRounds);if(correct)setScore(v=>v+15);setMessage(nextRounds>=8?(correct?'Correct. Round complete!':'Round complete.'):correct?'Trustworthy choice! +15':'Not the strongest evidence.');setQuestionIndex(nextIndex);if(nextRounds<8)setPresented(shuffledQuestion(QUESTIONS[nextIndex]));}
  async function save(){if(saved||rounds===0)return;try{const before=await progressionSnapshot();if(activeChallenge)await recordGameChallengeScore(String(activeChallenge.id),score,rounds);else await recordGameResult(game.code,score,Date.now()-startedAt,{rounds,focus:'bathroom_trust'});const after=await progressionSnapshot();setSaved(true);setMessage(progressionMessage(before,after,activeChallenge?'Challenge score submitted.':'Score saved to progression.'));await refreshSocial()}catch(error:any){setMessage(error?.message||'Score could not be saved.')}}
  async function challenge(targetId:string){try{await createGameChallenge(game.code,targetId);setMessage('Challenge sent.');await refreshSocial()}catch(error:any){setMessage(error?.message||'Challenge could not be sent.')}}
  async function respond(id:string,accept:boolean){try{await respondGameChallenge(id,accept);setMessage(accept?'Challenge accepted.':'Challenge declined.');await refreshSocial()}catch(error:any){setMessage(error?.message||'Challenge could not be updated.')}}
  function playChallenge(row:any){const selected=QUIZ_GAMES.find(g=>g.code===row.game_code)||QUIZ_GAMES[0];reset(selected,row);}
  function openContributor(id:any){if(id)router.push({pathname:'/contributor/[id]',params:{id:String(id)}});}
  const playable=challenges.filter(c=>c.status==='accepted'&&((c.creator_id===userId&&c.creator_score==null)||(c.invitee_id===userId&&c.invitee_score==null)));
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>GAME CENTER</Text><Text style={s.title}>Learn trust. Earn progress. Challenge friends.</Text><Text style={s.body}>Games teach the same signals that make bathroom reviews and recommendations useful.</Text>
    <View style={s.scoreRow}><Stat value={score} label="score"/><Stat value={`${rounds}/8`} label="questions"/><Stat value={activeChallenge?'VS':'SOLO'} label="mode"/></View>
    <View style={s.section}><Text style={s.sectionTitle}>Choose a game</Text><View style={s.pills}>{QUIZ_GAMES.map(g=><Pressable key={g.code} style={[s.pill,g.code===game.code&&s.pillActive]} onPress={()=>reset(g)}><Text style={[s.pillText,g.code===game.code&&s.pillTextActive]}>{g.name}</Text></Pressable>)}</View><Text style={s.body}>{game.description}</Text></View>
    <View style={s.quiz}><Text style={s.quizLabel}>{activeChallenge?'HEAD-TO-HEAD':'NOW PLAYING'} · {game.name}</Text><Text style={s.question}>{presented.prompt}</Text>{presented.options.map(option=><Pressable key={`${questionIndex}:${option.index}`} disabled={saved||rounds>=8} style={s.answer} onPress={()=>answer(option.index)}><Text style={s.answerText}>{option.text}</Text></Pressable>)}<Text style={s.message}>{message}</Text>{saved&&/(progression points|Level|badge)/.test(message)?<Pressable onPress={()=>router.push('/play')}><Text style={s.progressLink}>See your progress →</Text></Pressable>:null}<Pressable disabled={saved||rounds===0} style={[s.primary,(saved||rounds===0)&&s.disabled]} onPress={save}><Text style={s.primaryText}>{saved?'Score saved':activeChallenge?'Submit challenge score':'Save score'}</Text></Pressable></View>
    <View style={s.section}><Text style={s.sectionTitle}>Challenge your community</Text>{targets.length?targets.slice(0,8).map(target=><View style={s.row} key={target.user_id}><Pressable style={{flex:1}} onPress={()=>openContributor(target.user_id)}><Text style={s.cardTitle}>{target.display_name||target.username||'Kleenest contributor'}</Text><Text style={s.meta}>{target.relationship||'community'} · View profile →</Text></Pressable><Pressable style={s.secondary} onPress={()=>challenge(String(target.user_id))}><Text style={s.secondaryText}>Challenge</Text></Pressable></View>):<Text style={s.body}>Follow contributors in Community to unlock challenge targets.</Text>}</View>
    <View style={s.section}><Text style={s.sectionTitle}>Your matches</Text>{challenges.length?challenges.slice(0,12).map(c=>{const opponentId=c.creator_id===userId?c.invitee_id:c.creator_id;const opponentName=c.creator_id===userId?c.invitee_name:c.creator_name||'Opponent';return <View style={s.card} key={c.id}><Text style={s.cardTitle}>{QUIZ_GAMES.find(g=>g.code===c.game_code)?.name||c.game_code}</Text><Pressable onPress={()=>openContributor(opponentId)}><Text style={s.meta}>{opponentName} · {c.status} · View profile →</Text></Pressable><View style={s.actions}>{c.status==='pending'&&c.invitee_id===userId?<><Pressable style={s.primarySmall} onPress={()=>respond(String(c.id),true)}><Text style={s.primaryText}>Accept</Text></Pressable><Pressable style={s.secondary} onPress={()=>respond(String(c.id),false)}><Text style={s.secondaryText}>Decline</Text></Pressable></>:null}{playable.some(p=>p.id===c.id)?<Pressable style={s.primarySmall} onPress={()=>playChallenge(c)}><Text style={s.primaryText}>Play match</Text></Pressable>:null}{c.status==='completed'?<Text style={s.meta}>{c.winner_id===userId?'You won':'Match complete'} · {c.creator_score??0}–{c.invitee_score??0}</Text>:null}</View></View>}):<Text style={s.body}>No game challenges yet.</Text>}</View>
  </ScrollView></SafeAreaView>;
}
function Stat({value,label}:{value:any;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},content:{padding:22,paddingBottom:42,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},scoreRow:{flexDirection:'row',gap:9},stat:{flex:1,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:'#dde7e0'},statValue:{fontSize:22,fontWeight:'900',color:'#173d2b'},meta:{fontSize:12,color:'#6c7c72',fontWeight:'700'},section:{gap:9,marginTop:10},sectionTitle:{fontSize:21,fontWeight:'900',color:'#14231b'},pills:{flexDirection:'row',flexWrap:'wrap',gap:7},pill:{paddingHorizontal:11,paddingVertical:9,borderRadius:999,backgroundColor:'#e8f0eb'},pillActive:{backgroundColor:'#173d2b'},pillText:{fontSize:12,fontWeight:'800',color:'#173d2b'},pillTextActive:{color:'#fff'},quiz:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0',gap:10},quizLabel:{fontSize:12,fontWeight:'900',color:'#4d6658',letterSpacing:1},question:{fontSize:20,lineHeight:26,fontWeight:'900',color:'#14231b'},answer:{backgroundColor:'#edf3ef',padding:14,borderRadius:13},answerText:{color:'#173d2b',fontWeight:'800'},message:{fontWeight:'800',color:'#53645a'},progressLink:{fontWeight:'900',color:'#173d2b'},primary:{backgroundColor:'#173d2b',padding:14,borderRadius:14,alignItems:'center'},primarySmall:{backgroundColor:'#173d2b',paddingHorizontal:12,paddingVertical:9,borderRadius:11},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},secondary:{backgroundColor:'#edf3ef',paddingHorizontal:12,paddingVertical:9,borderRadius:11},secondaryText:{color:'#173d2b',fontWeight:'800'},row:{backgroundColor:'#fff',padding:14,borderRadius:16,flexDirection:'row',alignItems:'center',gap:10},card:{backgroundColor:'#fff',padding:15,borderRadius:17,borderWidth:1,borderColor:'#dde7e0',gap:6},cardTitle:{fontSize:16,fontWeight:'800',color:'#14231b'},actions:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'}});
