import { getMobileProgressionSummary, listMobileActivity } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function HomeScreen() {
  const [progress,setProgress]=useState<any>(null),[activity,setActivity]=useState<any[]>([]);
  useEffect(()=>{Promise.all([getMobileProgressionSummary(),listMobileActivity(4)]).then(([p,a])=>{setProgress(p);setActivity(a)}).catch(()=>{})},[]);
  const profile=progress?.profile||progress||{};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>KLEENEST</Text><Text style={styles.title}>Find a bathroom without the detour.</Text><Text style={styles.body}>Nearby restroom discovery stays first. Pick a place and navigate directly.</Text><Pressable style={styles.primary} onPress={()=>router.push('/explore')}><Text style={styles.primaryText}>Find nearby restrooms</Text></Pressable>
  <View style={styles.divider}/><Text style={styles.eyebrow}>YOUR KLEENEST</Text><Text style={styles.sectionTitle}>Play, progress, and help the community.</Text><View style={styles.stats}><Stat value={profile.points??0} label="points"/><Stat value={profile.level??1} label="level"/><Stat value={`${profile.streak??0}d`} label="streak"/></View><Pressable style={styles.play} onPress={()=>router.push('/play')}><Text style={styles.playTitle}>Open Play + Progress</Text><Text style={styles.playBody}>Challenges · badges · contests · leaderboard</Text></Pressable><View style={styles.actions}><Pressable style={styles.secondary} onPress={()=>router.push('/social')}><Text style={styles.secondaryText}>Find people</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.push('/activity')}><Text style={styles.secondaryText}>Community activity</Text></Pressable></View>
  {activity.length?<View style={styles.feed}><Text style={styles.feedTitle}>Fresh community activity</Text>{activity.slice(0,3).map(item=><View key={item.id} style={styles.feedRow}><Text style={styles.feedRowTitle}>{item.title}</Text><Text style={styles.meta}>{item.location?.name||item.detail||'Kleenest community'}</Text></View>)}</View>:null}</ScrollView></SafeAreaView>;
}
function Stat({value,label}:{value:any;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.meta}>{label}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},container:{padding:24,paddingBottom:42},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:40,lineHeight:43,fontWeight:'900',color:'#14231b',marginTop:10,marginBottom:14},body:{fontSize:17,lineHeight:25,color:'#53645a',marginBottom:20},primary:{backgroundColor:'#173d2b',padding:17,borderRadius:16,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},divider:{height:1,backgroundColor:'#dce6df',marginVertical:26},sectionTitle:{fontSize:27,lineHeight:31,fontWeight:'900',color:'#14231b',marginTop:8,marginBottom:14},stats:{flexDirection:'row',gap:9},stat:{flex:1,backgroundColor:'#fff',padding:14,borderRadius:16,borderWidth:1,borderColor:'#dde7e0'},statValue:{fontSize:22,fontWeight:'900',color:'#173d2b'},meta:{fontSize:12,color:'#6c7c72',fontWeight:'700'},play:{backgroundColor:'#20382b',padding:18,borderRadius:18,marginTop:12},playTitle:{fontSize:18,fontWeight:'900',color:'#fff'},playBody:{color:'#dce9e1',marginTop:4},actions:{flexDirection:'row',gap:10,marginTop:10},secondary:{flex:1,backgroundColor:'#e8f0eb',padding:13,borderRadius:14,alignItems:'center'},secondaryText:{color:'#173d2b',fontWeight:'800'},feed:{marginTop:22,gap:8},feedTitle:{fontSize:18,fontWeight:'900',color:'#14231b'},feedRow:{backgroundColor:'#fff',padding:14,borderRadius:14},feedRowTitle:{fontWeight:'800',color:'#14231b'}});
