import { useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,Share,StyleSheet,Text,View } from 'react-native';
import { BATHROOM_FIT_OPTIONS,getConsumerIntelligence,getBathroomFit,getBathroomFitPreferences,getLocationExplanation,getLocationProofCard,getLocationTrustChanges,setLocationTrustWatch,updateBathroomFitPreferences,type BathroomFitPreferences } from '../services/intelligenceLayer';
import { useConsumerTheme } from '../services/theme';

const pretty=(v:unknown)=>String(v??'').replaceAll('_',' ');
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString():'Not recorded';
export default function Intelligence(){
 const theme=useConsumerTheme();
 const params=useLocalSearchParams<{locationId?:string|string[]}>();
 const locationId=Array.isArray(params.locationId)?params.locationId[0]:String(params.locationId||'');
 const[data,setData]=useState<any>(null),[prefs,setPrefs]=useState<Partial<BathroomFitPreferences>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading Kleenest intelligence…');
 async function load(){if(!locationId){setMessage('Open Kleenest intelligence from a location.');return}setBusy(true);try{const next=await getConsumerIntelligence(locationId);setData(next);setPrefs(next.preferences||{});setMessage('')}catch(e:any){setMessage(e?.message||'Kleenest intelligence unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[locationId]);
 async function toggle(key:keyof BathroomFitPreferences){const next={...prefs,[key]:!Boolean(prefs[key])};setPrefs(next);try{await updateBathroomFitPreferences(next);if(locationId){const[fit,stored]=await Promise.all([getBathroomFit(locationId),getBathroomFitPreferences()]);setPrefs(stored);setData((old:any)=>({...old,fit}));}setMessage('Bathroom Fit preferences updated.')}catch(e:any){setMessage(e?.message||'Could not update Bathroom Fit preferences.')}}
 const n=data?.now||{},passport=data?.passport||{},access=data?.access||{},fit=data?.fit||{},milestones=Array.isArray(passport?.milestones)?passport.milestones:[];
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={[s.page,{backgroundColor:theme.canvas}]}>
  <View style={[s.hero,{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:'#173f2d',borderColor:theme.line}]}><Text style={s.kicker}>KLEENEST NOW</Text><Text style={s.title}>{n?.name||passport?.location?.name||'Current restroom intelligence'}</Text><Text style={s.body}>Freshness tells you how recent the strongest current evidence is. Confidence tells you how strongly Kleenest can independently support the current condition.</Text></View>
  {message?<View style={[s.notice,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.meta,{color:theme.ink,fontWeight:'800'}]}>{message}</Text></View>:null}
  <QualityPassIntelligence locationId={locationId} theme={theme}/>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>KLEENEST NOW</Text><View style={s.metrics}><Metric label="Freshness" value={n.freshness_score==null?'—':`${Math.round(Number(n.freshness_score))}%`} theme={theme}/><Metric label="Confidence" value={n.confidence_score==null?'—':`${Math.round(Number(n.confidence_score))}%`} theme={theme}/><Metric label="Independent" value={String(Number(n.independent_confirmations||0))} theme={theme}/></View><Text style={[s.headline,{color:theme.ink}]}>{pretty(n.freshness_label||'unknown')} · {pretty(n.freshness_provenance||'inferred')}</Text><Text style={[s.meta,{color:theme.muted}]}>{n.latest_service?`Business reported ${pretty(n.latest_service.event_kind)} · ${when(n.latest_service.reported_at)}`:`Last evidence: ${when(n.freshness_at)}`}</Text>{Number(n.recent_conflicts||0)>0?<Text style={[s.warning,{color:theme.warning}]}>Recent contradictory evidence: {Number(n.recent_conflicts)}</Text>:null}<Text style={[s.meta,{color:theme.muted}]}>{n.explanation?.confidence}</Text></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>BATHROOM FIT</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Bathroom Fit</Text><Text style={[s.meta,{color:theme.muted}]}>Choose practical restroom features you care about. These preferences are used for matching only—Kleenest does not infer health information.</Text><View style={s.chips}>{BATHROOM_FIT_OPTIONS.map(([key,label])=><Pressable key={key} onPress={()=>toggle(key)} style={[s.chip,{backgroundColor:prefs[key]?theme.accent:theme.surfaceRaised,borderColor:theme.line}]}><Text style={{fontWeight:'900',fontSize:11,color:prefs[key]?theme.accentText:theme.ink}}>{prefs[key]?'✓ ':''}{label}</Text></Pressable>)}</View><View style={s.fitLine}><Text style={[s.fitScore,{color:theme.ink}]}>{fit.score==null?'—':`${Math.round(Number(fit.score))}%`}</Text><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>Match for this restroom</Text><Text style={[s.meta,{color:theme.muted}]}>{Array.isArray(fit.matched)&&fit.matched.length?`Matches: ${fit.matched.map(pretty).join(', ')}`:'Set preferences to get a fit score.'}</Text>{Array.isArray(fit.missing)&&fit.missing.length?<Text style={[s.meta,{color:theme.muted}]}>Not confirmed: {fit.missing.map(pretty).join(', ')}</Text>:null}</View></View></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>VERIFIED ACCESS</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Verified Access</Text><View style={[s.accessPill,{backgroundColor:access.allowed?theme.accentSoft:theme.surfaceRaised,borderColor:theme.line}]}><Text style={[s.accessTitle,{color:access.allowed?theme.accent:theme.ink}]}>{access.allowed?'ACCESS AVAILABLE':'NO ENTITLEMENT CONFIRMED'}</Text><Text style={[s.meta,{color:theme.muted}]}>{access.reason||'Kleenest could not confirm a current entitlement for this facility.'}</Text><Text style={[s.meta,{color:theme.muted}]}>Source: {pretty(access.source||'none')}</Text></View></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>FACILITY PASSPORT</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Facility Passport</Text><Text style={[s.meta,{color:theme.muted}]}>A living record built from discovery, verification, claimed-business service, amenities and trust recovery—without rewriting the original evidence.</Text><View style={s.metrics}><Metric label="Reviews" value={String(passport?.summary?.reviews||0)} theme={theme}/><Metric label="Observations" value={String(passport?.summary?.observations||0)} theme={theme}/><Metric label="Service updates" value={String(passport?.summary?.service_updates||0)} theme={theme}/></View>{milestones.slice(0,12).map((row:any,index:number)=><View key={`${row.kind}-${row.occurred_at}-${index}`} style={[s.row,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>{row.label||pretty(row.kind)}</Text><Text style={[s.meta,{color:theme.muted}]}>{when(row.occurred_at)} · {pretty(row.provenance)}</Text></View></View>)}{!milestones.length?<Text style={[s.meta,{color:theme.muted}]}>The Facility Passport will grow as evidence and service history accumulate.</Text>:null}</View>
 </ScrollView>
}
function QualityPassIntelligence({locationId,theme}:{locationId:string;theme:any}){
 const[why,setWhy]=useState<any>(null),[proof,setProof]=useState<any>(null),[changes,setChanges]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){if(!locationId)return;setBusy(true);try{const[explanation,card,allChanges]=await Promise.all([getLocationExplanation(locationId),getLocationProofCard(locationId),getLocationTrustChanges(40).catch(()=>[])]);setWhy(explanation);setProof(card);setChanges((Array.isArray(allChanges)?allChanges:[]).filter((row:any)=>String(row.location_id)===locationId));setMessage('')}catch(e:any){setMessage(e?.message||'Evidence explanation unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[locationId]);
 async function toggleWatch(){if(!locationId)return;setBusy(true);try{await setLocationTrustWatch(locationId,!Boolean(why?.watched));setMessage(why?.watched?'Trust-change alerts turned off.':'Trust-change alerts turned on. Only meaningful evidence changes surface; following a place never awards XP.');await load()}catch(e:any){setMessage(e?.message||'Could not update trust-change alerts.')}finally{setBusy(false)}}
 async function shareProof(){if(!proof)return;try{await Share.share({message:String(proof.share_text||proof.deep_link||'Kleenest proof card')})}catch(e:any){setMessage(e?.message||'Proof card could not be shared.')}}
 const rationale=Array.isArray(why?.rationale)?why.rationale:[],evidence=Array.isArray(why?.recent_evidence)?why.recent_evidence:[],amenities=Array.isArray(proof?.amenities)?proof.amenities:[];
 return <>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>WHY KLEENEST?</Text><Text style={[s.cardTitle,{color:theme.ink}]}>See the evidence behind the signal</Text><Text style={[s.meta,{color:theme.muted}]}>Freshness, confidence and recommendations stay explainable. Business-reported service is labeled separately from independent confirmation.</Text>{rationale.map((line:any,index:number)=><Text key={index} style={[s.meta,{color:theme.ink}]}>• {String(line)}</Text>)}{evidence.slice(0,5).map((row:any,index:number)=><View key={index} style={[s.row,{borderColor:theme.line}]}><View style={{flex:1}}><Text style={[s.rowTitle,{color:theme.ink}]}>{pretty(row.kind)}</Text><Text style={[s.meta,{color:theme.muted}]}>{pretty(row.provenance)} · {when(row.observed_at)} · confidence {Math.round(Number(row.confidence||0)*100)}%</Text></View></View>)}{message?<Text style={[s.meta,{color:theme.warning}]}>{message}</Text>:null}</View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>PROOF CARD</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{proof?.name||why?.location?.name||'Kleenest proof'}</Text><View style={s.metrics}><Metric label="Freshness" value={proof?.freshness_score==null?'—':Math.round(Number(proof.freshness_score))+'%'} theme={theme}/><Metric label="Confidence" value={proof?.confidence_score==null?'—':Math.round(Number(proof.confidence_score))+'%'} theme={theme}/><Metric label="Confirmations" value={String(Number(proof?.independent_confirmations||0))} theme={theme}/></View><Text style={[s.meta,{color:theme.muted}]}>Evidence age {proof?.evidence_age_days==null?'unknown':proof.evidence_age_days+' day(s)'} · {pretty(proof?.freshness_provenance||'inferred')}</Text>{amenities.length?<Text style={[s.meta,{color:theme.muted}]}>Confirmed amenities: {amenities.slice(0,8).join(', ')}</Text>:null}<Pressable disabled={busy||!proof} onPress={()=>void shareProof()} style={[s.chip,{backgroundColor:theme.accent,borderColor:theme.line,alignSelf:'flex-start'}]}><Text style={{fontWeight:'900',fontSize:11,color:theme.accentText}}>Share proof card</Text></Pressable></View>
  <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.eyebrow,{color:theme.accent}]}>TRUST CHANGE ALERTS</Text><Text style={[s.cardTitle,{color:theme.ink}]}>Meaningful changes only</Text><Text style={[s.meta,{color:theme.muted}]}>Watch this place for freshness, confidence, contradiction, service or availability changes. Passive watching never awards XP or Trust.</Text><Pressable disabled={busy} onPress={()=>void toggleWatch()} style={[s.chip,{backgroundColor:why?.watched?theme.surfaceRaised:theme.accent,borderColor:theme.line,alignSelf:'flex-start'}]}><Text style={{fontWeight:'900',fontSize:11,color:why?.watched?theme.ink:theme.accentText}}>{why?.watched?'Stop watching':'Watch meaningful changes'}</Text></Pressable>{changes.map((row:any,index:number)=><View key={index} style={[s.row,{borderColor:theme.line}]}><Text style={[s.meta,{color:theme.ink}]}>{Array.isArray(row.changes)?row.changes.join(' · '):'Evidence changed'}</Text></View>)}{why?.watched&&!changes.length?<Text style={[s.meta,{color:theme.muted}]}>No new meaningful changes since the last snapshot.</Text>:null}</View>
 </>
}
function Metric({label,value,theme}:{label:string;value:string;theme:any}){return <View style={[s.metric,{backgroundColor:theme.surfaceRaised,borderColor:theme.line}]}><Text style={[s.metricValue,{color:theme.ink}]}>{value}</Text><Text style={[s.meta,{color:theme.muted}]}>{label}</Text></View>}
const s=StyleSheet.create({page:{padding:16,gap:12,paddingBottom:90},hero:{borderRadius:20,padding:16,gap:6,borderWidth:1},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#c9e8d4'},title:{fontSize:24,fontWeight:'900',color:'#fff'},body:{fontSize:12,lineHeight:18,color:'#e4eee8'},notice:{borderWidth:1,borderRadius:14,padding:11},card:{borderWidth:1,borderRadius:18,padding:14,gap:9},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},cardTitle:{fontSize:19,fontWeight:'900'},headline:{fontSize:16,fontWeight:'900',textTransform:'capitalize'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{minWidth:92,flexGrow:1,borderWidth:1,borderRadius:14,padding:10},metricValue:{fontSize:19,fontWeight:'900'},meta:{fontSize:11,lineHeight:16},warning:{fontSize:11,fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:999,borderWidth:1},fitLine:{flexDirection:'row',gap:12,alignItems:'center'},fitScore:{fontSize:29,fontWeight:'900'},row:{borderTopWidth:1,paddingTop:9},rowTitle:{fontSize:13,fontWeight:'900'},accessPill:{borderWidth:1,borderRadius:14,padding:12,gap:4},accessTitle:{fontSize:12,fontWeight:'900'}});
