import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { disableConsumerLiveNetwork,enableConsumerLiveNetwork,getConsumerLiveNetworkStatus,openConsumerLiveNetworkSettings,refreshConsumerLiveNetworkRegions } from '../services/liveNetwork';
import { listLiveNetworkMotifs,subscribeLiveNetworkMotifs,type LiveNetworkMotif } from '../services/liveNetworkMotifs';

type Status=Awaited<ReturnType<typeof getConsumerLiveNetworkStatus>>;

export default function LiveNetworkScreen(){
 const[status,setStatus]=useState<Status|null>(null),[motifs,setMotifs]=useState<LiveNetworkMotif[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[lastLiveAt,setLastLiveAt]=useState<string|null>(null);
 const load=useCallback(async()=>{const nextStatus=await getConsumerLiveNetworkStatus();setStatus(nextStatus);const nextMotifs=await listLiveNetworkMotifs(60);setMotifs(nextMotifs)},[]);
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:String(e))).finally(()=>setLoading(false))},[load]);
 useEffect(()=>subscribeLiveNetworkMotifs(()=>{setLastLiveAt(new Date().toISOString());listLiveNetworkMotifs(60).then(setMotifs).catch(e=>setError(e instanceof Error?e.message:String(e))) }),[]);
 async function reload(){setRefreshing(true);setError(null);try{await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRefreshing(false)}}
 async function run(action:()=>Promise<unknown>,message:string){setBusy(true);setError(null);setNotice(null);try{await action();setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:String(e));await load().catch(()=>undefined)}finally{setBusy(false)}}
 function confirmEnableLiveNetwork(){Alert.alert('Allow background location for Live Network','Kleenest collects location data to enable Live Network nearby-restroom alerts even when the app is closed or not in use. Kleenest does not use this background location for advertising, and you can turn Live Network off at any time.',[{text:'Not now',style:'cancel'},{text:'Continue',onPress:()=>void run(enableConsumerLiveNetwork,'Live Network is enabled on this device.')}]);}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 const backgroundReady=status?.background==='granted';
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:72}}>
  <View style={hero}><Text style={eyebrow}>KLEENEST LIVE NETWORK</Text><Text style={heroTitle}>Helpful bathrooms can find you too</Text><Text style={heroBody}>Live Network combines nearby geofencing with privacy-safe realtime motifs: patterns in discovery, routing, occupancy, quality and source health across the Kleenest trust network.</Text></View>
  {error?<View style={errorCard}><Text style={{color:'#9b2c2c',fontWeight:'800'}}>{error}</Text></View>:null}{notice?<View style={noticeCard}><Text style={{color:'#22553a',fontWeight:'800'}}>{notice}</Text></View>:null}
  <View style={grid}><Metric label="Live Network" value={status?.registered?'On':'Off'}/><Metric label="Nearby regions" value={String(status?.regionCount??0)}/><Metric label="Live motifs" value={String(motifs.filter(item=>item.severity!=='quiet').length)}/><Metric label="Realtime" value={lastLiveAt?'Updated':'Listening'}/></View>
  <View style={card}><Text style={kicker}>NETWORK MOTIFS · LAST 60 MIN</Text><Text style={heading}>What the network is sensing</Text><Text style={muted}>These are aggregate patterns, not a feed of individual people or precise movements. Realtime changes refresh the analysis without exposing raw geofence or Fleet telemetry.</Text></View>
  <View style={{gap:10}}>{motifs.map(item=><MotifCard key={item.motif_key} item={item}/>)}</View>
  <View style={card}><Text style={heading}>Device controls</Text><Text style={muted}>Live Network is opt-in. Android background access is granted from the app's system location settings instead of forcing a settings transition in the middle of this screen. Return here after choosing Allow all the time.</Text><View style={row}><Action disabled={busy} label={status?.registered?'Live Network enabled':'Enable Live Network'} onPress={confirmEnableLiveNetwork}/>{!backgroundReady?<Action secondary disabled={busy} label="Open location settings" onPress={()=>run(openConsumerLiveNetworkSettings,'Location settings opened. Return here after granting background access.')}/>:null}<Action secondary disabled={busy||!status?.registered} label="Turn off" onPress={()=>run(disableConsumerLiveNetwork,'Live Network is off on this device.')}/><Action secondary disabled={busy||!status?.registered} label="Refresh nearby regions" onPress={()=>run(refreshConsumerLiveNetworkRegions,'Nearby Live Network regions refreshed.')}/></View></View>
  <View style={card}><Text style={heading}>How it works</Text><Text style={muted}>Kleenest registers only the closest restroom regions the operating system can monitor: up to 20 on iOS and up to 100 on Android. Entering a monitored restroom region uses the canonical geofence pipeline. Separately, sanitized network revision signals refresh the motif analysis above in realtime.</Text></View>
  <View style={card}><Text style={heading}>Privacy & permission safety</Text><Text style={muted}>Consumer motifs are deliberately aggregate-only. Business geofence flow and Fleet operational pressure are excluded from Consumer responses. Live Network does not need your microphone and does not draw over other apps.</Text></View>
 </ScrollView>;
}
function MotifCard({item}:{item:LiveNetworkMotif}){return <View style={card}><View style={{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10}}><View style={{flex:1,gap:3}}><Text style={{fontSize:18,fontWeight:'900',color:'#173024'}}>{item.label}</Text><Text style={muted}>{motifDetail(item)}</Text></View><View style={[severityPill,item.severity==='high'||item.severity==='elevated'?{backgroundColor:'#fff0d8'}:undefined]}><Text style={{fontSize:10,fontWeight:'900',color:item.severity==='high'||item.severity==='elevated'?'#85551b':'#28533c'}}>{item.severity.toUpperCase()}</Text></View></View><View style={row}><Badge text={`${item.observed_count} signals`}/><Badge text={`${Math.round(item.confidence*100)}% confidence`}/>{item.last_seen_at?<Badge text={`Seen ${formatTime(item.last_seen_at)}`}/>:null}</View></View>}
function motifDetail(item:LiveNetworkMotif){const e=item.evidence??{};switch(item.motif_key){case'network_momentum':return `${num(e.discoveries)} discovery signals and ${num(e.routes)} route intents are shaping current network momentum.`;case'occupancy_pressure':return `${pct(e.occupancy_ratio)} observed occupancy · ${num(e.queue_avg,1)} avg queue · ${num(e.wait_minutes_avg,1)} min avg wait.`;case'quality_drift':return `Cleanliness ${num(e.cleanliness_avg,1)} · safety ${num(e.safety_avg,1)} · availability ${num(e.availability_avg,1)} from recent trust evidence.`;case'source_health':return `${num(e.degraded)} source-health degradations and ${num(e.recovered)} recoveries in the analysis window.`;default:return `${item.observed_count} aggregate observations contributed to this motif.`}}
function num(value:unknown,digits=0){const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):'—'}
function pct(value:unknown){const n=Number(value);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}
function formatTime(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?'recently':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function Metric({label,value}:{label:string;value:string}){return <View style={metric}><Text style={muted}>{label}</Text><Text style={{fontSize:20,fontWeight:'900',color:'#173024'}}>{value}</Text></View>}
function Badge({text}:{text:string}){return <View style={{backgroundColor:'#edf3ef',borderRadius:999,paddingHorizontal:9,paddingVertical:5}}><Text style={{fontSize:11,fontWeight:'900',color:'#28533c'}}>{text}</Text></View>}
function Action({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[action,secondary&&secondaryAction,disabled&&{opacity:.45}]}><Text style={{fontWeight:'900',color:secondary?'#244d39':'white'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:7},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={color:'white' as const,fontSize:27,fontWeight:'900' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},heading={fontSize:20,fontWeight:'900' as const,color:'#173024' as const},kicker={fontSize:10,fontWeight:'900' as const,letterSpacing:1.2,color:'#547060' as const},muted={color:'#66766e' as const,lineHeight:19},grid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},metric={backgroundColor:'white' as const,borderRadius:16,padding:13,minWidth:120,flexGrow:1},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},action={backgroundColor:'#173f2d' as const,borderRadius:999,paddingHorizontal:13,paddingVertical:9,alignSelf:'flex-start' as const},secondaryAction={backgroundColor:'#edf3ef' as const},severityPill={backgroundColor:'#edf3ef' as const,borderRadius:999,paddingHorizontal:9,paddingVertical:6},errorCard={backgroundColor:'#fae7e7' as const,borderRadius:14,padding:12},noticeCard={backgroundColor:'#e4f3ea' as const,borderRadius:14,padding:12};
