import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Text,View } from 'react-native';
import { disableConsumerLiveNetwork,enableConsumerLiveNetwork,getConsumerLiveNetworkStatus,refreshConsumerLiveNetworkRegions } from '../services/liveNetwork';

type Status=Awaited<ReturnType<typeof getConsumerLiveNetworkStatus>>;

export default function LiveNetworkScreen(){
 const[status,setStatus]=useState<Status|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>setStatus(await getConsumerLiveNetworkStatus()),[]);
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:String(e))).finally(()=>setLoading(false))},[load]);
 async function reload(){setRefreshing(true);setError(null);try{await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRefreshing(false)}}
 async function run(action:()=>Promise<unknown>,message:string){setBusy(true);setError(null);setNotice(null);try{await action();setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(loading)return <View style={{flex:1,justifyContent:'center'}}><ActivityIndicator size="large"/></View>;
 return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload}/>} contentContainerStyle={{padding:16,gap:16,paddingBottom:72}}>
  <View style={hero}><Text style={eyebrow}>KLEENEST LIVE NETWORK</Text><Text style={heroTitle}>Helpful bathrooms can find you too</Text><Text style={heroBody}>When you turn Live Network on, Kleenest can watch a limited set of nearby restroom regions and alert you when one is close—even while the app is in the background.</Text></View>
  {error?<View style={errorCard}><Text style={{color:'#9b2c2c',fontWeight:'800'}}>{error}</Text></View>:null}{notice?<View style={noticeCard}><Text style={{color:'#22553a',fontWeight:'800'}}>{notice}</Text></View>:null}
  <View style={grid}><Metric label="Live Network" value={status?.registered?'On':'Off'}/><Metric label="Nearby regions" value={String(status?.regionCount??0)}/><Metric label="Location" value={String(status?.foreground??'unknown')}/><Metric label="Background" value={String(status?.background??'unknown')}/></View>
  <View style={card}><Text style={heading}>Device controls</Text><Text style={muted}>Live Network is opt-in. Enabling it requests foreground location first, then background location, then notification permission. You can turn it off at any time.</Text><View style={row}><Action disabled={busy} label={status?.registered?'Live Network enabled':'Enable Live Network'} onPress={()=>run(enableConsumerLiveNetwork,'Live Network is enabled on this device.')}/><Action secondary disabled={busy||!status?.registered} label="Turn off" onPress={()=>run(disableConsumerLiveNetwork,'Live Network is off on this device.')}/><Action secondary disabled={busy||!status?.registered} label="Refresh nearby regions" onPress={()=>run(refreshConsumerLiveNetworkRegions,'Nearby Live Network regions refreshed.')}/></View></View>
  <View style={card}><Text style={heading}>How it works</Text><Text style={muted}>Kleenest registers only the closest restroom regions the operating system can monitor: up to 20 on iOS and up to 100 on Android. The region set refreshes when you ask it to and can be refreshed when the app becomes active. Entering a monitored restroom region creates the same canonical nearby-restroom notification used elsewhere in Kleenest.</Text></View>
  <View style={card}><Text style={heading}>Privacy & permission safety</Text><Text style={muted}>Live Network does not need your microphone and does not draw over other apps. Those Android permissions are explicitly blocked. Background location is used only for the nearby-restroom feature you enable here, and you can revoke it in system settings at any time.</Text></View>
 </ScrollView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={metric}><Text style={muted}>{label}</Text><Text style={{fontSize:20,fontWeight:'900',color:'#173024'}}>{value}</Text></View>}
function Action({label,onPress,disabled,secondary=false}:{label:string;onPress:()=>void|Promise<void>;disabled?:boolean;secondary?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[action,secondary&&secondaryAction,disabled&&{opacity:.45}]}><Text style={{fontWeight:'900',color:secondary?'#244d39':'white'}}>{label}</Text></Pressable>}
const hero={backgroundColor:'#173f2d' as const,borderRadius:24,padding:19,gap:7},eyebrow={color:'#bfe0cd' as const,fontWeight:'900' as const,letterSpacing:1},heroTitle={color:'white' as const,fontSize:27,fontWeight:'900' as const},heroBody={color:'#dce9e2' as const,lineHeight:20},card={backgroundColor:'white' as const,borderRadius:18,padding:16,gap:10},heading={fontSize:20,fontWeight:'900' as const,color:'#173024' as const},muted={color:'#66766e' as const,lineHeight:19},grid={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},metric={backgroundColor:'white' as const,borderRadius:16,padding:13,minWidth:120,flexGrow:1},row={flexDirection:'row' as const,flexWrap:'wrap' as const,gap:8},action={backgroundColor:'#173f2d' as const,borderRadius:999,paddingHorizontal:13,paddingVertical:9,alignSelf:'flex-start' as const},secondaryAction={backgroundColor:'#edf3ef' as const},errorCard={backgroundColor:'#fae7e7' as const,borderRadius:14,padding:12},noticeCard={backgroundColor:'#e4f3ea' as const,borderRadius:14,padding:12};
