import { getMobileAccountSummary, listMobilePricingCatalog } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { TrustStrip, palette } from '../components/ConsumerUI';

const formatPrice=(plan:any)=>plan?.price_note||(plan?.price_cents==null?'Contact':plan.price_cents===0?'Free':`${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(plan.price_cents)/100)}${plan.interval==='month'?'/month':plan.interval==='once'?' one-time':''}`);
const benefitCopy=(code:string)=>code==='premium_user'?['Every Consumer capability included','One-time $5 permanent Premium entitlement','Advertising removed when ad inventory is present']:code==='family'?['Same complete Consumer capability set','Shared household access for up to 5 users','One-time Family entitlement']:['Every Consumer capability included','Trusted restroom discovery + evidence','Community, routes, QR, AI, progression and access tools'];

export default function MembershipScreen(){
  const [plans,setPlans]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[message,setMessage]=useState('Loading membership…');
  useEffect(()=>{Promise.all([listMobilePricingCatalog(),getMobileAccountSummary()]).then(([catalog,account])=>{setPlans(catalog);setSummary(account);setMessage('')}).catch((error:any)=>setMessage(error?.message||'Membership could not be loaded.'))},[]);
  const profile=summary?.profile||{};
  const tier=String(profile.subscription_tier||'free').replaceAll('_',' ');
  const consumerPlans=useMemo(()=>plans.filter(plan=>plan.category==='consumer'&&['free','premium_user','family'].includes(String(plan.code))),[plans]);
  return <SafeAreaView style={s.safe}><FlatList data={consumerPlans} keyExtractor={item=>String(item.code)} contentContainerStyle={s.list} ListHeaderComponent={<>
    <View style={s.hero}><Text style={s.heroEyebrow}>KLEENEST MEMBERSHIP</Text><Text style={s.heroTitle}>Every consumer gets the complete Kleenest experience.</Text><Text style={s.heroBody}>Free and Premium use the same Consumer capabilities. Premium is a one-time purchase whose consumer value is removing advertising—not unlocking hidden bathroom features.</Text><TrustStrip items={['Complete feature parity','One-time Premium','No feature locks']}/><View style={s.current}><Text style={s.currentLabel}>YOUR PLAN</Text><Text style={s.currentTier}>{tier.toUpperCase()}</Text></View></View>
    <View style={s.sectionLead}><Text style={s.sectionKicker}>COMPLETE CONSUMER ACCESS</Text><Text style={s.sectionTitle}>Useful before, during, and after the stop</Text></View>
    <View style={s.valueGrid}><Value title="Find + plan" body="Nearby discovery, trust signals, amenities, saved bathrooms, routes, offline trips and Kleenest AI."/><Value title="Verify + contribute" body="Check in, QR, reviews, photos, amenity observations, trust missions and evidence."/><Value title="Connect + progress" body="Community, direct messages, access tools, points, badges, quests, contests, games and leaderboards."/></View>
    <View style={s.billingNote}><Text style={s.billingTitle}>Native purchase boundary</Text><Text style={s.body}>Digital consumer purchases must use the App Store / Google Play billing boundary. Kleenest does not send mobile users through web Stripe checkout. Until native store fulfillment is active, the app will not fake an entitlement change.</Text></View>
    {message?<Text style={s.message}>{message}</Text>:null}
    <View style={s.sectionLead}><Text style={s.sectionKicker}>PLANS</Text><Text style={s.sectionTitle}>Choose how you support the network</Text></View>
  </>} renderItem={({item})=>{const active=String(item.code).toLowerCase().includes(String(profile.subscription_tier||'').toLowerCase())||(String(profile.subscription_tier||'free')==='free'&&Number(item.price_cents||0)===0);const benefits=benefitCopy(String(item.code));return <View style={[s.card,active&&s.activeCard]}><View style={s.planTop}><View style={{flex:1}}><Text style={s.planName}>{item.name}</Text><Text style={s.price}>{formatPrice(item)}</Text></View>{active?<Text style={s.activeBadge}>CURRENT</Text>:null}</View>{benefits.map(benefit=><Text key={benefit} style={s.benefit}>✓ {benefit}</Text>)}{item.code==='premium_user'?<Text style={s.planNote}>Same Consumer capabilities as Free; permanent ad-free entitlement after verified native purchase.</Text>:item.code==='family'?<Text style={s.planNote}>Family access for up to 5 users; Consumer capability parity remains unchanged.</Text>:<Text style={s.planNote}>Free includes the full Consumer capability set.</Text>}</View>}} ListFooterComponent={<View style={s.footer}><Text style={s.footerTitle}>Keep using every Consumer feature now</Text><Text style={s.body}>Membership never blocks the consumer mission: find a bathroom, use trusted evidence, contribute, connect, plan, play and strengthen the network.</Text><View style={s.actions}><Pressable style={s.primary} onPress={()=>router.push('/explore')}><Text style={s.primaryText}>Find a bathroom</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/assistant')}><Text style={s.secondaryText}>Open Kleenest AI</Text></Pressable></View></View>}/></SafeAreaView>
}
function Value({title,body}:{title:string;body:string}){return <View style={s.value}><Text style={s.valueTitle}>{title}</Text><Text style={s.valueBody}>{body}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},list:{padding:20,paddingBottom:44,gap:12},hero:{backgroundColor:palette.green,padding:20,borderRadius:26,gap:8,shadowColor:'#000',shadowOpacity:.08,shadowRadius:14,elevation:3},heroEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.8,color:'#bad0c2'},heroTitle:{fontSize:31,lineHeight:35,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},current:{marginTop:8,backgroundColor:'rgba(255,255,255,.12)',borderRadius:16,padding:12},currentLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#c5d8cc'},currentTier:{fontSize:18,fontWeight:'900',color:'#fff',marginTop:3},sectionLead:{gap:3,marginTop:8},sectionKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:palette.muted},sectionTitle:{fontSize:23,fontWeight:'900',color:palette.ink},valueGrid:{gap:8},value:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:1,borderColor:'#dce6df'},valueTitle:{fontSize:16,fontWeight:'900',color:palette.ink},valueBody:{fontSize:13,lineHeight:19,color:palette.muted,marginTop:3},billingNote:{backgroundColor:'#edf4ef',padding:15,borderRadius:18,borderWidth:1,borderColor:'#d3e2d8',gap:4},billingTitle:{fontWeight:'900',color:palette.green},body:{fontSize:14,lineHeight:21,color:palette.muted},message:{color:palette.muted,fontWeight:'700'},card:{backgroundColor:'#fff',padding:18,borderRadius:21,borderWidth:1,borderColor:'#dce6df',gap:7},activeCard:{borderColor:palette.green,borderWidth:2},planTop:{flexDirection:'row',alignItems:'flex-start',gap:10},planName:{fontSize:20,fontWeight:'900',color:palette.ink},price:{fontSize:24,fontWeight:'900',color:palette.green,marginTop:3},activeBadge:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#fff',backgroundColor:palette.green,paddingHorizontal:9,paddingVertical:6,borderRadius:999,overflow:'hidden'},benefit:{fontSize:13,fontWeight:'800',color:'#40584a'},planNote:{fontSize:12,lineHeight:18,color:palette.muted,marginTop:2},footer:{backgroundColor:'#fff',padding:18,borderRadius:22,borderWidth:1,borderColor:'#dce6df',gap:6,marginTop:4},footerTitle:{fontSize:19,fontWeight:'900',color:palette.ink},actions:{flexDirection:'row',gap:8,flexWrap:'wrap',marginTop:6},primary:{backgroundColor:palette.green,paddingHorizontal:14,paddingVertical:12,borderRadius:13},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#edf3ef',paddingHorizontal:14,paddingVertical:12,borderRadius:13},secondaryText:{color:palette.green,fontWeight:'900'}});