import { searchMobilePeople } from '@kleenest/mobile-core';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { TrustStrip,palette } from '../components/ConsumerUI';
import { hydrateMessagePeople,listDirectMessages,markDirectMessageRead,sendDirectMessage } from '../services/messages';

type Row=Record<string,any>;
export default function MessagesScreen(){const[messages,setMessages]=useState<Row[]>([]),[people,setPeople]=useState<Record<string,Row>>({}),[query,setQuery]=useState(''),[results,setResults]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading messages…');
async function load(){try{const rows=await listDirectMessages(100);setMessages(rows);const current=String(rows[0]?.current_user_id||'');const ids=rows.flatMap(r=>[String(r.from_id||''),String(r.to_id||'')]).filter(id=>id&&id!==current);const profiles=await hydrateMessagePeople(ids);setPeople(Object.fromEntries(profiles.map((p:any)=>[String(p.id),p])));setMessage('')}catch(e:any){setMessage(e?.message||'Messages could not be loaded.')}}useEffect(()=>{void load()},[]);async function search(){try{const rows=await searchMobilePeople(query);setResults(rows);if(!rows.length)setMessage('No contributors found.')}catch(e:any){setMessage(e?.message||'People search failed.')}}async function send(){if(!selected||busy||!draft.trim())return;setBusy(true);try{await sendDirectMessage(String(selected.id||selected.user_id),draft);setDraft('');await load()}catch(e:any){setMessage(e?.message||'Message could not be sent.')}finally{setBusy(false)}}const threads=useMemo(()=>{const by=new Map<string,Row[]>();for(const row of messages){const current=String(row.current_user_id||'');const other=String(row.from_id||'')===current?String(row.to_id):String(row.from_id);if(!other)continue;const list=by.get(other)||[];list.push(row);by.set(other,list)}return[...by.entries()].map(([id,rows])=>({id,rows,person:people[id]}))},[messages,people]);
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.hero}><Text style={s.eyebrow}>COMMUNITY MESSAGES</Text><Text style={s.heroTitle}>Keep useful restroom conversations in the trust network.</Text><Text style={s.heroBody}>Direct messages use the canonical participant-scoped message table and notification pipeline. Only sender and recipient can read a conversation.</Text><TrustStrip items={['Participant-only access','Canonical notification trigger','No public message feed']}/></View>{message?<Text style={s.message}>{message}</Text>:null}
<View style={s.card}><Text style={s.cardTitle}>Start a conversation</Text><View style={s.row}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Search contributor" style={s.input}/><Pressable style={s.smallButton} onPress={search}><Text style={s.smallButtonText}>Search</Text></Pressable></View>{results.slice(0,8).map(p=><Pressable key={String(p.id||p.user_id)} onPress={()=>{setSelected(p);setResults([]);setQuery('')}} style={s.person}><View style={{flex:1}}><Text style={s.personName}>{p.display_name||p.username||'Kleenest contributor'}</Text>{p.username?<Text style={s.meta}>@{p.username}</Text>:null}</View><Text style={s.select}>MESSAGE</Text></Pressable>)}{selected?<><Text style={s.composeLabel}>To {selected.display_name||selected.username||'contributor'}</Text><TextInput multiline value={draft} onChangeText={setDraft} placeholder="Write a helpful message" style={[s.input,{minHeight:92,textAlignVertical:'top'}]}/><Pressable disabled={busy||!draft.trim()} onPress={send} style={[s.primary,(busy||!draft.trim())&&{opacity:.5}]}><Text style={s.primaryText}>{busy?'Sending…':'Send message'}</Text></Pressable></>:null}</View>
<View style={s.section}><Text style={s.sectionTitle}>Recent messages</Text>{threads.length?threads.map(t=><View key={t.id} style={s.card}><Pressable onPress={()=>setSelected(t.person||{id:t.id})}><Text style={s.personName}>{t.person?.display_name||t.person?.username||'Contributor'}</Text></Pressable>{t.rows.slice(0,6).map(r=>{const received=String(r.to_id||'')===String(r.current_user_id||'');return <Pressable key={String(r.id)} onPress={()=>{if(received&&!r.read_at)void markDirectMessageRead(String(r.id)).then(load)}} style={s.messageRow}><Text style={s.body}>{r.content}</Text><Text style={s.meta}>{new Date(r.created_at).toLocaleString()} · {received?'received':'sent'}{received?` · ${r.read_at?'read':'unread'}`:''}</Text></Pressable>})}</View>):<Text style={s.body}>No direct messages yet.</Text>}</View>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:44,gap:13},hero:{backgroundColor:palette.green,padding:20,borderRadius:26,gap:8},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#bad0c2'},heroTitle:{fontSize:28,lineHeight:32,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},message:{fontSize:12,fontWeight:'700',color:'#6b756f'},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6df',borderRadius:18,padding:15,gap:8},cardTitle:{fontSize:19,fontWeight:'900',color:palette.ink},row:{flexDirection:'row',gap:8},input:{flex:1,borderWidth:1,borderColor:'#ccd9d1',borderRadius:13,padding:12,backgroundColor:'#fbfdfc'},smallButton:{backgroundColor:'#edf3ef',paddingHorizontal:12,borderRadius:12,justifyContent:'center'},smallButtonText:{fontWeight:'900',color:palette.green},person:{flexDirection:'row',alignItems:'center',gap:8,padding:11,borderRadius:12,backgroundColor:'#f5f8f6'},personName:{fontSize:15,fontWeight:'900',color:palette.ink},meta:{fontSize:10,lineHeight:15,color:palette.muted},select:{fontSize:8,fontWeight:'900',color:palette.green},composeLabel:{fontSize:11,fontWeight:'900',color:palette.green},primary:{alignSelf:'flex-start',backgroundColor:palette.green,paddingHorizontal:14,paddingVertical:11,borderRadius:12},primaryText:{color:'#fff',fontWeight:'900'},section:{gap:9},sectionTitle:{fontSize:23,fontWeight:'900',color:palette.ink},messageRow:{paddingVertical:7,borderTopWidth:1,borderTopColor:'#edf1ee'},body:{fontSize:13,lineHeight:20,color:palette.muted}});
