import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { markAllNotificationsRead, markNotificationRead, listNotificationInbox } from '../services/notificationInbox';
import { notificationContext, notificationDestination } from '../services/notificationRouting';
import { getNotificationPreferenceStatus, updateNotificationPreferences, type NotificationPreferences, type NotificationSuppressionCounts } from '../services/notificationPreferences';
import { registerNativePush } from '../services/push';

const filters=['All','Unread','Restroom','Community','Support','Route','Progress','Intelligence'] as const;
type Filter=(typeof filters)[number];
const preferenceRows:[keyof NotificationPreferences,string,string][]=[
  ['push','Native push','Allow this device to receive Kleenest push alerts.'],
  ['community','Community','Followers, reviews, helpful votes, and business replies.'],
  ['rewards','Rewards & progress','Badges, quests, contests, and progression updates.'],
  ['intelligence','Kleenest intelligence','Restroom-network reports and product intelligence updates.'],
];
const emptySuppressions:NotificationSuppressionCounts={community:0,rewards:0,intelligence:0,total:0};
export default function NotificationsScreen(){
  const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState('Loading notifications…'),[filter,setFilter]=useState<Filter>('All'),[prefs,setPrefs]=useState<NotificationPreferences|null>(null),[suppressed,setSuppressed]=useState<NotificationSuppressionCounts>(emptySuppressions),[prefsBusy,setPrefsBusy]=useState(false);
  async function load(){try{const[data,status]=await Promise.all([listNotificationInbox(),getNotificationPreferenceStatus()]);setRows(data);setPrefs(status.preferences);setSuppressed(status.suppressed30d);setMessage(data.length?'':'No notifications yet.')}catch(error:any){setMessage(error?.message||'Notifications could not be loaded.')}}
  useEffect(()=>{load()},[]);
  const unreadCount=useMemo(()=>rows.filter(item=>!item.read_at).length,[rows]);
  const visibleRows=useMemo(()=>rows.filter(item=>filter==='All'||(filter==='Unread'?!item.read_at:notificationContext(item)===filter)),[rows,filter]);
  async function open(item:any){try{if(!item.read_at){await markNotificationRead(String(item.id));setRows(current=>current.map(row=>String(row.id)===String(item.id)?{...row,read_at:new Date().toISOString()}:row));}const destination=notificationDestination(item);if(destination)router.push(destination as any);else await load()}catch(error:any){setMessage(error?.message||'Notification could not be opened.')}}
  async function readAll(){try{await markAllNotificationsRead();await load()}catch(error:any){setMessage(error?.message||'Notifications could not be updated.')}}
  async function enablePush(){try{setMessage('Registering this device…');await registerNativePush();const next=await updateNotificationPreferences({push:true});setPrefs(next);setMessage('Push notifications are enabled for this device.')}catch(error:any){setMessage(error?.message||'Push notifications could not be enabled.')}}
  async function setPreference(key:keyof NotificationPreferences,value:boolean){if(prefsBusy)return;setPrefsBusy(true);try{if(key==='push'&&value)await registerNativePush();const next=await updateNotificationPreferences({[key]:value});setPrefs(next);const status=await getNotificationPreferenceStatus();setSuppressed(status.suppressed30d);setMessage(key==='push'&&!value?'Native push delivery is paused.':'Notification preferences updated.')}catch(error:any){setMessage(error?.message||'Notification preferences could not be updated.')}finally{setPrefsBusy(false)}}
  return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.eyebrow}>NOTIFICATIONS</Text><View style={s.titleRow}><Text style={s.title}>Updates</Text><View style={s.unreadPill}><Text style={s.unreadPillText}>{unreadCount} unread</Text></View></View><Text style={s.body}>Tap an update to return to the support request, restroom, contributor, route, or progression context behind it.</Text><View style={s.actions}><Pressable style={s.primary} onPress={enablePush}><Text style={s.primaryText}>Enable push</Text></Pressable><Pressable style={s.secondary} onPress={readAll}><Text style={s.secondaryText}>Mark all read</Text></Pressable></View><View style={s.preferenceCard}><Text style={s.preferenceTitle}>Notification controls</Text><Text style={s.body}>Choose which Kleenest updates reach you. Turning native push off stops delivery before the push worker is invoked.</Text>{suppressed.total>0?<Text style={s.suppressionNote}>{suppressed.total} optional update{suppressed.total===1?'':'s'} filtered by your settings in the last 30 days · Community {suppressed.community} · Progress {suppressed.rewards} · Intelligence {suppressed.intelligence}</Text>:null}{prefs?preferenceRows.map(([key,label,detail])=><View key={key} style={s.preferenceRow}><View style={s.preferenceCopy}><Text style={s.preferenceLabel}>{label}</Text><Text style={s.preferenceDetail}>{detail}</Text></View><Switch value={prefs[key]} disabled={prefsBusy} onValueChange={value=>setPreference(key,value)}/></View>):<Text style={s.message}>Loading preferences…</Text>}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(value=><Pressable key={value} onPress={()=>setFilter(value)} style={[s.filter,filter===value&&s.filterActive]}><Text style={[s.filterText,filter===value&&s.filterTextActive]}>{value}</Text></Pressable>)}</ScrollView>{message?<Text style={s.message}>{message}</Text>:null}{rows.length&&visibleRows.length===0?<Text style={s.message}>No {filter.toLowerCase()} notifications in your recent updates.</Text>:null}</View><FlatList data={visibleRows} keyExtractor={item=>String(item.id)} contentContainerStyle={s.list} renderItem={({item})=>{const destination=notificationDestination(item),context=notificationContext(item);return <Pressable style={[s.card,!item.read_at&&s.unread]} onPress={()=>open(item)}><View style={s.contextRow}><Text style={s.context}>{context}</Text>{!item.read_at?<Text style={s.newLabel}>NEW</Text>:null}</View><View style={s.cardTop}><Text style={s.cardTitle}>{item.title||'Kleenest update'}</Text>{destination?<Text style={s.openLabel}>Open →</Text>:null}</View>{item.body?<Text style={s.body}>{item.body}</Text>:null}<Text style={s.meta}>{new Date(item.created_at).toLocaleString()}{item.read_at?' · Read':' · Unread'}</Text></Pressable>}}/></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},header:{padding:22,gap:8},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},title:{fontSize:32,fontWeight:'800',color:'#14231b'},unreadPill:{backgroundColor:'#e8f3ec',paddingHorizontal:10,paddingVertical:6,borderRadius:999},unreadPillText:{fontSize:12,fontWeight:'900',color:'#173d2b'},body:{color:'#53645a',lineHeight:21},message:{color:'#53645a'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},preferenceCard:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6df',borderRadius:18,padding:14,gap:10},preferenceTitle:{fontSize:17,fontWeight:'900',color:'#14231b'},suppressionNote:{fontSize:12,lineHeight:18,fontWeight:'700',color:'#40584a',backgroundColor:'#f1f7f3',padding:10,borderRadius:12},preferenceRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,paddingTop:8,borderTopWidth:1,borderTopColor:'#edf2ee'},preferenceCopy:{flex:1},preferenceLabel:{fontWeight:'900',color:'#14231b'},preferenceDetail:{fontSize:12,lineHeight:17,color:'#65756b',marginTop:2},filters:{gap:8,paddingVertical:4},filter:{borderWidth:1,borderColor:'#d6e2da',paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#fff'},filterActive:{backgroundColor:'#173d2b',borderColor:'#173d2b'},filterText:{fontSize:12,fontWeight:'800',color:'#4d6658'},filterTextActive:{color:'#fff'},list:{padding:20,paddingTop:0,gap:12},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0',gap:7},unread:{borderColor:'#173d2b',borderWidth:2},contextRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},context:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#4d6658',textTransform:'uppercase'},newLabel:{fontSize:10,fontWeight:'900',color:'#173d2b',backgroundColor:'#e8f3ec',paddingHorizontal:8,paddingVertical:4,borderRadius:999,overflow:'hidden'},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},cardTitle:{fontSize:18,fontWeight:'800',color:'#14231b',flex:1},openLabel:{color:'#173d2b',fontWeight:'900'},meta:{color:'#65756b',marginTop:2,fontSize:12},primary:{backgroundColor:'#173d2b',padding:12,borderRadius:12},primaryText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#edf3ef',padding:12,borderRadius:12},secondaryText:{color:'#173d2b',fontWeight:'800'}});
