import { listMobileNotifications, markAllMobileNotificationsRead, markMobileNotificationRead } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { notificationDestination } from '../services/notificationRouting';
import { registerNativePush } from '../services/push';

export default function NotificationsScreen(){
  const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState('Loading notifications…');
  async function load(){try{const data=await listMobileNotifications();setRows(data);setMessage(data.length?'':'No notifications yet.')}catch(error:any){setMessage(error?.message||'Notifications could not be loaded.')}}
  useEffect(()=>{load()},[]);
  async function open(item:any){try{if(!item.read_at)await markMobileNotificationRead(String(item.id));const destination=notificationDestination(item);if(destination)router.push(destination as any);else await load()}catch(error:any){setMessage(error?.message||'Notification could not be opened.')}}
  async function readAll(){try{await markAllMobileNotificationsRead();await load()}catch(error:any){setMessage(error?.message||'Notifications could not be updated.')}}
  async function enablePush(){try{setMessage('Registering this device…');await registerNativePush();setMessage('Push notifications are enabled for this device.')}catch(error:any){setMessage(error?.message||'Push notifications could not be enabled.')}}
  return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.eyebrow}>NOTIFICATIONS</Text><Text style={s.title}>Updates</Text><Text style={s.body}>Tap an update to return to the restroom, contributor, route, or progression context behind it.</Text><View style={s.actions}><Pressable style={s.primary} onPress={enablePush}><Text style={s.primaryText}>Enable push</Text></Pressable><Pressable style={s.secondary} onPress={readAll}><Text style={s.secondaryText}>Mark all read</Text></Pressable></View>{message?<Text style={s.message}>{message}</Text>:null}</View><FlatList data={rows} keyExtractor={item=>String(item.id)} contentContainerStyle={s.list} renderItem={({item})=>{const destination=notificationDestination(item);return <Pressable style={[s.card,!item.read_at&&s.unread]} onPress={()=>open(item)}><View style={s.cardTop}><Text style={s.cardTitle}>{item.title||'Kleenest update'}</Text>{destination?<Text style={s.openLabel}>Open →</Text>:null}</View>{item.body?<Text style={s.body}>{item.body}</Text>:null}<Text style={s.meta}>{new Date(item.created_at).toLocaleString()}{item.read_at?' · Read':' · Unread'}</Text></Pressable>}}/></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},header:{padding:22,gap:8},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:32,fontWeight:'800',color:'#14231b'},body:{color:'#53645a',lineHeight:21},message:{color:'#53645a'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},list:{padding:20,paddingTop:0,gap:12},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0'},unread:{borderColor:'#173d2b',borderWidth:2},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},cardTitle:{fontSize:18,fontWeight:'800',color:'#14231b',flex:1},openLabel:{color:'#173d2b',fontWeight:'900'},meta:{color:'#65756b',marginTop:8,fontSize:12},primary:{backgroundColor:'#173d2b',padding:12,borderRadius:12},primaryText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#edf3ef',padding:12,borderRadius:12},secondaryText:{color:'#173d2b',fontWeight:'800'}});
