import { completeMobileChallenge, getMobileProgressionDashboard, getMobileProgressionSummary, joinMobileContest, listMobileBadgeCatalog, listMobileBadges, listMobileChallengeProgress, listMobileChallenges, listMobileContests, listMobileLeaderboard } from '@kleenest/mobile-core';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

export default function PlayScreen(){
  const [dashboard,setDashboard]=useState<any>({}),[summary,setSummary]=useState<any>({}),[badges,setBadges]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[challenges,setChallenges]=useState<any[]>([]),[progress,setProgress]=useState<any[]>([]),[contests,setContests]=useState<any[]>([]),[leaders,setLeaders]=useState<any[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
  async function load(){setLoading(true);setMessage('');try{const [d,s,b,c,ch,p,co,l]=await Promise.all([getMobileProgressionDashboard(),getMobileProgressionSummary(),listMobileBadges(),listMobileBadgeCatalog(),listMobileChallenges(8),listMobileChallengeProgress(),listMobileContests(5),listMobileLeaderboard(10)]);setDashboard(d);setSummary(s);setBadges(b);setCatalog(c);setChallenges(ch);setProgress(p);setContests(co);setLeaders(l)}catch(error:any){setMessage(error?.message||'Progression could not be loaded.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const profile=dashboard?.profile||summary?.profile||summary||{};
  const earned=new Set(badges.map(b=>String(b.id)));
  const nextBadge=useMemo(()=>catalog.find(b=>!earned.has(String(b.id))),[catalog,badges]);
  const metricByName=new Map(progress.map((row:any)=>[String(row.metric),Number(row.quantity||0)]));
  async function complete(id:string){try{await completeMobileChallenge(id);setMessage('Challenge progress updated.');await load()}catch(error:any){setMessage(error?.message||'Challenge could not be completed.')}}
  async function join(id:string){try{await joinMobileContest(id);setMessage('Contest joined.');await load()}catch(error:any){setMessage(error?.message||'Contest could not be joined.')}}
  return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.content}><Text style={s.eyebrow}>PLAY + PROGRESS</Text><Text style={s.title}>Make every useful stop count.</Text><Text style={s.body}>Check-ins, reviews, community contributions and exploration build your Kleenest progression.</Text>
  <View style={s.stats}><Stat label="Points" value={profile.points??summary.points??0}/><Stat label="Level" value={profile.level??summary.level??1}/><Stat label="Streak" value={`${profile.streak??summary.streak??0}d`}/></View>
  {message?<Text style={s.message}>{message}</Text>:null}
  <Section title="Next achievement">{nextBadge?<View style={s.card}><Text style={s.icon}>{nextBadge.icon||'🏅'}</Text><Text style={s.cardTitle}>{nextBadge.name}</Text><Text style={s.body}>{nextBadge.description||'Keep contributing to unlock this badge.'}</Text><Text style={s.meta}>{badges.length}/{catalog.length} badges earned</Text></View>:<Text style={s.body}>{catalog.length?'You earned every current badge.':'Badge catalog is loading.'}</Text>}</Section>
  <Section title="Challenges">{challenges.length?challenges.map(ch=>{const metric=String(ch.metrics_config?.metric||ch.challenge_type||'');const current=metricByName.get(metric)||0;return <View style={s.card} key={ch.id}><Text style={s.cardTitle}>{ch.name}</Text><Text style={s.body}>{ch.description||'Complete the target to earn progression.'}</Text><Text style={s.meta}>{current}/{ch.target||1} · +{ch.reward_points||0} points</Text><Pressable style={s.secondary} onPress={()=>complete(String(ch.id))}><Text style={s.secondaryText}>Check completion</Text></Pressable></View>}):<Text style={s.body}>No active challenges right now.</Text>}</Section>
  <Section title="Contests">{contests.length?contests.map(co=><View style={s.card} key={co.id}><Text style={s.cardTitle}>{co.name||co.title||'Kleenest contest'}</Text><Text style={s.body}>{co.description||'Compete with the community.'}</Text><Pressable style={s.secondary} onPress={()=>join(String(co.id))}><Text style={s.secondaryText}>Join contest</Text></Pressable></View>):<Text style={s.body}>No active contests right now.</Text>}</Section>
  <Section title="Community leaderboard">{leaders.length?leaders.map((row:any,index)=><View style={s.rank} key={row.user_id||row.id||index}><Text style={s.rankNumber}>{index+1}</Text><View style={{flex:1}}><Text style={s.cardTitle}>{row.display_name||row.username||'Kleenest contributor'}</Text><Text style={s.meta}>{row.points??row.score??0} points · Level {row.level??1}</Text></View></View>):<Text style={s.body}>Leaderboard is warming up.</Text>}</Section>
  </ScrollView></SafeAreaView>;
}
function Section({title,children}:{title:string;children:any}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Stat({label,value}:{label:string;value:any}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},content:{padding:22,paddingBottom:40,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},message:{padding:12,borderRadius:12,backgroundColor:'#e8f0eb',color:'#173d2b',fontWeight:'700'},stats:{flexDirection:'row',gap:10,marginTop:8},stat:{flex:1,backgroundColor:'#173d2b',padding:14,borderRadius:18},statValue:{fontSize:22,fontWeight:'900',color:'#fff'},section:{gap:10,marginTop:16},sectionTitle:{fontSize:22,fontWeight:'900',color:'#14231b'},card:{backgroundColor:'#fff',padding:16,borderRadius:18,borderWidth:1,borderColor:'#dde7e0',gap:6},cardTitle:{fontSize:16,fontWeight:'800',color:'#14231b'},icon:{fontSize:30},meta:{fontSize:12,color:'#708077',fontWeight:'700'},secondary:{alignSelf:'flex-start',marginTop:6,backgroundColor:'#edf3ef',paddingHorizontal:14,paddingVertical:10,borderRadius:12},secondaryText:{color:'#173d2b',fontWeight:'800'},rank:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#fff',padding:14,borderRadius:16},rankNumber:{fontSize:20,fontWeight:'900',color:'#173d2b'}});
