import { getKleenestSupabaseClient, isKleenestRewardThemeMode, KLEENEST_THEME_OPTIONS, loadKleenestThemeMode, resolveKleenestTheme, setKleenestThemeMode, subscribeKleenestTheme, type KleenestThemeMode } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, useColorScheme, View } from 'react-native';
import { FeatureCard, HeroCard, SectionHeader, palette } from '../components/ConsumerUI';
import { getProgressionRewards } from '../services/discoveryProgression';

type Prefs={profile_visibility:'public'|'followers'|'private';show_activity:boolean;show_checkins:boolean;show_reviews:boolean;allow_followers:boolean;discoverable:boolean;preferred_units:'imperial'|'metric';home_region:string};
const defaults:Prefs={profile_visibility:'public',show_activity:true,show_checkins:true,show_reviews:true,allow_followers:true,discoverable:true,preferred_units:'imperial',home_region:''};
const toggles:[keyof Prefs,string,string][]=[
 ['show_activity','Show activity','Let permitted followers see your community activity.'],
 ['show_checkins','Show check-ins','Allow your verified visit history to appear where permitted.'],
 ['show_reviews','Show reviews','Associate your published reviews with your contributor profile.'],
 ['allow_followers','Allow followers','Let other people follow your profile and published contributions.'],
 ['discoverable','Discoverable','Allow your profile to appear in community search and discovery.'],
];
const rewardPreview:Partial<Record<KleenestThemeMode,{background:string;border:string;ink:string;muted:string;badge:string}>>={
 founders:{background:'#101a17',border:'#66e3c4',ink:'#fbfdfc',muted:'#bccbc5',badge:'◆ FOUNDERS EDITION'},
 'clean-slate':{background:'#ffffff',border:'#247466',ink:'#10211d',muted:'#52645f',badge:'✧ CLEAN SLATE'},
 'midnight-transit':{background:'#101b2d',border:'#72b8ff',ink:'#f5f8ff',muted:'#b4c3d8',badge:'◈ MIDNIGHT TRANSIT'},
 'neon-city':{background:'#11151d',border:'#44f1dd',ink:'#f9fbff',muted:'#bbc4d1',badge:'✦ NEON CITY'},
 trailblazer:{background:'#fffaf0',border:'#4d7044',ink:'#263326',muted:'#5e6650',badge:'🧭 TRAILBLAZER'},
 'verified-gold':{background:'#171714',border:'#e7c45d',ink:'#fffdf7',muted:'#c8c2ad',badge:'✪ VERIFIED GOLD'},
 'civic-atlas':{background:'#fffdf8',border:'#315f78',ink:'#172d39',muted:'#536875',badge:'🗺 CIVIC ATLAS'},
 'road-warrior':{background:'#1d2022',border:'#f39a43',ink:'#f8faf9',muted:'#bec5c2',badge:'🛣 ROAD WARRIOR'},
 'community-builder':{background:'#fffaf6',border:'#2d7b78',ink:'#382623',muted:'#755d57',badge:'◉ COMMUNITY BUILDER'},
 'data-guardian':{background:'#0e1f1b',border:'#51e3b8',ink:'#ecfff9',muted:'#afd0c5',badge:'⌁ DATA GUARDIAN'},
 'spring-renewal':{background:'#fffefd',border:'#4f8b66',ink:'#203222',muted:'#617364',badge:'🌱 SPRING RENEWAL'},
 'summer-roadtrip':{background:'#fffdf7',border:'#e57b37',ink:'#20313a',muted:'#5d7079',badge:'☀️ SUMMER ROADTRIP'},
 'stl-edition':{background:'#152335',border:'#f4c45f',ink:'#f8fbff',muted:'#b9c8d9',badge:'⚜ ST. LOUIS EDITION'},
 'chicago-edition':{background:'#122338',border:'#71b7ed',ink:'#f5f9ff',muted:'#b6c7da',badge:'✶ CHICAGO EDITION'},
 fall:{background:'#fff5e8',border:'#b85d24',ink:'#5a2c16',muted:'#755642',badge:'🍁 AUTUMN TRAIL'},
 halloween:{background:'#17101e',border:'#ff8a2b',ink:'#fff7ed',muted:'#c9b8cf',badge:'🎃 NIGHT WATCH'},
 thanksgiving:{background:'#fff5e8',border:'#9b3f36',ink:'#5b2922',muted:'#77594d',badge:'🌾 HARVEST TABLE'},
 christmas:{background:'#0e211a',border:'#f0c75e',ink:'#f7fbf9',muted:'#b6c9c0',badge:'❄️ WINTER GUARDIAN'},
};
const hitSlop={top:8,right:8,bottom:8,left:8};

export default function PreferencesScreen(){
 const client=getKleenestSupabaseClient();
 const systemScheme=useColorScheme();
 const[themeMode,setThemeModeState]=useState<KleenestThemeMode>('default');
 const theme=resolveKleenestTheme(themeMode,systemScheme==='dark','consumer');
 const[prefs,setPrefs]=useState<Prefs>(defaults),[themeRewards,setThemeRewards]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setLoading(true);setMessage('');try{const[{data,error},rewards]=await Promise.all([client.rpc('get_my_profile_preferences'),getProgressionRewards().catch(()=>[])]);if(error)throw error;if(data)setPrefs({...defaults,...data,profile_visibility:data.profile_visibility==='community'?'public':data.profile_visibility||'public',home_region:data.home_region||''});setThemeRewards(Array.isArray(rewards)?rewards:[])}catch(error:any){setMessage(error?.message||'Preferences could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{let active=true;void loadKleenestThemeMode().then(mode=>{if(active)setThemeModeState(mode)});const unsubscribe=subscribeKleenestTheme(mode=>{if(active)setThemeModeState(mode)});return()=>{active=false;unsubscribe()}},[]);
 const allowedRewardThemes=new Set(themeRewards.filter((reward:any)=>reward?.reward_kind==='theme'&&reward?.unlocked).map((reward:any)=>String(reward.reward_key)));
 const visibleThemeOptions=KLEENEST_THEME_OPTIONS;
 async function chooseTheme(mode:KleenestThemeMode){if(isKleenestRewardThemeMode(mode)&&!allowedRewardThemes.has(mode)){setMessage('This progression reward theme is still locked.');return}setThemeModeState(mode);await setKleenestThemeMode(mode)}
 function patch<K extends keyof Prefs>(key:K,value:Prefs[K]){setPrefs(current=>({...current,[key]:value}))}
 async function save(){if(busy)return;setBusy(true);setMessage('');try{const payload={...prefs,home_region:prefs.home_region.trim()||null};const{data,error}=await client.rpc('update_my_profile_preferences',{p_preferences:payload});if(error)throw error;if(data)setPrefs({...defaults,...data,profile_visibility:data.profile_visibility==='community'?'public':data.profile_visibility||'public',home_region:data.home_region||''});setMessage('Privacy and experience preferences saved.')}catch(error:any){setMessage(error?.message||'Preferences could not be saved.')}finally{setBusy(false)}}
 return <SafeAreaView style={[s.safe,{backgroundColor:theme.canvas}]}><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <HeroCard eyebrow="PROFILE CONTROL" title="Privacy & preferences" body="Choose how your contributor identity, activity, visits, reviews and discovery presence work across Kleenest."/>
   {message?<View accessibilityRole="alert" style={[s.notice,{backgroundColor:theme.surfaceRaised,borderColor:theme.line}]}><Text style={[s.noticeText,{color:theme.ink}]}>{message}</Text></View>:null}
   <SectionHeader eyebrow="VISIBILITY" title="Who can see you?" body="These controls affect the community layer; your private account details stay private."/>
   <View accessibilityRole="radiogroup" style={s.segment}>{(['public','followers','private'] as const).map(value=>{const selected=prefs.profile_visibility===value;const label=value==='public'?'Community':value==='followers'?'Followers':'Private';return <Pressable key={value} accessibilityRole="radio" accessibilityLabel={`${label} profile visibility`} accessibilityState={{selected,disabled:loading}} hitSlop={hitSlop} disabled={loading} onPress={()=>patch('profile_visibility',value)} style={[s.segmentItem,{backgroundColor:selected?theme.accent:theme.surfaceRaised,borderColor:selected?theme.accent:theme.line},selected&&s.segmentOn]}><Text style={[s.segmentText,{color:selected?theme.accentText:theme.ink},selected&&s.segmentTextOn]}>{label}</Text></Pressable>})}</View>
   <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}>{toggles.map(([key,title,body])=><View style={[s.toggleRow,{borderBottomColor:theme.line}]} key={String(key)}><View style={{flex:1}}><Text style={[s.toggleTitle,{color:theme.ink}]}>{title}</Text><Text style={[s.toggleBody,{color:theme.muted}]}>{body}</Text></View><Switch accessibilityLabel={title} accessibilityHint={body} value={Boolean(prefs[key])} disabled={loading} onValueChange={value=>patch(key,value as never)} trackColor={{false:'#cfd8d2',true:'#8fb9a0'}} thumbColor={prefs[key]?'#173d2b':'#ffffff'}/></View>)}</View>
   <SectionHeader eyebrow="APPEARANCE" title="Choose your Kleenest theme" body="Default, Light, Dark and System stay available. Early Access marks the beta. Reward themes stay visible as part of your progression collection: earn the gate, keep the theme. Platform owners can use every edition, and Owner grants can unlock any reward theme early."/>
   <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}>
    <View accessibilityRole="radiogroup" style={s.themeGrid}>{visibleThemeOptions.map(option=>{const selected=themeMode===option.value;const earlyAccess=option.value==='early-access';const rewardTheme=isKleenestRewardThemeMode(option.value);const preview=rewardPreview[option.value];const reward=rewardTheme?themeRewards.find((item:any)=>item?.reward_key===option.value):null;const unlocked=!rewardTheme||Boolean(reward?.unlocked);const req=reward?.requirements||{};const source=String(reward?.unlock_source||'');return <Pressable key={option.value} accessibilityRole="radio" accessibilityLabel={earlyAccess?'Early Access beta theme':rewardTheme?option.label+' progression reward theme':option.label} accessibilityHint={rewardTheme&&!unlocked?`Earn it at Level ${Number(req.level||1)}, Trust ${Number(req.trust_score||0)}, ${Number(req.lifetime_xp||0).toLocaleString()} XP and ${Number(req.badges||0)} badges.`:undefined} accessibilityState={{selected,disabled:rewardTheme&&!unlocked}} disabled={rewardTheme&&!unlocked} onPress={()=>void chooseTheme(option.value)} style={[s.themeChoice,(earlyAccess||rewardTheme)&&s.specialThemeChoice,{backgroundColor:preview?.background||(earlyAccess?'#0f172a':selected?theme.accent:theme.surfaceRaised),borderColor:preview?.border||(earlyAccess?'#5de2c2':selected?theme.accent:theme.line),opacity:rewardTheme&&!unlocked ? .72 : 1}]}><View style={s.themeTitleRow}><Text style={[s.themeTitle,{color:preview?.ink||(earlyAccess?'#f7faff':selected?theme.accentText:theme.ink)}]}>{option.label}</Text>{earlyAccess?<Text style={s.betaPill}>BETA · EARLY ACCESS</Text>:rewardTheme?<Text style={[s.seasonPill,{borderColor:preview?.border,color:preview?.ink}]}>{preview?.badge||'SEASONAL REWARD'}</Text>:null}</View><Text style={[s.themeBody,{color:preview?.muted||(earlyAccess?'#aab8d1':selected?theme.accentText:theme.muted)}]}>{option.description}</Text>{seasonal?(unlocked?<Text style={[s.unlockedText,{color:preview?.border}]}>UNLOCKED · {source==='platform_owner'?'OWNER ACCESS':source==='owner_grant'?'OWNER GRANT':'EARNED REWARD'}</Text>:<Text style={[s.unlockedText,{color:preview?.border}]}>Earn it at Level {Number(req.level||1)} · Trust {Number(req.trust_score||0)} · {Number(req.lifetime_xp||0).toLocaleString()} XP · {Number(req.badges||0)} badges</Text>):null}</Pressable>})}</View>
   </View>
   <SectionHeader eyebrow="EXPERIENCE" title="Make Kleenest feel local"/>
   <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.label,{color:theme.accent}]}>Preferred units</Text><View accessibilityRole="radiogroup" style={s.segment}>{(['imperial','metric'] as const).map(value=>{const selected=prefs.preferred_units===value;const label=value==='imperial'?'Miles / feet':'Kilometers / meters';return <Pressable key={value} accessibilityRole="radio" accessibilityLabel={label} accessibilityState={{selected}} hitSlop={hitSlop} onPress={()=>patch('preferred_units',value)} style={[s.segmentItem,{backgroundColor:selected?theme.accent:theme.surfaceRaised,borderColor:selected?theme.accent:theme.line},selected&&s.segmentOn]}><Text style={[s.segmentText,{color:selected?theme.accentText:theme.ink},selected&&s.segmentTextOn]}>{label}</Text></Pressable>})}</View><Text style={[s.label,{color:theme.accent}]}>Home region</Text><TextInput accessibilityLabel="Home region" accessibilityHint="Optional city or region used to localize your Kleenest experience" returnKeyType="done" value={prefs.home_region} onChangeText={value=>patch('home_region',value)} placeholder="Optional city or region" placeholderTextColor={theme.muted} style={[s.input,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,color:theme.ink}]}/></View>
   <Pressable accessibilityRole="button" accessibilityLabel="Save preferences" accessibilityState={{disabled:busy||loading,busy}} hitSlop={hitSlop} style={[s.save,{backgroundColor:theme.accent},(busy||loading)&&s.disabled]} disabled={busy||loading} onPress={save}><Text style={[s.saveText,{color:theme.accentText}]}>{busy?'Saving…':'Save preferences'}</Text></Pressable>
   <SectionHeader eyebrow="SAFETY + LEGAL" title="Your trust controls" body="Review the policies that govern community participation and manage contributors you have blocked."/>
   <View style={s.stack}><FeatureCard kicker="TERMS + PRIVACY" title="Terms, privacy & community" body="Review current policy versions and accept updated community terms when required." onPress={()=>router.push('/legal')}/><FeatureCard kicker="BLOCKING" title="Blocked contributors" body="Review or unblock people you have blocked from interacting with you." onPress={()=>router.push('/blocked-users')}/></View>
   <SectionHeader eyebrow="CONNECTED CONTROLS" title="Your account, your rules"/>
   <View style={s.stack}><FeatureCard kicker="LIVE NETWORK" title="Nearby restroom alerts" body="Opt in to geofence-aware nearby restroom alerts, background location and region controls." onPress={()=>router.push('/live-network')}/><FeatureCard kicker="NOTIFICATIONS" title="Notification preferences" body="Control push, community, reward and intelligence alerts in the existing notification center." onPress={()=>router.push('/notifications')}/><FeatureCard kicker="SUPPORT" title="Help & support" body="Open a real account-linked support request and review your ticket history." onPress={()=>router.push('/support')}/><FeatureCard kicker="ACCOUNT" title="Protected account control" body="Account deletion stays a deliberate, separate protected flow." onPress={()=>router.push('/account-deletion')}/></View>
   <Pressable accessibilityRole="button" accessibilityLabel="Back to profile" hitSlop={hitSlop} style={[s.back,{backgroundColor:theme.accentSoft}]} onPress={()=>router.back()}><Text style={[s.backText,{color:theme.accent}]}>Back to profile</Text></Pressable>
 </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:44,gap:14},notice:{backgroundColor:'#e8f1eb',borderRadius:14,padding:12},noticeText:{fontSize:12,fontWeight:'800',color:palette.green},card:{backgroundColor:'#fff',borderWidth:1,borderColor:palette.line,borderRadius:20,padding:15,gap:5},toggleRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf1ee'},toggleTitle:{fontSize:15,fontWeight:'900',color:palette.ink},toggleBody:{fontSize:12,lineHeight:17,color:palette.muted,marginTop:3},segment:{flexDirection:'row',gap:7,flexWrap:'wrap'},segmentItem:{flexGrow:1,minWidth:90,minHeight:48,backgroundColor:'#e9efeb',borderRadius:12,paddingHorizontal:12,paddingVertical:10,alignItems:'center',justifyContent:'center'},segmentOn:{backgroundColor:palette.green},segmentText:{fontSize:11,fontWeight:'900',color:palette.green},segmentTextOn:{color:'#fff'},label:{fontSize:11,fontWeight:'900',color:palette.green,marginTop:8},input:{minHeight:48,backgroundColor:'#f9fbfa',borderWidth:1,borderColor:'#ccd9d1',borderRadius:13,padding:12,fontSize:14},save:{minHeight:48,backgroundColor:palette.green,padding:15,borderRadius:14,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.5},themeGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},themeChoice:{width:'48%',minWidth:150,borderWidth:1,borderRadius:14,padding:12,gap:4},earlyAccessChoice:{width:'100%',minHeight:96},specialThemeChoice:{width:'100%',minHeight:96},themeTitleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,flexWrap:'wrap'},themeTitle:{fontSize:13,fontWeight:'900'},betaPill:{fontSize:9,fontWeight:'900',letterSpacing:.8,color:'#06100d',backgroundColor:'#5de2c2',paddingHorizontal:8,paddingVertical:5,borderRadius:999},seasonPill:{fontSize:9,fontWeight:'900',letterSpacing:.5,borderWidth:1,paddingHorizontal:8,paddingVertical:5,borderRadius:999},unlockedText:{fontSize:9,fontWeight:'900',letterSpacing:.7,marginTop:5},themeBody:{fontSize:11,lineHeight:16},stack:{gap:9},back:{minHeight:48,backgroundColor:'#e7efe9',padding:14,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:4},backText:{fontWeight:'900',color:palette.green}});
