import * as Linking from 'expo-linking';
import { getKleenestSupabaseClient, getMobileAccountSummary } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function ProfileScreen(){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[session,setSession]=useState<any>(null),[summary,setSummary]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const client=getKleenestSupabaseClient();
  async function refresh(){const {data,error}=await client.auth.getSession();if(error){setMessage(error.message);return}setSession(data.session);if(data.session){try{setSummary(await getMobileAccountSummary())}catch(error:any){setMessage(error?.message||'Account could not be loaded.')}}else setSummary(null)}
  async function handleAuthUrl(url:string|null){if(!url)return;try{const parsed=Linking.parse(url);const code=typeof parsed.queryParams?.code==='string'?parsed.queryParams.code:'';if(code){const {error}=await client.auth.exchangeCodeForSession(code);if(error)throw error;setMessage('Signed in.');await refresh()}}catch(error:any){setMessage(error?.message||'Sign-in link could not be completed.')}}
  useEffect(()=>{void refresh();void Linking.getInitialURL().then(handleAuthUrl);const auth=client.auth.onAuthStateChange(()=>{void refresh()});const link=Linking.addEventListener('url',event=>{void handleAuthUrl(event.url)});return()=>{auth.data.subscription.unsubscribe();link.remove()}},[]);
  async function signIn(){if(busy)return;setBusy(true);try{const {error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setMessage('Signed in.')}catch(error:any){setMessage(error?.message||'Sign in failed.')}finally{setBusy(false)}}
  async function signUp(){if(busy)return;setBusy(true);try{const {error}=await client.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:Linking.createURL('/profile')}});if(error)throw error;setMessage('Account created. Check your email if confirmation is required.')}catch(error:any){setMessage(error?.message||'Account could not be created.')}finally{setBusy(false)}}
  async function magicLink(){if(busy)return;setBusy(true);try{if(!email.trim())throw new Error('Enter your email first.');const {error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:Linking.createURL('/profile'),shouldCreateUser:true}});if(error)throw error;setMessage('Magic link sent. Open it on this device to sign in.')}catch(error:any){setMessage(error?.message||'Magic link could not be sent.')}finally{setBusy(false)}}
  async function signOut(){await client.auth.signOut();setMessage('Signed out.')}
  const profile=summary?.profile||{};
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.eyebrow}>ACCOUNT</Text><Text style={s.title}>{session?(profile.display_name||session.user.email||'Profile'):'Sign in or create an account'}</Text>{session?<><Text style={s.body}>Membership: <Text style={s.strong}>{profile.subscription_tier||'free'}</Text></Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push('/membership')}><Text style={s.secondaryText}>Membership</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/saved')}><Text style={s.secondaryText}>Saved</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/activity')}><Text style={s.secondaryText}>Activity</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/social')}><Text style={s.secondaryText}>Community</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push('/notifications')}><Text style={s.secondaryText}>Notifications</Text></Pressable></View><Pressable style={s.secondary} onPress={signOut}><Text style={s.secondaryText}>Sign out</Text></Pressable></>:<><Text style={s.body}>Sign in to save bathrooms, check in, review amenities, earn progression, and join the community.</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email"/><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry autoComplete="password" placeholder="Password"/><Pressable style={[s.primary,busy&&s.disabled]} disabled={busy} onPress={signIn}><Text style={s.primaryText}>Sign in</Text></Pressable><Pressable style={[s.secondary,busy&&s.disabled]} disabled={busy} onPress={signUp}><Text style={s.secondaryText}>Create account</Text></Pressable><View style={s.divider}/><Text style={s.body}>Prefer not to use a password?</Text><Pressable style={[s.secondary,busy&&s.disabled]} disabled={busy} onPress={magicLink}><Text style={s.secondaryText}>Email me a magic link</Text></Pressable></>}{message?<Text style={s.message}>{message}</Text>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},container:{padding:22,paddingBottom:42,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,fontWeight:'900',color:'#14231b'},body:{fontSize:16,lineHeight:23,color:'#53645a'},strong:{fontWeight:'800',color:'#14231b'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ccd9d1',borderRadius:14,padding:14},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{backgroundColor:'#173d2b',padding:14,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#edf3ef',padding:14,borderRadius:14,alignItems:'center'},secondaryText:{color:'#173d2b',fontWeight:'800'},message:{color:'#53645a',fontWeight:'700'},disabled:{opacity:.55},divider:{height:1,backgroundColor:'#d9e3dc',marginVertical:4}});
