import * as Location from 'expo-location';
import { router } from 'expo-router';
import { useEffect,useMemo,useState } from 'react';
import { Pressable,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,useColorScheme,View } from 'react-native';
import { getMobileProgressionDashboard,loadKleenestThemeMode,resolveKleenestTheme,subscribeKleenestTheme,type KleenestThemeMode } from '@kleenest/mobile-core';
import { getProgressionOverviewV2,getProgressionRewards,getProgressionWorld,listActiveObjectivesV2,listNearbyProgressionOpportunities,listProgressionRankingsV2 } from '../services/discoveryProgression';
import { clearTrustMission,readTrustMission,type TrustMission } from '../services/trustMissions';
import { palette } from '../components/ConsumerUI';
import { badgeCollectionTier,divisionForXp,divisionProgress,nextDivisionForXp } from '../services/engagementMetaGame';

const KINDS=['quest','mission','challenge','journey','campaign','contest'] as const;
const KIND_LABEL:Record<string,string>={quest:'Quests',mission:'Missions',challenge:'Challenges',journey:'Journeys',campaign:'Campaigns',contest:'Contests'};
const SPECIALTY_LABEL:Record<string,string>={explorer:'Explorer',verifier:'Verifier',accessibility_scout:'Accessibility Scout',restroom_mapper:'Restroom Mapper',photographer:'Photographer',reviewer:'Reviewer',community_contributor:'Community Contributor',pathfinder:'Pathfinder'};
const RANK_SCOPES=['global','following','local','city','state','national','specialty'];
const SEASON_MARKETING={label:'SEASON 01',name:'THE FRESHNESS RUN'};

function safeArray(value:any){return Array.isArray(value)?value:[]}
function percent(progress:number,target:number){return Math.max(0,Math.min(1,target?progress/target:0))}
function objectiveFlavor(kind:string){
 if(kind==='quest')return{icon:'⚡',label:'QUICK QUEST',promise:'Short, surprising objectives that can change what you do right now.',accent:'#8a6414',soft:'#fff8df'};
 if(kind==='mission')return{icon:'🎯',label:'MISSION',promise:'Purposeful assignments tied to real network needs and evidence gaps.',accent:'#1c6240',soft:'#edf7f0'};
 if(kind==='challenge')return{icon:'⏱️',label:'CHALLENGE',promise:'Pressure, constraints and mastery targets—not just another counter.',accent:'#8a3d24',soft:'#fbefe9'};
 if(kind==='journey')return{icon:'🧭',label:'JOURNEY',promise:'Long-form chapter progress with checkpoints, reveals and a finish.',accent:'#315b79',soft:'#edf4f8'};
 if(kind==='campaign')return{icon:'🌐',label:'CAMPAIGN',promise:'The whole Kleenest community moves one shared meter together.',accent:'#5a477c',soft:'#f3eff9'};
 if(kind==='contest')return{icon:'🏆',label:'CONTEST',promise:'Ranked competition with a clock, ladder and explicit prize tiers.',accent:'#765b15',soft:'#faf5e3'};
 return{icon:'◆',label:'OBJECTIVE',promise:'Useful progress.',accent:palette.green,soft:'#eef5f0'};
}
function chapterState(chapters:any[],seasonXp:number){
 const rows=[...chapters].sort((a,b)=>Number(a.unlock_xp||0)-Number(b.unlock_xp||0));
 const current=[...rows].reverse().find(row=>seasonXp>=Number(row.unlock_xp||0))||rows[0]||null;
 const next=rows.find(row=>Number(row.unlock_xp||0)>seasonXp)||null;
 return{rows,current,next};
}

export default function ProgressScreen(){
 const systemScheme=useColorScheme();
 const[themeMode,setThemeMode]=useState<KleenestThemeMode>('default');
 const theme=resolveKleenestTheme(themeMode,systemScheme==='dark','progress');
 const[overview,setOverview]=useState<any>({}),[world,setWorld]=useState<any>({}),[dashboard,setDashboard]=useState<any>({}),[rewards,setRewards]=useState<any[]>([]),[objectives,setObjectives]=useState<any[]>([]),[rankings,setRankings]=useState<any[]>([]),[opportunities,setOpportunities]=useState<any[]>([]),[activeMission,setActiveMission]=useState<TrustMission|null>(null),[rankScope,setRankScope]=useState('global'),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 async function load(scope=rankScope){
  setLoading(true);setMessage('');
  try{
   const[o,w,d,rw,obj,r,tm]=await Promise.all([
    getProgressionOverviewV2(),getProgressionWorld().catch(()=>({})),getMobileProgressionDashboard().catch(()=>({})),getProgressionRewards().catch(()=>[]),
    listActiveObjectivesV2(),listProgressionRankingsV2(scope),readTrustMission().catch(()=>null)
   ]);
   setOverview(o);setWorld(w);setDashboard(d);setRewards(safeArray(rw));setObjectives(obj);setRankings(r);setActiveMission(tm);
   const permission=await Location.getForegroundPermissionsAsync();
   if(permission.status==='granted'){
    const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});
    setOpportunities(await listNearbyProgressionOpportunities(current.coords.latitude,current.coords.longitude,5000).catch(()=>[]));
   }
  }catch(error:any){setMessage(error?.message||'Progression could not be loaded.')}finally{setLoading(false)}
 }
 useEffect(()=>{let active=true;void loadKleenestThemeMode().then(mode=>{if(active)setThemeMode(mode)});const unsubscribe=subscribeKleenestTheme(mode=>{if(active)setThemeMode(mode)});return()=>{active=false;unsubscribe()}},[]);
 useEffect(()=>{void load()},[]);
 async function changeScope(scope:string){setRankScope(scope);await load(scope)}
 async function clearActiveMission(){try{await clearTrustMission();setActiveMission(null);setMessage('Trust mission cleared.')}catch(error:any){setMessage(error?.message||'Trust mission could not be cleared.')}}

 const level=overview?.global_level||{},totalXp=Number(overview?.lifetime_xp||0),currentThreshold=Number(level?.xp_threshold||0),nextThreshold=Number(level?.next_threshold||currentThreshold),span=Math.max(1,nextThreshold-currentThreshold),within=Math.max(0,totalXp-currentThreshold),pct=nextThreshold>currentThreshold?Math.min(1,within/span):1;
 const specialties=safeArray(overview?.specialties),allBadges=safeArray(overview?.badges),recent=safeArray(overview?.recent_xp);
 const badges=allBadges.filter((b:any)=>!b?.criteria?.catalog_hidden),earnedBadges=badges.filter((b:any)=>b.earned),lockedBadges=badges.filter((b:any)=>!b.earned);
 const leagueDivision=divisionForXp(totalXp),nextLeagueDivision=nextDivisionForXp(totalXp),leaguePct=divisionProgress(totalXp),collectionTier=badgeCollectionTier(earnedBadges.length,badges.length);
 const byKind=useMemo(()=>Object.fromEntries(KINDS.map(kind=>[kind,objectives.filter((o:any)=>o.kind===kind)])),[objectives]);

 const season=world?.season||null,seasonXp=Number(season?.season_xp||0),chapters=safeArray(season?.chapters),chapter=chapterState(chapters,seasonXp);
 const rewardTrack=safeArray(season?.reward_track),nextReward=rewardTrack.find((row:any)=>Number(row.xp||0)>seasonXp)||null;
 const trust=world?.contributor_trust||{},trustScore=Number(trust?.score||0),trustNext=Number(trust?.next_rank_score||100),trustPct=trustNext?Math.min(1,trustScore/trustNext):1;
 const collections=safeArray(world?.badge_collections),campaign=world?.community_campaign||null,contest=world?.featured_contest||null,rivals=safeArray(world?.rivals);
 const seasonalRewards=rewards.filter((reward:any)=>reward?.reward_kind==='theme');
 const trustDiscoveries=recent.filter((event:any)=>Boolean(event?.subject?.trust_discovery));
 const publicIdentity=seasonalRewards[0]?.identity||{};
 const showcaseSlots=Math.max(1,Math.min(6,Number(publicIdentity.showcase_slots||1))),publicCrests=earnedBadges.filter((badge:any)=>badge?.criteria?.public_showcase===true).slice(0,showcaseSlots);

 return <SafeAreaView style={[s.safe,{backgroundColor:theme.canvas}]}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>load()}/>} contentContainerStyle={s.content}>
  <View style={[s.hero,{backgroundColor:theme.resolved==='dark'?theme.surfaceRaised:'#594016',borderWidth:1,borderColor:theme.accent}]}>
   <Text style={s.eyebrow}>YOUR KLEENEST CAREER</Text>
   <View style={s.heroRow}><View style={{flex:1}}><Text style={s.heroLevel}>Level {level.level||1}</Text><Text style={s.heroTitle}>{level.title||'Scout'}</Text><Text style={s.heroXp}>{totalXp.toLocaleString()} lifetime XP</Text></View><View style={[s.streak,{backgroundColor:theme.surface}]}><Text style={[s.streakValue,{color:theme.accent}]}>{Number(dashboard?.current_streak||0)}d</Text><Text style={[s.streakLabel,{color:theme.muted}]}>STREAK</Text></View></View>
   <View style={s.track}><View style={[s.fill,{backgroundColor:theme.accent,width:(String(Math.round(pct*100))+'%') as any}]} /></View>
   <Text style={s.heroMeta}>{nextThreshold>totalXp?(nextThreshold-totalXp).toLocaleString()+' XP to Level '+Number((level.level||1)+1):'Current top threshold reached'}{level.unlock_text?' · '+level.unlock_text:''}</Text>
  </View>

  <View style={s.actions}><Pressable style={[s.primary,{backgroundColor:theme.accent}]} onPress={()=>router.push('/discover')}><Text style={[s.primaryText,{color:theme.accentText}]}>Find useful work nearby</Text></Pressable><Pressable style={[s.secondary,{backgroundColor:theme.surface,borderColor:theme.line}]} onPress={()=>router.push('/games')}><Text style={[s.secondaryText,{color:theme.accent}]}>Game Center</Text></Pressable></View>

  <View style={[s.leagueCard,{backgroundColor:theme.surface,borderColor:theme.accent}]}><View style={s.leagueHead}><View style={[s.leagueIcon,{backgroundColor:theme.accent}]}><Text style={[s.leagueIconText,{color:theme.accentText}]}>{leagueDivision.icon}</Text></View><View style={{flex:1}}><Text style={[s.kicker,{color:theme.muted}]}>KLEENEST LEAGUE</Text><Text style={[s.leagueTitle,{color:theme.ink}]}>{leagueDivision.name} Division</Text><Text style={[s.body,{color:theme.muted}]}>{leagueDivision.description}</Text></View></View><View style={s.trackSmall}><View style={[s.fillSmall,{width:(String(Math.round(leaguePct*100))+'%') as any}]} /></View><Text style={[s.meta,{color:theme.muted}]}>{nextLeagueDivision?Math.max(0,nextLeagueDivision.minXp-totalXp).toLocaleString()+' XP to '+nextLeagueDivision.name:'Top current division'} · {collectionTier}</Text></View>

  <View style={s.trustCard}>
   <View style={s.row}><View style={{flex:1}}><Text style={s.lightKicker}>TRUST RANK · EVIDENCE-BACKED</Text><Text style={s.trustTitle}>{trust?.rank||'New'}</Text><Text style={s.trustBody}>Your level shows progress. Trust shows how reliable your real-world contributions have become.</Text></View><View style={s.trustDial}><Text style={s.trustScore}>{trustScore}</Text><Text style={s.trustScoreLabel}>TRUST</Text></View></View>
   <View style={s.darkTrack}><View style={[s.goldFill,{width:(String(Math.round(trustPct*100))+'%') as any}]} /></View>
   <View style={s.trustStats}><MiniDark value={Number(trust?.evidence_score||0)} label="evidence score"/><MiniDark value={'+'+Number(trust?.progression_bonus||0)} label="progress bonus"/><MiniDark value={Number(trust?.verified_checkins||0)} label="verified visits"/></View>
   <Text style={s.trustFoot}>{trust?.explanation||'Verified evidence grows trust. Games improve mastery but cannot manufacture contributor authority.'}</Text>
  </View>

  {seasonalRewards.length?<View>
   <Header kicker="SEASONAL REWARD VAULT" title="Themes you grow into" body="These editions are owner-gated during Early Access. Their future progression requirements are already staged so they can become permanent earned rewards without changing the reward system."/>
   <View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}>
    {seasonalRewards.map((reward:any)=>{const req=reward.requirements||{},key=String(reward.reward_key||''),icon=key==='fall'?'🍁':key==='halloween'?'🎃':key==='thanksgiving'?'🌾':'❄️';return <View key={reward.code} style={[s.vaultReward,{borderColor:reward.unlocked?theme.accent:theme.line,backgroundColor:theme.surfaceRaised}]}><Text style={s.vaultIcon}>{icon}</Text><View style={{flex:1}}><View style={s.row}><Text style={[s.cardTitle,{color:theme.ink,flex:1}]}>{reward.name}</Text><Text style={[s.vaultState,{color:reward.unlocked?theme.accent:theme.muted}]}>{reward.unlocked?'UNLOCKED':'LOCKED'}</Text></View><Text style={[s.body,{color:theme.muted}]}>{reward.description}</Text><Text style={[s.meta,{color:theme.muted}]}>Future gate · Level {Number(req.level||1)} · Trust {Number(req.trust_score||0)} · {Number(req.lifetime_xp||0).toLocaleString()} XP · {Number(req.badges||0)} badges</Text>{reward.unlocked?<Text style={[s.unlockSource,{color:theme.accent}]}>{String(reward.unlock_source||'reward').replaceAll('_',' ').toUpperCase()}</Text>:null}</View></View>})}
   </View>
  </View>:null}

  <View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}>
   <Text style={[s.worldKicker,{color:theme.accent}]}>TRUST DISCOVERY</Text>
   <Text style={[s.worldTitle,{color:theme.ink}]}>Some trusted reviews have more to reveal.</Text>
   <Text style={[s.body,{color:theme.muted}]}>A normal review can uncover surprise XP when multiple forms of useful, trustworthy evidence line up. The exact trigger stays intentionally hidden, so there is no single field to game. Bonuses are duplicate-protected and daily-capped.</Text>
   <Text style={[s.meta,{color:theme.muted}]}>Trust itself is never random: your public Trust Rank still comes from verified evidence and contribution history. Trust Discovery XP advances progression and the evidence-backed progression bonus path.</Text>
   {trustDiscoveries.length?<Text style={[s.unlockSource,{color:theme.accent}]}>{trustDiscoveries.length} recent Trust Discovery unlock{trustDiscoveries.length===1?'':'s'}</Text>:<Text style={[s.meta,{color:theme.muted}]}>You will know when one unlocks—but not which single review detail caused it.</Text>}
  </View>

  {season?<View style={s.seasonHero}>
   <View style={s.seasonTop}><View><Text style={s.seasonLabel}>{season.label||SEASON_MARKETING.label}</Text><Text style={s.seasonTitle}>{String(season.name||SEASON_MARKETING.name).toUpperCase()}</Text></View><View style={s.daysPill}><Text style={s.daysValue}>{Number(season.days_remaining||0)}</Text><Text style={s.daysLabel}>DAYS LEFT</Text></View></View>
   <Text style={s.seasonBody}>{season.description}</Text>
   <View style={s.seasonScore}><Text style={s.seasonScoreValue}>{seasonXp.toLocaleString()}</Text><Text style={s.seasonScoreLabel}>SEASON XP</Text></View>
   <View style={s.chapterNow}><Text style={s.lightKicker}>CURRENT CHAPTER</Text><Text style={s.chapterTitle}>{chapter.current?.chapter?chapter.current.chapter+'. ':''}{chapter.current?.title||'Signal Hunt'}</Text><Text style={s.chapterBody}>{chapter.current?.subtitle||'Make the network fresher than you found it.'}</Text></View>
   <View style={s.reveal}><Text style={s.revealKicker}>NEXT REVEAL</Text><Text style={s.revealTitle}>{chapter.next?chapter.next.title:nextReward?.label||'Season finale unlocked'}</Text><Text style={s.revealBody}>{chapter.next?Math.max(0,Number(chapter.next.unlock_xp||0)-seasonXp).toLocaleString()+' season XP to reveal · '+String(chapter.next.surprise||'New objectives appear.'):(nextReward?Math.max(0,Number(nextReward.xp||0)-seasonXp).toLocaleString()+' season XP · '+String(nextReward.reward||'Reward reveal'):'You have revealed the current season path.')}</Text></View>
  </View>:null}

  {chapters.length?<View><Header kicker="CHAPTERS" title="An expedition, not a checklist" body="Each chapter changes the shape of play—from fast signal hunts to community campaigns and a Guardian finale."/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chapterRail}>{chapters.map((row:any)=>{const unlocked=seasonXp>=Number(row.unlock_xp||0),active=chapter.current?.code===row.code;return <View key={row.code} style={[s.chapterCard,active&&s.chapterActive,!unlocked&&s.chapterLocked]}><Text style={s.chapterNumber}>CH {row.chapter}</Text><Text style={[s.chapterCardTitle,{color:theme.ink}]}>{unlocked?row.title:'Locked'}</Text><Text style={[s.chapterCardBody,{color:theme.muted}]}>{unlocked?row.subtitle:Number(row.unlock_xp||0).toLocaleString()+' season XP to unlock'}</Text><Text style={s.chapterMechanic}>{unlocked?safeArray(row.mechanics).join(' · ').replaceAll('_',' '):'🔒'}</Text></View>})}</ScrollView></View>:null}

  {message?<Text style={s.message}>{message}</Text>:null}
  {activeMission?.status==='active'?<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.kicker,{color:theme.muted}]}>ACTIVE TRUST MISSION</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{activeMission.locationName}</Text><Text style={[s.body,{color:theme.muted}]}>{activeMission.title||'Complete the verified evidence goal at this restroom.'}</Text><View style={s.actions}><Pressable style={[s.primary,{backgroundColor:theme.accent}]} onPress={()=>router.push({pathname:'/location/[id]',params:{id:activeMission.locationId,mission:'1'}})}><Text style={[s.primaryText,{color:theme.accentText}]}>Resume mission</Text></Pressable><Pressable style={[s.secondary,{backgroundColor:theme.surface,borderColor:theme.line}]} onPress={clearActiveMission}><Text style={[s.secondaryText,{color:theme.accent}]}>Clear mission</Text></Pressable></View></View>:null}

  {campaign?<View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={s.worldKicker}>COMMUNITY METER</Text><Text style={[s.worldTitle,{color:theme.ink}]}>{campaign.title}</Text><Text style={[s.body,{color:theme.muted}]}>{campaign.description}</Text><WorldMeter progress={Number(campaign.community_progress||0)} target={Number(campaign.community_target||1)} label="Kleenest-wide progress"/><Text style={[s.meta,{color:theme.muted}]}>Your contribution: {Number(campaign.progress||0)}/{Number(campaign.target||1)} · when the community meter moves, everybody sees it.</Text></View>:null}

  {contest?<View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={s.worldKicker}>PRIZE LADDER</Text><Text style={[s.worldTitle,{color:theme.ink}]}>{contest.title}</Text><Text style={[s.body,{color:theme.muted}]}>{contest.description}</Text><WorldMeter progress={Number(contest.progress||0)} target={Number(contest.target||1)} label="Your qualifying progress"/><View style={s.prizeRow}>{safeArray(contest?.rewards?.prize_ladder).map((p:any)=><View style={s.prize} key={String(p.place)}><Text style={s.prizePlace}>TOP {p.place}</Text><Text style={s.prizeReward}>{p.reward}</Text></View>)}</View></View>:null}

  {rivals.length?<View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}><View style={s.row}><View style={{flex:1}}><Text style={s.worldKicker}>RIVAL LADDER</Text><Text style={[s.worldTitle,{color:theme.ink}]}>People close enough to matter</Text></View><Pressable style={[s.secondary,{backgroundColor:theme.surface,borderColor:theme.line}]} onPress={()=>router.push('/social')}><Text style={[s.secondaryText,{color:theme.accent}]}>Community</Text></Pressable></View>{rivals.slice(0,8).map((r:any)=><View style={s.rivalRow} key={String(r.user_id)}><Text style={s.rivalRank}>#{r.rank}</Text><View style={{flex:1}}><Text style={[s.rivalName,{color:theme.ink}]}>{r.is_current_user?'You':r.display_name}</Text><Text style={[s.meta,{color:theme.muted}]}>{Number(r.score||0).toLocaleString()} season XP</Text></View>{r.is_current_user?<Text style={s.youPill}>YOU</Text>:null}</View>)}</View>:null}

  <Header kicker="SPECIALTY LEVELS" title="Build your own kind of expertise" body="The same trusted actions grow your overall level and the specialties they actually represent."/>
  <View style={s.grid}>{specialties.length?specialties.map((item:any)=><View style={[s.specialty,{backgroundColor:theme.surface,borderColor:theme.line}]} key={item.specialty}><Text style={[s.specialtyLevel,{color:theme.accent}]}>LV {item.level||1}</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{SPECIALTY_LABEL[item.specialty]||String(item.specialty).replaceAll('_',' ')}</Text><Text style={[s.meta,{color:theme.muted}]}>{Number(item.xp||0).toLocaleString()} specialty XP</Text></View>):Object.entries(SPECIALTY_LABEL).map(([key,label])=><View style={[s.specialty,{backgroundColor:theme.surface,borderColor:theme.line}]} key={key}><Text style={[s.specialtyLevel,{color:theme.accent}]}>LV 1</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{label}</Text><Text style={[s.meta,{color:theme.muted}]}>Start contributing to progress</Text></View>)}</View>

  <Header kicker="WHAT TO DO NEXT" title="Useful actions near you" body="Nearby data gaps turn progression into real-world assignments instead of abstract grinding."/>
  {opportunities.length?opportunities.slice(0,6).map((item:any)=><Pressable key={item.location_id} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]} onPress={()=>router.push({pathname:'/location/[id]',params:{id:String(item.location_id)}})}><View style={s.row}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{item.name||'Nearby location'}</Text><Text style={[s.body,{color:theme.muted}]}>{String(item.kind||'contribution opportunity').replaceAll('_',' ')}</Text></View><Text style={[s.distance,{color:theme.accent}]}>{Number(item.distance_m||0)>=1609?(Number(item.distance_m)/1609.344).toFixed(1)+' mi':Math.max(0,Math.round(Number(item.distance_m||0)))+' m'}</Text></View></Pressable>):<View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.cardTitle,{color:theme.ink}]}>Find a missing place</Text><Text style={[s.body,{color:theme.muted}]}>Explore nearby or add a place that the network missed. GPS-supported and live on-site evidence are rewarded more strongly.</Text><Pressable style={[s.secondary,{backgroundColor:theme.surface,borderColor:theme.line}]} onPress={()=>router.push('/discover')}><Text style={[s.secondaryText,{color:theme.accent}]}>Start discovery</Text></Pressable></View>}

  {KINDS.map(kind=><View key={kind}><Header kicker={kind.toUpperCase()} title={KIND_LABEL[kind]} body={objectiveFlavor(kind).promise}/>{byKind[kind]?.length?byKind[kind].map((o:any)=><ObjectiveWorldCard key={o.id||o.code} item={o}/>):<View style={[s.empty,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.body,{color:theme.muted}]}>No active {KIND_LABEL[kind].toLowerCase()} right now.</Text></View>}</View>)}

  {collections.length?<View><Header kicker="BADGE COLLECTIONS" title="Collect sets, not random icons" body="Individual badges still matter, but completing a themed set gives your achievements a larger shape."/><View style={s.collectionGrid}>{collections.map((c:any)=><View style={[s.collectionCard,{backgroundColor:theme.surface,borderColor:theme.line}]} key={c.code}><Text style={s.collectionIcon}>{c.icon||'🏅'}</Text><Text style={[s.collectionName,{color:theme.ink}]}>{c.name}</Text><Text style={[s.body,{color:theme.muted}]}>{c.description}</Text><WorldMeter progress={Number(c.earned_count||0)} target={Number(c.total_count||1)} label={Number(c.earned_count||0)+'/'+Number(c.total_count||0)+' collected'}/><Text style={s.collectionReward}>{c?.reward?.completion_reward||'Collection completion mark'}</Text></View>)}</View></View>:null}

  <Header kicker="PUBLIC SHOWCASE" title="What other contributors can see" body="Showcase space is earned by combining progression Level with evidence-backed Trust Rank. Higher gates unlock more public crest slots."/>
  <View style={[s.worldPanel,{backgroundColor:theme.surface,borderColor:theme.line}]}><View style={s.showcaseRail}>{Array.from({length:showcaseSlots}).map((_,index)=>{const badge=publicCrests[index];return badge?<View style={[s.showcaseCell,{backgroundColor:theme.surfaceRaised,borderColor:theme.accent}]} key={badge.id||badge.code}><Text style={s.showcaseIcon}>{badge.icon||'🏅'}</Text><Text style={[s.showcaseName,{color:theme.ink}]}>{badge.name}</Text><Text style={[s.showcaseMeta,{color:theme.accent}]}>PUBLIC CREST</Text></View>:<View style={[s.showcaseCell,{backgroundColor:theme.surfaceRaised,borderColor:theme.line,borderStyle:'dashed'}]} key={'slot-'+index}><Text style={[s.showcaseIcon,{color:theme.muted}]}>◇</Text><Text style={[s.showcaseMeta,{color:theme.muted}]}>OPEN SHOWCASE SLOT</Text></View>})}</View><Text style={[s.meta,{color:theme.muted}]}>Current public identity · Level {Number(publicIdentity.level||level.level||1)} {publicIdentity.level_title||level.title||'Scout'} · Trust {publicIdentity.trust_rank||trust.rank||'New'} {Number(publicIdentity.trust_score??trustScore)}</Text></View>

  <Header kicker="BADGES" title="Achievement collection" body={earnedBadges.length+'/'+badges.length+' visible badges earned. Legacy duplicates stay out of the active collection without deleting history.'}/>
  <View style={s.badgeGrid}>{earnedBadges.slice(0,12).map((b:any)=><View style={[s.badge,s.badgeEarned]} key={b.code||b.name}><Text style={s.badgeIcon}>{b.icon||'🏅'}</Text><Text style={[s.badgeName,{color:theme.ink}]}>{b.name}</Text><Text style={[s.badgeState,{color:theme.muted}]}>EARNED</Text></View>)}{lockedBadges.slice(0,12).map((b:any)=><View style={s.badge} key={b.code||b.name}><Text style={s.badgeIcon}>🔒</Text><Text style={[s.badgeName,{color:theme.ink}]}>{b.name}</Text><Text numberOfLines={2} style={[s.badgeState,{color:theme.muted}]}>{b.description||'Keep contributing'}</Text></View>)}</View>

  <Header kicker="RANKINGS" title="Where you stand" body="Switch scopes without exposing anyone's precise contribution history."/>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.scopeRow}>{RANK_SCOPES.map(scope=><Pressable key={scope} onPress={()=>changeScope(scope)} style={[s.scope,rankScope===scope&&s.scopeActive]}><Text style={[s.scopeText,rankScope===scope&&s.scopeTextActive]}>{scope.toUpperCase()}</Text></Pressable>)}</ScrollView>
  {rankings.length?rankings.slice(0,15).map((r:any)=><View style={[s.rank,{backgroundColor:theme.surface,borderColor:theme.line}]} key={rankScope+'-'+r.user_id}><Text style={[s.rankNumber,{color:theme.accent}]}>#{r.rank}</Text><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>Kleenest contributor</Text><Text style={[s.meta,{color:theme.muted}]}>{Number(r.score||0).toLocaleString()} XP · {String(r.scope||rankScope)}</Text></View></View>):<View style={[s.empty,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.body,{color:theme.muted}]}>No ranking activity yet in this scope.</Text></View>}

  <Header kicker="XP HISTORY" title="Why your level moved" body="Every canonical award is explainable and duplicate-protected."/>
  {recent.slice(0,20).map((event:any,index:number)=>{const discovery=Boolean(event?.subject?.trust_discovery);return <View style={[s.xpRow,{backgroundColor:theme.surface,borderColor:discovery?theme.accent:theme.line}]} key={String(event.created_at)+'-'+index}><View style={{flex:1}}><Text style={[s.cardTitle,{color:theme.ink}]}>{discovery?'Trust Discovery':String(event.action||'progress').replaceAll('_',' ')}</Text><Text style={[s.meta,{color:theme.muted}]}>{discovery?'Mystery evidence bonus · ':''}{event.created_at?new Date(event.created_at).toLocaleString():''}</Text></View><Text style={[s.xpAward,{color:theme.accent}]}>+{Number(event.xp||0)} XP</Text></View>})}
 </ScrollView></SafeAreaView>;
}

function ObjectiveWorldCard({item}:{item:any}){
 const kind=String(item.kind||'quest'),flavor=objectiveFlavor(kind),progress=Number(item.progress||0),target=Math.max(1,Number(item.target||1)),pct=percent(progress,target),reward=Number(item?.rewards?.xp||0),mechanic=String(item?.rules?.mechanic||'progress').replaceAll('_',' ');
 const special=kind==='quest'?'One sharp objective. Finish it and move on.':kind==='mission'?'A purposeful assignment that builds evidence in the real world.':kind==='challenge'?'Constraints create the difficulty—time, count, accuracy or freshness.':kind==='journey'?'Milestones reveal as the journey advances.':kind==='campaign'?'Your progress contributes to something larger than your own account.':kind==='contest'?'Your progress qualifies you; ranking decides the podium.':'Useful progress.';
 const chapterMarks=kind==='journey'?safeArray(item?.rules?.chapters):[];
 return <View style={[s.objective,{borderColor:flavor.accent,backgroundColor:flavor.soft}]}>
  <View style={s.row}><View style={s.objectiveIcon}><Text style={s.objectiveIconText}>{flavor.icon}</Text></View><View style={{flex:1}}><Text style={[s.objectiveKicker,{color:flavor.accent}]}>{flavor.label} · {mechanic.toUpperCase()}</Text><Text style={s.objectiveTitle}>{item.title||'Objective'}</Text></View>{reward?<Text style={[s.reward,{color:flavor.accent}]}>+{reward} XP</Text>:null}</View>
  <Text style={s.body}>{item.description||'Complete useful Kleenest actions to advance.'}</Text>
  <Text style={s.objectiveRule}>{special}</Text>
  <View style={s.trackSmall}><View style={[s.fillSmall,{width:(String(Math.round(pct*100))+'%') as any,backgroundColor:flavor.accent}]} /></View>
  {chapterMarks.length?<View style={s.milestones}>{chapterMarks.map((mark:any)=><View key={String(mark)} style={[s.milestone,progress>=Number(mark)&&{backgroundColor:flavor.accent}]}><Text style={[s.milestoneText,progress>=Number(mark)&&{color:'#fff'}]}>{mark}</Text></View>)}</View>:null}
  <Text style={s.meta}>{progress}/{target} · {String(item.state||'active').toUpperCase()}</Text>
 </View>
}
function WorldMeter({progress,target,label}:{progress:number;target:number;label:string}){const pct=percent(progress,Math.max(1,target));return <View style={{gap:5}}><View style={s.trackSmall}><View style={[s.fillSmall,{width:(String(Math.round(pct*100))+'%') as any}]} /></View><View style={s.meterLine}><Text style={s.meta}>{label}</Text><Text style={s.meterValue}>{Math.min(progress,target).toLocaleString()} / {target.toLocaleString()}</Text></View></View>}
function MiniDark({value,label}:{value:any;label:string}){return <View style={s.miniDark}><Text style={s.miniDarkValue}>{value}</Text><Text style={s.miniDarkLabel}>{label}</Text></View>}
function Header({kicker,title,body}:{kicker:string;title:string;body:string}){return <View style={s.header}><Text style={s.kicker}>{kicker}</Text><Text style={s.sectionTitle}>{title}</Text><Text style={s.body}>{body}</Text></View>}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:palette.canvas},content:{padding:18,paddingBottom:50,gap:12},
 hero:{backgroundColor:palette.green,borderRadius:24,padding:20,gap:9},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.5,color:'#bed3c5'},heroRow:{flexDirection:'row',alignItems:'center',gap:12},heroLevel:{fontSize:12,fontWeight:'900',color:'#d3e3d8'},heroTitle:{fontSize:31,fontWeight:'900',color:'#fff'},heroXp:{fontSize:15,fontWeight:'800',color:'#fff',marginTop:3},streak:{width:68,height:68,borderRadius:34,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},streakValue:{fontSize:19,fontWeight:'900',color:palette.green},streakLabel:{fontSize:7,fontWeight:'900',color:palette.muted},track:{height:9,borderRadius:999,backgroundColor:'rgba(255,255,255,.2)',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#fff'},heroMeta:{fontSize:10,fontWeight:'800',color:'#dce9e1'},
 actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{flex:1,minWidth:150,minHeight:48,borderRadius:13,backgroundColor:palette.green,alignItems:'center',justifyContent:'center',paddingHorizontal:12},primaryText:{color:'#fff',fontWeight:'900'},secondary:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:'#bdd0c4',backgroundColor:'#fff',alignItems:'center',justifyContent:'center',paddingHorizontal:12},secondaryText:{fontWeight:'900',color:palette.green},
 message:{padding:11,borderRadius:12,backgroundColor:'#fff7d5',color:'#65510a'},header:{gap:3,marginTop:8},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.35,color:palette.muted},lightKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:'#bcd4c5'},sectionTitle:{fontSize:22,fontWeight:'900',color:palette.ink},body:{fontSize:12.5,lineHeight:18,color:palette.muted},
 leagueCard:{backgroundColor:'#fff',borderRadius:20,padding:15,borderWidth:2,borderColor:palette.green,gap:9},leagueHead:{flexDirection:'row',gap:11,alignItems:'center'},leagueIcon:{width:50,height:50,borderRadius:25,backgroundColor:palette.green,alignItems:'center',justifyContent:'center'},leagueIconText:{fontSize:25,fontWeight:'900',color:'#fff'},leagueTitle:{fontSize:20,fontWeight:'900',color:palette.ink},
 trustCard:{backgroundColor:'#112d21',borderRadius:22,padding:17,gap:10},trustTitle:{fontSize:29,fontWeight:'900',color:'#fff',marginTop:2},trustBody:{fontSize:12,lineHeight:18,color:'#d7e7dd',marginTop:4},trustDial:{width:70,height:70,borderRadius:35,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},trustScore:{fontSize:23,fontWeight:'900',color:'#173d2b'},trustScoreLabel:{fontSize:7,fontWeight:'900',color:'#6a766f'},darkTrack:{height:8,borderRadius:999,backgroundColor:'#315141',overflow:'hidden'},goldFill:{height:'100%',backgroundColor:'#f0d17d'},trustStats:{flexDirection:'row',gap:7},miniDark:{flex:1,backgroundColor:'#1d4030',borderRadius:12,padding:9},miniDarkValue:{fontSize:16,fontWeight:'900',color:'#fff'},miniDarkLabel:{fontSize:7,fontWeight:'800',color:'#bad0c2',marginTop:2},trustFoot:{fontSize:10,lineHeight:15,color:'#bad0c2'},
 seasonHero:{backgroundColor:'#143925',borderRadius:26,padding:19,gap:11,borderWidth:1,borderColor:'#2c5c42'},seasonTop:{flexDirection:'row',justifyContent:'space-between',gap:10,alignItems:'flex-start'},seasonLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.8,color:'#f0d17d'},seasonTitle:{fontSize:28,lineHeight:31,fontWeight:'900',color:'#fff',marginTop:3},seasonBody:{fontSize:13,lineHeight:20,color:'#d7e7dd'},daysPill:{backgroundColor:'#fff',borderRadius:16,paddingHorizontal:12,paddingVertical:9,alignItems:'center'},daysValue:{fontSize:20,fontWeight:'900',color:'#173d2b'},daysLabel:{fontSize:7,fontWeight:'900',color:'#65756b'},seasonScore:{flexDirection:'row',gap:8,alignItems:'baseline'},seasonScoreValue:{fontSize:32,fontWeight:'900',color:'#f0d17d'},seasonScoreLabel:{fontSize:9,fontWeight:'900',color:'#c8d8ce'},chapterNow:{backgroundColor:'#1d4934',borderRadius:17,padding:13,gap:3},chapterTitle:{fontSize:19,fontWeight:'900',color:'#fff'},chapterBody:{fontSize:11,lineHeight:16,color:'#d4e4da'},reveal:{backgroundColor:'#fff',borderRadius:17,padding:13,gap:3},revealKicker:{fontSize:8,fontWeight:'900',letterSpacing:1.4,color:'#8a6414'},revealTitle:{fontSize:17,fontWeight:'900',color:palette.ink},revealBody:{fontSize:11,lineHeight:16,color:palette.muted},
 chapterRail:{gap:9,paddingVertical:2},chapterCard:{width:205,minHeight:150,backgroundColor:'#fff',borderRadius:17,padding:13,borderWidth:1,borderColor:'#dbe5de',gap:4},chapterActive:{borderWidth:2,borderColor:palette.green},chapterLocked:{opacity:.62},chapterNumber:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:'#8a6414'},chapterCardTitle:{fontSize:17,fontWeight:'900',color:palette.ink},chapterCardBody:{fontSize:11,lineHeight:16,color:palette.muted},chapterMechanic:{fontSize:8,fontWeight:'900',color:palette.green,marginTop:5,textTransform:'uppercase'},
 worldPanel:{backgroundColor:'#fff',borderRadius:20,padding:16,borderWidth:1,borderColor:'#d9e4dc',gap:9},worldKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#557060'},worldTitle:{fontSize:22,lineHeight:26,fontWeight:'900',color:palette.ink},vaultReward:{flexDirection:'row',gap:11,padding:12,borderRadius:15,borderWidth:1},vaultIcon:{fontSize:29},vaultState:{fontSize:8,fontWeight:'900',letterSpacing:1},unlockSource:{fontSize:9,fontWeight:'900',letterSpacing:.8,marginTop:3},meterLine:{flexDirection:'row',justifyContent:'space-between',gap:8},meterValue:{fontSize:10,fontWeight:'900',color:palette.green},prizeRow:{flexDirection:'row',gap:7,flexWrap:'wrap'},prize:{flexGrow:1,flexBasis:95,backgroundColor:'#faf5e3',borderRadius:13,padding:10},prizePlace:{fontSize:8,fontWeight:'900',color:'#765b15'},prizeReward:{fontSize:10,lineHeight:14,fontWeight:'800',color:palette.ink,marginTop:3},rivalRow:{flexDirection:'row',alignItems:'center',gap:10,borderTopWidth:1,borderTopColor:'#edf1ee',paddingTop:9},rivalRank:{width:34,fontSize:16,fontWeight:'900',color:palette.green},rivalName:{fontSize:13,fontWeight:'900',color:palette.ink},youPill:{fontSize:8,fontWeight:'900',color:'#fff',backgroundColor:palette.green,paddingHorizontal:8,paddingVertical:5,borderRadius:999},
 grid:{flexDirection:'row',flexWrap:'wrap',gap:8},specialty:{width:'48%',backgroundColor:'#fff',borderRadius:16,padding:13,borderWidth:1,borderColor:'#dbe5de',gap:3},specialtyLevel:{fontSize:10,fontWeight:'900',color:palette.green},card:{backgroundColor:'#fff',borderRadius:17,padding:14,borderWidth:1,borderColor:'#dbe5de',gap:8},cardTitle:{fontSize:15,fontWeight:'900',color:palette.ink},meta:{fontSize:10.5,fontWeight:'700',color:palette.muted},row:{flexDirection:'row',alignItems:'flex-start',gap:10},distance:{fontSize:11,fontWeight:'900',color:palette.green},reward:{fontSize:12,fontWeight:'900'},
 trackSmall:{height:7,borderRadius:999,backgroundColor:'#e3ebe6',overflow:'hidden'},fillSmall:{height:'100%',backgroundColor:palette.green},empty:{backgroundColor:'#fff',borderRadius:15,padding:13,borderWidth:1,borderColor:'#e1e8e3'},
 objective:{borderRadius:19,padding:15,borderWidth:1.5,gap:8},objectiveIcon:{width:42,height:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},objectiveIconText:{fontSize:21},objectiveKicker:{fontSize:8,fontWeight:'900',letterSpacing:1.1},objectiveTitle:{fontSize:18,lineHeight:22,fontWeight:'900',color:palette.ink,marginTop:2},objectiveRule:{fontSize:10,lineHeight:15,fontWeight:'800',color:'#53665a'},milestones:{flexDirection:'row',justifyContent:'space-between',gap:6},milestone:{width:28,height:28,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#d7e2da',alignItems:'center',justifyContent:'center'},milestoneText:{fontSize:8,fontWeight:'900',color:palette.green},
 collectionGrid:{flexDirection:'row',flexWrap:'wrap',gap:9},collectionCard:{width:'48%',minHeight:210,backgroundColor:'#fff',borderRadius:18,padding:14,borderWidth:1,borderColor:'#d9e4dc',gap:6},collectionIcon:{fontSize:28},collectionName:{fontSize:17,fontWeight:'900',color:palette.ink},collectionReward:{fontSize:9,fontWeight:'900',color:'#8a6414'},
 showcaseRail:{flexDirection:'row',flexWrap:'wrap',gap:8},showcaseCell:{width:'31%',minHeight:116,borderRadius:15,borderWidth:1,padding:9,alignItems:'center',justifyContent:'center',gap:4},showcaseIcon:{fontSize:27},showcaseName:{fontSize:9,fontWeight:'900',textAlign:'center'},showcaseMeta:{fontSize:7,fontWeight:'900',letterSpacing:.5,textAlign:'center'},badgeGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},badge:{width:'31%',minHeight:112,borderRadius:15,padding:10,backgroundColor:'#f7f9f8',borderWidth:1,borderColor:'#dce5df',alignItems:'center',justifyContent:'center',gap:4},badgeEarned:{backgroundColor:'#eaf4ed',borderColor:'#b7d0c0'},badgeIcon:{fontSize:25},badgeName:{fontSize:10,fontWeight:'900',textAlign:'center',color:palette.ink},badgeState:{fontSize:7,fontWeight:'800',textAlign:'center',color:palette.muted},
 scopeRow:{gap:6,paddingBottom:2},scope:{paddingHorizontal:11,paddingVertical:8,borderRadius:999,backgroundColor:'#fff',borderWidth:1,borderColor:'#d5e0d8'},scopeActive:{backgroundColor:palette.green,borderColor:palette.green},scopeText:{fontSize:8,fontWeight:'900',color:palette.muted},scopeTextActive:{color:'#fff'},rank:{flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#fff',borderRadius:15,padding:12,borderWidth:1,borderColor:'#dce5df'},rankNumber:{width:40,fontSize:17,fontWeight:'900',color:palette.green},xpRow:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#fff',borderRadius:14,padding:12,borderWidth:1,borderColor:'#e1e8e3'},xpAward:{fontSize:14,fontWeight:'900',color:palette.green}
});
