import { CameraView, useCameraPermissions } from 'expo-camera';
import { router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,StyleSheet,Text,TextInput,View } from 'react-native';
import { executeQrAction,resolveQrAction,type ResolvedQrAction } from '../services/qrActions';

export default function QrActionScreen(){
  const {code}=useLocalSearchParams<{code?:string}>();
  const[input,setInput]=useState(String(code||''));
  const[value,setValue]=useState<ResolvedQrAction|null>(null);const[message,setMessage]=useState(code?'Resolving Kleenest QR…':'Scan or enter a Kleenest QR code.');const[busy,setBusy]=useState(false);const[scanning,setScanning]=useState(false);const[scanLocked,setScanLocked]=useState(false);
  const[permission,requestPermission]=useCameraPermissions();
  async function resolve(raw:string){const qr=String(raw||'').trim();if(!qr){setValue(null);setMessage('Enter the code printed on the Kleenest QR.');return;}setBusy(true);setMessage('Resolving Kleenest QR…');try{const action=await resolveQrAction(qr);setValue(action);setInput(qr);setScanning(false);setMessage(action.action_type==='trust_mission'?'This restroom needs fresh verified evidence. Start the trust mission while you are physically there.':'QR action ready.')}catch(error:any){setValue(null);setMessage(error?.message||'QR could not be resolved.')}finally{setBusy(false);setScanLocked(false)}}
  useEffect(()=>{if(code)void resolve(String(code))},[code]);
  async function startScanner(){if(permission?.granted){setValue(null);setScanning(true);setScanLocked(false);setMessage('Point the camera at a Kleenest QR code.');return;}const next=await requestPermission();if(next.granted){setValue(null);setScanning(true);setScanLocked(false);setMessage('Point the camera at a Kleenest QR code.')}else setMessage('Camera permission is needed to scan. You can still enter the QR code manually.')}
  function scanned({data}:{data:string}){if(scanLocked||busy)return;setScanLocked(true);void resolve(data)}
  async function run(){if(!value||busy)return;setBusy(true);try{const result=await executeQrAction(value);if(result.kind==='trust_mission'){setMessage('Reverification mission started. Opening the restroom…');router.replace({pathname:'/location/[id]',params:{id:result.locationId,contribute:'1',mission:'1'}});return;}if(result.locationId){router.replace({pathname:'/location/[id]',params:{id:String(result.locationId)}});return;}setMessage('This QR action is not supported by the mobile client yet.')}catch(error:any){setMessage(error?.message||'QR action could not be started.')}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><View style={s.card}><Text style={s.eyebrow}>KLEENEST QR</Text><Text style={s.title}>{value?.label||'Trust network action'}</Text><Text style={s.body}>{message}</Text>{scanning?<View style={s.scannerWrap}><CameraView style={s.camera} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanLocked?undefined:scanned}/><View style={s.scanGuide}/><Pressable style={s.stopScan} onPress={()=>{setScanning(false);setScanLocked(false);setMessage('Scanner closed. Enter a code or scan again.')}}><Text style={s.stopScanText}>Close scanner</Text></Pressable></View>:<Pressable style={s.scanButton} disabled={busy} onPress={startScanner}><Text style={s.scanButtonText}>Scan QR with camera</Text></Pressable>}<View style={s.codeRow}><TextInput style={s.input} value={input} onChangeText={setInput} onSubmitEditing={()=>resolve(input)} autoCapitalize="none" autoCorrect={false} returnKeyType="go" placeholder="Enter QR code"/><Pressable style={[s.resolve,busy&&s.disabled]} disabled={busy} onPress={()=>resolve(input)}><Text style={s.resolveText}>{busy?'Checking…':'Resolve'}</Text></Pressable></View><Text style={s.hint}>Camera and manual entry use the same canonical QR resolver. Scanning does not create a separate trust or attribution path.</Text>{value?.action_type==='trust_mission'?<View style={s.callout}><Text style={s.calloutTitle}>REVERIFICATION MISSION</Text><Text style={s.body}>Your verified check-in, review, and amenity observations will recalculate this restroom’s freshness and conflict consensus automatically.</Text></View>:null}<Pressable style={[s.primary,(!value||busy)&&s.disabled]} disabled={!value||busy} onPress={run}><Text style={s.primaryText}>{busy?'Starting…':value?.action_type==='trust_mission'?'Start trust mission':'Continue'}</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.replace('/explore')}><Text style={s.secondaryText}>Back to Explore</Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f8f6'},card:{margin:18,padding:20,borderRadius:22,backgroundColor:'#fff',borderWidth:1,borderColor:'#dde7e0',gap:12},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:2,color:'#4d6658'},title:{fontSize:24,fontWeight:'900',color:'#14231b'},body:{fontSize:14,lineHeight:20,color:'#607168'},scannerWrap:{height:320,borderRadius:18,overflow:'hidden',backgroundColor:'#102018',position:'relative'},camera:{flex:1},scanGuide:{position:'absolute',left:42,right:42,top:64,bottom:64,borderWidth:3,borderColor:'#fff',borderRadius:18},stopScan:{position:'absolute',bottom:12,alignSelf:'center',backgroundColor:'#fff',paddingHorizontal:14,paddingVertical:9,borderRadius:999},stopScanText:{color:'#173d2b',fontWeight:'900'},scanButton:{padding:15,borderRadius:14,backgroundColor:'#e4efe8',alignItems:'center'},scanButtonText:{color:'#173d2b',fontWeight:'900'},codeRow:{flexDirection:'row',gap:8},input:{flex:1,borderWidth:1,borderColor:'#ccd9d1',borderRadius:13,paddingHorizontal:13,paddingVertical:12,color:'#14231b'},resolve:{backgroundColor:'#edf3ef',paddingHorizontal:14,borderRadius:13,justifyContent:'center'},resolveText:{color:'#173d2b',fontWeight:'900'},hint:{fontSize:11,lineHeight:16,color:'#718078',fontWeight:'700'},callout:{padding:14,borderRadius:16,backgroundColor:'#fff6dd',borderWidth:1,borderColor:'#ead69c',gap:5},calloutTitle:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#695615'},primary:{padding:15,borderRadius:14,backgroundColor:'#173d2b',alignItems:'center'},disabled:{opacity:.5},primaryText:{color:'#fff',fontWeight:'900'},secondary:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#ccd9d1',alignItems:'center'},secondaryText:{color:'#173d2b',fontWeight:'900'}});
