import { CameraView, useCameraPermissions } from 'expo-camera';
import { router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { executeQrAction,resolveQrAction,type ResolvedQrAction } from '../services/qrActions';
import { TrustStrip, palette } from '../components/ConsumerUI';

export default function QrActionScreen(){
  const {code}=useLocalSearchParams<{code?:string}>();
  const[input,setInput]=useState(String(code||''));
  const[value,setValue]=useState<ResolvedQrAction|null>(null);const[message,setMessage]=useState(code?'Resolving Kleenest QR…':'Scan or enter a Kleenest QR code.');const[busy,setBusy]=useState(false);const[scanning,setScanning]=useState(false);const[scanLocked,setScanLocked]=useState(false);
  const[permission,requestPermission]=useCameraPermissions();
  async function resolve(raw:string){const qr=String(raw||'').trim();if(!qr){setValue(null);setMessage('Enter the code printed on the Kleenest QR.');return;}setBusy(true);setMessage('Resolving Kleenest QR…');try{const action=await resolveQrAction(qr);setValue(action);setInput(qr);setScanning(false);setMessage(action.action_type==='trust_mission'?'This restroom needs fresh verified evidence. Start the trust mission while you are physically there.':'QR action ready.')}catch(error:any){setValue(null);setMessage(error?.message||'QR could not be resolved.')}finally{setBusy(false);setScanLocked(false)}}
  useEffect(()=>{if(code)void resolve(String(code))},[code]);
  async function startScanner(){if(permission?.granted){setValue(null);setScanning(true);setScanLocked(false);setMessage('Point the camera at a Kleenest QR code.');return;}const next=await requestPermission();if(next.granted){setValue(null);setScanning(true);setScanLocked(false);setMessage('Point the camera at a Kleenest QR code.')}else setMessage('Camera permission is needed to scan. You can still enter the QR code manually.')}
  function scanned({data}:{data:string}){if(scanLocked||busy)return;setScanLocked(true);void resolve(data)}
  async function run(){if(!value||busy)return;setBusy(true);try{const result=await executeQrAction(value);if(result.kind==='trust_mission'){setMessage('Reverification mission started. Opening the restroom…');router.replace({pathname:'/location/[id]',params:{id:result.locationId,contribute:'1',mission:'1'}});return;}if(result.locationId){router.replace({pathname:'/location/[id]',params:{id:String(result.locationId)}});return;}setMessage('This QR action is not supported by the mobile client yet.')}catch(error:any){setMessage(error?.message||'QR action could not be started.')}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.hero}><Text style={s.heroEyebrow}>KLEENEST QR</Text><Text style={s.heroTitle}>Scan trust into the network.</Text><Text style={s.heroBody}>A Kleenest code can open the right restroom context, start a verified trust mission, or connect your visit to the evidence loop.</Text><TrustStrip items={['One canonical resolver','Verified visit context','No shadow attribution']}/></View>
    <View style={s.sectionLead}><Text style={s.sectionKicker}>SCAN</Text><Text style={s.sectionTitle}>{value?.label||'Point, scan, continue'}</Text><Text style={s.body}>{message}</Text></View>
    {scanning?<View style={s.scannerWrap}><CameraView style={s.camera} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanLocked?undefined:scanned}/><View style={s.scanShade}/><View style={s.scanGuide}/><View style={s.scanCaption}><Text style={s.scanCaptionText}>Align the Kleenest QR inside the frame</Text></View><Pressable style={s.stopScan} onPress={()=>{setScanning(false);setScanLocked(false);setMessage('Scanner closed. Enter a code or scan again.')}}><Text style={s.stopScanText}>Close scanner</Text></Pressable></View>:<Pressable style={s.scanButton} disabled={busy} onPress={startScanner}><Text style={s.scanButtonEyebrow}>CAMERA</Text><Text style={s.scanButtonText}>Scan Kleenest QR</Text><Text style={s.scanButtonHint}>Fastest when you are standing at the restroom</Text></Pressable>}
    <View style={s.manualCard}><Text style={s.cardKicker}>MANUAL FALLBACK</Text><Text style={s.cardTitle}>Enter the printed code</Text><Text style={s.body}>Use this when camera access is unavailable. Manual entry follows the exact same resolver and trust authority.</Text><View style={s.codeRow}><TextInput style={s.input} value={input} onChangeText={setInput} onSubmitEditing={()=>resolve(input)} autoCapitalize="none" autoCorrect={false} returnKeyType="go" placeholder="Enter QR code"/><Pressable style={[s.resolve,busy&&s.disabled]} disabled={busy} onPress={()=>resolve(input)}><Text style={s.resolveText}>{busy?'Checking…':'Resolve'}</Text></Pressable></View></View>
    {value?<View style={[s.readyCard,value.action_type==='trust_mission'&&s.missionCard]}><Text style={s.cardKicker}>{value.action_type==='trust_mission'?'TRUST MISSION READY':'QR ACTION READY'}</Text><Text style={s.cardTitle}>{value.label||'Kleenest action'}</Text><Text style={s.body}>{value.action_type==='trust_mission'?'Your verified check-in, review, photos and amenity observations can refresh this restroom’s trust state.':'Continue into the Kleenest context connected to this code.'}</Text><Pressable style={[s.primary,busy&&s.disabled]} disabled={busy} onPress={run}><Text style={s.primaryText}>{busy?'Starting…':value.action_type==='trust_mission'?'Start trust mission →':'Continue →'}</Text></Pressable></View>:null}
    <View style={s.integrity}><Text style={s.integrityTitle}>Why this matters</Text><Text style={s.integrityItem}>✓ Camera and manual entry converge through the same QR resolver.</Text><Text style={s.integrityItem}>✓ QR does not create a separate trust truth or hidden attribution path.</Text><Text style={s.integrityItem}>✓ Verified contribution still requires the real consumer evidence flow.</Text></View>
    <Pressable style={s.secondary} onPress={()=>router.replace('/explore')}><Text style={s.secondaryText}>Back to Explore</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:44,gap:12},hero:{backgroundColor:palette.green,padding:20,borderRadius:26,gap:8,shadowColor:'#000',shadowOpacity:.08,shadowRadius:14,elevation:3},heroEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.8,color:'#bad0c2'},heroTitle:{fontSize:31,lineHeight:35,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},sectionLead:{gap:4,marginTop:5},sectionKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:palette.muted},sectionTitle:{fontSize:23,fontWeight:'900',color:palette.ink},body:{fontSize:14,lineHeight:21,color:palette.muted},scannerWrap:{height:390,borderRadius:24,overflow:'hidden',backgroundColor:'#102018',position:'relative'},camera:{flex:1},scanShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(5,18,11,.16)'},scanGuide:{position:'absolute',left:42,right:42,top:74,bottom:88,borderWidth:3,borderColor:'#fff',borderRadius:24},scanCaption:{position:'absolute',left:28,right:28,top:24,alignItems:'center'},scanCaptionText:{color:'#fff',fontWeight:'900',fontSize:12},stopScan:{position:'absolute',bottom:18,alignSelf:'center',backgroundColor:'#fff',paddingHorizontal:16,paddingVertical:10,borderRadius:999},stopScanText:{color:palette.green,fontWeight:'900'},scanButton:{padding:18,borderRadius:20,backgroundColor:'#e5efe8',borderWidth:1,borderColor:'#cfdfd4',gap:3},scanButtonEyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:palette.muted},scanButtonText:{fontSize:20,fontWeight:'900',color:palette.green},scanButtonHint:{fontSize:12,color:palette.muted,fontWeight:'700'},manualCard:{backgroundColor:'#fff',padding:17,borderRadius:20,borderWidth:1,borderColor:'#dce6df',gap:6},cardKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:palette.muted},cardTitle:{fontSize:18,fontWeight:'900',color:palette.ink},codeRow:{flexDirection:'row',gap:8,marginTop:6},input:{flex:1,borderWidth:1,borderColor:'#ccd9d1',borderRadius:13,paddingHorizontal:13,paddingVertical:12,color:palette.ink,backgroundColor:'#fbfdfc'},resolve:{backgroundColor:'#edf3ef',paddingHorizontal:14,borderRadius:13,justifyContent:'center'},resolveText:{color:palette.green,fontWeight:'900'},readyCard:{backgroundColor:'#edf5f0',padding:18,borderRadius:20,borderWidth:1,borderColor:'#d4e3d9',gap:6},missionCard:{backgroundColor:'#fff6dd',borderColor:'#ead69c'},primary:{marginTop:5,padding:15,borderRadius:14,backgroundColor:palette.green,alignItems:'center'},disabled:{opacity:.5},primaryText:{color:'#fff',fontWeight:'900'},integrity:{backgroundColor:'#fff',padding:16,borderRadius:18,borderWidth:1,borderColor:'#dce6df',gap:6},integrityTitle:{fontSize:16,fontWeight:'900',color:palette.ink},integrityItem:{fontSize:12,lineHeight:18,fontWeight:'700',color:'#40584a'},secondary:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#ccd9d1',alignItems:'center'},secondaryText:{color:palette.green,fontWeight:'900'}});