import { router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { executeQrAction,resolveQrAction,type ResolvedQrAction } from '../services/qrActions';

export default function QrActionScreen(){
  const {code}=useLocalSearchParams<{code?:string}>();
  const[value,setValue]=useState<ResolvedQrAction|null>(null);const[message,setMessage]=useState('Resolving Kleenest QR…');const[busy,setBusy]=useState(false);
  useEffect(()=>{const qr=String(code||'');if(!qr){setMessage('This QR link is missing its code.');return;}resolveQrAction(qr).then(action=>{setValue(action);setMessage(action.action_type==='trust_mission'?'This restroom needs fresh verified evidence. Start the trust mission while you are physically there.':'QR action ready.')}).catch(error=>setMessage(error?.message||'QR could not be resolved.'))},[code]);
  async function run(){if(!value||busy)return;setBusy(true);try{const result=await executeQrAction(value);if(result.kind==='trust_mission'){setMessage('Reverification mission started. Opening the restroom…');router.replace({pathname:'/location/[id]',params:{id:result.locationId,contribute:'1',mission:'1'}});return;}if(result.locationId){router.replace({pathname:'/location/[id]',params:{id:String(result.locationId)}});return;}setMessage('This QR action is not supported by the mobile client yet.')}catch(error:any){setMessage(error?.message||'QR action could not be started.')}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><View style={s.card}><Text style={s.eyebrow}>KLEENEST QR</Text><Text style={s.title}>{value?.label||'Trust network action'}</Text><Text style={s.body}>{message}</Text>{value?.action_type==='trust_mission'?<View style={s.callout}><Text style={s.calloutTitle}>REVERIFICATION MISSION</Text><Text style={s.body}>Your verified check-in, review, and amenity observations will recalculate this restroom’s freshness and conflict consensus automatically.</Text></View>:null}<Pressable style={[s.primary,(!value||busy)&&s.disabled]} disabled={!value||busy} onPress={run}><Text style={s.primaryText}>{busy?'Starting…':value?.action_type==='trust_mission'?'Start trust mission':'Continue'}</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.replace('/explore')}><Text style={s.secondaryText}>Back to Explore</Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f8f6'},card:{margin:18,padding:20,borderRadius:22,backgroundColor:'#fff',borderWidth:1,borderColor:'#dde7e0',gap:12},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:2,color:'#4d6658'},title:{fontSize:24,fontWeight:'900',color:'#14231b'},body:{fontSize:14,lineHeight:20,color:'#607168'},callout:{padding:14,borderRadius:16,backgroundColor:'#fff6dd',borderWidth:1,borderColor:'#ead69c',gap:5},calloutTitle:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#695615'},primary:{padding:15,borderRadius:14,backgroundColor:'#173d2b',alignItems:'center'},disabled:{opacity:.5},primaryText:{color:'#fff',fontWeight:'900'},secondary:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#ccd9d1',alignItems:'center'},secondaryText:{color:'#173d2b',fontWeight:'900'}});
