import * as Linking from 'expo-linking';
import * as Location from 'expo-location';
import * as SecureStore from 'expo-secure-store';
import { useLocalSearchParams } from 'expo-router';
import { buildMobileRoute, getMobileLocations, mobileNavigationUrl, persistMobileRoute } from '@kleenest/mobile-core';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

const DRAFT_KEY='kleenest.native.route.draft';
export default function RouteScreen(){
  const params=useLocalSearchParams<{add?:string}>();
  const [stopIds,setStopIds]=useState<string[]>([]),[stops,setStops]=useState<any[]>([]),[built,setBuilt]=useState<any>(null),[message,setMessage]=useState('');
  useEffect(()=>{SecureStore.getItemAsync(DRAFT_KEY).then(raw=>{if(raw)try{setStopIds(JSON.parse(raw))}catch{}})},[]);
  useEffect(()=>{const add=String(params.add||'');if(!add)return;setStopIds(current=>current.includes(add)?current:[...current,add])},[params.add]);
  useEffect(()=>{SecureStore.setItemAsync(DRAFT_KEY,JSON.stringify(stopIds));getMobileLocations(stopIds).then(rows=>{const byId=new Map(rows.map((row:any)=>[String(row.id),row]));setStops(stopIds.map(id=>byId.get(id)).filter(Boolean))}).catch((error:any)=>setMessage(error?.message||'Stops could not be loaded.'))},[stopIds]);
  const byId=useMemo(()=>new Map(stops.map((row:any)=>[String(row.id),row])),[stops]);
  function move(index:number,delta:number){setStopIds(current=>{const next=[...current],target=index+delta;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next})}
  async function build(){setMessage('Building route…');try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Location permission is required to use My Location.');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const route=await buildMobileRoute([current.coords.longitude,current.coords.latitude],stopIds);setBuilt(route);setMessage(`${route.distanceMiles} mi · about ${route.durationMinutes} min`)}catch(error:any){setMessage(error?.message||'Route could not be built.')}}
  async function save(){if(!built)return;try{const saved=await persistMobileRoute(built);setBuilt(saved);setMessage(`Route saved${saved.routeId?` · ${saved.routeId}`:''}.`)}catch(error:any){setMessage(error?.message||'Route could not be saved.')}}
  async function navigate(){const url=mobileNavigationUrl(built);if(url)await Linking.openURL(url)}
  async function clear(){setStopIds([]);setBuilt(null);await SecureStore.deleteItemAsync(DRAFT_KEY);setMessage('Route cleared.')}
  return <SafeAreaView style={s.safe}><View style={s.container}><Text style={s.eyebrow}>ROUTE</Text><Text style={s.title}>Starting location + ordered stops</Text><Text style={s.body}>Start: <Text style={s.strong}>My Location</Text>. Add restroom stops from Explore, then rearrange them here. There is no Destination field.</Text><View style={s.actions}><Pressable style={s.primary} onPress={build} disabled={!stopIds.length}><Text style={s.primaryText}>Build route</Text></Pressable><Pressable style={s.secondary} onPress={clear}><Text style={s.secondaryText}>Clear</Text></Pressable></View>{message?<Text style={s.message}>{message}</Text>:null}{built?<View style={s.actions}><Pressable style={s.secondary} onPress={save}><Text style={s.secondaryText}>Save route</Text></Pressable><Pressable style={s.primary} onPress={navigate}><Text style={s.primaryText}>Start navigation</Text></Pressable></View>:null}</View><FlatList data={stopIds} keyExtractor={id=>id} contentContainerStyle={s.list} ListEmptyComponent={<View style={s.card}><Text style={s.body}>No stops yet. Add restroom locations from Explore.</Text></View>} renderItem={({item,index})=>{const row=byId.get(item);return <View style={s.card}><Text style={s.stopNumber}>STOP {index+1}</Text><Text style={s.cardTitle}>{row?.name||'Loading stop…'}</Text><Text style={s.meta}>{[row?.address,row?.city,row?.state].filter(Boolean).join(', ')}</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>move(index,-1)}><Text style={s.secondaryText}>Up</Text></Pressable><Pressable style={s.secondary} onPress={()=>move(index,1)}><Text style={s.secondaryText}>Down</Text></Pressable><Pressable style={s.secondary} onPress={()=>setStopIds(ids=>ids.filter(id=>id!==item))}><Text style={s.secondaryText}>Remove</Text></Pressable></View></View>}}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},container:{padding:22,gap:12},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,fontWeight:'800',color:'#14231b'},body:{fontSize:16,lineHeight:24,color:'#53645a'},strong:{fontWeight:'800',color:'#14231b'},message:{color:'#53645a',fontWeight:'700'},list:{padding:22,paddingTop:0,gap:12},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0'},cardTitle:{fontSize:18,fontWeight:'800',color:'#14231b'},stopNumber:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:'#4d6658',marginBottom:6},meta:{color:'#65756b',marginTop:6},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{backgroundColor:'#173d2b',padding:13,borderRadius:13},primaryText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#edf3ef',padding:13,borderRadius:13},secondaryText:{color:'#173d2b',fontWeight:'800'}});
