import * as Linking from 'expo-linking';
import { listMobileFavoriteLocations, toggleMobileFavorite } from '@kleenest/mobile-core';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { FlatList, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, View } from 'react-native';
const idOf=(item:any)=>String(item.location_id||item.id||'');
const navigateUrl=(item:any)=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${item.latitude},${item.longitude}`)}&travelmode=driving`;
export default function SavedScreen(){const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState('Loading saved restrooms…'),[loading,setLoading]=useState(false),[removingId,setRemovingId]=useState('');async function load(){setLoading(true);try{const data=await listMobileFavoriteLocations();setRows(data);setMessage(data.length?'':'No saved restrooms yet. Save one from Explore or its location page.')}catch(error:any){setMessage(error?.message||'Saved restrooms could not be loaded.')}finally{setLoading(false)}}async function remove(id:string){if(!id||removingId)return;setRemovingId(id);try{await toggleMobileFavorite(id);setRows(current=>current.filter(item=>idOf(item)!==id));setMessage('Restroom removed from Saved.')}catch(error:any){setMessage(error?.message||'Saved restroom could not be removed.')}finally{setRemovingId('')}}useEffect(()=>{load()},[]);return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.eyebrow}>SAVED</Text><Text style={s.title}>Your restroom shortlist</Text><Text style={s.body}>Keep trusted options close, navigate directly, or add one to a multi-stop route.</Text>{message?<Text style={s.message}>{message}</Text>:null}</View><FlatList data={rows} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} keyExtractor={(item,index)=>idOf(item)||String(index)} contentContainerStyle={s.list} renderItem={({item})=>{const id=idOf(item),hasCoordinates=Number.isFinite(Number(item.latitude))&&Number.isFinite(Number(item.longitude)),removing=removingId===id;return <View style={s.card}><Text style={s.cardTitle}>{item.name||item.location_name||'Restroom location'}</Text><Text style={s.meta}>{[item.address,item.city,item.state].filter(Boolean).join(', ')||'Location details available'}</Text><View style={s.actions}><Pressable style={s.secondary} onPress={()=>router.push(`/location/${id}`)}><Text style={s.secondaryText}>Details</Text></Pressable>{hasCoordinates?<Pressable style={s.primary} onPress={()=>Linking.openURL(navigateUrl(item))}><Text style={s.primaryText}>Navigate</Text></Pressable>:null}<Pressable style={s.secondary} onPress={()=>router.push({pathname:'/route',params:{add:id}})}><Text style={s.secondaryText}>Add to route</Text></Pressable><Pressable style={[s.remove,removing&&s.disabled]} disabled={removing} onPress={()=>remove(id)}><Text style={s.removeText}>{removing?'Removing…':'Remove'}</Text></Pressable></View></View>}}/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},header:{padding:22,gap:8},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:32,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},message:{color:'#53645a',fontWeight:'700'},list:{padding:20,paddingTop:0,gap:12},card:{backgroundColor:'#fff',padding:18,borderRadius:20,borderWidth:1,borderColor:'#dde7e0',gap:7},cardTitle:{fontSize:18,fontWeight:'800',color:'#14231b'},meta:{color:'#65756b'},actions:{flexDirection:'row',gap:8,marginTop:8,flexWrap:'wrap'},primary:{backgroundColor:'#173d2b',padding:12,borderRadius:12},primaryText:{color:'#fff',fontWeight:'900'},secondary:{backgroundColor:'#edf3ef',padding:12,borderRadius:12},secondaryText:{fontWeight:'800',color:'#173d2b'},remove:{backgroundColor:'#fff1ef',padding:12,borderRadius:12},removeText:{fontWeight:'900',color:'#8a352f'},disabled:{opacity:.5}});
