import { listMobileActivity, listMobileFollowers, listMobileFollowing, searchMobilePeople, toggleMobileFollow } from '@kleenest/mobile-core';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export default function CommunityScreen(){
  const [query,setQuery]=useState(''),[rows,setRows]=useState<any[]>([]),[following,setFollowing]=useState<any[]>([]),[followers,setFollowers]=useState<any[]>([]),[activity,setActivity]=useState<any[]>([]),[message,setMessage]=useState('');
  async function refresh(){try{const[nextFollowing,nextFollowers,nextActivity]=await Promise.all([listMobileFollowing(),listMobileFollowers(),listMobileActivity(12)]);setFollowing(nextFollowing);setFollowers(nextFollowers);setActivity(nextActivity)}catch(error:any){setMessage(error?.message||'Community could not be loaded.')}}
  useEffect(()=>{refresh()},[]);
  async function search(){try{const data=await searchMobilePeople(query);setRows(data);setMessage(data.length?'':'No people found.')}catch(error:any){setMessage(error?.message||'People search failed.')}}
  async function follow(id:string){try{await toggleMobileFollow(id);await refresh();setMessage('Follow state updated.')}catch(error:any){setMessage(error?.message||'Follow state could not be changed.')}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>COMMUNITY</Text><Text style={s.title}>People helping people.</Text><Text style={s.body}>Follow contributors, see what the community is doing, and build your own Kleenest standing by checking in and reviewing places.</Text>
    <View style={s.stats}><Stat value={following.length} label="following"/><Stat value={followers.length} label="followers"/><Stat value={activity.length} label="recent updates"/></View>
    <View style={s.section}><Text style={s.sectionTitle}>Find people</Text><View style={s.searchRow}><TextInput style={s.input} value={query} onChangeText={setQuery} placeholder="Name or username"/><Pressable style={s.primary} onPress={search}><Text style={s.primaryText}>Search</Text></Pressable></View>{message?<Text style={s.message}>{message}</Text>:null}{rows.map(item=><View style={s.card} key={item.id}><View><Text style={s.cardTitle}>{item.display_name||item.username||'Kleenest user'}</Text>{item.username?<Text style={s.meta}>@{item.username}</Text>:null}{item.bio?<Text style={s.body}>{item.bio}</Text>:null}</View><Pressable style={s.secondary} onPress={()=>follow(String(item.id))}><Text style={s.secondaryText}>Follow / Unfollow</Text></Pressable></View>)}</View>
    <View style={s.section}><Text style={s.sectionTitle}>Following</Text>{following.length?following.slice(0,6).map(person=><View style={s.personRow} key={person.id}><View><Text style={s.cardTitle}>{person.display_name||person.username||'Kleenest user'}</Text>{person.username?<Text style={s.meta}>@{person.username}</Text>:null}</View><Text style={s.points}>{person.points??0} pts</Text></View>):<Text style={s.body}>Find a few people to start building your community.</Text>}</View>
    <View style={s.section}><Text style={s.sectionTitle}>Community pulse</Text>{activity.length?activity.map(item=><View style={s.feedRow} key={item.id}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.meta}>{item.location?.name||item.detail||'Kleenest community'}</Text></View>):<Text style={s.body}>Community activity will appear here as people contribute.</Text>}</View>
  </ScrollView></SafeAreaView>;
}
function Stat({value,label}:{value:any;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f7f5'},content:{padding:22,paddingBottom:42,gap:10},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,color:'#4d6658'},title:{fontSize:34,lineHeight:38,fontWeight:'900',color:'#14231b'},body:{fontSize:15,lineHeight:22,color:'#53645a'},stats:{flexDirection:'row',gap:9,marginTop:6},stat:{flex:1,backgroundColor:'#fff',padding:13,borderRadius:16,borderWidth:1,borderColor:'#dde7e0'},statValue:{fontSize:20,fontWeight:'900',color:'#173d2b'},section:{gap:9,marginTop:16},sectionTitle:{fontSize:21,fontWeight:'900',color:'#14231b'},searchRow:{flexDirection:'row',gap:8},input:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:'#ccd9d1',borderRadius:14,padding:13},primary:{backgroundColor:'#173d2b',padding:13,borderRadius:13,justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'800'},message:{color:'#53645a'},meta:{color:'#65756b',fontSize:12,fontWeight:'700'},card:{backgroundColor:'#fff',padding:16,borderRadius:18,borderWidth:1,borderColor:'#dde7e0',gap:10},cardTitle:{fontSize:16,fontWeight:'800',color:'#14231b'},secondary:{backgroundColor:'#edf3ef',padding:11,borderRadius:12,alignSelf:'flex-start'},secondaryText:{color:'#173d2b',fontWeight:'800'},personRow:{backgroundColor:'#fff',padding:14,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},points:{fontWeight:'900',color:'#173d2b'},feedRow:{backgroundColor:'#fff',padding:14,borderRadius:16,gap:3}});
