import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { listMySupportRequests, submitSupportRequest, type SupportCategory, type SupportRequest } from '../services/support';
import { TrustStrip, palette } from '../components/ConsumerUI';

const CATEGORIES:{code:SupportCategory;label:string}[]=[{code:'general',label:'General'},{code:'account',label:'Account'},{code:'billing',label:'Billing'},{code:'technical',label:'Technical'},{code:'safety',label:'Safety'},{code:'feedback',label:'Feedback'}];
export default function SupportScreen(){
  const [subject,setSubject]=useState(''),[body,setBody]=useState(''),[category,setCategory]=useState<SupportCategory>('general'),[rows,setRows]=useState<SupportRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){try{setRows(await listMySupportRequests(20))}catch(error:any){setMessage(error?.message||'Support history could not be loaded.')}}
  useEffect(()=>{void load()},[]);
  async function submit(){if(busy)return;setBusy(true);setMessage('');try{if(subject.trim().length<3)throw new Error('Subject must be at least 3 characters.');if(body.trim().length<10)throw new Error('Message must be at least 10 characters.');const result=await submitSupportRequest(subject,body,category);setSubject('');setBody('');setCategory('general');setMessage(`Support request submitted. Status: ${result.status||'open'}.`);await load()}catch(error:any){setMessage(error?.message||'Support request could not be submitted.')}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.hero}><Text style={s.heroEyebrow}>HELP & SUPPORT</Text><Text style={s.heroTitle}>Get help without leaving Kleenest.</Text><Text style={s.heroBody}>Send an account-linked request, keep its status visible, and return to the exact consumer experience you were using.</Text><TrustStrip items={['Account-linked','Private identity','Status history']}/></View><View style={s.sectionLead}><Text style={s.sectionKicker}>NEW REQUEST</Text><Text style={s.sectionTitle}>What do you need help with?</Text><Text style={s.body}>Your ticket is tied to your signed-in account without exposing your email in the request form.</Text></View><View style={s.card}><Text style={s.cardTitle}>Choose a category</Text><View style={s.categories}>{CATEGORIES.map(item=><Pressable key={item.code} style={[s.pill,category===item.code&&s.pillOn]} onPress={()=>setCategory(item.code)}><Text style={[s.pillText,category===item.code&&s.pillTextOn]}>{item.label}</Text></Pressable>)}</View><TextInput style={s.input} value={subject} onChangeText={setSubject} maxLength={160} placeholder="Subject"/><TextInput style={[s.input,s.textarea]} value={body} onChangeText={setBody} maxLength={5000} multiline placeholder="Tell us what happened and what you need help with."/><Text style={s.counter}>{body.length}/5000</Text><Pressable style={[s.primary,busy&&s.disabled]} disabled={busy} onPress={submit}><Text style={s.primaryText}>{busy?'Sending…':'Send support request'}</Text></Pressable></View>{message?<View style={s.notice}><Text style={s.noticeText}>{message}</Text></View>:null}<View style={s.section}><View style={s.sectionHead}><View><Text style={s.sectionKicker}>HISTORY</Text><Text style={s.sectionTitle}>Your requests</Text></View><Pressable onPress={load}><Text style={s.refresh}>Refresh</Text></Pressable></View>{rows.length?rows.map(row=><View style={s.ticket} key={row.id}><View style={s.ticketTop}><View style={{flex:1}}><Text style={s.ticketTitle}>{row.subject}</Text><Text style={s.meta}>{row.category} · {new Date(row.created_at).toLocaleString()}</Text></View><Text style={s.status}>{String(row.status||'open').replaceAll('_',' ')}</Text></View><Text style={s.ticketBody}>{row.message}</Text></View>):<View style={s.empty}><Text style={s.emptyTitle}>No support requests yet.</Text><Text style={s.body}>When you contact Kleenest, your request history and current status will stay here.</Text></View>}</View><Pressable style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back to profile</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},content:{padding:20,paddingBottom:44,gap:12},hero:{backgroundColor:palette.green,padding:20,borderRadius:26,gap:8,shadowColor:'#000',shadowOpacity:.08,shadowRadius:14,elevation:3},heroEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.8,color:'#bad0c2'},heroTitle:{fontSize:31,lineHeight:35,fontWeight:'900',color:'#fff'},heroBody:{fontSize:14,lineHeight:21,color:'#dce9e1'},sectionLead:{gap:4,marginTop:4},sectionKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:palette.muted},sectionTitle:{fontSize:22,fontWeight:'900',color:palette.ink},body:{fontSize:13,lineHeight:20,color:palette.muted},card:{backgroundColor:'#fff',padding:17,borderRadius:20,borderWidth:1,borderColor:'#dde7e0',gap:11},cardTitle:{fontSize:18,fontWeight:'900',color:palette.ink},categories:{flexDirection:'row',flexWrap:'wrap',gap:7},pill:{paddingHorizontal:10,paddingVertical:8,borderRadius:999,backgroundColor:'#edf3ef'},pillOn:{backgroundColor:palette.green},pillText:{fontSize:12,fontWeight:'800',color:'#365344'},pillTextOn:{color:'#fff'},input:{backgroundColor:'#fbfdfc',borderWidth:1,borderColor:'#ccd9d1',borderRadius:14,padding:13},textarea:{minHeight:120,textAlignVertical:'top'},counter:{alignSelf:'flex-end',fontSize:12,color:'#718078',fontWeight:'700'},primary:{backgroundColor:palette.green,padding:14,borderRadius:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.5},notice:{backgroundColor:'#eaf2ed',padding:13,borderRadius:14},noticeText:{color:'#274535',fontWeight:'700'},section:{gap:9,marginTop:7},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},refresh:{color:palette.green,fontWeight:'900'},ticket:{backgroundColor:'#fff',padding:15,borderRadius:18,borderWidth:1,borderColor:'#dde7e0',gap:7},ticketTop:{flexDirection:'row',justifyContent:'space-between',gap:10},ticketTitle:{fontSize:16,fontWeight:'900',color:palette.ink},status:{fontSize:10,fontWeight:'900',color:palette.green,textTransform:'uppercase',backgroundColor:'#e8f3ec',paddingHorizontal:8,paddingVertical:5,borderRadius:999,overflow:'hidden',alignSelf:'flex-start'},meta:{fontSize:12,color:'#718078',fontWeight:'700',marginTop:3},ticketBody:{fontSize:13,lineHeight:20,color:palette.muted},empty:{backgroundColor:'#fff',padding:17,borderRadius:18,borderWidth:1,borderColor:'#dde7e0',gap:4},emptyTitle:{fontSize:17,fontWeight:'900',color:palette.ink},secondary:{backgroundColor:'#edf3ef',padding:14,borderRadius:14,alignItems:'center'},secondaryText:{color:palette.green,fontWeight:'800'}});