import { LegalDocument, LegalSection } from '../components/LegalDocument';

export default function TermsScreen(){return <LegalDocument eyebrow="LEGAL" title="Kleenest Terms of Use">
  <LegalSection title="Using Kleenest">Kleenest provides restroom discovery, routing, access information, community contributions, messaging, progression, safety, support, and related consumer features. You may use the service only lawfully and in accordance with these Terms and the Community Guidelines.</LegalSection>
  <LegalSection title="Accounts">Keep your account credentials secure and provide accurate information. You are responsible for activity performed through your account unless you promptly report unauthorized access. Do not impersonate another person, create accounts to evade moderation, or misuse another person's account.</LegalSection>
  <LegalSection title="User content">You retain ownership of content you create. By publishing content through Kleenest, you grant Kleenest a non-exclusive, worldwide license to host, store, reproduce, format, display, distribute, and use that content as necessary to operate, secure, moderate, and improve the service. Do not upload content you lack the right to share.</LegalSection>
  <LegalSection title="Community safety">Harassment, threats, hate, sexual exploitation, illegal content, doxxing, impersonation, fraud, spam, malicious manipulation of restroom information, and other harmful conduct are prohibited. Kleenest may investigate reports, restrict content visibility, remove content, suspend features, or limit or terminate accounts when reasonably necessary to protect users or enforce these rules.</LegalSection>
  <LegalSection title="Location and safety information">Restroom availability, cleanliness, accessibility, operating hours, routes, safety signals, and community observations can change. Kleenest provides decision-support information, not a guarantee that a location is open, accessible, sanitary, safe, or suitable for a particular need. Use appropriate judgment and follow posted rules and local conditions.</LegalSection>
  <LegalSection title="Membership and digital purchases">Any paid digital Consumer functionality offered in the Google Play-distributed Android app must use the applicable native-store purchase and entitlement process unless a Google Play policy exception applies. Displayed pricing does not itself grant an entitlement. Purchases, renewals, cancellations, refunds, and restores are subject to the store terms and the entitlement state verified by Kleenest.</LegalSection>
  <LegalSection title="Rewards, games and contests">Points, badges, streaks, quests, rankings, game progress and similar features are service features with no cash value unless a specific promotion expressly states otherwise. Any contest or promotion may have additional official rules that control that promotion.</LegalSection>
  <LegalSection title="Service changes">Kleenest may change, suspend, or discontinue features when necessary for security, compliance, maintenance, product evolution, or other legitimate operational reasons. We aim to preserve user control over account data as described in the Privacy Policy.</LegalSection>
  <LegalSection title="Disclaimers and liability">To the extent permitted by law, Kleenest is provided on an as-available basis without guarantees that all community information is complete or error-free. Nothing in these Terms excludes rights or remedies that cannot legally be excluded.</LegalSection>
  <LegalSection title="Termination and deletion">You may stop using Kleenest at any time and may request account deletion through the in-app or public deletion process. Kleenest may restrict or terminate access for material or repeated violations, fraud, abuse, security threats, or legal requirements.</LegalSection>
  <LegalSection title="Changes">We may update these Terms when the service or applicable requirements change. The effective date above identifies the current version. Continued use after an update is subject to any acceptance flow required for material changes.</LegalSection>
</LegalDocument>}
