import { router } from 'expo-router';
import { useEffect,useState } from 'react';
import { FlatList,Pressable,RefreshControl,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { TrustStrip } from '../components/ConsumerUI';
import { useConsumerTheme } from '../services/theme';
import { getWeekInReview,type WeekInReviewSummary,type WeekInReviewVisit } from '../services/weekInReview';

function visitState(item:WeekInReviewVisit){
  if(item.reviewId)return{label:'REVIEWED',detail:'Your review is already part of the Kleenest evidence for this visit.'};
  if(item.reviewReady)return{label:'VERIFIED · REVIEW READY',detail:'A verified check-in is available and has not been used for a review yet.'};
  if(item.verificationAvailable)return{label:'Presence detected',detail:'Kleenest detected your on-site presence. Verify the visit before the presence window expires to create verified review evidence.'};
  if(item.verified)return{label:'VERIFIED VISIT',detail:'This visit is verified, but there is no unused review opportunity attached to it.'};
  return{label:'Presence detected',detail:'This is visit history, not verified review evidence. The verification window for this stop has ended.'};
}
function when(value:string){const time=new Date(value);return Number.isNaN(time.getTime())?'Recent visit':time.toLocaleString()}

export default function WeekInReviewScreen(){
  const theme=useConsumerTheme();
  const[summary,setSummary]=useState<WeekInReviewSummary|null>(null),[message,setMessage]=useState('Loading your week…'),[loading,setLoading]=useState(false);
  async function load(){if(loading)return;setLoading(true);try{const next=await getWeekInReview(7);setSummary(next);setMessage(next.visits.length?'':'No Kleenest visits in the last 7 days yet.')}catch(error:any){setMessage(error?.message||'Your week could not be loaded.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const rows=summary?.visits||[];
  return <SafeAreaView style={[s.safe,{backgroundColor:theme.canvas}]}><FlatList data={rows} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} keyExtractor={item=>item.visitId} contentContainerStyle={s.list} ListHeaderComponent={<>
    <View style={[s.hero,{backgroundColor:theme.accent}]}><Text style={[s.eyebrow,{color:theme.accentText}]}>YOUR WEEK IN REVIEW</Text><Text style={[s.heroTitle,{color:theme.accentText}]}>Turn recent stops into fresh evidence.</Text><Text style={[s.heroBody,{color:theme.accentText}]}>Presence, verified check-ins and published reviews stay distinct. This recap shows what happened and what you can still contribute.</Text><TrustStrip items={['7-day recap','Presence ≠ verification','One review per verified visit']}/><View style={s.stats}><Stat value={summary?.placeCount||0} label="places" theme={theme}/><Stat value={summary?.verifiedVisitCount||0} label="verified" theme={theme}/><Stat value={summary?.reviewReadyCount||0} label="review ready" theme={theme}/></View></View>
    <View style={[s.boundary,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.boundaryTitle,{color:theme.ink}]}>Trust stays explicit.</Text><Text style={[s.body,{color:theme.muted}]}>A detected visit can remind you where you were, but it does not become verified review evidence until Kleenest has valid visit proof. Dwell can strengthen trust; it never blocks a check-in or review by itself.</Text></View>
    {message?<Text accessibilityLiveRegion="polite" style={[s.message,{color:theme.muted}]}>{message}</Text>:null}
  </>} ListEmptyComponent={<View style={[s.empty,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.cardTitle,{color:theme.ink}]}>{loading?'Refreshing your week…':'Nothing to review yet.'}</Text><Text style={[s.body,{color:theme.muted}]}>Explore nearby restrooms and Kleenest will build this recap from your own account-scoped visit history.</Text>{!loading?<Pressable style={[s.primary,{backgroundColor:theme.accent}]} onPress={()=>router.push('/explore')}><Text style={[s.primaryText,{color:theme.accentText}]}>Explore bathrooms</Text></Pressable>:null}</View>} renderItem={({item})=>{
    const state=visitState(item);const action=item.reviewReady?'Review this visit':item.verificationAvailable?'Verify & review':'Open restroom';
    return <View style={[s.card,{backgroundColor:theme.surface,borderColor:theme.line}]}><View style={s.cardTop}><View style={{flex:1}}><Text style={[s.state,{color:theme.accent}]}>{state.label}</Text><Text style={[s.cardTitle,{color:theme.ink}]}>{item.locationName}</Text></View>{item.reviewId?<Text style={[s.done,{backgroundColor:theme.accentSoft,color:theme.accent}]}>✓ DONE</Text>:null}</View><Text style={[s.meta,{color:theme.muted}]}>{when(item.visitedAt)}</Text><Text style={[s.body,{color:theme.muted}]}>{state.detail}</Text><Pressable accessibilityRole="button" style={[s.action,{borderColor:theme.line,backgroundColor:item.reviewReady||item.verificationAvailable?theme.accent:theme.surfaceRaised}]} onPress={()=>router.push(`/location/${item.locationId}`)}><Text style={[s.actionText,{color:item.reviewReady||item.verificationAvailable?theme.accentText:theme.accent}]}>{action} →</Text></Pressable></View>;
  }}/></SafeAreaView>
}
function Stat({value,label,theme}:{value:number;label:string;theme:any}){return <View style={[s.stat,{backgroundColor:theme.surface}]}><Text style={[s.statValue,{color:theme.ink}]}>{value}</Text><Text style={[s.statLabel,{color:theme.muted}]}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1},list:{padding:20,paddingBottom:44,gap:11},hero:{padding:20,borderRadius:26,gap:8},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.6},heroTitle:{fontSize:30,lineHeight:34,fontWeight:'900'},heroBody:{fontSize:14,lineHeight:21,fontWeight:'700',opacity:.88},stats:{flexDirection:'row',gap:8,marginTop:6},stat:{flex:1,borderRadius:14,padding:10},statValue:{fontSize:20,fontWeight:'900'},statLabel:{fontSize:9,fontWeight:'800',marginTop:2},boundary:{borderWidth:1,borderRadius:18,padding:15,gap:4},boundaryTitle:{fontSize:17,fontWeight:'900'},body:{fontSize:13,lineHeight:20},message:{fontWeight:'700'},card:{borderWidth:1,borderRadius:20,padding:17,gap:7},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:8},state:{fontSize:9,fontWeight:'900',letterSpacing:1},cardTitle:{fontSize:19,fontWeight:'900',marginTop:3},meta:{fontSize:12,fontWeight:'700'},done:{fontSize:9,fontWeight:'900',paddingHorizontal:8,paddingVertical:5,borderRadius:999,overflow:'hidden'},action:{minHeight:48,borderWidth:1,borderRadius:12,paddingHorizontal:13,justifyContent:'center',alignItems:'center',marginTop:3},actionText:{fontWeight:'900'},empty:{borderWidth:1,borderRadius:20,padding:18,gap:7},primary:{minHeight:48,borderRadius:12,paddingHorizontal:14,justifyContent:'center',alignSelf:'flex-start'},primaryText:{fontWeight:'900'}});
